### ISSUE TITLE
Mattermost isn't listed in GNOME's Notifications settings

### ISSUE THREAD

**Issue by echosa** [mattermost/desktop#1006]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Mattermost isn't listed in GNOME's Notifications settings

**Environment**
- Operating System:
- Mattermost Desktop App version: 4.2.1
- Mattermost Server version: 5.10.0

**Steps to reproduce**
- Install Mattermost in Linux with GNOME 3.32.

**Expected behavior**
Mattermost should be listed and available in GNOME's Notifications settings so that users can adjust the notification settings.

**Observed behavior**
Mattermost is neither listed nor available.

![image](https://user-images.githubusercontent.com/133786/61895226-cc484200-aed7-11e9-84ff-127e006bc8ac.png)

Note that both Slack and Discord *are* listed and accessible.

**Comment by amyblais** [comment]
We have a Help Wanted issue open for this: https://github.com/mattermost/desktop/issues/539.

**Comment by echosa** [comment]
@amyblais I think that help wanted issue is a different issue. That one is about the notifications themselves. This isn't about the notifications themselves sticking around and being available. What I'm reporting here is a DE settings issue. In GNOME, if you open the Settings program and go to Notifications, you can individually enable, disable, or change the preferences for notifications for various apps you have installed. That is what is missing: Mattermost is not listed there, so I can't tweak my notifications settings there.

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-17834.

**Comment by echosa** [comment]
Thanks!

**Comment by devinbinnie** [comment]
Closing as I can get it to appear in GNOME settings under Fedora 35. Might need to just have it send a message first.
