### ISSUE TITLE
Long cache of names in Mattermost

### ISSUE THREAD

**Issue by swood** [mattermost/desktop#1010]
Hello.

I have trouble with the cache names in Desktop client. I have a script which changes the last name with absence status, like "Out of office". it helps us to clearly understand that this employe now absents and why.
My script changing the last name via API with the patch method. All works fine. But if the computer with Mattermost client is offline when the script has been worked, old name displaying. How could I ask the client to force drop their own cache when I am patching users?
Or maybe I could disable cache on the client-side?

**Comment by hmhealey** [comment]
Hi @swood. What version of the Mattermost server are you using? We've made some recent improvements to have clients reload any updated users when Mattermost reconnects, but they might not be on the version you're using

**Comment by swood** [comment]
hi @hmhealey.
Thank you for your answer. My current server version is 5.12.0 but my issue grows since version 5.6 or something like that.
In which version you have done your improvements and how could I check it?

**Comment by hmhealey** [comment]
I just double checked, and the fix actually hasn't been released yet. It should be fixed in 5.14 which is scheduled for release on August 16th.
