### ISSUE TITLE
Internal domains for Team Server fail URL validation

### ISSUE THREAD

**Issue by norbertwenzel** [mattermost/desktop#1018]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

The team server URL validation marks internal domains (eg. `https://mattermost.company-internal`) as invalid.

**Environment**
- Operating System: Win7
- Mattermost Desktop App version: 4.2.3, 4.3.0a
- Mattermost Server version: 5.12.4

**Steps to reproduce**
 - Setup new team server and use the an internal domain name (which is resolved successfully using eg. `nslookup`).
 - Another way to reproduce is to upgrade from MM Desktop 4.2.1 to 4.2.3, where 4.2.1 already uses the internal domain name. 4.2.3 (and 4.3.0a) seem to interpret the URL as invalid and open up with the "add new team server" screen after the update.

**Expected behavior**
URL should be accepted as a valid (although internal) team server URL.

**Observed behavior**
URL validation fails. (Sorry, I already downgraded to 4.2.1 again, so I cannot reproduce the exact error message just now. If you need the exact error message or a screenshot just let me know and I'll switch MM versions again.

The team URL works as expected when entered into a current Chrome release.

**Possible fixes**

---
I've searched your issues and found some validation related tickets, but none specifically mentioning team server URL validation with internal domain names. Please feel free to close this as duplicate if you think this issue should be merged with one of the other validation related tickets.

**Comment by tschlue** [comment]
I can confirm this issue. Our Url is like: http://serverXY/mattermost

**Comment by amyblais** [comment]
Ticket for reference: https://mattermost.atlassian.net/browse/MM-17837.

**Comment by nlowe** [comment]
FYI we're also seeing this for URL's linked elsewhere in the UI (in messages / the channel header), not just the Server URL. This feels like a breaking change to me, is it related to the security update shipped in 4.2.3?

**Comment by amyblais** [comment]
@deanwhillier Can you help take a look if this is related to 4.2.3?

**Comment by deanwhillier** [comment]
@amyblais, will have a look today.

**Comment by norbertwenzel** [comment]
@deanwhillier Does merging #1000 mean this can be closed now?

**Comment by deanwhillier** [comment]
Yes, thanks for the reminder! Merging #1000 should address this issue, so closing.

**Comment by norbertwenzel** [comment]
Thank you.

**Comment by norbertwenzel** [comment]
Just for your information: Tested with 4.3.0-rc1 and it works on our internal server again. Thank you.
