### ISSUE TITLE
WiFi with captive portal causes a lot of popups about invalid certificate

### ISSUE THREAD

**Issue by astax-t** [mattermost/desktop#1019]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Repeated popups asking whether I want to accept certificate 

**Environment**
- Operating System: Ubuntu Linux 16.04
- Mattermost Desktop App version: 4.2.3
- Mattermost Server version: 5.12.0

**Steps to reproduce**
- Have the app connected to a MM server on a non-restricted network
- Disconnect from the network
- Connect to a wifi AP with captive portal

I'm not sure if relevant, but this is own instance of MM installed in company intranet, directly accessible from outside.

I also cannot confirm whether this is actually due to captive portal or the wifi network uses some other network restrictions (this happens on onboard wifi in trains in the UK, if this helps)

**Expected behavior**
- The app sits tight and waits for a connection to be established OR
- Shows a non-modal notification that certificate is not valid AND waits for it to get fixed

**Observed behavior**
A series of popups asking whether I want to accept a certificate are shown. And new popups appear every 10-30 seconds, potentially causing a stack of tens or even hundreds of modal popups.

![Selection_010](https://user-images.githubusercontent.com/2169470/62857192-e4e59400-bcee-11e9-86af-36846ac670e2.png)

Possibly related issues:
https://github.com/mattermost/desktop/issues/569
https://github.com/mattermost/desktop/issues/894

**Possible fixes**

**Comment by amyblais** [comment]
Ticket for reference: https://mattermost.atlassian.net/browse/MM-17835.

**Comment by Willyfrog** [comment]
this should be fixed by https://github.com/mattermost/desktop/pull/1240

closing, feel free to reopen if the issue persists in the new versions
