### ISSUE TITLE
URL is not formatted correctly.

### ISSUE THREAD

**Issue by kagari2613** [mattermost/desktop#1023]
#### url that end of 'x', e.g. 'www.example.x' is not  formatted correctly. why you limit me to input any urls through it is not correct . it's just my fault,and this program need to do what's just only remind me the url maybe incorrect,but couldn't limit me to add it, that's enough!

**Comment by bunower** [comment]
Same Here, we have an own proxy and DNS-Server. Our chat Domain domain is: https://chat.w9s

**Comment by pfeiferbit** [comment]
As a workaround you could use the IP `http://12.34.56.78/`, possibly with a certificate warning if HTTPS is used.

**Comment by Elvaron** [comment]
Same issue here, no TLD just an internal DNS name, so e.g. http://foo-bar:8065 for the name and port
