### ISSUE TITLE
Tabs in chat window

### ISSUE THREAD

**Issue by laitkor** [mattermost/desktop#1028]
Tabs in the chat window may provide more help with the navigation.  This can help to remember to whom we chat previously.

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @laitkor 

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review.

**Comment by amyblais** [comment]
I'll close this for now as we haven't received feedback on this, but I hope you will open a feature request issue for this,
