### ISSUE TITLE
Error while going back in history

### ISSUE THREAD

**Issue by Shlizer** [mattermost/desktop#1033]
- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Environment**
- Operating System: Linux Ubuntu 18, Windows 10 (i belive also on Mac, but didn't test it)
- Mattermost Desktop App version: 4.2.1
- Mattermost Server version: 5.14.2

---

**To reproduce:**
- try to open any link in new window (middle mouse button on eg. 'help' link or open console)
- in new window go to any other page (eg. in console choose something in menu)
- go to History -> Back
- enjoy error message =p

Error message for easier debugging:

Application: Mattermost 4.2.1
Platform: Linux 4.15.0-62-generic x64
TypeError: focusedWindow.goBack is not a function
    at click (/opt/Mattermost/resources/app.asar/main_bundle.js:12806:25)
    at MenuItem.click (/opt/Mattermost/resources/electron.asar/browser/api/menu-item.js:55:9)
    at Function.executeCommand (/opt/Mattermost/resources/electron.asar/browser/api/menu.js:29:13)

**Possible fixes**
- disable History on other pages than main window, use other history.back fn on child windows etc.

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-18630.

**Comment by amyblais** [comment]
Closing as this is fixed for the upcoming v4.3 release. v4.3 release is currently scheduled for October 16th,
