### ISSUE TITLE
Desktop Notification is not working

### ISSUE THREAD

**Issue by bitdessert** [mattermost/desktop#1036]
I confirm (by marking "x" in the [ ] below: [x]):

- [ ] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [ ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

I minimize the application(mattermost desktop) and click desktop notification, but it will not run.

**Environment**
- Operating System: windows 10, windows 7, macOS(It runs but there is an error, eg. EnhancedNotification is not loaded.)
- Mattermost Desktop App version: 4.2.3 
- Mattermost Server version: 5.14.2 

Earlier versions worked as expected.(eg. mattermost desktop version 4.2.1)

**Steps to reproduce**
1. Someone minimizes the app.(on windows)
2. Send a message to someone from another pc.
3. Then, Someone was notified.
4. Someone click desktop notification
5. But, nothing happens.

**Expected behavior**
When someone clicks Desktop Notification, the app should launch.

**Observed behavior**

**Possible fixes**

**Comment by amyblais** [comment]
@bitdessert We have this ticket open: https://mattermost.atlassian.net/browse/MM-18131. Let me know if this sounds like the same issue you're seeing.

**Comment by bitdessert** [comment]
Yes.
So when can I install version 4.3?

Version 4.2.3 has other issues too.
eg. If terminate and launch the App(mattermost-desktop) in a Windows 10, the session may expire.

**Comment by bitdessert** [comment]
Perhaps this problem is related to 'webPreferences.contextIsolation'.

**Comment by deanwhillier** [comment]
This issue should be fixed by this PR: https://github.com/mattermost/desktop/pull/1040

**Comment by amyblais** [comment]
Closing as this is fixed for the upcoming v4.3 release. v4.3 release is currently scheduled for October 16th,
