### ISSUE TITLE
Crash on startup with 4.3.0-develop-2762

### ISSUE THREAD

**Issue by StackKorora** [mattermost/desktop#1038]
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Error with 4.3.0-develop-2762 on Lubuntu 18.04.

**Environment**
- Operating System:  Lubuntu 18.04
- Mattermost Desktop App version: 4.3.0-develop-2762
- Mattermost Server version: 5.13.3

**Steps to reproduce**
```
$ sudo dpkg -i mattermost-desktop-4.3.0-develop-linux-amd64.deb 
$ mattermost-desktop 
config.autostart has been configured: true
Gtk-Message: 19:12:26.888: GtkDialog mapped without a transient parent. This is discouraged.
/opt/Mattermost/resources/app.asar/main_bundle.js:8388
    throw err;
    ^

TypeError: Cannot read property 'origin' of undefined
    at isTrustedURL (/opt/Mattermost/resources/app.asar/main_bundle.js:879:19)
    at WebContents.<anonymous> (/opt/Mattermost/resources/app.asar/main_bundle.js:571:35)
    at WebContents.emit (events.js:194:13)

```
**Expected behavior**
Mattermost Desktop starts up without an error.

**Observed behavior**
Mattermost throws the above error. If you click on the option for more details it just says the same thing really.
```
Application: Mattermost 4.3.0-develop
Platform: Linux 4.15.0-62-generic x64
TypeError: Cannot read property 'origin' of undefined
    at isTrustedURL (/opt/Mattermost/resources/app.asar/main_bundle.js:879:19)
    at WebContents.<anonymous> (/opt/Mattermost/resources/app.asar/main_bundle.js:571:35)
    at WebContents.emit (events.js:194:13)
```
**Possible fixes**
I don't have any at this time. However, it is worth noting that I have only two Lubuntu 18.04 systems. It installed and works just fine on one but not the other. There is a pretty big difference in terms of software/setup/hardware on the two of them, so I don't have leads at this time to why one worked and one did not.

I also uninstalled and purged the package and installed fresh. No difference. I reinstalled 4.2.3-79 and it works just fine.

**Comment by deanwhillier** [comment]
Thanks for the report @StackKorora! Any chance you could provide me with the server URL's you have setup? Here if you don't mind, or more privately by DM'ing me on https://community.mattermost.com if you prefer? @deanwhillier

**Comment by StackKorora** [comment]
Greetings,
Sorry for the long response time. I've been traveling for work and didn't always have decent internet access. I just got home and installed 4.3.0-rc5-3227. So far it has worked across every device! Whoo!
Not sure what fixed it though.
Thanks for the response and the work on Mattermost. It is much appreciated!
