### ISSUE TITLE
Alt+Shift opens menu on Cinnamon desktop environment

### ISSUE THREAD

**Issue by ddrozdov** [mattermost/desktop#104]
Alt+Shift is a common hotkey for switching keyboard layouts, but pressing it in a Linux client opens a `File` menu. Please fix.

**Comment by yuya-oc** [comment]
In my side, Alt+Shift doesn't open the menu.

- Ubuntu 14.04: Unity
- Antergos Linux: GNOME 3.18.2

Maybe I can't fix this. And have to read codes of Electron and Chromium. Could you tell me your distro and desktop environment for reference?

**Comment by ddrozdov** [comment]
I'm running Linux Mint 17.3 Rosa with Cinnamon 2.8.6.

**Comment by yuya-oc** [comment]
Reproduced on Linux Mint 17.3 Rosa with Cinnamon 2.8.6.
Then I tested some Electron-based apps.
- Atom 1.6.2: OK
- VS code 0.10.11: OK

**Comment by ddrozdov** [comment]
Found a similar bug report in another Electron-based app: https://github.com/RocketChat/Rocket.Chat.Electron/issues/50

Seems they've fixed it in some trivial but not obvious way.

**Comment by yuya-oc** [comment]
Thanks, it seems that the leading '&' fixes the issue. Besides, Atom also uses it.
Unfortunately I don't know why it's fixed.
