### ISSUE TITLE
Unqualified hostnames are no longer accepted

### ISSUE THREAD

**Issue by nomis** [mattermost/desktop#1045]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Using a URL with an unqualified hostname like http://example/ no longer works.

**Environment**
- Operating System: Windows 10
- Mattermost Desktop App version: 4.2.3

It is not possible to change the hostname used to connect to Mattermost.

**Steps to reproduce**
Try to add the URL http://example/

**Expected behavior**
The client connects to hostname "example" using the configured DNS search domains. This works with 4.2.1 and earlier versions.

**Observed behavior**
The client considers "http://example/" to be an invalid URL and will not connect.

**Comment by amyblais** [comment]
This is fixed with https://github.com/mattermost/desktop/pull/1000 for v4.3,
