### ISSUE TITLE
[DOC] Linux setup

### ISSUE THREAD

**Issue by baptistedonaux** [mattermost/desktop#105]
The documentation doesn't explain the best way to install ```mattermost-desktop``` on Linux distributions. Run ```Mattermost``` executable into folder downloaded can be improve (Gnome sidebar integration per example).

**Comment by yuya-oc** [comment]
I'm not familiar at such integration for Linux desktop environment.

**Comment by emerham** [comment]
Really just needs a .desktop (https://wiki.archlinux.org/index.php/Desktop_entries) file to be dumped into /usr/local/share/applications/ then the icon and that is about it. A quick make file could place such files in their correct folder.

**Comment by baptistedonaux** [comment]
@emerham Make a desktop launcher can be a solution but I think that package Mattermost desktop in .deb package can improve the setup proccess.

@yuya-oc [electron-builder](https://www.npmjs.com/package/electron-builder) is really to use. I build with success an personal electron app ([deezer desktop for linux](https://github.com/baptistedonaux/deezer-desktop-linux) ).

**Comment by yuya-oc** [comment]
@baptistedonaux Thanks! I will consider it.

**Comment by yuya-oc** [comment]
.deb packages will be add at v1.2.0. However, .desktop file is reft.

**Comment by baptistedonaux** [comment]
Super green ! Thanks for your job !
