### ISSUE TITLE
Auto Suggest Hashtags

### ISSUE THREAD

**Issue by cjk02025** [mattermost/desktop#1055]
It would be really convenient / efficient if mattermost would auto-suggest hashtags in the same way that @user auto-suggests users...

**Comment by amyblais** [comment]
@cjk02025 Please suggest features in the Mattermost feature idea forum so it can be discussed, upvoted and considered for a [https://mattermost.uservoice.com](https://mattermost.uservoice.com/forums/306457-general?category_id=159795).

You get 10 votes in the feature idea forum, and each one influences the future of the project.

**Comment by amyblais** [comment]
I'll close this for now as we haven't received feedback on this, but I hope you will open a feature request issue for this,
