### ISSUE TITLE
osx client missing double and single quotes

### ISSUE THREAD

**Issue by gitthismoney** [mattermost/desktop#107]
Hello,

When I type ' or " in mattermost osx I get `&#39;` and `&quot;`

Has anyone else noticed this or is it just me?

Thanks!

<img width="291" alt="screen shot 2016-04-07 at 6 40 05 pm" src="https://cloud.githubusercontent.com/assets/404807/14371851/58979618-fcf0-11e5-92be-ed187f5a189f.png">

**Comment by yuya-oc** [comment]
Not reproduced, and I have never heard that issue.

* OS X: 10.11.3
* mattermost-desktop: 1.1.0
* mattermost-server: 2.0.0 and 2.1.0

**Comment by gitthismoney** [comment]
it's doing it for me in Firefox and Chrome as well

**Comment by GhostLyrics** [comment]
If you can reproduce the issue outside of mattermost-desktop then it is probably not an issue of mattermost-desktop. Consider checking your matter most server or opening an issue with mattermost-platform.

**Comment by yuya-oc** [comment]
Right. The app can't fix issues which are reproduced on web browsers. The problem is probably caused by html/js/css served by mattermost-server
