### ISSUE TITLE
client needs to remember credentials

### ISSUE THREAD

**Issue by 2019-05-10** [mattermost/desktop#1074]
the client needs to remember credentials
i have a never-ending session (computer hibernates usually, no reboots), but mattermost nevertheless likes to unpredictably destroy my sessions, even if i communicated in that very session an hour ago or so.
when that happens i have to look up the credentials again, because the client does not store them

**Comment by amyblais** [comment]
@2019-05-10 Would you be open to trying these troubleshooting steps: https://docs.mattermost.com/install/desktop.html#desktop-app-constantly-asks-to-log-in-to-mattermost-server?

**Comment by 2019-05-10** [comment]
@amyblais I considered that already, but while "Cookies" and "Cookies-journal" is somewhat self-explanatory, I don't know what "IndexDB" is used for ("DB" always rings a warning bell), and thus did not like to delete it. A short explanation _what_ those files contain and why it is safe (or not? Should I make a backup?) to delete them, would probably improve the entry.

**Comment by 2019-05-10** [comment]
Any progress on this?
Just about 15 minues ago I posted a message, and about 5 minutes later Mattermost popped up a message about my connection being expired and needing to log in again.

I don't understand, what's so difficult about storuing credentials and offering them for the next login.
If for "security issues": keeping a post-it with credentials on my monitor ist not necessarily a better solution, but obviously the more reliable one.

Even better, if maybe unrelated, Mattermost should sensibly keep track of a session -- it's inexplicable that a session should timeout just minutes after the last activity.

**Comment by 2019-05-10** [comment]
This is getting ridiculous!
Is it really that difficult to either check the timeout or at least provide a credentails manager??

**Comment by Willyfrog** [comment]
@2019-05-10 if you try on the browser, does it store the credentials or is it also asking for them? I'm wondering as it might be a server configuration issue.

What kind of authentication method are you using?

**Comment by 2019-05-10** [comment]
See initial post - I am using the client.
Brwoser nowaday have a decent password management that would at least mitigate the issue.

**Comment by Willyfrog** [comment]
hi! I understand it might be frustrating sometimes, but I don't think it is secure that the desktop stores the credentials. I'd happily create a ticket if there was a secure way to do it (feel free to suggest if you know of one)

Maybe using a password manager might aleviate your issue? I use one for quite some time and it helps with all the hassle of having to log into sites as well as the desktop

**Comment by 2019-05-10** [comment]
Would it be possible to plug in KeePassXC or such?

**Comment by Willyfrog** [comment]
I'm afraid I don't use keepassxc, so I'm not sure what would be needed to integrate, but if you know how it works, a PR for such a feature would be great :)

**Comment by devinbinnie** [comment]
Closing as inactive.

**Comment by 2019-05-10** [comment]
What sort of "avctivity" am I supposed to provide?
Frequently asking whether there's any progress?

Please reopen and do not indiscriminately close tickets w/o asking the OP.
