### ISSUE TITLE
client's new message notification does not disappear reliably from systray icon

### ISSUE THREAD

**Issue by 2019-05-10** [mattermost/desktop#1075]
-    systray icon signals new message(s) by showing a fat black dot
-    open client and read message
-    close client
    dot is still there
-    open again
-    switch to another channel and back
    dot finally disappears

it does not happen always but very often, so often in fact as to render the "new message" notification almost useless, since I can never tell whether there's really a new message or just the systray icon hasn't been reset after reading the last message.

**Comment by amyblais** [comment]
@2019-05-10 What desktop app version are you currently using?

**Comment by 2019-05-10** [comment]
Package: mattermost-desktop
Status: install ok installed
Priority: extra
Section: default
Installed-Size: 184845
Maintainer: Mattermost, Inc. <feedback@mattermost.com>
Architecture: amd64
Version: 4.2.3-79
Depends: gconf2, gconf-service, libnotify4, libappindicator1, libxtst6, libnss3, libxss1
Description: Mattermost
  Mattermost
License: Apache-2.0
Vendor: Mattermost, Inc. <feedback@mattermost.com>
Homepage: https://about.mattermost.com

**Comment by amyblais** [comment]
What OS and version are you on? Would you be open to help test if you see the same issue on v4.3 desktop app version?

**Comment by 2019-05-10** [comment]
Debian/SID
Installed, 4.3.1, didn't start, 4.3.0 neither:
 XDG_CURRENT_DESKTOP=Unity /opt/Mattermost/mattermost-desktop %U
[13022:1028/123918.121907:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Mattermost/chrome-sandbox is owned by root and has mode 4755.

**Comment by devinbinnie** [comment]
Closing as inactive
