### ISSUE TITLE
[Feature] Minimize to tray on Windows 10

### ISSUE THREAD

**Issue by mjekovec2** [mattermost/desktop#108]
Currently there is no way to minimize application to tray without it also appearing in task bar. Also tried combination with rbtray (http://rbtray.sourceforge.net/) but does not work (works only the first time you minimize).

**Comment by lfbrock** [comment]
This also doesn't work on OS X right now - it would be great to get minimize and other standard keyboard shortcuts such as close window and hide window working.

**Comment by melekhove** [comment]
@mjekovec2 , In case if you're able to build from sources it (which is easy thanks to npm) you can make quick and dirty hack contained in the following diff.
[hide.diff](https://github.com/mattermost/desktop/files/222139/hide.txt)

I came here to find solution but eventually did it for myself (google helps :smile:  ).

**Comment by mjekovec2** [comment]
Hi,

it seems it works. I also made some additions (like a special menu 
option to select/deselect this behaviour). It is only limited to 
Windows, but if someone is interested, I can fork it/provide tha patch.


Best,

M

On 16. 04. 2016 12:49, Eugene Melekhov wrote:
>
> @mjekovec2 <https://github.com/mjekovec2> , In case if you're able to 
> build from sources it (which is easy thanks to npm) you can make quick 
> and dirty hack contained in the following diff.
> hide.diff <https://github.com/mattermost/desktop/files/222139/hide.txt>
>
> I came here to find solution but eventually did it for myself (google 
> helps :smile: ).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/mattermost/desktop/issues/108#issuecomment-210788501>
>

-- 
podpis
*Matija Jekovec*
Executive Director
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
. . . . . . . . . . . . .
t: 01 77 77 877
g: +386 41 375 541
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
. . . . . . . . . . . . .
Spletna agencija Klaro d.o.o. <https://www.klaro.si>
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
. . . . . . . . . . . . .
Klaro spletna agencija d.o.o.
www.klaro.si <https://www.klaro.si>

**Comment by obones** [comment]
Hello,

Could you attach the diff here?

Thanks

**Comment by revondage** [comment]
it's funny i can't get my desktop github works, all the other apps works 100%. some suggestions/help?

**Comment by Razzeee** [comment]
I'm not sure what your trying to say. Can you explain it in another way? Maybe with steps, what your doing?

**Comment by revondage** [comment]
@Razzeee i open "rbtray", then right-click on the Minimize icon, (read the README file), but my  GitHub Desktop app don't go to the tray :(

**Comment by jasonblais** [comment]
Thanks @revondage for the report -- which operating system (Windows, OS X/Mac, Linux) are you using?

On Windows, if you minimize the app, it should go to the taskbar. 

If you close the app (either by clicking "X" on the top-right corner of the app, or by pressing `ALT+F4`), the app will only remain in the system tray, which I think you want to accomplish.

**Comment by Razzeee** [comment]
Forget about rbtray (http://rbtray.sourceforge.net/) for mattermost it should work out of the box as @jasonblais said.
So don't rightclick the tray icon, just hit the X on the window.

**Comment by revondage** [comment]
i tried that but nothing seemed to work. i'm working on Win10 Pro Anniv Ed.

**Comment by jasonblais** [comment]
@revondage What happens if you click on the X? It just minimizes to the taskbar?

Maybe it's an issue in Win10 Pro Anniv Ed?

![image](https://cloud.githubusercontent.com/assets/13119842/17749301/122aec9a-648b-11e6-870e-63d38722cde6.png)

**Comment by revondage** [comment]
Just closes :( i tried on my work's PC, Win10 Pro (no Anniv Ed). Same issue. Right-clicked in the 3 window icons, minimized, closed. But nothing seems to work :(

**Comment by Razzeee** [comment]
Are you absolutely sure your on certain 1.3.0?

**Comment by mjekovec2** [comment]
Yes. We just upgraded server to 3.2 and i'll test it tommorow

**Comment by jasonblais** [comment]
Thanks @mjekovec2 and @revondage! Please also make sure that you are using Desktop App v1.3, which was released last month and [can be downloaded here](https://about.mattermost.com/downloads/).

Previous versions of the desktop app only minimized the app.

**Comment by revondage** [comment]
i just reinstalled (i know kinda dumb) and now it's working.

**Comment by jasonblais** [comment]
Great to hear! Thanks for reporting and coming back that the issue is resolved.

@mjekovec2 and @revondage, if you'd like, it would be great to see you join our [Desktop community](https://pre-release.mattermost.com/core/channels/desktop-app) channel as well, if you're not there already.
