### ISSUE TITLE
Lock file out of sync

### ISSUE THREAD

**Issue by kethinov** [mattermost/desktop#1082]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

When doing development against the app, `npm ci` will fail.

**Environment**
- Operating System: all
- Mattermost Desktop App version: latest master
- Mattermost Server version: not relevant

**Steps to reproduce**

1. Fork project.
2. Clone project.
3. `npm ci`

**Expected behavior**

Should be able to install dependencies using `npm ci`.

**Observed behavior**

```
> npm ci
npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR!
npm ERR!
npm ERR! Invalid: lock file's electron-builder@20.44.4 does not satisfy electron-builder@^21.2.0
```

**Possible fixes**

Generate a new lock file by running `npm i` and commit it to master.

**Comment by devinbinnie** [comment]
Closing as this no longer reproduces.
