### ISSUE TITLE
Tilde ~ not working anymore - German Keyboard Layout

### ISSUE THREAD

**Issue by th-joerger** [mattermost/desktop#1084]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Tilde [~] used for strike-through is not generated anymore when pressing Alt Gr and + on German keyboard.

**Environment**
- Operating System: Win 10 x64 Enterprise - 10.0.17134 Build 17134
- Mattermost Desktop App version: 4.2.3
- Mattermost Server version: 5.14.2

**Steps to reproduce**
Make sure you have German keyboard layout and press Alt Gr and + to input ~ character. (Does not matter if in Edit Post or directly in chat window.)

**Expected behavior**
Alt Gr and + should input ~ character.

**Observed behavior**
Focus is switching between multiple parts of the window.

**Possible fixes**
None

**Work around**
At the moment, I have to input the tilde character in another window and copy paste it to Mattermost to be able to strike text. This is very frustrating and inconvienient.

**Comment by HighwindProject** [comment]
Same Problem here with Desktop App version: 4.2.1

**Comment by amyblais** [comment]
Opened a bug ticket here: https://mattermost.atlassian.net/browse/MM-19659.

**Comment by esethna** [comment]
Hi @th-joerger @HighwindProject can you please upgrade to v5.15 or later and this issue should be fixed

**Comment by th-joerger** [comment]
@esethna Thanks for the update!
[The commit in question, for those interested](https://github.com/mattermost/mattermost-webapp/pull/3636)
