### ISSUE TITLE
Switch  `simple-spellchecker` for `electron-spellchecker`.

### ISSUE THREAD

**Issue by deanwhillier** [mattermost/desktop#1085]
Replace current `simple-spellchecker` with [`electron-spellchecker`](https://www.npmjs.com/package/electron-spellchecker) to utilize Google Chrome’s included dictionaries. Strip out any unnecessary code and files related to `simple-spellchecker` and remove the package.

Implementation should integrate with the settings and user preferences for the existing `simple-spellchecker` where possible and should build and package for all supported OS’s.

Once complete, CI should be updated as needed to support this new package.

**Comment by keithcruz** [comment]
Hi @deanwhillier I would like to work on this.

**Comment by deanwhillier** [comment]
That's great, thanks so much @keithcruz! 🎉

**Comment by borisyurkevich** [comment]
Why we have to use electron spell checker or custom spell checker, why can't we use system spell checker form MacOS? It can be activated with `command + shift + ;`. Is this Electron limitation? 
Thank you.

**Comment by devinbinnie** [comment]
Closing as we now integrate with the spellchecker provided by Electron.
