### ISSUE TITLE
Hit ESC key to close the sidebar opened when I reply a message.

### ISSUE THREAD

**Issue by nickolasdeluca** [mattermost/desktop#1087]
When I reply to a message, a sidebar opens with that message's details and a inputbox to reply said message.

What I want is that after I reply to the message I wanted, I would be able to hit ESC to close the sidebar without having to use my mouse.

It's a simple enhancement, but it would improve day-to-day usage a lot!

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @nickolasdeluca,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by nickolasdeluca** [comment]
turns out someone already suggested a shortcut to close the RHS.

If someone wants to contribute, here is the link:
[keyboard shortcut to close the right hand sidebar rhs](https://mattermost.uservoice.com/forums/306457-general/suggestions/16821268-keyboard-shortcut-to-close-right-hand-sidebar-rhs‬)

**Comment by amyblais** [comment]
Thank you, I'll close this issue here and we can follow the progress in the future request forum,
