### ISSUE TITLE
Zoom in/out doesn't work in 4.3.1

### ISSUE THREAD

**Issue by hlavki** [mattermost/desktop#1091]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Zoom in/out does not work in 4.3.1 and Linux

**Environment**
- Operating System: openSUSE Tumbleweed
- Mattermost Desktop App version: 4.3.1
- Mattermost Server version: 5.15.0

**Steps to reproduce**
Open application and try to zoom in/out

**Expected behavior**
Zoom in/out works

**Observed behavior**
Zoom in/out do nothing

**Comment by amyblais** [comment]
Hi @hlavki, this is a known issue that we are actively working on fixing for a dot release: https://docs.mattermost.com/help/apps/desktop-changelog.html.

**Comment by hlavki** [comment]
Hi @amyblais, thanks for info. I think we can close this issue.
