### ISSUE TITLE
/opt/Mattermost/chrome-sandbox permission is wrong

### ISSUE THREAD

**Issue by cielavenir** [mattermost/desktop#1094]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

/opt/Mattermost/chrome-sandbox permission is wrong

**Environment**
- Operating System: Linux (deb package)
- Mattermost Desktop App version: 4.3.1
- Mattermost Server version: 5.16.0

**Steps to reproduce**

just `$ mattermost-desktop `

**Expected behavior**

mattermost should startup.

**Observed behavior**

```
[11150:1028/105800.194222:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Mattermost/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap
```

**Possible fixes**

Set permission properly

**Side note**

Launching from applications menu has the same situation: `sudo chmod 4755 /opt/Mattermost/chrome-sandbox` fixes the issue.

**Comment by wget** [comment]
@cielavenir Hi there. Thanks for this bug report. Do you mean that if you run the following command, the binary `chrome-sandbox` is reported as having the sticky bit enabled? If this is true this can cause security concerns and a potential privilege escalation in the event there is a feature/bug present in chrome-sandbox that could trigger some nasty actions.

```
# find /opt/Mattermost/ -type d -perm -1000 -exec ls -ld {} \;
```

I checked on my side and the package is not at risk on Arch Linux :) Nothing is reported by
```
# find /usr/share/webapps/ -type d -perm -1000 -exec ls -ld {} \;
```

**Comment by cielavenir** [comment]
I checked and I don't see sticky bit.

I suppose mattermost-desktop is just created under 0755 and needs to be changed to 4755.

**Comment by cielavenir** [comment]
https://github.com/mattermost/desktop/issues/1101#issuecomment-549241692

**Comment by devinbinnie** [comment]
Closing as this is now fixed.
