### ISSUE TITLE
There is no way to permanently accept invalid certificates in the client

### ISSUE THREAD

**Issue by rustyscottweber** [mattermost/desktop#1096]
Currently, users are allowed to bypass the warnings about certificate errors while opening mattermost or connecting to a mattermost server.  It should be really low hanging fruit, so to speak, to allow an additional option to permanently add the certificate error so that the warning doesn't show up every time mattermost is opened.

**Comment by amyblais** [comment]
Thank you for opening a feature suggestion for this https://mattermost.uservoice.com/forums/306457-general/suggestions/38912248-allow-certificate-errors-to-be-permanently-ignored.
