### ISSUE TITLE
Option to disable spell checking

### ISSUE THREAD

**Issue by mtgrosser** [mattermost/desktop#1098]
Currently, spell checking is always enabled and cannot be disabled.

To some users, the red underlining is visually distracting. Also, the spell checker is currently unable to detect on-the-fly, in-sentence language switching, which is sometimes used in mixed-language teams or when discussing mixed-language subjects (like programming).

Therefore, I'd like to suggest adding an option to permanently disable spell checking - either in the configuration, or, in the input bar's context menu, where the spell check language is usually selected.

![spellcheck](https://user-images.githubusercontent.com/1374413/67931185-aa8ae500-fbc1-11e9-920e-8dab512119a0.png)

**Comment by amyblais** [comment]
@mtgrosser Would you be open to sharing this on our feature idea forum here https://mattermost.uservoice.com/forums/306457-general? If you're interested in implementing this, please let us know.

**Comment by mtgrosser** [comment]
I added it here: https://mattermost.uservoice.com/forums/306457-general/suggestions/38938567-option-to-disable-spell-checking

Regarding implementation, I'll first have to make myself familiar with the codebase in order to tell whether I could do it.

**Comment by amyblais** [comment]
Thank you for opening a feature request for this!
