### ISSUE TITLE
dmg background image does not display

### ISSUE THREAD

**Issue by bitdessert** [mattermost/desktop#1099]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

I can't see the background image of a dmg file.

**Environment**
- Operating System: macOS 10.14.5
- Mattermost Desktop App version: 4.3.1 
- Mattermost Server version: 5.16.1 

**Steps to reproduce**
1. Download the mattermost from below URL
https://releases.mattermost.com/desktop/4.3.1/mattermost-desktop-4.3.1-mac.dmg
2. Click the mattermost-desktop-4.3.1-mac.dmg

**Expected behavior**
The image set in the electron-builder.json should be displayed.
![image](https://user-images.githubusercontent.com/42505950/67932560-789c7180-fc07-11e9-8382-0d3390aa9098.png)

**Observed behavior**
The image set in the electron-builder is not displayed.
Even the icon size did not apply.

![image](https://user-images.githubusercontent.com/42505950/67932382-25c2ba00-fc07-11e9-8537-df06cf68e069.png)

**Possible fixes**
It is probably associated with the electron-builder version.
In the 20.44.4 version of electron-builder, the background image is visible.

**Comment by amyblais** [comment]
A ticket was opened here: https://mattermost.atlassian.net/browse/MM-20348.

**Comment by amyblais** [comment]
Closing as this is fixed for upcoming v4.4 release,
