### ISSUE TITLE
Windows App showing white/blank screen

### ISSUE THREAD

**Issue by boschkundendienst** [mattermost/desktop#1100]
- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: `Windows 10 Version 1903 (OS Build 18362.418)`
- Mattermost Desktop App version: `4.3.1`
- Mattermost Server version: `mattermost-team-5.16.0-linux-amd64.tar.gz`

**Steps to reproduce**
Setup Mattermost client to autostart. After login and startup of everything, Mattermost Window is white like this:

![2019-10-31_10h03_41](https://user-images.githubusercontent.com/2026234/67933536-461e5480-fbc6-11e9-9a91-901348fafe7f.png)

**Expected behavior**

Mattermost should just display what it shows it the title bar.

**Observed behavior**

When opening `View -> Developer Tools for Application Wrapper` (Ctrl+Shift+I), the developer tools show on the right hand side and immediately on the left the usual content arrives. I close the Developer toolbar and everything is fine. This happens only when my computer is started up after login (where many other things start also).

So it seems that all the other startups that are going on somehow prevent this first, initial screen refresh within the application.

I connect to a self-hosted Mattermost server with GitLab authentication where my authentication is still valid when I startup the client.

Problem does not happen, when closing Mattermost and manually start it then.

**Possible fixes**

Maybe do another screen refresh after certain amount of time after the application startup?

**Comment by amyblais** [comment]
Closing as a duplicate,
