### ISSUE TITLE
Click a link in app does not open page in browser

### ISSUE THREAD

**Issue by braineo** [mattermost/desktop#1101]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Click a link in app does not open page in browser

**Environment**
- Operating System: Debian 9.0
- Mattermost Desktop App version: 4.3.1 
- Mattermost Server version: 5.16.1 

**Steps to reproduce**
Send a link https://google.com
Click the link

**Expected behavior**
Open a new page in browser

**Observed behavior**
Nothing happens: no jump within app nor to browser

**Possible fixes**

**Comment by deanwhillier** [comment]
Hi @braineo, thanks for filing the report!

Couple quick questions if you are able so we can triage this properly:
1. Can you open up the dev tools for the tab in question and see if there are any console errors along the lines of `Untrusted URL blocked: https://google.com/`?
2. Can you inspect the anchor tag that is generated for the link using dev tools and see if there is a `target="blank"` attribute on the tag?

Thanks!

**Comment by braineo** [comment]
Hi @deanwhillier Thanks! I'll check and get back to you.

**Comment by braineo** [comment]
hi @deanwhillier 

1. Exactly: `Untrusted popup window blocked: https://google.com/`
2. Element of the link is 
```html
<a class="theme markdown__link" href="https://google.com/" rel="noreferrer" target="_blank">https://google.com/</a>
```

**Comment by hannu78** [comment]
This is what I get in Debian 10 and mattermost-desktop 4.3.1 after starting mattermost-desktop binary from terminal:
```
/opt/Mattermost> ./mattermost-desktop 
config.autostart has been configured: true
[08:51:39.804] [info] Untrusted popup window blocked: https://github.com/mattermost/desktop/issues/1101
The setuid sandbox is not running as root. Common causes:
  * An unprivileged process using ptrace on it, like a debugger.
  * A parent process set prctl(PR_SET_NO_NEW_PRIVS, ...)
Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
``` 
To even start mattermost-desktop after installation, I had to change the permissions of /opt/mattermost/chrome-sandbox to 4755.

**Comment by cielavenir** [comment]
I found https://github.com/electron/electron/issues/17972#issuecomment-486927073 and this procedure fixes the issue:

- sudo chmod 0755 /opt/Mattermost/chrome-sandbox # this is the current default on deb package
- sudo sysctl kernel.unprivileged_userns_clone=1
- (restart mattermost-desktop)

However as I have little knowledge on Electron, I'm not sure if this is correct fix.

**Comment by cielavenir** [comment]
(by the way hannu78's error message was helpful to relate the (electron issue) comment to this issue)

**Comment by cielavenir** [comment]
unfortunately `sudo sysctl kernel.unprivileged_userns_clone=1` is required everytime after rebooting...

**Comment by cierzniak** [comment]
@cielavenir just add this to fixed config

```bash
 echo "kernel.unprivileged_userns_clone=1" | sudo tee /etc/sysctl.d/electron-fix.conf
```

**Comment by hannu78** [comment]
Fix above seems to work at least in 4.3.2 version of app (server 5.17.0).

**Comment by cielavenir** [comment]
@cierzniak Adding that line and rebooting worked. Thank you so much.

**Comment by DHaussermann** [comment]
@cielavenir or @hannu78  would you be able to help out by testing an advanced build of 4.4 to confirm this issue is resolved on your OS setup?  
The build is available here https://circleci.com/gh/mattermost/desktop/4909#artifacts/containers/0

**Comment by cielavenir** [comment]
@DHaussermann sorry I cannot find the direct link to deb file.

**Comment by DHaussermann** [comment]
@cielavenir, no worries. The circleci UI is a bit awkward. if you click  `> linux/` it expands out and shows you the download links for the installers.

The links for the deb file is https://4909-43964563-gh.circle-artifacts.com/0/packages/linux/mattermost-desktop-4.3.0-develop-linux-i386.deb

**Comment by DHaussermann** [comment]
Just following up on this. @cielavenir, @hannu78 or @cierzniak  Please let me know if you're able to confirm the Circle Ci build linked above resolves the issue on your OS.

**Comment by bsibsi** [comment]
It seems that the very same issue exists in the Windows desktop client too, even in v4.4

**Comment by bsibsi** [comment]
External links did not work, they're rejected with "Untrusted popup window blocked" error message in the console.

**Comment by ubhide** [comment]
I have the same problem with the latest windows client (v4.4.2). Even MM's internal "help" url does not open due to the same error.

**Comment by markgitset** [comment]
I didn't have this problem until I upgraded to 4.5.0 (on a Mac).  Now, I have to copy links and paste them in my browser.
Clicking the link seems to change the focus to my browser, but not follow the link.
![image](https://user-images.githubusercontent.com/282985/97015269-fa6c6580-1510-11eb-8491-5a879dbb00b5.png)

**Comment by goligo** [comment]
I have this issue in the latest 4.6.2 version on Windows. Left-click on links does not give any reaction, right-click on links shows "Copy Link" as the only context menu option. This makes Mattermost desktop almost useless, opening links is essential functionality.

**Comment by devinbinnie** [comment]
Closing as this should now be working correctly with v5.0.2
Please re-open if you continue to experience this.

**Comment by KlavsKlavsen** [comment]
I seem to have this problem with 5.0.2 - except i see ZERO reaction in console or security tab of developer console for current tab, nor for application wrapper.. I tried applying above sysctl and chmod adjustments on Ubuntu 21.10 with no change.. nothing happens when I click a link.. I can copy link and paste in browser myself just fine..

**Comment by DasTobbel** [comment]
> I seem to have this problem with 5.0.2 - except i see ZERO reaction in console or security tab of developer console for current tab, nor for application wrapper.. I tried applying above sysctl and chmod adjustments on Ubuntu 21.10 with no change.. nothing happens when I click a link.. I can copy link and paste in browser myself just fine..

I have the same experience currently, ubuntu 22.04, client version 5.2.2, Server version 7.7.1 - anyone has any idea?
Link in dev Tools has a valid ahref and on click there is no console output whatsoever.
