### ISSUE TITLE
macOS desktop 4.3.1: editor Help link opens a new browser tab in addition to pop-up

### ISSUE THREAD

**Issue by felibb** [mattermost/desktop#1103]
**Summary**

macOS desktop 4.3.1: editor Help link opens a new browser tab in addition to pop-up

**Environment**
- Operating System: macOS 10.14.6
- Mattermost Desktop App version: 4.3.1 (4.3.1.3679) 
- Mattermost Server version: 5.16.3 

**Steps to reproduce**
Launch client, click Help link under text input field.
**Expected behavior**
Open a pop-up with editing help.
**Observed behavior**
Open a pop-up with editing help; additionally open a new browser tab with the same help.

**Comment by amyblais** [comment]
We have a few related bug tickets open for this:
 - https://mattermost.atlassian.net/browse/MM-19919
 - https://mattermost.atlassian.net/browse/MM-19875

**Comment by felibb** [comment]
@amyblais thanks, didn't think to search JIRA first.

Should I close or will you? Not sure about the correct procedure.

**Comment by amyblais** [comment]
I'm thinking we could keep this open for now as an FYI for other community members.
