### ISSUE TITLE
Win desktop: Help webrtc error

### ISSUE THREAD

**Issue by GuimingLu** [mattermost/desktop#1104]
Desktop source code downloaded from the official website, local package compilation, NPM install, NPM run build, NPM run package: Windows, generated exe file, run webrtc website, report error: navigator. GetUserMedia error:NotReadableError:  MAC platform can run fine. error only on win.
 But the official version of the exe file can run fine on both win&mac . will not report an error.Access audio successfully. please help!. 

![111](https://user-images.githubusercontent.com/26270338/68670654-62d46800-0588-11ea-911e-8bbffe7a22d4.png)

**Comment by amyblais** [comment]
@GuimingLu What Mattermost server version are you on?

Do you see errors in Console logs? https://docs.mattermost.com/install/desktop.html#reporting-issues.

**Comment by GuimingLu** [comment]
> @GuimingLu What Mattermost server version are you on?
> 
> Do you see errors in Console logs? https://docs.mattermost.com/install/desktop.html#reporting-issues.

I have tried 4.3.1 and some other versions include the latest version . There is only "NotReadableError " in Console log.

**Comment by amyblais** [comment]
What Mattermost server version are you on? You can find it from Mattermost > Main Menu > About Mattermost.

**Comment by GuimingLu** [comment]
> What Mattermost server version are you on? You can find it from Mattermost > Main Menu > About Mattermost.

 Version 4.2.1 Desktop source code downloaded from the official website, local package compilation, NPM install, NPM run build, NPM run package  Or NPMstart .  run this website 
 https://webrtc.github.io/samples/src/content/getusermedia/record/  .report error: navigator. GetUserMedia error:NotReadableError: MAC platform can run fine. error only on win. 

![222](https://user-images.githubusercontent.com/26270338/68828438-a93cda80-06e0-11ea-8823-c9e1109858da.jpg)

**Comment by amyblais** [comment]
Would you be able to ask your System Administrator about which Mattermost server version you are on? 

We removed support for built-in WebRTC in server v5.6, so perhaps the feature is not supported on your server: https://forum.mattermost.org/t/built-in-webrtc-video-and-audio-calls-removed-in-v5-6-in-favor-of-open-source-plugins/5998.

**Comment by devinbinnie** [comment]
Closing as inactive.
