### ISSUE TITLE
Mattermost desktop v4.3.2 shows version v.4.2.0

### ISSUE THREAD

**Issue by dmarkdvt** [mattermost/desktop#1117]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
After uninstalling the version v4.3.1, while v.4.3.2 is installed, the Mattermost desktop client shows version 4.2.0.

**Steps to reproduce**

Install new version via msiexec.
Uninstall previous version.
Voila.

**Expected behavior**
Show the correct version in the Desktop client.

**Observed behavior**
After uninstalling the version v4.3.1, while v.4.3.2 is installed, the Mattermost desktop client shows version 4.2.0. The Windows software overview shows the correct version.

BUT when you do NOT uninstall the previous version, than the version in the Mattermost desktop client is correct. The Windows software itselfs shows both versions correct.

![image001](https://user-images.githubusercontent.com/57185425/69960411-a8da7700-1509-11ea-917e-9ac924ead6c0.jpg)

**Possible fixes**

---

[JIRA tickets](https://mattermost.atlassian.net/browse/MM-14183?jql=labels%20%3D%20desktop) are created for all valid bug reports filed here. Bugs and features that the Mattermost core team are not immediately working on are opened as [Help Wanted GitHub issues](https://developers.mattermost.com/contribute/getting-started/contribution-checklist/) and welcome to contributions. 

Our goal is to bring the Mattermost desktop repository into our day-to-day internal process with the hope of having more frequent desktop releases with faster feature development and turnaround time on bug fixes.

**Comment by svelle** [comment]
Hi @dmarkdvt could you do me a favor and check if you have the following items in the `View` menu?

- Developer Tools for Application Wrapper
- Developer Tools for Current Server

**Comment by dmarkdvt** [comment]
@svelle 

The funny thing is:
- my installation is fine and has these items in the View menu
- the environment from a colleague has the mentioned issues and not the items listed in the View menu

**Comment by svelle** [comment]
@dmarkdvt got it.
Thing is these items are specific to versions above 4.3 so if they're in the menu the version is 4.3.* if they're not then it's some version below 4.3.

There were some people with issues of uninstalling 4.2 correctly when upgrading to 4.3

Could you or your colleague please check the path of the mattermost shortcut that opens the 4.2.0 version and see if it points to the correct directory?

**Comment by dmarkdvt** [comment]
That is the case. We needed to delete C:\Program Files\Mattermost\lib\net45.
Everything is fine now. Thank you.

**Comment by svelle** [comment]
> That is the case. We needed to delete C:\Program Files\Mattermost\lib\net45.
> Everything is fine now. Thank you.

Of course anytime. 

Happy to help
