### ISSUE TITLE
 Mattermost desktop v4.3.2 and CTRL+v via Windows 10 does not work

### ISSUE THREAD

**Issue by dmarkdvt** [mattermost/desktop#1118]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
CTRL+v does not work with Mattermost desktop v4.3.2 and Windows 10.

**Steps to reproduce**

Try CTRL+v in a message box.

**Expected behavior**
Paste the copy.

**Observed behavior**
CTRL+v does not paste the copied content. Left click and paste only works for text but not for images.

**Possible fixes**

**Comment by amyblais** [comment]
Do you have an example image you're attempting to paste?

**Comment by squareBQ** [comment]
same issue at macOs, the Matermost version is `4.3.2(4.3.2.4230)`.

**Comment by dmarkdvt** [comment]
> Do you have an example image you're attempting to paste?

https://i.imgur.com/nBYOnvl.jpg

**Comment by amyblais** [comment]
There is an existing ticket open that may be related to this: https://mattermost.atlassian.net/browse/MM-20822.

**Comment by Ablesius** [comment]
Confirmed on Arch Linux, too (package mattermost-desktop-bin from AUR, version 4.3.2-1, kernel 5.4.1-arch1-1)

**Comment by twistedvip** [comment]
Can confirm that CTRL+v does not work with MatterMost (using Windows 10).
I can rightclick+paste with text, however, it does not paste images. I believe amyblais is correct, seems that ticket is related to this issue.

Going to be reverting back to v4.3.1 for now..

**Comment by Ablesius** [comment]
FWIW, I can copy/paste with Ctrl+Shift+C/V, but it won't work for Cut with Ctrl+Shift+X.

**Comment by ashishpatelmi** [comment]
MAC OS Catalina
Same here in 4.3.2 Copy paste not working

**Comment by a25814740** [comment]
**Windows** 
Copy: Ctrl + Insert
Paste: Shift + Insert

**Mac OX ( I'm not sure )**
Copy: Command+ Insert
Paste: Shift + Insert

**Comment by twistedvip** [comment]
@a25814740 Still unable to copy/paste images using the shortcuts.

**Comment by stefnats** [comment]
I can confirm this. I cannot paste with CMD+V, but i can paste with right click->paste

**Comment by ashishpatelmi** [comment]
Please back to version Version 4.2.1

**Comment by jazzzz** [comment]
I can reproduce on Windows 10 with Mattermost Desktop 4.3.2: Ctrl-c and Ctrl-v do not work but Ctrl-Insert and Shift-Insert work. With Mattermost Desktop 4.3.1 it works. On Ubuntu 19.10 it works with Mattermost Desktop 4.3.2.

**Comment by jazzzz** [comment]
I found out that the issue happens since the commit fddb891d8dbb32be7fcab75fe482128130e76255. Removing the manual handling of copy/cut/paste keyboard shortcuts in `main.js` fixes the issue.

**Comment by Romancha** [comment]
Same issue :( 

macOS Catalina 10.15.2 (19C57)
matermost 4.3.2 (4.3.2.4230)

command+c (copy)
command+v (paster)
command+x (cut)

not working.

**Comment by amyblais** [comment]
Would you be open to trying if desktop app v4.4.0-rc1 fixes the issue for you: https://github.com/mattermost/desktop/releases/tag/v4.4.0-rc1?

**Comment by twistedvip** [comment]
@amyblais just downloaded/installed. It fixes the issue for me :) (Win10)

**Comment by jazzzz** [comment]
> Would you be open to trying if desktop app v4.4.0-rc1 fixes the issue for you: https://github.com/mattermost/desktop/releases/tag/v4.4.0-rc1?

It fixes the issue for me too on Windows 10.

**Comment by nyclabels** [comment]
I had the same issue crop up after switching from non-SSL to SSL communication on the server end, switching to the new release client seems to have fixed the issue.

**Comment by nyclabels** [comment]
I believe this issue may be related to enabling SSL via the nginx proxy- as soon as I enable SSL, it stops functioning, but as soon as I disable SSL, it works.

Not using letsencrypt, using local CA-generated certificates.

**Comment by IanLee1521** [comment]
Looks like this happens on macOS too (`Version 4.3.2 (4.3.2.4230)`)

**Comment by amyblais** [comment]
Would you be open to trying if desktop app v4.4.0-rc1 fixes the issue for you: https://github.com/mattermost/desktop/releases/tag/v4.4.0-rc1?

**Comment by nyclabels** [comment]
I can confirm the 4.4.0-rc1 client does resolve the issue for me.

**Comment by dmarkdvt** [comment]
The problem is solved with https://docs.mattermost.com/help/apps/desktop-changelog.html#release-v4-4-0 on Win10, Ubuntu 18.04 and current MacOS.
