### ISSUE TITLE
Windows 10 Toast Notifications Are NOT Working

### ISSUE THREAD

**Issue by theriverman** [mattermost/desktop#1119]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
[Toast notifications](https://blogs.msdn.microsoft.com/tiles_and_toasts/2015/07/08/toast-notification-and-action-center-overview-for-windows-10/) on Windows 10 Enterprise are **not** working for Mattermost v4.3.2 (and probably for many earlier versions too).
I've cleared cache (and all related) folders in `%APPDATA%` to no avail.
When I roll back to the last known working version (Mattermost Desktop v3.7.1) it **does** work as intended.

**Environment**
- Operating System: Windows 10 Enterprise Version: 1809 | OS Build: 17763.475
- Mattermost Desktop App version: 4.3.2
- Mattermost Server version: 5.15.0

**Steps to reproduce**
1. Install Mattermost Desktop
2. Configure & Login
3. Minimise the Mattermost Desktop application
4. Receive a direct message
5. Look for a toast notification

**Expected behaviour**
See a toast notification in the display's corner. 

**Observed behaviour**
There is no toast notification, only a number badge on the icon on the tray.

**Possible fixes**
Rollback to an earlier Mattermost Desktop release. For us v3.7.1 did the trick but newer releases could work too.

**Comment by JtheBAB** [comment]
Hi

MSI or exe installer? The MSI has a know issue with toast notifications. 

And if your Mattermost server is with http:// you need at least 5.15.1 or later to get it working again with the latest desktop app

**Comment by theriverman** [comment]
> 
> 
> Hi
> 
> MSI or exe installer? The MSI has a know issue with toast notifications.
> 
> And if your Mattermost server is with http:// you need at least 5.15.1 or later to get it working again with the latest desktop app

Hi,

Tried both the MSI and EXE installers and I've tried installing with and without administrator rights too.
Yes, the server is plain HTTP. I'll schedule a server upgrade for this week and see what happens.

Thanks a lot for the fast response and for the tip! 👍

**Comment by JtheBAB** [comment]
I am quite certain that it will work again. 

See https://docs.mattermost.com/administration/important-upgrade-notes.html for 5.16

**Comment by theriverman** [comment]
I can confirm upgrading mattermost-server to the latest, which is v5.17.1 at the time of writing, solved this issue.
Thank you very much for your help @JtheBAB -- much appreciated!
