### ISSUE TITLE
ComponentDownload property of MSI is outdated in 4.3.2

### ISSUE THREAD

**Issue by ghost** [mattermost/desktop#1121]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
`ComponentDownload` property in the `Property` table of the Mattermost Desktop 4.3.2 x64 MSI points to an old version.

`https://releases.mattermost.com/desktop/4.1.2/mattermost-setup-4.1.2-win64.msi`

**Environment**
- Operating System: Windows 10 x64
- Mattermost Desktop App version: 4.3.2 x64 MSI

**Expected behavior**
Value should be the current MSI

**Observed behavior**
Value is for v4.1.2

**Comment by JtheBAB** [comment]
Also reported here: https://community.mattermost.com/core/pl/echd4mo6t7bipee8kj9458hf8y perhaps @amyblais can create some Jira Tickets?

**Comment by amyblais** [comment]
Ticket here: https://mattermost.atlassian.net/browse/MM-20931.
