### ISSUE TITLE
persistent notifications for a message do not automatically disappear once that message is read

### ISSUE THREAD

**Issue by lancethomps** [mattermost/desktop#1122]
On mac, with the Mattermost notification style to Alert (notification stays on screen until dismissed), the notification will stay on screen until it is either closed manually or clicked on. Ideally, the notification should automatically go away once the related message has been read.

**Comment by amyblais** [comment]
What Mattermost desktop app and Mattermost server version are you on?

**Comment by lancethomps** [comment]
Desktop version 4.3.2 and server version 5.17.1

**Comment by amyblais** [comment]
Are you referring to the desktop/push notification, or the notification number/count that appears on the left-hand sidebar?

**Comment by lancethomps** [comment]
I'm referring to the desktop notification.

**Comment by amyblais** [comment]
@lancethomps Are you referring to an OS setting to make the notification persistent until dismissed?

**Comment by lancethomps** [comment]
No - I have the OS setting enabled to make the notification persistent until dismissed. That works as expected.

I want the reading of a message within the Mattermost app to automatically dismiss the notification associated with that message. This functionality is available within the Messages application on Macs, so that can be used as an example.

**Comment by cTxplorer** [comment]
This is what I was exactly searching for. Is there any update on this?

My notification drawer is always flooded with 'already read' mattermost messages

I feel that it will be a great user experience if those notifications get cleared once I read the message (even without clicking on the notification)

--------
Mattermost Version: 5.24.0
maxOs Catalina: 10.15.16

**Comment by devinbinnie** [comment]
Closing as this is unfortunately an issue with Electron and Mac. We do dismiss the notifications when clicked on, but they don't seem to close.

**Comment by sportfloh** [comment]
Hi,
I still have this bug with mattermost desktop 5.4.0 on macOS 13.5.
It is really annoying, when will this be fixed?

At least leave this issue open until it is some how fixed either by updating electron or somehow else.
Just closing the issue and pointing to someone else doesn't help anyone. 
Maybe the relevant electron issue could be linked so people can keep track of it.

Thanks and cheers
