### ISSUE TITLE
Undo does not work on MacOS 10.15

### ISSUE THREAD

**Issue by GauthierPLM** [mattermost/desktop#1143]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Undo does not work on MacOS, neither with `command+z` nor "Edit | Undo".

**Environment**
- Operating System: MacOS 10.15.2 (19C57)
- Mattermost Desktop App version: 4.3.1
- Mattermost Server version: 5.18.0

**Steps to reproduce**
Write some text in the message field.
Press `command+z` to undo or use the menu action "Edit | Undo".

**Expected behavior**
The last typed letters should be erased, as it does in all other applications (including browser).

**Observed behavior**
Nothing happens.

**Comment by stefnats** [comment]
v4.3.2 (2019-11-29) should have fixed this. Can you confirm?

**Comment by GauthierPLM** [comment]
Indeed, my app wasn't up to date. The issue is fixed now.
