### ISSUE TITLE
Block formatted input is difficult in Mattermost

### ISSUE THREAD

**Issue by ylluminate** [mattermost/desktop#1146]
Block formatting is sometimes very difficult in Mattermost.  This is especially evident with quoting things.  Currently we have to use a `>` before each line in order to quote something.  We really need to address this issue pretty quickly.

A `/quote` might be alright since that will just simply quote an entire section.

An option like a beginning and ending ``` could also help, perhaps a `>>>` at the beginning and ending of a quoted block? 

I previously requested the ability to have a WYSIWYG style input editor box, but that seems to have been poo-pooed.  However, this quotation of chunks of text such as emails and so forth is a real point of pain presently in using Mattermost.

**Comment by Willyfrog** [comment]
Are you sure it is on each new line? I know you need to do that for paragraphs (double new line) but if I press enter just once I don't have that issue.

Can you check if you are doing double new line instead of just once? If it still reproduces, can you provide info on which versions are you using as well as operating system?

**Comment by ylluminate** [comment]
What I guess I'm saying is that this shouldn't matter. We need a better way for this vs trying to make sure there are not additional spaces. For example, a lot of times users will copy an email and there is variability in terms of having multiple line breaks (ie, a signature or man other things). It should be possible to just say: "anything within this chunk needs to be quoted."

**Comment by ylluminate** [comment]
Following the methodology that Discord follows would probably be best ([link](https://support.discordapp.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline-)):
![example](https://p153.p0.n0.cdn.getcloudapp.com/items/NQuvx779/blockquote.jpg)

**Comment by Willyfrog** [comment]
This would be a great improvement, and I think it would make writing a lot easier.
Unfortunately it is not related to the desktop app. Can you open the issue [here](https://github.com/mattermost/mattermost-server/issues) so it gets more exposure?

**Comment by ylluminate** [comment]
Thanks for the recommendation! I've done as you've requested, as you can see from the mention.
