### ISSUE TITLE
Create team flow does not work

### ISSUE THREAD

**Issue by ozten** [mattermost/desktop#115]
Mac OS X 10.11.4
Mattermost Desktop 1.1.1
Chrome Version 49.0.2623.110 (64-bit)

## Mattermost Desktop (broken)

Create new team creates a smaller pop-up window. After entering an email address and clicking "Create Team", nothing happens and there is no user feedback.
Steps to Reproduce

1) Click Team name (three dots upper left hand corner)
2) Click "Create a New Team"
3) On new popup window, enter email address
4) Click "Create Team"

Actual
Nothing happens, no feedback

Expected
Team confirmation page saying an email has been sent

## Mattermost Web (works)

Create new teams creates a new tab (on Chrome). After entering an email address and clicking "Create Team", the page is redirected to a confirmation screen.

- [X] Did you read `CONTRIBUTING.md`?

**Comment by yuya-oc** [comment]
It seems that jQuery doesn't work correctly in the new window. It will be fixed at next release by 902c16b08057904328f06081b28ed7e0cdc1be04.
For now, please use web browsers.
