### ISSUE TITLE
Client comes with screenshot function?  

### ISSUE THREAD

**Issue by Songxwn** [mattermost/desktop#1150]
Client comes with screenshot function?

**Comment by amyblais** [comment]
@Songxwn Can you help with more details on what issue you are seeing?

**Comment by Willyfrog** [comment]
@Songxwn can you clarify on the feature you'd like to see? currently there is no screentshot function for the desktop, but you can probably use the one from the operating system in most cases, if you have a special case for this feature, can you explain your case?
