### ISSUE TITLE
Automatic Startup in Windows 10 does not work

### ISSUE THREAD

**Issue by attzonko** [mattermost/desktop#1153]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
After upgrading to version 4.3.2 of the Windows Desktop Client, the client no longer starts up automatically after PC reboot, even though the checkmark in settings is on.

**Environment**
- Operating System: Windows 10 Version 1809
- Mattermost Desktop App version: 4.3.2 
- Mattermost Server version: 5.18.0

**Steps to reproduce**
Install version 4.3.2 of the client.

**Expected behavior**
The client starts up automatically after PC reboot. 

**Observed behavior**
The client does not start-up automatically on reboot.

**Possible fixes**
Reverting the client installation to 4.3.1 fixes the problem for me.

**Comment by svelle** [comment]
Starting with 4.3.2 the app reverts back to the original intended behavior to start minimized. 
Can you check if the application appears in the task bar when you use 4.3.2?

**Comment by nyclabels** [comment]
I had this same "issue" as well, requesting adding the same settings as krychu90.

**Comment by kuenzign** [comment]
Perhaps an additional setting could be added to allow Mattermost to open the window on startup instead of being minimized to the system tray.

**Comment by le-yams** [comment]
I still have the same issue with 4.5.2. 
__Environment__
* Operating System: Windows 10 Version 1809
* Mattermost Desktop App version: 4.5.2
* Mattermost Server version: 5.23.1

**Comment by devinbinnie** [comment]
Closing as I cannot reproduce on v5.0.2, this works as expected.
Feel free to re-open if you still experience this.
