### ISSUE TITLE
Slight UI server tabs issue in 4.4.0-rc0

### ISSUE THREAD

**Issue by arjitc** [mattermost/desktop#1157]
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

Currently the tab appears like this,

![2020-01-19_00-50-48](https://user-images.githubusercontent.com/363587/72669307-37716c00-3a56-11ea-8c72-4aefe3507dac.png)

Might be better if it appears smoother (or sharper?) like this,

![2020-01-19_00-50-48 - Copy](https://user-images.githubusercontent.com/363587/72669314-4a843c00-3a56-11ea-956d-2a5920937f3c.png)

**Environment**
- Operating System: Windows 10
- Mattermost Desktop App version: 4.4.0-rc0
- Mattermost Server version: 5.18.0

**Steps to reproduce**

Install the 4.4.0-rc0 desktop app

**Comment by amyblais** [comment]
Ticket here: https://mattermost.atlassian.net/browse/MM-21975.

**Comment by andrewbrown00** [comment]
Hi @arjitc thanks for logging this 😄

I do see a slight pixel bump, it's not as pronounced on my end as it is in the screenshot you've included.

![image](https://user-images.githubusercontent.com/48559658/72913192-c8706d80-3d0a-11ea-93a1-fd01e1fe7430.png)

**I have a few questions to help use better understand the issue:**

- What type of display are you using?
- What is the resolution set to?
- Is it set to scale?
- Is the zoom set to 100%, or is it zoomed in or out? If so, to what percentage?

Any other details you can provide would be helpful!

**Comment by arjitc** [comment]
> What type of display are you using?

It's a laptop 1080p, 15.6" display

> What is the resolution set to?

1920 * 1080

> Is it set to scale?
> Is the zoom set to 100%, or is it zoomed in or out? If so, to what percentage?

Windows Display Properties lists it as 125%

**Comment by andrewbrown00** [comment]
Thanks for the details! I'll work with the team and see what going on.

**Comment by amyblais** [comment]
Closing, this was fixed in v4.7,
