### ISSUE TITLE
Unable to download 4.4.0-rc0 for Mac

### ISSUE THREAD

**Issue by jby** [mattermost/desktop#1158]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: macOS 10.15.2
- Mattermost Desktop App version: 4.4.0-rc0
- Mattermost Server version: N/A

Go to https://github.com/mattermost/desktop/releases and try to download for macOS

**Expected behavior**
Indicated pkg should be downloaded
**Observed behavior**

<img width="1522" alt="Screenshot 2020-01-20 at 13 38 33" src="https://user-images.githubusercontent.com/1584888/72727207-a4861e00-3b8a-11ea-98e2-8a05e36a46e2.png">

**Comment by Willyfrog** [comment]
Hi, on the [release page for 4.0.0-rc0](https://github.com/mattermost/desktop/releases/tag/4.4.0-rc0) you can use the assets on it which can be used for download while we solve this issue.

**Comment by Willyfrog** [comment]
it'll be fixed by rc1
