### ISSUE TITLE
Mattermost Desktop 4.4.0-rc0 is closing when you try download a file

### ISSUE THREAD

**Issue by luk4sk** [mattermost/desktop#1160]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: Windows 10 1909 18363.592
- Mattermost Desktop App version: 4.4.0-rc0 
- Mattermost Server version: 
Version: 5.19.0
Build Number: 5.19.0
Build Enterprise Ready: false
DB Version: 5.19.0
 

**Steps to reproduce**

When you try to download a file in the Mattermost Desktop app, the application rapidly closes. 

**Expected behavior**

The file is downloading.

**Observed behavior**

In the `AppData\Roaming\Mattermost` folder you can find a file like `uncaughtException-1579534415127.txt` with content:
`Application: Mattermost 4.4.0-rc0
Platform: Windows_NT 10.0.18363 x64
TypeError: Error processing argument at index 0, conversion failure from #<Promise>
    at Session.<anonymous> (C:\Program Files\Mattermost\Desktop\resources\app.asar\main_bundle.js:829:12)
    at Session.emit (events.js:200:13)`

**Comment by arjitc** [comment]
Facing the same issue here.

**Comment by JtheBAB** [comment]
And here is the reason: https://github.com/mattermost/desktop/pull/1159

**Comment by Willyfrog** [comment]
thanks @JtheBAB 
it will be fixed for rc1

**Comment by Willyfrog** [comment]
fixed in RC1
