### ISSUE TITLE
Version 4.3.2 throws "process is not defined" in developer console after update

### ISSUE THREAD

**Issue by jurgenhaas** [mattermost/desktop#1163]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

Just installed version 4.3.2 over 4.0.0 (which was running ok before) and when starting the desktop client it only shows a white screen. When opening the devebloper console, there is an error message `Uncaught ReferenceError: process is not defined` in lin 1689 of index.js

I then stopped the client, removed the existing directory `~/.config/Mattermost` to start over, but the result after starting the client again is still the same.

**Environment**
- Operating System: Ubuntu 18.04
- Mattermost Desktop App version: 4.3.2 - although the help dropdown shows 1.3.0
- Mattermost Server version: 5.17.1

**Possible fixes**

Found out that in `/opt/Mattermost/ressources` there has been an old `apps/` subdirectory which wasn't deleted or updated. When I removed that manually, all was then just working fine.

**Comment by devinbinnie** [comment]
Closing as this no longer reproduces.
