### ISSUE TITLE
osx desktop client just shows white blank window

### ISSUE THREAD

**Issue by maxandersen** [mattermost/desktop#117]
downloaded 1.0.7 of native client and it just shows a white screen.

**Comment by yuya-oc** [comment]
Please try v1.1.1. Then if you still have problem, please write about your environment to understand your trouble (see CONTRIBUTING.md).

* Mattermost server version
* Operating system

**Comment by maxandersen** [comment]
where do I find v.1.1.1 ? the page http://about.mattermost.com/downloads/ say it is 1.1.1 but it actually points to 1.0.7.

**Comment by maxandersen** [comment]
ah found it on https://github.com/mattermost/desktop/releases/

**Comment by maxandersen** [comment]
and it is the same problem. Just a blank white screen.

server version should not matter since I haven't even been able to configure the desktop client and my operating system is OS El Capitain 10.11.3 (15D21)

**Comment by yuya-oc** [comment]
Thanks, I had thought that there are som problem in connection. Does the application menu, `Mattermost -> Settings` work? If it doesn't, could you check below?

- The directory which the app is located at.
- The console output of window when reloading by `Cmd+R` (the developper tool is shown by `Cmd+Alt+I` or menu).

**Comment by maxandersen** [comment]
Yes, the Matermost -> Settings does work (I didn't even realize there was a menu since the app looked blank ;)

But when I add a team/connection I still just see a white screen.

**Comment by yuya-oc** [comment]
Hmm...it seems that there some problem while rendering DOM... Could you check the console output of developer tool? (the developer tool is shown by `Cmd+Alt+I` or menu)

**Comment by maxandersen** [comment]
It gives me this: 

![mattermost_and_re___mattermost_desktop__osx_desktop_client_just_shows_white_blank_window___117__ _all_messages__3_messages_](https://cloud.githubusercontent.com/assets/54129/15111065/fb03040c-15e4-11e6-8143-bf961b69a83c.png)

**Comment by maxandersen** [comment]
note, since I can't go and delete the connection I have in settings I can't be sure this is the only thing that errors.

If you can tell me how to remove the settings mattermost uses then I can try reproduce more precise.

**Comment by yuya-oc** [comment]
Please remove `~/Library/Application Support/Mattermost` on OS X.

**Comment by maxandersen** [comment]
hmm - does not seem to reproduce. it still shows blank for a second or so - but no longer "stuck".

**Comment by jasonblais** [comment]
Thanks @maxandersen for the report, checking whether the issue reproduces for you anymore?

You might see a blank screen while the application loads; we should look into improving the loading screen to provide feedback to the user while the application loads

**Comment by maxandersen** [comment]
after I got the connection configured it stopped "blocking", haven't been able to reproduce it again even after nuking the settings.

**Comment by jasonblais** [comment]
Great to hear it's no longer blocking, I will close this issue for now
