### ISSUE TITLE
Please make history of last channels with part of last message on CTRL+K window

### ISSUE THREAD

**Issue by believer-ufa** [mattermost/desktop#1172]
Can you make history of last channels with part of last message on CTRL+K window? Because when you have many chat channels, it becomes difficult to navigate between them and remember where was your last important conversation.

I'm also made post on uservoice about it: https://mattermost.uservoice.com/forums/306457-general/suggestions/39565285-make-history-of-last-channels-with-part-of-last-me.

Thank you guys. It nice project by the way!

**Comment by Willyfrog** [comment]
Hi @believer-ufa thanks for reporting, but this seems to be a feature to have on the webapp as the desktop doesn't handle that part. can you reopen it on the [server's issues](https://github.com/mattermost/mattermost-server/issues)

closing the issue, but feel free to reopen if i missed something
