### ISSUE TITLE
Occasionally stops rendering

### ISSUE THREAD

**Issue by rpglover64** [mattermost/desktop#118]
Sporadically, the client will turn into this:

![2016-04-29-09 13 23](https://cloud.githubusercontent.com/assets/233689/14917003/dfd4bd76-0dea-11e6-9aee-88c61ee4f88a.png)

and I'll have to quit and restart. It happens more often after my laptop has been in sleep mode for a prolonged period of time.

OS: Linux (with i3 as a window manager)
MM version: 1.1.1

**Comment by jasonblais** [comment]
Thanks @rpglover64 for the report,

Can you try upgrading to [Mattermost desktop version 1.2.1](https://github.com/mattermost/desktop/releases) to see whether the issue still reproduces? The newest version offered a few bug fixes and stability improvements

**Comment by rpglover64** [comment]
I _think_  that you can close the bug. I've been running 1.2.1 for a bit now, and never has it gotten stuck in that state. It does, however, flicker twice (for about 2 seconds) every time I change the channel, but that sounds like a different bug.

**Comment by jasonblais** [comment]
Thanks @rpglover64! Does the flickering happen in Linux, and consistently every time you change a channel?

While it sounds to be a different issue, it sounds like something that's worth to take a closer look.

**Comment by rpglover64** [comment]
Yes. It is consistent.

First, there's a "Loading ...", then the screen goes blank like in the screenshot, then the page is drawn, then it goes blank again, then the page is drawn again. This happens even if I "switch" to the same channel.

Closing this one and opening a new one.
