### ISSUE TITLE
Newly appearing server tab bar in v4.4.0-rc1 does not respect dark theme setting 

### ISSUE THREAD

**Issue by bentolor** [mattermost/desktop#1181]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
A newly appearing server tabulator bar does not respect dark theme setting.

**Environment**
- Operating System: Linux Mint 19.3, Cinnamon, Dark Theme
- Mattermost Desktop App version: v4.4.0-rc1 (2020-01-30) Build Hash: c81e4f87c20a717b1dc52b2b77780fa789e19148
- Mattermost Server version: X.X.X 

**Steps to reproduce**
1. Choose "Window dark" Theme in settings
2. Open Client Application

**Expected behavior**
Complete Mattermost UI should adhere its theme or at least it should only appear on using more than one team/server. After reading #844 it seems that the issue itself is already older, but the new behavior of 4.4 to always show the bar exposes it to every user.

**Observed behavior**
The new title tab bar is in bright theme, even though also the Desktop UX Theme is a dark theme

![grafik](https://user-images.githubusercontent.com/588260/73736854-cadaba80-4741-11ea-97e5-51acc160ba49.png)

**Comment by bentolor** [comment]
Maybe similar or related to the much older #844 ?

**Comment by svelle** [comment]
Same happening on Fedora 31 using Gnome 3.34

**Comment by devinbinnie** [comment]
Hey @bentolor,

Unfortunately choosing the 'Windows Dark' or 'Mattermost Dark' theme in the app is not the setting to turn on dark mode in the desktop app.
You'll have to use the 3-dot menu, go to View > Toggle Dark Mode.

**Comment by esethna** [comment]
Note we have a ticket open to follow the Windows OS theme option (as we currently do on Mac OS), but it currently blocked on us updating the Electron 7 dependencies: https://mattermost.atlassian.net/browse/MM-22279

**Comment by bentolor** [comment]
> You'll have to use the 3-dot menu, go to View > Toggle Dark Mode.

Thanks for the pointer, @devinbinnie. This actually does render the top bar in an appropriate dark color. Yes. Quite hidden, though.

**Comment by Willyfrog** [comment]
@bentolor thanks for reporting, seems like it got solved so I'm closing the issue, feel free to reopen if there is anything else left to handle
