### ISSUE TITLE
Do not silently close Edit Message dialog on a mouse click outside it

### ISSUE THREAD

**Issue by mvitaly2003** [mattermost/desktop#1184]
If you try to edit a message in chat and accidentally click outside Edit Message dialog, the dialog silently closes and all your changes get lost.

**Steps to reproduce**
Open a chat, find any of your messages and choose 'Edit' from 'More Actions' menu, then change text and do a click outside the edit dialog (e.g. for activating application back after switching to another one).

**Expected behavior**
Mattermost either should show a confirmation dialog (like it does when you delete a message) or it shouldn't close this dialog with unsaved changes on a mouse click outside the dialog.

**Observed behavior**
Edit dialog just disappears w/o saving your changes and w/o asking your if you want to save them.

**Comment by Willyfrog** [comment]
hello @mvitaly2003 
thanks for reporting the issue, but this is not a desktop one, can you reopen it [on the server repo](https://github.com/mattermost/mattermost-server/issues) where it belongs? thanks!
