### ISSUE TITLE
Option to always trust self-signed certificates

### ISSUE THREAD

**Issue by Edll** [mattermost/desktop#1188]
On a server that is only accessible internally with a self-signed certificate, it would be great if you could configure the client to always trust the certificate. I have not found an option like this in the documentation.
I try to import the certificate to the system store without success.

**Comment by Willyfrog** [comment]
whenever the certificate is not trusted, it is issuing a popup to notify this to the user, going into details lets you trust a previously untrusted certificate which gets stored in `certificates.json`. Once the certificate is there, it shouldn't bother you anymore.

**Comment by Edll** [comment]
@Willyfrog 
Then this doesn't seem to be working right. Whenever I start the mattermost client I get a message "Certificate Error", "more Details" and "Trust Insecure Certificate" will rewrite the ```certificates.json``` file but the message will come back the next time I start mattermost client.

tested on:
Ubuntu gnome 18.04.4
Manjaro XFCE 18.1.5
Windows 10

**Comment by Willyfrog** [comment]
which version are you using? have you tried 4.4.0-rc1? we did some changes there

**Comment by Edll** [comment]
I try it in version 4.3.2  i will try version 4.4.0-rc1x and then give you feedback.

**Comment by Edll** [comment]
@Willyfrog 
no, same with 4.4.0-rc1 and have to retrust again and again. 

tested on:
Ubuntu gnome 18.04.4
Manjaro XFCE 18.1.5

**Comment by Willyfrog** [comment]
thanks! I've created a ticket to track it, we'll try to investigate it

**Comment by gvcgael** [comment]
Same problem here.

**Comment by Willyfrog** [comment]
see https://mattermost.atlassian.net/browse/MM-22434

**Comment by Willyfrog** [comment]
closing, will be released on 4.5

**Comment by maximsnezhkov** [comment]
@Willyfrog where can I find `certificates.json` ? I'm using mattermost 4.4.1 from deb-package and always get untrusted error with the same CAcert

**Comment by Willyfrog** [comment]
on linux should be in "~/.config/Mattermost" but if you have this problem, it is fixed on master (you'll need to build from sources) and on future 4.5

**Comment by maximsnezhkov** [comment]
Build from master is resolved the problem. Thanks @Willyfrog

**Comment by maximsnezhkov** [comment]
I've also caught this bug on the mac client. It will be fixed on 4.5 too? @Willyfrog

**Comment by Willyfrog** [comment]
yes
