### ISSUE TITLE
Does not respond to OS quit event

### ISSUE THREAD

**Issue by rpglover64** [mattermost/desktop#119]
Using Linux with i3 as a window manager, <kbd>Win-Shift-q</kbd> closes every window but not Mattermost's; <kbd>Ctrl-q</kbd> works fine. Perhaps this is related to #88 or #8

MM version: 1.1.1

**Comment by yuya-oc** [comment]
I don't know about i3, but [`$mod+Shift+q`](http://build.i3wm.org/docs/userguide.html#_closing_windows) seems to be just closing a window. So I think that it's related to #8 and #90. And as I had written at #90, the way to tell 'quit' and 'close' is necessary. If 'quit' performs as 'close all windows', I might not be able to handle that.

btw, why is #88 related?

**Comment by rpglover64** [comment]
Correct; mod+shift+q closes the window. I considered the lack of system tray icon as relevant because without one, a closed window would be impossible to reopen, but the application would still be running.

**Comment by jasonblais** [comment]
Thanks @rpglover64  for the feedback,

A related ticket #178 has been resolved and closed, which should fix the issue presented here.

However, if there is a further improvement you would like to see, I invite you to help contribute your suggestion in Mattermost [feature idea forum](https://mattermost.uservoice.com/forums/306457-general) so it can be discussed, upvoted and considered for a ticket accepting pull requests?

If you do add it to the [feature idea forum](https://mattermost.uservoice.com/forums/306457-general), please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review.
