### ISSUE TITLE
Inline images from links not displaying

### ISSUE THREAD

**Issue by PotatoAdmin** [mattermost/desktop#120]
Hello everyone!

We are experiencing this issue (as the title says) on the desktop application of Mattermost. The mobile and web interfaces are working as intended.

**How to reproduce, step-by-step:**
-Select an image to link
-Copy the link
-Paste the link in any Mattermost channel using the application
-Press enter to post

**Expected behavior (or what is wrong):**
-The image is not displayed inline when the link is directly copy-pasted. Only the link is displayed
-The image is not displayed inline using the markdown for inline images (found [HERE](http://docs.mattermost.com/help/messaging/formatting-text.html#in-line-images)). Nothing is displayed using this technique apart from a missing image place holder.

**Screenshots (for GUI issues):**
![inline_markup](https://cloud.githubusercontent.com/assets/18739870/14919889/e1067e10-0df8-11e6-8f5c-f0491919ab15.png)
![direct_link](https://cloud.githubusercontent.com/assets/18739870/14919900/e79c73ec-0df8-11e6-8627-cabadbffda25.png)

**Application version:**
Version 1.1.1

**Operating system:**
-Ubuntu 16.04
-Windows 10

**Mattermost server version:**
Version 2.2.0

**Comment by yuya-oc** [comment]
Thank you for detailed reporting!

1. The URL (https://en.wikipedia.org/wiki/Potato#/media/File:Patates.jpg) does not seem a direct link for the image file. So I think that it does not appears. Please try also with web browsers.
2. The images with `http://` don't appear (#35). The option to show them will be provided at next release.

**Comment by PotatoAdmin** [comment]
Oh, thanks for the clarifications! We will be eagerly waiting for the next release!
