### ISSUE TITLE
Mattermost v4.4.0 portable (zip file) for Windows x64 checksum is incorrect

### ISSUE THREAD

**Issue by LoZeno** [mattermost/desktop#1201]
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: Windows 10
- Mattermost Desktop App version: 4.4.0

**Steps to reproduce**
Go to https://github.com/mattermost/desktop/releases/tag/v4.4.0
Download the windows zip file for x64 (https://releases.mattermost.com/desktop/4.4.0/mattermost-desktop-4.4.0-win-x64.zip)

**Expected behavior**
The SHA-256 checksum should be `653f9837f612aac6a6ce564f622f04a8094246eb2e4ff9da9399370e75664e6e` as listed in the release page

**Observed behavior**
The actual SHA-256 checksum is `10ad1308f311cfa4936667b47262ad8c87c72c5a070594f78bd028b7b465d2b6`

Consequences of this is that package managers and install managers (such as scoop) are unable to update the app to the new version due to the checksum mismatch.

**Possible fixes**

**Comment by Willyfrog** [comment]
thanks for noticing, I already updated the release description with the right checksums.
closing the issue, but if you notice anything else off, feel free to reopen
