### ISSUE TITLE
First two numbers cuted away if you write 1234. test (Output: 34. test)

### ISSUE THREAD

**Issue by DVTrast** [mattermost/desktop#1202]
**Summary**
If you write 1234. test in the output the first two numbers are cuted away.

**Steps to reproduce**
Enter for example the text "1234. test". In the desktop version the first two numbers are cuted away (in the app the problem doesn´t exitsts).

**Expected behavior**

**Observed behavior**

![grafik](https://user-images.githubusercontent.com/61227869/74837360-9c540680-5321-11ea-9ec3-a30803141ca4.png)

![grafik](https://user-images.githubusercontent.com/61227869/74837448-d3c2b300-5321-11ea-8529-474847559b16.png)

**Possible fixes**
Don´t have one.

**Comment by JtheBAB** [comment]
I tested on community.mattermost.com and on the personal server. Can't reproduce.
Are you on the latest desktop app (4.4)?

**Comment by esethna** [comment]
Hi @DVTrast, this is not related to the desktop app, it is actually the server version. We fixed this in v5.20 just released Feb 16th. When you have a chance please upgrade your server version and we can reopen this issue if it persists.

**Comment by esethna** [comment]
https://mattermost.atlassian.net/browse/MM-18541
