### ISSUE TITLE
Font rendering is not using subpixel rendering (on Linux)

### ISSUE THREAD

**Issue by jagerman** [mattermost/desktop#1207]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Mattermost desktop is not enabling subpixel rendering and so fonts look fuzzy compared to other applications.

**Environment**
- Operating System: Debian Linux
- Mattermost Desktop App version: 4.4.0
- Mattermost Server version: 5.20.1

**Steps to reproduce**

Open mattermost.

**Expected behavior**

See crisp subpixel rendered fonts.

**Observed behavior**

See blurry greyscale rendered fonts.

8x zoom:
![image](https://user-images.githubusercontent.com/4459524/74901341-f59b5480-5378-11ea-97c5-1371aaa9521e.png)

Here's a comparison from another electron app that doesn't have this issue:
![image](https://user-images.githubusercontent.com/4459524/74901377-0fd53280-5379-11ea-8b69-9ae774843886.png)

**Possible fixes**

https://www.electronjs.org/docs/faq#the-font-looks-blurry-what-is-this-and-what-can-i-do

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-22772.

**Comment by amyblais** [comment]
Closing as there is now a Help Wanted issue open for this here: https://github.com/mattermost/desktop/issues/1232.
