### ISSUE TITLE
No Tray Icon in XFCE4

### ISSUE THREAD

**Issue by zepalmer** [mattermost/desktop#121]
I have downloaded the Linux binary package for the Mattermost desktop client (version 1.1.1).  I am running the client using Debian Stretch (testing) with XFCE4.  Mattermost does not seem to add an icon to the XFCE4 "notification area", which is where the tray icons for my applications such as Pidgin go.  Closing the Mattermost window causes it to minimize to my task bar rather than go to the tray.  I'm not sure what's different about XFCE4 from e.g. GNOME that's causing this behavior.

**Comment by yuya-oc** [comment]
For now, the tray icon is not implemented for Linux. Then, the window is merely minimized when closing regardless of desktop environment. Please see #88.

**Comment by zepalmer** [comment]
Ah; thank you.  :)
