### ISSUE TITLE
Bugged Out Taskbar icon of Mattermost

### ISSUE THREAD

**Issue by hectorskypl** [mattermost/desktop#1210]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: Windows 7 Professional x64 (with ESU)
- Mattermost Desktop App version: 4.4.0 
- Mattermost Server version: 5.20.1 

**Steps to reproduce**
Run Mattermost Application
**Expected behavior**

**Observed behavior**
Icon is too small and glitched.
Also the notification dot is not visible

https://i.imgur.com/nzBc58x.png
**Possible fixes**

**Comment by amyblais** [comment]
Thanks, I opened a ticket here: https://mattermost.atlassian.net/browse/MM-22690.

**Comment by devinbinnie** [comment]
Closing since we no longer directly support Windows 7 anymore and the icon has been changed since.
