### ISSUE TITLE
Add option to use old frame border for legacy systems

### ISSUE THREAD

**Issue by hectorskypl** [mattermost/desktop#1211]
The new Windows 10 forced border on legacy OSes looks so awfull...
Would be nice to have switch which allow to disable it. :)

**Comment by esethna** [comment]
@devinbinnie are we able to detect the OS version? What would be involved in detecting the OS version (ie Windows 7 or 8) and adjusting the window frame accordingly?

**Comment by devinbinnie** [comment]
@esethna Yeah we can detect the windows version and use the old frame on older versions of Windows.

**Comment by esethna** [comment]
Thanks, @hectorskypl I opened a ticket here: https://mattermost.atlassian.net/browse/MM-22751

**Comment by esethna** [comment]
Closing this issue to follow in JIRA

**Comment by licaon-kter** [comment]
Could you implement a toggle/option/command to disable this? It's horrendous :(

**Comment by esethna** [comment]
@licaon-kter can you help me understand what you're referring to? Is your preference to have the native frame or not? Do you have more than one server? What OS are you using?

**Comment by licaon-kter** [comment]
One server, multiple teams, and there's no need for an extra titlebar, imha, yes it doesn't look "native" but doesn't look any better with it. Windows 7 and 8. Will make some screenshots.

**Comment by esethna** [comment]
Got it. @licaon-kter we have a ticket open to remove the tab bar if only one server is configured, so in your case you would only have the native windows frame: https://mattermost.atlassian.net/browse/MM-25961
