### ISSUE TITLE
Multiple Display Windows 10 - MM taskbar button stuck in main taskbar

### ISSUE THREAD

**Issue by Ubiqus-labs** [mattermost/desktop#1212]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: Windows 10 Professionnel 1909 x64 - build 18363.657
- Mattermost Desktop App version: 4.4.0
- Mattermost Server version: 5.17.1

**Steps to reproduce**
2 displays connected to computer
In Windows Settings app >> Personalization >> Taskbar, the option "Show taskbar buttons on to" is set  "taskbar where window is open".

**Expected behavior**
The MM taskbar icon should show up in the relevant taskbar, the one where the MM window is open.

**Observed behavior**
As of MM v4.4.0, the MM taskbar icon keeps showing up only in the main taskbar.
This issue has never occurred with MM app v4.3.2.
![Mattermost4-4-0](https://user-images.githubusercontent.com/24956897/75341339-7f28b600-5894-11ea-8b20-fc063e7142c4.png)
![WindowsTaskbarSettings](https://user-images.githubusercontent.com/24956897/75341340-7fc14c80-5894-11ea-8cd3-3cfa8ddfca67.png)

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-22770

**Comment by Willyfrog** [comment]
I've asked several people, but noone seems to be able to reproduce the issue. So we are missing something that affects or it was a glitch due to something else.
please reopen if there is any info on how to get it to reproduce
