### ISSUE TITLE
Typing message input focus lost when using ctrl+alt+up/down on Linux

### ISSUE THREAD

**Issue by ajantiss** [mattermost/desktop#1215]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Let's assume that you get focus on typing message input. If you switch (At least on Linux) through multiple desktops with `ctrl+alt+down `, focus is lost and is positioned to `three-dot-menu` tab-index. This is really annoying, as even `ctrl+shift+L` is not working to set the focus back (as seem to be outside Mattermost webview), only a click in the webview can recover from this state.

**Environment**
- Operating System: Ubuntu 19.10
- Mattermost Desktop App version: 4.4.0
- Mattermost Server version: 5.8.0 

**Steps to reproduce**
Having multiple vertical desktops on Linux (Ubuntu default) and type `ctrl+alt+down `

**Expected behavior**
Focus stay on typing message input

**Observed behavior**
Focus is moved to three dot menu and isn't set back to Mattermost webview

Please ask if you need screen or video of this issue.

**Possible fixes**
Have a way to disable frameless window and rollback to use OS default one ?

**Comment by amyblais** [comment]
@ajantiss Would you be open to testing if you can reproduce this on a recent server version? Our most recent server is v5.20.0.

**Comment by ajantiss** [comment]
I just tried with 5.20.1 server version and still the same, here an animated gif of what happens
![focus](https://user-images.githubusercontent.com/6159881/75525794-c89e1000-5a10-11ea-8816-4ec3d4c2cd38.gif)

**Comment by amyblais** [comment]
Opened a ticket here: https://mattermost.atlassian.net/browse/MM-22769.

**Comment by tmakgit** [comment]
I can also confirm this issue. I came about after the new interface design with the menus being condensed into the three-dot menu. When using any Alt shortcut keys common in most Linux desktops, the three-dot menu is selected, can cannot be de-selected with Alt. Either a click in the webview or pressing Enter (opening the menu) and pressing Esc to close it will allow other shortcut keys inside of Mattermost to be used.

**Comment by tmakgit** [comment]
I would prefer to have the option to switch back to the OS window framing as well.

**Comment by Willyfrog** [comment]
you can try https://github.com/mattermost/desktop/releases/tag/v4.7.0-rc6 to see if https://github.com/mattermost/desktop/pull/1619 fixes theproblem
