### ISSUE TITLE
Cannot copy/paste screenshot from clipboard to text box for version 4.3 on Windows 10

### ISSUE THREAD

**Issue by dhanaa** [mattermost/desktop#1219]
I confirm (by marking "x" in the [ ] below: [x]):

- [x ] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [ ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: Windows 10
- Mattermost Desktop App version: 4.3.0 
- Mattermost Server version: X.X.X 

**Steps to reproduce**

**Expected behavior**

**Observed behavior**

**Possible fixes**

**Comment by JtheBAB** [comment]
Please update to the latest version (4.4) and try again.

**Comment by Willyfrog** [comment]
did 4.4 help?

**Comment by amyblais** [comment]
I'll close this for now as we haven't received feedback for a while. Please re-open this issue if the problem persists on v4.4.0,
