### ISSUE TITLE
Red badge on taskbar and tray icon

### ISSUE THREAD

**Issue by JinZhuXing** [mattermost/desktop#1220]
I confirm (by marking "x" in the [ ] below: [x]):

- [ ] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
I can't see red badge on taskbar and tray icon when I received new message.

**Environment**
- Operating System: Windows 10 x64 1909
- Mattermost Desktop App version: 4.4.0
- Mattermost Server version: 5.20.1

**Steps to reproduce**
Run Mattermost Application and receive a new message.

**Expected behavior**
Show red badge on taskbar and tray icon when I set red badge setting.

**Observed behavior**
I can't see red badge on taskbar and tray icon when I received new message.

![002](https://user-images.githubusercontent.com/15034343/75620400-7cdf9800-5bc3-11ea-897a-380517ff8691.png)
![001](https://user-images.githubusercontent.com/15034343/75620401-7e10c500-5bc3-11ea-80cd-84cfa588b85f.png)

**Comment by SheanYa** [comment]
I have a same problem.

**Comment by luk4sk** [comment]
Same problem here.

**Comment by devinbinnie** [comment]
@JinZhuXing Do you see a blue badge when you receive a message that isn't a mention? Or do you see no badge at all?

**Comment by JinZhuXing** [comment]
Sometimes it works well, so I can see the red badge on tray icon.
But when this problem occurs, I can't see any badge(red, blue).

**Comment by cbrand-ludlums** [comment]
I'm seeing this too.  Also, there are times when there are no notification indicators displaying in the sidebar for channels along with no badges on the taskbar/system tray icons.  I've noticed that sometimes, if I'm currently in a channel,  I'll not receive any notifications of any activity, direct notifications or otherwise.  I'm only seeing this on the 4.4 desktop client, As far as I can tell it works as intended if I run the 4.3.2 client and I think thru the web interface, although I've not done a lot of testing on this.

**Comment by amyblais** [comment]
@devinbinnie Since lot of users are seeing this, do you feel we can we open a ticket to investigate this?

**Comment by devinbinnie** [comment]
> @devinbinnie Since lot of users are seeing this, do you feel we can we open a ticket to investigate this?

Absolutely. Would be interested to see if I can reproduce this myself though, since I've never seen this before personally.

**Comment by JinZhuXing** [comment]
I think you can reproduce this problem with below steps.

First, open the mattermost program with double clicking tray icon.
And chat with someone. (for example named "John")
After finish chatting, close the window.
So, at this time, selected person is "John".
After that, you can not receive any notification of new message from "John".
But you can get notification of new message from others.

Before you close windows, if you select other (not "John"), you can receive notification from "John".

**Comment by devinbinnie** [comment]
@JinZhuXing so I opened a DM with another account, I had the 2 accounts talk to each other, then I closed the desktop window and I had the other account message the account running desktop. I received a notification from that account and the badge appeared.

Is there anything else I can do to make this happen?

**Comment by JinZhuXing** [comment]
@devinbinnie Open windows with double clicking tray icon.
And then, chat with only one account in "Direct Message". (for example named "John")
Also John must chat with only you in "Direct Message".
After finish chatting, close the mattermost window.
So at this moment, John and you does not select other account. John selected you, and you selected John.
After closing window, John reopen window with double clicking tray icon.
And send new message to you without selecting other account.
But you can not receive notification and badge does not appear.

PS. You and John must use in same environment.
Operating System: Windows 10 x64 1909
Mattermost Desktop App version: 4.4.0
Mattermost Server version: 5.20.1

Thank you.

**Comment by devinbinnie** [comment]
@JinZhuXing Okay so that confirms the process I took before, but to further confirm are you running 2 instances of the desktop app on one machine (one with you signed in and the other with 'John')? If not, can you clarify what you mean by 'use in same environment'?

Thanks a bunch!

**Comment by JinZhuXing** [comment]
@devinbinnie Running 2 app on seperate machines.
'Same environment' means OS, Mattermost Server and Desktop App version of two machines are same.
Operating System: Windows 10 x64 1909
Mattermost Desktop App version: 4.4.0
Mattermost Server version: 5.20.1

Thank you.

**Comment by maxmukhin88** [comment]
same issue here, hope to see it fixed soon

**Comment by JinZhuXing** [comment]
Thanks.
This issue was fixed.
