### ISSUE TITLE
Mattermost 4.4.0 not starting on Linux

### ISSUE THREAD

**Issue by martinmarques** [mattermost/desktop#1221]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [ X ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ X ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Installation of client 4.4.0 for Linux doesn't work, while 4.3.2 does work just fine

**Environment**
- Operating System: Fedora 30 Linux
- Mattermost Desktop App version: 4.4.0
- Mattermost Server version: 5.19.1

**Steps to reproduce**
- Download client from Mattermost web site
- Extract to a new directory
- Run "mattermost-desktop

Even though I extracted the binaries to a clean directory, I was prompted with a pop-up window indicating that there were existing files that would be replaced. Odd.

**Expected behavior**
Have the client start, just like I'm still able to with the 4.3.2 version

**Observed behavior**
```
$ ./mattermost-desktop 
internal/modules/cjs/loader.js:630
    throw err;
    ^

Error: Cannot find module '/home/martin/bin/mattermost-desktop-4.4.0-linux-x64/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:850:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

```

**Possible fixes**
:man_shrugging:

**Comment by svelle** [comment]
@martinmarques what package did you download from the releases page? Just the regular .tar.gz?

I'm also running Fedora and would like to confirm this.

**Comment by martinmarques** [comment]
It's the tarball from https://docs.mattermost.com/install/desktop.html#linux
More specifically, this one: https://releases.mattermost.com/desktop/4.4.0/mattermost-desktop-4.4.0-linux-x64.tar.gz

**Comment by svelle** [comment]
> It's the tarball from https://docs.mattermost.com/install/desktop.html#linux
> More specifically, this one: https://releases.mattermost.com/desktop/4.4.0/mattermost-desktop-4.4.0-linux-x64.tar.gz

Interesting, I could start this without any issues.

@martinmarques can you try the rc4 release and see if that one works? 

https://releases.mattermost.com/desktop/4.4.0-rc4/mattermost-desktop-4.4.0-rc4-linux-x64.tar.gz

**Comment by martinmarques** [comment]
Same issue. I'm going to restart my laptop later and see if it's something that's left in cache

**Comment by martinmarques** [comment]
Restarted the graphical session. No joy.
Rebooted Linux, same issue, even with the RC4 version.

**Comment by Willyfrog** [comment]
tested on ubuntu, it works. I currently don't have fedora, but I can install it on a vm

@martinmarques  Do you have any especial config setup? different DE or anything away from the defaults?

**Comment by martinmarques** [comment]
I use the plasma environment. I don't believe I have anything special setup on this laptop.

**Comment by martinmarques** [comment]
I was able to make it work on a desktop computer with Fedora 30 and plasma desktop. What I did see there was that the look&feel is completely different from what I see here with mattermost 4.3.2. This looks very much like plasma desktop, while on the desktop computer it has more of a chrome look&feel

**Comment by martinmarques** [comment]
Maybe this helps. It's part of the strace output, at the end:
```
madvise(0x3f8774394000, 36864, MADV_DONTNEED) = 0
futex(0x3f8773f99d68, FUTEX_WAKE_PRIVATE, 1) = 1
mmap(0x3017e3ac0000, 520192, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x3017e3ac0000
munmap(0x3017e3b00000, 258048)          = 0
mprotect(0x3017e3ac0000, 262144, PROT_READ|PROT_WRITE) = 0
getpid()                                = 14793
readlink("/proc/self/exe", "/home/martin/mattermost/mattermo"..., 8191) = 42
getuid()                                = 1000
geteuid()                               = 1000
getgid()                                = 1000
getegid()                               = 1000
getuid()                                = 1000
geteuid()                               = 1000
getgid()                                = 1000
getegid()                               = 1000
mprotect(0x2da2d9f82000, 249856, PROT_READ|PROT_WRITE) = 0
mprotect(0x2da2d9f82000, 249856, PROT_READ|PROT_EXEC) = 0
mprotect(0x2da2d9f82000, 249856, PROT_READ|PROT_WRITE) = 0
mprotect(0x2da2d9f82000, 249856, PROT_READ|PROT_EXEC) = 0
stat("/home/martin/mattermost/resources/electron.asar", 0x7fffb64743d8) = -1 ENOENT (No existe el fichero o el directorio)
openat(AT_FDCWD, "/home/martin/mattermost/resources/electron.asar", O_RDONLY) = -1 ENOENT (No existe el fichero o el directorio)
openat(AT_FDCWD, "/home/martin/mattermost/resources/electron.asar", O_RDONLY) = -1 ENOENT (No existe el fichero o el directorio)
openat(AT_FDCWD, "/home/martin/mattermost/resources/electron.asar", O_RDONLY) = -1 ENOENT (No existe el fichero o el directorio)
openat(AT_FDCWD, "/home/martin/mattermost/resources/electron.asar", O_RDONLY) = -1 ENOENT (No existe el fichero o el directorio)
openat(AT_FDCWD, "/home/martin/mattermost/resources/electron.asar", O_RDONLY) = -1 ENOENT (No existe el fichero o el directorio)
ioctl(2, TCGETS, 0x7fffb6473e90)        = -1 ENOTTY (Función ioctl no apropiada para el dispositivo)
fstat(2, {st_mode=S_IFREG|0664, st_size=220080, ...}) = 0
madvise(0x3f87743b3000, 36864, MADV_DONTNEED) = 0
madvise(0x3f87743a2000, 69632, MADV_DONTNEED) = 0
madvise(0x3f8774399000, 36864, MADV_DONTNEED) = 0
madvise(0x3f8774399000, 36864, MADV_DONTNEED) = 0
mprotect(0x2da2d9f82000, 249856, PROT_READ|PROT_WRITE) = 0
mprotect(0x2da2d9f82000, 249856, PROT_READ|PROT_EXEC) = 0
mprotect(0x2da2d9f82000, 249856, PROT_READ|PROT_WRITE) = 0
mprotect(0x2da2d9f82000, 249856, PROT_READ|PROT_EXEC) = 0
write(2, "internal/modules/cjs/loader.js:6"..., 466internal/modules/cjs/loader.js:630
    throw err;
    ^

Error: Cannot find module '/home/martin/mattermost/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:850:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
) = 466
madvise(0x3f8774037000, 4096, MADV_DONTNEED) = 0
madvise(0x3f8774032000, 4096, MADV_DONTNEED) = 0
madvise(0x3f8774356000, 12288, MADV_DONTNEED) = 0
madvise(0x3f8774381000, 16384, MADV_DONTNEED) = 0
madvise(0x3f87742f2000, 20480, MADV_DONTNEED) = 0
madvise(0x3f877431e000, 24576, MADV_DONTNEED) = 0
madvise(0x3f87742cd000, 32768, MADV_DONTNEED) = 0
madvise(0x3f8774341000, 12288, MADV_DONTNEED) = 0
close(29)                               = 0
close(30)                               = 0
madvise(0x3f8773e21000, 4096, MADV_DONTNEED) = 0
madvise(0x3f8773e22000, 4096, MADV_DONTNEED) = 0
madvise(0x3f8773e0d000, 4096, MADV_DONTNEED) = 0
madvise(0x3f8773e0e000, 4096, MADV_DONTNEED) = 0
madvise(0x3f8773e0f000, 4096, MADV_DONTNEED) = 0
madvise(0x3f8773e10000, 4096, MADV_DONTNEED) = 0
madvise(0x3f8773e11000, 4096, MADV_DONTNEED) = 0
madvise(0x3f8773e12000, 4096, MADV_DONTNEED) = 0
madvise(0x3f8773e13000, 4096, MADV_DONTNEED) = 0
madvise(0x3f8773e14000, 4096, MADV_DONTNEED) = 0
madvise(0x3f8773e15000, 4096, MADV_DONTNEED) = 0
madvise(0x3f8773e16000, 4096, MADV_DONTNEED) = 0
madvise(0x3f8773e18000, 4096, MADV_DONTNEED) = 0
madvise(0x3f8773e19000, 4096, MADV_DONTNEED) = 0
exit_group(1)                           = ?
+++ exited with 1 +++
```

**Comment by Willyfrog** [comment]
given that you saw this warning:

> Even though I extracted the binaries to a clean directory, I was prompted with a pop-up window indicating that there were existing files that would be replaced. Odd.

I'm guessing you wrote over a previous installation of the app, can you try using a new directory or removing the original one and see if you still get the warning and where it is actually unarchiving the files? and also see if the problem reproduces

**Comment by martinmarques** [comment]
When I say *clean directory* I meant a newly created directory.

**Comment by Willyfrog** [comment]
yes, i understood, but that pop up window should not happen, right? I don't know of a way to unarchive into a new directory and get it (which doesn't mean there isn't a way, it just never happened to me). So i'd recomend double checking just to ensure we are not trying to debug something that is solved by a clean install.

**Comment by martinmarques** [comment]
Oh dear. It seems there was something wrong with where `ark` was placing the target files (seems with the years I've become too lazy and keep using these GUI).

I downloaded the binary to disk and manually used `tar` from the console (what I should have done to start with, or at least after the first failure) and now it works just fine.

Sorry for the noise and the time wasted.
