### ISSUE TITLE
Progress of download file

### ISSUE THREAD

**Issue by JinZhuXing** [mattermost/desktop#1222]
Please add a progress for download file.
When I send file (upload file), I can see the progress for uploading file.
![image](https://user-images.githubusercontent.com/15034343/75688938-4c8b1d00-5cdb-11ea-8045-00526c855610.png)

But, when I download file, I can't see the progress.
Also, please notify me when the downloading finished.
Thank you.

**Comment by devinbinnie** [comment]
@JinZhuXing we have an internal ticket for this already: https://mattermost.atlassian.net/browse/MM-22239
Hoping to work on it soon :)
