### ISSUE TITLE
Application hides behind the taskbar upon minimize to maximize with a left window taskbar

### ISSUE THREAD

**Issue by Jeffreyjelly** [mattermost/desktop#1228]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

Features get hidden behind a left mounted windows task bar.

**Environment**
- Operating System:
Windows 10 Pro
- Mattermost Desktop App version: X.X.X 
4.4.0
- Mattermost Server version: X.X.X 
5.16.2

**Steps to reproduce**
Set the task bar to be docked on the left side of your window with windows 10 and proceed to minimize and re-expand the mattermost window.

**Expected behavior**
Align the window to the task bar and not behind it.

**Observed behavior**
Application settings are hidden behind the taskbar.

**Possible fixes**

**Comment by Willyfrog** [comment]
hello @Jeffreyjelly thanks for ther report!
i'm trying to reproduce but I'm sure I'm doing something wrong

can you record a video/gif on how do you get it to happen? I'd like to make sure I'm not confusing any steps.

**Comment by Jeffreyjelly** [comment]
![mattermostMinimizeFail1of2](https://user-images.githubusercontent.com/4224835/76231702-fdbe1580-61fb-11ea-895a-330c4b2b59ac.png)
![mattermostMinimizeFail2of2](https://user-images.githubusercontent.com/4224835/76231706-ff87d900-61fb-11ea-83b0-26832f46547d.png)

**Comment by Jeffreyjelly** [comment]
If that's not enough to recreate the problem let me know.

**Comment by Jeffreyjelly** [comment]
looks to be also related to #1225

**Comment by amyblais** [comment]
Ticket created here: https://mattermost.atlassian.net/browse/MM-23195.

**Comment by amyblais** [comment]
This is now fixed in v4.4.1 dot release,

**Comment by Jeffreyjelly** [comment]
This same problem is happening with a left aligned taskbar in windows.

(two monitor setup)
Minimize on the non-main display and it reopens on the main monitor display (seems to have forgotten location) while being hidden behind the taskbar

Mattermost Version: 5.16.2
Database Schema Version: 5.16.0
Database: mysql

**Comment by amyblais** [comment]
Our supported server versions include v5.19 and later versions. Would you be open to upgrading to see if it helps with the issue? Also, are you currently on desktop app v4.4.1?

**Comment by Jeffreyjelly** [comment]
I'm on 4.4.0 for the desktop app, I'll try and see if I can push for some updates

**Comment by amyblais** [comment]
The latest version of the desktop app can be dowloaded here https://mattermost.com/download/#mattermostApps.

**Comment by Jeffreyjelly** [comment]
4.4.2 fixed it. Thanks.
