### ISSUE TITLE
Problem when copying link

### ISSUE THREAD

**Issue by jackyes** [mattermost/desktop#123]
Hi, 

On windows, sending a link to a file example:

`[ Document](file://///192.168.1.2/path/to/file.pdf)`

Create a link that do nothing if clicked and can't be copyed to clipboard.
is this normal?

**Comment by yuya-oc** [comment]
Excuse me, could you describe that in detail (step by step)? I couldn't understand the operation which you did.

**Comment by jackyes** [comment]
if a post this string:

`[ Document](file://///192.168.1.2/path/to/file.pdf)`

On the web i can click on the generated link but don't open the file (security reason?), but i can copy the adress and past in in file manager in order to open the file.
On the desktop app i can only copy the text of the message, so if i make a copy/past of that link, the result will be " Document".

Sorry for my bad english :(

**Comment by yuya-oc** [comment]
Thank you for your description. Maybe need to implement 'copy' for the case.

**Comment by jasonblais** [comment]
Would anyone from the community be open to helping with a PR to address this?

**Comment by jnugh** [comment]
I'll try to get [electron-context-menu](https://www.npmjs.com/package/electron-context-menu) to work, to fix this issue :construction_worker:

**Comment by jasonblais** [comment]
Thanks @jnugh! Highly appreciate it,

as per our discussion in [Desktopp App channel](https://pre-release.mattermost.com/core/pl/6giis1nbqifoidnnz3ouqzmoga), we'll move this issue from v1.3, but would love to have this issue for v1.4

**Comment by akashnimare** [comment]
@jnugh is it resolved?

**Comment by jnugh** [comment]
Not yet, I hope to get to it this week

**Comment by akashnimare** [comment]
@jnugh electron-context-menu is pretty easy to use. I'm using it [here](https://github.com/zulip/zulip-electron). Let me know if you need any help.

**Comment by jnugh** [comment]
The problem here, is that the right click event is caught by react.js. Just embedding the context menu library would be too easy I guess ;)

**Comment by akashnimare** [comment]
haha, yes definitely.

**Comment by jnugh** [comment]
This linked fix depends on https://github.com/sindresorhus/electron-context-menu/pull/15 I will open a PR after this one got meregd

**Comment by jasonblais** [comment]
Perfect, thanks @jnugh! 

Looks like the PR was merged, would you have a PR available to submit in the desktop repo? 

This would be a huge improvement for user experience, really looking forward to it :)
