### ISSUE TITLE
Permalink in private chat while in a team that someone doesn't have access to doesn't allow them to click the permalink

### ISSUE THREAD

**Issue by Jeffreyjelly** [mattermost/desktop#1230]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System:
Windows 10 Pro
- Mattermost Desktop App version: X.X.X 
4.4.0
- Mattermost Server version: X.X.X 
5.16.2

**Steps to reproduce**
Permalink a private chat in a private chat while in a group someone doesn't have access to and send it to them and they can't use the permalink.

**Expected behavior**
Permalinks to private chats shouldn't be team specific.

**Observed behavior**
![permalinkFail](https://user-images.githubusercontent.com/4224835/76102346-df5ade80-5f9d-11ea-8b08-cee1175d880c.png)

**Possible fixes**

**Comment by Willyfrog** [comment]
Hellow @Jeffreyjelly thanks for reporting!
this is a webapp related issues, for those we use the https://github.com/mattermost/mattermost-server/issues/ repo.

Since I can't move the issue to another repo, could you reopen the issue there so it gets much more visibility?
