### ISSUE TITLE
[Feature] Windows distribution via Chocolatey

### ISSUE THREAD

**Issue by kwill** [mattermost/desktop#124]
When packaging for Windows, please consider Chocolatey as a distribution channel.

Chocolatey is a distribution tool for Windows applications, including many free software applications (for example, https://chocolatey.org/packages/pidgin). It allows an end-user to get application updates somewhat like using apt or yum on GNU/Linux.

https://github.com/chocolatey/choco/wiki/ChocolateyFAQs
https://github.com/chocolatey/choco/wiki/Moderation

(Separated out from #103 )

**Comment by lholman** [comment]
I'd be happy to work on this if there is a genuine need, do we have any idea of how many people are using the MM client for Windows?

**Comment by lunawesley9** [comment]
my whole company is using MM client for windows...

**Comment by lholman** [comment]
@lunawesley9 @yuya-oc A few stats, based on github releases below.
Using the github API we can get the number of downloads per asset `download_count` as follows for the latest stable release (v1.1.1)

`GET https://api.github.com/repos/mattermost/desktop/releases/tags/v1.1.1`

OS | Download count
------------ | -------------
mattermost-desktop-1.1.1-linux-ia32.tar.gz  | 61
mattermost-desktop-1.1.1-linux-x64.tar.gz  | 861
mattermost-desktop-1.1.1-osx.tar.gz  | 1397
mattermost-desktop-1.1.1-win32.zip  | 207
mattermost-desktop-1.1.1-win64.zip  | 2097

That's in a month for that release, the previous two releases are similar numbers for the Windows platform.

From this, it would seem to make sense to do a Chocolatey installer that targets 64 BIT Windows as a minimum.

**Comment by jasonblais** [comment]
Thanks @kwill, @lholman, @lunawesley9  for your suggestions and feedback here.

We have added an experimental version of the Windows installer for the upcoming Desktop App release, v1.3. I encourage you to take a look, either by testing [our release candidate](https://github.com/mattermost/desktop/issues/198 or by downloading the new version, which will be released on July 16th.

We're beginning to move feature requests from GitHub issues to our feature idea forum to keep all feature ideas in one place. I have [added your suggestion there](https://mattermost.uservoice.com/forums/306457-general/suggestions/15175773-windows-distribution-via-chocolatey) so it can be discussed, upvoted and considered for a ticket accepting pull requests?

You get 10 votes in the feature idea forum, and each one influences the future of the project.

**Comment by kwill** [comment]
Thanks! (I've voted) Should I close this issue?

**Comment by jasonblais** [comment]
Perfect, thanks @kwill! You may go ahead and close this issue. We'll be monitoring votes on UserVoice

**Comment by hansnull** [comment]
https://chocolatey.org/packages/mattermost-desktop

**Comment by Razzeee** [comment]
Thank you! Appreciated!

**Comment by jasonblais** [comment]
This is fabulous, thank you @hansnull!! 

We'd like to welcome you to join the installers discussion on our nightly builds server if you like, would be great to see you there and hear more about the project: https://pre-release.mattermost.com/core/channels/installers-and-images
