### ISSUE TITLE
Configurable background color behind your own messages

### ISSUE THREAD

**Issue by mdiller** [mattermost/desktop#1241]
Mattermost has a particular feature where it highlights your own messages. Multiple people (myself included) would very much prefer that it did not do this. An issue was raised on the mattermost-server repo asking to remove the feature ([Issue #5072](https://github.com/mattermost/mattermost-server/issues/5072)). The issue was closed but there are still a lot of people not happy with it. A solution was suggested which was to allow the user to simply be able to configure this via the theme. This seems like it would be a very straightforward solution with minimal repercussions that would let the user configure it to be how they want. Would this not be trivial to implement?

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @mdiller.

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by mdiller** [comment]
@amyblais Thanks for getting back to me on this! I checked the forum and found this post: ([Disable highlighting of own messages](https://mattermost.uservoice.com/forums/306457-general/suggestions/16635304-disable-highlighting-of-own-messages)) which has 39 votes. I could create a new one but I doubt it would get as many votes as this one has. If I was interested in implementing, could I start a pull request based on the interest of the people in that post? Or should I wait to start a pull request until I can get a post noticed and approved on the forum?

**Comment by Willyfrog** [comment]
> If I was interested in implementing, could I start a pull request based on the interest of the people in that post?

Absolutely! we might have to review and see how to better benefit the whole community, but the first step is that one :)

Also, bear in mind that would be a change in the https://github.com/mattermost/mattermost-webapp/ repo, as this is not a desktop issue

**Comment by mdiller** [comment]
Ok thanks! I might take a look at doing this sometime soon, we'll see.

**Comment by Willyfrog** [comment]
let us know if you want to start it, that way we might be able to help with directions on what would be the best way to handle that :)

**Comment by asaadmahmood** [comment]
@mdiller We've removed it :) So this can be closed as no longer valid.

**Comment by esethna** [comment]
@mdiller thanks for the feedback, this is actually already implemented in our master branch https://mattermost.atlassian.net/browse/MM-22963

**Comment by mdiller** [comment]
Fantastic, thanks!
