### ISSUE TITLE
make download folder configurable/remember last selected folder

### ISSUE THREAD

**Issue by 2019-05-10** [mattermost/desktop#1250]
Download folder should be configurable -- I am no fan of one-folde3r-for-all apps, but need to decide where each app stores its stuff.

**Comment by amyblais** [comment]
@Willyfrog Do you know if this is a bug or a feature request?

**Comment by Willyfrog** [comment]
it is a feature request, currently we don't store any info of previously downloaded files, nor have a predefined location

**Comment by Willyfrog** [comment]
also, there is a ticket for this feature: https://mattermost.atlassian.net/browse/MM-22013
