### ISSUE TITLE
Could not find the program '/usr/local/bin/firefox'

### ISSUE THREAD

**Issue by 2019-05-10** [mattermost/desktop#1253]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Hitting a link in a message results in an error popup saying

Could not find the program '/usr/local/bin/firefox'

which is true, since it doesn't exist.
- It's unclear why MM tries to open that path at all.
- There's no way in the very very limited settings to configure anything of that kind.

**Environment**
- Operating System: Linux
- Mattermost Desktop App version: 4.4.0
- Mattermost Server version: 5.17.1

**Steps to reproduce**

click a link

**Expected behavior**

use system default or ask

**Observed behavior**

MM tries to open non-existant path and pops up a message "Could not find the program '/usr/local/bin/firefox'"

**Possible fixes**

- don't presume
- use system defaults as other programs are used to do
- ask and store
- provide a setting

**Comment by Willyfrog** [comment]
Hi, thanks for the report, but mattermost does not choose the browser, it is based on OS configuration, so you'll need to check how that's configured for your distro.

If it is Ubuntu, you can check the following page: https://askubuntu.com/questions/16621/how-to-set-the-default-browser-from-the-command-line

**Comment by 2019-05-10** [comment]
in the OS no such configuration exists:
/etc/alternatives/x-www-browser -> /usr/bin/vivaldi-stable

**Comment by 2019-05-10** [comment]
Please, explain, how exactly MM asks the OS (and nevertheless, stuff like needs to be configurable on a per-app basis)

**Comment by Willyfrog** [comment]
> Please, explain, how exactly MM asks the OS (and nevertheless, stuff like needs to be configurable on a per-app basis)

we are using electron's method for it: https://www.electronjs.org/docs/api/shell#shellopenexternalurl-options

**Comment by Willyfrog** [comment]
as mentioned above, closing the issue as it is most likely related to OS configuration. Linux sometimes is a bit complex for configuration (interacting configuration for different desktops for example).
Feel free to reopen if we can help in any way.

**Comment by 2019-05-10** [comment]
After a lot of searching I found  a configuration in some KDE config file (kdeglobals) -- a setting I don't even recall to have made.
In all these years, Mattermost is the only application ever having read/used that setting.
+1 to have that configurable in settings as all other applications do.

**Comment by Willyfrog** [comment]
you can [request it as a new feature](https://mattermost.uservoice.com/forums/306457-general) and see if others would like the same :)
