### ISSUE TITLE
Mac desktop client focuses on Search-box instead of Type-box when replying to a thread

### ISSUE THREAD

**Issue by jby** [mattermost/desktop#1254]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Mac desktop client focuses on Search-box instead of Type-box when replying to a thread

**Environment**
- Operating System: macOS 10.15.4
- Mattermost Desktop App version: 4.4.0 (4.4.0.5682)
- Mattermost Server version: 5.19.1

**Steps to reproduce**
Go to input field, press "reply", either by clicking the 'reply-arrow' or by typing S-arrowup
**Expected behavior**
Reply field opened, and focus in that field
**Observed behavior**
Reply field opened, focus in "Search" field instead

**Comment by amyblais** [comment]
@jby This has been fixed in server v5.20 release.

**Comment by jby** [comment]
Oh, I thought it was a desktop problem since I don't see it in browser.
