### ISSUE TITLE
Red dot on taskbar icon does not appear if "Use small taskbar buttons" is enabled.

### ISSUE THREAD

**Issue by wtjones** [mattermost/desktop#1265]
I confirm (by marking "x" in the [ ] below: [x]):

- [x ] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Red dot on taskbar icon does not appear if "Use small taskbar buttons" is enabled.

**Environment**
- Operating System: Win 10
- Mattermost Desktop App version: 4.2.0 
- Mattermost Server version: 5.17.3 

**Steps to reproduce**
Have an event causes the red dot to appear on the taskbar icon.
Switch Windows Taskbar settings to small buttons

**Expected behavior**
Small taskbar icon appears with the red dot

**Observed behavior**
Small taskbar icon appears without the red dot

Sorry for the poor capture. I was not able to take direct screenshots.

![image](https://user-images.githubusercontent.com/1031558/79017772-c5319480-7b37-11ea-8dfd-35c7c719affb.png)
![image](https://user-images.githubusercontent.com/1031558/79017712-9f0bf480-7b37-11ea-8738-4f89cd1b60c2.png)

**Possible fixes**

**Comment by esethna** [comment]
Thanks for the report! @amyblais can we file a ticket for the above ^

**Comment by amyblais** [comment]
@wtjones Do you see this issue on desktop v4.4.0?

**Comment by wtjones** [comment]
@amyblais Unfortunately the only Windows environment I have at the ready has 4.2 deployed.

**Comment by devinbinnie** [comment]
Created a JIRA ticket: https://mattermost.atlassian.net/browse/MM-40571

**Comment by devinbinnie** [comment]
Looking into it, it looks like Windows disables badges when 'small taskbar icons' are enabled. Since this doesn't look like something we can fix, I'll have to close this.
