### ISSUE TITLE
The mattermost client cannot be closed.

### ISSUE THREAD

**Issue by etienne-monier** [mattermost/desktop#1266]
I confirm (by marking "x" in the [ ] below: [x]):

- [x ] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
I cannot close the mattermost client normally.

**Environment**
- Operating System: Ubuntu 18.04 LTS with i3wm environment.
- Mattermost Desktop App version: 4.4.0
- Mattermost Server version: 5.20.2 (I use Framteam) 

**Steps to reproduce**
- Download Linux .tar.gz for 64 bits (here)[https://mattermost.com/download/]. 
- Extract it at ~/.mattermost.
- Run `create_desktop_file`
- Open mattermost.

**Expected behavior**

I use i3wm. When closing window with i3wm or when clicking on the upper right cross, the application should close.

**Observed behavior**

It does not close. I must kill the process to close it.

When running from command-line, I get

```
config.autostart has been configured: true
[12885:0413/150410.591125:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
```
but all this appears at launching. Nothing appears when I try to close it.

**Possible fixes**

Arg, sorry. No idea.

**Comment by Willyfrog** [comment]
if you have the tray icon, closing on the window button, or on unity's taskbar only hides the window but doesn't close it. Disabling the tray icon on preferences menu or closing from there should close the app.

I'm closing the issue as this is expected behaviour, but feel free to reopen if you have any new info.

**Comment by etienne-monier** [comment]
Well, It seems I was not clear.

I'm using [i3wm](https://i3wm.org/) which is a [tiling window manager](https://en.wikipedia.org/wiki/Tiling_window_manager). When the window is open, it takes some place at the screen. When I close it, the surrounding windows get bigger to occupy the place. I've got also a tray icon.

When I use the i3wm kill command to close the Mattermost window, it does not close. The window is still here. I still have both the window and the tray icon.

**Comment by Willyfrog** [comment]
Hi, I know i3, although never used it, but used other tiling WM in the past.

As I said earlier, our current code has a mechanism to minimize to tray if a user closes the window. Why i3wm is keeping the window, I really don't know as I'm not sure if it differs on desktop api implementation from ubuntu's Unity or Gnome.

from a quick glance from google I'd say it's a common problem on i3: https://www.reddit.com/r/i3wm/comments/63hzpo/closing_windows_that_wont_close/

if you happen to get any extra info, don't hesitate in reopening the issue (you should see a reopen button below)
