### ISSUE TITLE
Auto reload the team after failed to load

### ISSUE THREAD

**Issue by yuya-oc** [mattermost/desktop#127]
From the forum: [When the team URL can't be loaded during app startup, automatically reload every 30 seconds – Mattermost Feature Request Forum](https://mattermost.uservoice.com/forums/306457-general/suggestions/13526514-when-the-team-url-can-t-be-loaded-during-app-start)

**Comment by Razzeee** [comment]
Some nice to haves we also could do on top of this is rendering the "countdown" to the next refresh. And maybe show a link to refresh now.

**Comment by yuya-oc** [comment]
Would you open a new issue? The closed issue is hard to track. The refresh button seems to be nice.
