### ISSUE TITLE
Missing copy image option in desktop client

### ISSUE THREAD

**Issue by caspChristian** [mattermost/desktop#1275]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Right clicking on an image only shows "save image" no option to copy.
(I also think that the "click on image" starts the download is a bug, but it is there on the web as well)

**Environment**
- Operating System: Windows 1
- Mattermost Desktop App version: 4.1.12
- Mattermost Server version: 5.20.1

**Steps to reproduce**
send a message with an image, click the image in the sent message, right click,

**Expected behavior**
See copy image option.

**Observed behavior**
There is no copy image option on desktop app, in web browser it is.

**Possible fixes**

Can you show the raw browser menu instead?

**Comment by Willyfrog** [comment]
can you upgrade to 4.4 or 4.4.1 (will be available today), I see the copy option on my right click menu.

**Comment by caspChristian** [comment]
Indeed 4.4 has copy image. Thanks and sorry for the nioise.
The whole client still hangs for several minutes tho when I accidentally click on the image after it pops open, it won't respond until the save dialog is closed (but before being able to close it it takes several minutes) The dalay and hang part is a windows issue due to filesystem over a slow network link. However, opening the save dialog in cases other than clicking download or save image, should bee seen as a bug.
