### ISSUE TITLE
Notification icon to big in Ubuntu

### ISSUE THREAD

**Issue by tomasnorre** [mattermost/desktop#1276]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [ ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
The notification icon in the TopPanel is to big on ubuntu

**Environment**
- Operating System: Linux Ubuntu Budgie 20.04
- Mattermost Desktop App version: 4.0.0
- Mattermost Server version: 5.20.1 and 5.18.0 (To different connections)
**Steps to reproduce**

Start mattermost with `Show icon in the notification area` checked
This is a problem regardless of if I get new messages or not. It's not scaling. 

**Expected behavior**
I would expect the notification icon to scale accordingly to TopPanel settings, so that it doesn't overlap with my e.g. Browser window, see screenshot. 

**Observed behavior**

![mattermost_notify](https://user-images.githubusercontent.com/1212481/80091687-cb753700-8561-11ea-8cc6-46f296618c24.png)

**Possible fixes**
The icon is svg so should be scaleable. 
https://github.com/mattermost/desktop/blob/master/resources/linux/icon.svg

**Comment by amyblais** [comment]
Do you see the same issue on desktop app v4.4.1?

**Comment by tomasnorre** [comment]
Unfortunately yes. 
![mattermost_4 4 1](https://user-images.githubusercontent.com/1212481/80563593-c09c2580-89eb-11ea-985e-1a583a0701d0.png)

**Comment by amyblais** [comment]
Does this seem similar to this issue: https://github.com/mattermost/desktop/issues/317?

**Comment by tomasnorre** [comment]
It does a lot, I think it's a matter if we call it `tray` or `topPanel`, but from screenshots it looks like the same issue. 

We can close this and mark it as duplicate.

Sorry should have investigated better for know issues before creating a new one.

**Comment by tomasnorre** [comment]
I don't know if this is of importance to you. But I've experienced this with Slack and rambox too, so don't know if it's general Ubuntubudgie problem in my case or if it's all apps having the same issue. 

Sounds more like the first one.

**Comment by amyblais** [comment]
Closing, this is getting fixed for v5.0,
