### ISSUE TITLE
Popup window on notification (Windows 10, Desktop Client)

### ISSUE THREAD

**Issue by savegame** [mattermost/desktop#1284]
Add option to popup mattermost application window when you have notification. 

At this point, if you miss the notification, you can forget about the chat for a long time and not reply to messages. In Windows 10, the display of a new message is very low and you can't configure a more effective notification.

**Comment by Willyfrog** [comment]
hi! thanks for the report. I'm aware of the problem and i've built a smaller project to help electron team to debug the issue.
hopefully we are able to solve it soon

**Comment by devinbinnie** [comment]
Closing as inactive.
