### ISSUE TITLE
gitlab authentication not working anymore (gitlab 12.10.3)

### ISSUE THREAD

**Issue by ArnY** [mattermost/desktop#1291]
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Since gitlab 12.10.2 mattermost-desktop can't submit the authentication gitlab's forms (ldap and standard logins)

**Environment**
- Operating System:  Linux Ubuntu 18.04
- Mattermost Desktop App version: 4.2.1 
- Mattermost Server version: 5.21.0 

**Steps to reproduce**
When on the mattermost server's login page, choose "log in with gitlab", then on gitlab, enter your credentials either using ldap or standard forms.

**Expected behavior**
As it used before, gitlab should authenticate you and forward you back to mattermost where you should be automatically logged on.

**Observed behavior**
The gitlab's ldap authencation form just reload the form when submitting, the credentials aren"t submitted at all. The standard form returns a 422 "The change you requested was rejected." error.

On both firefox and Chrome the problem doesnt occurs. Users can logon properly on mattermost using gitlab.

**Possible fixes**

**Comment by Willyfrog** [comment]
Hello and thanks for the report!

have you tried with a more recent release? [4.4.2 just got out](https://github.com/mattermost/desktop/releases/tag/v4.4.2)

**Comment by ArnY** [comment]
Excellent, it does fix the problem! Thanks!
