### ISSUE TITLE
special characters used in gpo DefaultServerList

### ISSUE THREAD

**Issue by rular** [mattermost/desktop#1293]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: Windows 10 x64
- Mattermost Desktop App version: 4.4.2
- Mattermost Server version: 5.22.3

**Steps to reproduce**
use one special character from my list (ÄÖÜäöü) and insert in gpo DefaultServerList as name of the url. Wait for activiation of gpo or do it by "gpupdate /force" and restart mattermost desktop.
![GPO_defaultserverlist](https://user-images.githubusercontent.com/3407850/81804925-45259280-951a-11ea-879d-60ce9ae492ff.PNG)

**Expected behavior**
Special characters should be displayed in tab server of the desktop app.

**Observed behavior**
I see just black squares with white questionmarkes for every special character I use inside the name of the server tab
![Servername Tab](https://user-images.githubusercontent.com/3407850/81804948-4e166400-951a-11ea-8771-8890e53c9172.PNG)

**Comment by Willyfrog** [comment]
ticket created: https://mattermost.atlassian.net/browse/MM-25122

**Comment by amyblais** [comment]
Closing, this was fixed in v4.7,
