### ISSUE TITLE
render percent encoding to readable characters in links pasted into chat

### ISSUE THREAD

**Issue by aol-nnov** [mattermost/desktop#1294]
When pasted into chat, render percent-encoded URLs into readable characters

i.e. instead of displaying https://ru.wikipedia.org/wiki/%D0%93%D0%B5%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B5_%D0%BA%D0%BE%D0%BE%D1%80%D0%B4%D0%B8%D0%BD%D0%B0%D1%82%D1%8B

show https://ru.wikipedia.org/wiki/Географические_координаты

I propose changing text only, not the href of an `<a>` tag

P.S. uservoice is banned in our country, so, I'm unable to post there, unfortunately

**Comment by Willyfrog** [comment]
do you mean to have this on the post? or somewhere else? if it is in the post, that would be an issue to be tackled on the [server repo](https://github.com/mattermost/mattermost-server/issues) can you reopen it there?
closing the issue for now, but feel free to reopen if you think it is still relevant

**Comment by aol-nnov** [comment]
> do you mean to have this on the post?

@Willyfrog I mean the chat log - a large area where all discussion is displayed.

I thought url text rendering is performed on the client.. Okay, will reopen in the server repo.

**Comment by Willyfrog** [comment]
It is performed on the client side, but on the webapp part of it (webapp issues are in the server repo), not the desktop client.

**Comment by aol-nnov** [comment]
okay, gotcha! thanks!
