### ISSUE TITLE
Build fails with unhandled error event

### ISSUE THREAD

**Issue by noahsmindfuck** [mattermost/desktop#1296]
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
build fails with unhadled error event
Sorry for the shitty Github Markup but the 'code block' markup is super fucked

**Environment**
- Operating System: Linux 5.6.13-arch1-1 #1 SMP PREEMPT Thu, 14 May 2020 06:52:53 +0000 x86_64 GNU/Linux
- Mattermost Desktop App version: 5.23.0 
- Mattermost Server version: X.X.X 

**Steps to reproduce**
Build mattermost-desktop with Arch User Repository helper Pikaur

**Expected behavior**

build should work fine

**Observed behavior**

First there was no dependency check for cross-env:

> sh: cross-env: command not found
> npm ERR! code ELIFECYCLE
> npm ERR! syscall spawn
> npm ERR! file sh
> npm ERR! errno ENOENT
> npm ERR! mattermost-webapp@0.0.1 build: `cross-env NODE_ENV=production webpack --display-error-details --verbose`
> npm ERR! spawn ENOENT
> npm ERR! 
> npm ERR! Failed at the mattermost-webapp@0.0.1 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/herbert/.npm/_logs/2020-05-19T08_33_35_761Z-debug.log
> make[1]: *** [Makefile:65: build] Error 1
> make[1]: Leaving directory '/home/herbert/.cache/pikaur/build/mattermost/src/mattermost-webapp-5.23.0'
> make: *** [build/release.mk:35: build-client] Error 2
> ==> ERROR: A failure occurred in build().

After installing nodejs-cross-env I just receive

> Build Linux amd64
> env GOOS=linux GOARCH=amd64 go build -o /home/herbert/.cache/pikaur/build/mattermost/src/src/github.com/mattermost/mattermost-server/bin  -mod=vendor -trimpath -ldflags '-X "github.com/mattermost/mattermost-server/v5/model.BuildNumber=5.23.0-1" -X "github.com/mattermost/mattermost-server/v5/model.BuildDate=2020-05-19 08:37:09" -X "github.com/mattermost/mattermost-server/v5/model.BuildHash=5.23.0-1 Arch Linux (x86_64)" -X "github.com/mattermost/mattermost-server/v5/model.BuildHashEnterprise=none" -X "github.com/mattermost/mattermost-server/v5/model.BuildEnterpriseReady=false" -linkmode external -extldflags '-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now' -s -w' ./...
> # github.com/mattermost/mattermost-server/v5/app/layer_generators
> loadinternal: cannot find runtime/cgo
> # github.com/mattermost/mattermost-server/v5/cmd/platform
> loadinternal: cannot find runtime/cgo
> # github.com/mattermost/mattermost-server/v5/plugin/checker
> loadinternal: cannot find runtime/cgo
> # github.com/mattermost/mattermost-server/v5/plugin/interface_generator
> loadinternal: cannot find runtime/cgo
> # github.com/mattermost/mattermost-server/v5/store/layer_generators
> loadinternal: cannot find runtime/cgo
> Building mattermost web app
> cd ../mattermost-webapp && make build
> make[1]: Entering directory '/home/herbert/.cache/pikaur/build/mattermost/src/mattermost-webapp-5.23.0'
> Building mattermost Webapp
> rm -rf dist
> npm run build
> 
> > mattermost-webapp@0.0.1 build /home/herbert/.cache/pikaur/build/mattermost/src/mattermost-webapp-5.23.0
> > cross-env NODE_ENV=production webpack --display-error-details --verbose
> 
> events.js:292
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: spawn webpack ENOENT
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
>     at onErrorNT (internal/child_process.js:468:16)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21)
> Emitted 'error' event on ChildProcess instance at:
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
>     at onErrorNT (internal/child_process.js:468:16)
>     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'spawn webpack',
>   path: 'webpack',
>   spawnargs: [ '--display-error-details', '--verbose' ]
> }
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! mattermost-webapp@0.0.1 build: `cross-env NODE_ENV=production webpack --display-error-details --verbose`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the mattermost-webapp@0.0.1 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/herbert/.npm/_logs/2020-05-19T08_37_25_323Z-debug.log
> make[1]: *** [Makefile:65: build] Error 1
> make[1]: Leaving directory '/home/herbert/.cache/pikaur/build/mattermost/src/mattermost-webapp-5.23.0'
> make: *** [build/release.mk:35: build-client] Error 2
> ==> ERROR: A failure occurred in build().

**Comment by Willyfrog** [comment]
I think you are building the webapp+server? if so, can you reopen this on the https://github.com/mattermost/mattermost-server repo?

If you are indeed trying to get the desktop built, can you check what sources you downloaded? there is no go code on the desktop, and cross-env is actually on the [dev dependencies](https://github.com/mattermost/desktop/blob/master/package.json#L54)

**Comment by Willyfrog** [comment]
closing the issue
