### ISSUE TITLE
Alt-Key Handling broken if alt is used to switch workspaces

### ISSUE THREAD

**Issue by patric42** [mattermost/desktop#1297]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
When using alt-<key> to switch workspaces, switching back towards MD, the focus is set to the three-dot-menu.
The error seems to happen in main.js:550, where, after switching away, altLastPressed is set true, and when returning, everything seems as if alt was pressed and released.
My suggestion would be to monitor focus state of the window, if it's lost inbetween, to set altLastPressed to false to avoid this.

**Environment**
- Operating System: Pop OS 20.04
- Mattermost Desktop App version: 4.4.2
- Mattermost Server version: 5.21.0

**Steps to reproduce**
- Set up to workspaces and assign shortcut keys alt-1 to first, alt-2 to the second.
- Open MD on first workspace
- Focus the input text field on MD
- press alt-2 to switch to the second desktop
- press alt-1 to return to MD, but keep alt pressed
- you can see the text field still focused, the cursor blinking
- now release alt
- the focus is on the three-dot-menu.

**Expected behavior**
The focus after alt-1 should stay in the text field, as I just switched apps.

**Observed behavior**
See above. Focus is on three-dot-menu.

**Possible fixes**
Described above

**Comment by Willyfrog** [comment]
you can try https://github.com/mattermost/desktop/releases/tag/v4.7.0-rc6 to see if https://github.com/mattermost/desktop/pull/1619 fixes theproblem

**Comment by patric42** [comment]
Can confirm that it fixes the problem.

Thanks a lot :-)

**Comment by Willyfrog** [comment]
@patric42 can you check the latest 5.0RC? I think there is another fix in it for the problem, so if you could double check that would be great

**Comment by devinbinnie** [comment]
@patric42 Does this still reproduce for you on v5.0.2?

**Comment by patric42** [comment]
Yes, still :(
