### ISSUE TITLE
[Windows]: Full Screen mode turns off on restart

### ISSUE THREAD

**Issue by PetbkA** [mattermost/desktop#1298]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
If Full Screen mode was enabled, it turns off after restarting the app.

**Environment**
- Operating System: Microsoft Windows 10 LTSC (version 1809) x64, fully patched;
- Mattermost Desktop App version: 4.4.2;
- Mattermost Server version: 5.21.

**Steps to reproduce**
- Open the app;
- Enable Full Screen mode by pressing F11 or _View → Toggle Full Screen_;
- Restart the app.

**Expected behavior**
App restarts with Full Screen mode enabled.

**Observed behavior**
App restarts with Full Screen mode disabled

**Comment by Willyfrog** [comment]
hi! thanks for the report.

I think that's the standard behaviour of windows. I've tested with chrome and edge and neither of them restart in full screen mode.

**Comment by PetbkA** [comment]
> I think that's the standard behaviour of windows. I've tested with chrome and edge and neither of them restart in full screen mode.

Indeed, my mistake was to think that Chrome behaves differently. Although in Chrome I can force Full Screen by setting _--start-fullscreen_ option which doesn't work in the app. Is there analogue for this?

**Comment by PetbkA** [comment]
Funny, I've found a ["reversed request"](https://github.com/mattermost/desktop/issues/538) which _required_ to restart without Full Screen.

This is very strange - usually the expected behavior is that the app should _preserve_ its settings on restart. May be this was done 'cause there were bugs with Full Screen that couldn't be fixed. For example, Full Screen mode is saved when restarting _Visual Studio Code_ which is also an Electron-based app.

If behavior can't be changed, it stilll would be nice to add some flag to start in Full Screen

**Comment by Willyfrog** [comment]
Yeah, I think having a flag makes sense, so people can force it if needed.

I created [a ticket](https://mattermost.atlassian.net/browse/MM-25484) for it

**Comment by devinbinnie** [comment]
Opening as HW.

Comment from JIRA ticket:

Some users might find useful to have a command line argument to force the app to start on fullscreen.

Flag should be fullscreen, with a short version of f. It should be a boolean flag, with false as default value.

In order to do so, we need to add the code for it on https://github.com/mattermost/desktop/blob/master/src/main/ParseArgs.js and make sure it validates correctly in https://github.com/mattermost/desktop/blob/master/src/main/Validator.js 

ideally, a mocha test to ensure this behaviour happens would be great if that’s possible.

if issue needs clarification, don’t hesitate to ask any question in the desktop channel: https://community.mattermost.com/core/channels/desktop-app

**Comment by coltoneshaw** [comment]
@devinbinnie - I'm wondering if this could / should be just a setting in preferences to enable it to always start in full-screen mode. 

In theory, there are three ways this could work:

- it could be ticked as a user enters full-screen mode to always open in full screen, and turned off if they exit full screen move. 
- simply a setting that says "If last mode was full screen, open next time in full screen." and automatically trigger it off after that.
- just this option below to always load in full screen when opened. ( feels annoying, but maybe someone would like it? )

![Screen Shot 2022-01-07 at 2 03 38 PM](https://user-images.githubusercontent.com/46071821/148593912-fe25bcdb-f966-4451-ae14-9ba2bd7d289f.png)

**Comment by devinbinnie** [comment]
> @devinbinnie - I'm wondering if this could / should be just a setting in preferences to enable it to always start in full-screen mode.
> 
> In theory, there are three ways this could work:
> 
> * it could be ticked as a user enters full-screen mode to always open in full screen, and turned off if they exit full screen move.
> * simply a setting that says "If last mode was full screen, open next time in full screen." and automatically trigger it off after that.
> * just this option below to always load in full screen when opened. ( feels annoying, but maybe someone would like it? )
> 
> ![Screen Shot 2022-01-07 at 2 03 38 PM](https://user-images.githubusercontent.com/46071821/148593912-fe25bcdb-f966-4451-ae14-9ba2bd7d289f.png)

@coltoneshaw I'd be good with adding a setting for it. It also might make sense to never open the app in full screen in the first place (especially on Windows where it's not really a paradigm), though some people I assume use it.
