### ISSUE TITLE
Can't get past "settings" after clean install of 1.2.0-rc1

### ISSUE THREAD

**Issue by jovandeginste** [mattermost/desktop#130]
I installed the deb package on a clean machine, and got the settings popup. After filling in the team info, clicking 'save' did nothing.

I then downloaded 1.1.1 (tar.gz, no deb available). Settings worked as expected and generated a config.json in my ~/.config; again installed the deb and it went immediately to the team page. Now opening the settings dialog gives a black screen.

**Comment by yuya-oc** [comment]
Could you tell me your environment? (See CONTRIBUTING.md)

**Comment by jovandeginste** [comment]
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"

**Comment by jovandeginste** [comment]
also, should have been *blank* screen instead of *black*

**Comment by yuya-oc** [comment]
`~/.config/Mattermost` is not created on clean environment, so 'save' did not work.

**Comment by yuya-oc** [comment]
Could you try with this build? https://circleci.com/gh/mattermost/desktop/311#artifacts

**Comment by jovandeginste** [comment]
This build seems to fix this issue. I tried it on a clean VM. I will close the issue, thanks!
