### ISSUE TITLE
Value for 'Exec' in 'Mattermost.desktop' inside deb package is not full path

### ISSUE THREAD

**Issue by jovandeginste** [mattermost/desktop#131]
Path appears to be `/usr/local/bin/Mattermost`, however in `/usr/share/applications/Mattermost.desktop` the path is set as follows:

`Exec="Mattermost"`

The shortcut seems not to work. I changed it to the full path, ran `sudo desktop-file-install /usr/share/applications/Mattermost.desktop` and now it works as expected.

However, I'm certainly not an expert on *.desktop files, so I may have some other issue causing this behaviour...

**Comment by yuya-oc** [comment]
It works on my environment (ubuntu 16.04), however I think that `Exec` should be the full path, too.
For now, could you check your `$PATH`?

**Comment by jovandeginste** [comment]
My (normal, in a terminal) `$PATH` includes `/usr/local/bin`; however I'm not sure what it is for Unity ...

**Comment by yuya-oc** [comment]
The latest `electron-builder` should solve this.
