### ISSUE TITLE
Popup to open downloaded files on mattermost desktop

### ISSUE THREAD

**Issue by h-methlouthi** [mattermost/desktop#1314]
Hello,
 on several chat application that installed on the desktop we are offered to directly open the file downloaded from the application without the need to go to the download folder.
Why not add it to your famous application.
thank you in advance

**Comment by philip-n** [comment]
This is what I just came here to post as well. After downloading a file to a selected location, a possibility to directly open the file at that location would be highly appreciated.

**Comment by FolkertRA** [comment]
I second this request.
Or maybe a open/save window with multiple choices like in a web browser.

Now I save the file to a temp folder, then click save again an right-click the file in the dialog to open it.

**Comment by devinbinnie** [comment]
Closing as this now exists.
