### ISSUE TITLE
Add 'Mark Read' option in right click of Channel to clear notification icon

### ISSUE THREAD

**Issue by csankhala** [mattermost/desktop#1316]

**Comment by Willyfrog** [comment]
hello @csankhala this repo holds issues/request that are not related to our webapp (meaning it is not reproducible on the browser, but only on the desktop app).
would you mind opening this one on the [server repo](https://github.com/mattermost/mattermost-server/issues) where it can be seen better? 

Closing the issue, but let me know if you think it should be kept open

**Comment by csankhala** [comment]
As you suggested, created in server repo: https://github.com/mattermost/mattermost-server/issues/14828

as you said, it is reproducible in Desktop app, don't we need the change in this repo?

**Comment by Willyfrog** [comment]
both repos are related, as the desktop app displays the webapp, if it is fixed there usually it is fixed on the desktop (if it appears on both)
