### ISSUE TITLE
Desktop App allows to browse to other websites

### ISSUE THREAD

**Issue by JtheBAB** [mattermost/desktop#1320]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: Windows
- Mattermost Desktop App version: 4.4.2 

**Steps to reproduce**

Add a new server and use https://www.google.com
Go to the tab to load the server

**Expected behavior**

The Desktop App should only load Mattermost Servers.

**Observed behavior**

Google is loading.

--------------------------

When you have a locked environment where you for example disable all browsers and use the Desktop App for Mattermost it is not good that the users could add just other webaddresses

**Comment by henricook** [comment]
The proposed fix further compounds Mattermost's poor support for IAP and other secure-border offerings

https://github.com/mattermost/desktop/pull/1321#issuecomment-677530942

**Comment by devinbinnie** [comment]
Closing as inactive.
