### ISSUE TITLE
Notification Sound not working

### ISSUE THREAD

**Issue by mountainash** [mattermost/desktop#1324]
**Summary**
Alert notification sound/audio not heard. 

**Environment**
- Operating System: macOS 10.15.5
- Mattermost Desktop App version: 4.4.0 & 4.4.2
- Mattermost Server version: 5.20.2

**Steps to reproduce**

1. Open Mattermost
1. Wait for someone/thing to send a message to a channel you don't have muted

**Expected behaviour**

I expect a "ping/alert" sound to play when a new message arrives

**Observed behavior**

Desktop notifications are turned on and os Preferences are enabled.
<img width="780" alt="osX Notifications Screenshot" src="https://user-images.githubusercontent.com/27637/84489887-a750ef00-aca2-11ea-8ac3-9d033f95b815.png">

The System notification,  Dock and Menubar indicators appear as expected, but no noise is played.

Running Mattermost directly in Chrome "chirps" as expected.

**Comment by mountainash** [comment]
This could be a macOS only issue as Linux loving colleges have reported that sound works for them.

**Comment by amyblais** [comment]
Would you be able to gather any logs via https://docs.mattermost.com/install/desktop.html#reporting-issues?

**Comment by mountainash** [comment]
Good idea. I've updated to latest 4.5.0.6629 release, but still no sound.
```
index_bundle.js:42028 [Mattermost] Loading jitsi plugin
(anonymous) @ index_bundle.js:42028
index_bundle.js:42028 [Mattermost] Loading com.github.matterpoll.matterpoll plugin
(anonymous) @ index_bundle.js:42028
index_bundle.js:42028 [Mattermost] Loading standup-raven plugin
(anonymous) @ index_bundle.js:42028
index_bundle.js:42028 [Mattermost] Loading com.mattermost.nps plugin
(anonymous) @ index_bundle.js:42028
index_bundle.js:42028 [Mattermost] Loaded jitsi plugin
(anonymous) @ index_bundle.js:42028
index_bundle.js:42028 [Mattermost] Loaded com.mattermost.nps plugin
(anonymous) @ index_bundle.js:42028
index_bundle.js:42028 [Mattermost] Loaded com.github.matterpoll.matterpoll plugin
(anonymous) @ index_bundle.js:42028
index_bundle.js:42028 [Mattermost] Loaded standup-raven plugin
(anonymous) @ index_bundle.js:42028
index_bundle.js:42028 [Mattermost] websocket connecting to wss://mattermost.{self-hosted}.com/api/v4/websocket
(anonymous) @ index_bundle.js:42028
```
No issues there.

I'm starting to think it could be an OS X issue rather than Mattermost. Can anyone confirm that Mattermost Desktop (>4.0.0) on macOS is playing audible notifications for them?

**Comment by mountainash** [comment]
I'm going to close this. I've tested with "mattermost-desktop-4.3.2-mac" & "mattermost-desktop-4.2.3-mac" and still have the same issue - no sound on "Mac1". I've tested "4.2.3.79" & "4.5.0.6629" on another Mac ("Mac2") and the sound **is working**. So it's something wrong with the Mac1 - but it's a strange issue as other apps notification sounds work and all the settings Notifications System Preferences for Mattermost are enabled. If I find a fix, I'll post it here...

**Comment by JosephMarinier** [comment]
I have experienced this issue for a couple of days. The notifications were popping, but not producing any sound. Even after rebooting. I changed the Notification Sound in Mattermost settings, and it started to work again. I changed the sound back to the original Bing, and it kept working. 🤷‍♂️
