### ISSUE TITLE
Mattermost takes up screen space even when hidden in Pop_os tiling

### ISSUE THREAD

**Issue by bvhme** [mattermost/desktop#1325]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

Mattermost desktop takes up screen space even when hidden in [Pop_os desktop tiling](https://github.com/pop-os/shell). In the tiling Mattermost will just take up a transparent space.

**Environment**
- Operating System: Pop_os Pop!_OS 20.04 LTS
- Mattermost Desktop App version: 4.3.2 

**Steps to reproduce**

1. Open Mattermost on Pop_os with Tiling on.
2. Close Mattermost.

**Expected behavior**

The window closes and the space is left for other apps to use.

**Observed behavior**

The window hides and is still taking up it's space making it useless and it can't be hidden. Mattermost needs to be quit in order for the space to be used by another application.

**Possible fixes**

Close the window instead of hiding it.

**Comment by Willyfrog** [comment]
it would probably be solved by https://github.com/mattermost/desktop/pull/1279

**Comment by bvhme** [comment]
This was solved 😃 thanks!
