### ISSUE TITLE
Font missing in Fedora 32

### ISSUE THREAD

**Issue by cyruzin** [mattermost/desktop#1326]
How can I fix thix issue? It happens when I try to save a file.

OS: Linux
Arch: x64
Distro: Fedora 32 (Wayland)
Kernel: 5.6.18-300.fc32.x86_64
Mettermost version: 4.4.2

![image](https://user-images.githubusercontent.com/2396581/84893543-cae6b180-b075-11ea-8143-213e49ce4e2b.png)

**Comment by Willyfrog** [comment]
Hello, thanks for the report

If you open a browser, does it show the same behavior?

If not, could you go to the menu, open the developer tools for current server and see if there is any error?

**Comment by cyruzin** [comment]
Hi, works fine on browser. And there is no error in the development tools. Maybe this is a Fedora issue.

**Comment by Willyfrog** [comment]
looking again at the screenshot, that doesn't seem to be mattermost's client, but rather gnome's file explorer (don't know it's exact name)

how does this relate with mattermost?

**Comment by cyruzin** [comment]
> looking again at the screenshot, that doesn't seem to be mattermost's client, but rather gnome's file explorer (don't know it's exact name)
> 
> how does this relate with mattermost?

Indeed. I'm using Gnome v3.36.3. Perhaps this is an isolated issue, I'm going to close the issue and switch to browser.

**Comment by baskinsy** [comment]
No it is the mattermost window when you try to attach a file. I have the same problem with the snap version on Opensuse Tumbleweed

![image](https://user-images.githubusercontent.com/1850894/140544156-5e8c285b-f770-419d-be1a-4d91739ac930.png)
