### ISSUE TITLE
Drop gconf2 and/or python-2.7 dependencies

### ISSUE THREAD

**Issue by lkraav** [mattermost/desktop#1329]
Hi

Many distros are phasing or have already phased out python-2.7.

It's possible that Mattermost desktop client might be the only package on a Linux system still pulling these outdated packages in.

Do we know what it would take to drop them?

**Comment by Willyfrog** [comment]
i think python v2.7 is the minimum required version. it might be needed for node-gyp and problably electron-builder, but I don't think it is restricted to v2.7

**Comment by lkraav** [comment]
Could someone skilled enough here run an experiment setting the minimum to Python 3.6?

**Comment by devinbinnie** [comment]
Closing as inactive. Feel free to re-open if this is still an issue.

**Comment by lkraav** [comment]
> Closing as inactive. Feel free to re-open if this is still an issue.

Gentoo managed to take care of it on its own, so it might not have been an upstream problem after all.
