### ISSUE TITLE
Display of the Mattermost icon in the menu bar is wrong. [v1.2.0-rc1] [OS X 10.11.5]

### ISSUE THREAD

**Issue by Johnich** [mattermost/desktop#133]
The icon in the menu bar lost its color. It should display an icon with a red/blue dot on it when new/mentioned message arrived, but the result is an icon with WHITE dot on it.  

1. Mattermost version is: v1.2.0-rc1
2. OS: Mac OS X 10.11.5 beta
3. Screenshot is attached.
![13 02 01](https://cloud.githubusercontent.com/assets/16934719/15204650/2484c392-1842-11e6-9ae2-971f7e3b7037.jpg)

**Comment by yuya-oc** [comment]
The black/white icon is by design for OS X appearance. Then, the icon will be changed into another one when mentioned.

**Comment by Johnich** [comment]
Did you mean you design the black/white icon to fit the OS X style? Or OS X turned your colorful icon into black/white automatically? I think a colorful dot on the mattermost icon will be more eye-catching while a white dot is very hard to tell. And I do believe that colorful icon is supported by OS X like attached screenshot below.
![colorful](https://cloud.githubusercontent.com/assets/16934719/15234852/9fa0919a-18e8-11e6-8ab6-79b930464439.jpg)

**Comment by yuya-oc** [comment]
I prepared only black icons for OS X. OS X automatically generates white/black images to fit the style. 
Sure, colorful images are also supported. But I have to manually prepare/handle several images to support clicking and dark theme. So need more time to implement that.
