### ISSUE TITLE
Cannot type ~ˇ^˘°˛`˙´ with Hungarian keyboard layout

### ISSUE THREAD

**Issue by MathiasMagnus** [mattermost/desktop#1331]
- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Typing any of `~ˇ^˘°˛``˙´` is impossible using Hungarian keyboard layout. Most problematic are backtick and tilde which are used for unformatted snippets and channel references, but I'd also occasionally want to type -15°C. (Winter's coming.)

The root cause likely is Windows treating `Ctrl+Alt` the same as `AltGr` which on many European keyboards are used to access characters found all over the keyboard. If that special character happens to reside on a `Ctrl+Alt+<key>` hotkey combination, it will likely be misinterpreted.

**Environment**
- Operating System: Windows 10 2004
- Mattermost Desktop App version: 4.2.3
- Mattermost Server version: 5.23.1

**Steps to reproduce**
Change keyboard layout to Hungarian, press `AltGr+7`.

**Expected behavior**
See backtick as typed

**Observed behavior**
Shortcut activated taking me to the 7th channel.

**Possible fixes**
- Allow to customize hotkeys?
- At least allow changing hotkey from `Ctrl+Alt` to `Ctrl+Shift`.

**Related issues:**
- [Cannot type a closing brace with Spanish keyboard layout](https://github.com/mattermost/desktop/issues/984)

**Comment by Willyfrog** [comment]
hello and thanks for the report!
first question that comes to mind is: does this happen only on the desktop app or also on the browser? have you tried with a more recent version of the app?

**Comment by MathiasMagnus** [comment]
- This happens only in the desktop app. Doesn't happen in Firefox.
- I don't regularily search for updates. There was an [issue opened](https://github.com/mattermost/desktop/issues/492) about this which I've also mentioned it was closed too soon, as the accompanying [JIRA ticket](https://mattermost.atlassian.net/browse/MM-14067) has been on the backlog for more than a year now. Auto-updates is an integral part of UX, and by no means do I mean baking it into the app itself. Running it through the app converter should suffice.
  - Having that said I updated the app which seems to have solved the issue.
  - Another indication to having value in auto-updates. @Willyfrog Please publish through the Microsoft Store to avoid users falling behind on versions.

**Comment by Willyfrog** [comment]
there are plans to deliver apps through stores, but we still have to work through some tickets to get there (like having the option on mac to use nsuserdefaults)
