### ISSUE TITLE
Pixelated Icon on Arch Linux KDE

### ISSUE THREAD

**Issue by cyruzin** [mattermost/desktop#1332]
Hi, the Mattermost icon is pixelated on Arch Linux KDE. Is this a KDE issue?

![image](https://user-images.githubusercontent.com/2396581/85415330-970efe80-b543-11ea-8619-00285104893c.png)

![image](https://user-images.githubusercontent.com/2396581/85415377-a42bed80-b543-11ea-9e81-f97ebeb5a218.png)

**Comment by devinbinnie** [comment]
Closing as this no longer reproduces.
