### ISSUE TITLE
ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by bhartvigsen** [mattermost/desktop#1333]
Mattermost OSX 4.5.0.6629

I recently switched my machine's DNS server. As a result I get this error in the Mattermost app on OSX Catalina:

ERR_NAME_NOT_RESOLVED

This is a typical DNS error and could easily be fixed in Chrome by purging the DNS cache. Unfortunately Mattermost does not surface the ability to do so in the application. Removing the chat server and re-adding it does nothing. Removing the desktop app completely and re-installing does nothing.

My proposed fix would be to either add an option in preferences to clear any caches OR simple don't cache DNS in this application.

**Comment by Willyfrog** [comment]
A couple of options:
1. menu -> view -> clear cache and reload
1. menu -> view -> developer tools (not sure what would be best if current server or application wrapper). from there application-> clear storage
1. go to ~/Library/Application Support/Mattermost and delete anything that is not a .json file

**Comment by bhartvigsen** [comment]
> menu -> view -> clear cache and reload
-- No effect

> menu -> view -> developer tools (not sure what would be best if current server or application wrapper). from there application-> clear storage
-- No effect

> go to ~/Library/Application Support/Mattermost and delete anything that is not a .json file
-- No effect. In fact I deleted the entire directory and reinstalled the application.

It appears that the app is storing some config elsewhere on the filesystem, or it's using a shared library or something that is caching this configuration.

**Comment by Willyfrog** [comment]
i'm afraid there is a lot of ways that something like that can be cached, it should eventually solve itself, as the cache might expire. if it doesn't it is not being cached but being solved by a different provider, in any case electron apps doesn't try to do anything with the dns cache as far as I know, so it is most likely something related your machine.

as I mention, the only way I know to clear the cache without creating a new PR would be to delete /Users/<user>/Library/Application Support/<yourAppName>/Cache which would solve most of this kind of problems.

**Comment by A248** [comment]
I was having this same issue. For me, clearing the system-wide DNS cache solved the issue.

How you clear your system's DNS cache depends on which OS you use. Usually, a device restart should solve the problem.

**Comment by Willyfrog** [comment]
great to hear that you managed to solve it. I'll close the issue, but feel free to reopen if anything comes up :)
