### ISSUE TITLE
Multi-server (slash) commands

### ISSUE THREAD

**Issue by ojacquet** [mattermost/desktop#1334]
During the day I'm logged in into multiple mattermost servers. This means that when I want to change my status I have to click on each server and set my status to the desired state. Doing this every start and end of a meeting is not fun.

It would be great if it was possible to change my status in multiple servers at once. Either via a slash command or a UI widget in the application wrapper.

Maybe this is already possible with some javascript in the application wrapper console?

**Comment by devinbinnie** [comment]
Closing as the slash commands are currently controlled by each individual Mattermost server, so we can't actually synchronize these unless the servers are linked.

We could look into something like this in the future when the Desktop App no longer relies on using the webapp within a `BrowserView`
