### ISSUE TITLE
Mattermost Desktop No Longer Remembers Last Download Location

### ISSUE THREAD

**Issue by starlightknight** [mattermost/desktop#1337]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

Mattermost desktop doesn't remember download folder after upgrading from 4.3.1 -> 4.5.0

**Environment**
- Operating System: Linux Mint 19.3
- Mattermost Desktop App version: 4.5.0
- Mattermost Server version: 5.22.2 (via GItlab Omnibus)

**Steps to reproduce**

Download a file. Download another file

**Expected behavior**

I expect it to remember where I last downloaded files. It used to in older versions of Mattermost Desktop.

**Observed behavior**

It now always reverts to the Downloads folder. This was working in 4.3.x), and broke when I upgraded. It's very frustrating when someone shares photos and you're trying to download them. It's frustrating enough that I will roll back the desktop client for now.

Edit: Confirmed working in 4.3.2, confirmed broken in 4.4.x

**Comment by amyblais** [comment]
Thanks, opened a ticket here: https://mattermost.atlassian.net/browse/MM-26788.

**Comment by amyblais** [comment]
Closing, this was fixed in v4.7,
