### ISSUE TITLE
screenshot 

### ISSUE THREAD

**Issue by flunda** [mattermost/desktop#134]
can we get a functionality for making screenshots directly from the chat window with a single click?

**Comment by Razzeee** [comment]
What's wrong about Print button and then Ctrl + V?

**Comment by flunda** [comment]
just less comfortable. because mostly you do not want to paste the whole print screen only just a part of a window / programm code, etc..

**Comment by Razzeee** [comment]
Well you can get single windows with Alt + Print. But I don't think mattermost is planned/trying to be a screen grabbing tool.

**Comment by MetalCar** [comment]
Then use snagit and you can paste your Screenshot with ctrl+v after you selected the Area on you Desktop

**Comment by yuya-oc** [comment]
That should be supported by external software. You can use it on other applications by its common usage.

For example, there are some ways supported by OS.
- Win: Snipping Tool
- OS X: `Command+Shift+4`
