### ISSUE TITLE
Impossible to login with SSO solution requiring FIDO2/WebAuthN two-factor auth

### ISSUE THREAD

**Issue by restena-sw** [mattermost/desktop#1346]
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
When user login requires FIDO2/WebAuthN hardware tokens, it is not possible to log in.

**Environment**
- Operating System: Linux (openSUSE 15.2)
- Mattermost Desktop App version: 4.5.0 from Flatpak, updated today
- Mattermost Server version: GitLab Mattermost; Mattermost Version: 5.22.2; Database Schema Version: 5.22.0; Database: postgres

**Steps to reproduce**
- Enable SSO login with an extenal auth source (in my Case: "Login with GitLab")
- have an SSO solution which asks username+password+tap on a FIDO2/WebAuthN hardware token
- observe how verification of username and password succeeds, and the request to tap the key is displayed

**Expected behavior**
- WebAuthN API is triggered, the key flashes, you push it, the second-factor auth completes

**Observed behavior**
- WebAuthN API is not triggered (no browser popup asking to touch the key). You hang forever in that screen. Screenshot attached.
![Screenshot_20200715_093957](https://user-images.githubusercontent.com/6346943/87517534-3f197280-c67f-11ea-8e64-b5aacb917196.png)

**Possible fixes**

Logging in via web using most recent Chrome works as expected. It looks like for some reason, using Chrome as embedded engine does not support the FIDO2/WebAUthN APIs.

If there is a way to enable this when calling the API, sounds like this would be the fix. 

Or maybe you have a version of Chrome embedded in the Electron app, and that version is ancient and not supporting FIDO2 yet? I guess then updating it is the thing to do.

**Comment by Willyfrog** [comment]
recent versions of the desktop app should have webauthn support (seems it was added in chrome 67 as beta and seems to be in electron [since v4](https://github.com/electron/electron/issues/15404)).

I'm wondering if it might be related to https://mattermost.atlassian.net/browse/MM-26807

**Comment by svelle** [comment]
@restena-sw another thing that comes to mind, have you tried a non-flatpak release? just to be sure.

**Comment by restena-sw** [comment]
I have now tried 4.5.1 on macOS - no WebAuthN API triggered.
Also, on a Windows 10 VM, I used the windows build of 4.5.1. It does trigger the WebAuthN API call (the key still isn't actually activated, but I am ready to blame that on VMWare's USB port emulation).

**Comment by restena-sw** [comment]
Nice! I tried the "proper" tarball release 4.5.1 on Linux now. It does not display the browser popup, but: the authenticator key starts flashing, so it seemingly activated the 2FA process "silently". Tapping the key actually worked and I'm logged in.
