### ISSUE TITLE
systray icon -> left click -> open immediatelly

### ISSUE THREAD

**Issue by 2019-05-10** [mattermost/desktop#1348]
I confirm (by marking "x" in the [ ] below: [x]):

- [ x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [ x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
If only one server is configured, immediatelly open the application window on left click on the systray icon.

a) basically every other systray icon works that way
b) it's meaningless to have for both left and right click the exactly same options
c) the very same options are available in the application window as well
d) the current menu should be reserved for the right click

**Comment by Willyfrog** [comment]
i like this suggestion. I'll create a ticket for it, but most likely will be set as help wanted so someone from the community can help deliver :)

**Comment by esethna** [comment]
@2019-05-10 can you clarify on what operating system you are referring to? Screenshot would help too.

On Windows this is already the observed behavior and on Mac it is native behaviour to open the option dropdown when clicking the icon at the top of the screen.

**Comment by 2019-05-10** [comment]
Linux/Plasma 5.17.5
mattermost-desktop 4.5.2

This I see both with left and right click:

![Screenshot_20200729_102937](https://user-images.githubusercontent.com/50481865/88776870-d3f39400-d186-11ea-8199-d3fcb689aec7.png)

If it helps: it's the same with Slack's desktop client, which is AFAIK based on Electron as well.

**Comment by 2019-05-10** [comment]
Seems to be a known issue, related to libappindicator, and if I understand correctly, fixed in Electron 8:

> https://github.com/electron/electron/issues/21819

**Comment by esethna** [comment]
Cool, we're working on the upgrade to electron 8 right now. https://mattermost.atlassian.net/browse/MM-25765
