### ISSUE TITLE
Offer Debian/Ubuntu repository

### ISSUE THREAD

**Issue by PanderMusubi** [mattermost/desktop#1350]
Please offer a dep repository foor Debian/Ubuntu. Also as PPA is welcome. Offering deb files in this way eases upgrading for users on Debian/Ubuntu.

**Comment by Willyfrog** [comment]
@metanerd do you know if this is something we can do easily? I haven't messed with PPAs

**Comment by metanerd** [comment]
I created a ticket for this: Sounds like a good idea! https://mattermost.atlassian.net/browse/DOPS-170

**Comment by PanderMusubi** [comment]
Any progress on this one? Because of the manual update process, I missed a few versions :grin: Creating a PPA at Launchpad is fairly straight forward and doesn't require you host it yourself.

**Comment by Willyfrog** [comment]
I don't think any progress has been done, AFAIK

**Comment by akmet** [comment]
I would welcome a repository as it would be much easier for our users to update.

@assafmo has created a very nice [tutorial](https://assafmo.github.io/2019/05/02/ppa-repo-hosted-on-github.html) on how to set up a PPA repository with GitHub Pages - maybe it's worth considering? I would assume it would integrate easily into the existing release workflow

**Comment by Willyfrog** [comment]
that looks nice! I've shared that with our devops team and see if that would be possible.

**Comment by akmet** [comment]
@Willyfrog Would you be so kind as to enlighten us as to whether there is anything new on this yet?
Perhaps the community can also help by providing a pull request.

**Comment by Willyfrog** [comment]
I'd love to have that for the next major release (5.0), for now we are focused on delivering v4.7

sorry I can't provide any dates, regarding community PRs they are always welcome, let me know if I can help with anything regarding this

**Comment by devinbinnie** [comment]
We did this! https://docs.mattermost.com/install/desktop-app-install.html#install-and-update-the-mattermost-desktop-app
