### ISSUE TITLE
Repeating modal dialog box if telemetry URL pdat.matterlytics.com is blocked

### ISSUE THREAD

**Issue by lpsinger** [mattermost/desktop#1352]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
My employer proxies Internet traffic and blocks certain domains that haven't been seen before. The Mattermost analytics domain, pdat.matterlytics.com, is not yet in their system, so it is blocked. The consequence is that the address https://pdat.matterlytics.com gets redirected and the TLS certificate is wrong.

This makes the Mattermost desktop app unusable because the modal dialog box shown in the screen shot below comes up whenever switching channels, clicking reply on a thread, and also every minute or so seemingly at random.

**Environment**
- Operating System: macOS Catalina 10.15.6 (19G73)
- Mattermost Desktop App version: 4.5.2 (4.5.2.6864)
- Mattermost Server version: 5.23.1

**Steps to reproduce**
Set up a proxy that blocks pdat.matterlytics.com and open the Mattermost desktop app.

**Expected behavior**
At most one error dialog box when the application starts up. Once dismissed, the application should be usable without further interruptions (but, of course, without functioning telemetry).

**Observed behavior**
User is nagged every few seconds by the dialog box shown below.

<img width="931" alt="Screen Shot 2020-07-22 at 15 22 46" src="https://user-images.githubusercontent.com/728407/88224054-6ef3e780-cc36-11ea-94e4-ea5facf031b7.png">

**Possible fixes**
- Show at most one error dialog if pdat.analytics.com if it is unreachable, then give up silently on telemetry.
- A checkbox in the desktop application's Preferences to opt out of telemetry.
- Use the browser client instead of the desktop app. The browser client is not affected.

**Comment by Willyfrog** [comment]
hi there!
quick question: which desktop version are you using? i'm afraid you pasted the same version for the os and the desktop app.

if you click on "more details" and then "trust" does it still keep popping up?

regarding your notes on possible fixes:
>    Show at most one error dialog if pdat.analytics.com if it is unreachable, then give up silently on telemetry.

telemetry is not managed by the desktop, but by the webapp. you might want to make that suggestion [here](https://github.com/mattermost/mattermost-server/issues/)

>    A checkbox in the desktop application's Preferences to opt out of telemetry.

opting in/out of telemetry is something managed at server level, and it is an option for administrators. there is no control on the webapp or the desktop

> Use the browser client instead of the desktop app. The browser client is not affected.

that's interesting, have you trusted this certificate in the browser? it should be affected the same way (keep raising a warning until you trust it or stop navigating there)

**Comment by lpsinger** [comment]
> quick question: which desktop version are you using? i'm afraid you pasted the same version for the os and the desktop app.

Oops! I corrected it. It's 4.5.2.

> if you click on "more details" and then "trust" does it still keep popping up?

Well, it's not doing it anymore. Maybe my employer finally unblocked it (without confirming).

**Comment by lpsinger** [comment]
> if you click on "more details" and then "trust" does it still keep popping up?

Yes, it does. (Besides, I don't *really* trust the third party that is doing the filtering.)

> regarding your notes on possible fixes:
> 
> > Show at most one error dialog if pdat.analytics.com if it is unreachable, then give up silently on telemetry.
> 
> telemetry is not managed by the desktop, but by the webapp. you might want to make that suggestion [here](https://github.com/mattermost/mattermost-server/issues/)
> 
> > A checkbox in the desktop application's Preferences to opt out of telemetry.
> 
> opting in/out of telemetry is something managed at server level, and it is an option for administrators. there is no control on the webapp or the desktop

So, it turns out that what had really happened was that the person who maintains our on-premise Mattermost deployment (@skymoo) turned off analytics. I asked him to turn it back on temporarily, and I am still seeing the dialog boxes.

> > Use the browser client instead of the desktop app. The browser client is not affected.
> 
> that's interesting, have you trusted this certificate in the browser? it should be affected the same way (keep raising a warning until you trust it or stop navigating there)

I'd really rather not trust this certificate.

**Comment by Willyfrog** [comment]
> Yes, it does. (Besides, I don't really trust the third party that is doing the filtering.)

so, if I understood you right, you want exactly the opposite behaviour to what's implemented, a "never trust" button so it doesn't ask you again. 

thinking through it, it makes some sense as we are not a browser and we are not trying to scare people off some page, it is within mattermost, so it makes sense to not load something you don't trust but not to be bugged by that again since it might be an image in a channel or (as in this case) a redirection being intercepted.

[Ticket created](https://mattermost.atlassian.net/browse/MM-27205)

**Comment by devinbinnie** [comment]
Closing as this is fixed now.
