### ISSUE TITLE
Mattermost 4.5.1 Does Not Start on Windows Startup

### ISSUE THREAD

**Issue by jbkatz** [mattermost/desktop#1353]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Mattermost 4.5.1 will not start automatically when booting a Windows 10 machine.

**Environment**
- Operating System: Windows 10
- Mattermost Desktop App version: 4.5.1
- Mattermost Server version: ? (Can't find this in my version) 

**Steps to reproduce**
Mattermost is listed as Enabled in the Startup section of Task Manager and as On in the Settings --> Startup Apps list.
When I boot up my machine, Mattermost does not automatically start up/open.  If I go to the Task Manager, there are multiple Mattermost processes running, but nothing I see outside of the Task Manager.

When I manually open Mattermost, it opens normally.

I will note that this began when I upgraded to 4.5.1 a few weeks ago (I don't remember the old version I had installed prior).  The older version started automatically on Windows startup.  Since upgrading to 4.5.1, I've tried reinstalling MM, and have also replaced my hard drive with a new one/fresh Windows installation, and the problem persists.

**Expected behavior**
Mattermost should open when I boot up and log into Windows

**Observed behavior**
Mattermost processes are shown in Task Manager, but the app does not appear to the user to be running. This is what Task Manager shows before manually starting MM:

![image](https://user-images.githubusercontent.com/68755451/88432996-1cd7d100-cdb2-11ea-8c17-9eb198b4677d.png)

**Possible fixes**

**Comment by Willyfrog** [comment]
have you checked if this still happens on [v.4.5.2](https://github.com/mattermost/desktop/releases/tag/v4.5.2)? we added a small fix for linux that might also affect your case.

Also, have you checked the tray? when autostarting, it goes directly to the tray whithout popping a window, so that might be confusing if you expect the window to show.

**Comment by jbkatz** [comment]
It does look like it's in the tray.  Previously, it would show up as a regular entry on the taskbar, so it was obvious.  I was pointed to a registry edit here: Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run.  By removing the "--hidden" the MM window now opens as normal with a regular taskbar entry.  Since the setting in MM says that MM will start up minimized, I do think that means it should be on the task bar.  As an example, if I open Lync, it goes to the tray/notification center when I hit the X in its window (as close to closed as it can get without actually exiting).  If I minimize it (hit the -) it remains on the taskbar.

![image](https://user-images.githubusercontent.com/68755451/88593785-eea5fb80-d014-11ea-8ba1-20d1f4424a02.png)

I haven't tried 4.5.2 yet.  I'll have to wait for my company to allow the installation.  At least for now I have a workaround in place, though if 4.5.2 hasn't fixed this, I do still think it's an issue to be addressed.

**Comment by bbodenmiller** [comment]
I agree this is confusing. It definitely used to open in taskbar when this option was checked.

**Comment by jbkatz** [comment]
I just installed 4.5.2 and the issue remains.  If you manually removed "--hidden" from the registry entry, that remains until the "Start app on login" setting is cycled.  Any time that setting is checked in MM Settings, the registry key is updated to contain --hidden, which results in MM being present as a small icon on the tray, but not present on the Taskbar itself.

**Comment by jbkatz** [comment]
Additional follow-up: I followed these instructions (https://support.microsoft.com/en-us/help/4558286/windows-10-add-an-app-to-run-automatically-at-startup) with 4.5.2, and even with the registry entry set to --hidden, MM did open on startup as desired, the same way it opened when I removed --hidden manually.  The MM window isn't minimized on startup, but that was never a problem in my eyes; MM opens and shows up on the taskbar, which is what I was hoping for.  

This workaround is good in that it doesn't care about the --hidden flag, which is important because if I change my MM settings after manually removing that flag, the --hidden is added back in, resulting in the registry edit workaround failing.  That said, if I now turn off the setting that starts MM on Windows startup, it appears that MM will still open, so in truth this workaround bypasses the setting in MM, rather than fixing it.  Still, for my needs it works, though it may not be perfect for all users.

**Comment by amyblais** [comment]
I can reproduce it. @Willyfrog Is there a ticket similar to this open or do I create a ticket for this?

**Comment by Willyfrog** [comment]
@amyblais I created this one https://mattermost.atlassian.net/browse/MM-27332 but feel free to add any extra details

**Comment by amyblais** [comment]
Closing, this was fixed in v4.6,
