### ISSUE TITLE
Easier change of focus for threads

### ISSUE THREAD

**Issue by riggasconi** [mattermost/desktop#1356]
Currently the right section of the app (thread) changes only if I click on "reply". It'd be good if it changed whenever I clicked on any message, be that part of a thread or a single one (it'd be coupled in both the mid and right sections).

**Comment by Willyfrog** [comment]
hello there! thanks for taking the time to suggest this feature, but that would be related to the webapp repo. Can you please reopen it [here](https://github.com/mattermost/mattermost-server/issues) (webapp shares issues with the server repo)
another option would be to add it to our [uservoice list of suggested features](https://mattermost.uservoice.com/forums/306457-general)

I'm closing the issue, but feel free to reopen if you think it is actually relevant for the desktop app.
