### ISSUE TITLE
Automatically join new public channels

### ISSUE THREAD

**Issue by riggasconi** [mattermost/desktop#1357]
By default, new public channels are joined by all members. At channel creation, channel creator can choose not to.

**Comment by Willyfrog** [comment]
hello there! thanks for taking the time to suggest this feature, but that would be related to the webapp repo. Can you please reopen it [here](https://github.com/mattermost/mattermost-server/issues) (webapp shares issues with the server repo)
another option would be to add it to our [uservoice list of suggested features](https://mattermost.uservoice.com/forums/306457-general)

I'm closing the issue, but feel free to reopen if you think it is actually relevant for the desktop app.
