### ISSUE TITLE
Auto check/download updates 

### ISSUE THREAD

**Issue by ageekhere** [mattermost/desktop#1360]
Is there an auto updater for mattermost desktop app in the works?

**Comment by Willyfrog** [comment]
it is in the roadmap, but not currently being worked on. Would you like to help in that regard?

Closing as it is not an issue but a question, feel free to reopen with more details if there is an issue

**Comment by ageekhere** [comment]
how about using this https://github.com/iffy/electron-autoupdate-example

**Comment by Willyfrog** [comment]
yes, that's partially the idea, but it also requires having user configuration, check if it works with installers not based on squirrel (not all our options do), etc.
