### ISSUE TITLE
Unblock Downloaded Files from Mattermost Desktop Application on Windows 10 

### ISSUE THREAD

**Issue by andrsharov** [mattermost/desktop#1361]
Hello! 

I have some problem with Mattermost desktop application on Windows 10 

OS: Windows 10 Pro x64 ver 2004 buid 18361.1016
Mattermost Application: 4.5.2

On Windows 10 all downloaded from Internet files classifies Attachment Manager by 3 types: High Risk , Moderate Risk, Low Risk .
To disables this feature I use registry tweak from aticle https://www.tenforums.com/tutorials/85418-disable-downloaded-files-being-blocked-windows.html  
To unblock already blocked files I use solution from this aticle http://thehunk.blogspot.com/2012/04/stop-having-to-click-unblock-on-every.html 

For any another Windows applications this solution works, but not for Mattermost Desktop Application. 

Main problem consists in inability to open MS Office files, each was downloaded from Mattermost Desktop Application. Users must go to the file properties and Ublock each downloaded file. 
After unblock file, he begin to open. 

Maybe you can advise a way to solve the problem ?

**Comment by devinbinnie** [comment]
Closing as I don't believe we support the tweak mentioned above.
