### ISSUE TITLE
Build .dmg file for macOS  error

### ISSUE THREAD

**Issue by AiTranXuan** [mattermost/desktop#1363]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

I use the script npm run package: mac to build .dmg file for macOS
 But this error appears.
Command failed: spctl --assess --type execute --verbose --ignore-cache --no-cache /Users/aitx/go/src/github.com/mattermost/mm135/mmc-desktop/release/mac/Chatops.app
/Users/aitx/go/src/github.com/mattermost/mm135/mmc-desktop/release/mac/Chatops.app: rejected

**Steps to reproduce**

Please include all of the following:
- Operating System MacOS 10.15.6
- Mattermost Desktop App version 4.5.2
- Mattermost Server version 5.25.2

![Screen Shot 2020-08-26 at 08 26 03](https://user-images.githubusercontent.com/15552410/91268847-3cdb2580-e7a0-11ea-8663-b72fd8ca9922.png)

**Comment by Willyfrog** [comment]
seems like it is rejecting signing the package, but I'm afraid it doesn't give much info on that.
please make sure you follow the steps and requirements from [electron builder's guide](https://www.electron.build/code-signing)

**Comment by Willyfrog** [comment]
Since you are also getting help on[community server](https://community.mattermost.com/core/pl/1ir3iu9fqtf8x8gzbqzoqnit3c) un closing this issue to focalize efforts
