### ISSUE TITLE
Upgrade electron to 9 or later

### ISSUE THREAD

**Issue by NgoHuy** [mattermost/desktop#1364]
Hi team,
I have noticed that electron 7 is end of support now. And on Archlinux I built with electron 9 fine, but when I clicked any menu it crashed with message
```
Error: Failed to serialize arguments at WebContents._.send (electron/js2c/browser_init.js:173:2149) at Menu.handleCloseAppMenu (/usr/lib/mattermost-desktop/app.asar/main_bundle.js:1063:26) at Menu.emit (events.js:223:5)
```
We should move to electron 8 or 9 but electron 8 will be end of support soon.

**Comment by Willyfrog** [comment]
Our policy is to be one version behind the current one, to prevent running into new bugs and have a more stable experience.
there are several breaking changes to be considered between 7 and 9, next release will most likely be using 9 (we are currently working in a major rework of the app and plan is to ship with this new version)
you can take a look at electron's [breaking changes](https://www.electronjs.org/docs/breaking-changes) to get a feeling of what's needed in each case.

Regarding the error, on 8 they changed how to do ipc messaging and on 9 they enforce it.

closing the issue, but reopen if you feel it is necessary
