### ISSUE TITLE
Support ARM-based macOS

### ISSUE THREAD

**Issue by mcarthur-cpt** [mattermost/desktop#1365]
As ARM-based macOS devices are the future of Apple devices, there needs to worked on a version for ARM-based Apple devices.

**Comment by Willyfrog** [comment]
it is [supported by electron](https://github.com/electron/electron/issues/24306) already. Are you aware of any issues or incompatibilities?

I'm closing this for the time being, but feel free to reopen with any more details you have that need to be worked on.

**Comment by svewag** [comment]
[This app](https://github.com/DigiDNA/Silicon/releases) claims that Mattermost `Version 4.6.1 (4.6.1.7401)` is running  on a `Intel 64` code base.
![image](https://user-images.githubusercontent.com/155578/100524437-7dd84100-31b8-11eb-8dfc-e776b40336b8.png)

For me it looks like that Mattermost is not running optimized 🤔

I'm using macOS 11.0 on a Apple M1 Chip.

**Comment by Willyfrog** [comment]
most likely using rosetta to run, I guess.

have you noticed any problems?

**Comment by svewag** [comment]
So far no problems noticed

**Comment by Willyfrog** [comment]
eventually we'll get M1 builds, but for now I don't think circle will support it. Feel free  to reopen or open a new issue if you notice any odd behaviour that might be related to running through rosetta so we can take a look and consider doing a specific build

**Comment by pashdown** [comment]
![mm-power](https://user-images.githubusercontent.com/175150/104517422-30226700-55b3-11eb-8436-637f46ebd617.jpg)

I don't know if an M1 build would help the power consumption, but if it is eating nearly as much as my Firefox, with umpteen tabs open, that is something to consider.

**Comment by logiota** [comment]
cpu cycles are reduced by at absolute minimum 30% so of course it will reduce consumption, it also enhances parallel processing a lot and hardware acceleration.

**Comment by jbub** [comment]
Looks like the 4.7.* beta and rc versions already include mac-arm64.dmg, guess it will be released soon ?

**Comment by Willyfrog** [comment]
4.7 addresses part of the power comsumption and as well will provide m1 builds (but keep in mind those are beta as we haven't had many people test them)

Right now m1 builds are the ones ending in arm64, but it will be renamed to m1 by release. Feel free to test them and report any feedback

**Comment by jbub** [comment]
> Right now m1 builds are the ones ending in `arm64`, but they will be renamed to `m1` by release. Feel free to test them and report any feedback

Yep already running on ARM64 Version 4.7.0-rc6 (4.7.0-rc6.10554), so far so good. Thank you
