### ISSUE TITLE
Links don't Work in Windows Desktop Client 4.5.3

### ISSUE THREAD

**Issue by ingomohr** [mattermost/desktop#1367]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
When I click on a link in a message I received, nothing happens.
I uninstalled 4.5.3 and installed 4.5.2 instead => works as expected.

**Environment**
- Operating System: Windows 10
- Mattermost Desktop App version: 4.5.3
- Mattermost Server version: 5.18.0

**Steps to reproduce**
* Log into client
* Receive a message w/ a link
* Click on link

**Expected behavior**
* Link opens on browser

**Observed behavior**
* Nothing happens

**Possible fixes**
* Install 4.5.2 instead. Worked for me.

**Comment by Willyfrog** [comment]
hi! thanks for the report, when you say that it works on 4.5.2, is it the same link?

is the link behind some sort of authentication or requires accepting a certificate?

**Comment by ingomohr** [comment]
> hi! thanks for the report, when you say that it works on 4.5.2, is it the same link?
> 
> 
> 
> is the link behind some sort of authentication or requires accepting a certificate?

Hi! Thx for the quick reply!
Sorry, I should've added those info. 
Yes, the link was the same, and it was a link to a Jira issue - in both cases I was already logged in to Jira on the browser (Chrome (default browser)). A link to the Jira server typically works w/o authentification or certificates, as well: if you're not logged in, the link will bring you to a page where you can log in / or an error page.

But in this case nothing happened w/ the latest MM desktop version. Even at a clickfest on the link, there was no reaction.

**Comment by ingomohr** [comment]
It was not only that one link. Other links (w/o authentification or certificates) didn't work before, either.

**Comment by Willyfrog** [comment]
would you share that link with me through a private DM in the community server? so I can see if there is anything special about it?

i've retested with our own jira and I don't seem to have any problem opening

**Comment by ingomohr** [comment]
> would you share that link with me through a private DM in the community server? so I can see if there is anything special about it?
> 
> i've retested with our own jira and I don't seem to have any problem opening

Thank you @Willyfrog for getting back. I don't have the link anymore - but it was just a typical Jira issue link.
If you cannot reproduce it, maybe the problem was not on the Mattermost client but on the browser.

Meanwhile (i.e. today), I also had problems with Lotus Notes not opening links. And that problem could be fixed by simply restarting the browser.

I suggest to drop this issue then. You will probably have tests that prove that opening links works.

I'll update my Mattermost client tomorrow again to the latest version. I'll let you know in case I get the same problem and can cross other problems out.

Again, thank you for your support!

**Comment by Willyfrog** [comment]
Sure! feel free to reopen if you find the issue again :D
