### ISSUE TITLE
Copy and Paste results in multiple Paste

### ISSUE THREAD

**Issue by sjeeva** [mattermost/desktop#1368]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Copy and Paste of image or text using Ctrl+V results in multiple paste

**Environment**
- Operating System: Windows
- Mattermost Desktop App version: 4.5.3 
- Mattermost Server version: X.X.X 

**Steps to reproduce**
Simple copy and paste results in multiple paste

**Expected behavior**
It should not paste multiple times

**Observed behavior**

**Possible fixes**

**Comment by Willyfrog** [comment]
can you share your server version to see if there is a problem there? I've been trying to copy and paste several images but couldn't find anything that pasted multiple times.

**Comment by sjeeva** [comment]
I have a strong feeling that it is an UI bug. The Server Current version is 5.23.0

**Comment by Willyfrog** [comment]
i've tested with a windows 10, server version 5.23 but couldn't reproduce the issue.

Does this happen if you use the browser? Any hints on what can I do to repro the issue?

**Comment by sjeeva** [comment]
Perhaps it is very specific to my environment, wherein the control keys are way too sensitive. In web browser I don't see any such behavior. 

Again, this happens only with Control + Keys... I can consistently reproduce ctrl + v and ctrl + z repeating itself. I can show it on a video call if needed...

**Comment by amyblais** [comment]
@sjeeva Are you able to reproduce this on our [community server](https://community.mattermost.com/)? It is currently on the latest release v5.27.

**Comment by Willyfrog** [comment]
> I can show it on a video call if needed...

if you could record it, that would be useful
