### ISSUE TITLE
No Toast Messages with Windows 10 when used portable

### ISSUE THREAD

**Issue by IzeQube** [mattermost/desktop#1370]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: Windows 10
- Mattermost Desktop App version: 4.5.3
- Mattermost Server version: 5.26.1

I receive a new private message and the application is minimized => No new toast message

If I install the application and don't use it portable everything works as it should...

**Comment by Willyfrog** [comment]
the way windows notifications work right now requires an installation path to match AppId, I don't think a portable version is going to make it work, unless there are any other ways to generate notifications in windows.

**Comment by IzeQube** [comment]
Any way to create the needed entries manually without the installer? If you know where the portable exe is located of course...

**Comment by Willyfrog** [comment]
you can find info here: https://www.electronjs.org/docs/tutorial/notifications#windows

closing the issue, as we are not currently supporting portable apps for the moment. Please reopen if you have any more info or think it is relevant.
