### ISSUE TITLE
Notifications for currently active channel

### ISSUE THREAD

**Issue by gitfizicist** [mattermost/desktop#1372]
I keep missing messages in my currently active channel as the window is minimized or behind another window.
Please have notifications for these messages too!

Suggest features in the Mattermost feature idea forum so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html).

[https://mattermost.uservoice.com](https://mattermost.uservoice.com/forums/306457-general?category_id=159795)

You get 10 votes in the feature idea forum, and each one influences the future of the project.

**Comment by Willyfrog** [comment]
can you provide info on the environment?
os, app version, server version, what kind of channel are we talking (public, private, GM, DM), how are the nnotification settings of that channel configured?

**Comment by gitfizicist** [comment]
Hi Willyfrog,
this is Windows 10, Matermost 5.24.2. This is setup for my work with Gitlab signin, so I think it is a public channel in a private session?
I have notifications configured for desktop notifications, which pop up when I get notifications for any channel other than the active channel.

**Comment by Willyfrog** [comment]
sorry, I have more questions: 
do messages contain at-mentions (like `@gitfizicist`)?
which desktop app version are you using?
does this happen also with the browser?

**Comment by esethna** [comment]
@gitfizicist are you using our [latest desktop version](https://mattermost.com/download/#mattermostApps)? Can you attempt to upgrade as see if your issue persists? We recently fixed this: https://mattermost.atlassian.net/browse/MM-23215

**Comment by gitfizicist** [comment]
Thank you esethna that sorted it!
