### ISSUE TITLE
Mattermost Helper (Renderer) is not working under macOS Big Sur!

### ISSUE THREAD

**Issue by PontusTideman** [mattermost/desktop#1377]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

Running latest version of Mattermost desktop client for macOS (4.5.4.7024) and running it under macOS Big Sur 11.0 beta, and the render is not working as it should. Don't blame me for using a beta, blame Apple that can't fix the bugs they have in Catalina for the 16" MacBook Pro's from 2019!

**Environment**
- Operating System: macOS Big Sur 11.0 Beta
- Mattermost Desktop App version: X.X.X  4.5.4.7024
- Mattermost Server version: X.X.X  Dunno! Don't have access to it on work.

**Steps to reproduce**
Install macOS Big Sur 11.0 Beta! Install latest version of Mattermost, launch 

**Expected behavior**
That the renderer should work?

**Observed behavior**
Seeing that Mattermost Helper (Renderer) is not responding under Activity monitor.

```
Sep 28 10:51:36 Pontuss-MBP Mattermost Helper (GPU)[1540]: getattrlist failed for /System/Library/Extensions/AppleIntelKBLGraphicsGLDriver.bundle/Contents/MacOS/AppleIntelKBLGraphicsGLDriver: #2: No such file or directory
Sep 28 10:51:36 Pontuss-MBP Mattermost Helper (GPU)[1540]: getattrlist failed for /Library/GPUBundles/AMDRadeonX6000GLDriver.bundle/Contents/MacOS/ATIRadeonX6000SCLib.dylib: #2: No such file or directory
Sep 28 10:51:36 Pontuss-MBP Mattermost Helper (GPU)[1540]: getattrlist failed for /System/Library/Extensions/AMDRadeonX6000GLDriver.bundle/Contents/MacOS/ATIRadeonX6000SCLib.dylib: #2: No such file or directory
Sep 28 10:51:36 Pontuss-MBP Mattermost Helper (GPU)[1540]: getattrlist failed for /System/Library/Frameworks/OpenGL.framework/Resources//GLRendererFloat.bundle/GLRendererFloat: #2: No such file or directory
```

**Possible fixes**

**Comment by PontusTideman** [comment]
This is still an issue in the latest release of Big Sur!

**Comment by AizatHawari** [comment]
Still is an issue in Nov 2021.

**Comment by AizatHawari** [comment]
Yes, in Windows 10 its fast and snappy.
Even running on the browser is snappy on Win 10.
Although I must say my Windows is i7 6700k and has 32GB, versus my MacBook is MBP 13 inch 2015 i5 processor with 16GB ram.
Should still be okay too actually.

Aizat

**Comment by devinbinnie** [comment]
@PontusTideman Is this still an issue for you as well?

**Comment by devinbinnie** [comment]
Closing as inactive.
