### ISSUE TITLE
Panel indicator is blank if no unread posts exist

### ISSUE THREAD

**Issue by erkinalp** [mattermost/desktop#1380]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).

---

**Summary**
Panel indicator is a blank space if no unread posts exist.

**Environment**
- Operating System: Ubuntu 20.04 + GNOME 3
- Mattermost Desktop App version: 4.5.4 (.deb)
- Mattermost Server version: this problem is client-side only

**Steps to reproduce**
Read all your messages

**Expected behavior**
Mattermost icon or a green dot should appear instead

**Comment by Willyfrog** [comment]
hello @erkinalp thanks for reporting

could you provide a screenshot/video of the problem? I'm not really sure what you mean with "panel indicator"

**Comment by erkinalp** [comment]
![resim](https://user-images.githubusercontent.com/5833034/94948478-0fdd0980-04e8-11eb-9865-b0fab1b8b91d.png) Unread posts
![resim](https://user-images.githubusercontent.com/5833034/94948543-284d2400-04e8-11eb-8001-fc734ffe8ab5.png) No unread posts (The space allocated for indicator is blank)

**Comment by Willyfrog** [comment]
can you try switching to the light icon theme and see if that helps?

**Comment by erkinalp** [comment]
GNOME 3's activity bar is black even in the light theme, so I did not get how that would help.

**Comment by Willyfrog** [comment]
i've created a ticket to take a look at some point https://mattermost.atlassian.net/browse/MM-29343

thanks for reporting

**Comment by devinbinnie** [comment]
@erkinalp Does this still reproduce for you on v5.0.2? You can toggle the icon colour in the Settings window as well if you need to change the theme, since it does appear that the icon is there, just not particularly visible.

**Comment by erkinalp** [comment]
I now see a grayi-ish icon with GNOME 40.

**Comment by devinbinnie** [comment]
@erkinalp If you go into Settings and toggle the icon theme from Light to Dark, that might resolve your issue.

![image](https://user-images.githubusercontent.com/52460000/146228186-1907c9fb-6a97-4b7d-b936-6d44d058d696.png)

**Comment by erkinalp** [comment]
It works!
