### ISSUE TITLE
Add Ukrainian language in the spellcheck list

### ISSUE THREAD

**Issue by daniloff200** [mattermost/desktop#1381]
I saw today, that Russian language was added for spellcheck in  https://github.com/mattermost/desktop/pull/1375, and also, **simple-spellchecker** was updated to 1.0.1. In this version also Ukrainian was added, and, as a person from Ukraine I also would like to add my native language to the spellcheck list

P.s. also wondering, can it be counted as a Hacktoberfest PR, if it will be my first contribution to Mattermost?

**Comment by amyblais** [comment]
Ticket for reference: https://mattermost.atlassian.net/browse/MM-29652
