### ISSUE TITLE
[macOS] Big Sur icon support

### ISSUE THREAD

**Issue by mrleblanc101** [mattermost/desktop#1389]
Hi, 
It would be great to have a Big Sur assets so that Mattermost is ready when the OS launch.
You could reuse the iOS as-is or add the new drop shadow like apple did on it's icons.

**Comment by tdimeco** [comment]
Hi,

Here is a suggestion. What do you think?

![mattermost-bigsur-v1](https://user-images.githubusercontent.com/3112087/99183503-95d1ae80-273c-11eb-9ba3-a8db2233c792.png)

<img width="364" alt="dock-bigsur-v1" src="https://user-images.githubusercontent.com/3112087/99183492-7a66a380-273c-11eb-810e-5086f30763d0.png">

**Comment by tdimeco** [comment]
Here is the source Sketch file, in case it's needed for further use...

[Mattermost.sketch.zip](https://github.com/mattermost/desktop/files/5545979/Mattermost.sketch.zip)
