### ISSUE TITLE
Window title regression on Linux

### ISSUE THREAD

**Issue by SemaiCZE** [mattermost/desktop#1391]
**Summary**
Mattermost desktop 4.6.0 doesn't have nice compact window border as version 4.5.4 and adds border from my window manager (Gnome).

**4.5.4:**
![Screenshot from 2020-10-16 14-53-17](https://user-images.githubusercontent.com/12883607/96260845-e0d29780-0fbf-11eb-8c90-0c7e5eecbba9.png)

**4.6.0:**
![Screenshot from 2020-10-16 14-51-23](https://user-images.githubusercontent.com/12883607/96260903-f5169480-0fbf-11eb-90f1-e912f2b44b3e.png)

**Environment**
- Operating System: Linux (Fedora 32)
- Mattermost Desktop App version: 4.6.0 (both Flatpak and AppImage builds)

**Comment by esethna** [comment]
Hi @SemaiCZE, thanks for the feedback. This was recently changed as a result of feedback from many users that they prefer having the native window frame wrapped around the tab bar interface in Linux.

With that said, we're looking into improvements to make the tab bar not show if you only have one server connected: https://mattermost.atlassian.net/browse/MM-25961

**Comment by jsg2021** [comment]
I rather liked the custom title bar tbh. I would like the option to choose the macos & windows 10 styles for myself on Linux. 
![image](https://user-images.githubusercontent.com/577453/96326957-b05c1f00-0ffa-11eb-98cc-d1edf9a93fcc.png)
Esp, since my theme looks like macOS...

**Comment by SemaiCZE** [comment]
Hi @esethna,
thanks for your clarification. I didn't know that it's intentional, for me it's just useless space on my screen. But I respect what people want and closing this issue 🙂
