### ISSUE TITLE
4.6.0 does not play notification sound on Windows OS

### ISSUE THREAD

**Issue by cbrand-ludlums** [mattermost/desktop#1395]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
4.6.0 does not play notification sound on Windows OS

**Environment**
- Operating System: Windows 7, Windows 10 1909, 2004, 20H2
- Mattermost Desktop App version: 4.6.0 (exe installer)
- Mattermost Server version: 5.28.0 

**Steps to reproduce**
receive notification in desktop app
**Expected behavior**
when receiving notification, see toast (banner) notification and hear a notification sound
**Observed behavior**
when receiving notification, see toast (banner) notification, but no notification sound is played

**Notes**
To test, I spun up fresh installs of Windows 7, Windows 10 1909, Windows 10 2004 & Windows 10 20H2.  Also fresh installs of Solus Budgie, Linux Mint 20.  On the windows installs, I used the .exe installer.  Of these, only the Linux desktop app played the notification sounds.  On each virtual machine, I was able to select the new custom notification sound and hear them when selecting one, but no sound ever played when receiving notifications.  If I install 4.5.4 on windows, notification sounds played as expected.

Anyone else notice this behavior on windows or am I missing something?

**Comment by amyblais** [comment]
I've opened a ticket and asked a dev to investigate this today https://mattermost.atlassian.net/browse/MM-29921.

**Comment by cbrand-ludlums** [comment]
Thanks!
