### ISSUE TITLE
All of my text is being labeled as misspelled or has the red underline.

### ISSUE THREAD

**Issue by mobesgithub** [mattermost/desktop#1398]
All or most of my words are marked as misspelled.

https://www.loom.com/share/cff6a86c7def42da9501f7a77e09d945

I updated the app to the latest version but still have the issue.

**Comment by amyblais** [comment]
@mobesgithub Which spelling language do you have enabled (right-click on any word you're typing > Spelling language)?
Which language do you have enabled in Account Settings > Display > Language?

**Comment by mobesgithub** [comment]
> @mobesgithub Which spelling language do you have enabled (right-click on any word you're typing > Spelling language)?
> Which language do you have enabled in Account Settings > Display > Language?

Oh I see, didn't notice that before. Looks like it got switched to Portuguese. Thanks Amy!
