### ISSUE TITLE
Changing language forces menu focus and makes it hard to write multi-language messages

### ISSUE THREAD

**Issue by steve-todorov** [mattermost/desktop#1399]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

If you use multiple languages you would normally swap between them via `ALT + SHIFT`.

However, because of an Electron bug (https://github.com/electron/electron/issues/22213), this focuses the menu and thus you need to either hit Escape like 15 times or manually click with the mouse in the message input. 

As you can imagine, this becomes an **EXTREME PAIN** when your workflow requires language switch. 
I literally need to slow down my entire flow to avoid and go around this bug.

Mattermost as well as https://github.com/RocketChat/Rocket.Chat.Electron/issues/1355, Skype, Slack and other Electron based applications also have this issue and there are a dozen of opened tickets about this in the Electron github issue tracker.

**Environment**
- Operating System: Ubuntu 20.04 LTS
- Mattermost Desktop App version:  Mattermost Version: 4.6.1 
- Mattermost Server version: Mattermost Version: 5.28.1 

**Steps to reproduce**

Setup an additional input language and configure it to switch via  `ALT + SHIFT`.
Start typing and switch fast which is common practice since sometimes you write `нещо на Български език :D` where part of the message is in Bulgarian and part of it an emoji which is in English.

**Expected behavior**

Be able to write a message like a normal person without having to use the mouse to 

**Observed behavior**

`ALT + SHIFT` causes menu focus and severely complicates writing and usage.

![image](https://user-images.githubusercontent.com/2303663/97231716-95509280-17e4-11eb-85e1-b8e774202f9e.png)

**Possible fixes**

Usually this issue goes away if you can set the application to work in full screen.
This hides the toolbar menu therefore it never gets focused.
However with the latest desktop version `5.28.1` of Mattermost there's a top toolbar which is always shown even in full screen and the workaround no longer work.

I would suggest making a simple checkbox in the `App Options` which is under `File -> Settings` that can hide the toolbar (which is something I believe used to be there?). This would be the easiest solution, because the guys from Electron don't seem to be interested in fixing this bug on their end.

**Comment by Willyfrog** [comment]
Hi, while not directly addressing what you say, we do have a plan to hide the custom window in case of having only one server. You can see more details in the [Jira ticket](https://mattermost.atlassian.net/browse/MM-25961)

**Comment by steve-todorov** [comment]
Thank you very much for pointing me to the jira ticket! I've dropped a message there as well! :)

**Comment by vquemener** [comment]
See also #1080.

**Comment by Willyfrog** [comment]
you can try https://github.com/mattermost/desktop/releases/tag/v4.7.0-rc6 to see if that fixes the problem. it should be addressed there
