### ISSUE TITLE
Windows desktop notification icon barely readible

### ISSUE THREAD

**Issue by mavct** [mattermost/desktop#1402]
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Just updated to 4.6.1 and compared to previous versions, the notification icon on the Windows Desktop app is now difficult to read.

**Environment**
- Operating System: Windows 10
- Mattermost Desktop App version: 4.6.1

**Steps to reproduce**
By receiving messages, the blue or red badge appears on the icon situated in the taskbar. 

**Expected behavior**
Bigger and more readable badges like previous versions or the desktop app

**Observed behavior**
Top row is from a previous version (like 4.2.0). Bottom row is from version 4.6.1

![image](https://user-images.githubusercontent.com/13253468/97580136-4fa0ef00-19c9-11eb-83eb-f96ad9ccb9f8.png)

**Comment by Willyfrog** [comment]
thanks for reporting, I'll bring this up with the team.

**Comment by Willyfrog** [comment]
ticket created: https://mattermost.atlassian.net/browse/MM-30409

**Comment by amyblais** [comment]
I'll close this for now as this was fixed for v4.7.0, but feel free to re-open it if the problem persists,
