### ISSUE TITLE
Spell check being overly aggressive

### ISSUE THREAD

**Issue by alex-taffe** [mattermost/desktop#1410]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
The spellchecker is correcting before words are done being typed, for example correcting `immediately` to `I’mmediately`. This started when upgrading from 4.4.X to 4.6.X

**Environment**
- Operating System: macOS 10.15.7 (19H2)
- Mattermost Desktop App version: Version 4.6.1 (4.6.1.7401)
- Mattermost Server version: 5.28.0

**Steps to reproduce**
1. Open chat
2. Type a word that might be a contraction (ex: idk or immediately)
3. Note the correction to `I’dk` or `I'mmediately`

**Expected behavior**
The auto correct respects macOS system behavior and doesn’t autocorrect until the word is done being typed

**Observed behavior**
The auto correct activates after typing the next letter (ex when typing `immediately`, typing the 2nd `m` immediately changes the string `im` to `I’m`)

**Possible fixes**

**Comment by Willyfrog** [comment]
do you have osx to automatically correct the spelling? https://support.apple.com/en-hk/guide/mac-help/mchlp2299/mac

**Comment by alex-taffe** [comment]
![image](https://user-images.githubusercontent.com/6820226/98272385-07e90d00-1f5f-11eb-8ae2-c9c976b2cc44.png)
I do yes, but it still shouldn’t be correcting until after space is pressed

**Comment by alex-taffe** [comment]
For what it’s worth, I have `im` a a manual replacement to `I’m` in system preferences. But it doesn’t cause problems in any other app
![image](https://user-images.githubusercontent.com/6820226/98275890-2ea94280-1f63-11eb-9d29-efa91f75ab10.png)

**Comment by Willyfrog** [comment]
if you remove the correct spelling automatically, does it behave properly?

**Comment by alex-taffe** [comment]
That does not cause it behave properly. But if I remove my `replace im with I'm` rule, it does behave properly, so seems to be related to the replacement

**Comment by Willyfrog** [comment]
> But if I remove my `replace im` `with I'm` rule, it does behave properly, so seems to be related to the replacement

that seems to hint that the os is the problem not so much the app, not sure how to help you here :/

**Comment by alex-taffe** [comment]
It’s only recent versions of Mattermost where it’s occurring though. It doesn’t occur in older versions, nor any other app on my system. Every other app respects how the behavior is supposed to work

**Comment by Willyfrog** [comment]
is there anything else affecting this replacements? I've added a rule for `im` to be replaced by `I'm` and it is suggested but not forced. also if I hit any key other than space the suggestion gets removed. if I hit space it does get replaced.

**Comment by alex-taffe** [comment]
I don’t see anything else that could be causing it, but not sure

**Comment by Willyfrog** [comment]
i've just rechecked in big sur and I can't reproduce this behaviour either.

When I type `Im` it suggests using `I'm`, but doesn't replace right away, if I type space it gets corrected, if I type any other letter the suggestion dissappears and doesnt substitute anything. AFAIK this is the expected behaviour.

I'm leaving the issue open in case someone can provide more details, but without being able to reproduce it is hard to think of possible solutions (either by modifying the app or by config)

**Comment by alex-taffe** [comment]
This seems to be an issue with Electron as a whole as Slack is doing the same thing. Filed a bug on that project https://github.com/electron/electron/issues/32101

**Comment by devinbinnie** [comment]
@alex-taffe Is this still an issue in Mattermost? Looking at the upstream issue it looks like Slack has the issue as well.

**Comment by alex-taffe** [comment]
@devinbinnie  I'm honestly not sure, I've moved to a company that uses Slack. It's definitely still an issue in Slack and driving me nuts

**Comment by devinbinnie** [comment]
Looks like this issue was closed by Electron and doesn't look like it was re-opened. I'm guessing something has been fixed or dealt with else, so I'm going to close as inactive for now.

Will re-open if Electron opens a new issue or it comes up again.
