### ISSUE TITLE
Can't close the application window on Linux

### ISSUE THREAD

**Issue by plaperdr** [mattermost/desktop#1415]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Using the X to close the application window on Linux does not work. It either minimizes the application or does not do anything.

**Environment**
- Operating System: Ubuntu 20.04 - Gnome 3.36.3
- Mattermost Desktop App version: 4.6.1 
- Mattermost Server version:  5.26.2 

**Steps to reproduce**
1) Open the Mattermost application.
2) Click on the X on the top right of the application.

**Expected behavior**
The application should quit.

**Observed behavior**
Two behaviors are observed:
- By clicking on the X, the application minimizes despite "Leave app running in notifications area when application window is closed" being unchecked.
- In Gnome Activities screen, clicking on the X does not do anything.

**Possible fixes**
Probably change this line to "mainWindow.close()" ?
https://github.com/mattermost/desktop/blob/master/src/main/mainWindow.js#L137

**Comment by Willyfrog** [comment]
hello! and thanks for reporting.
we are aware of the issue and working to fix it in a future release. 

Meanwhile, I'll close the issue as it is already reported [here](https://github.com/mattermost/desktop/issues/90) 

Feel free to reopen if you feel it is a different kind of issue.

**Comment by esethna** [comment]
@Willyfrog do we have a JIRA bug ticket to track this? If not let's open one?

**Comment by Willyfrog** [comment]
there are different complains depending on how people is used to close the app.

i've [created a ticket](https://mattermost.atlassian.net/browse/MM-30713) to try and fix all of them and try to be consistent.
