### ISSUE TITLE
[feature request] newer electron

### ISSUE THREAD

**Issue by greyltc** [mattermost/desktop#1416]
Looks like this needs electron 7 today
https://github.com/mattermost/desktop/blob/83bae0c2b8e3b479988cd3c9507bb47eab0c3422/package.json#L57

Version 11 is the stable release of electron now. I wonder if you folks could bump up the electron version that mattermost builds on.

Thanks!

**Comment by Willyfrog** [comment]
it is planned to upgrade in a future release. newer versions have some breaking changes that need to be worked on.

Closing the issue for now, but feel free to reopen if you feel it wasn't addressed
