### ISSUE TITLE
How to change language of dictionary in UI?

### ISSUE THREAD

**Issue by JoeMurray** [mattermost/desktop#1419]
I use the app with several Mattermost sites. I typed a message in French in one and I vaguely recall that something came up that made all the spelling mistakes go away. However, I normally use English, and now all of my English words are underlined in red. How do I switch back to English? There are no sections in the User's Guide for Language https://docs.mattermost.com/guides/user.html

**Comment by amyblais** [comment]
You can right-click on any word you're typing > Spelling language.

Please see: https://docs.mattermost.com/help/apps/desktop-guide.html#app-options ("Check spelling")

**Comment by JoeMurray** [comment]
Merci beaucoup!
