### ISSUE TITLE
Notifications make sounds even when I have disabled notification sounds

### ISSUE THREAD

**Issue by mcfedr** [mattermost/desktop#142]
Actually, if i don't disable sounds then two sounds are played at the same time, and if I disable sounds only the desktop client sound is played.

I am on OSX

**Comment by yuya-oc** [comment]
Please see #38

**Comment by mcfedr** [comment]
Desktop notification sounds? I have turned this off, still get sounds

**Comment by yuya-oc** [comment]
Assuming that, the sound is played by Notification Center. Please disable from OS X Preference app.
