### ISSUE TITLE
Linux --version doesn't work

### ISSUE THREAD

**Issue by pierrehenrymuller** [mattermost/desktop#1422]
Hello,

The Linux version of Mattermost desktop respond to --version or -v with correct information, we receive "unknow".

**Environment**
- Operating System: Debian 10
- Mattermost Desktop App version: 4.6.1

**Steps to reproduce**

For tgz archive : 

```
wget https://releases.mattermost.com/desktop/4.6.1/mattermost-desktop-4.6.1-linux-x64.tar.gz
tar xvfz mattermost-desktop-4.6.1-linux-x64.tar.gz
cd mattermost-desktop-4.6.1-linux-x64
./mattermost-desktop -v
unknow
./mattermost-desktop --version
unknow
```

For Appimage : 
```
wget https://releases.mattermost.com/desktop/4.6.1/mattermost-desktop-4.6.1-linux-x86_64.AppImage
chmod +x mattermost-desktop-4.6.1-linux-x86_64.AppImage
./mattermost-desktop-4.6.1-linux-x86_64.AppImage  -v
unknown
./mattermost-desktop-4.6.1-linux-x86_64.AppImage --version
unknown
```

**Expected behavior**

```
./mattermost-desktop  -v
4.6.1
./mattermost-desktop --version
4.6.1
```

Actually I can't check the current version of desktop client and the script who look for new release need to download all the time.

Thanks

**Comment by Willyfrog** [comment]
what was the last version that worked for you?

I've created a [jira ticket](https://mattermost.atlassian.net/browse/MM-31129) for it

**Comment by pierrehenrymuller** [comment]
I don't know, before I have a script who download the latest stable from github. Now I would like to optimize this to download the archive only if version differ from latest release.

**Comment by vaaas** [comment]
I'll take this one.
