### ISSUE TITLE
Branching model

### ISSUE THREAD

**Issue by yuya-oc** [mattermost/desktop#143]
Now there are two active branches, master and dev. They almost follow git-flow, it's used to keep master stable. However recently I noticed that careful maintenance of the previous version is a rare case.

So I want to decide the branching model after v1.3.0. Which is better for contributors, git-flow or GitHub flow? (Now I'm considering GitHub flow to simplify the model)

**Comment by yuya-oc** [comment]
Demerit of GitHub flow: Docs will be different from the latest stable release.

**Comment by MetalCar** [comment]
Actually, I'm not sure from which branch i should create my branch. `master` or `dev`? Or will this question be answered, when we decided to use Git Flow or GitHub Flow?

**Comment by yuya-oc** [comment]
Sure. In my thoughts,

- git-flow style
  - master: recommended for bug and minor fixes.
  - dev: recommended for any improvemnts.

- GitHub flow style
  - master: all improvements. In some cases, topic branch will be created.

On my experience, CONTRIBUTING.md is not read, so GitHub flow is better for avoiding complexity.

**Comment by MetalCar** [comment]
+1 GitHub flow since we are currently working in github.

**Comment by Razzeee** [comment]
+1 for github. That would mean that the dev branch gets removed completely right?

**Comment by yuya-oc** [comment]
yes.

**Comment by yuya-oc** [comment]
As a result of conversation, `dev` will be obsoleted.

Ref: #171

**Comment by Razzeee** [comment]
A small side note @yuya-oc would you work in your fork then and not create branches on upstream?

**Comment by yuya-oc** [comment]
Would you tell me the reason for reference?

**Comment by Razzeee** [comment]
Well I think it would be clearer for everyone involved, especially new people, if they don't have branches your currently working on in their remotes and just can work with master.

**Comment by yuya-oc** [comment]
So the people can't know what is WIP. Maybe everyone(especially new people) doesn't check my fork in order to know the branches. I think topic branches should be created at mattermost/desktop in order to prevent wasting their time.

**Comment by Razzeee** [comment]
If you want to go that route, you need to do it for everyone involved.

Another option would be to "claim" an issue and let everybody know that way, what your working on.

**Comment by yuya-oc** [comment]
Thank you for feedback. Sure, I try to indicate what my working on.
