### ISSUE TITLE
desktop client doesn't memorized credentials anymore?

### ISSUE THREAD

**Issue by bcag2** [mattermost/desktop#1430]
**Summary**
After update to [mattermost-desktop-4.6.1-linux-x64.tar.gz](https://releases.mattermost.com/desktop/4.6.1/mattermost-desktop-4.6.1-linux-x64.tar.gz?src=dl) (when run mattemost-desktop --version, it returns v4.3.2 !), I set back my accounts but it require enters login each day when I start my computer. With previous version, login was memorized.

**Environment**
- Operating System: Ubuntu LTS 18.04
- Mattermost Desktop App version: 4.3.2 
- Mattermost Server version: X.X.X

**Comment by Willyfrog** [comment]
Hello and thanks for reporting

if you do a file->about does it also say 4.3.2?

does the program have write permissions in the config folder (it is usually in `~/.config/mattermost`)

**Comment by bcag2** [comment]
yes, it is also 4.3.2

I have `~/.config/Mattermost` folder with mod 755 on my $USER: account.
with folder (blob_storage for example), files and links modified today

**Comment by Willyfrog** [comment]
does this login everyday also happens with the browser? It might be the session cookie not having a long life span. If the authentication server (wether that's mattermost server or third party) was upgraded/reconfigured recently the value might have changed

**Comment by bcag2** [comment]
Hello, I backuped last Friday my  `~/.config/Mattermost` and launch back mattemost-desktop and this Monday morning, it doesn't ask me logins.
