### ISSUE TITLE
Maximized window leaks to other monitors (fixed in Electron 8.5.3)

### ISSUE THREAD

**Issue by Tamberlox** [mattermost/desktop#1432]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
When Mattermost Desktop client is maximized, it will leak to onto other monitors. This happens due to an issue with Electron that has been fixed in Electron 8.5.3.

**Environment**
- Operating System: Windows 10
- Mattermost Desktop App version: 4.6.1 
- Mattermost Server version: 5.29.0 

**Steps to reproduce**
Maximize Desktop Client

**Expected behavior**
The program should fit into the monitor and not go beyond.

**Observed behavior**
The program leaks onto the other monitors.

**Screenshot**
![2020-12-19 22_51_08-](https://user-images.githubusercontent.com/56069014/102700352-ec0aa380-424c-11eb-9a72-d6558e6f3e78.png)

**Possible fixes**
Update Mattermost Desktop Client to Electron 8.5.3 or higher.

**Comment by bbodenmiller** [comment]
Latest release uses Electron 12 so maybe this is fixed?

**Comment by Tamberlox** [comment]
> Latest release uses Electron 12 so maybe this is fixed?

Yep it's not doing it anymore, thanks for the heads up!
