### ISSUE TITLE
GitLab Login broken because of CloudFlare checks

### ISSUE THREAD

**Issue by anebi** [mattermost/desktop#1435]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: Mac OS Catalina
- Mattermost Desktop App version: 
- Mattermost Server version: Version: 5.28.0

**Steps to reproduce**
1. Integrate Mattermost login with GitLab
2. Click to login using GitLab on Mattermost Desktop client
3.

**Expected behavior**
Shows GitLab login page
**Observed behavior**
CloudFlare browser check happens where redirect never happens

Images
--------
<img width="1440" alt="Screenshot 2020-12-26 at 23 09 51" src="https://user-images.githubusercontent.com/225278/103159491-bc224980-47d2-11eb-959e-501fcca680be.png">
<img width="1440" alt="Screenshot 2020-12-26 at 23 24 48" src="https://user-images.githubusercontent.com/225278/103159493-bfb5d080-47d2-11eb-8790-4bf306ab521b.png">

**Comment by Willyfrog** [comment]
hello and thanks for reporting!

most likely we are blocking some requests that are preventing gitlab to operate. can you try again with the server console opened and see what's going on in the network tab?

**Comment by anebi** [comment]
Hi,

Thank you very much for your fast reply.

From what I see it fails on GitLab sign_in returning 503.

I am attaching screenshot from network tab and also the export. I hope that this info will be useful.

Regards,
Ali Nebi

[devtools-export.har.zip](https://github.com/mattermost/desktop/files/5745145/devtools-export.har.zip)
<img width="1440" alt="Screenshot 2020-12-27 at 22 31 39" src="https://user-images.githubusercontent.com/225278/103179352-c8221000-4893-11eb-948c-a70e50614e71.png">

**Comment by amyblais** [comment]
@Willyfrog Do the errors above indicate an issue? Is this affecting all Gitlab logins?

**Comment by Willyfrog** [comment]
no, they don't

I made a couple of quick tests and could reproduce, but I still have to dig into the issue. Most likely something is catching the requests and dropping them.

**Comment by Willyfrog** [comment]
created a ticket for it: https://mattermost.atlassian.net/browse/MM-31626

**Comment by Jenjen1324** [comment]
Would also be resolved by implementing OAuth securely: #1451

**Comment by Willyfrog** [comment]
yes, I agree and that's one of the big changes I'd like to see this year, but implementing OAuth would take some resources that we currently don't have as we are working on some other features. In the meantime, this is a patch to enable users to use their mattermost instance. I hope that makes sense, but as always feel free to discuss it either here or in the [dekstop channel in the community server](https://community-daily.mattermost.com/core/channels/desktop-app)

**Comment by Willyfrog** [comment]
closing the issue, we are currently in the process to generate an RC with this patch
