### ISSUE TITLE
Support apple m1

### ISSUE THREAD

**Issue by bastien-solutions** [mattermost/desktop#1436]
Now Electron v11 support Apple M1 ARM cpu on OSX is it possible to upgrade Mattermost version in order to get a native version of them on M1?

**Comment by Willyfrog** [comment]
not right now, we have a policy of staying one version behind the current version of electron, to try and be as stable as we can.
We are also looking into adding some native modules to help with notifications in windows, which would prevent us from moving from v9.3.3 until a patch is added to allow building of windowsRT modules.

As far as I know, previous versions of electron work using the new Rosetta and I haven't seen any reports of trouble or low performance, but let us know if you have any cases that it is happening.

Eventually we will, get to v11 (when v12 is released, if the mentioned bug is corrected), so I'm closing this issue, but feel free to reopen if there is anything I missed.

**Comment by bastien-solutions** [comment]
I confirm Intel version work through Rosetta 2.
But it's always better to use native program.

Anyway, thank you for your response.

**Comment by Willyfrog** [comment]
> I confirm Intel version work through Rosetta 2.
> But it's always better to use native program.
> 
> Anyway, thank you for your response.

I agree and we'll get there :)
