### ISSUE TITLE
SSH links in 1.2.0 client not working

### ISSUE THREAD

**Issue by hany** [mattermost/desktop#144]
Hi there,

We use a bot in Mattermost to display SSH links to hosts (in the form of `ssh://user@host`). It seems the recent upgrade of the client (1.2.0) broke the ability to follow these links. HTTP(S) links work just fine, but not others (like SSH). Downgrading back to the older client (1.1.1) works.

**Comment by yuya-oc** [comment]
Except http(s), the link is disabled by security reason.

**Comment by hany** [comment]
Hey @yuya-oc, may I ask what the security risk is allowing SSH links to be followed? Each operating system has configured handlers and its own security implemented. Can you outline what the risks are?

**Comment by hany** [comment]
Further to this, the links work just fine in a normal browser window. I'm sure Chrome/Firefox would have identified this as a risk a while ago if indeed there was a vital one.

**Comment by yuya-oc** [comment]
SSH is not matter. v1.1.1 allows ALL protocols for the link. I think this can be used for attacking. For example, `file://` protocol may open attacker's desired file. (I'm not a security professional, so this might be wrong.)

In v1.3.0, I'm considering to add the dialog to confirm the link and protocol. Is this okay?

**Comment by hany** [comment]
Hey @yuya-oc, I believe the operating system has sufficient protections against this and it's not the client's responsibility to govern which links to activate. The client should act the same way as the browser-based version. Browsers like Chrome and Firefox do allow opening links with `file://` and both Mozilla and Google are very security focused. The desktop version should act the same.

> In v1.3.0, I'm considering to add the dialog to confirm the link and protocol. Is this okay?

A dialog for each link will be very disruptive, and I do not think it's necessary.

Unless there are solid security concerns, is it possible to cut a minor release removing this restriction? Right now it's preventing others from upgrading to v1.2.0 due to this lost functionality.

**Comment by yuya-oc** [comment]
I think the browsers doesn't allow ALL protocols.

> The client should act the same way as the browser-based version.

Could you check the allowed protocols? Only I thinks allowing `ssh://` and `file://` will be insufficient (ssh is just your hope), so requests will be raised some times. It's troublesome to allow the protocol every time. However I don't know what protocols are desired and allowed.

**Comment by yuya-oc** [comment]
Sorry for extreme example, chrome shows a dialog to confirm `itmss//` to open iTunes. So maybe browsers have white-list.

**Comment by hany** [comment]
@yuya-oc I actually just tested this out by inventing a new protocol, `hany://`, and Chrome happily opened it up. See screenshots below:

<img width="1046" alt="screen shot 2016-05-21 at 9 53 16 am" src="https://cloud.githubusercontent.com/assets/26979/15448816/6493b3f4-1f3a-11e6-8b99-1517ed19f3ee.png">

![screen shot 2016-05-21 at 9 53 31 am](https://cloud.githubusercontent.com/assets/26979/15448819/6c0ef2e2-1f3a-11e6-8ae8-04eb5f3e735f.png)

I believe the dialog you're referring to is when the operating system has a configured handler for a particular link. Chrome will prompt you saying it will launch the external application and allows you to save the choice you make. However, this is only for launching external apps, which not all protocols do.

**Comment by yuya-oc** [comment]
Thanks. For now, there are no way to know the protocol will launch the external application, so I have to assume the link will open the external app. Does the choice on the dialog to memory the protocol as allowed become a compromise?

**Comment by hany** [comment]
Yes, I believe that's fair. Is there any chance that can be added in a minor release to avoid the long wait until 1.3.0? Right now we are unable to upgrade the client or server due to this limitation.

**Comment by yuya-oc** [comment]
Could you try this build? https://circleci.com/gh/mattermost/desktop/334#artifacts This is derived from v1.2.0.

btw, the client does not depend on server version in most case. So you can upgrade the server.

**Comment by hany** [comment]
> Could you try this build? https://circleci.com/gh/mattermost/desktop/334#artifacts This is derived from v1.2.0.

@yuya-oc yes! This works very well. Thank you!

> btw, the client does not depend on server version in most case. So you can upgrade the server.

We're hoping to take advantage of v3.0 of the server, which I was under the impression require new clients? Or is that only for mobile?

**Comment by yuya-oc** [comment]
Sorry for not explaining enough, I had said about the desktop client only. In my memory, mobile clients depend on server version. So if you want to use mobile clients, please refer to announcements from Mattermost server team.

**Comment by hany** [comment]
@yuya-oc thanks for the clarification. Makes sense!

Do you think it's possible to release a minor version with this latest build? Or will it need to wait for v1.3.0?

**Comment by yuya-oc** [comment]
I want to prepare v1.2.1. Please wait a moment.

**Comment by hany** [comment]
@yuya-oc thanks very much for the release! Looks to be resolved now!
