### ISSUE TITLE
Directory symlinks not followed when selecting an attachment

### ISSUE THREAD

**Issue by wck0** [mattermost/desktop#1446]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

Interface to add an attachment does not follow directory symlinks.

**Steps to reproduce**

- Pop!_OS 20.04 LTS
- Mattermost Desktop App version 4.6.0
- Mattermost Server version 5.25.0

1. Open desktop client.
2. Choose any channel.
3. Click the paperclip icon.
4. Double-click to navigate to a symlinked directory.
5. Fail with the message 'There was a problem uploading your files."

**Expected behavior**
Step 4 above does not fail, but instead navigates to the symlinked directory.

I have not observed this behavior with any other application on my machine.

**Observed behavior**
Symlinks appear as files not directories in the GUI.

The only error message is "There was a problem uploading your files."

**Possible fixes**

?

---

[JIRA tickets](https://mattermost.atlassian.net/browse/MM-14183?jql=labels%20%3D%20desktop) are created for all valid bug reports filed here. Bugs and features that the Mattermost core team are not immediately working on are opened as [Help Wanted GitHub issues](https://developers.mattermost.com/contribute/getting-started/contribution-checklist/) and welcome to contributions. 

Our goal is to bring the Mattermost desktop repository into our day-to-day internal process with the hope of having more frequent desktop releases with faster feature development and turnaround time on bug fixes.

**Comment by Willyfrog** [comment]
Hello and thanks for the feedback.

Quick question: does this behavior reproduces if you are using the browser for accessing mattermost?

**Comment by wck0** [comment]
It does not. The browser behaves as expected.

-------- Original Message --------

**Comment by devinbinnie** [comment]
@wck0 Does this reproduce for you on v5.0.2? This does not reproduce for me.

**Comment by devinbinnie** [comment]
Closing as inactive
