### ISSUE TITLE
Spell checker: enable "add to dictionary"

### ISSUE THREAD

**Issue by 2019-05-10** [mattermost/desktop#1464]
spell checker does underline words it doesn't know -- but there's no way to add the word to its dictionary.
![image](https://user-images.githubusercontent.com/50481865/106896246-99e4eb00-66f1-11eb-80f0-a6cf26be9626.png)
Thus the same word will be marked over and over again, rendering spell checking somewhat pointless.

**Comment by Willyfrog** [comment]
hi, this is not possible with our current dictionary implementation, but we are working on adding a chrome-like one that will have this option. there is already a [ticket for that](https://mattermost.atlassian.net/browse/MM-27545)

**Comment by Willyfrog** [comment]
this is fixed in 4.7, currently on RC
