### ISSUE TITLE
Introduce auto updates

### ISSUE THREAD

**Issue by Razzeee** [mattermost/desktop#147]
For auto updates to work, we will need a server running 
- [ ] https://github.com/ArekSredzki/electron-release-server
or
https://github.com/Aluxian/squirrel-updates-server

- [ ] Update the application code acordingly

**Comment by Razzeee** [comment]
https://github.com/mattermost/desktop/pull/162

**Comment by Razzeee** [comment]
This seems to be an duplicate of #15

**Comment by jasonblais** [comment]
That's correct @Razzeee, I'll close this issue as a duplicate of #15 and have carried over your initial comment there.
