### ISSUE TITLE
Preview site with invalid certificate fails

### ISSUE THREAD

**Issue by tbille** [mattermost/desktop#1478]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

Preview links with an invalid certificate returns an error on channels.

**Environment**
- Operating System: Ubuntu 20.10 / MacOS
- Mattermost Desktop App version: 4.6.2 (ubuntu), 4.6.1 (MacOS)
- Mattermost Server version: 5.31.0

**Steps to reproduce**

- On a channel, share a link with an invalid certificate (in my case https://dasprogramm.co.uk/ )
- Go out of the channel and go back

**Expected behavior**

The certificate is invalid. The preview should fail gracefully.

**Observed behavior**

![image](https://user-images.githubusercontent.com/2707508/108048495-068bae00-703f-11eb-8a45-6a9c147f5679.png)
![image](https://user-images.githubusercontent.com/2707508/108048719-45216880-703f-11eb-882d-c7e8eb7e42aa.png)

**Possible fixes**

**Comment by Willyfrog** [comment]
if you hit cancel, does it fail gracefully?
we added the option to handle invalid certificates, as there are situations when there is the need to bypass the certificate validation

**Comment by tbille** [comment]
It does fail gracefully.
But every time we go back on the channel we get the popup.

**Comment by Willyfrog** [comment]
Ok, I reopened [this ticket](https://mattermost.atlassian.net/browse/MM-24815) to discuss again with the team.

**Comment by devinbinnie** [comment]
Closing as this is the same issue solved here: https://github.com/mattermost/desktop/pull/1733
