### ISSUE TITLE
no close button on images links

### ISSUE THREAD

**Issue by gpopesc** [mattermost/desktop#1491]
I confirm (by marking "x" in the [ ] below: [x]):

- [x ] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [ x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System:
- Mattermost Desktop App version: 4.6.1 
- Mattermost Server version: 5.32.0 

**Steps to reproduce**
I send an external link with a picture to person from another group. That person click on the link and the picture was displayed full screen without little X in the top right corner.
That person hadn't active expand links activated from menu.
If the expand option is active, you can press the image and the close option is there, no issues with this option active.

**Expected behavior**
It should be active option to return to previous screen.

**Possible fixes**
I found only one workaround: ALT + left arrow or 
exit from application and reload

**Comment by amyblais** [comment]
This is queued for fixing in the next desktop app version https://mattermost.atlassian.net/browse/MM-32039.
