### ISSUE TITLE
Menu language

### ISSUE THREAD

**Issue by hwellmann** [mattermost/desktop#1497]
I'm on MacOS. My system language and my Mattermost account setting is German, but the menu bar entries are all in English.

There is no language setting in the application preferences (Cmd-,).

Is there any other config setting to change the menu language?

**Comment by Willyfrog** [comment]
So far there hasn't been an effort to internationalise the desktop app, so I'm afraid there is no option to switch languages for the time being.

**Comment by devinbinnie** [comment]
Closing as question was answered. There is a plan to start translating the Desktop App into languages starting next year :)
