### ISSUE TITLE
Links to the server's domain outside of its path open inside the app

### ISSUE THREAD

**Issue by imaspeer** [mattermost/desktop#1500]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

Links to a resource on the same domain as the mattermost server, but at a different path - that is not below the prefix mattermost is served at nor its configured SiteURL - open inside the app, replacing the mattermost webapp with no obvious way to go back to it.

**Steps to reproduce**

Windows app version 4.6.2, server version 5.31.1

Assuming a mattermost instance served at `https://your.domain.example/mattermost` with its SiteURL set to `https://your.domain.example/mattermost` (actual domain and path is unimportant as long as it's on a subpath and not the webserver's root):
1. Post a link to `https://your.domain.example/whatever` in any channel
2. On the desktop app, click the link

**Expected behavior**
Link opens in default browser like any link to a different domain would.

**Observed behavior**
Link opens inside the app, replacing the mattermost webapp. The only way to get back to mattermost is history -> back in the menu, or to quit the app.

**Comment by Willyfrog** [comment]
not right away that I know of, but we could probably try to add some other routes to the subpath server so we can try and reproduce.

**Comment by Willyfrog** [comment]
I created a ticket to track it: https://mattermost.atlassian.net/browse/MM-33738

**Comment by grisuthedragon** [comment]
The problem still exists in the 5.x series under linux. Is there any progress on this?

**Comment by devinbinnie** [comment]
Fixed in this PR: https://github.com/mattermost/desktop/pull/2702
