### ISSUE TITLE
Mattermost does not recognize the word "gauge", thinks it is mispelled

### ISSUE THREAD

**Issue by timkpaine** [mattermost/desktop#1518]
- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
`gauge` is marked as mispelled.

**Environment**
- Operating System: All
- Mattermost Desktop App version: All
- Mattermost Server version: All

**Steps to reproduce**
Type word "gauge"

**Expected behavior**
Not be underlined in red

**Observed behavior**
Underlined in red

**Possible fixes**

I've fixed upstream here: https://github.com/jfmdev/simple-spellchecker/pull/41

**Comment by Willyfrog** [comment]
Hi, next desktop version is not going to use simple-spellchecker anymore, so it should be fixed there.

I'll close the issue, but feel free to reopen if you have any concerns.

**Comment by timkpaine** [comment]
@Willyfrog thanks!

**Comment by timkpaine** [comment]
Looks like if you switch to electron's as planned it will leverage chromium's spellchecker, which in turn will use native Mac APIs (solving my problem) and hunspell which has the word present.
