### ISSUE TITLE
Mattermost win desktop windows size not correct

### ISSUE THREAD

**Issue by renchili** [mattermost/desktop#1521]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System:
- Mattermost Desktop App version: 4.6.2
- Mattermost Server version: NA this nothing related to Mattermost Server

**Steps to reproduce**

**Expected behavior**
Correct windows size 
**Observed behavior**
![image](https://user-images.githubusercontent.com/33677006/112783510-0e992d80-9082-11eb-8b83-591c3d626d7c.png)
![image](https://user-images.githubusercontent.com/33677006/112783564-2cff2900-9082-11eb-9971-c91f37acc488.png)
![image](https://user-images.githubusercontent.com/33677006/112783665-6b94e380-9082-11eb-9ea7-c104d7f748a7.png)

**Comment by renchili** [comment]
this made the scrollbar size on the split of the screen in the third screenshot can see there is a | at the bottom 
![image](https://user-images.githubusercontent.com/33677006/112783873-e231e100-9082-11eb-80ea-8c8f50104ea9.png)

**Comment by Willyfrog** [comment]
hi! thanks for reporting, is this happening in windows 10? or any other OS?

**Comment by devinbinnie** [comment]
@renchili Is this still an issue on v5.0.2?

**Comment by renchili** [comment]
> @renchili Is this still an issue on v5.0.2?

sorry we did not put this version into test.

**Comment by devinbinnie** [comment]
@renchili Can you test that for us? If it's been fixed we can close this issue.

**Comment by devinbinnie** [comment]
Closing as inactive.
