### ISSUE TITLE
MSI install possibly creating malformed shortcut that prevents notification onclick behavior

### ISSUE THREAD

**Issue by zpersichetti** [mattermost/desktop#1523]
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

Clicking notifications with an MSI install does not open to the message. This appears to be caused by a malformed shortcut. 

**Steps to reproduce**
Install Mattermost 4.6.2 from the MSI. Cause a notification. Click notification. It wont open. 

**Expected behavior**
Clicking the notification opens the app. 

**Observed behavior**
Clicking the notification does not open the app. 

**Possible fixes**
Locally: replacing the shortcut with a properly formed one (possibly from the .exe installer). 
Ive attached lnk parses for a broken and working one. 
Possible leads:
****working****
Property set GUID:                      9f4c2855-9f79-4b39-a8d0-e1d42de1d5f3
ID:                                     System.AppUserModel.ID
Value:                                  0x001f (VT_LPWSTR)      Mattermost.Desktop

****not working****
Property set GUID:                      9f4c2855-9f79-4b39-a8d0-e1d42de1d5f3
ID:                                     26
Value:                                  0x0048 (VT_CLSID)       CLSID: 082f98dc-8bd8-4771-9d01-3a75930884d1
ID:                                     System.AppUserModel.ID
Value:                                  0x001f (VT_LPWSTR)      Mattermost.Desktop

[lnkparse.txt](https://github.com/mattermost/desktop/files/6231514/lnkparse.txt)
Can also upload the shortcuts themselves if requested. 

---

[JIRA tickets](https://mattermost.atlassian.net/browse/MM-14183?jql=labels%20%3D%20desktop) are created for all valid bug reports filed here. Bugs and features that the Mattermost core team are not immediately working on are opened as [Help Wanted GitHub issues](https://developers.mattermost.com/contribute/getting-started/contribution-checklist/) and welcome to contributions. 

Our goal is to bring the Mattermost desktop repository into our day-to-day internal process with the hope of having more frequent desktop releases with faster feature development and turnaround time on bug fixes.

**Comment by Willyfrog** [comment]
we already have an [issue for that](https://mattermost.atlassian.net/browse/MM-19511), but i added a comment to it, as I think you provided valuable info.

thank you! :)

**Comment by zpersichetti** [comment]
> we already have an [issue for that](https://mattermost.atlassian.net/browse/MM-19511), but i added a comment to it, as I think you provided valuable info.
> 
> thank you! :)

Neat. FYI I attached a picture of what led me in this direction. I was trying to figure out what caused it by unistalling / reinstalling the exe and MSI and at some point the MSI popped this error during install (install still finished) and notification click through worked. 

![error](https://user-images.githubusercontent.com/17482716/113145756-d407d000-91fc-11eb-849e-a684b2aa4efc.PNG)

**Comment by Willyfrog** [comment]
hi! is this still happening with msi for 4.7.0-rc4?

**Comment by amyblais** [comment]
I'll close this for now as this was fixed for v4.7.0, but feel free to re-open it if the problem persists,
