### ISSUE TITLE
deb package 1.2.1 on debian : mattermost window can't be closed

### ISSUE THREAD

**Issue by rrajkomar** [mattermost/desktop#153]
When opening the mattermost window in a debian system, I find myself unable to close it and quit the application (there does not seems to be any shorcut on an app icon the tray bar either)

**Comment by rrajkomar** [comment]
Note : same isue as https://github.com/mattermost/desktop/issues/90

**Comment by yuya-oc** [comment]
It seems same. For now please use `Ctrl+Q`.
