### ISSUE TITLE
Mattermost taskbar icon is black on black background (macOS 11.2.3)

### ISSUE THREAD

**Issue by distante** [mattermost/desktop#1533]
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Mattermost icon is black

**Environment**
- Operating System: macOS Big Sur 11.2.3
- Mattermost Desktop App version: 4.6.2
- Mattermost Server version: 5.25.0

**Steps to reproduce**
- Set Mattermost to start automatically
- Start MacOs
- Close Mattermost
- Start Mattermost
- 
**Expected behavior**
Mattermost icon should be white.

**Observed behavior**
Mattermost icon is black
![image](https://user-images.githubusercontent.com/5490201/114363618-dbbe6180-9b78-11eb-996a-672df687259d.png)
Here when I press the icon
![image](https://user-images.githubusercontent.com/5490201/114363642-e678f680-9b78-11eb-8f70-bac8bb37cbd0.png)

**Comment by amyblais** [comment]
@distante Are the notes here helpful https://github.com/mattermost/desktop/issues/317#issuecomment-402703667? Not sure if this is something that could potentially be documented.

**Comment by distante** [comment]
Hi @amyblais , not really, I think my problem has more to do with MacOs light/dark modes.

**Comment by amyblais** [comment]
Does the same issue occur on v4.7.0-beta version https://github.com/mattermost/desktop/releases/tag/v4.7.0-beta2?

On Mac, I went to General > Appearance > Dark, but wasn't able to repro just now.

**Comment by distante** [comment]
@amyblais I tried v4.7.0 beta and it still happens. 

But I have found a way for you to reproduce it (I think).

* First I am using [this image](https://images.wallpaperscraft.com/image/light_lines_long_exposure_198920_3840x2400.jpg) as background 
* General > Appearance  -- Is not set to **Dark** but **Auto**, more important, in **Dark** mode it works correctly.
* Setting Appearance to **Light** reproduces the error.

**Comment by Willyfrog** [comment]
this should be fixed on 4.7.0-rc1 or greater. Although there is an issue with the tray icon being fixed in https://github.com/mattermost/desktop/pull/1549 which should make it to daily and rc2

**Comment by distante** [comment]
@Willyfrog The initial problem is fixed but now instead of getting an black icon with black background the app just crashes when I change Appareance from 'Auto' to 'Dark'. in system -> general

![image](https://user-images.githubusercontent.com/5490201/115407236-2599ee00-a1f0-11eb-92c4-ce5a6e106aa4.png)

```
Application: Mattermost 4.7.0-rc1 [commit: ceefc85
]
Platform: Darwin 20.3.0 x64
TypeError: Cannot read property 'normal' of undefined
    at setTray (/Applications/Mattermost.app/Contents/Resources/app.asar/index.js:68671:48)
    at refreshTrayImages (/Applications/Mattermost.app/Contents/Resources/app.asar/index.js:68624:5)
    at Config.handleDarkModeChange (/Applications/Mattermost.app/Contents/Resources/app.asar/index.js:373:32)
    at Config.emit (events.js:315:20)
    at NativeTheme.<anonymous> (/Applications/Mattermost.app/Contents/Resources/app.asar/index.js:39285:14)
    at NativeTheme.emit (events.js:315:20)
```

**Comment by Willyfrog** [comment]
yes, sorry about that, we noticed that on rc1, can you try rc2 (we released it a few minutes ago)? we should have fixed it, but let me know if it still happens

**Comment by distante** [comment]
Yes it works now

**Comment by GeorgLink** [comment]
I look forward to having this when it releases and my client updates

**Comment by kedar-joshi** [comment]
Is there any Windows specific version of this issue ? The stated behavior isn't MacOS specific and reproducible on Windows 10 as well.  

![image](https://user-images.githubusercontent.com/13585883/119122324-0808b000-ba4c-11eb-9873-cecc9665e88c.png)

I am using desktop client v4.7.0-RC5.

**Comment by Willyfrog** [comment]
@kedar-joshi that's a different issue, see https://github.com/mattermost/desktop/issues/1601
