### ISSUE TITLE
Problem with right click for spell check

### ISSUE THREAD

**Issue by Kaor** [mattermost/desktop#1541]
- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
nothing happen when rigth click on a (bad) word to check spell

**Environment**
- Operating System:
- Mattermost Desktop App version: 4.6.2
- Mattermost Server version: 5.33.0

**Steps to reproduce**
Just right click
**Expected behavior**
Propositions of goog words
**Observed behavior**
on 2 differents computers, same version of mattermost desktop, one work only
Maybe a problem of configuration ? of dependencies ? i don't know.
Thanks

**Comment by Willyfrog** [comment]
on 4.7 we are changing how the dictionary works, and it uses either the operating system one (in mac) or the hunspell one (win/linux)

as far as I've tested it worked in this new version (we recently published beta 2 if you want to try)

closing as we won't be fixing it for 4.6.2, feel free to reopen if you think we need to work on it.
