### ISSUE TITLE
"Save Image" does not work on the Windows application

### ISSUE THREAD

**Issue by nakasix** [mattermost/desktop#1542]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

When we right click on an image and click on "Save Image", nothing happens.

**Environment**
- Operating System:
- Mattermost Desktop App version: 4.6.2 
- Mattermost Server version: 5.32.1 

**Steps to reproduce**
Right click on an image and click on "Save Image".

**Expected behavior**
An opening of the Windows Explorer.

**Observed behavior**
Nothing.

**Possible fixes**

**Comment by Willyfrog** [comment]
hi, this is fixed in the upcoming v4.7, you can try the beta if you like to test.

closing for that reason, but feel free to reopen if you think we didin't address it properly.

**Comment by hirusi** [comment]
Mattermost Desktop App version: 4.7.0
Mattermost Server version: 5.34.2
OS: Windows 10

I do see a new option `Save Image As` along with `Save image` and `Copy image` -- but neither of the save actions do anything with an image. Doesn't look like this is resolved.

**Comment by hirusi** [comment]
Nevermind. A full system restart did the trick. Restarting Mattermost alone did not help.
