### ISSUE TITLE
Scrambled icon on taskbar in older version of windows

### ISSUE THREAD

**Issue by hectorskypl** [mattermost/desktop#1566]
I confirm (by marking "x" in the [ ] below: [x]):

- [x ] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [ x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: Windows 8.1 Pro
- Mattermost Desktop App version: 4.7.0-rc2 
- Mattermost Server version: 5.31.3 

**Steps to reproduce**

**Expected behavior**
Not scrambled icon i think :D
**Observed behavior**

**Possible fixes**

![345643](https://user-images.githubusercontent.com/5221712/115973821-2d42f500-a558-11eb-80c9-06226d722627.PNG)

**Comment by Willyfrog** [comment]
[ticket](https://mattermost.atlassian.net/browse/MM-35172) created for the issue

**Comment by Willyfrog** [comment]
Does 4.7.0-rc4 help with the issue? we did some changes in the windows icons and might yield different results

**Comment by hectorskypl** [comment]
Hello,

Now is much better, except fact that icon goes black and is barely visible when its out of tray.
![image](https://user-images.githubusercontent.com/5221712/120902433-ba419980-c640-11eb-9672-4b628443cea3.png)

**Comment by devinbinnie** [comment]
Closing as we have updated the icon. As for the mismatched colours, that depends on your OS's dark mode setting. We have an outstanding issue for some users on Windows 11 having this issue, but that appears to be an Electron problem.
