### ISSUE TITLE
[4.7.0-rc2] Windows client shows as macOS

### ISSUE THREAD

**Issue by hectorskypl** [mattermost/desktop#1567]
I confirm (by marking "x" in the [ ] below: [x]):

- [ x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: Windows 8.1 Pro
- Mattermost Desktop App version: 4.7.0-rc2 
- Mattermost Server version: 5.31.3 

**Steps to reproduce**
Login into mattermost server with 4.7.0-rc2 client :)

**Expected behavior**
Idenitfy as Windows client

**Observed behavior**

**Possible fixes**

**Comment by Willyfrog** [comment]
Hi there and thanks for reporting!

 just to clarify, do you mean the UserAgent or some other thing?

**Comment by hectorskypl** [comment]
> Hi there and thanks for reporting!
> 
> just to clarify, do you mean the UserAgent or some other thing?

Oh yes apparently its user-agent :)

**Comment by Willyfrog** [comment]
Thanks for reporting, I've [created an issue](https://mattermost.atlassian.net/browse/MM-35171) for it

**Comment by Willyfrog** [comment]
fixed in #1567
