### ISSUE TITLE
Impossible to install mattermost on debian bullseye (libappindicator3-1 dependency missing)

### ISSUE THREAD

**Issue by thurstonmore** [mattermost/desktop#1570]
I confirm (by marking "x" in the [ ] below: [x]):

    [x ] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/.
    [ x] This doesn't reproduce on web browsers (such as in Chrome). If it does, issue reports go to the Mattermost Server repository.
    [x ] I have read contributing guidelines.

hello, i cannot install mattermost-desktop-4.7.0-rc3-linux-amd64 (or others) on Debian Bullseye. 
I got this message
Package libappindicator3-1 is not installed.
Cheers
T

**Comment by Willyfrog** [comment]
Hi! is the package not available to install? I'm trying to figure out if the package needs upgrading or if its a problem especific with debian.

**Comment by thurstonmore** [comment]
Super, thanks for your quick answer. And yes i cannot manage to install it, seems not available from debian repository. (i am not a linux expert at all, so please take my info with care). I wonder if it is then more on debian side...

**Comment by thurstonmore** [comment]
Hello Guillermo, i don't fully understand all the on-going process. Does it mean that the future RC4 (coming in few days perhaps) will be ok for intall? thanks, sorry for the disturbance.

**Comment by Willyfrog** [comment]
No worries, I'm happy to help clarify.

Yes, the change will be shipped in RC4

**Comment by thurstonmore** [comment]
superbe, thanks a lot.
