### ISSUE TITLE
Wrong icon color in Windows taskbar notification area with light background

### ISSUE THREAD

**Issue by nmatt** [mattermost/desktop#1575]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] I have confirmed this is an issue on the newest beta build [available here](https://github.com/mattermost/desktop/tags)
- [x] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Tray icon is white on light background; regression from 4.6.x.

**Environment**
- Operating System: Windows 10
- Mattermost Desktop App version: 4.7.0-rc3 
- Mattermost Server version: 5.31.4 

**Steps to reproduce**
Run 4.7.0-rc3 on Windows with a light theme (Windows Settings > Personalization > Color > Choose your color > Light).

**Expected behavior**
The Mattermost icon in the taskbar notification area should be dark gray or black when the taskbar has a light color.

**Observed behavior**
The Mattermost icon in the taskbar notification is white and therefore barely visible on a light taskbar; see the attached screenshot: ![image](https://user-images.githubusercontent.com/7593340/116475665-75288b80-a87a-11eb-83e8-af07f1c7cfc6.png)

**Possible fixes**

This regression is likely caused by the icon overhaul triggered by issue #1402. That very issue is why I installed RC3, to have more visible badges again. But now the Mattermost icon itself is barely visible.

**Comment by amyblais** [comment]
A ticket for this is here: https://mattermost.atlassian.net/browse/MM-35302.
