### ISSUE TITLE
Wrong icon color in Windows taskbar notification area with dark background

### ISSUE THREAD

**Issue by elgrafico** [mattermost/desktop#1601]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
This is the inverted version of https://github.com/mattermost/desktop/issues/1575 ;-)
Tray icon is black on dark background; regression from v4.7.0-rc3 (2021-04-27)

**Environment**
- Operating System: Windows 10
- Mattermost Desktop App version: 4.7.0-rc4
- Mattermost Version: 5.33.3

**Steps to reproduce**
Run 4.7.0-rc4 on Windows with a dark theme (Windows Settings > Personalization > Color > Choose your color > Dark).

**Expected behavior**
The Mattermost icon in the taskbar notification area should be white when the taskbar has a dark color.

**Observed behavior**
The Mattermost icon in the taskbar notification is black and therefore barely visible on a dark taskbar; see the attached screenshot:  
![image](https://user-images.githubusercontent.com/754317/118008836-bf673d80-b34d-11eb-9195-f9b096533b45.png)

**Possible fixes**
none;  this might have been introduced by 47f36294b839ca20eca1a298a03c477ca7932954

**Unrelated**
I would like to take this opportunity to thank you. The desktop client is really great and I really appreciate your work on it!

**Comment by amyblais** [comment]
@Willyfrog Is there a ticket for this already?

**Comment by holle** [comment]
I have the same behavior under:

* OS: openSUSE 15.2
* Desktop: KDE Plasma 5.18.6
* Mattermost Desktop: 4.6.2

My Mattermost Icon is pitch black on a black KDE System Tray ;-)

So I guess we could use some Try "Icon Set" for dark and the existing for bright backgrounds.

As far as understand it, these files are the tray icons? (Git Repo)
resources/windows/tray.svg
resources/windows/tray_mention.svg
resources/windows/tray_unread.svg

Cheers, Holger

**Comment by holle** [comment]
After poking around in the git repo I figured out that the "dark" theme icon is invisible on a "dark" themed desktop while a "light" theme icon vice versa is invisible on a "light" background.

So I switched this in my config.json:
``` json
 "trayIconTheme": "light",
```

And started Mattermost anew. Now the icon shows as expected:

(openSUSE 15.2 / KDE Plasma 5.18 / Mattermost 4.6.2)

Cheers, Holger

PS: Locations of the config.json:
* Linux: `~/.config/Mattermost`
* Mac OS: `~/Library/Application Support/Mattermost`
* Windows: `%APPDATA%\Mattermost`

**Comment by Willyfrog** [comment]
@amyblais we can always reopen the original one https://mattermost.atlassian.net/browse/MM-35302 as it is related/followup. Since I added a bunch of different icons i might have messed up, although my test of the original PR was showing correctly, I'll go through it just to make sure there werent any other problems.

**Comment by Willyfrog** [comment]
closing the issue as wont fix, the only way to repro this is to use custom colors on windows having the Windows mode dark and default app mode light (same goes for light/dark combination which would result in a black over black)
having the same on both values or not using custom colors fixes the problem.

feel free to reopen if this is not the case and I missed some other repro steps that might need to be looked at.

**Comment by elgrafico** [comment]
So let's see if I got it right...
1. mattermost/desktop relies on electron's [nativeTheme](https://www.electronjs.org/docs/api/native-theme) API that exposes the **application** color mode (dark/light) only. 
2. There [doesn't seem to exist](https://github.com/electron/electron/issues/19729) an electron API that exposes the **system** color mode, which at least for Win10 would be more applicable in the context of selecting a suitable color for the taskbar icon.

If I understand correctly, mattermost/desktop makes an assumption about the system color mode based on the application color mode that is false in some cases - right?

@holle's trick with adjusting the config.json `trayIconTheme` doesn't seem to work for me, sadly.

**Comment by Willyfrog** [comment]
on 4.6.2 it used that property, but now it relies on nativeTheme, yes.

thanks for the link to the electron issue, I just subscribed to it, so if there are any changes we can update the app accordingly

**Comment by hrvojegolcic** [comment]
It appears to have something to do with "Personalization / Colors", but other apps seems not to have any issues with it like Mattermost do

![image](https://user-images.githubusercontent.com/6906827/131683787-51959f53-e6e3-4978-bd1e-eca9b83ae90c.png)

**Comment by Willyfrog** [comment]
can you share some examples of electron apps that don't show the problem? I've seen the issue in the electron repos as nativeTheme api doesn't support all the options from windows 10 regarding themes (or it didn't last time I checked)

There might be an alternative way, so any help finding that would be apreciated :)

**Comment by hrvojegolcic** [comment]
I didn't realize it's electron only issue. I mean generally other apps. I don't have electron app example. 
Regardless, shouldn't the issue be opened until solved?

**Comment by Willyfrog** [comment]
sure, done!

**Comment by biva** [comment]
Hello,
I tried to add a custom value for the tray icon, as suggested in https://github.com/mattermost/desktop/issues/1601#issuecomment-841082063
- "trayIconTheme": "#ffffff"
- "trayIconTheme": "light"
- "trayIconTheme": "#000000"

I save and restart my desktop app, but the icon in the taskbar it remains black and not visible in a dark taskbar in Windows 10.
![image](https://user-images.githubusercontent.com/9964305/139919121-ff53ac81-28d6-411f-a787-61f79171a27d.png)

Is there another value I can change? (I didn't find anything about _tray_ in https://docs.mattermost.com/messaging/customizing-theme-colors.html)

**Comment by Willyfrog** [comment]
try "trayIconTheme": "dark", although I'm not sure if that still affects the tray icon, but doesn't hurt to try :)

the docs you mention are about theming inside mattermost and that doesn't apply to the tray icon.

**Comment by biva** [comment]
Thanks @Willyfrog and sorry for my confusion. In this case, where should I add this parameter about "trayIconTheme"? On the server installation? (_/opt/mattermost/config/config.json_) On the local installation of the desktop app on Windows? (in this case, which file should I edit?)

Thanks again!

**Comment by Willyfrog** [comment]
it is a parameter in the local installation of the desktop app.

for a windows machine it should be in `%userprofile%\AppData\Roaming\Mattermost\config.json`

**Comment by biva** [comment]
Thanks! I closed the app, edited it (with `"trayIconTheme": "dark"`), started the app → nothing changes :(
I didn't have the issue before my update to v5 (currently 5.0.1)

For reference, here is the content of `C:\Users\biva\AppData\Roaming\Mattermost\config.json`:

```
  "showTrayIcon": false,
  "trayIconTheme": "dark",
  "minimizeToTray": false,
  "notifications": {
    "flashWindow": 0,
    "bounceIcon": false,
    "bounceIconType": "informational"
  },
  "showUnreadBadge": true,
  "useSpellChecker": true,
  "enableHardwareAcceleration": true,
  "autostart": true,
  "spellCheckerLocales": [
    "en-GB"
  ],
  "darkMode": false,
```

**Comment by pearj** [comment]
Apparently https://mattermost.atlassian.net/browse/MM-36058 fixed this in 5.0.4, but it's still not fixed for me.

**Comment by devinbinnie** [comment]
@pearj What happens if you set it to Dark instead?

**Comment by pearj** [comment]
> @pearj What happens if you set it to Dark instead?

Oh, that's embarrassing. I was thinking the icon is too dark so I want it lighter. As opposed to my toolbar being in dark mode so I need the icon in dark mode.

So yes, it works fine now that I have the right mode.

**Comment by hrvojegolcic** [comment]
BTW I've noticed the setting is also available in Mattermost Desktop App under File -> Settings -> Icon theme -> "Use system default"; I changed it to "Dark"

**Comment by GrabsOrion** [comment]
@CryptoSiD last comment from @hrvojegolcic solved the issue for me.
