### ISSUE TITLE
Version number disable notifications build in the electron project.

### ISSUE THREAD

**Issue by KheroNem** [mattermost/desktop#1603]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Noticed when you change the version in the `package.json` you loose the notification build in the desktop project, instead the webapp notification is fired. This happens only on the package build executable.

**Environment**
- Operating System: Windows
- Mattermost Desktop App version: 4.7.0-rc4 
- Mattermost Server version: 5.24.0
**Steps to reproduce**

1. Change the version number in the `package.json`
2. Run `npm install`
3. Run `npm run package:windows`
4. Go to the `release/win-ia32-unpacked` folder in the project directory.
5. Run the executable `Mattermost.exe`
6. Connect to your server and send a message to the connected account with another account.

**Expected behavior**
Receive the notifcation built in the file `src/main/notifications/Mention.js`
**Observed behavior**
Receiving the notification directly from the webapp the event handler is ignored.

**Possible fixes**
None yet.

**Comment by Willyfrog** [comment]
hello and thanks for reporting.
my guess is that this is a custom build, right? did you change the name of the app by any chance? if the desktop doesn't register properly with the server, the server won't send the message for the notification and will do an html notification instead

we don't check for the version number in any way for notifications, but we need to have the expected user agent for the server as well as doing the handshake, if any of these fail, you'll get an html notification

**Comment by devinbinnie** [comment]
Closing as explanation is given. Feel free to re-open if you have further questions.
