### ISSUE TITLE
Snap need update

### ISSUE THREAD

**Issue by boistordu** [mattermost/desktop#1605]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

To avoid this https://forum.snapcraft.io/t/snap-and-square-symbols-in-systems-popup/24466/15 the snap needs to be updated 

**Environment**
- Operating System: fedora 
- Mattermost Desktop App version: 4.6.2
- Mattermost Server version: X.X.X 

**Steps to reproduce**

**Expected behavior**

**Observed behavior**

**Possible fixes**

**Comment by Willyfrog** [comment]
Hi there! Thanks for reporting. Is there an error or any context regarding of what it needs for updating?

**Comment by boistordu** [comment]
Well I m not an expert of snap package but as you can see on the thread from the forum I post (where they are experts on the question), you can see also on an another thread of the forum where one of the dev directly answered me https://forum.snapcraft.io/t/snaps-show-squares-instead-of-fonts/18073/7
What needs to be updated to have a correct build.

**Comment by boistordu** [comment]
I ve update my original thread here because apparently the text was not showing properly with the link to the snapcraft forum

**Comment by devinbinnie** [comment]
Closing as this was updated to v5.0.2 a while ago.
https://github.com/snapcrafters/mattermost-desktop/pull/48
