### ISSUE TITLE
There is no hotkey for editing my own messages

### ISSUE THREAD

**Issue by tchv71** [mattermost/desktop#1614]
Please, add hotkey for editing myself messages - i mean three dotted menu on right of messages. The mouse way is too long on big windows

**Comment by Willyfrog** [comment]
Have you tried arrow up?

**Comment by tchv71** [comment]
Hmm, indeed its working! But it’s not obvious nor displayed in the menu

Regards,
***@***.***

**Comment by Willyfrog** [comment]
You have a list of available shortcuts with `command`+`/` for mac or `ctrl` + `/` for all other platforms.

**Comment by tchv71** [comment]
Thanks, but this is non standard nor Windows nor Mac hotkey, how would i know it? Perhaps, something Web specific...
