### ISSUE TITLE
Use Mattermost Desktop with SOCKS5 proxy [Ubuntu 20.04]

### ISSUE THREAD

**Issue by P9k** [mattermost/desktop#1622]
I would like to use the Mattermost Desktop app on Ubuntu 20.04 via a SOCKS5 proxy (established with SSH) to access a Mattermost instance running within an internal network.

With Firefox, everything works fine following these steps:

1. In a terminal, establish the SOCKS5 proxy with `ssh -D 8080 remote-server-in-internal-network`
2. In Firefox, I activate the proxy settings: 'Manual configuration' -> SOCKS5 (with localhost and port 8080) + Usage of SOCKS5 proxy to resolve DNS requests
3. In a new tab, I can access the Mattermost instance under `https://internal-domain-for-mattermost` (Mattermost server is set up to re-route from port 8085 to port 443)

However, using the Mattermost app does allow me to access the instance when using the internal domain `https://internal-domain`. It says that the address could not be found although Firefox can resolve it just fine.

Starting the Mattermost app with `--proxy-server="socks5://127.0.0.1:8080"` or `--proxy-server="socks5h://127.0.0.1:8080"` has the outcomes. 

I suspect that the DNS is not resolved via the SOCKS5 proxy the same way Firefox is able to. Also, I have experimented a bit and found that Chromium can resolve the DNS request via SOCKS5 when called with `--proxy-server="socks5h://127.0.0.1:8080"`. 

**Can you advise how I can get the Mattermost Linux app to resolve DNS via a SOCKS5 proxy?** :-)

Many thanks in advance!!

---

_A bit more background:_
Using the server's IP directly does not work for me: I **have** to use `https://internal-domain-for-mattermost` since another web service (a wiki) is running on port 443 of the server (under a different internal domain). Depending on the used domain name it is possible to choose which one should be called.

**Comment by Still34** [comment]
Ditto, I'm surprised this isn't a feature already.
