### ISSUE TITLE
How to toogle menubar?

### ISSUE THREAD

**Issue by leoniscsem** [mattermost/desktop#1624]
For troubleshooting, see [https://www.mattermost.org/troubleshoot/](https://www.mattermost.org/troubleshoot/).
Ubuntu 20.04
Mattermost 4.6.2
installed via snap from channel latest/stable

When I start the Mattermost desktop application, it comes with a collapsed / hidden menu bar, and instead it shows a "three dots menu" in the top left corner. When I (accidentally) press a key combination like Alt+W, it invokes the according window menu in the menu bar. So, instead of expanding the the "three dots" menu, the menu bar shows up and navigates to the respective menu entries. That's perhaps a minor issue, but what bothers me is, that I cannot collapse or hide the menu bar after that. I didn't find an entry in the "view" menu, neither did any key combination I have tried work. Only when I quite and restart the application, I find a collapsed menu bar. It's a bit of a drag, as  GTK window decorations already put a rather useless top bar above the main application windows, which has just a sole purpose - to inform me about the channel and the team I am currently browsing and sporting a close button. Below that is the tabbed bar of the main application, which already shows that information redundantly. Another level of redundancy at the cost of vertical space just looks useless to me.

**Comment by Willyfrog** [comment]
Hello and thanks for reporting! It indeed is annoying, I just filled a [ticket for it](https://mattermost.atlassian.net/browse/MM-36309) feel free to add any details to it.

**Comment by devinbinnie** [comment]
Closing as this is fixed.
