### ISSUE TITLE
Loosen uri validation for custom protocols launched from the app to match mattermost webapp

### ISSUE THREAD

**Issue by dmitrysamuylovpharo** [mattermost/desktop#1635]
### **Problem:** 
Since mattermost desktop release 4.6, the desktop client applies valid URL validation to custom protocols when a user tries to launch a link with a custom protocol from the mattermost app. In the past, prior to this release, this action would simply launch any application registered with the OS to handle this custom protocol and let that application take it from there. In the versions 4.6+, because of this validation, in some cases, the protocol URI fails valid URL validation and gets blocked from launching the app. This only happens in the desktop client, the same custom protocol works correctly if the mattermost app is accessed directly from the browser without the desktop client. In our case this change broke our custom protocol integration with a history of a couple of years of messages using this format.

**Example Problem Custom Protocol:** `taco:type=script;scriptname=somescriptname\parameter`
**Error Message Thrown:** `Untrusted popup window blocked:`

Discussed this with @Willyfrog and @jupenur and we seem to be in agreement that the desktop client should not be more restrictive with URL/URI validation than the webapp running within the browser.

**Code Preventing URI Launching**
https://github.com/mattermost/desktop/blob/c281f6680947e584eaee8b229b427dc66b45eaa0/src/main.js#L533

### **Proposed Solution:**
Remove URL validation currently being applied in the desktop client for any custom protocols, only apply this validation if the URI starts with `http:` or `https:`

**Comment by Willyfrog** [comment]
added a [ticket](https://mattermost.atlassian.net/browse/MM-36650) for reference, we'll discuss this in our sprint meeting. But tagging as help wanted as that might be the fastest way of getting it done ATM.

Thanks for bringing this to my attention :)

**Comment by yash2002109** [comment]
Hi @Willyfrog, @cpanato

I'd like to work on this issue. Could you please assign it to me?
