### ISSUE TITLE
Latest compiled desktop application prevent the use of gitlab sso

### ISSUE THREAD

**Issue by FuriousTurtle** [mattermost/desktop#1643]
I confirm:

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
The Gitlab SSO feature doesn't work with the current master because the form is never actually sent to the server.
**Environment**
- Operating System: Ubuntu 20.04
- Mattermost Desktop App version: 4.8.0 commit 86a3f13
- Mattermost Server version: 5.36.1

**Steps to reproduce**
Enable gitlab SSO in security options, logout, then try to log in using gitlab SSO

**Expected behavior**
It logs in with no problem

**Observed behavior**
Clicking the green button to validate the login password form doesn't do anything, no XHR or anything, no errors in the console.

**Possible fixes**
I will investigate in the week-end unless resolved

**Comment by FuriousTurtle** [comment]
Note that it works perfectly on chromium browser, I replicated my tokens in my desktop app to bypass the issue for now

**Comment by Willyfrog** [comment]
Hello there and sorry to hear about that, are you getting to a page that would "check your browser" or is this a different issue?

**Comment by FuriousTurtle** [comment]
After clicking on the SSO button, I'm redirected to a page which asks me for my sso login and password, as expected, but the 
connect button won't do anything. I tried to click on it, select it with tab and pressing enter, it's like it's somehow unplugged ? Yet the exact same page works perfectly on my chromium browser, I don't get why it wouldn't work on electron's chromium instance ...
![image](https://user-images.githubusercontent.com/45388199/124237316-b0179b80-db17-11eb-856a-7adb9838c540.png)

**Comment by Willyfrog** [comment]
if you go to view>developer tools for current server, does any error or log appear that might be relevant?

when you mention "default mattermost app" which version are you referring? 4.6.X or 4.7.0?

**Comment by FuriousTurtle** [comment]
There is no particular logs or anything, even with debug and stuff enabled
It works on 4.7.0

**Comment by Willyfrog** [comment]
I've created a [ticket to investigate](https://mattermost.atlassian.net/browse/MM-36923)
