### ISSUE TITLE
Taskbar icon flashing on new message arrival despite setting being disabled following 4.7.0 upgrade #1648

### ISSUE THREAD

**Issue by bbodenmiller** [mattermost/desktop#1649]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

Taskbar icon flashing on new message arrival despite setting being disabled following 4.7.0 upgrade

**Environment**
- Operating System: Windows 10
- Mattermost Desktop App version: 4.7.0 
- Mattermost Server version: 5.33.3 

**Steps to reproduce**

1. Install 4.7.0
3. Verify flash icon option is disabled in settings

**Expected behavior**

New message arrives, taskbar icon does not flash

**Observed behavior**

New message arrives, taskbar icon flashes

**Possible fixes**

Maybe related to https://github.com/mattermost/desktop/issues/1648

**Comment by Willyfrog** [comment]
most likely both issues are related, as in both cases seem to be ignoring the configuration for some reason.

**Comment by bbodenmiller** [comment]
https://github.com/mattermost/desktop/issues/1648#issuecomment-881321270

> can you go to the folder where the config is stored and remove everything but the json files? it might be something that is cached from a previous version.
> 
> the path to that folder usually is `c:\Users\<user>\AppData\Roaming\Mattermost`

Still getting flashing system tray icon after doing above

**Comment by Willyfrog** [comment]
are there any errors? can you try and launch mattermost from the command line as well as check the console logs (both the wrapper and the current server one) to see if there are any errors?

**Comment by bbodenmiller** [comment]
@Willyfrog I installed the 4.7.1 update and am still getting this issue. No errors showing in console logs or command line.

**Comment by amyblais** [comment]
I can reproduce, created a ticket: https://mattermost.atlassian.net/browse/MM-37797

**Comment by amyblais** [comment]
This is fixed in v4.7.2,

**Comment by bbodenmiller** [comment]
Looks like the fix was https://github.com/mattermost/desktop/pull/1696 for future reference.
