### ISSUE TITLE
Icon barely visible on taskbar notification area

### ISSUE THREAD

**Issue by giuliolastra** [mattermost/desktop#1657]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Icon barely visible on taskbar notification area

**Environment**
- Operating System: Windows 10 21H1
- Mattermost Desktop App version: 4.7.0
- Mattermost Server version: 5.34.2

**Steps to reproduce**
My Windwos color settings:
Windows Mode: Dark
App Preferred Mode: Light

![image](https://user-images.githubusercontent.com/15835362/125926497-902e7b1f-6c25-46e4-9e9a-227086ae5d37.png)

**Comment by Willyfrog** [comment]
hello and thanks for reporting. this is an upstream bug on electron as it doesn't give us access to both configurations, only one of them. We already have a [ticket](https://mattermost.atlassian.net/browse/MM-36058) for tracking it and will fix it as soon as electron gives us the chance.

I'll close this issue, but feel free to reopen or add details to the mentioned jira ticket.
