### ISSUE TITLE
Taskbar-Icon: unread message symbol does not disappear after reading messages on 4.7.0

### ISSUE THREAD

**Issue by mhsurfer** [mattermost/desktop#1658]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

The red badge for unread messages on the Windows task bar icon does not disappear after reading new message.

**Steps to reproduce**

- Windows 10 20H2 (Build 19042.1110)
- Mattermost client 4.7.0 commit b757742
- Mattermost server: 5.36.1
steps to reproduce
- use Windows client
- get new message
- task bar icon gets red badge with "1"
- open client and jump to new message

**Expected behavior**
- red badge should disappear after reading the new message 

**Observed behavior**
- red badge of task bar icon does not disappear
- however, the number of unread messages ("1") disappears
- red badge only disappears when switching to another channel

**Possible fixes**

---

[JIRA tickets](https://mattermost.atlassian.net/browse/MM-14183?jql=labels%20%3D%20desktop) are created for all valid bug reports filed here. Bugs and features that the Mattermost core team are not immediately working on are opened as [Help Wanted GitHub issues](https://developers.mattermost.com/contribute/getting-started/contribution-checklist/) and welcome to contributions. 

Our goal is to bring the Mattermost desktop repository into our day-to-day internal process with the hope of having more frequent desktop releases with faster feature development and turnaround time on bug fixes.

**Comment by amyblais** [comment]
This is fixed in v4.7.1 dot release,
