### ISSUE TITLE
Taskbar icon vs Tray icon

### ISSUE THREAD

**Issue by Razzeee** [mattermost/desktop#167]
On windows, the taskbar item can have a different status from the tray icon.
So we can have an mention in the tray, but it doesn't show in the taskbar. Maybe the taskbar is only reading data from the channel that is currently open for some reason?
I think it would be nice to have both based on the same data.

**Comment by yuya-oc** [comment]
I have thought that they are based on same data(Tray icon doesn't indicate the number of mentions because of its size). Could you tell detail?

**Comment by Razzeee** [comment]
It's the same data, just had a look. At least with dev branch.
So it has to either be a bug or was updated since 1.2.1 which I run at work.

**Comment by Razzeee** [comment]
(Can't compile the dev branch at work, but this is with 1.2.1)
For replecation:
1. Login with account a and b
2. Write a DM with account a to account b
3. Account b's desktop app won't show that there is a mention, on the taskbar.

**Comment by yuya-oc** [comment]
Hmm...I could get correct indication after the steps.
- taskbar: Red (1) badge
- tray icon: Red dot (means mention)

Windows 10 x64
Mattermost desktop: 1.2.1
Mattermost server: 3.0.0 (3.0.3)

**Comment by Razzeee** [comment]
Sorry, ignore me. I got a dual taskbar programm for windows 7 and I forgot, that one of the two taskbars just shows the app icon, nothing else. Sorry.
