### ISSUE TITLE
v4.7.0 - Mattermst client window does not open - the window remains permanently minimized on the taskbar. Windows 10.

### ISSUE THREAD

**Issue by IGrego** [mattermost/desktop#1675]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] I have confirmed this is an issue on the newest beta build [available here](https://github.com/mattermost/desktop/tags)
- [x] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: Windows 10
- Mattermost Desktop App version: 4.7.0.10824
- Mattermost Server version: can't see - window unavaliable

**Steps to reproduce**
1. Run app.
2. And you see minimized window in Windows task bar.
3. Click on icon in task bar has no effect.

**Comment by Willyfrog** [comment]
Just to clarify, is the app still running? I know windows sometimes keep the tray icon for a while but the app has crashed.

**Comment by IGrego** [comment]
The problem is solved - it was possible to open the window with the key combination: Win + Shift + M.
