### ISSUE TITLE
Ubuntu 20.04 Snap Client - allways Certificate Error (Error: net::ERR_CERT_AUTHORITY_INVALID)

### ISSUE THREAD

**Issue by qupfer** [mattermost/desktop#1677]
Hi,
we have a mattermost server (gitlab omnibus) with a company signed certificate. 
The company root-ca is installed to the ubuntu ca store (/usr/local/share/ca-certificates/company.crt) and open mattermost in browser (or curl'ing) works fine.
But the Desktop (snap) app always complains about the certificate. 
Any change to get rid of the massage? 
I think the problem is, that its not a direct self-signed, but also no public accepted one. 
Thanks

**Comment by Willyfrog** [comment]
when the popup appers, you can click on details about the certificate and from there add a permanent exception so it won't bother you again, please make sure that the certificate you are trusting is the one from your company, as the desktop won't ask again and trusting an insecure certificate might bring some risk.

**Comment by qupfer** [comment]
Yeah, thats the behavior i would expect. But its not working. 
I have this mesage:
![1](https://user-images.githubusercontent.com/2614431/127548705-925813a7-9f1f-4e16-9040-b3f24077ee95.png)
Clicking on details and Trust. 
![2](https://user-images.githubusercontent.com/2614431/127549189-87a988cf-64e4-4651-9e6f-3261fc93dc28.png)
Works one time, but after restarting mattermost, the same error mesages appear again.
If I look in ~./.config/Mattermost/certifiacte.json, I see the mattermost.company.com certifiacte but not the company-ca.
I tried to add it manually to the json, but this was overwritten after next start.

**Comment by devinbinnie** [comment]
@qupfer Does this reproduce with the latest version available from Snap? The version on Snap was outdated until recently. It should now be v5.0.2
