### ISSUE TITLE
All URL open as mailto: can't change it

### ISSUE THREAD

**Issue by Transisto** [mattermost/desktop#1679]
I managed to have every link in my mattermost desktop to open as mailto:http://...
Anyone has a clue on how to fix this beside re-installing?

**Comment by Willyfrog** [comment]
Is it possible that your OS settings are to open http/s links with your mail client?

**Comment by Transisto** [comment]
No, this happens only on mattermost
I will try reinstalling it

**Comment by Willyfrog** [comment]
do you have the autolinker enabled with any kind of rule that might trigger this?

**Comment by Transisto** [comment]
I don't know what that i, I just remember having been asked once to chose
how to open an Url, I chose chrome and it's been opening as mailto into
chrome bar ever since. Btw I don't use any app associated with mailto.

**Comment by Willyfrog** [comment]
sorry for the delay in answering, as I was away for a few days.

seems like a missconfiguration in the OS? you might want to check the default app to open with each option.

**Comment by devinbinnie** [comment]
Closing as inactive, this is likely caused by an internal OS issue.
Feel free to re-open if this is still happening.
