### ISSUE TITLE
Cannot switch to Dark Mode on Windows

### ISSUE THREAD

**Issue by MichalVasut** [mattermost/desktop#1685]
Just installed MatterMost Desktop Client 4.7.1 on Win10 and yes there is new feature / "improvement"

- Windows desktop now automatically switches between light and dark themes based on the operating system settings.
- src: https://docs.mattermost.com/install/desktop-app-changelog.html#windows

but it's rather annoying with dark theme to have light header / top bar of the window.

There is an option for macOS:
- https://docs.mattermost.com/messaging/managing-desktop-app-options.html#dark-theme
- On macOS, the Mattermost desktop app respects the System Preferences appearance setting of the operating system to set the theme of the title bar. On Windows, you can toggle the theme of the Mattermost desktop app title bar in … > View > Toggle Dark Mode.

![image](https://user-images.githubusercontent.com/20949562/128471495-211273d8-c9ad-42dc-8a09-fb418bc00c59.png)

No **Dark Mode** here...

Could you add it also for Windows? Thanks.

**Comment by JtheBAB** [comment]
The only fix is that you turn on the Dark Mode on Windows itself. Then the top bar will be also dark. The docs are outdated but the doc fix is in review.

**Comment by MichalVasut** [comment]
This is very bad decision to force users to change system settings just to fit single application needs. ... Reverted client back to 4.6.2 where it was OK.

**Comment by JtheBAB** [comment]
It is consistent to the mac world ¯\_(ツ)_/¯

**Comment by OwlProjects** [comment]
There is also one unpleasant effect in this mattermost version. When this state installed
![2021-09-09 16_54_12-Window](https://user-images.githubusercontent.com/90596392/133030717-82c477f2-79b5-4e73-acf1-0fd19531adae.png)
there is this state in system tray
![1](https://user-images.githubusercontent.com/90596392/133032529-482c153b-4a5f-4a72-9fb1-ec608c83ab53.png)
![2](https://user-images.githubusercontent.com/90596392/133032542-1d81afae-99c1-4309-b205-df2a4435cea9.png)
Black icon on black tray background look not so good

**Comment by devinbinnie** [comment]
Closing as we have made the decision to synchronize our Desktop App with the OS's dark mode setting where available.
We have another issue open for the tray icon here: https://github.com/mattermost/desktop/issues/1601
