### ISSUE TITLE
if server coms only via GPO "Add Server" appears on each startup

### ISSUE THREAD

**Issue by neeral85** [mattermost/desktop#1686]
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
If users do not have configured any server there is a popup of Desktop Settings/Add Server on each start of the client.

![grafik](https://user-images.githubusercontent.com/42938711/128479444-5ada12ae-29b7-4686-ba22-35a894cf4935.png)

This popup appears even if server configuration is deploy via GPO (Computer setting). If closed without any changes clients works perfect with GPO provided server. But on next start same behavior again.

**Steps to reproduce**

Please include all of the following:
- Operating System: Windows 10 21H2
- Mattermost Desktop App version: 4.7.1
- Mattermost Server version: NA

GPO (Computer): 
EnableServerManagement: Enabled
DefaultServerList: one valid server in list

Client is installed with no additional configuration and just started.

**Expected behavior**
if server settings are provided via GPO client should start without popup for settings (as it would do if user has configured a server)
**Observed behavior**
popup "Add Server" appears on any start of the application

**Possible fixes**
check if server may provided via GPO (Computer/User), if so, do not open "Add Server" window.

---

[JIRA tickets](https://mattermost.atlassian.net/browse/MM-14183?jql=labels%20%3D%20desktop) are created for all valid bug reports filed here. Bugs and features that the Mattermost core team are not immediately working on are opened as [Help Wanted GitHub issues](https://developers.mattermost.com/contribute/getting-started/contribution-checklist/) and welcome to contributions. 

Our goal is to bring the Mattermost desktop repository into our day-to-day internal process with the hope of having more frequent desktop releases with faster feature development and turnaround time on bug fixes.

**Comment by amyblais** [comment]
Opened a ticket: https://mattermost.atlassian.net/browse/MM-37863

**Comment by amyblais** [comment]
This is fixed in v4.7.2,
