### ISSUE TITLE
Windows Desktop App: Minimize to tray setting disappeared (since 4.7.0)

### ISSUE THREAD

**Issue by mreymann** [mattermost/desktop#1687]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: Windows 10 Pro (Build 19043.1151)
- Mattermost Desktop App version: 4.7.1 
- Mattermost Server version: 5.36.1 on linux 

**Steps to reproduce**
Update to Mattermost version 4.7.0 (or directly to 4.7.1?) from a previous 4.6.x version.

**Expected behavior**
"Minimize to tray" entry should show in the app settings. When enabled, app should minimize to systray when minimizing app window or when clicking the Mattermost entry in the task bar.

**Observed behavior**
"Minimize to tray" entry does not show in the app settings. App only mimimizes to systray when closing the app window.
The setting is still present in config.json but not in the Settings window:

```
  "showTrayIcon": true,
  "trayIconTheme": "light",
  "minimizeToTray": true,
```
![2021-08-04 09_56_34-Mattermost Desktop Settings](https://user-images.githubusercontent.com/31735558/128675868-b2bfa28a-22d8-4945-9638-c20fd6f9f9de.png)

**Possible fixes**
Currenty unknown.

**Comment by mreymann** [comment]
I've just updated to 4.7.2 but the minimize to tray option is still not present. Is there any way to get this feature back?

**Comment by amyblais** [comment]
I asked and a dev mentioned that it was intentionally removed, but we have a ticket to add it back in the future in a different form.

**Comment by devinbinnie** [comment]
Created a JIRA ticket: https://mattermost.atlassian.net/browse/MM-40572

**Comment by mreymann** [comment]
I'm on version 5.0.4 now but the issue remains. 
I've enabled "Leave app running in notification area when application window is closed" an restarted the app.
When minimizing the app window, Mattermost still shows up both in the systray AND in the task bar!
The older behaviour was to show ONLY the systray icon when the app window was minimized.

**Comment by devinbinnie** [comment]
@mreymann The setting only applies to when you close the window, the `minimizeToTray` naming in the background is a bit misleading, sorry for the confusion.

What the setting does is make sure the app stays open when you close the window, instead of outright closing the entire application.

**Comment by mreymann** [comment]
Is there a chance to get the original feature back?

**Comment by devinbinnie** [comment]
@mreymann I don't think we have any plans to do that, sorry for the inconvenience.

**Comment by mreymann** [comment]
That's too bad. The way it is now, the useless Mattermost item in the taskbar just adds to the clutter ... :-(
