### ISSUE TITLE
Win7/Desktop 1.2.1 - Propose pinned Start Menu option just says "Mattermost"

### ISSUE THREAD

**Issue by it33** [mattermost/desktop#169]
Repro: 

On Win7 install Mattermost Desktop 1.2.1 and right click on mattermost.exe and select "Pin to Start Menu" 

Observed: 

Text in Start Menu reads "Mattermost Desktop application for Windows, Mac and Linux". But the Mac and Linux references may be confusing to Windows users. 

![image](https://cloud.githubusercontent.com/assets/177788/16195921/89da180a-36b0-11e6-8862-3fe461f110fc.png)

Expected: 

"Mattermost" // to be consistent with naming of other Windows applications, proposing we just use the name of the system.

**Comment by jasonblais** [comment]
Would anyone from the community be open to helping with a PR to address this?
