### ISSUE TITLE
Incorrect Notification Bubble

### ISSUE THREAD

**Issue by kcpearce** [mattermost/desktop#1690]
#### Summary
The red notification bubble appears in the windows taskbar if I am in a channel whose name starts with a "*" character

#### Steps to reproduce
1. Create a channel that starts with a "*" character, e.g. "*Urgent Issues*"
2. Click on that channel
3. Red notification bubble appears regardless of whether there are new messages or not

#### Expected behavior
My team has a few specific channels that contain urgent/important information. In order to keep those at the top of our channel list when alphabetically sorted, we've added asterisks to the channel name, e.g. "*Urgent Issues*", "*Urgent Sales Request*", etc.

#### Observed behavior (that appears unintentional) 
Even if there are no unread/new messages, if I am in one of the channels with a "*" name, the red notification bubble appears in the windows taskbar. 

#### Possible fixes
N/A

**Comment by amyblais** [comment]
@kcpearce I wasn't able to reproduce just now, wondering if you'd be able to upgrade to a more recent server version to see if you can still reproduce it? You can also optionally do some testing on our [community server here](https://community.mattermost.com/), which is on the latest version. You should have access to create a Private channel there, but let me know if you don't.

**Comment by devinbinnie** [comment]
Need to fix the regex for the Desktop App to make sure a space exists. Nice find!
