### ISSUE TITLE
Tray icon does not depend on tray color on Windows

### ISSUE THREAD

**Issue by liefke** [mattermost/desktop#1694]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

Tray icon does not depend on tray color but on app color on Windows

**Steps to reproduce**

- Open the color settings in Windows
- In "Choose your color" choose "custom"
- In "Choose your default Windows mode" choose "Dark" or "Light"
- In "Choose your default app mode" choose the opposite

Example: ![Color settings](https://i.ytimg.com/vi/bgGdjlxwPk0/maxresdefault.jpg)

Environment:
- Operating System: Windows 10 20H2 Built 19042.1110
- Mattermost Desktop App version: 4.7.1
- Mattermost Server version: 5.36.1

**Expected behavior**

- The color of the icon in the tray depends on the "Windows mode", it becomes white if the "Windows Mode" is "Dark" and it becomes black if the "Windows mode" is "Light".

**Observed behavior**

The icon in the tray depends on the "Default app mode".

It becomes black, even if the tray is dark: 
![image](https://user-images.githubusercontent.com/9518325/128985524-d70542b1-4052-43c5-8184-3768368e0629.png)

And it becomes white even if the tray is light:
![image](https://user-images.githubusercontent.com/9518325/128985596-0dd132a1-d16b-45ff-8c1c-ffea1dd74565.png)

A workaround could be to change the `trayIconTheme` in `%APPDATA%\Mattermost\config.json` as needed, but this has currently no effect on Windows.

**Possible fixes**

Respect `trayIconTheme` in `tray.ts` even for Windows and initialize with `default`, which falls back to the native theme.

---

[JIRA tickets](https://mattermost.atlassian.net/browse/MM-14183?jql=labels%20%3D%20desktop) are created for all valid bug reports filed here. Bugs and features that the Mattermost core team are not immediately working on are opened as [Help Wanted GitHub issues](https://developers.mattermost.com/contribute/getting-started/contribution-checklist/) and welcome to contributions. 

Our goal is to bring the Mattermost desktop repository into our day-to-day internal process with the hope of having more frequent desktop releases with faster feature development and turnaround time on bug fixes.

**Comment by Willyfrog** [comment]
Hi there, and thanks for reporting, it is a [known issue](https://mattermost.atlassian.net/browse/MM-36058) and we are waiting on a fix from upstream.
