### ISSUE TITLE
Future process for prioritizing issues in the desktop project

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#171]
Huge thanks to all the community contributors of the desktop app, @yuya-oc, @Razzeee, @MetalCar, @mid0111, @jnugh, @mgielda, @alerque, @CarmDam, @pascalw, @jeremycook as well as everyone who have filed new issues to the repository. The desktop client is used by numerous end users for their daily work and it's fantastic to have the community working on this incredible project.

As more people use the desktop app, more feature ideas, improvements and issues arise; @yuya-oc and I have a proposal to upgrade the current process to discuss, prioritize and accept community contributions to the desktop project. This is a continuation of our [plan for future build, documentation and download locations](https://github.com/mattermost/desktop/issues/137) and is [shared with community](https://docs.google.com/document/d/19cyP_phXzPQikB3WBKTzX-1A0PHpVUGhTDUIau1lY9w/edit#bookmark=kix.bmy6h0mu75ew) to have it transparent and to give everyone an opportunity to share feedback. The new process will be rolled out in the next few days.

If you haven't yet, I invite you to join our [Desktop App](https://pre-release.mattermost.com/core/channels/desktop-app) channel, which will be used for the community to discuss and prioritize issues and new features. 

We will also be creating a page for the "Most Valued Professional" of the desktop project to award an outstanding contributor for a Mattermost Desktop release. You may see awards already given to [community contributors of Mattermost releases](http://www.mattermost.org/mvp/).

Again, big thank you to everyone for shaping the future of the Mattermost Desktop project. I'm quite excited to work with all of you

**Comment by Razzeee** [comment]
Any news on code signing / jenkins builds?

**Comment by jasonblais** [comment]
@Razzeee It is in progress and planned for Mattermost v3.2 (which is released July 16). You can follow  these tickets to track their progress in the Mattermost Jira instance
 - [PLT-3146](https://mattermost.atlassian.net/browse/PLT-3146)
 - [PLT-3348](https://mattermost.atlassian.net/browse/PLT-3348)
 - [PLT-3354](https://mattermost.atlassian.net/browse/PLT-3354)
 - [PLT-3356](https://mattermost.atlassian.net/browse/PLT-3356)

(the first two have been completed and closed)

**Comment by jasonblais** [comment]
Thanks for noticing the typo ;)

**Comment by jasonblais** [comment]
Closing the task with a new project plan for v1.4/3.4 posted in #207
