### ISSUE TITLE
Switching channels results in rendering flicker on Linux

### ISSUE THREAD

**Issue by rpglover64** [mattermost/desktop#172]
* OS: Linux using i3 as the window manager
* MM desktop version: 1.2.1

See #118 

When switching channels, even to the same channel, the entire screen blanks and re-renders twice.

**Comment by yuya-oc** [comment]
Not reproduced on Ubuntu 14.04 64bit / Unity.

- Does [the latest master](https://circleci.com/gh/mattermost/desktop/420#artifacts) solve that?
- Is that reproduced in Chrome/Chromium?

**Comment by rpglover64** [comment]
Still present on latest master. Something similar (but not clearly identical) occurs in Firefox. The issue is present in Vivaldi (which is chromium-based).

@leafac can say more about the server configuration (version 2.2.0, IIRC).

**Comment by leafac** [comment]
The issue happens in all major OS, on the desktop client.

The current Mattermost version is:

```
Current version is 2.2.0 (6671/Fri Apr 15 18:40:19 UTC 2016/8e883ad2f516820942cc0131241268c1ea909ff3)
```

The Mattermost service is running behind a reverse proxy provided by Apache. Here are the relevant configurations:

```apache
<VirtualHost *:443>
    ServerAdmin [...]
    ServerName [...]

    AddType text/html .shtml
    AddOutputFilter INCLUDES .shtml

    DocumentRoot /home/mattermost/mattermost/web

    <Directory />
        Options FollowSymLinks
        Require all denied
    </Directory>
    <Directory /var/www/>
        Options -Indexes +FollowSymLinks -MultiViews +ExecCGI +Includes
        AllowOverride All
        Require all granted
    </Directory>

    SSLEngine on

    ProxyPreserveHost On

    RewriteEngine On

    RewriteCond %{REQUEST_URI}  ^/api/v1/websocket    [NC,OR]
    RewriteCond %{HTTP:UPGRADE} ^WebSocket$           [NC,OR]
    RewriteCond %{HTTP:CONNECTION} ^Upgrade$          [NC]
    RewriteRule .* ws://127.0.0.1:8065%{REQUEST_URI}  [P,QSA,L]

    RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_FILENAME} !-f
    RewriteRule .* http://127.0.0.1:8065%{REQUEST_URI} [P,QSA,L]
    RequestHeader set X-Forwarded-Proto "https"

    <Location /api/v1/websocket>
        Require all granted
        ProxyPassReverse ws://127.0.0.1:[...]/api/vi/websocket
        ProxyPassReverseCookieDomain 127.0.0.1 [...]
    </Location>

    <Location />
        Require all granted
        ProxyPassReverse http://127.0.0.1:[...]/
        ProxyPassReverseCookieDomain 127.0.0.1 [...]
    </Location>

    SSLEngine on

    SSLCertificateFile [...]
    SSLCertificateKeyFile [...]
    SSLCertificateChainFile [...]

    <FilesMatch "\.(cgi|shtml|phtml|php)$">
        SSLOptions +StdEnvVars
    </FilesMatch>
    <Directory /usr/lib/cgi-bin>
        SSLOptions +StdEnvVars
    </Directory>
    BrowserMatch "MSIE [2-6]" \
        nokeepalive ssl-unclean-shutdown \
        downgrade-1.0 force-response-1.0
    BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown
</VirtualHost>
<VirtualHost *:80>
    [Same as 443 configuration]
</VirtualHost>
```

**Comment by yuya-oc** [comment]
The desktop app is also chromium-based, it behaves like a tab browser. So it might be server-side issue if the problem happens on web browsers.

Unfortunately I'm not familiar at Apache configuration. How about trying without reverse proxy or asking at forum?

**Comment by leafac** [comment]
I'm going to do that. Then I come back here and tell you how it went. Thanks for the help.

**Comment by leafac** [comment]
Upgrading to Mattermost 3.1.0 solved the issue.

Thanks a lot for your time.

@rpglover64: you can close the issue, now.
