### ISSUE TITLE
Channel list jumble with multi teams on same server

### ISSUE THREAD

**Issue by nItroFreeZer** [mattermost/desktop#173]
Hi,

there is a problem with the channel list. When I switch to the second or third team tab, some channels of the first team appears in the channel list of the second or third team.
Clicking on one of the channels triggers a refresh of the channel list and shows the correct channel list.

When I start the desktop app and there are new messages in the first team, all team tabs are marked as 'new messages available'.

OS: OS X
Mattermost desktop app: 1.2.1, 1.2.0
Mattermost server: 3.1

**Comment by yuya-oc** [comment]
Does it happen on web browser? Please open the teams with multi tabs.
If it happens, it seems the issue of mattermost server.

**Comment by nItroFreeZer** [comment]
No, it happens not in browser and not in iOS app.

**Comment by yuya-oc** [comment]
Reproduced in Chrome. Could you consider to report at /platform repo?

1. Create two teams, T1 and T2 on same server.
2. Create two accounts, A and B for both of teams.
3. Login as A in desktop app.
4. Login as B in Chrome, and open tabs for each team.
5. Create a new channel in T1.
6. Post to the channel as A in desktop app.
7. The channel appears on B's T2 tab.

Mattermost server 3.1

**Comment by jasonblais** [comment]
Thanks @nItroFreeZer for the report,

There is indeed a [pull request submitted to the /platform repo](https://github.com/mattermost/platform/pull/3329), which will fix the issue for Mattermost v3.2
