### ISSUE TITLE
Improve fullscreen handling

### ISSUE THREAD

**Issue by tnixeu** [mattermost/desktop#1731]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

I accidentally enabled fullscreen and did not think of trying to toggle it. 

**Environment**
- Operating System: Windows 10
- Mattermost Desktop App version: 4.71 and 4.7.2-rc3
- Mattermost Server version:  5.37.1

**Steps to reproduce**

* Enable fullscreen
* Forget about having enabled fullscreen
* Try moving window by using the title bar

**Expected behavior**

Have some indication that Mattermost is in fullscreen mode.

**Observed behavior**

There is no indication that the fullscreen mode is enabled, besides filling the full screen but also having a title bar. Not even a restart of the App or PC helped. I did not know that Mattermost now stays if fullscreen even when the App is restarted. Seems quite new:  #1546

**Possible fixes**

Add some indication that Mattermost is in fullscreen mode would be helpful:

* Hide window icons or allow the maximizing button to disable fullscreen mode
* Allow dragging the title bar to disable fullscreen
* Add check mark to "Toggle Full Screen F11" in menu
* Show toast notification on startup that fullscreen is enabled
* Add setting to enable restarting with fullscreen enabled. This would allow people to know about this feature.

**Comment by devinbinnie** [comment]
@esethna @matthewbirtch Thoughts?

**Comment by devinbinnie** [comment]
Closing as I think the full screen case in Windows works well enough, we've done some changes to resizing that should make sure the experience works well.
