### ISSUE TITLE
Show countdown for automatic refresh 

### ISSUE THREAD

**Issue by Razzeee** [mattermost/desktop#174]
When the app can't find a server we're now refreshing each 30 sec. #127
Make this transparent, by showing the countdown and maybe also give a link to refresh now.

**Comment by jasonblais** [comment]
Thanks @Razzeee for your suggestion.

Could we have your help contributing your suggestion in the [feature idea forum](https://mattermost.uservoice.com/forums/306457-general) so it can be discussed, upvoted and considered for a ticket accepting pull requests?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review.

You get 10 votes in the feature idea forum, and each one influences the future of the project.

**Comment by jasonblais** [comment]
Closing for now -- please post in the feature idea forums if you'd like the issue to be considered.
