### ISSUE TITLE
Mattermost desktop open the wrong web browser

### ISSUE THREAD

**Issue by florencebiree** [mattermost/desktop#1741]
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Mattermost desktop open the wrong (not default) web browser

**Environment**
- Operating System: Linux, Debian Sid / Desktop environment : sway/wayland
- Mattermost Desktop App version: 4.7.1 
- Mattermost Server version: 5.39.0 

**Steps to reproduce**
Click on a link, to open a web page

**Expected behavior**
The web page is opened in Firefox, my default web browser

**Observed behavior**
The web page is opened in Chromium, another web browser installed on my machine.

Maybe it's due to my use of an uncommon desktop (sway). But other software open the right web browser, like my email client (claws). I've some pieces of an Xfce 4 desktop, like the setting apps allowing to set a default browser, and Firefox is defined here as a default browser.

**Comment by Willyfrog** [comment]
I'm afraid there must be something configured in your desktop that is defaulting to Chrome instead of Firefox. We don't choose any browser as each user has its own preferences, to open an URL we call [shell.openexternalurl](https://www.electronjs.org/docs/latest/api/shell/#shellopenexternalurl-options) which tries to use whatever the environment has defined.

I'm closing the issue as there is not much we can do on that, but feel free to reopen if you think we can help somehow.

**Comment by florencebiree** [comment]
I understand, but it's the only application on my system which open the wrong web browser. Even signal-desktop (another electron application) open the right one…

**Comment by mattcasters** [comment]
This is still an issue for me on Linux and I google-ing I found folks who apparently had it on Windows as well. (version 5.1.1, commit 7eef060)

**Comment by Finnlife** [comment]
https://github.com/electron/electron/issues/42611

**Comment by lechten** [comment]
That was a bug in Electron, see there, also for a workaround: https://github.com/electron/electron/issues/45129
