### ISSUE TITLE
PLEASE: Write the current selected Channel / Group / Direct Message Name into the Window Caption

### ISSUE THREAD

**Issue by derdast** [mattermost/desktop#175]
PLEASE
As a user of Manic Time it would be more then useful for me to summarize the time I spend with different conversations, at imho this would do the trick so nicely.

Using Mattermost with a browser changes the title - I just like the app

---

When you have a trouble, please write below.
- Operationg system                                                       Windows 64bit
- Mattermost desktop app version                                  v1.1.1
- Mattermost server version                                           v3.x
- How to reproduce the trouble                                      obviious

**Comment by jasonblais** [comment]
Thanks @derdast, appreciate your feedback.

Could we have your help contributing your suggestion in the [feature idea forum](https://mattermost.uservoice.com/forums/306457-general) so it can be discussed, upvoted and considered for a ticket accepting pull requests?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review.

You get 10 votes in the feature idea forum, and each one influences the future of the project.

**Comment by derdast** [comment]
Done.
https://mattermost.uservoice.com/forums/306457-general/suggestions/14974134-windows-mattermost-client-make-us-of-the-window-c

**Comment by jasonblais** [comment]
Perfect, thanks @derdast!
