### ISSUE TITLE
Feature request: Unread messages badge counter

### ISSUE THREAD

**Issue by jnugh** [mattermost/desktop#176]
This was part of #88.
It would be nice to have a unread message counter badge in the unity dock.

This depends on https://github.com/electron/electron/issues/4193 and should be easy to implement after the feature has been implemented in electron.

**Comment by jasonblais** [comment]
Thanks @jnugh! I've added this to v1.4/3.3 as you signalled interest to add it in

We'll have a set of notification improvements queued for Windows and OSX for v1.4/3.3, so we're fine to take this in too

**Comment by yuya-oc** [comment]
Should be closed by #199
