### ISSUE TITLE
Below File > About Mattermost, add a help page that redirects to docs.mattermost.com

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#177]
Currently, there is no way to look for help while working on the Mattermost Desktop app.

**UPDATED SPECIFICATION:**

For the `Help`context menu item, propose adding a new line item `Docs Help`, which redirects to [http://docs.mattermost.com/](http://docs.mattermost.com/).

It should be located above the grayed out version number as follows:

 - `Docs Help`

 ----- Section Break

 - `Version Number` (grayed out)

**Comment by jasonblais** [comment]
Would anyone from the community be open to helping with a PR to address this?

**Comment by Razzeee** [comment]
I'm not sure about your specifications, as Mattermost 1.3.0 has an help menu and doesn't/we shouldn't use the file menu for that stuff. (Well OS X does in parts)

This is what I how I would do it for windows:
![unbenannt](https://cloud.githubusercontent.com/assets/5943908/16387534/8536d44c-3c95-11e6-9f97-8ab897205ddd.png)

**Comment by Razzeee** [comment]
Also "About Mattermost" is only used/available for darwin, as it seems pretty useless right now. It doesn't adds anything valuable to the app. As the version info is now shown under help and there is not anything else in that popup.

**Comment by jasonblais** [comment]
@Razzeee, thanks! I had an older version of the desktop running, I've updated the issue accordingly.

Would you still be interested in submitting a pull request for it?

**Comment by Razzeee** [comment]
Your sure about ```Docs Help```
Feels redundant, how about ```Documentation```
