### ISSUE TITLE
Closing/Quitting Mattermost desktop should minimize it to the system tray (i.e. notification area)

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#178]
Closing/Quitting Mattermost desktop should minimize it to the system tray (i.e. notification area).

Currently, closing/quitting Mattermost desktop simply minimizes the application to the taskbar.

**Comment by jasonblais** [comment]
Would anyone from the community be open to helping with a PR to address this?

**Comment by jasonblais** [comment]
In progress for Windows by @magicmonty ([#179]https://github.com/mattermost/desktop/pull/179)

Any takers for OS X or Linux?

**Comment by jasonblais** [comment]
Thanks @magicmonty!

**Comment by magicmonty** [comment]
The hide on close for OSX is now part of PR #179

**Comment by yuya-oc** [comment]
It's done for Windows and OS X at #179.

**Comment by jasonblais** [comment]
Huge thanks again @magicmonty!! I'll mark this for `Linux` and remove from v1.3 for now

**Comment by jasonblais** [comment]
Closing the issue as done
