### ISSUE TITLE
Build system issue: macOS Universal Binary build is huge, contains unnecessary files

### ISSUE THREAD

**Issue by Westacular** [mattermost/desktop#1783]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

The newly-added [universal binary download for 5.0.0-rc2](https://releases.mattermost.com/desktop/5.0.0-rc2/mattermost-desktop-5.0.0-rc2-mac-universal.dmg) is 542 MB, but the two individual architecture-specific builds are only ~96 MB each.

Comparing the app bundles reveals that most of the difference is in `Resources/app.asar`: in the non-universal builds, it's 44 MB; in the universal build, it's 419 MB.

Listing the contents of `app.asar` shows that in the universal build, it includes

```
/macos-release
/macos-release/builder-debug.yml
/macos-release/mattermost-desktop-5.0.0-rc2-mac-arm64.dmg
/macos-release/mattermost-desktop-5.0.0-rc2-mac-arm64.dmg.blockmap
/macos-release/mattermost-desktop-5.0.0-rc2-mac-arm64.zip
/macos-release/mattermost-desktop-5.0.0-rc2-mac-x64.dmg
/macos-release/mattermost-desktop-5.0.0-rc2-mac-x64.dmg.blockmap
/macos-release/mattermost-desktop-5.0.0-rc2-mac-x64.zip
/macos-release/rc2-mac.yml
```

i.e., multiple full versions of both the Intel and Apple Silicon builds are accidentally being archived inside the universal build's assets.

I suspect there's some config missing that's needed to tell the packager to ignore the `macos-release` folder when building the universal version

**Comment by devinbinnie** [comment]
Thanks @Westacular, created a ticket for it in JIRA: https://mattermost.atlassian.net/browse/MM-39047
