### ISSUE TITLE
Show validation errors in the settings

### ISSUE THREAD

**Issue by Razzeee** [mattermost/desktop#181]
If you try to create a team and give it an invalid url, the app blocks you from doing it.
It might be nice to show the user what's going on by some kind of error handling.

Maybe like done in this example http://getbootstrap.com/components/#glyphicons-examples

**Comment by jasonblais** [comment]
Would this be an easy update? It would be quite nice particularly with new user on-boarding as it's currently against [Mattermost UX guidelines > Error Messages](https://docs.mattermost.com/developer/fx-guidelines.html#input-hints)
.

Following the behaviour elsewhere on Mattermost, the user would be allowed to click on the `Add` button, but an error message would be shown below the input field:
 - if `Name` is not set: `Name is a required field.`
 - if only `URL` is not set: `URL is a required field.` 

![image](https://cloud.githubusercontent.com/assets/13119842/17835654/80c0dfaa-6744-11e6-82fc-23ea03320837.png)


We should probably also enforce `http://` and `https://` as required for the URL, but that's a separate issue from this.

**Comment by yuya-oc** [comment]
I'm not sure. Probably we have to use `react-bootstrap` now, but we need to migrate to latest version in order to refer to documents because it looks still unstable.
If I could, I would like to consider this, including refactoring. It might be better not to use `react-bootstrap` now.

**Comment by jasonblais** [comment]
@yuya-oc By next version, do you mean after v1.4?

If it involves significant refactoring, I would agree. It would be better to work on it early for v1.5 in that case.

**Comment by yuya-oc** [comment]
Ah, sure. That should be done after v1.4. Then I tried adding a simple one at 255ff9a.

<img width="551" alt="blank_name" src="https://cloud.githubusercontent.com/assets/1412057/17855363/5c217a54-68b3-11e6-85ff-58004e8ca697.png">
<img width="549" alt="blank_url" src="https://cloud.githubusercontent.com/assets/1412057/17855366/5c29aa08-68b3-11e6-834c-79341ed70b31.png">
<img width="550" alt="invalid_url" src="https://cloud.githubusercontent.com/assets/1412057/17855364/5c281472-68b3-11e6-93d6-534ce5274387.png">

**Comment by jasonblais** [comment]
Awesome, many thanks @yuya-oc! 

I've queued it for a meeting to get the texts UX approved. Starting to get so excited for v1.4 with all the improvements :)

**Comment by jasonblais** [comment]
@yuya-oc Here's some feedback:

1. Change colour of the error validation texts to grey
2. Change texts to 
 - `Name is required.`
 - `URL is required.`
 - `URL should start with http:// or https://.`

The above two would make it more consistent with other similar error messages in Mattermost.

Otherwise looks great!

**Comment by yuya-oc** [comment]
@jasonblais Thanks for feedback. Please let me confirm, does "gray" mean `color: 'red'` of CSS? Or, is there the color value for "gray"?

**Comment by jasonblais** [comment]
Hmm, let me double check with @asaadmahmood, good question

**Comment by jasonblais** [comment]
Confirmed that using the [color #777](http://www.spycolor.com/777777) for gray would be fine.
