### ISSUE TITLE
Notification icon hardly visible

### ISSUE THREAD

**Issue by razzeee** [mattermost/desktop#1812]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Notification area icon is hardly visible

**Environment**
- Operating System: Fedora 34
- Mattermost Desktop App version: 5.0.0 
- Mattermost Server version: 5.37.1 

**Steps to reproduce**
- Start mattermost
- Look at your notification bar (you'll need the notification extension for gnome)

**Expected behavior**
It should be easier to see, like the other icons

**Observed behavior**
![image](https://user-images.githubusercontent.com/5943908/137308291-92ec6c79-30f5-4f5f-84df-295bcb69ca26.png)

**Possible fixes**

The previous behavior was better, not sure if that was a change in 5.0.0

**Comment by amyblais** [comment]
A ticket is open here: https://mattermost.atlassian.net/browse/MM-40145.

**Comment by razzeee** [comment]
That ticket is windows specific, this one is for linux.

**Comment by amyblais** [comment]
I'll add a note in the ticket.

**Comment by amyblais** [comment]
I opened a separate ticket for Linux: https://mattermost.atlassian.net/browse/MM-40149.

**Comment by devinbinnie** [comment]
This has already been solved, you going to the Settings page and manually change the icon colour from Light to Dark (or vice-versa) if the icon contrasts with the menu bar.

Closing.
