### ISSUE TITLE
Windows: Crashing when changing between Channels and Boards

### ISSUE THREAD

**Issue by s1gh** [mattermost/desktop#1825]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
When changing back and forth between Channels and Boards the desktop app sometimes crashes.

**Environment**
- Operating System: Windows 10 19042
- Mattermost Desktop App version: 5.0.0 
- Mattermost Server version: 6.0.0 

**Steps to reproduce**
Change back and forth between the two tabs "Channels" and "Boards".

**Expected behavior**
No crash. Channels and Boards loading as usual.

**Observed behavior**
Desktop app sometimes crashes with the following error message:
```
Application: Mattermost 5.0.0
Platform: Windows_NT 10.0.19042 x64
Error: EBUSY: resource busy or locked, open 'C:\Users\username\AppData\Roaming\Mattermost\config.json'
    at C:\Users\username\AppData\Local\Programs\mattermost-desktop\resources\app.asar\index.js:40992:19
    at fs.js:1504:7
    at FSReqCallback.oncomplete (fs.js:180:23)
```

**Possible fixes**
Not sure

**Comment by devinbinnie** [comment]
@s1gh So just to understand, if you have the Boards tab closed, and then re-open it by clicking a link (or by using the Global Header) and then while the loading screen is running you switch back to the Channels tab, and that causes a crash?

**Comment by devinbinnie** [comment]
Thanks for the info, create a ticket to track: https://mattermost.atlassian.net/browse/MM-39428
