### ISSUE TITLE
Minimise / Close buttons disappeared in v5.0.0 on Windows 8.1

### ISSUE THREAD

**Issue by acataluddi** [mattermost/desktop#1826]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Hi,
Since the installation of the client version `5.0.0`, I cannot close or minimise the desktop window anymore. The control buttons have disappeared:

![immagine](https://user-images.githubusercontent.com/8874358/137893279-eeb22498-5088-4590-ae2d-c39364dcd1cf.png)

The only temporary work-around is to use the <kdb>CTRL</kbd> + <kbd>W</kbd> which sometimes works and sometimes just **closes the client**.

**Environment**
- Operating System: Microsoft Windows 8.1 Professional x64
- Mattermost Desktop App version: 5.0.0
- Mattermost Server version: 6.0.0

**Steps to reproduce**

- Open the Windows App
- Enjoy the lack of control buttons.

**Expected behavior**

See control buttons on the header to mimimise (`_`) or close the window (`X`).

**Observed behavior**

**Possible fixes**

**Comment by devinbinnie** [comment]
Versions of Windows before v10 should be using the native window instead of the frameless one. I'll make a quick fix for this.

**Comment by ricab** [comment]
I have this issue but on Ubuntu 25.04 (though not in another machine with 22.04).
