### ISSUE TITLE
Running the app again does not raise the window from the tray icon

### ISSUE THREAD

**Issue by dkuzmenko-sunpower** [mattermost/desktop#1833]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

Running the app again does not raise the window from the tray icon

**Environment**
- Operating System: Arch Linux, KDE
- Mattermost Desktop App version: 5.0.0 
- Mattermost Server version: 5.39.0 

**Steps to reproduce**
1. Run the app either from shell or the app menu `mattermost-desktop`
2. Open settings and check both options:
    - "Show icon in the notification area"
    - "Leave app running in notification area when application window is closed".
3. Close the app window. Window is being minimized to tray.
4. Run the app again either from shell or the app menu `mattermost-desktop`

**Expected behavior**
Nothing is happening. The app window still be minimized to tray.

**Observed behavior**
Raise the app window as it was for mattermost-desktop prior to 5.0.0 release.

**Possible fixes**

P.S.: personally I'm using this to raise the app window by global hotkey. If there is another useful method to raise the window from tray with a hotkey, I will be okay with that.

**Comment by amyblais** [comment]
@devinbinnie Are we able to repro this / is there a ticket for this already?

**Comment by devinbinnie** [comment]
This is another issue that's a part of this ticket: https://mattermost.atlassian.net/browse/MM-30713
@dkuzmenko-sunpower Are you able to have this work if you uncheck "Leave app running in notification area when application window is closed"? I don't think that setting is doing what it's supposed to.

**Comment by srfall** [comment]
I have the same issue on windows 10 since I updated the desktop app to version 5

**Comment by devinbinnie** [comment]
Yes, I can reproduce that. Created a ticket: https://mattermost.atlassian.net/browse/MM-39843

**Comment by dkuzmenko-sunpower** [comment]
@devinbinnie the same behavior whenever the "Leave app running in notification area when application window is closed" checkbox checked or not. The application binary execution is not raising the running application window.
