### ISSUE TITLE
"Add a server" button doesn't work

### ISSUE THREAD

**Issue by KotoWhiskas** [mattermost/desktop#1834]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: Pop!_OS 21.04
- Mattermost Desktop App version: 5.0.0 
- Mattermost Server version: None 

**Steps to reproduce**
Try to add server
**Expected behavior**
Opens new window with a field where server should be added
**Observed behavior**
White window

![Screenshot from 2021-10-21 21-03-00](https://user-images.githubusercontent.com/61150040/138332410-a305b048-69b9-42f0-8532-98dc017bb26d.png)

![Screenshot from 2021-10-21 21-09-32](https://user-images.githubusercontent.com/61150040/138333369-f09bac5b-e1f4-4d54-938a-7883e068a676.png)
```
20:58:54.388 › Current working directory is /home/bike-station, changing into /opt/Mattermost
20:58:54.445 › config.autostart has been configured: true
20:58:54.446 › config.autostart has been configured: true
20:58:54.474 › preloading with /opt/Mattermost/resources/app.asar/modalPreload.js
20:58:54.491 › config.autostart has been configured: true
[28737:1021/205854.516948:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
mesa: for the --simplifycfg-sink-common option: may only occur zero or one times!
mesa: for the --global-isel-abort option: may only occur zero or one times!
mesa: for the --amdgpu-atomic-optimizations option: may only occur zero or one times!
20:59:19.039 › There is already a new server modal # if I click on "Add a server button"
20:59:20.638 › There is already a new server modal

```
EDIT:
When I click on "No servers configured", errors appear on developer tools console:

![Screenshot from 2021-10-21 22-42-34](https://user-images.githubusercontent.com/61150040/138346309-3ddda216-129f-4ebe-84d8-f52dde510531.png)

**Possible fixes**

**Comment by neufeind** [comment]
same problem here with the official 5.0.2-rpm, installed on Fedora 34. Works fine after switching to flatpak. Hmm, why does that fail with the rpm-package?
