### ISSUE TITLE
No screen sharing with Jitsi under both Linux & MacOS

### ISSUE THREAD

**Issue by alexander-potemkin** [mattermost/desktop#1850]
I confirm (by marking "x" in the [ ] below: [x]):

- [ x ] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [ x ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ x ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
If you try to start Jitsi conf. call with Jitsi extension under Mattermost - screen sharing doesn't work: Jitsi displays the window allowing to choose what to share, but it's all empty.
Same conference, same link - works just fine on any browser - Jitsi screen sharing works like a charm.

**Environment**
- Operating System:
- Mattermost Desktop App version: 5.0.1, but I'm pretty sure it was the same on previous latest version, as the issue is long lasting.
- Mattermost Server version: 6.0.2, pretty sure the same was with previous version.

**Steps to reproduce**
* install Jitsi plugin (https://github.com/mattermost/mattermost-plugin-jitsi)
* start new meeting
* try to screen share

**Expected behavior**
* screen sharing to work, like it is under the web browser

**Observed behavior**
* it doesn't... (screen permissions under MacOS X checked), even under Linux Mint 20.2 with no permissions restrictions. 

**Possible fixes**
Don't know - check why mattermost blocks screen sharing?

**Comment by devinbinnie** [comment]
I can reproduce this. Looks like Jitsi is expecting our Electron to support something it doesn't have. When I try to screenshare, this error appears in the console:
```
Logger.js:154 2021-11-03T14:23:26.928Z [features/desktop-picker] Called JitsiMeetElectron.obtainDesktopStreams but it is not defined
i @ Logger.js:154
(anonymous) @ functions.js:40
e.length.thumbnailSize @ functions.js:23
_updateSources @ DesktopPicker.js:408
functions.js:42 Uncaught (in promise) Error: Called JitsiMeetElectron.obtainDesktopStreams but it is not defined
    at functions.js:42
    at new Promise (<anonymous>)
    at e.length.thumbnailSize (functions.js:23)
    at VU._updateSources (DesktopPicker.js:408)
```

Currently, the embedded view for Jitsi in Mattermost is still experimental, so I'll create a ticket to address this at some point. For now, I'd recommend when using the Desktop App and Jitsi, if you need to screenshare, to open your Jitsi meeting in the browser until we can resolve this issue.

Ticket here: https://mattermost.atlassian.net/browse/MM-39854

**Comment by devinbinnie** [comment]
Closing as inactive. Happy to re-open if this is really bothering anyone still.
