### ISSUE TITLE
Kubuntu can't see add server dialog

### ISSUE THREAD

**Issue by livwvil** [mattermost/desktop#1853]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Add server dialog (modal window) does not appears, but if I resize window it does.
**Environment**
- Operating System: Kubuntu 20.04
- Mattermost Desktop App version: 5.0.1

**Steps to reproduce**
Just download latest version from official site as tar.gz, unpack and run mattermost-desktop (the same story with .deb package), then try to add server.
**Expected behavior**
Button "add server" should open dialog with prompting the server link.
**Observed behavior**
I decided that button do nothing, but later I clicked maximize button and modal window appears. Another problem is that modal window not filled all available space, like document body were not notified about window size changed. Manual changing of window size fix all problems.
![Screenshot_20211105_034411](https://user-images.githubusercontent.com/53614453/140439765-138b57c6-b26a-4901-b4fb-aca2eaa25a64.png)

**Comment by Margrie** [comment]
I have the same problem

- Ubutunu 20.04 
- Mattermost Desktop App version: 5.0.1

**Comment by nhp** [comment]
Same problem resides with 

- ubuntu 20.04
- Mattermost Desktop 5.0.2

Same workaround is still possible: resize the main window and it direclty works.

**Comment by amyblais** [comment]
cc @devinbinnie if we're able to test this.

**Comment by devinbinnie** [comment]
I've tested and can't reproduce it myself on Ubuntu 20.04 and v5.0.1
@nhp @Margrie @livwvil Can you reproduce this consistently? If so can you tell me what kind of hardware you're running? (CPU and RAM)

**Comment by livwvil** [comment]
Laptop (1600x900, Intel Core i7 4700MQ, 4x2.4 GHz, RAM 8 GB, SSD, GeForce GTX 850M)
Nothing else. I just installed it, launched, and try to connect to my job server, but dialog doesn't appeared after button was clicked. Then I resized the window and dialog appeared.
Now I have another laptop. I'll install kubuntu and try clean installation of mattermost.

**Comment by devinbinnie** [comment]
> Laptop (1600x900, Intel Core i7 4700MQ, 4x2.4 GHz, RAM 8 GB, SSD, GeForce GTX 850M) Nothing else. I just installed it, launched, and try to connect to my job server, but dialog doesn't appeared after button was clicked. Then I resized the window and dialog appeared. Now I have another laptop. I'll install kubuntu and try clean installation of mattermost.
> 
> So, now it works. I believe there is some problem with markup. Previous laptop has uncommon screen resolution. And this laptop screen is 2560x1600. But when I resize window, there is a little white background line, it was not before resizing. ![image](https://user-images.githubusercontent.com/53614453/142069232-225fedcb-796c-428a-b5f9-49610a12c7c6.png)

@livwvil I don't think there's a markup issue, I just tested the same thing with your screen resolution and everything worked fine. I'm using a VM with a 4-core processor as well. I'm wondering if something strange is happening with the timing of the application showing the modal, where it tries to show it but fails, yet the app still thinks it's there.

**Comment by devinbinnie** [comment]
@livwvil Can I get you to try one of these builds on the affected machine? I'd like to see if this fixes your issue:
https://15075-43964563-gh.circle-artifacts.com/0/tmp/artifacts/mattermost-desktop-5.0.0-develop-linux-ia32.tar.gz
https://15075-43964563-gh.circle-artifacts.com/0/tmp/artifacts/mattermost-desktop-5.0.0-develop-linux-x64.tar.gz

**Comment by livwvil** [comment]
@devinbinnie Unfortunately, I have not my first laptop any more, and I can't help you with my initial problem reproducing. But on my second laptop I still can break modal window. Here are three screenshots:
1. Open modal - everything is OK.
2. Resize window from the bottom -  a white stripe appears at the bottom.
3. Resize the window from the left - a big white column appears on the right.
I do not push the mouse button, it's free. If I close modal and open it again goto 1.
![1](https://user-images.githubusercontent.com/53614453/142229771-bf220560-2724-4c0e-ab43-7e1d76424d9b.png)
![2](https://user-images.githubusercontent.com/53614453/142229793-874123e7-4bf2-430d-952f-eb49da9f544f.png)
![3](https://user-images.githubusercontent.com/53614453/142229801-1dd3f420-fe37-4a5a-8503-ef836db59ae5.png)

**Comment by devinbinnie** [comment]
@livwvil Thanks for checking, I'm not sure why the resizing still isn't working, it's working correctly for me.

@Margrie @nhp Would you be willing to try the above linked builds?

**Comment by livwvil** [comment]
@devinbinnie maybe it's because of the system drivers. I don't know. I have only clean kubuntu-20.04.3-desktop-amd64 installation and your build unpacked.

**Comment by devinbinnie** [comment]
I can reproduce sporadically, the app must not be waiting for the window to exist at some points.
Created a ticket: https://mattermost.atlassian.net/browse/MM-40574

**Comment by livwvil** [comment]
Can I get build for tests on my laptop?
