### ISSUE TITLE
 Windows 11 - MM Desktop Not Connecting 

### ISSUE THREAD

**Issue by hartescout** [mattermost/desktop#1854]
I confirm (by marking "x" in the [ ] below: [x]):

- [x ] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

Desktop Client on Windows 11 not connecting to any server. Connect loop

**Environment**
- Operating System: Windows 11 Pro Version 21H2 OS build 22000.282 Windows Feature Experience Pack 1000.22000.318.0
- Mattermost Desktop App version: 4.1.4
- Mattermost Server version: X.X.X 

**Steps to reproduce**
Attempt connection in Windows 11 environment to any MM server
**Expected behavior**
Successful Connection, Server load.
**Observed behavior**
Stuck, never connecting. 
![image](https://user-images.githubusercontent.com/41243343/140657071-e2ad76fe-2503-495d-a431-42752a4f328f.png)

**Possible fixes**
?

**Comment by devinbinnie** [comment]
@hartescout Mattermost Desktop v4.1.4 was built long before the release of Windows 11 and is therefore unsupported on that OS. You can upgrade to version v5.0.1 here which should work correctly on Windows 11: https://github.com/mattermost/desktop/releases/tag/v5.0.1

**Comment by hartescout** [comment]
Oh wow. I didnt realize I was so far behind. Thanks

**Comment by devinbinnie** [comment]
Closing as per above.
