### ISSUE TITLE
change back to the old server tab

### ISSUE THREAD

**Issue by zhubeilife** [mattermost/desktop#1855]
Hi May I know can we change back to the old server tab? It seems more convenient

![image](https://user-images.githubusercontent.com/7824663/140676113-01d6da73-5545-4995-988a-7eaacf584dd5.png)

**Comment by devinbinnie** [comment]
@zhubeilife Apologies, but there's no way to change back to the original tab structure without reverting back to v4.7.
We have plans to look into an interface in the future for a single-tab, single-server view that will not show tabs or a dropdown, but going forward we will be sticking with the dropdown structure for multiple servers.

**Comment by zhubeilife** [comment]
@devinbinnie ok thanks for feedback!
