### ISSUE TITLE
5.x New server selector is not daily usuable

### ISSUE THREAD

**Issue by ouafnico** [mattermost/desktop#1858]
Hi,

I'm using multiple mattermost servers on mattermost-deskop app.

Since 5.x release, the new selector imposes to the user to multiple clic for every notification.

When you receive a notification from a server, you don't know the source. You have to clic on the selector to see, and clic again to change server if needed.
Before it was fast and clear, each tab is a server, the notification appears on each tab.

On a daily use, it's really painfull to just multiple clic for a simple task.

Sorry if it's not the place, but the suggestions forum seems not really seen.

https://mattermost.uservoice.com/forums/306457-general/suggestions/44372673-new-server-selector-is-a-regression

**Comment by devinbinnie** [comment]
@ouafnico For the notification portion, do your notifications not show the server name when they launch? If not, can you tell me which OS you're running on?

**Comment by ouafnico** [comment]
@devinbinnie I don't use notifications because of the number of them (using Arch/Gnome).

But I'm talking about the new selector on the client here :
![Capture d’écran de 2021-11-09 15-52-25](https://user-images.githubusercontent.com/807350/140947014-eff06add-af30-4edc-ae61-a4543acc8a4a.png)

When any server configured got a notification, you don't know what server is concerned until you click on this selector, and must click again to change server.
The method on 4.x was a lot quicker.

**Comment by devinbinnie** [comment]
@ouafnico Ahh okay, sorry for the misunderstanding.
Thanks for the feedback. We've decided to go with the dropdown for the ease of use of switching between the Channels view, as well as Boards and Playbooks. I understand that it adds more clicks but we've had to make that trade-off in this case.

We will continue to iterate on the design. One thing we're planning on doing is creating a view for single-server, single-tab view that removes the header and the switcher for a bit cleaner UI.

If you have any other suggestions feel free to post them in Mattermost Community. Thanks again for the feedback :)

**Comment by devinbinnie** [comment]
> Thank you for your response.
> 
> That's bad new actually for multiple servers, the previous tab system was quite helpful. No possible workaround?

Not at the present, other than to downgrade to v4.7. Apologies.

**Comment by the-glu** [comment]
Hello,

I would like to support this issue: the new UI is really bad for people with multiple servers and it's really painful day-to-day.

At least an option to have the old behavior would be useful.

Thanks,

**Comment by alvegh** [comment]
Same as all before: With multiple servers, switching is really painful. The old tabbed UI was (almost) perfect

Regards
Alex

**Comment by t0r0X** [comment]
Here an example. 

I got a message on another Mattermost server:
![image](https://user-images.githubusercontent.com/9170345/142852300-d2404736-d6d5-4a57-b6da-ce3b12670da1.png)

To get there I have to open the drop-down, and select the server:
![image](https://user-images.githubusercontent.com/9170345/142852660-881dd5fe-4d29-402f-be56-a02146c6a2ec.png)

Well, this doesn't seem a lot, just one additional click... Now I'm on the other server, and I see "oh, that channel/discussion can wait", and I want to return to the other server... Again one additional click... At least now it got annoying and impractical.

I'd wish an option for having 1 server per tab, or (in fact nah, not really a wish, I've got enough open windows) multiple Mattermost Desktop instances, one per server.

PS
Side note, that button/tab/thing besides the server selector dropdown, what is it anyway:
![image](https://user-images.githubusercontent.com/9170345/142854293-2008ba55-61ee-4255-99d0-a88dcfe075e3.png)

**Comment by ppodevin** [comment]
Is there a way to have a configuration for the layout ?
This is bothering me too... Plus notification do not always appear in the taskbar.

**Comment by devinbinnie** [comment]
Closing as we have gathered feedback for this and will be contemplating what to do, but we won't be restoring the old behaviour as it existed. Sorry about that.

Thanks for the feedback from everyone, if you have any further feedback let us know here: https://community.mattermost.com/core/channels/user-feedback
