### ISSUE TITLE
Channel name is not highlighted when channel notifications is set to mentions only

### ISSUE THREAD

**Issue by Shutterstrom** [mattermost/desktop#186]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [x] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [x] This is a product defect issue that can be reproduced using the steps listed below.
- [x] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary
I only want to get notifications in Mattermost when my name is mentioned. Therefore I, in Notification Preferences for a channel I only have "Global Default" and "Only For Mentions" set. But with these settings I can't see in the left Channel List that the channel name is bold when something is written in the channel.

Is it possible to only get notifications for mentions (and @channel notifications) but still get the Channel marked as bold (or something) in the channel list on the left side of the client?

Is this a setting issue for me or a feature that can be fixed?

I'm using:
Server Version: 3.1.0
Mattermost Desktop 1.2.1
Windows 10

Kind Regards

**Comment by jasonblais** [comment]
Thank you @Shutterstrom for the report!

Is your `Notification Preferences` > `Mark Channels Unread` (which you can find by clicking "v" right of the channel name) marked `For all unread messages` or `Only for mentions`?

![image](https://cloud.githubusercontent.com/assets/13119842/16560155/989f2d48-41bf-11e6-8381-b48d60225dd4.png)

**Comment by Shutterstrom** [comment]
Here is the settings I have. As you see I have "Only for mentions" checked, but I still what the channel name in the left pane to become bold (or something) for any happenings in the channel. If the channel is bold, I can easily see that something has been happening in the channel without being logged in to that specific channel.


![channelnotificationpreferences](https://cloud.githubusercontent.com/assets/14293826/16575493/efab7028-4288-11e6-9af3-cdfa9d4b4185.PNG)

**Comment by yuya-oc** [comment]
@Shutterstrom The interface is controlled by mattermost server itself (The app works like a tab browser). How about raising this issue in /platform repo, or asking in the forum?

**Comment by jasonblais** [comment]
Thanks you again @Shutterstrom! 

This would indeed be a feature suggestion for the Mattermost Server itself.

Could we have your help contributing your suggestion in the [feature idea forum](https://mattermost.uservoice.com/forums/306457-general) so it can be discussed, upvoted and considered for a ticket accepting pull requests?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review.

You get 10 votes in the feature idea forum, and each one influences the future of the project.

**Comment by jasonblais** [comment]
@Shutterstrom Closing this for now, but you're very welcome to add your suggestion to our [feature idea forum](https://mattermost.uservoice.com/forums/306457-general) for discussion.

Many of the suggestions added to the forum have eventually been added as new features for Mattermost. Adding it there let's others in the community provide feedback and upvote the feature based on their preference.
