### ISSUE TITLE
Your session has expired errors

### ISSUE THREAD

**Issue by michaelkozakovsc** [mattermost/desktop#1861]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: OSX Big Sur on M1 mac mini
- Mattermost Desktop App version: 5.0.1.14620 for silicon mac 
- Mattermost Server version: 6.0.0 

**Steps to reproduce**

- Attempt to log in into server by entering the correct credentials
- Receive an error
 
**Expected behavior**
Should log in

**Observed behavior**
Fails to log in

https://user-images.githubusercontent.com/22355373/140983316-9ecf4e54-3865-4595-adf1-ba8786a07888.mov

**Possible fixes**

I downloaded an earlier version `5.0.0.14247 for silicon` and this problem does not exist on it

**Comment by coltoneshaw** [comment]
https://user-images.githubusercontent.com/46071821/141007535-3e91fa95-9d86-46ef-8d5e-b3c599a0f2d3.mov

Here is a video of the issue along with the workaround for it. This is a cloud server running with the playbooks and boards plugin manually deactivated / removed.

**Comment by amyblais** [comment]
@devinbinnie I opened a ticket: https://mattermost.atlassian.net/browse/MM-40025. Perhaps a candidate for 5.0.2?

**Comment by devinbinnie** [comment]
@michaelkozakovsc Are you still able to reproduce this? Did @coltoneshaw's explanation help at all?

**Comment by ressonix** [comment]
I reproduced this on the Rocky Linux instance. Playbooks appear to be installed, so I'm not sure if this is the cause of the bug, but I was able to get logged in by clearing the app's cache and entering login info again.

**Comment by BenAgner** [comment]
> I reproduced this on the Rocky Linux instance. Playbooks appear to be installed, so I'm not sure if this is the cause of the bug, but I was able to get logged in by clearing the app's cache and entering login info again.

I can confirm reproduce-ability for myself as well on a clean install.  Clearing the cache also fixed my issue.

**Comment by johnnyasantoss** [comment]
Still a bug on 5.0.2 on Linux running on Flatpak.

**Comment by devinbinnie** [comment]
> Still a bug on 5.0.2 on Linux running on Flatpak.

@johnnyasantoss The fix will be released in v5.0.3
