### ISSUE TITLE
Application hangs when right clicking text or clicking drop-downs

### ISSUE THREAD

**Issue by joseph-henry** [mattermost/desktop#1866]
- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

The desktop application will hang if one selects text and right clicks. The context menu is always empty. Application restart required.

This desktop application was installed via the `Snap` package

**Environment**
- Operating System: Ubuntu 21.10
- Mattermost Desktop App version: 4.7.0 
- Mattermost Server version: 5.37.2 

**Steps to reproduce**

Method 1: `Select text -> Right click`
Method 2: `Click dropdown`

**Expected behavior**
 The application should not hang

**Observed behavior**

The application hangs

**Possible fixes**

**Comment by amyblais** [comment]
@joseph-henry Do you see the same issue with Mattermost Desktop App version v5.0.2?

**Comment by joseph-henry** [comment]
Unfortunately `5.0.2` via the snap store wont open. It installs but no window ever pops up. I've reverted back to `4.7.0` for the time being. If you push a new version to `edge` I can test that.

**Comment by devinbinnie** [comment]
@joseph-henry Can you try with the app downloaded directly from https://github.com/mattermost/desktop/releases/tag/v5.0.2 and see if it reproduces?

**Comment by devinbinnie** [comment]
Closing as inactive
