### ISSUE TITLE
Debian amd64 package: systray: dark icon is light and vice versa

### ISSUE THREAD

**Issue by 2019-05-10** [mattermost/desktop#1871]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [ ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Updated to 5.0.2 via provided amd64 deb package.
After restart of client the systray icon is light instead of dark, as previosuly.
In Settings still dark ist selected.
Toggled between light and dark, the light icon apperas dark.

Either a condition evaluates wrong or the icons were swapped during packing.

**Environment**
- Operating System: Debian/unstable
- Mattermost Desktop App version: 5.0.2 
- Mattermost Server version: X.X.X 

**Steps to reproduce**

**Expected behavior**

**Observed behavior**

**Possible fixes**

**Comment by 2019-05-10** [comment]
![settings_icon](https://user-images.githubusercontent.com/50481865/142594246-62bdc6d3-974c-4351-935c-c380346b6331.png)
![dark_icon](https://user-images.githubusercontent.com/50481865/142594266-63a6f1ea-de67-40ba-b270-985072efde63.png)

Additionally, the icons now are considerably smaller than before, and thus smaller than every other systray icon.

**Comment by devinbinnie** [comment]
@2019-05-10 I see what you mean by the icon setting being reversed. It definitely could get a little confusing, I think the intention was that the "Light" themed icon was for "Light" themed OSes and vice-versa for dark.

@esethna Is this something we should change?

**Comment by esethna** [comment]
@devinbinnie ya perhaps we should reverse that, agree it's confusing

**Comment by devinbinnie** [comment]
Created a ticket: https://mattermost.atlassian.net/browse/MM-40233

**Comment by esethna** [comment]
Thanks. @2019-05-10 if you want to contribute a fix feel free! ^

**Comment by devinbinnie** [comment]
Closed by https://github.com/mattermost/desktop/pull/2180
