### ISSUE TITLE
consolidate settings

### ISSUE THREAD

**Issue by 2019-05-10** [mattermost/desktop#1872]
Currently, the client has at least three (or four) different places where settings are to be configured:
a) `sandwich menu -> File -> Settings` / systray icon `rmc -> Settings`
b) `cog` symbol left of the account icon
c) `account icon -> Account Settings`

While separating c) may with some effort and squiniting may look ok, splitting a) and b) make no sense.
Additionally, `File -> Settings` is a particularly odd path for settings

I move for putting everthing together into one UI, accessible via either `cog` or systray context menu.

**Comment by devinbinnie** [comment]
@2019-05-10 Thanks for the suggestion, unfortunately due to the way the Desktop App is designed (ie. a wrapper around our webapp) we are unable to consolidate these settings at this time. It will be looked into in the future if and when the architecture changes.
