### ISSUE TITLE
Closing application window does not close application

### ISSUE THREAD

**Issue by joseph-henry** [mattermost/desktop#1873]
- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

When closing the application window all associated processes still remain, videos still play, etc. Is this intended behaviour?

This desktop application was installed via the `Snap` package

**Environment**
- Operating System: Ubuntu 21.10
- Mattermost Desktop App version: 4.7.0 
- Mattermost Server version: 5.37.2 

**Steps to reproduce**

Method 1: `Open application` -> `Click close (X) in window title bar`
Method 2: `Open application` -> `Click "quit" in activity menu`

**Expected behavior**
 The application should stop associated processes.

**Observed behavior**

 The application does not stop associated processes.

**Possible fixes**

**Comment by devinbinnie** [comment]
Hi @joseph-henry, we have an outstanding issue to look at the Linux closing behaviour.
Currently what you can do is go to Settings and toggle the `Leave app running in notification area when application window is closed`. I think the setting might be backwards, but that's what you'll want to use.

Additionally, we are on version v5.0.2 now which will have some additional fixes. You can find it here: https://github.com/mattermost/desktop/releases/tag/v5.0.2

**Comment by devinbinnie** [comment]
Ticket here: https://mattermost.atlassian.net/browse/MM-30713

**Comment by devinbinnie** [comment]
Fixed in this PR: https://github.com/mattermost/desktop/pull/1988
