### ISSUE TITLE
npm install failure: chromedriver: Exit status 1

### ISSUE THREAD

**Issue by jneureuther** [mattermost/desktop#189]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [x] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [x] This is a product defect issue that can be reproduced using the steps listed below.
- [x] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

Manual installation with `npm install` or packaging with `npm run package` are failing because of an error during the chromedriver install.

#### Steps to reproduce

Run `npm install` or `npm run package`.

#### Expected behavior

Installation succeeds.

#### Observed behavior

```bash
18:57:18 › npm install                                                                                  !1972
npm WARN package.json mattermost-desktop@1.2.1 No repository field.
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm

> chromedriver@2.21.2 install /home/julian/git/mattermost/desktop/node_modules/chromedriver
> node install.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/julian/git/mattermost/desktop/node_modules/rimraf/rimraf.js:7:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
npm ERR! Linux 4.5.5-300.fc24.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v4.4.6
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE

npm ERR! chromedriver@2.21.2 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the chromedriver@2.21.2 install script 'node install.js'.
npm ERR! This is most likely a problem with the chromedriver package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chromedriver
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls chromedriver
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/julian/git/mattermost/desktop/npm-debug.log

```

#### Possible fixes

There is already an issue at the upstream project: https://github.com/giggio/node-chromedriver/issues/46
Unfortunately there is not much activity in this issue.
The proposed workaround (`npm install chromedriver --chromedriver_cdnurl=http://cdn.npm.taobao.org/dist/chromedriver`) does not work for me.

**Comment by jasonblais** [comment]
Thanks for the report @jneureuther!

It sounds like this would be a problem with [node-chromedriver](https://github.com/giggio/node-chromedriver/issues/46) than Mattermost Desktop app, am I correct?

**Comment by jneureuther** [comment]
@jasonblais as i mentioned in my issue:

> There is already an issue at the upstream project: giggio/node-chromedriver#46
> Unfortunately there is not much activity in this issue.

Since this hinders possible contributors i opened this issue.

**Comment by yuya-oc** [comment]
I think node-chromedriver is not used now. It was replaced with Spectron and electron-chromedriver is internally used. Would you try the latest code?

**Comment by Razzeee** [comment]
I had the same problem with a win7 machine I use (as documented in giggio/node-chromedriver#46 ), just tried again with latest master and the problem is gone. Thx!

**Comment by jneureuther** [comment]
> Would you try the latest code?

@yuya-oc On the master branch `npm install` works :smile: I was on the latest tagged version when I opened this issue.

**Comment by jasonblais** [comment]
Awesome! Thanks everyone :+1:
