### ISSUE TITLE
Allow multi-select in file upload dialog

### ISSUE THREAD

**Issue by Razzeee** [mattermost/desktop#190]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [x] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [x] This is a product defect issue that can be reproduced using the steps listed below.
- [x] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

You can only upload one file via the upload dialog.

#### Steps to reproduce

Please include: 
- Operating System: Win7
- Mattermost Desktop App version (See File > About Mattermost) : 1.2.1
- Mattermost Server version (See Main Menu > About Mattermost) : 3.0.0

1. Open a channel
2. Click the paperclip
3. In the new dialog, press CTRL and try to select multiple items

#### Expected behavior

You can select multiple items, as you can when you do the same in the browser

#### Observed behavior

You can't select multiple items

#### Possible fixes

I can't find any code, that customizes our handling of this dialog.
So it might in fact be a bug in electron, really no clue.

https://mattermost.uservoice.com/forums/306457-general/suggestions/13092408-win7-x64-desktop-allow-multi-select-in-file-uploa

**Comment by jasonblais** [comment]
Thanks @Razzeee for the report!

Agree, it would be great to fix it. Would you or anyone from the community be open to help investigate the issue further?

**Comment by Razzeee** [comment]
I really don't have an idea where to look for this or how to debug it.

**Comment by yuya-oc** [comment]
I have found that `multiple` attribute is removed.

It seems that the app is handled as API access by platform's [Utils.isMobileApp()](https://github.com/mattermost/platform/blob/v3.1.0/webapp/utils/utils.jsx#L60) because the UserAgent, `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Mattermost/1.2.1 Chrome/49.0.2623.75 Electron/0.37.8 Safari/537.36` includes "Mattermost". As the result, `multiple` attribute is removed in [FileUpload](https://github.com/mattermost/platform/blob/v3.1.0/webapp/components/file_upload.jsx#L310).

**Comment by jasonblais** [comment]
FYI, there is a [pull request submitted by the Mattermost team](https://github.com/mattermost/platform/pull/3654) which will change Utils.isMobileApp to return false for desktop apps.

After the pull request is in, will there be any further work on our end to allow multi-selecting files in the upload dialog?

**Comment by Razzeee** [comment]
I think that should be everything to fix it, but we will have to see/test.

**Comment by jasonblais** [comment]
The [pull request has been merged](https://github.com/mattermost/platform/pull/3654) and issue verified fixed. Thanks @Razzeee for reporting it!
