### ISSUE TITLE
Taskbar icon is pixelatted with poor quality

### ISSUE THREAD

**Issue by Razzeee** [mattermost/desktop#192]
I just tested https://circleci.com/gh/mattermost/desktop/477#artifacts 
Windows 7 64x and the taskbar icon looks weird/bad. But only as long as you NOT pin it to the taskbar.
When you do the quality is great.

![unbenannt](https://cloud.githubusercontent.com/assets/5943908/16613805/31506dae-436e-11e6-93b2-d0fc59b81dff.png)

**Comment by yuya-oc** [comment]
@Razzeee Would you tell me your environment? It seems that you are using higher-DPI resolution(more than 96 dpi). Windows 7 has three choices, 100%, 125% and 150%.

I had tested the icon with 100% and 150% on Windows 10, and they look fine. But reproduced with 125%.

<img alt="2016-07-06 21 49 56" src="https://cloud.githubusercontent.com/assets/1412057/16618420/34e69e2e-43c4-11e6-8108-bc7e268644d9.png">

**Comment by Razzeee** [comment]
I'm on 125% but 125% is marked as default for me. Maybe due to this beeing a laptop or some crazy screen aspect ratio.

**Comment by yuya-oc** [comment]
The default is determined by the pixel density parameter which is returned by the screen.

I thought Atom should have same problem, but it's fine. I tried with Atom's .ico, but it was pixelated. And electron-api-demos also has the problem. I'm not sure why Atom can solve this.

**Comment by jasonblais** [comment]
Did we change anything since the last release? Because there didn't use to be any issues with the taskbar icon in v1.2

**Comment by yuya-oc** [comment]
In v1.2, [I had added the png to the window](https://github.com/mattermost/desktop/blob/v1.2.0/src/main.js#L212). As the result, it avoided this problem. But #98 had been caused because the icon is too large for the top left icon.

So I stopped using the png in v1.3. In this case, the window uses the ico which is embedded into the exe. As I wrote, it works fine in 100% and 150% environment...

**Comment by Razzeee** [comment]
The weird thing is that it starts to work again, when you pin it.

**Comment by yuya-oc** [comment]
For now, I will fix this by reverting the usage of icons. Of course #98 reoccurs, but it looks better than this problem.
