### ISSUE TITLE
Uploading then deleting a custom emoji causes the app to stop working.

### ISSUE THREAD

**Issue by inclementweather** [mattermost/desktop#1920]
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Adding a custom emoji then deleting it after using it in chat results in the desktop App on macOS going to a blank white screen.  I can log in through the browser again and add the emoji again with the same name and the desktop App loads fine again.

**Environment**
- Operating System: macOS 12.0.1 (21A559)
- Mattermost Desktop App version: Version 5.0.2 (5.0.2.15006)
- Mattermost Server version: 6.1.0

**Steps to reproduce**
Add custom emoji, use it in chat, delete custom emoji.

**Expected behavior**
The text should be displayed in the emoji's absence 

**Observed behavior**
App refreshes to a white screen.  Reloading shows the chat for a second then goes back to a white screen.

Screenshot of dev console attached.
![Screen Shot 2021-12-09 at 9 39 01 PM](https://user-images.githubusercontent.com/13460432/145520117-f0f15878-5df9-49f7-90f4-2c73ed8ac6c4.png)

**Possible fixes**

**Comment by amyblais** [comment]
There is a fix queued for this for server v6.2.
