### ISSUE TITLE
Top bar (with "< Back" button) only shows content after reload

### ISSUE THREAD

**Issue by nmatt** [mattermost/desktop#1923]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

The new top bar is initially blank until a first explicit reload.

**Environment**
- Operating System: Windows 10 (2021H2)
- Mattermost Desktop App version: 5.0.2 
- Mattermost Server version: 5.37.5 

**Steps to reproduce**

1. exit the Mattermost desktop app (no Mattermost process running anymore)
2. start the Mattermost desktop app 
=> top bar is blank and white
3. press Ctrl+R to reload
=> top bar is now shown with (in my color scheme) grey background color and the "< Back" button
Repeating the above steps reproduces the behavior, i.e. the reload is not "sticky" after exiting the appkication.

**Expected behavior**

The top bar should correctly display without having to reload after each start of the application.

**Observed behavior**

The top bar is blank after starting the application, until a manual reload is performed.

Screenshot with the blank top bar marked with a red rectangle:
![image](https://user-images.githubusercontent.com/7593340/146221872-60678b7a-12e2-4933-8a28-c9d3e01bc7bb.png)

**Possible fixes**

**Comment by devinbinnie** [comment]
@nmatt The answer here should solve this issue as well: https://github.com/mattermost/desktop/issues/1924
