### ISSUE TITLE
New top bar with Back button is redundant

### ISSUE THREAD

**Issue by nmatt** [mattermost/desktop#1924]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

The new top bar containing the "< Back" button seems to be redundant and wastes valuable vertical space.

**Environment**
- Operating System: Windows 10 (2021H2)
- Mattermost Desktop App version: 5.0.2 
- Mattermost Server version: 5.37.5 

**Steps to reproduce**

No particular steps.

**Expected behavior**

There should be no top bar, or at least one should be able to disable/hide it.

**Observed behavior**

Screenshot showing the top bar with the "< Back" button, and also the existing back button in the channels list, both marked with a red border:

![image](https://user-images.githubusercontent.com/7593340/146222897-e8c58a79-2a58-4c85-8d63-3097b0d38ff6.png)

The top bar is wasting precious space, containing only the "Back" button. Moreover, that button seems to be redundant, as there is already an existing Back (and Forward) button.

**Possible fixes**

**Comment by devinbinnie** [comment]
@nmatt This shouldn't be showing when you're using Mattermost, it should only display when you're on an external site.

Can you confirm that the server URL you have configured explicitly matches the SiteURL configured on your Mattermost server?

**Comment by nmatt** [comment]
@devinbinnie You're right, we just had a server upgrade which apparently changed the URLs. It coincided with the desktop client upgrade which kept the existing configuration. So the issue is rather that the desktop client accepts an inappropriate server URL.

**Comment by devinbinnie** [comment]
@nmatt We can only verify that the URL is a valid URL in general at this time, not that it connects directly to a Mattermost server. We're looking into a way to make sure that the URL is valid when you configure it, but sounds like the configuration on your end just needed to be updated.

Let me know if I can be of any further help :)

**Comment by nmatt** [comment]
@devinbinnie: I'd open a new issue for that, but maybe it's better if you can provide the correct wording for that? I'm not really familiar with the different kinds of mattermost URLs.

**Comment by devinbinnie** [comment]
> @devinbinnie: I'd open a new issue for that, but maybe it's better if you can provide the correct wording for that? I'm not really familiar with the different kinds of mattermost URLs.

Not really sure what you mean, it seems to be that the URL was incorrect and by correcting it this issue is resolved, am I correct in saying that? Or is there a further issue?

**Comment by nmatt** [comment]
> > @devinbinnie: I'd open a new issue for that, but maybe it's better if you can provide the correct wording for that? I'm not really familiar with the different kinds of mattermost URLs.
> 
> Not really sure what you mean, it seems to be that the URL was incorrect and by correcting it this issue is resolved, am I correct in saying that? Or is there a further issue?

Sorry, our comments intersected. This was about that the client should be checking that it has a correct server URL. I hadn't yet seen your comment that it's currently not possible. I didn't expect the architecture to allow the application to somehow work with arbitrary HTTP payloads... Closing, although I think it's a messed up situation. ;)
