### ISSUE TITLE
Bug Hunt Competition (Desktop App v1.3)

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#193]
Huge thanks to everyone who helped submit [pull requests for Desktop App v1.3](https://github.com/mattermost/desktop/pulls?utf8=%E2%9C%93&q=merged%3A%3E2016-05-13), excited to ship the new release soon!

We're trying out something new: a **Bug Hunt Competition**! Top 5 point scorers will win a special prize (if your mailing address is reachable by our merchandise vendor, we'd like to send you a personalized award with your name and Bug Hunt Champion achievement date.).

Anyone who scores at least one point will be recognized on the Mattermost page.

Here are steps to participate in the competition:
 1. Download [release candidate for v1.3](https://github.com/mattermost/desktop/releases/tag/v1.3.0-rc1)
 2. Find an issue with the product which is
   - [ ] not a feature idea (feature ideas go here: http://www.mattermost.org/feature-ideas/)
   - [ ] not a troubleshooting question (troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
   - [ ] is not already reported by someone else in this thread or in [GitHub issues](https://github.com/mattermost/desktop/issues)
   - [ ] is a product defect issue that can be reproduced using the steps listed below.
 3. Reply to this thread with an issue you have found, containing
  - the operating system 
  - Mattermost server version and database (from Main Menu > About Mattermost)
  -  clear repro steps

You are welcome to join our [Desktop App](https://pre-release.mattermost.com/core/channels/desktop-app) discussion channel to meet the Desktop App community and use the Mattermost server for testing.

The point system that will be used: 
   - 1 point: Issue filed satisfies all three steps above
   - 2 bonus points: Issue reproduces on Windows
   - 3 bonus points: Issue is deemed critical and fixed for v1.3
   - 4 bonus points: The issuer submits a pull request, which is merged to the /desktop repo

**The competition will run from Thursday July 7th until Monday July 11th 23:59 GMT**

Good luck, let the bug hunt begin!
![image pasted at 2016-7-5 18-09](https://cloud.githubusercontent.com/assets/13119842/16640754/b973d220-43c8-11e6-8422-7f33391be348.png)

**Comment by jasonblais** [comment]
Update: [Release candidate for Desktop App v1.3 has been posted](https://github.com/mattermost/desktop/releases/tag/v1.3.0-rc1).

The competition has now begun, good luck everyone!

**Comment by DavidLu1997** [comment]
Clicking on text in the Settings checklist does nothing, even though it appears to be clickable

Operating System: Windows 10 64 bit
Mattermost Server Version and Database: N/A

Reproduction steps:
1. Go into settings
2. Attempt to click text next to the checkboxes, instead of the checkboxes themselves
![20160708_140339](https://cloud.githubusercontent.com/assets/5740966/16697024/a4f42a5e-4515-11e6-9450-7401e6de78a2.jpg)

**Comment by DavidLu1997** [comment]
Cannot save settings

Operating System: Windows 10 64 bit
Mattermost Server Version and Database: N/A
Desktop App version: Installed v1.3

Reproduction steps:
1. Change any setting
2. Save button still disabled

**Comment by DavidLu1997** [comment]
+ next to Teams should turn into a -
This confuses me, as pressing it again closes the Teams dropdown

Operating System: Windows 10 64 bit
Mattermost Server Version and Database: N/A
Desktop App version: Installed v1.3

Reproduction steps:
1. Press + next to teams

![image](https://cloud.githubusercontent.com/assets/5740966/16697304/0d5930d4-4517-11e6-9bf0-9a8267a4a150.png)

**Comment by DavidLu1997** [comment]
#improvement 

User should not have to type `https://` or `http://`

**Comment by lindy65** [comment]
#bug (credit to Steve MacQuiddy, Tesla)

"taskicon" in "Notifications" section of "Settings" should be "task icon"

Repro:
1. Click on "File" and select "Settings"
2. Scroll down until you can see the "Notifications" section

Observed:
"taskicon" is shown as one word (see screenshot)

Expected:
"task icon" is two separate words

![image](https://cloud.githubusercontent.com/assets/13020833/16710066/c76d8d4c-4622-11e6-817a-2b24a5281fd9.png)

**Comment by lindy65** [comment]
#improvement (credit to Steve MacQuiddy, Tesla)

If "Settings" is accessed, return to the channel that was being viewed before "Settings" was opened.

Environment: Windows, Mattermost Server 3.1

Repro:
1. Go to any channel of your choice
2. Click on "File" and select "Settings" (or CTRL+comma)
3. Click "Cancel" from within "Settings" 

Observed:
You are redirected to "Town Square" ("Reception" channel on Contributors team)

Expected:
You are redirected to the channel you were viewing before you accessed the "Settings" menu.

![image](https://cloud.githubusercontent.com/assets/13020833/16710158/b4f84f78-4625-11e6-88c1-ffdda3e623ec.png)

![image](https://cloud.githubusercontent.com/assets/13020833/16710164/de8621bc-4625-11e6-9bd7-00fb3eb67b5a.png)

**Comment by LordMike** [comment]
The `Report A Problem` link in the menu goes to a 404'ed page.

![image](https://cloud.githubusercontent.com/assets/1027111/16764986/ca2b3fbe-4831-11e6-9b16-d6f3e0455039.png)

Client: 1.3.0-rc1
Server: 3.0.3

Reproduction:
1. Click Report a Problem in the menu on your profile
2. Get redirected to: https://about.mattermost.com/default-report-problem/

**Comment by LordMike** [comment]
It is possible to open two running instances of the client. Instead, the client should direct focus to the existing instance of the program.

Client: 1.3.0-rc1
Server: 3.0.3

Reproduction:

1. Set up the MM client.
2. Open a new instance of the client (doubleclick the shortcut or whatever you do to start it)
2a. In Windows 7+ it can be done by the Task bar by right clicking the icon for MM and clicking on the Mattermost menu item:
![image](https://cloud.githubusercontent.com/assets/1027111/16765188/edea1456-4832-11e6-998a-2aa8e71347d9.png)
3. You now have two running windows with the same configuration.

**Comment by Razzeee** [comment]
https://github.com/mattermost/desktop/issues/193#issuecomment-232010629
Doesn't happen for me on Win10 
Client: 1.3.0-rc1
Server: 3.2.0
Probably server specific?

**Comment by LordMike** [comment]
https://github.com/mattermost/desktop/issues/193#issuecomment-232141046
Probably is. I'll try to poke our admin to upgrade.

**Comment by shieldsjared** [comment]
OS: Windows 7 Enterprise, 64-bit
Server Version: 3.1.0
Desktop Version: 1.3 RC2

Reproduction:
1. Open MM client
2. Press Ctrl+- to zoom out
3. Press Ctrl+Shift+= to zoom back in [Per shortcut-key on the menu]
4. Press Ctrl+- to zoom out
5. Press Ctrl++ to zoom in [Per the MM documentation AND standard convention]

Standard convention and the documentation state that Ctrl+(+/-) handle the zooming capability.  This is also the same sequence for most browsers.  Desktop application doesn't follow this convention.  Recommend either (a) updating the app to support the documentation of mattermost _and_ the convention, or (b) updating the documentation.

**Comment by jasonblais** [comment]
Thank you to all of you who filed new issues from the release candidates!

The competition closed earlier this week, so I will close the issue as complete. The winners will be contacted and included in our recognition page, to be released on the 18th as part of our v1.3 release of the desktop app.

All issues have been prioritized and those included in v1.4 will be included in our project plan, to be posted on the 18th as well!

Hope to see you all next time! Excited to see v1.3 out soon and get started with another set of improvements for v1.4!
