### ISSUE TITLE
Blank white screen after upgrading to Windows 11

### ISSUE THREAD

**Issue by kipjunes** [mattermost/desktop#1930]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
After Windows 11 upgrade and launching Mattermost client, screen turns white when I move the mouse cursor.

**Environment**
- Operating System: Windows 11 Home v21H2
- Mattermost Desktop App version: 5.0.2

**Steps to reproduce**
1) Upgrade from Win 10 to Win 11
2) Launch Mattermost client
3) After loading data, move mouse cursor

**Expected behavior**
Mattermost works as it should.

**Observed behavior**
Entire screen inside Mattermost window except for the header (menu, tabs) turns white.

**Possible fixes**

**Comment by devinbinnie** [comment]
@kipjunes Can you post a screenshot of what you're seeing?
Are you able to press `Ctrl+Shift+I` and see if you get a console window with any output?

**Comment by kipjunes** [comment]
This is what I see @devinbinnie:
![image](https://user-images.githubusercontent.com/96261448/146539365-3859a8e1-1a11-4237-8572-8a6734d5e8a3.png)

I am able to get the Developer Tools window by pressing Ctrl+Shift+I

**Comment by kipjunes** [comment]
Update: I got some feedback from our system admin who looked into this as the issue was also happening for other users in our company. Apparently the session expires somehow or somewhere within seconds or minutes (resulting in the white screen). It connects to the server successfully but the session is not starting. So, he thought perhaps the DB was not allowing the credentials (there were no other errors or symptoms found). Essentially, the client could reach the MM server, but all calls were possibly not being processed by the DB from the MM server. 

In any case, restarting the DB resolved the issue (for now)!

**Comment by devinbinnie** [comment]
Thanks for the update @kipjunes! As long as you can see the top bar with the tabs and the dropdown, that means that the issue generally lies with the server.

I'm going to close this one for now, let me know if the issue persists for you and not other users.
