### ISSUE TITLE
macOS client unhides the dock when clicking the Mattermost icon in the menu bar

### ISSUE THREAD

**Issue by EddyLB** [mattermost/desktop#1938]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Clicking on the Mattermost icon in the menu bar of macOS shows the desktop app window and unhides the dock. One must launch an app by clicking on an icon of the dock to hide the dock. This problem does not depend on the position of the dock on the screen.

**Environment**
- Operating System: macOS Monterey version 12.2 Beta (21D5025f) and all previous versions.
- Mattermost Desktop App version: 5.0.2 (5.0.2.15006)
- Mattermost Server version: 5.34.2, Database Schema Version: 5.34.0, mySQL

**Steps to reproduce**
- Launch Mattermost from the Applications folder
- Check that the option "Show Mattermost icon in the menu bar" is enabled
- Once connected to a server, close the window by clicking on the red button
- Click on the Mattermost icon in the menu bar
- The Dock is unhide and the Finder icon looks selected
- The Dock stays unhide until an icon of the dock is clicked.

**Expected behavior**
- The dock stays hidden when one clicks on the Mattermost icon in the menu bar.

**Observed behavior**
Screenshot taken before clicking on the Mattermost icon in the menu bar. 
<img width="867" alt="Before clicking" src="https://user-images.githubusercontent.com/7103032/147962495-cb948d59-25be-49e3-99c6-6a98f99a8550.png">

Screenshot taken after having clicking on the Mattermost icon in the menu bar
<img width="867" alt="After clicking" src="https://user-images.githubusercontent.com/7103032/147962507-076d009f-fe9a-4f3d-854d-f388cd998925.png">

**Comment by devinbinnie** [comment]
Created a ticket: https://mattermost.atlassian.net/browse/MM-40822
