### ISSUE TITLE
Win7右上角没有关闭按钮

### ISSUE THREAD

**Issue by yf639898** [mattermost/desktop#1942]
Win7右上角没有关闭按钮
Windows 7 does not have a close button in the upper right corner

**Comment by amyblais** [comment]
@yf639898 We currently support Windows v8.1+ https://docs.mattermost.com/install/software-hardware-requirements.html#desktop-apps. Are you able to update your OS?

**Comment by yf639898** [comment]
No, so I used versions 4.5.2 or 4.7.2 to install it
不行，所以我使用了4.5.2和4.7.2的版本去安装




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mattermost/desktop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月6日(星期四) 晚上9:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mattermost/desktop] Win7右上角没有关闭按钮 (Issue #1942)





 
@yf639898 We currently support Windows v8.1+ https://docs.mattermost.com/install/software-hardware-requirements.html#desktop-apps. Are you able to update your OS?

**Comment by amyblais** [comment]
Do you see the same bug with the latest v5.0.2?

**Comment by yf639898** [comment]
No, the old version of the natural perfect operation, but some Windows 7 running 4.5.2 will be black screen, so using 4.7.2 can work properly
However, the 4.7.2 title bar and the server title bar are not merged



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mattermost/desktop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月6日(星期四) 晚上9:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mattermost/desktop] Win7右上角没有关闭按钮 (Issue #1942)





 
Do you see the same bug with the latest Desktop app v5.0.2?

**Comment by devinbinnie** [comment]
@yf639898 We no longer support Windows 7 as it is no longer supported by Microsoft, so we ask that you upgrade your operating system to a supported version before we look into fixing any issues.

We are aware that the server bar and the top bar are not merged on Windows 7 as we only created the top bar style for Windows 10.

Closing this as won't fix. Let me know if you have further questions.
