### ISSUE TITLE
请添加中文语言Please add Chinese language

### ISSUE THREAD

**Issue by yf639898** [mattermost/desktop#1943]
Please add Chinese language

**Comment by devinbinnie** [comment]
@yf639898 Currently the desktop app only supports spell checking in languages other than English. The webapp, however, does support Chinese I believe, which you can change under Account Settings.

We'll be looking into translating the Desktop App this year, so this will be addressed soon!

**Comment by devinbinnie** [comment]
We are working on adding new languages here: https://translate.mattermost.com/projects/mattermost/mattermost-desktop/

**Comment by devinbinnie** [comment]
Looks like this is done: https://github.com/mattermost/desktop/blob/master/i18n/zh-CN.json
Let us know if there any mistakes :)
