### ISSUE TITLE
Apple Silicon (M1/Arm64) downloads not listed on downloads page

### ISSUE THREAD

**Issue by lathiat** [mattermost/desktop#1949]
#### Summary

Apple Silicon M1/ARM64 builds are not offered on the download page, only the AMD64 build:
https://mattermost.com/download/

However if you manually change the URL to include 'm1' as per https://github.com/mattermost/desktop/issues/1365 the download works. For example https://releases.mattermost.com/desktop/5.0.2/mattermost-desktop-5.0.2-mac-m1.dmg?src=dl

Ideally it would be a universal build but the download should at least offer the choice.

The performance of the AMD64 client on Apple Silicon is quite bad, I had noticed it taking many many seconds to load a channel especially for the first time. This is significantly improved by the M1 build. I assume this is due to needing to dynamicaly translate JITd javascript code but I am not sure of that :)

If this is the wrong place to file issues that are the website please let me know and I'm happily to refile elsewhere. But this repository seems mostly happy to be a catch-all location.

**Comment by devinbinnie** [comment]
Thanks for the feedback @lathiat. At this point I think we can look into updating the releases when v5.1 is out, as we'll be doing a full test of the application upon that release.

**Comment by rbebb** [comment]
@devinbinnie I think this can be closed since the downloads page now refers you to the App Store, and the GitHub page provides universal _and_ an ARM only downloads
