### ISSUE TITLE
linux (debian) desktop - Add server fails

### ISSUE THREAD

**Issue by jarek-jpa** [mattermost/desktop#1952]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: Debian and Ubuntu
- Mattermost Desktop App version: 5.0.2 
- Mattermost Server version: n/a 

**Steps to reproduce**
(installing - unpacking from .tar.gz file)
Launch "./mattermost-desktop", click on "No servers configured -> Add Server"

**Expected behavior**
Add-server dialog opens

**Observed behavior**
nothing happens

there are no errors.

NB. same happens when trying to use binary app from .deb package

**Possible fixes**

**Comment by devinbinnie** [comment]
@jarek-jpa This bug should be fixed in v5.0.3, you can grab an RC version from the Releases page.

**Comment by jarek-jpa** [comment]
hi @devinbinnie - thanks for reaching out, I've just tried both .deb and .tar.gz of 5.0.3-rc1 and it still doesn't work. NB. the version displayed in ... -> Help -> still says Version 5.0.2

is there some workaround maybe for this? like editing some config file (since it's a one-time operation normally)

**Comment by devinbinnie** [comment]
@jarek-jpa Sounds like you downloaded the wrong version, the version number should Version 5.0.3-rc1.
You can get it here: https://github.com/mattermost/desktop/releases/tag/v5.0.3-rc1

**Comment by jarek-jpa** [comment]
@devinbinnie I've double checked it. the sha256sum says "aabd7aa82de36aeff39e1928d56ae37695bffed4394e800d079d0b1af9c1d117" - so it matches the 5.0.3-rc1. however, as described, the behaviour is the same and the Help -> Version says it's 5.0.2

can you verify it on your side?

**Comment by devinbinnie** [comment]
@jarek-jpa Yes, I can verify that downloading from the above link gives me version 5.0.3-rc1:
![image](https://user-images.githubusercontent.com/52460000/149956215-de2135f0-7263-4f70-b98a-3bc8d5b27570.png)

And the Add Server modal opens correctly on my instance:
![image](https://user-images.githubusercontent.com/52460000/149956354-3a38bbc4-2535-402e-9f30-1e0fd5c5dfd6.png)

**Comment by jarek-jpa** [comment]
@devinbinnie ok, good to hear it works for you. any ideas what might get wrong here?

![mattermost-desktop-5 0 3-bug](https://user-images.githubusercontent.com/28875393/149958563-f51f6105-14d8-4210-b466-b0ba6ac4cca6.png)

**Comment by devinbinnie** [comment]
@jarek-jpa Not sure really, maybe try downloading again?

**Comment by devinbinnie** [comment]
@jarek-jpa Also make sure that you fully quit the original app before launching the new one (use File > Quit)

**Comment by jarek-jpa** [comment]
@devinbinnie ok, that was it! I have quit the application, but `ps` showed quite a few mattermost processes in background. now it works, thanks!

**Comment by devinbinnie** [comment]
Great! Closing the issue.
