### ISSUE TITLE
How to configure multilingual spellcheck?

### ISSUE THREAD

**Issue by leoniscsem** [mattermost/desktop#1954]
Since my system setting is German the desktop app automatically sets the spellcheck to German, but most of my conversations in Mattermost are English. When using Firefox or Chromium, I can configure the browser to do spellcheck in either English or German. I don't know where to look for (under the hood) to get to advanced settings or similar, so I could enable English spellchecking. Right now using the desktop app gives me just a sea of red waves.

**Comment by esethna** [comment]
Hey @leoniscsem. You can go to settings (...) on Windows or Preferences on Mac to add or change spell check languages:

![image](https://user-images.githubusercontent.com/14333569/149830785-c2480a69-d6c6-47b5-8055-5b887915e714.png)

**Comment by leoniscsem** [comment]
Unfortunately I can't see this fields on Ubuntu 20.04 in the latest snap install.
![Bildschirmfoto von 2022-01-18 05-27-27](https://user-images.githubusercontent.com/6514726/149838803-3370866a-825f-4806-9835-00e8b1fafcdf.png)

**Comment by Willyfrog** [comment]
Which version are you running? I know snap sometimes lags behind in versions, and the original 5.0 didn't allow to use different languages.

If you can't install a newer version, you could probably fiddle with the locales for starting mattermost so it uses that particular language instead.

**Comment by devinbinnie** [comment]
@leoniscsem You can manually installed v5.0.2 from [here](https://github.com/mattermost/desktop/releases/tag/v5.0.2) using the `.deb` package if you'd like, it will provide the feature mentioned above.

**Comment by leoniscsem** [comment]
Great to hear its on the roadmap anyway, I totally didn't check in with the Ubuntu snap store and just realised the 5.0.2 release is also there, just in the edge channel. Thanks a bunch for the help!

**Comment by devinbinnie** [comment]
The latest version of Mattermost Desktop should be hitting Snap soon, we updated it here back in November: https://github.com/snapcrafters/mattermost-desktop

Closing this as will be fixed.
