### ISSUE TITLE
Settings screen doesn't appear on Linux

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#196]
Cross-posting from /platform repo: https://github.com/mattermost/platform/issues/3528
#### Summary

Settings screen not appearing
#### Steps to reproduce

I am using mattermost desktop 1.2.1 on Ubuntu. Below are the steps to reproduce.

1) Login into 2 team
2) And then click on File --> Settings
#### Expected behavior

Setting screen should be shown.
#### Observed behavior

Screen was blank.
Note: Out of 10 times, I have observed this happening 5+ times

**Comment by jasonblais** [comment]
@prakashprabhakar, I have cross-posted your issue to the /desktop repo.

This was also reported by a user on Windows. Has anyone else in the community noticed this issue? I have been unable to reproduce so far on my end.

**Comment by YerayAlonso** [comment]
It happens for me too in an Ubuntu Mate 16.04 virtual machine (virtual box); both with v1.2.1 and 1.3.0-rc1.
However, I can see the settings screen in Windows 10 without problems.

**Comment by jasonblais** [comment]
Thanks @YerayAlonso! I've changed the title to only reflect the `linux` environment until it's reproduced reliably in Windows.

I'm wondering if the settings page is loading? If so, the screen might appear blank, given we haven't added a loading icon for the app yet (there's [an existing Jira ticket to create an animated loading icon for Mattermost](https://mattermost.atlassian.net/browse/PLT-2769)).

**Comment by YerayAlonso** [comment]
I think it tries to load the settings screen. This is how it looks for me:

![2016-07-12_16-28-04](https://cloud.githubusercontent.com/assets/1788228/16770548/b14ff3f6-484d-11e6-96ca-3fd1101b7aa7.gif)

**Comment by jasonblais** [comment]
Thanks for the gif @YerayAlonso, very helpful!

Wondering if the settings page loads successfully after some time?

**Comment by YerayAlonso** [comment]
Nothing changes after minutes...

**Comment by jnugh** [comment]
@YerayAlonso This looks like some kind of rendering error, do you have problems with other electron apps like Atom?
What kind of graphics card are you using?

**Comment by YerayAlonso** [comment]
@jnugh indeed it may be some problem with VirtualBox because it works fine for me in a "real" installation with the same OS.
I'll check Atom tomorrow in the same virtual machine.

**Comment by Razzeee** [comment]
You can also try to bring up the Developer Tools under the View menu

**Comment by YerayAlonso** [comment]
Atom shows fine; Developer Tools in Mattermost not.

![2016-07-13_09-18-34](https://cloud.githubusercontent.com/assets/1788228/16795126/fcbdc6f4-48db-11e6-8541-516a200ddb7e.gif)

Here what I did:
Open Atom - Maximize - View Welcome Guide
Mate Menu doesn't open. It's probably drawn behind Atom. So I minimize Atom.
Open Mattermost. You can see the rendering problem again, showing some Atom parts.
Try to switch between Atom and Mattermost through the Window switcher at the bottom panel to see if the rendering is corrected...
With Atom minimized and Mattemost with the focus, I press Ctrl+Shift+I to show the Developer Tools. It seems to try to show the screen, but the rendering is still wrong.
I press Ctrl+Shift+I to hide the Developer Tools. And I press Ctrl+Q to quit the app.

**Comment by animedbz16** [comment]
I am receiving this same issue with Mattermost Desktop 1.3.0-rc1 on Windows.

When I open the developer console, I am receiving an error:

```
Not allowed to load local resource:
file://users/<user>/Downloads/mattermost-desktop-1.3.0-rc1-win64/resources/app/browser/index.html
```

**Comment by jasonblais** [comment]
Hey @YerayAlonso, is this issue still applicable with the latest Desktop App release (3.4.1)

It sounded like it works on a "real" development environment

**Comment by YerayAlonso** [comment]
Yes @jasonblais, the issue is still happening with v3.4.1 [here](https://releases.mattermost.com/desktop/3.4.1/mattermost-desktop-3.4.1-linux-amd64.deb) in the same Ubuntu virtual machine.

**Comment by yuya-oc** [comment]
@YerayAlonso Would you try using `--disable-gpu` option?

**Comment by YerayAlonso** [comment]
> Would you try using `--disable-gpu` option?
That worked for me! Thanks @yuya-oc !

**Comment by jasonblais** [comment]
Glad to hear, thanks everyone! Closing the ticket,
