### ISSUE TITLE
Expected linebreaks to be 'LF' but found 'CRLF'

### ISSUE THREAD

**Issue by Profesor08** [mattermost/desktop#1961]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

When I run `npm run lint:js` I get **22560 errors**. I checked `.editorconfig`, it has `end_of_line = lf`, but every file in project has `crlf`.

**Environment**
- Operating System: Windows 10
- Mattermost Desktop App version: latest sources

**Steps to reproduce**
1. `git clone https://github.com/mattermost/desktop` !important, to have clean repo from master
2. `cd desktop`
3. `npm i`
4. `npm run lint:js`

**Expected behavior**
To have no linter errors

**Observed behavior**

```
  47:17  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  48:35  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  49:42  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  50:22  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  51:34  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  52:30  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  53:7   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  54:29  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  55:4   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  56:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  57:39  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

✖ 22590 problems (22560 errors, 30 warnings)
  22560 errors and 0 warnings potentially fixable with the `--fix` option.
```

**Possible fixes**

Change `end_of_line = lf` to `end_of_line = crlf` in `.editorconfig`, or fix linter issues and push to master.

**Comment by devinbinnie** [comment]
You need to set `core.autocrlf` to `false` when cloning, so that it will preserve the Unix-style line endings:
`git config --global core.autocrlf false`

**Comment by Profesor08** [comment]
So, git itself replace line ending depending by system, that breaks linter tests. Thanks.
