### ISSUE TITLE
Menubar Icon is bad visible on bright backgrounds on Mac OS

### ISSUE THREAD

**Issue by bomas13** [mattermost/desktop#1970]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

Menubar Icon is bad visible on bright backgrounds on Mac OS

**Environment**
- Operating System: Mac OS
- Mattermost Desktop App version: 4.6.2
- Mattermost Server version: 6.2.1

**Steps to reproduce**
- Start Mattermost Desktop Client

**Expected behavior**
- Menubar icon has more contrast to background

**Observed behavior**
- Menubar icon is white

![Bildschirmfoto 2022-01-26 um 11 49 37](https://user-images.githubusercontent.com/4661591/151150082-bae7213b-e04b-4ca2-bb8f-53e544ae6796.png)

**Possible fixes**

- Let the user adjust the color of the icon through the preferences

**Comment by devinbinnie** [comment]
@bomas We'll be adding this feature into v5.1, but I guess it makes sense to turn on for macOS as well. I'll make a change.

**Comment by bomas13** [comment]
Ah. On 5.0 it's already black... 👍

**Comment by devinbinnie** [comment]
@bomas13 Yeah, so apparently macOS works differently and doesn't allow us to override it. It does seem to work correctly in v5.0 so I think we can close this. Thanks for bringing this up :)
