### ISSUE TITLE
Notification sounds trigger twice at the same time

### ISSUE THREAD

**Issue by francislavoie** [mattermost/desktop#1974]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: Linux, Ubuntu 21.04
- Mattermost Desktop App version: 5.0.3-rc3 
- Mattermost Server version: 6.2.1 

**Steps to reproduce**

Receive a message while the window is not focused

**Expected behavior**

Notification sound only triggers once 

**Observed behavior**

Notification sound can be heard twice. Sometimes they're perfectly synced on top of eachother, sometimes offset by a few milliseconds as to sound stuttery.

FWIW, this occurred on Desktop v5.0.0 as well, I upgraded to the latest RC to see if it was fixed.

This started happening after we upgraded from Mattermost Server v5.6-ish (I no longer have the exact number, whatever version was included in Gitlab v14.3) to v6.2.1, by upgrading our Gitlab installation.

**Possible fixes**

:man_shrugging:

**Comment by devinbinnie** [comment]
Thanks @francislavoie, created a ticket here: https://mattermost.atlassian.net/browse/MM-41544

**Comment by francislavoie** [comment]
regarding the labels, this is a Linux issue, not Windows

**Comment by devinbinnie** [comment]
Fixed by https://github.com/mattermost/mattermost-webapp/pull/9778
