### ISSUE TITLE
Unable to login to the very first server the first time in the desktop app while being already logged in via a safari browser window

### ISSUE THREAD

**Issue by rpkoller** [mattermost/desktop#1986]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

after registering and verifying my email i have logged into the server with safari, while the safari window was still open i've tried to log into the server with the desktop app as well which lead to three "session expired: please sign in to continue receiving notification" notifications in a row and i was unable to log into the server via the desktop app.  

**Environment**
- Operating System: MacOS 10.13.6
- Mattermost Desktop App version: 5.0.2 (5.0.2.15006) 
- Mattermost Server version: cloud-2022-01-27-1 

**Steps to reproduce**
- Talked about the issue with Jason Blais who joined the server as well. he said it is probably a bug and i should report it in here. 
steps taken: 

- got an invite link to a server
- registered an account in safari 13.1.2
- verified my email address
- Logged into the server with Safari 
- Left the Safari window open 
- downloaded the desktop app v5.0.2
- added the server there 
- tried to log in with my credentials

**Expected behavior**
I would expect to login in flawlessly

**Observed behavior**
after submitting the login credentials it took a little while with a white screen then i've received 3 or 4 message center notifications stating "session expired: please sign in to continue receiving notification". after that the empty login form was shown again. if i reentered my credentials and submitted them again the same results show up again. 

as soon as i've closed the safari window and tried again to login via the desktop app it worked. as soon as i was logged in the first time it is possible to connect with the desktop app while a browser window is already open. 

and cant provide any screenshots unfortunately. forgot to take any :(

**Comment by amyblais** [comment]
You should be able to log in when you click on the “X” to dismiss the “Your session has expired…” message. We are also currently in progress of fixing this bug for v5.0.3.

**Comment by rpkoller** [comment]
hmmm the x i haven't noticed. my attention was drawn to the macos notifications. therefor i havent noticed unfortunately. but good that it is an already known issue and being fixed in the next version. thanks! but unfortunately i am unable to reproduce now since closing the browser window already enabled me to login. so the issue could be closed i guess? :)

**Comment by devinbinnie** [comment]
Closing this issue as per @rpkoller's comment. Let us know if it pops up again :)
