### ISSUE TITLE
Question regarding milestone of https://github.com/mattermost/desktop/pull/1933

### ISSUE THREAD

**Issue by pandel** [mattermost/desktop#1987]
Hi!

@amyblais marked the mentioned PR for milestone 5.1.0, but does that really mean we have to wait 5.0.2...5.1.0 until this will find its way into an official client? I have about 400 colleagues going totally mad about this problem after the last upgrade (because of our corporate Windows theme) and they'd love to see this showing up as soon as possible in an upcoming version.

Is there any reason for this not being planned for 5.0.3? Or do I have to compile the desktop version on my own?

Regards,
Holger

**Comment by devinbinnie** [comment]
@pandel Yes, the plan is to release this in version v5.1, which should be out in the coming months.

However, if you would like to use the fix now you can find nightly builds of our Desktop App (which will contain the fix) [here](https://community.mattermost.com/core/channels/desktop-builds). Please note however that these builds are not considered stable and are currently unsupported.

**Comment by JtheBAB** [comment]
I guess the main question is more why is that fix not included in 5.0.3? Also don’t see the point.

**Comment by devinbinnie** [comment]
At the time we didn't think it was mission critical, sorry for the inconvenience. Unfortunately v5.0.3 final was cut yesterday so I'm unable to add it at this point.

**Comment by JtheBAB** [comment]
I am general in favor to add all available bigfixes into the next release. Why wait?

**Comment by amyblais** [comment]
Normally we include regression fixes and high severity fixes to dot releases. We didn't realize this was critical, but we can take this into consideration if 5.0.4 gets scheduled.

**Comment by pandel** [comment]
@amyblais Many thanks for your clarification. I must admit that a visible taskbar icon is absolutely mission critical! I had over 100(!) phone calls only in the first two hours after upgrading Mattermost to 5.0.2 because of the missing icon! Our task bar is nearly black (corporate decision) and so the icon is invisible atm. People open and close Mattermost via this icon and we use minimize to taskbar, so they simply don't find the icon whenever they want to write a new message.

Thanks for the hint regarding the nightly builds. I am no big friend of them in production, but the icon problem is even more problematic, so I will consider this...

**Comment by pandel** [comment]
@amyblais 
FYI, I recompiled 5.0.3 from source with added #1933 . It works now :-) - hopefully you decide to integrate this patch before 5.1.0, so we don't have to recompile again for every new version.

**Comment by amyblais** [comment]
@pandel We're planning to fix this in v5.0.4 along with another fix. v5.0.4-rc1 will be cut soon.

**Comment by pandel** [comment]
@amyblais WOW! Ok, that is faster than I expected. Many many thanks for taken this so seriously!
