### ISSUE TITLE
Unable to remove autostart for mattermost-desktop

### ISSUE THREAD

**Issue by FiV0** [mattermost/desktop#1989]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

Unable to remove autostart for mattermost-desktop

**Environment**
- Operating System: Arch Linux, Linux 5.16.4-arch1-1, xfce4
- Mattermost Desktop App version: 5.0.2
- Mattermost Server version: 5.31.4

**Steps to reproduce**

Open mattermost-desktop. Restart the system. Mattermost is started maximized. 

**Expected behavior**

Mattermost is not started at all.

**Observed behavior**

I tried removing the mattermost-desktop entry in `Session and Startup` as well as removing `mattermost-desktop.desktop` from `~/.config/autostart/`. If I don't use mattermost-desktop this will work, but the next time I reopen mattermost the `.desktop` entry is back and it will get started on boot. 

**Possible fixes**

**Comment by devinbinnie** [comment]
@FiV0 I wasn't able to reproduce using Manjaro and the latest v5.0.4 from that repo. Did you go into Settings and uncheck "Start app on login"?

**Comment by FiV0** [comment]
@davinbinnie Ok that did it for me. Still a bit confusing that it overrides the system level options.
