### ISSUE TITLE
Desktop Toast notifications don't work in 5.0.3

### ISSUE THREAD

**Issue by phreaker0** [mattermost/desktop#1992]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

Desktop Toast notifications don't work any more.

**Environment**
- Operating System: Windows 10 and Linux (Ubuntu 20.04)
- Mattermost Desktop App version: 5.0.3 
- Mattermost Server version: 6.3.1 

**Steps to reproduce**
Enable desktop notifications.

**Expected behavior**
If messages are received a desktop toast notification should be displayed.

**Observed behavior**
No desktop notification is displayed.

**Possible fixes**

Going back to 5.0.2, toast notifications work there.

**Comment by jgilliam17** [comment]
@amyblais I can repro on 5.0.3. 
Not reproducing on 5.0.2 and daily builds (master)
Ticket created: https://mattermost.atlassian.net/browse/MM-41567

**Comment by amyblais** [comment]
@devinbinnie We can plan a dot release for this and the other issue discussed yesterday https://github.com/mattermost/desktop/issues/1987.

@jgilliam17 Let me know if release tests can be added for this case (toast notifications).

**Comment by babono** [comment]
i'm having this issue as well, even there is no mattermost item on the system setting -> notification (mac os catalina) v.5.0.3

**Comment by amyblais** [comment]
This is being fixed for v5.0.4, to be released soon.
