### ISSUE TITLE
annoying and rather pointless error popup about dubious cert error

### ISSUE THREAD

**Issue by 2019-05-10** [mattermost/desktop#1997]
**Summary**
Suddenly I get an error popup about a certificate issue. There are several things wrong with that popup:
a) I cannot copy the error message (to either search for it or send it on to the admin)
b) the message blocks everything -- it keeps appearing on and on and on. It's nearly impossible to even minimize Mattermost, and even after managing that the popup keeps popping up
c)  checking the error details does not provide much detail and also the error message again cannot be copied 
d) it is impossible to see the supposedly offending certificate
e) it is impossible to shut up the client, ie keep the popup from happeningh over and over again

So far, it is basically impossible to determine if there's a genuine issue with that certificate (no information at all) or if the client is malfunctioning.

**Environment**
- Operating System: Linux (Debian/sid)
- Mattermost Desktop App version: 5.0.4
- Mattermost Server version: currently inaccessible
**Steps to reproduce**

**Expected behavior**
a) show useful message
b) allow to copy message
c) show certificate in full
d) allow to minimize to systray and silence the popup while minimized

**Observed behavior**

**Possible fixes**

**Comment by devinbinnie** [comment]
@2019-05-10 Can you provide reproduction steps for us? A screenshot or a video of what you're seeing as well would be helpful :)

**Comment by devinbinnie** [comment]
@2019-05-10 We do have functionality for explicitly trusting or untrusting certificates. That should make the popup go away after the certificate has been explicitly trusted, so if there's an issue there I'd like to see the workflow with a screenshot, and understand a little more about what you mean. Otherwise there's not much we can do to fix it.

**Comment by 2019-05-10** [comment]
The message told me the certificate was invalid without _any_ reason at all, "Details" gave a very short and pointless message and the choice to "Trust" or "Cancel".
At no point I was able to see the certificate in question, let alone get _any_ information at all, what made MM distrust the certificate.
How am I supposed to trust blindly a certificate MM chokes on?

If MM has reason to distrust a certificate, it certainly should be able to tell users instead of leaving them in the dark.
And, once again, it should in any case allow to view the certificate -- every cheap browser allows easy access to a certificate -- why doesn't MM, even when there's an issue with it?

**Comment by devinbinnie** [comment]
@2019-05-10 Thanks for the feedback. Based on what I'm reading, it sounds like we have 2 issues to look at:
1) The message about why the certificate is untrusted is unclear.
2) The user should be able to view the certificate in question.

Is there anything else I'm missing?

**Comment by 2019-05-10** [comment]
Uhm, I think, I alreday enumerated twice what other issues are there.
Please, see the initial issue and my first answer.

**Comment by devinbinnie** [comment]
A ticket has been created: https://mattermost.atlassian.net/browse/MM-42066

**Comment by 2019-05-10** [comment]
And it's back.
Did anything happen in the meantime?

I _still_ cannot see the certificate and I still don't really know what the issue is.

Version 5.1.0
Mattermost Version: 6.0.2
Database Schema Version: 6.0.2
Database: postgres

I am still left with the pointless options to either 
- cancel the connection (whatever that means, since I still can post to channels)
- trust a certificate I do know nothing about and cannot learn anything

You do realize that this is a rather grave security issue, do you?

**Comment by devinbinnie** [comment]
@vanilla-thunder Is this affecting you on v5.1.1? We did a change in that version that should stop the popup from re-appearing as often (it was popping up everytime we would retry loading the page, which would happen everytime the certificate check was cancelled).

**Comment by devinbinnie** [comment]
Closing as stale.
