### ISSUE TITLE
No notification on mac

### ISSUE THREAD

**Issue by teger** [mattermost/desktop#1999]
Hi,

On mac, with application 5.0.3, i have no notifications in noifications center.
Why ?

Thanks

**Comment by amyblais** [comment]
@teger We fixed a bug related to this in v5.0.4. Do you see improvements in that version?

**Comment by Willyfrog** [comment]
if you are using multiple displays and you are on the latest version of macos, make sure you enable showing notifications when having multiple displays attached.
