### ISSUE TITLE
Unable to import client certificate on Mattermost-Desktop

### ISSUE THREAD

**Issue by smilekison** [mattermost/desktop#2007]
Hello everyone, I have installed the Mattermost-Desktop application from snap store on Ubuntu 20.04. I have a site which requires me to import a certificate so that i can access it. The Mattermost-Desktop app on windows is working fine and it prompts a certificate popup box for choosing certificate but Ubuntu Mattermost-Desktop is not prompting me to such pop up. It directly redirects me to unauthorized page. Can anyone help me with this?

Ubuntu: 20.04 LTS
Mattermost: v4.7.0

**Comment by devinbinnie** [comment]
@smilekison Have you tried with the latest v5.0.4 directly from the Mattermost website? Also I think the latest version on snap should be v5.0.2 (if you'd prefer to try that)

**Comment by devinbinnie** [comment]
@smilekison Which version of the Mattermost Desktop App are you using? Your initial post says v4.7, but we are currently on v5.0.4 and have made many improvements. If you upgrade it's possible that your issue has already been resolved.

If not, i'll be happy to look into it for you :)

**Comment by smilekison** [comment]
@devinbinnie.. While posting the question, i installed v4.7.0 from snapstore and after you provided your insights, I tried it installing the v5.0.2 version from snapstore. To import the client certificate i followed the correct steps of the following QA.
 
https://askubuntu.com/questions/73287/how-do-i-install-a-root-certificate
