### ISSUE TITLE
Selectable spellchecker language in windows app

### ISSUE THREAD

**Issue by MM-Mikhail** [mattermost/desktop#2022]
In current windows app it is impossible to switch language of spellchecker, it always defaults to system.

This is very inconvenient for international users or those that speck different languages in different groups.

Should be an easy to use popup menu in the editing gadget (eg. see how FireFox does it)
Possibly have a language setting for the channel.

Ideally detect current language via currently enabled keymap.

Suggest features in the Mattermost feature idea forum so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html).

[https://mattermost.uservoice.com](https://mattermost.uservoice.com/forums/306457-general?category_id=159795)

You get 10 votes in the feature idea forum, and each one influences the future of the project.

**Comment by MM-Mikhail** [comment]
There is no such setting to do so, or not visible to general users

**Comment by devinbinnie** [comment]
This should be setting right here:

![image](https://user-images.githubusercontent.com/52460000/159924539-4704f89a-4f97-4b4d-82ff-6338053de077.png)

**Comment by MM-Mikhail** [comment]
Do you see it ?    I don't.
Besides, even if it was, it would be global setting and can not be changed rapidly for each channel when needed.

![изображение](https://user-images.githubusercontent.com/32386040/159932439-1e77c7c8-ecd4-402c-a0e5-86e2a25aece5.png)

**Comment by devinbinnie** [comment]
Which version of the Desktop App are you running?

**Comment by MM-Mikhail** [comment]
Ok, partially solved, updated to current 5.0.4 and the language selection works now.
Still very inconvenient when you need to change it since it is global and requires restarting.
