### ISSUE TITLE
Blue badge on the tray icon but no unread messages

### ISSUE THREAD

**Issue by hammenm** [mattermost/desktop#2024]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

Blue badge in the icon tray, but no unread messages

**Environment**
- Operating System: Windows 10 Professional 21H2 19044.1586
- Mattermost Desktop App version: 5.0.4
- Mattermost Server version: 6.3.5 (but I think it happened also when we were on 5.37.9

**Steps to reproduce**

Open Mattermost Desktop app and connect to my company Mattermost server.

**Expected behavior**

No icon

**Observed behavior**

Icon is present

![image](https://user-images.githubusercontent.com/9029787/159803872-37ea41ec-5f7c-4674-b9ef-14286e5cac38.png)

I don't know if this can be related but I also see this when I am scrolling through my direct messages.

![image](https://user-images.githubusercontent.com/9029787/159804108-11d33a73-8ef2-461d-a750-15ec0ae6b11a.png)

**Comment by devinbinnie** [comment]
@hammenm Yes the screenshout would be related, it would appear that you have some unread messages, or at least the server/webapp believes so. Has this persisted or were you able to clear the unreads?

**Comment by devinbinnie** [comment]
@hammenm Have you tried removing and re-adding the server? It looks like the server that you are using does have some unreads, does it not show any unreads using the webapp?

**Comment by hammenm** [comment]
@devinbinnie 

What do you mean by removing and re-adding the server ? We do regular server update and we follow the procedure described on the web page : https://docs.mattermost.com/upgrade/upgrading-mattermost-server.html

So excepting server data, the update erase the server files.

As said in my previous message, this does not occur on my Android phone, nor on the web app.

**Comment by devinbinnie** [comment]
@hammenm If you go to your dropdown, and click on the trash icon next to the server, it will remove it. You can then re-add the server afterwards. It's possible something is stuck in the cache, it would be very odd that the `More Unreads` indicator would pop up. It's also possible that the server is stuck in a way where it believes it has unreads when it doesn't.

**Comment by devinbinnie** [comment]
Closing as inactive, likely a troubleshooting question that was resolved.
