### ISSUE TITLE
Channel Files -> open -> MM goes blank and needs to be restarted

### ISSUE THREAD

**Issue by 2019-05-10** [mattermost/desktop#2028]
**Summary**
Open channel files overview and try to open a file.
MM desktop client channels pane goes gray and connat be restored until client is restarted.

**Environment**
- Operating System: Linux, Debian/SID
- Mattermost Desktop App version: 5.0.4
- Mattermost Server version: 6.0.2

**Steps to reproduce**
- open list of channel files
- click on a file
- MM goes gray, can switch to "Boards" or "Playbooks", but when switching back to "Channels" pane is still gray and unresponsive
- need to quit the client and restart
- nothing in the log
- experienced it with both XLS files and CSV. While XLS may, in fact, ask too much of MM (in which case it simply should pop up a dialog asking for an application), CSV is just plain text -- so I am assuming it is not necessarily the file type but opening a file as such that breaks something

**Expected behavior**
File opens (inside MM or with system default application) or a dialog asks for an application to open the file with.
**Observed behavior**
"Channels" page goes gray and unresponsive, apparently no other way to get out that restarting the client

**Possible fixes**

**Comment by amyblais** [comment]
@2019-05-10 We fixed this issue in server v6.2.0. Would you be open to upgrading?

**Comment by 2019-05-10** [comment]
I am but a lowly user.
Will ask the providing party next time I met them.

**Comment by amyblais** [comment]
I'll close this for now as the bug will be fixed with a server upgrade to a newer version.
