### ISSUE TITLE
Issue template: "MM Server Version" path outdated?

### ISSUE THREAD

**Issue by 2019-05-10** [mattermost/desktop#2029]
**Summary**
Below you ask for the server version -- the "three dots next to your profile picture" don't exist in 5.0.4.
The only existing "three dots" do in none of the submenus contain the information.
Instead now one needs to click the checker board/nine dots square icon.
**Environment**
- Operating System:
- Mattermost Desktop App version: 5.0.4
- Mattermost Server version: 6.0.2

**Steps to reproduce**

**Expected behavior**

**Observed behavior**

**Possible fixes**

**Comment by amyblais** [comment]
I've opened a PR to fix the template: https://github.com/mattermost/desktop/pull/2030.
