### ISSUE TITLE
Replace login on startup with native electron feature

### ISSUE THREAD

**Issue by Razzeee** [mattermost/desktop#203]
If I read the changelog for electron 1.2.7 correct

> Add app.getLoginItemSettings() and app.setLoginItemSettings(settings) APIs.

http://electron.atom.io/docs/all/#appsetloginitemsettingssettings-macos-windows

It should allow us to drop our third party package and offer the option to show on startup also for macos

**Comment by Razzeee** [comment]
Okay, our third party package supports linux, electron core so far doesn't. We probably want to wait some versions, if they add it.

**Comment by jasonblais** [comment]
Circling back -- would this be something we want to pursue, or is it still pending?

**Comment by Razzeee** [comment]
I feel like our auto launch is mature enough, so we won't need this.
