### ISSUE TITLE
Can't grab vertical scrollbar easily in messages pane

### ISSUE THREAD

**Issue by kelderek** [mattermost/desktop#2034]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Can't easily grab vertical scrollbar in message pane when mattermost desktop is windowed because Windows resize area is most of the scrollbar width

**Environment**
- Operating System: Windows 10 21H2
- Mattermost Desktop App version: 5.0.4
- Mattermost Server version: 6.5.0

**Steps to reproduce**
Open mattermost desktop in windowed mode (not an issue when maximized)
Go to a channel or DM with enough messages that there is a vertical scrollbar
Attempt to grab the vertical scrollbar with the mouse

**Expected behavior**
All, or at least most, of the scrollbar should be available to grab

**Observed behavior**
Only a couple pixels are available to grab.  The majority of the scrollbar changes to the window resize function
Problem does not occur on browser versions because resize starts at the window frame (last pixel of window) and extends a bit beyond the edge of the window

**Possible fixes**
1) override the ::-webkit-scrollbar width property to increase the scrollbar width
2) add a small amount of padding between the scrollbar and the edge of the window (~6px or so) to account for the problem
3) somehow adjust the electron wrapper to handle the window resize borders like other windows apps, where the right hand resize starts at the last pixel of the window and extends a few pixels past the edge of the window.  This might be something controlled by the window's frame size, even though the frame isn't visible.  If possible, set the application window frame size to 1 pixel

**Comment by kelderek** [comment]
I think it is the kResizeInsideBoundsSize property in electron that controls the resize handle.  It is set to 5, which is consistent with the very small area to grab the scrollbar (default width 8px).  Found here:

https://github.com/electron/electron/blob/7caa88c46f70d9600bd4f78fb902374e72a2a4bf/shell/browser/ui/views/frameless_view.cc

I have never made an electron app so I don't know if that can be overridden

**Comment by devinbinnie** [comment]
We have an issue open for this already here: https://github.com/mattermost/desktop/issues/1513
Closing.
