### ISSUE TITLE
Desktop application opens any provided site when adding a server

### ISSUE THREAD

**Issue by userbradley** [mattermost/desktop#2054]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Desktop application allows you to open any website by adding new server

**Environment**
- Operating System: OSX 12.3 (21E230)
- Mattermost Desktop App version: 5.0.4
- Mattermost Server version: 6.6

1. Open desktop application
2. Click add new server
3. Name it anything
4. Fill in any web address
5. Site loads

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/41597815/163494132-2533ca4a-2371-4b93-8018-36a3daa3a724.png">

**Expected behavior**

Desktop application should respond with `This is not a mattermost server Address`

**Observed behavior**

Web page loads and you are able to interact with it

**Possible fixes**

1. Check headers contain the word `mattermost` (Will require the mattermost server to send these)
2. Check HTML contains certain mattermost specific phrases

**Comment by devinbinnie** [comment]
This will be worked on as part of next-gen changes to the Desktop App. Currently we don't require any specific server side validation (apart from a couple cosmetic checks) so there's no incentive to support this, but in the future we likely will.

**Comment by devinbinnie** [comment]
Relevant JIRA issue: https://mattermost.atlassian.net/browse/MM-50352
