### ISSUE TITLE
Allow different proxy settings for different server in same standalone client

### ISSUE THREAD

**Issue by MaximBoguk** [mattermost/desktop#2055]
Hi, I currently in situation when I have 3 mattermost servers from 3 different outside customer each require independent socks proxy settings (socks over ssh tunnel).
How I can configure Ubuntu MM client to work in such environment? Currently only global proxy settings available via environment variables,

**Comment by devinbinnie** [comment]
@MaximBoguk This isn't something currently supported by the Desktop App. The only thing I could think of doing would be to tunnel manually and forward a different port where each server resides to your local machine, not sure how that works in conjunction with SOCKS though.
