### ISSUE TITLE
Cannot login with GitLab

### ISSUE THREAD

**Issue by pessi-v** [mattermost/desktop#2069]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: Ubuntu Budgie 20.04
- Mattermost Desktop App version: 5.0.4 64-bit .deb
- Mattermost Server version: can't find out

**Steps to reproduce**
Open desktop client. Click on GitLab login page link

**Expected behavior**
GitLab login page opens

**Observed behavior**
Nothing happens. Terminal output says opening link was prevented

**Comment by amyblais** [comment]
@pessi-v You can find the Mattermost server version at Main Menu > About Mattermost. Can you help check this?

**Comment by pessi-v** [comment]
@amyblais I think I can't get to the Main Menu because I can't login, but the server admin says it's 6.3.2

**Comment by devinbinnie** [comment]
@pessi-v Would you be willing to try the latest release candidiate of v5.1? It may fix your issue.
https://github.com/mattermost/desktop/releases/tag/v5.1.0-rc.2

**Comment by pessi-v** [comment]
@devinbinnie 5.1.0-rc2.1_amd64 didn't work either

**Comment by pessi-v** [comment]
17:33:35.229 › webContentEvents.did-start-navigation {
  webContentsId: 3,
  url: 'https://chat.x.org/oauth/gitlab/login'
}
17:33:35.232 › webContentEvents.will-navigate {
  webContentsId: 3,
  url: 'https://chat.x.org/oauth/gitlab/login'
}
17:33:35.234 › Prevented desktop from navigating to: https://chat.x.org/oauth/gitlab/login

on 'Finest':

17:35:55.375 › TeamDropdownView.handleClose
17:35:55.380 › webContentEvents.did-start-navigation {
  webContentsId: 3,
  url: 'https://chat.x.org/oauth/gitlab/login'
}
17:35:55.381 › webContentEvents.will-navigate {
  webContentsId: 3,
  url: 'https://chat.x.org/oauth/gitlab/login'
}
17:35:55.382 › Prevented desktop from navigating to: https://chat.x.org/oauth/gitlab/login
17:35:55.388 › MattermostView.handleFaviconUpdate {
  tabName: 'X___TAB_MESSAGING',
  favicons: [
    'https://chat.x.org/static/images/favicon/favicon-default-16x16.png',
    'https://chat.x.org/static/images/favicon/favicon-default-24x24.png',
    'https://chat.x.org/static/images/favicon/favicon-default-32x32.png',
    'https://chat.x.org/static/images/favicon/favicon-default-64x64.png',
    'https://chat.x.org/static/images/favicon/favicon-default-96x96.png'
  ]
}
17:35:55.389 › MattermostView.handleFaviconIsUnread {
  favicon: 'https://chat.x.org/static/images/favicon/favicon-default-16x16.png',
  viewName: 'X___TAB_MESSAGING',
  result: false
}
17:35:55.390 › AppState.emitMentions {
  serverName: 'X___TAB_MESSAGING',
  isExpired: false,
  newMentions: 0,
  newUnreads: false
}
17:35:55.391 › Badge.showBadge { sessionExpired: false, mentionCount: 0, showUnreadBadge: false }
17:35:55.392 › TeamDropdownView.updateMentions { expired: {}, mentions: {}, unreads: {} }


@devinbinnie

**Comment by devinbinnie** [comment]
@pessi-v What is your server URL configured as? Is it exactly `https://chat.x.org`? Sometimes deviations can cause issues here. I assume there is also no subpath after the URL?

**Comment by pessi-v** [comment]
@devinbinnie sigh, that was it. I had configured the server with http://. Changing that to https:// did it. Thanks for the help!
