### ISSUE TITLE
Taskbar icon is missing Mattermost logo on Ubuntu Unity

### ISSUE THREAD

**Issue by prakashprabhakar** [mattermost/desktop#208]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [x] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [x] This is a product defect issue that can be reproduced using the steps listed below.
- [x] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary
App Options not working on Ubuntu Linux

#### Steps to reproduce

- Operating System - Ubuntu
- Mattermost Desktop App version: 1.3.0
- Mattermost Server version: 3.2.0

1) Select the below options and save the application

    Show icon on menu bar (Need to restart the application)
    Change team from Light to Dark.
    Leave app running in notification area when the window is closed (available on next restart)

2) Close and Re-open the application.

#### Expected behavior

1) Icon should be present in the menu bar
2) Theme should have changed.

#### Observed behavior

None of the above things happen. I can't notice the icons, theme is not changed.

2 other things are noticed:
a) From the Menu bar of Ubuntu, the application cannot be quit (Although there is an option. The user has to go to File --> Settings --> Exit to close the app.

b) While opening tthe applilcation from terminal I noticed the below error:

prakashp@BLRSOFT-106:~/mattermost$ ./Mattermost
{ Error: ENOENT: no such file or directory, open '/home/prakashp/.config/Mattermost/certificate.json'
at Error (native)
at Object.fs.openSync (fs.js:634:18)
at Object.module.(anonymous function) as openSync
at Object.fs.readFileSync (fs.js:502:33)
at Object.fs.readFileSync (ELECTRON_ASAR.js:426:29)
at new CertificateStore (/home/prakashp/mattermost/resources/app/main.js:3771:32)
at Object.load (/home/prakashp/mattermost/resources/app/main.js:3801:13)
at Object. (/home/prakashp/mattermost/resources/app/main.js:85:49)
at webpack_require (/home/prakashp/mattermost/resources/app/main.js:20:30)
at webpack_require.app.app (/home/prakashp/mattermost/resources/app/main.js:40:18)
errno: -2,
code: 'ENOENT',
syscall: 'open',
path: '/home/prakashp/.config/Mattermost/certificate.json' }

**Comment by prakashprabhakar** [comment]
I am sorry. There is a misreporting from my end.

The option "Change team from Light to Dark." is no more visible. And the option in place of it is working fine.

Menubar icon is coming. But refer the below screenshot for the issue.

![mattermost](https://cloud.githubusercontent.com/assets/13349934/16981769/c42ceb0e-4e89-11e6-9ce5-7e71d5c4e7df.png)

Other issues remain same.

**Comment by Razzeee** [comment]
Top right should be fine

**Comment by jasonblais** [comment]
Thanks @prakashprabhakar for the report!

It is expected that only a red dot appears for mentions in the notifications area; a blue dot should appear for unread messages. This is because the number would be too small in the notifications area, and therefore we've used two separate colours for differentiation.

I've updated the issue title to `Taskbar icon is missing Mattermost logo on Ubuntu Linux` as that is certainly a bug. Thanks for reporting it!

**Comment by prakashprabhakar** [comment]
@jasonblais Thanks for the reply. Red dot is appearing. But I have not seen a blue dot. Will confirm to you on that.

Also one more thing that I observed is that mattermost is not appearing in Ubuntu applications list to users that I have installed EXCEPT me.

**Comment by jnugh** [comment]
How did you install the application? Your search results show 2 deb packages and a folder called mattermost.
I'm actually not sure if we create a desktop file or something similar when running non-deb packages...

**Comment by prakashprabhakar** [comment]
@jnugh There was no deb packages this time. I downloaded, extracted and double clicked on "Mattermost" executable. 

You can ignore the search results. Those are old installation packages.

Moreover I was wondering as to why the .deb installation was removed.

**Comment by jnugh** [comment]
Did you remove the deb version?
Do you have a file called `/usr/share/applications/Mattermost.desktop?`
Or maybe something similar in `/home/[yourusername]/.local/share/applications/Mattermost.desktop`

**Comment by prakashprabhakar** [comment]
@jnugh 

Yes I removed the deb version as it was 1.2.1.

Yes it's there. Here is the entry:

[Desktop Entry]
Encoding=UTF-8
Version=1.0
Type=Application
Name=Mattermost
Icon=application-default-icon
Path=/home/prakashp
Exec=/home/prakashp/mattermost/Mattermost
StartupNotify=false
StartupWMClass=Mattermost
OnlyShowIn=Unity;
X-UnityGenerated=true

**Comment by jnugh** [comment]
This is located in your `/home/` folder, right?
My desktop file has a different Icon name, but I didn't remove the deb package and therefore have a desktop file in `/usr/share/...` `application-default-icon` maybe we don't set the icon in the unpackaged version?

**Comment by prakashprabhakar** [comment]
@jnugh Yes in the unpackaged version it is not being set. But have a doubt when it comes to Fedora as I think I saw an icon with a proper logo. Like for example in Intellij they set the icon when the user runs the sh file for the first time. See the attached snapshot.

![selection_013](https://cloud.githubusercontent.com/assets/13349934/17211553/bfb8dc40-54e7-11e6-8f0f-ad551e4bef60.png)

**Comment by prakashprabhakar** [comment]
@jnugh Also I feel that a deb package should be given as upgrading becomes a problem when there are large number of systems... If it part of the ubuntu software system then it's easy to upgrade. @jasonblais

**Comment by yuya-oc** [comment]
Tested on Ubuntu 16.04/GNOME. The icon appears so it seems the issue depends on desktop environment.

<img width="512" alt="ubuntu1604_gnome" src="https://cloud.githubusercontent.com/assets/1412057/17892365/da2fa43e-697b-11e6-8202-ed3757d5f317.png">

**Comment by jnugh** [comment]
The icon is defined by the .desktop file in gnome and Ubuntu. Maybe due to switching install locations? deb -> tar?

**Comment by yuya-oc** [comment]
I removed deb package before testing, and used tarball. So I think there is no .desktop file. The icon was missing when validated with Unity in same machine.

**Comment by yuya-oc** [comment]
Ah, that's correct. The reason is whether .deb is installed. As a workaround, you can download `resources/icon.png` and use its full path at `Icon` parameter in the .desktop file.

Here is the `/usr/share/applications/Mattermost.desktop` installed by the .deb package.

```
[Desktop Entry]
Name=Mattermost
Comment=Mattermost Desktop application for Windows, Mac and Linux
Exec="/opt/Mattermost/Mattermost"
Terminal=false
Type=Application
Icon=mattermost-desktop
```

The icons are installed under `/usr/share/icons/hicolor/[size]/apps/mattermost-desktop.png`. So it seems the .desktop file refers the icons by specifying `mattermost-desktop`. But sure there are no icons there when .deb is not installed, so .desktop file have to use the full path of the icon.

This is Unity's description. I'm not sure why `/usr/share/icons` is also found.

https://help.ubuntu.com/community/UnityLaunchersAndDesktopFiles#Adding_shortcuts_to_a_launcher
> Icon field is the icon that should be used by the launcher and represents the application. All icons that are under the directory /usr/share/pixmaps don't need to have their full path specified, but their filename without the extension. For example, if the icon file is /usr/share/pixmaps/wallch.png, then the Icon field should be just 'wallch'. All other icons should have their full path specified.

**Comment by yuya-oc** [comment]
I added a script to create .desktop file. Artifacts are available at https://circleci.com/gh/mattermost/desktop/635#artifacts
