### ISSUE TITLE
Automatically add https:// or http:// to Server URL

### ISSUE THREAD

**Issue by besendorf** [mattermost/desktop#2083]
It would help UX a lot when mattermost-desktop would probe the domain automatically if it supports https:// and adds it to the URL and only use http:// if it fails.
![image](https://user-images.githubusercontent.com/26350155/166426110-75cd79c2-d7be-4764-b36c-193185ebc4dd.png)

**Comment by larkox** [comment]
@besendorf Not sure if that url is real or not, but you may want to "censor" it if it is real. These issues are public for everyone to see.
