### ISSUE TITLE
Gustom Groups is'n working

### ISSUE THREAD

**Issue by woodman733** [mattermost/desktop#2084]
I confirm (by marking "x" in the [ ] below: [x]):

- [x ] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [ x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
I have enabled feature  https://docs.mattermost.com/welcome/manage-custom-groups.html
in my server config 

cat config/config.json | grep EnableCustomGroups
"EnableCustomGroups": true

But where is no such functional in desktop-app GUI (mac/win) and web-app gui too. 
Is this feature still in development?
-->

**Environment**
- Operating System: macos Big Sur/windows 10
- Mattermost Desktop App version: 5.1.0-rc4
- Mattermost Server version: 6.6.0 (ubuntu 20.04)

**Comment by amyblais** [comment]
@woodman733 Custom Groups is only available on Professional and Enterprise licenses. What license do you currently have?

**Comment by woodman733** [comment]
@amyblais also can you told me please why at this doc-source https://docs.mattermost.com/welcome/manage-custom-groups.html talking about availability custom-groups feature for Enterprise, Professional, Cloud and Self-hosted editions?
![image](https://user-images.githubusercontent.com/25365844/166453940-78c47e1d-8cb5-4e87-90c1-5d4bec23c4bb.png)

**Comment by JtheBAB** [comment]
That means it is available for Enterprise and Professional on Cloud (by Mattermost) and Self-hosted deployments. 
Price for professional is $10 USD per user/month
