### ISSUE TITLE
URL preview-on-hover not visible when window is maximized

### ISSUE THREAD

**Issue by plwalsh** [mattermost/desktop#2086]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] I have confirmed this is an issue on the newest beta build [available here](https://github.com/mattermost/desktop/tags)
- [x] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

When the app window is maximized and when hovering the mouse over a hyperlinked URL, the pop-up along the bottom left-hand edge is not fully visible; only a few pixels-worth of the top edge can be seen.

When the app window is not maximized, the pop-up is fully visible as expected.

**Environment**
- Operating System: Windows 10
- Mattermost Desktop App version: 5.1.0-nightly.20220505 commit: 19a075f8
- Mattermost Server version: Team Edition 5.37.6

**Steps to reproduce**

1. Maximize the app window.
2. View a message that contains a hyperlinked URL.
3. Hover the mouse over the hyperlink without clicking.

**Expected behavior**

The destination URL of the hyperlink should pop up and be visible along the bottom left-hand edge of the window.

**Observed behavior**

The pop-up is partially visible, with only a few pixels of the top edge in view.

![mmdt_url_hover](https://user-images.githubusercontent.com/43576448/167009888-528eddfb-45ef-45c8-9bed-e766c620a801.png)

In the screenshot above, the thin white line just above the taskbar is the URL pop-up while my mouse is hovered over the hyperlink. The window is not behind my taskbar; it is simply maximized. I even tested moving my taskbar to the top of my screen, and the issue remained. If I un-maximize my window, however, the pop-up becomes fully visible.

**Comment by amyblais** [comment]
@jgilliam17 Are you able to reproduce this? cc @devinbinnie

**Comment by devinbinnie** [comment]
@amyblais I can reproduce yes, will create a ticket.
