### ISSUE TITLE
Custom Emoji do not appear properly on Windows and OS X

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#209]
I confirm (by marking "x" in the [ ] below): 
- [X] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [X This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [X] This is a product defect issue that can be reproduced using the steps listed below.
- [X] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---
#### Summary

Custom Emoji do not appear properly on Windows and OS X
#### Steps to reproduce
1. Create custom emoji from **Main Menu** > **Custom Emoji**, named `:emoji:`
2. Type `:emoji:` in Town Square.
3. Logout from your team
4. Log back in to your team

**Observed:**
- Step 2: `:emoji:` rendered as an image
- Step 4: `:emoji:` renders as text. The user must go to **Main Menu** > **Custom Emoji**, then back to Town Square for the custom emoji to render as an image.

**Expected:** `:emoji:` renders as an image in both steps 2 and 4.

Reproduced on
- Mattermost v3.2
- Windows 10 Desktop v1.2.1 
- Mac OS X Desktop v.1.3.0

**Comment by jasonblais** [comment]
Wondering if anyone would be able to help investigate this issue?

**Comment by jasonblais** [comment]
@jnugh has offered to help investigate the issue and whether it is related to #212 and #213 -- big thanks!

**Comment by yuya-oc** [comment]
Reproduced in Chrome(Windows 10), and reloading solved this. So it seems that it's definitely caused by cache handling.

**Comment by jnugh** [comment]
Yes, no cache control or expires header. Cache will be invalidated by chance only. 
My pr does a reload as a workaround...

**Comment by jasonblais** [comment]
I have a team site where Custom Emoji didn't work with Mattermost Server v3.2 (Windows 10) and tried to clear cache and reload without success.

They only appeared after going to **Main Menu > Custom Emoji**, and it appears to happen sporadically when I launch the app (not consistently every time).

This is also what a few others have reported. So it might not be fixed with #219

**Comment by jnugh** [comment]
*IF* this is related to a cache hit, #219 should fix it. But it might also be something totally different we didn't think of.

Did you test the 219 build to see if it makes a difference?

**Comment by jasonblais** [comment]
Yeah, to clarify, it appears it might be partially related to a caching problem (since some people get it fixed after clearing cache and reloading), but not fully. 

So we should try and investigate what else might be causing the problem, in addition to submitting #219. Something in the Desktop App requires the user to display the list of custom emoji before they appear in messages.

**Comment by jasonblais** [comment]
There is a custom emoji loading issue also reported on the server side, so might not be a desktop-specific problem. https://github.com/mattermost/platform/issues/3700

Will update once there is more information.

**Comment by jasonblais** [comment]
A ticket in [platform Jira](https://mattermost.atlassian.net/browse/PLT-3805) added to investigate whether this is a server side problem

**Comment by jasonblais** [comment]
The issue was identified to be on the server side, fixed [with this Jira ticket](https://mattermost.atlassian.net/browse/PLT-3805) for MM server v3.4.

If anyone still experiences issues with MM server v3.4 or later, please let us know.

**Comment by polepoe** [comment]
The issue still occur with Matter Most 3.5.1, I'm install Matter Most on a Debian 8 server, the custom emoji only appear after I go to the "Custom Emoji" menu and go back to "Team chat".

**Comment by jasonblais** [comment]
Thanks @polepoe  for the report -- are you able to reproduce it on a browser?

**Comment by polepoe** [comment]
Yes I'm using Chrome Version 55.0.2883.87 m (64-bit) on a Windows 10 PC. The issue can be proc on the same as @jasonblais instruction:

Steps to reproduce:
1. Create custom emoji from Main Menu > Custom Emoji, named :emoji:
2. Type :emoji: in Town Square.
3. Logout from your team
4. Log back in to your team

The only fix is that you go to the "Custom Emoji" menu and click back to "Team chat". Do you want to try it on my server?

**Comment by polepoe** [comment]
First entering the site:
![image](https://cloud.githubusercontent.com/assets/24849795/21600213/4e78fd94-d1ab-11e6-878c-0d2cd052fae2.png)
After go back from "Custom Emoji" menu:
![image](https://cloud.githubusercontent.com/assets/24849795/21600229/6af30032-d1ab-11e6-9fac-98d5ad389ca1.png)

**Comment by polepoe** [comment]
I think my log trying to tell me something
VM157:35 Mixed Content: The page at 'https://undertale.club/undertalevn/channels/town-square' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://undertale.club/api/v3/users/websocket'. This endpoint should be available via WSS. Insecure access is deprecated.
When i click the shield guard and allow content i can see the emoji again :|

**Comment by yuya-oc** [comment]
As far as reading the message, I feel that there is something wrong in the server configuration.

**Comment by polepoe** [comment]
I did follow the exact https://docs.mattermost.com/guides/administrator.html#deployment
Here is the nginx configuration file (follow the SSL config of the guide):
```
#http
server {
   listen         80;
   server_name    undertale.club;
   return         301 https://$server_name$request_uri;
}
#https 
server {
   listen 443 ssl;
   #hostname to respond to
   server_name undertale.club;
   #ssl configuration
   ssl on;
   ssl_certificate /etc/letsencrypt/live/undertale.club/fullchain.pem;
   ssl_certificate_key /etc/letsencrypt/live/undertale.club/privkey.pem;
   ssl_session_timeout 5m;
   ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
   ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
   ssl_prefer_server_ciphers on;
   ssl_session_cache shared:SSL:10m;

   location / {      
	  #uncompress site
	  gzip off;
	  #switch off logging
	  access_log off;
	  
	  #redirect all http traffic to ip:8065
	  proxy_pass http://45.32.116.162:8065;
	  proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-Ssl on;
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Frame-Options SAMEORIGIN;
      
	  client_max_body_size 50M;
	  
	  #websocket support
	  proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
   }
   
 
}
```

Thanks if you help me figure out what is the problem here :D

**Comment by polepoe** [comment]
Okay I got this fixed by changing:
**http**://abc.xyz to **https**://abc.xyz
In **System Console -> Setting -> Configuration**
This is a configuration errors. I think you guys should closed this issue from now on.
Sorry for the bothering :).
Thanks!

**Comment by jasonblais** [comment]
Glad the error was found @polepoe! 

Would you like to submit a PR to update the Debian guides? Or would you have a suggestion for improving it so someone on our team can go and update it?

**Comment by yuya-oc** [comment]
@jasonblais I think that the nginx configuration for `location /api/v3/users/websocket` is missing in the Debian guide. Both of Ubuntu 14.04 and 16.04 guides have the configuration.

**Comment by polepoe** [comment]
I'll try to update the guide with my case (Debian 8) and I'll send them to http://forum.mattermost.org/ (I'll add the link later here) and may be I'll do a Vietnamese video tutorial for our little self-hosted community as well.
Thanks for your concern, keep up the good work!

**Comment by jasonblais** [comment]
I think `location /api/v3/users/websocket` is just for optimal performance, but shouldn't cause these issues..

They weren't added for the other docs, since the optimal configuration has been tested in Ubuntu only so far

**Comment by jasonblais** [comment]
Yes @polepoe that would be great! Feel free to submit the update in https://github.com/mattermost/docs as well, if you'd like. 

Would love to see a video tutorial too, our community would appreciate that! 

If you're interested, feel free to join our public community instance at [pre-release.mattermost.com](https://pre-release.mattermost.com/signup_user_complete/?id=f1924a8db44ff3bb41c96424cdc20676) to meet other contributors and ask any questions from the Mattermost core team. Would love to see you there :)
