### ISSUE TITLE
Deleted post persists on Desktop app (Windows 10)

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#210]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [X] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [X] This is a product defect issue that can be reproduced using the steps listed below.
- [X] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

Deleted post persists on Desktop app

#### Steps to reproduce

1. Make a post with an attached image
2. Edit the post text and Save
3. Open reply on another message in that channel, but don't reply
4. Attempt to delete the post in step 1

#### Expected behavior

Deleted post deleted

#### Observed behavior

Deleted post does not appear deleted

#### Possible fixes

Uncertain

**Comment by jasonblais** [comment]
The above has so far being reproduced on Windows 10, but not [on Windows 7](https://pre-release.mattermost.com/core/pl/tsnwnkrphjrgpnti7qfikbgztr).

Would anyone be able to take a look what might be the cause?

Also, anyone able to reproduce this issue on OS X?

**Comment by yuya-oc** [comment]
@jasonblais Not reproduced on Windows 10, `(message deleted)` appears after deleting. Does it happen in Chrome?

**Comment by jasonblais** [comment]
I'm actually able to reproduce this on the browser too - platform team will fix since it's an issue on the server side.

**Comment by jasonblais** [comment]
Closing since doesn't apply to the desktop app
