### ISSUE TITLE
`hideOnStart` is not working

### ISSUE THREAD

**Issue by AKorezin** [mattermost/desktop#2109]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Hide on start options was reintroduced in client by #1919.
But it doesn't work as expected, because it does nothing.

**Environment**
- Operating System: `linux`.
- Mattermost Desktop App version: `5.1.0` also `master`.
- Mattermost Server version: `6.5.0`.

**Steps to reproduce**
1. Start desktop client;
2. open settings;
3. check *hide on start*;
4. terminate client;
5. open client once more.

For `master` branch
1. `npm ci`;
2. `npm run watch`;
3. open settings;
4. check *hide on start*;
5. make client restart.

**Expected behavior**
Client window should not show at all at start.

**Observed behavior**
Client window stays up even if *hide on start* option is checked.

**Possible fixes**

* Previously this handled by show and then instant hide. So it can look like.
  ```patch
  --- a/src/main/windows/mainWindow.ts
  +++ b/src/main/windows/mainWindow.ts
  @@ -121,14 +122,17 @@
               if (windowIsMaximized) {
                   mainWindow.maximize();
               }
  +        } else {
  +                mainWindow.hide();
           }
       });
  ```
* Prevent `show()` if window is not yet ready.
  ```patch
  --- a/src/main/windows/windowManager.ts
  +++ b/src/main/windows/windowManager.ts
  @@ -101,6 +102,9 @@
           log.debug('WindowManager.showMainWindow', deeplinkingURL);

           if (this.mainWindow) {
  +            if (!this.mainWindowReady && Config.hideOnStart) {
  +                return;
  +            }
               if (this.mainWindow.isVisible()) {
                   this.mainWindow.focus();
               } else {
  ```
* Find out why `showMainWindow()` was called during startup sequence.
  Concretely this problem is caused by https://github.com/mattermost/desktop/blob/2e740d60bd55c409e756166ff414696d6449fa8e/src/main/app/config.ts#L36

**Additionally**
* Useless show
  https://github.com/mattermost/desktop/blob/2e740d60bd55c409e756166ff414696d6449fa8e/src/main/windows/mainWindow.ts#L127-L129
* Double blur
  https://github.com/mattermost/desktop/blob/2e740d60bd55c409e756166ff414696d6449fa8e/src/main/windows/mainWindow.ts#L140-L142
  https://github.com/mattermost/desktop/blob/2e740d60bd55c409e756166ff414696d6449fa8e/src/main/windows/mainWindow.ts#L231-L233

**Comment by amyblais** [comment]
@devinbinnie @jgilliam17 Are you able to reproduce this?

**Comment by devinbinnie** [comment]
@amyblais Yeah I can, created a ticket: https://mattermost.atlassian.net/browse/MM-44339

**Comment by AKorezin** [comment]
Find another case
If *Show icon in the notification area* is disabled and *Launch app minimized* is enabled then there's no way you can show the app.

Should I create a new issue?

**Comment by devinbinnie** [comment]
That case depends on whether your Linux distro supports a tray icon (via something like `libappindicator`). There's no way we can detect whether it does or not, so we decided to just allow the app to open as such.

**Comment by AKorezin** [comment]
So it's not possible to make *Launch app minimized* checkbox work like *Leave app running in notification area when application window is closed*?

**Comment by devinbinnie** [comment]
It is, but you need to have `libappindicator` running on your system, which will give you a 'Windows-like' system tray. Some other distributions have a 'Mac-like' dock that should also work the same way.
