### ISSUE TITLE
Custom emoji not applied on macOS.

### ISSUE THREAD

**Issue by jingookim** [mattermost/desktop#211]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [ ] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [x] This is a product defect issue that can be reproduced using the steps listed below.
- [ ] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

Custom emoji not applied on macOS.

#### Steps to reproduce

Please include: 
- Operating System : OS X El Capitan 10.11.5 (Client)
- Mattermost Desktop App version (See File > About Mattermost) : 1.3.0
- Mattermost Server version (See Main Menu > About Mattermost) : 3.2.0 (Matermost Enterprise Editon) - Ubuntu 12.04
- Clear steps to reproduce the issue

#### Expected behavior

I had to add custom emoji on the server.

and I had to clear the cache. (Ctrl + R or Shift + Ctrl + R)

But, Custom Emoji was not applied (However, Windows users, was applied.)

also, webbrowser was applied, only macOS not appiled.

#### Observed behavior

What did you see happen? Please include relevant error messages and/or screenshots.
macOS client view
![image](https://cloud.githubusercontent.com/assets/5326115/17008859/3861fa18-4f30-11e6-80e0-52cf377d9f03.png)

windows client view
![image](https://cloud.githubusercontent.com/assets/5326115/17008844/1f75930c-4f30-11e6-8330-6e96ed52e8dc.png)

#### Possible fixes

If you can, link to the line of code that might be responsible for the problem.

**Comment by jasonblais** [comment]
Thanks for the report @jingookim, does [this issue](https://github.com/mattermost/desktop/issues/209) appear to apply to your use case?

If you go to **Main Menu > Custom Emoji** (which opens a list of created custom emoji), then back to Town Square, does the custom emoji appear properly as an image?

**Comment by jingookim** [comment]
Oh, I was go the Custom emoji option. and back to channel. So, Now I will see the custom emoji.
Thank you.

**Comment by jasonblais** [comment]
Perfect, thanks @jingookim! 

That is still an issue that needs to be fixed, but we'll take care of it through #209
