### ISSUE TITLE
Release missing

### ISSUE THREAD

**Issue by elandorr** [mattermost/desktop#2112]
The 'Windows - zip files' portable releases are missing since [v5.1.0-rc.3](https://github.com/mattermost/desktop/releases/tag/v5.1.0-rc.3).

**Comment by devinbinnie** [comment]
We have cut the Windows ZIP files from future releases, since they do not support the autoupdater correctly. Sorry for the inconvenience.

**Comment by elandorr** [comment]
Please reconsider. All our Windows users use the portable and are updated centrally - we don't need autoupdate. Portables are of great value and easiest to maintain/move.

**Comment by devinbinnie** [comment]
We can look into providing ZIPs with the autoupdater cut.
Created a ticket: https://mattermost.atlassian.net/browse/MM-44344

**Comment by elandorr** [comment]
Thank you @devinbinnie.

**Comment by tech189** [comment]
The [Scoop package](https://github.com/ScoopInstaller/Extras/blob/master/bucket/mattermost.json) is also out of date for this reason. It relies on extracting the portable zip to install. It doesn't require autoupdater either as the user can run `scoop update *` to update their apps.
