### ISSUE TITLE
Mattermost Desktop app (5.10) on Osx 12.3.1 Monterey - Permanent White Screen when reopening the app in an archived channel

### ISSUE THREAD

**Issue by SimonHaenle2** [mattermost/desktop#2116]
I confirm (by marking "x" in the [ ] below: [x]):

- [ x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Mattermost Desktop app version 5.10 goes into a white screen after launching. Reinstalling and clear caches does not help. I was able to narrow down the issue. It has to do with archived channels. When you close the app in an archived channel and reopen it, it will hang up with a white screen. Colleagues of mine also had this issue multiple times.

**Environment**
- Operating System: Mac Os Monterey 12.3.1
- Mattermost Desktop App version: 5.10
- Mattermost Server version: 5.1.0.19939

**Steps to reproduce**
1. Go into a channel
2. Archive the channel
3. Close the mattermost app
4. Reopen the mattermost app

**Expected behavior**
App works

**Observed behavior**
App goes into white screen

![Bildschirmfoto 2022-05-19 um 08 59 37](https://user-images.githubusercontent.com/13623663/169230274-3b5b0709-5aef-4f2f-9164-02cb66d1d64d.png)

**Comment by devinbinnie** [comment]
@SimonHaenle2 Can you post the log from the Developer Tools window when this happens? You can access it by going to View > Developer Tools for Current Server

**Comment by SimonHaenle2** [comment]
Unfortunately I only have those 2 options
![Bildschirmfoto 2022-05-19 um 15 59 50](https://user-images.githubusercontent.com/13623663/169311585-fe2762f5-6f93-4b3c-8c52-740e7bf0f135.png)

**Comment by SimonHaenle2** [comment]
Tried to reproduce it but couldn't :/. I was able to fix it by changing the the server url directly to an unarchived channel since then I can't repro it unfortunately

**Comment by SimonHaenle2** [comment]
It seems this is related to a plugin.
