### ISSUE TITLE
5.1.0 - no multi user session support

### ISSUE THREAD

**Issue by JtheBAB** [mattermost/desktop#2117]
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Unable to launch Mattermost Desktop 5.1.0 on a Windows multi user system (Remote Desktop Session Host / Citrix Virtual Desktop)

**Environment**
- Operating System: Windows Server 2019
- Mattermost Desktop App version: 5.1.0

**Steps to reproduce**
- Install 5.1.0 on a RemoteDesktop Session Host
- Login with User A
- Start Mattermost Desktop 5.1.0
- It's starting
- Login with User B and User A stays loggedin
- Start Mattermost Desktop 5.1.0
- Nothing happen

**Expected behavior**

Mattermost Desktop starts also for User B

**Observed behavior**

Doesn't start. No error nothing.

**Possible fixes**

I don't think it is really related to the app itself. Its a electron issue as i heard that is also the case with the Slack App.

**Comment by JtheBAB** [comment]
Open a bug report also at [electron repo](https://github.com/electron/electron/issues/34281)

**Comment by devinbinnie** [comment]
Thanks @JtheBAB, we'll monitor the bug in Electron and do a dot release or something once the bug is resolved on their side.

**Comment by devinbinnie** [comment]
@JtheBAB Perfect! I'll make a patch.
