### ISSUE TITLE
Automatically clear the cache and reload the desktop app upon upgrade to a new Mattermost server version

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#212]
Propose looking into something on desktop that remembers the version number of the Mattermost server for each tab, and if that version number changes force a "Clear Cache and Reload"? 

Lots of community and customers have had trouble upgrading properly to the new Mattermost server due to caching issues on the desktop.

**Comment by yuya-oc** [comment]
Is there any way to check server's version?
