### ISSUE TITLE
5.1.0 - Cannot connect to Mattermost

### ISSUE THREAD

**Issue by gabrielctn** [mattermost/desktop#2121]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Unable to connect to Mattermost server.

**Environment**
- Operating System: macOS 12.4 (Monterey) on Apple M1
- Mattermost Desktop App version: 5.1.0 (5.1.0.19939)
- Mattermost Server version: 6.7.0

**Steps to reproduce**
Install Mattermost 5.1.0 via AppStore or via https://releases.mattermost.com/desktop/5.1.0/mattermost-desktop-5.1.0-mac-universal.dmg

**Expected behavior**
Connect and load Mattermost interface

**Observed behavior**

<img width="763" alt="Capture d’écran 2022-05-23 à 15 31 47" src="https://user-images.githubusercontent.com/25644865/169833385-a54f9b8f-1d88-495d-a8c1-06051b0add2a.png">

This issue does not occur on Browser version, and I confirm that the issue appeared only from 5.1.0. The version 5.0.4 worked perfectly.

**Comment by amyblais** [comment]
@gabrielctn Are you able to connect to our community server https://community.mattermost.com/?
Do you see any errors in the browser console or Mattermost server logs?

**Comment by gabrielctn** [comment]
Yes I have an account on the community server. Should I continue on the server chat ?  
This is the errors that occur in the devtools
![image](https://user-images.githubusercontent.com/25644865/169873306-6b2a3312-bd39-46ec-b706-b0ec583b1061.png)

**Comment by devinbinnie** [comment]
@gabrielctn Looking at the console logs it looks like the server is connecting properly and the react app is loading. Do you still see the `Cannot connect to Mattermost` screen? If so, do you see a loading screen with a spinner when the app loads?

**Comment by gabrielctn** [comment]
When I open the app, I get the spinner for ~15-20 seconds, and then the `Cannot connect to Mattermost` page.

**Comment by gabrielctn** [comment]
Sometimes (rarely), it somehow manages to connect to the server for few moments, I have the time to log in, and then it loses the connection to websocket. It seems to happen juste after the message `registering Mattermost v5.1.0 with the server` in the logs.
![image](https://user-images.githubusercontent.com/25644865/170062026-1e40c0fd-04d8-4e17-9b0c-cc945d0b20fd.png)

**Comment by devinbinnie** [comment]
Seems as though the connection to the server is unreliable at first glance. If you would, could you turn on debug logging in the Settings window and then restart your app? You can then find logs under `/Users/<username>/Library/Containers/Mattermost/Data/Library/Logs/Mattermost`

**Comment by gabrielctn** [comment]
I found the logs but didn't see anything relevant inside. I did a `docker-compose restart` on the web server for another reason, and since then it seems to work fine. No more websocket issue !
I have no idea why the restart was necessary but it seems to have made the trick !
Thanks for your help.
