### ISSUE TITLE
History shortcuts changed on italian layout.

### ISSUE THREAD

**Issue by superandrew** [mattermost/desktop#2123]
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

Starting from version 5.1.0 the keyboard shortcuts for history have changed in a non consistent way.
Before 5.1.0 (up to 5.0.4) the shortcut was "CMD+[" and "CMD+]" which in an italian keyboard were consistent.

In version 5.1.0 the shortcut is mapped tp "CMD+ò" and "CMD+à" which, honestly does not make any sense. There is also no way to change that behaviour, to my knowledge

**Environment**
- Operating System:
- Mattermost Desktop App version: 5.1.0 
- Mattermost Server version: not relevant

**Steps to reproduce**
navigate throgh channels, trying to use the shortcuts you know, with an italian keyboard
**Expected behavior**
shortcuts work
**Observed behavior**
shortcuts are changed

**Possible fixes**

**Comment by superandrew** [comment]
update: I guess the change happened in electron and not in mattermost, as also slack shows the same behaviour
<img width="135" alt="CleanShot 2022-05-25 at 10 43 20@2x" src="https://user-images.githubusercontent.com/71364/170221608-75aed60a-9d3f-4a62-b3b2-91145ebc74c9.png">
 
<img width="131" alt="CleanShot 2022-05-25 at 10 43 01@2x" src="https://user-images.githubusercontent.com/71364/170221600-77db643d-08e3-4c67-8e4c-801598c2edf8.png">

**Comment by superandrew** [comment]
reported issue here https://github.com/electron/electron/issues/34347

**Comment by devinbinnie** [comment]
@superandrew Looks like the upstream issue was closed due to inactivity, is this still an issue for you?

**Comment by superandrew** [comment]
no, the problem was fixed a few days later. Thanks
