### ISSUE TITLE
5.1.0 Client on MacOS - can't use mouse in filedialog

### ISSUE THREAD

**Issue by martinkouba** [mattermost/desktop#2127]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
When an action opens a finder dialog, the dialog can only be controlled using the keyboard. Mouse events are not registered.

**Environment**
- Operating System: MacOS Monterey
- Mattermost Desktop App version: 5.1.0
- Mattermost Server version: 6.7.0

**Steps to reproduce**
Try to upload an image in a chat or try to export the archive of a board.
A file dialog appears to choose a file to upload or save the export to.

**Expected behavior**
It should be possible to navigate using the mouse or the keyboard

**Observed behavior**
Only keyboard events are registered. Mouse can not be used. The dialog can be confirmed using ENTER or closed using ESC

**Possible fixes**

**Comment by amyblais** [comment]
I wasn't able to reproduce this now, maybe @jgilliam17 can test if she can reproduce.

**Comment by devinbinnie** [comment]
I'm also unable to reproduce.

**Comment by martinkouba** [comment]
I don't know if this would make any difference, but I did install Mattermost via App Store. This was recently after switching to a new Mac. I didn't move my profile. So it was a fresh Mattermost install from App Store.
The symptom doesn't appear to be linked to server version. I have only upgraded from 6.0 to latest today, and the behaviour already was like that before.

**Comment by martinkouba** [comment]
It might be a Monterey Bug. I have just seen the same behavior in another setting

**Comment by martinkouba** [comment]
It definitely was related to MacOS. I am closing this
