### ISSUE TITLE
"Clear Cache and Reload" may not work properly, as it only clears the cache of the React app

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#213]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [X] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [X] This is a product defect issue that can be reproduced using the steps listed below.
- [X] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

"Clear Cache and Reload" may not work properly, as it only clears the cache of the React app, which would not include webviews.

We've had several members in the community reporting problems and having to reload the cache multiple times across our platforms.

A related ticket to automate the 'clear cache and reload' upon Mattermost upgrade was created in #212.

**Comment by yuya-oc** [comment]
I have modified the way to reload. https://circleci.com/gh/mattermost/desktop/529#artifacts
It directly calls `clearCache()` of webview, so it might be better.

And it only refreshes the inside of the current tab and keep its URL. As the result, this would also improves about #223.

**Comment by mmahkamov** [comment]
Tried on OSX 10.11.
Before the fix (1.3.0 release): The entire page is reloaded, currently open channel is not restored
After the fix: The entire page is reloaded, currently open channel is restored

**Comment by jasonblais** [comment]
Fantastic, thanks @mmahkamov! 

@yuya-oc I think we're ready to merge this

**Comment by jasonblais** [comment]
By the way, @mmahkamov, we also have a [Desktop App discussion channel](https://pre-release.mattermost.com/core/channels/desktop) where the community discusses and prioritizes issues and new features.

Would love to see you there :)

**Comment by yuya-oc** [comment]
Thanks!
