### ISSUE TITLE
error when installing deb 5.1.0  on ubuntu ->Package gconf2 is not installed

### ISSUE THREAD

**Issue by tmotyl** [mattermost/desktop#2135]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Installing mattermost-desktop from deb file crashes on Ubuntu 21.10 because of the missing gconf2  dependency

**Environment**
- Operating System: Ubuntu 21.10
- Mattermost Desktop App version: 5.1.0 
- Mattermost Server version: X.X.X 

**Steps to reproduce**

**Expected behavior**

**Observed behavior**

```
sudo dpkg -i mattermost-desktop_5.1.0-1_amd64.deb 
Selecting previously unselected package mattermost-desktop.
(Reading database ... 212399 files and directories currently installed.)
Preparing to unpack mattermost-desktop_5.1.0-1_amd64.deb ...
Unpacking mattermost-desktop (5.1.0-19940) ...
dpkg: dependency problems prevent configuration of mattermost-desktop:
 mattermost-desktop depends on gconf2; however:
  Package gconf2 is not installed.
 mattermost-desktop depends on gconf-service; however:
  Package gconf-service is not installed.

dpkg: error processing package mattermost-desktop (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for mailcap (3.69ubuntu1) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Errors were encountered while processing:
 mattermost-desktop
```

**Possible fixes**

**Comment by devinbinnie** [comment]
@tmotyl Normally the procedure here would be to install `gconf2` and `gconf-service` yourself.
You can do this with `sudo apt-get install gconf2 gconf-service`.

Note: if you install our APT repository as described [here](https://docs.mattermost.com/install/desktop-app-install.html?highlight=desktop%20app#install-and-update-the-mattermost-desktop-app) it should install it automatically for you.

**Comment by tmotyl** [comment]
thanks @devinbinnie 
I went the APT way -> works great.
