### ISSUE TITLE
unwanted and unasked for network connections

### ISSUE THREAD

**Issue by elandorr** [mattermost/desktop#2137]
https://github.com/mattermost/desktop/releases/download/v5.0.4/mattermost-desktop-5.0.4-win-x64.zip
https://github.com/mattermost/desktop/releases/download/v5.0.4/mattermost-desktop-5.0.4-linux-x64.tar.gz
(but presumably with any recent version)

We naturally disable the enormous telemetry options server-side. It would follow that the client itself does not phone home either, especially not before even connecting to the server.

But it does.

I freshly deployed just now and noticed the network sniffer going wild on mattermost. I was confused, it was completely blank after all. Turns out on either platform MM creates a ton of connections to Google, AWS, and some random stuff I can't be bothered to dig out of the logs now.

**All before the user even has the chance to consent.**

Unasked for network connections are not okay.
![no consent](https://i.ibb.co/vwcRPVL/sniffing.gif)

**Comment by devinbinnie** [comment]
@elandorr Most of these connections are to retrieve assets such as fonts (eg. OpenSans is hosted by Google, so we pull it from them). It would be helpful to have a list of the connections you see and then we would be able to investigate further.

**Comment by vanilla-thunder** [comment]
whenever i navigate or post a message, mattermost client is sending telemetry data to https://pdat.matterlytics.com/v1/track
```json
{
  "channel": "web",
  "context": {
    "app": {
      "build": "1.0.0",
      "name": "RudderLabs JavaScript SDK",
      "namespace": "com.rudderlabs.javascript",
      "version": "1.0.16"
    },
    "traits": {},
    "library": {
      "name": "RudderLabs JavaScript SDK",
      "version": "1.0.16"
    },
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.160 Electron/18.3.0 Safari/537.36 Mattermost/5.1.1",
    "locale": "de",
    "os": {
      "name": "",
      "version": ""
    },
    "screen": {
      "density": 1.25
    },
    "campaign": {},
    "page": {
      "path": "",
      "referrer": "",
      "referring_domain": "",
      "search": "",
      "title": "",
      "url": ""
    },
    "ip": "0.0.0.0"
  },
  "type": "track",
  "messageId": "3431c7b2-9fa0-4e16-94dc-7f1840e40d5d",
  "originalTimestamp": "2022-07-08T09:22:37.538Z",
  "anonymousId": "00000000000000000000000000",
  "userId": "dyqoxe1hxjyui88mzzdq33pzyy",
  "event": "event",
  "properties": {
    "category": "api",
    "type": "api_posts_search",
    "user_actual_role": "system_user",
    "user_actual_id": "i8qa95mzftgh3pjbm9n6t57d4r",
    "team_id": "qbfo4ghpejgkfg7g54ejcx6xqe"
  },
  "integrations": {
    "All": true
  },
  "sentAt": "2022-07-08T09:22:37.538Z"
}
```
there is also my server url in request header.
I cound not find a setting to disable this telemetry yet.

**Comment by devinbinnie** [comment]
@vanilla-thunder Those are the aforementioned telemetry items that can only be disabled server-side. We don't actually have any desktop-specific telemetry yet, but will make sure to keep it in mind when we do eventually add it.
