### ISSUE TITLE
5.1.0 release not picked up by Autopkg

### ISSUE THREAD

**Issue by undulat** [mattermost/desktop#2138]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

5.1.0 release does not get picked up by Autopkg using the ygini-recipes download recipe because the name key in /releases does not contain the package name.

**Environment**
- Operating System: macOS
- Mattermost Desktop App version: 5.1.0

The autopkg ygini download recipe https://github.com/autopkg/ygini-recipes/blob/master/Mattermost/Mattermost.download.recipe uses the GitHubReleasesInfoProvider autopkg plugin to search for and download the latest release of Mattermost Desktop for Mac. The plugin in turns curls down github.com/mattermost/desktop/releases as json and searches for the regexp
mattermost-desktop-[0-9.]+-%os%-universal.dmg 
(we have added the -universal part) in the assets - > name key values. This has worked on previous version of Mattermost 5.x but it does not on 5.1.0 because the name key value no longer contains the package name but only "latest-mac". 

The expected behavior from the much used autopkg GitHubReleasesInfoProvider plugin https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/GitHubReleasesInfoProvider.py is that the name key value will contain the package name, to be used by the regexp for identifying the correct package to download. You break this with the 5.1.0 release.

**Comment by devinbinnie** [comment]
@undulat Is this due to the fact that the Assets section is missing the packages? We haven't changed anything else about the naming scheme (at least for the Mac release). If it's the assets missing that's the issue, I think we can look into fixing that.

**Comment by devinbinnie** [comment]
`latest-mac.yml` isn't one of the releases, it's the auto-update manifest. We have fixed the issue you've described here: https://github.com/mattermost/desktop/pull/2114
