### ISSUE TITLE
Mattermost Electron Steals Focus on new message

### ISSUE THREAD

**Issue by mtompkins** [mattermost/desktop#2147]
I confirm (by marking "x" in the [ ] below: [x]):

- [x ] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: Ubuntu 22.04
- Mattermost Desktop App version: 5.1.0
- Mattermost Server version: 6.7.0

Normal usage.

New messages should provide a notification in taskbar of new message, however the electron app should remain in current state of focus - either behind current active application(s) or in front if active application.

Descriptive:
MM Desktop steals focus and comes to foreground on any new message. If the user is in the process of typing in another application (e.g. creating an email), MM comes to the foreground and steals focus and typing results in MM.

**Comment by devinbinnie** [comment]
@mtompkins I believe this is the same issue as this one correct? https://github.com/mattermost/desktop/issues/1827

**Comment by mtompkins** [comment]
> @mtompkins I believe this is the same issue as this one correct? #1827

Apologies, *autoraise* was an unknown term to me. I would agree this is the same.
