### ISSUE TITLE
Too Many Gifs Will Cause The App To Show A Black Screen and Require a Refresh

### ISSUE THREAD

**Issue by eligundry** [mattermost/desktop#215]
I confirm (by marking "x" in the [ ] below): 
- [x] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [x] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [x] This is a product defect issue that can be reproduced using the steps listed below.
- [x] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---
#### Summary

We have a channel where only GIFs are posted and after a few weeks of running, navigating to the channel will cause the electron app to show a black screen and require a refresh.
#### Steps to reproduce
- OS: OS X
- Client: 1.2.1
- Server: 3.2.0
##### Steps:
1. Create a new channel
2. Post a lot of gifs (looking at the network inspector, this happens when the client attempts to load around ~600mb-1gb of GIFs at once)
3. Navigate away from the channel
4. Another user posts a GIF
5. Navigate back to channel
6. Channel will attempt to render for a sec and then throw up a black screen
7. Refresh app with CMD-R
8. Navigate back to channel and new GIFs will appear
9. Go back to step 3 and process will occur again

This will also happen if you attempt to load older messages which contain GIFs at once.
#### Expected behavior
- Mattermost would remove and add GIFs from the DOM as the user scrolls so the DOM doesn't get overloaded.
- Mattermost would remove older GIFs faster as new ones are posted so the DOM doesn't flip out
- As far as we can tell, the browser version of Mattermost doesn't have this issue, though it will render a white screen but recover eventually.
#### Observed behavior

[GIPHY GIF of what happens](http://i.giphy.com/l46CnbRXEjB4z5ES4.gif) (this was too big to host on Github)
#### Possible fixes

I know this is probably a tricky thing to fix, so I dunno how you'd go about this besides these pie in the sky fixes:
- Agressively removing older GIFs as the user scrolls?
- On the Mattermost server side, have a seperate Docker container running FFMPEG to convert all GIFs to GIFvs?

**Comment by jasonblais** [comment]
Thanks @eligundry for the report!

I will check with the Mattermost team on this and reply back with their thoughts.

**Comment by jasonblais** [comment]
A related issue was reported where the issue stems from an [excessive CPU usage of "Mattermost Helper"](https://github.com/mattermost/desktop/issues/222) when lots of GIFs appear on a page.

Would someone know if this is a problem with the desktop app, or something that would need to be fixed on the server side?

**Comment by eligundry** [comment]
@jasonblais I would say that this is on the Electron app in some way because doing the exact same thing on the actual web app in Chrome doesn't have this issue.

[GIF of that same channel in the web app not crashing](https://imgur.com/a/9JPRE)

**Comment by jasonblais** [comment]
Thanks for the update @eligundry! 

From #222, it appears `Mattermost Helper` is causing increased CPU usage, not sure if that's helpful information?

![image](https://cloud.githubusercontent.com/assets/13119842/17160643/78401bae-5374-11e6-93a4-2ff84a15d5bc.png)

**Comment by eligundry** [comment]
@jasonblais I just updated the client to 1.3.0 and it appears to have fixed the issue with our GIFs channel! Not only that, the GIFs load faster and the frame rate is noticeably higher when scrolling through it. I'll close this issue.

![Good job](http://i.giphy.com/3o85gdp4VhJE66NoNG.gif)

**Comment by jasonblais** [comment]
Great to hear! 

Thanks @eligundry for coming back, appreciate your help here!

**Comment by jasonblais** [comment]
Reopening as we've received reports that this issue still reproduces for users on Mac v1.3.0.

The performance is better than in v1.2, but we should consider options on how to improve performance in the long term.

**Comment by jasonblais** [comment]
I haven't heard reports of high CPU usage in a while + it's been fine on my end. Closing.
