### ISSUE TITLE
Infinite loading screen 

### ISSUE THREAD

**Issue by bghyt** [mattermost/desktop#2150]
I confirm (by marking "x" in the [ ] below: [x]):

- [x ] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [ x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: 11
- Mattermost Desktop App version: 5.1.0 
- Mattermost Server version: unable to get

**Steps to reproduce**
Open desktop app, screen has "loading ..."
**Expected behavior**
Login page
**Observed behavior**
few days ago I was abruptly logged out upon computer start & could not log in again, no page, no prompt.

**Possible fixes**

**Comment by bghyt** [comment]
I can see the log-in screen, I had tried that server previously but got the same result, It still occurs on the company's server.

**Comment by devinbinnie** [comment]
@bghyt Can you turn on Debug logging and post your log file? On Windows you can find it in `%APPDATA%/Roaming/Mattermost/logs`

**Comment by bghyt** [comment]
Sure, Note i've changed the name of the company to "COMPANYHERE" i've not made other changes I do not want this username associated with my workplace & community.
[main.log](https://github.com/mattermost/desktop/files/8894325/main.log)
.

**Comment by HighDef888** [comment]
I cannot use the app version, it infinitely loads and I cannot login. The web version works but I get no notifications and I need to keep my RAM without other stuff running.

**Comment by bghyt** [comment]
@devinbinnie I downgraded to mattermost 5.0.4 and I was able to login & access the company server just now!
thought i'd reply and tell you the news!

**Comment by devinbinnie** [comment]
@bghyt Looks like the URL you have configured in your server might not match the one your server actually uses. Can you confirm that the URL you have configured exactly matches: `https://chat.COMPANYHERE.com`

**Comment by bghyt** [comment]
> @bghyt Looks like the URL you have configured in your server might not match the one your server actually uses. Can you confirm that the URL you have configured exactly matches: `https://chat.COMPANYHERE.com`

I just had the same issue again as mattermost updated to 5.1.0 again & I saw your reply pop up so I thought to try it.

The link was "https://chat.COMPANYHERE.com/channels/town-square" before the update &  updating after turning on my PC it logged me out saying "session expired" So I could no longer login anymore, But after changing the server address to "https://chat.COMPANYHERE.com" it worked again in Ver 5.1.0
