### ISSUE TITLE
White screen after re-launch with "Open app in fullscreen" enabled

### ISSUE THREAD

**Issue by leitmori** [mattermost/desktop#2160]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
App shows white screen after re-launch if `Open app in fullscreen` option is selected.

**Environment**
- Operating System: macOS 12.4 
- Mattermost Desktop App version: 5.10
- Mattermost Server version: 7.0.0

**Steps to reproduce**
1. Select `Open app in fullscreen` in App Options
2. Close App
3. Reopen App

**Expected behavior**
App shows UI

**Observed behavior**
App shows white screen
<img width="1728" alt="Screen Shot 2022-06-19 at 10 59 23" src="https://user-images.githubusercontent.com/29522608/174473490-b263abf9-6ea6-41b5-b6d8-babb38eeb852.png">

**Comment by devinbinnie** [comment]
Looks like the BrowserView isn't being drawn correctly when the app opens in full-screen.

@leitmori A workaround for now would be to switch tabs or servers back and forth, but I'll make a fix.
Created a ticket: https://mattermost.atlassian.net/browse/MM-45203

**Comment by devinbinnie** [comment]
@leitmori It looks like this is fixed in the nightly builds. Can you confirm for me?

You can find the nightlies here: https://community.mattermost.com/core/channels/desktop-builds

**Comment by devinbinnie** [comment]
Great! I'll mark this as Closed then.
