### ISSUE TITLE
The 'uservoice' link in the issue templates leads to an unused uservoice account

### ISSUE THREAD

**Issue by Gaibhne** [mattermost/desktop#2164]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Title says it all - when filing a 'feature request' issue here, you are redirected to https://mattermost.uservoice.com/forums/306457-general which is evidently abandoned/unmaintained, as it has spam and links to viruses going back at least half a year.

**Environment**
Doesn't apply.

**Steps to reproduce**
Attempt to file an issue in this repository and select "Feature request"

**Expected behavior**
Following the advice in the template will guide me to a productive way to make a feature request.

**Observed behavior**
Following the advice in the template will guide me to a list of spam posts with download links for viruses and malware.

**Possible fixes**

Maintain or shut down (and remove the link to) the Uservoice forum.

**Comment by devinbinnie** [comment]
@amyblais Should I just make a change to the Issue Template for now to redirect to the above link instead?
