### ISSUE TITLE
Mac OS X notifications are missing Mattermost logo

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#217]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [X] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [X] This is a product defect issue that can be reproduced using the steps listed below.
- [X] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

Mac OS X notifications are missing the Mattermost logo.

Reproduced on
 - OS X
 - Mattermost Desktop 1.3
 - Mattermost Server 3.2

#### Expected behavior

Mattermost logo appears

#### Observed behavior

![image](https://cloud.githubusercontent.com/assets/13119842/17045155/25558e84-4f95-11e6-95e7-442c69dd719e.png)

#### Possible fixes

Might be related [to an earlier commit for 1.3](https://github.com/mattermost/desktop/commit/58412314775fc23fde4fd246d9e847c204ee1364).

**Comment by yuya-oc** [comment]
Not reproduced. I have downloaded v1.3 from https://about.mattermost.com/downloads/

OS X 10.11.5
Mattermost Server 3.2

**Comment by jasonblais** [comment]
Hmm, okay. I will confirm with the issuer next week

**Comment by mmahkamov** [comment]
I can confirm that on OSX 10.11.5 I can see the Mattermost logo in the notification.

**Comment by jasonblais** [comment]
Thanks @mmahkamov for verifying!

The original issuer is away at the moment, but I can check with her later.

For now I will close this issue as `cannot reproduce` and we can reopen the issue if needed.
