### ISSUE TITLE
Error to access channel in 5.1.0 but not in 5.0.4

### ISSUE THREAD

**Issue by squiaios** [mattermost/desktop#2171]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
By upgrading version 5.0.4 to 5.1.0 commit: 9cea6c2, I can not access to any channel.

**Environment**
- Operating System: Linux Mint 20.3
- Mattermost Desktop App version: 5.1.0 commit: 9cea6c2
- Mattermost Server version: I do not have this information

**Steps to reproduce**
- Click on any channel on the left menu
- Error message (https://github.com/mattermost/mattermost-webapp/blob/master/i18n/fr.json#L3109=)

**Expected behavior**
- Click on any channel on the left menu
- Channel opened

**Observed behavior**
On 5.04, no problem, but the request URL (see below) is not triggered.

On 5.0.1, when I look to the developer tools, in network tab, I have :

Request URL: https://chat.avalanche-tools.fr/api/v4/teams/name/channels
Request Method: GET
Status Code: 400
```json
{
  "id": "api.context.invalid_url_param.app_error",
  "message": "Paramètre team_id invalide ou manquant dans l'URL de la requête",
  "detailed_error": "",
  "request_id": "9j7zoqj8mib7xgadkotz7unuby",
  "status_code": 400
}
```

If I remove the 5.1.0 app, then re-install 5.0.4, all works fine.

**Comment by amyblais** [comment]
@squiaios Do you see any errors in [the desktop app logs](https://docs.mattermost.com/install/troubleshooting.html#mattermost-desktop-app-logs)?

Do you see the same issue with 5.1.1-RC1 https://github.com/mattermost/desktop/releases/tag/v5.1.1-rc1 ?

**Comment by squiaios** [comment]
Unfortunately I do not have `Mattermost` directory in `~/.local/share`

My application is installed in `/opt/Mattermost`, but no logs directory is present either.

With Mattermost 5.1.1-rc1, the problem is still present

**Comment by devinbinnie** [comment]
@squiaios Can you check `~/.config/Mattermost`? I think the docs might be out of date (will fix that)

Also, can you confirm that your configured server URL matches the site URL that you're trying to access?

**Comment by squiaios** [comment]
In `~/.config/Mattermost/config.json`, I changed the url of the team and now it works.

Thank you =D
