### ISSUE TITLE
Screen sharing during call does not work

### ISSUE THREAD

**Issue by torse** [mattermost/desktop#2172]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Sharing screen or window doesn't work during a call. This works with Firefox 101.0.1 and Chromium 95.0.4638.54 on same client and server thus I assume it's an issue of the Desktop App.

**Environment**
- Operating System: Ubuntu 20.04 LTS
- Mattermost Desktop App version: 5.1.0
- Mattermost Server version: 7.0.0

**Steps to reproduce**
1. Start call -> Works
2. Click "Start Presenting" Icon -> Dialog pops up
3. Select what to share (screen/window) and click "share" --> Nothing happens

**Expected behavior**

Screen/Window is shared and a preview of the shared content being shown above the small call dialog in the bottom left of the App (as in Firefox/Chromium). 

**Observed behavior**

Nothing is shown as preview, screen/window is not shared.

**Possible fixes**

N/A

**Comment by amyblais** [comment]
@torse Would you be open to moving this issue to the Calls repo https://github.com/mattermost/mattermost-plugin-calls/issues? When you do so, please also help include the following details if possible:

**1. JS Console Logs**

1. Dots menu -> View -> Developer Tools for Current Tab.
2. Right Click -> Save as…

**2. Call Stats Dump**

Running the ``/call stats`` slash command in the channel the call is ongoing. A JSON object will be returned to the user through an ephemeral message.

**Comment by devinbinnie** [comment]
Closing as this is a Calls issue
