### ISSUE TITLE
Cannot start a call in Linux desktop client.

### ISSUE THREAD

**Issue by stedekay** [mattermost/desktop#2173]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

I upgraded our server to version 7.0.1 and also upgraded my client version to 5.1.0 via snap on Ubuntu 22.04.
I wanted to test the new 'Start a call' function and enabled it for all channels in the system console. Now I've got a 'Start call' button in each channel but nothing happens when I click this button. When I test it in my browser, everything works fine. My colleague can start it from its windows client.

**Environment**
- Operating System: Ubuntu 22.04
- Mattermost Desktop App version: 5.1.0
- Mattermost Server version: 7.0.1 

**Steps to reproduce**

Click on 'Start call' button

**Expected behavior**

It should start a call

**Observed behavior**

Nothing happens at all.

**Possible fixes**

**Comment by amyblais** [comment]
@stedekay Would you be open to moving this issue to the Calls repo https://github.com/mattermost/mattermost-plugin-calls/issues? When you do so, please also help include the following details if possible:

**1. JS Console Logs**

1. Dots menu -> View -> Developer Tools for Current Tab.
2. Right Click -> Save as…

**2. Call Stats Dump**

Running the ``/call stats`` slash command in the channel the call is ongoing. A JSON object will be returned to the user through an ephemeral message.

**Comment by stedekay** [comment]
Sure, I opened a new issue with the console logs here: https://github.com/mattermost/mattermost-plugin-calls/issues/132
