### ISSUE TITLE
Windows 10 desktop notifications have a black Mattermost logo against a black background

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#218]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [X] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [X] This is a product defect issue that can be reproduced using the steps listed below.
- [X] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

Windows 10 desktop notifications have a black Mattermost logo against a black background
- Mattermost Desktop App 1.2/1.3
- Mattermost Server 3.2

#### Expected behavior

Mattermost logo appears white against the black background

#### Observed behavior

![image](https://cloud.githubusercontent.com/assets/13119842/17045683/b704a014-4f99-11e6-984d-d477f58c99b6.png)

#### Possible fixes

[Using Logomark (Inverted) from Mattermost Brand Guidelines](https://www.mattermost.org/brand-guidelines/)

**Comment by jasonblais** [comment]
Would need help whether this reproduces on other Windows operating systems (Windows 7 or 8)

@MetalCar Would you be able to help send a screenshot of what the desktop notification looks like on Windows 7?

**Comment by Razzeee** [comment]
Windows 7 is fine.

![notification](https://cloud.githubusercontent.com/assets/5943908/17050534/b0313bc6-4ff3-11e6-8304-e4a450a1ec1c.png)

**Comment by jasonblais** [comment]
Perfect, thanks for checking @Razzeee! Seems to be an issue with Windows 10 then

**Comment by Razzeee** [comment]
The icon is basically the one the platform gives us. We just need to set the correct icon at https://github.com/mattermost/desktop/blob/master/src/browser/js/notification.js#L9 
But I can't find a way to get the correct path to the png in that class.

**Comment by yuya-oc** [comment]
Sure it's the issue in fixes. The icon exists at `resources/appicon.png`, but `__dirname` returns nothing in the js.

**Comment by Razzeee** [comment]
Not sure if nothing is true, but at least nothing we can work with. Seems to lead to the top parent in my case d:/

Might be easier when we replace the notifications with an notifications library not sure if that would let us solve that easier.

**Comment by yuya-oc** [comment]
`remote.app.getAppPath()` solved the problem.

**Comment by jasonblais** [comment]
Will the above change then display the white icon (against a black background), or a blue icon?

**Comment by yuya-oc** [comment]
It show a blue icon as same as Windows 7 and 8.

![notification_icon](https://cloud.githubusercontent.com/assets/1412057/17141422/f5a9fd82-5386-11e6-80b5-e97588f671d7.png)

**Comment by jasonblais** [comment]
Perfect, sounds good!

**Comment by yuya-oc** [comment]
Thanks, I will merge.
