### ISSUE TITLE
app.asar is not built properly after code signing the mac app. without code sign app.asar is built properly and the desktop works fine.

### ISSUE THREAD

**Issue by bhattrahul14** [mattermost/desktop#2182]
![Screenshot from 2022-07-01 10-18-28](https://user-images.githubusercontent.com/105793021/176834556-f5120c9d-e92a-4975-ae4c-21ab21e46758.png)

**Comment by devinbinnie** [comment]
Closing as duplicate of https://github.com/mattermost/desktop/issues/2181
