### ISSUE TITLE
Mattermost-Desktop 5.1.x cannot switch to a certain channel on our server

### ISSUE THREAD

**Issue by heckert-epost** [mattermost/desktop#2184]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Switching to a certain channel doesn't work.

**Environment**
- Operating System:
- Mattermost Desktop App version: 5.1.0 and 5.1.1
- Mattermost Server version: 7.0.0
- Client running Ubuntu 18.04 (with KDE)

**Steps to reproduce**
- Before the update, using Mattermost-Desktop 5.0.4, I open the problematic channel
- I update mattermost-desktop from APT repository
- I open the client and can use the channel
- I switch to other channels
- I (try to) switch back to the initial channel

**Expected behavior**
- I can switch to any channel

**Observed behavior**
- Switching back to the initial channel doesn't work.

I observed that with the new client the channel link is shown in the lower left corner of the client. For the problematic channel this information does not appear.

Incidentally the problematic channel is our team's *primary* channel which makes being able to switch back to it all the more important.

One thing I want to investigate is, if I can reproduce it on our test-server and narrow in the circumstances of when it fails.

Channel-URLs involved are:

"our-server-hostname"/"group"/channels/team-internal
"our-server-hostname"/"group"/channels/team

("group" being the "teamname" in mattermost, which is more like "department" in our environment)

My initial theory is this:
I think this relates to the bugfix from 5.1.0 to 5.1.1 (I hoped that would have fixed it but it didn't):
"Fixed an issue where a channel name matching the server subpath would not be navigable."

**Comment by heckert-epost** [comment]
That single line I pasted above was the only logging entry I got after I had disabled the Jira-plugin on the test Mattermost instance.

This would be over an hour later:
```
{"timestamp":"2022-07-06 11:49:27.590 Z","level":"error","msg":"websocket.NextReader: closing websocket","caller":"app/web_conn.go:834","user_id":"(some_hash_value)","error":"read tcp 172.17.1.100:8065->172.17.1.172:52754: i/o timeout"}
{"timestamp":"2022-07-06 12:29:43.827 Z","level":"info","msg":"SimpleWorker: Job is complete","caller":"jobs/base_workers.go:88","worker":"ActiveUsers","job_id":"dxyizfq9spd15c6tpbppetizge"}
{"timestamp":"2022-07-06 12:09:43.708 Z","level":"info","msg":"SimpleWorker: Job is complete","caller":"jobs/base_workers.go:88","worker":"ProductNotices","job_id":"o9jyfazth7nb3mcmyqeaheb1fh"}
{"timestamp":"2022-07-06 12:47:13.909 Z","level":"info","msg":"License key valid unlocking enterprise features.","caller":"app/license.go:153"}
```
which all seem to be coming from some scheduled jobs. (yes, there's more of them, the only changes being the "job_id" values and time stamps.

**Comment by paulehoffman** [comment]
FWIW, I'm having the same problem as is reported in this issue with Mac client version Version 5.1.1 (20700). It starts up, I see a display of the normal starting channel, and then if I click on another channel or a direct message contact, I get:
Channel Not Found
The channel you're requesting is private or does not exist. Please contact an Administrator to be added to the channel.

[Back to Town Square](https://chat.dns-oarc.net/members/channels/town-square)

**Comment by devinbinnie** [comment]
@heckert-epost You're looking at the server logs in the System Console. Since this is likely a Desktop App issue, we'll need the logs from that. You can find them by looking here: https://docs.mattermost.com/install/troubleshooting.html#mattermost-desktop-app-logs

**Comment by heckert-epost** [comment]
[debug_session.sanitized.txt](https://github.com/mattermost/desktop/files/9062160/debug_session.sanitized.txt)

This is a complete session from starting the 5.1.1 client to quitting the application again. During the test-run I echoed the test steps into the log file (lines starting with dashes).
"Sanitized" means I replaced the actual server and channel names with neutral values.

I also opened a support ticket directly at mattermost.com for the issue now: 
`#33603: Mattermost-Desktop 5.1.x cannot switch to a certain channel on our server`

**Comment by heckert-epost** [comment]
Indeed, now it does work. :)

This seems to me to be some sort of regression though, since everything worked in the 5.0.4 version of the client.
I suggest to at least add some help-text line informing users on what the correct URL looks like and what not.

**Comment by heckert-epost** [comment]
Within the Server Console the entry for the URL has a comment text:
`Mattermost may be hosted at a subpath. For example: http://example.com:8065/company/mattermost. `

I see how telling users to omit the path from the URL could be incorrect in such a configuration...
Ideally the client could determine that it had been pointed to a URL below that root path (say "example.com:8065/company/mattermost/team/channel/channelname") and inform the users about this mistake.
