### ISSUE TITLE
Prevented desktop from navigating

### ISSUE THREAD

**Issue by FHantke** [mattermost/desktop#2191]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Today, I was automatically logged out from our Mattermost server. When I tried to login again, the application did not react to clicking the login button. This means, I am not able to login Mattermost via the application.
I also cleaned the application's folder and installed a fresh Mattermost version but still encountered the problem.
The behavior is similar to the closed issue #1271.

**Environment**
- Operating System: macOS 12.4
- Mattermost Desktop App version: 5.1.1.20701
- Mattermost Server version: 6.7.0 (That's what the web version shows)

**Steps to reproduce**
1. Install Mattermost
2. Configure server
3. Open server and click login

**Expected behavior**
The applications opens the Gitlab login page.

**Observed behavior**
The applications ignores the click. Log messages:
```
[2022-07-09 00:05:32.941] [debug] webContentEvents.did-start-navigation {
  webContentsId: 4,
  url: 'https://.../oauth/gitlab/login'
}
[2022-07-09 00:05:32.942] [debug] webContentEvents.will-navigate {
  webContentsId: 4,
  url: 'https://.../oauth/gitlab/login'
}
[2022-07-09 00:05:32.942] [info]  Prevented desktop from navigating to: https://.../oauth/gitlab/login
```

**Possible fixes**

Unfortunately, I have no idea where the issues originates.

**Comment by FHantke** [comment]
Web and iOS version work fine.

**Comment by FHantke** [comment]
Ok... works fine again. For other people having the same issue, here is what I think went wrong:
I had internet issues yesterday and was logged out and probably not logged in the first few times. Then, I changed the configuration. Instead of the plain server URL, I added the `/oauth/gitlab/login` path as well. This caused the application to prevent navigating. This morning, I realized it and removed the path :)

**Comment by alberto-miranda** [comment]
This is hitting me on Mattermost-desktop 5.2.2 downloaded from snap and using a self hosted mattermost server behind a nginx proxy. Previous versions worked without issues.

Below is the offending log:

```
[2022-12-07 10:29:39.586] [info]  Log level set to: info
[2022-12-07 10:29:39.606] [info]  config.autostart has been configured: true
[2022-12-07 10:29:39.652] [info]  opening SSEC___TAB_FOCALBOARD on hasFocalboard
[2022-12-07 10:29:39.652] [info]  opening SSEC___TAB_PLAYBOOKS on hasPlaybooks
[2022-12-07 10:29:39.659] [info]  Log level set to: info
[2022-12-07 10:29:39.679] [info]  config.autostart has been configured: true
[2022-12-07 10:29:50.750] [info]  [SSEC___TAB_MESSAG...] Loading http://chat.example.com/
[2022-12-07 10:29:50.867] [info]  show back button
[2022-12-07 10:29:51.062] [info]  [SSEC___TAB_MESSAG...] finished loading http://chat.example.com/
[2022-12-07 10:29:55.065] [info]  SSEC___TAB_MESSAGING timeout expired will show the browserview
[2022-12-07 10:29:59.307] [info]  Prevented desktop from navigating to: https://chat.example.com/oauth/gitlab/login
```

I increased the log verbosity but was not able to get more insight into why the error happens (my gut tells me the change between `http` and `https` could be the key factor here). Is there any way to get more details on why the navigation is prevented?

**Comment by anx-ag** [comment]
Hi @alberto-miranda ,

can you please verify that the `SiteUrl` parameter of your Mattermost server is set to https://chat.example.com? It seems as if the desktop app tries to connect to http://chat.example.com and the server redirects you to https://chat.example.com then.

**Comment by anx-ag** [comment]
The reason for the new behaviour is that the newer desktop apps (starting with 5.1 I think) redirect the client to the configured `SiteUrl`- older versions didn't do that, they just ignored it, so this is a somewhat breaking functionality.
Gitlab integrated setups are a bit special to work with, especially when authentication is also done via Gitlab, so I'm not 100% sure what to do here since I don't have experience with working in such an environment, but I recall that there are callback URLs in the Gitlab Auth configuration - maybe those need to be changed to https to, but I think this might cause problems since your Gitlab does not have SSL enabled :-/

**Comment by alberto-miranda** [comment]
@anx-ag Ok, we may need to go back to 5.1 then. Thanks for the help :)

**Comment by anx-ag** [comment]
I think you need to go back to 5.0.4 for the time being until you figure out how to fix your Gitlab setup. I'd strongly suggest to use an SSL certificate also for gitlab; certificates are cheap nowadays, if you cannot use free certificates for Let's encrypt for some reason.

**Comment by melt7777** [comment]
Thank you anx-ag, 

Confirmed behavior on Apple M1 Pro 16" 2021 with Monterey 12.6.2.

Downgrading by Installing dmg for v5.0.4 resolves the issue and I am able to login.

~ melt
