### ISSUE TITLE
Client does not overwrite pre-existing file on download from a chat

### ISSUE THREAD

**Issue by flxmrk** [mattermost/desktop#2199]
I confirm (by marking "x" in the [ ] below: [x]):

- [x ] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Downloading files from a chat will not overwrite preexisting files on save, but acts like it does.

**Environment**
- Operating System: OSX 12.4
- Mattermost Desktop App version: 5.1.1
- Mattermost Server version: 7.1.1

**Steps to reproduce**
1. put two different images in a chat
2. hover the first image, click the download icon, save the first image as a new file test.png
3. verify the right image is downloaded
4.  hover the second image, click the download icon, save the second image over the previous file named test.png
5. check the file, it is still the first image

**Expected behavior**
File becomes overwritten

**Observed behavior**
File stays the same as it was

**Comment by devinbinnie** [comment]
There’s an Electron issue with MAS entitlements causing this. I’ve submitted a bug report: https://github.com/electron/electron/issues/35104

As per the bug, I can at least set exceptions for the Downloads folder (and a couple other select folders) so I will start with that and finish up if/when the bug is resolved.
