### ISSUE TITLE
Set default server URL and Name before first start (set it without UI)

### ISSUE THREAD

**Issue by vlaterz** [mattermost/desktop#2206]
Hello. I need to connect to mattermost server automatically right after mattermost desktop installation on Windows. 
I followed guide https://docs.mattermost.com/deploy/desktop-app.html and changed config.json as was mentioned there. But after running mattermost it prompted for url and name. Config was reset to initial state.

The question: is there any way to configure server url and name parameters at installation step? (may be pass parameters to msi to start MM with configured server and name, so user will not have to do it). Or am i doing something wrong?

**Comment by devinbinnie** [comment]
If you're on Windows, you can configure a Group Policy setting as per this guide: https://docs.mattermost.com/install/desktop-msi-installer-and-group-policy-install.html

**Comment by vlaterz** [comment]
> If you're on Windows, you can configure a Group Policy setting as per this guide: https://docs.mattermost.com/install/desktop-msi-installer-and-group-policy-install.html

Thank you for your answer. Is there any other way? 
I need this to wrap MM msi installer in exe installer with some other installers, so that user will not have to configure anything. 
Do you know, if i do something wrong with config.json? Why is it reset to default? Is there any way to set server with that config?

**Comment by devinbinnie** [comment]
You can create a custom build of the Desktop App and edit the `buildConfig` file, that will allow teams to be automatically added.

However if you just edit the `config.json` file in the install directory, it should pick up those teams that you've added. If not, it's possible that the changes aren't formatted correctly and the app is rejecting them. Have a look at the logs if this is the case.

**Comment by devinbinnie** [comment]
Closing as inactive, likely resolved.
