### ISSUE TITLE
Mattermost desktop app does TLS validation on "http://" links and displays misleading message.

### ISSUE THREAD

**Issue by RobotDisco** [mattermost/desktop#2208]
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Unlike the web app, the mattermost desktop app checks the server certificates of "http://" links, which either causes an unnecessary https error message or causes a misleading message that entirely suggests server espionage or cert interception rather then a misconfigured linked server.

**Environment**
- Operating System: MacOS 11.6.5
- Mattermost Desktop App version: 5.1.1 (5.1.1.20701)
- Mattermost Server version: 5.37.0

**Steps to reproduce**
Insert the link http://captainkensdiner.com/ into a channel or DM.
**Expected behavior**
The link gets inserted and previewed without any issue.
**Observed behavior**
The following popup occurs every single time the channel/dm is viewed.

<img width="1112" alt="Screen Shot 2022-07-23 at 11 12 26 AM" src="https://user-images.githubusercontent.com/487847/180611593-77f6491f-4aac-45a8-bfeb-d93640477b5e.png">

**Possible fixes**
1. Don't perform cert validation on http:// links.
2. Change the message to include the possibility that the linked web host is misconfigured rather than a security breach of the mattermost server or network connection.

Closest source code link I could find: https://github.com/mattermost/desktop/blob/40c072981aa8c4adff5e86fe40f370d880597577/src/main/app/initialize.ts#L179

**Comment by RobotDisco** [comment]
I disagree in that the message is specifically claiming that the _Mattermost_ server is misconfigured, not the linked site. There is a big difference of interpretation between the chat program's server and the linked site.

That this is a popup also means that there's no way to tie this to the specific message, if one has never hit this popup before, the whole channel appears to be broken unless someone knows what to look for.

In this case, the user doesn't use the desktop app, so the insecure link worked just fine as the web client does not have this behaviour. As such, they inadvertently took down the entire channel. For people who did not post the site, because the entire app gets stalled with the popup and the message claims the mattermost server is the issue (or a networking hijack), there is nothing that leads to the specific post causing the issue or the specific issue itself.

**Comment by RobotDisco** [comment]
I just thought of another possible way to address this:

Instead of a popup, a potential solution would be to annotate the mattermost message as insecure (or refuse to load it) rather than a modal popup.

**Comment by Nike682631** [comment]
@devinbinnie  Is this issue available to work on?

**Comment by RobotDisco** [comment]
It looks like there is at least one previous issue related to this one: https://github.com/mattermost/desktop/issues/2107

That one specifically references icons, but it looks to me as if it is a specific description within a larger theme.

**Comment by devinbinnie** [comment]
The issue above was to reject cross-origin certificates. This actually might already be resolved.

@RobotDisco can you try our nightly build from [here](https://community.mattermost.com/core/channels/desktop-builds) and see if the issue is fixed for you?

**Comment by RobotDisco** [comment]
I didn't get an error on the latest build, reproducing with the URL from my ticket.

Thanks so much!
