### ISSUE TITLE
Possibility to copy email addres in profile without "mailto" prefix

### ISSUE THREAD

**Issue by AnnaGrishina** [mattermost/desktop#2212]
There is a link to the user's email address in the profile.

Not so long ago we used slack for communications and it was really ease to click on the emal link (to copy email addres) and sent it  to some one who asked it (for example) or copy email addres and add copyed email to mailing list

In MM I click (using right button) -> copy link and then paste. What I see.. I see **mailto:**anna.grishina@mail.com
If I press on the email, then new email is opened without prefix "mailto"

It would be greate to fix this issue so action "copy link" will copy only email address without prefix

Best regards,
Anna

**Comment by AnnaGrishina** [comment]
[](url
![Copyemail](https://user-images.githubusercontent.com/110117504/181295435-e8333491-e7a5-4835-8a89-86bd02fda14c.png)
)

**Comment by devinbinnie** [comment]
Unfortunately the `Copy Link` functionality is built into the browser and will always copy the URL attached to the given link. So I don't think there's anything we can do about this unless we wanted to change the click behaviour of the link itself. Which would break the normal flow of opening your default email client.

Sorry for the inconvenience.
