### ISSUE TITLE
The Ubuntu20.04 startup Mattermost-Desktop failed

### ISSUE THREAD

**Issue by lovechoudoufu** [mattermost/desktop#2234]
![image](https://user-images.githubusercontent.com/95681496/185836601-c93f7eed-acc4-4da7-8e94-4c09afea9a4b.png)

When I start mattermost-Desktop, Has been "ERROR: network_service_instance_impl. Cc (978)] Network service crashed, restarting the service." ERROR page, the program cannot be started

**Comment by devinbinnie** [comment]
@lovechoudoufu Are you running the application as root? There's an issue running sandboxed Electron applications under root.

**Comment by lovechoudoufu** [comment]
Yes, thank you
