### ISSUE TITLE
Mattermost osx Desktop Application becomes unresponsive when dragging an Emoji.

### ISSUE THREAD

**Issue by estherDow** [mattermost/desktop#2235]
I confirm (by marking "x" in the [ ] below: [x]):

- [x ] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [ x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Mattermost osx Desktop Application becomes unresponsive when dragging an Emoji.

**Environment**
- Operating System: macOS 12.3.1 monterey
- Mattermost Desktop App version: 4.7.1 
- Mattermost Server version: Version 4.7.1 (4.7.1.11707) 

**Steps to reproduce**
![image](https://user-images.githubusercontent.com/54309105/185972030-9ccebf08-8ab1-468f-98c3-1e35017b1d55.png)
click on Smiley menu in message bar

![image](https://user-images.githubusercontent.com/54309105/185972231-0bf7a311-6c68-45e3-83bf-41b0b1ffc701.png)
click and drag smiley (as opposed to click and release)

**Expected behavior**
Initially clicked smiley is deselected OR Initially clicked Smiley is dragged into text.
**Observed behavior**
Application becomes unresponsive. Shift + cmd + r do not resolve the issue. Choosing Clear Cache and reload in top menu resolves the issue after loading for 65 -70 wall clock seconds.

**Possible fixes**

**Comment by amyblais** [comment]
@kennethDow 
1. Do you see the same issue on the latest v5.1.1 version? 
2. Do you see any console errors [instructions here](https://docs.mattermost.com/install/desktop-app-install.html#report-desktop-app-issues)?
3. What is your Mattermost server version? (You can find this from Main Menu > About Mattermost)

**Comment by devinbinnie** [comment]
Closing as inactive.
