### ISSUE TITLE
Start call button doesn't work

### ISSUE THREAD

**Issue by Chaxwell** [mattermost/desktop#2248]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Cannot start a call in any channel.

**Environment**
- Operating System: Ubuntu 22.04.1 LTS
- Mattermost Desktop App version: Version 5.1.1 commit: 7eef060
- Mattermost Server version:  7.1.2

**Steps to reproduce**
Click on "{phoneIcon} Start call"

**Expected behavior**
To start a call

**Observed behavior**
Doesn't do anything.

**Remarks**
When I click on the button it doesn't produce any error log in ~/.config/Mattermost/logs/main.log

**Comment by anx-ag** [comment]
Hi Chaxwell,

can you verify that typing `/call start` also does not result in a call being started? Can you confirm that your audio device setup is working as expected? Sometimes the calls refuse to start when there are no connected/available audio devices, so if you have a bluetooth device which connected after you started the app, please (for testing purposes) make sure it's connected and then restart the Mattermost app and try again to initiate a call.

**Comment by Chaxwell** [comment]
Ah you were right, I had no audio device connected.

It still doesn't work with just an audio device, I actually need to plug an audio device plus a microphone.

I feel like it could be improved though (allowing to call or get an info message)

Thank you

**Comment by anx-ag** [comment]
Please note that the Calls plugin is still in beta; issues like these are currently being worked on and should be no problem anymore as soon as the plugin hits GA status.

Glad to hear that you could fix that by activating the microphone!
