### ISSUE TITLE
No inline spellcheck on OS X client

### ISSUE THREAD

**Issue by GElliott** [mattermost/desktop#225]
I confirm (by marking "x" in the [ ] below): 
- [x] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [x] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [x] This is a product defect issue that can be reproduced using the steps listed below.
- [x] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---
#### Summary

There is no inline spellcheck in the OS X client.
#### Steps to reproduce

OS: 10.11.6
Desktop App Version: 1.3.0
Server Version: Unknown, but this is clearly a client issue.

Steps to reproduce:
1) Enter a channel or direct message mode/window.
2) Enter misspelled word in the input text box.
#### Expected behavior

There should be some visual indicator that a word is misspelled (typically with a squiggly red underline).  The ability to correct spellings (via right-click) or auto-correct spellings should also be provided.  Given that Mattermost is a text-based communication tool, it's **bonkers** that there are no spellcheck features.
#### Observed behavior

There is no visual indicator (or otherwise) to indicate that a word is misspelled.
#### Possible fixes

Leverage the services/APIs already offered by Mac OS X.

**Comment by jasonblais** [comment]
Thanks @GElliott for the suggestion!

We have an existing [Feature Idea suggestion](https://mattermost.uservoice.com/forums/306457-general/suggestions/15272040-inline-spell-check-for-mattermost-client) in our forums, please feel free to upvote it and add your thoughts there as well?

**Comment by jasonblais** [comment]
@Razzeee @yuya-oc @timroes @jnugh 

Any thoughts on the work needed to implement this feature? It would be a great improvement to user experience, and we have received requests on this feature from several sources.

**Comment by Razzeee** [comment]
Well I can't get the spellchecker package to even compile :/
https://github.com/paulcbetts/electron-spellchecker/issues/8

**Comment by timroes** [comment]
Actually the spell checking is something Mac provides out of the box for native apps and also in browser. 

This seems to be an open issue in electron at the moment, that packaged webapps don't do that. See also: https://github.com/electron/electron/issues/3189 (the last comment holds two follow up tickets). So I guess either you need to implement own spell check, what could end up in a lot of work and trouble or wait for electron to fix the appropriate bugs and update then.

**Comment by yuya-oc** [comment]
If using `node-spellchecker`, `electron-spellcheker` or others, we have to take care that they are native modules. Because Multiple CI environments to build the modules for each platforms, Windows, macOS and Linux are necessary.

**Comment by akashnimare** [comment]
You could use [simple-spellchecker](https://github.com/jfmdev/simple-spellchecker#electrons-integration). I am using it [here](https://github.com/zulip/zulip-electron) in Zulip desktop app. I'll send a PR if it sounds good.

**Comment by jasonblais** [comment]
That's awesome @akashnimare! 

@yuya-oc Would the [simple-spellchecker](https://github.com/jfmdev/simple-spellchecker#electrons-integration) be a native module?

I can look into the integration a little further, but it would be excellent if it was something we could use.

I'm surprised I guess that electron wouldn't have added better support for system spell checking? It appears that the issues referenced above by @timroes haven't had a lot of activity for a while now.

**Comment by akashnimare** [comment]
@Razzeee electron-spellchecker looks good but it's fucking hard to compile or even configure it. You need to install electron-builder first then compile it with this -
> /node_modules/.bin/electron-rebuild

**Comment by yuya-oc** [comment]
@jasonblais It seems not a native module. So it can be used in the current CI process.

**Comment by Razzeee** [comment]
@akashnimare
Would you send a pr please?

**Comment by akashnimare** [comment]
@Razzeee I'll get it a try with simple-spellchecker.

**Comment by akashnimare** [comment]
@Razzeee do you guys have any demo instance of mattermost where I can test it out?

**Comment by Razzeee** [comment]
Not exactly a demo instance, but the official mattermost team server https://pre-release.mattermost.com

**Comment by akashnimare** [comment]
@Razzeee I did try spellchecking using simple-spellchecker.  I don't know for some reason it's not working with mattermost.

**Comment by jnugh** [comment]
Does `simple-spellchecker` work with webviews?

**Comment by akashnimare** [comment]
@jnugh I am not sure but it should work.

**Comment by jasonblais** [comment]
Thanks @akashnimare for your work here!

I'm really excited about the potential here, as an inline spell check could be a great improvement to user experience

**Comment by jasonblais** [comment]
Hey @akashnimare, any updates here? Let us know if you have any questions, would love to help out if needed :)

**Comment by jasonblais** [comment]
Would anyone like to work on this feature, perhaps using the `simple-spellchecker` mentioned above?
