### ISSUE TITLE
error: cannot communicate with server: Post http://localhost/v2/snaps/mattermost-desktop

### ISSUE THREAD

**Issue by vveckaln** [mattermost/desktop#2252]
https://docs.mattermost.com/install/desktop-app-install.html
![mmsnapcraft](https://user-images.githubusercontent.com/7974113/189680307-bd7bdebf-dac0-47e2-ab20-8888a71f13a4.png)

```
sudo snap install mattermost-desktop --beta
[sudo] password for v: 
error: cannot communicate with server: Post http://localhost/v2/snaps/mattermost-desktop: dial unix /run/snapd.socket: connect: connection refused
```

**Comment by amyblais** [comment]
What Mattermost desktop app version are you on?

**Comment by vveckaln** [comment]
`mattermost version 7.2.0`

**Comment by devinbinnie** [comment]
Looks like this is an issue with Snapcraft. We don't actually maintain the snap for mattermost, that happens here: https://github.com/snapcrafters/mattermost-desktop

**Comment by devinbinnie** [comment]
Closing as per above.
