### ISSUE TITLE
[Desktop] Ctrl+F doesn't search chat history, and prioritises channel names in the left-hand column.

### ISSUE THREAD

**Issue by JonathanDotCel** [mattermost/desktop#2255]
#### Summary
If I'm in a chat with a colleague, and search for e.g. the word "coin". Channels with the word "coin" in them will be highlighted on the left. Chat history (littered with the word coin) will be largely ignored despite the big "Hey, you can use ctrl+f".

#### Steps to reproduce
Ctrl+F, search for something a few days ago in a chat

#### Expected behavior
I hit Ctrl+F, I type "coin", I see a list of or iterate through a list of the word "coin"
-in the current chat window
-going back to my initial contact with this person
-excluding channel names on the left

If I want to search for a channel, I can use the "Find channel" at the top of the channels column/frame.
It's just misleading and frustrating otherwise, since Ctrl+F is just searching "cached stuff in the current html DOM".

#### Observed behavior (that appears unintentional) 
It highlights the wrong stuff, doesn't search my chat history.

#### Possible fixes
Search my chat history if I'm in a chat window, ignore the channels since there's already a search for that.
Cheers.

**Comment by esethna** [comment]
Hi @JonathanDotCel, sounds like you’re an out of date desktop version. Please update to the latest and try again if possible. Thanks! https://mattermost.com/apps/

**Comment by JonathanDotCel** [comment]
@amyblais, thanks:

1 & 2:
From the 3 dots -> Help - Version 4.6.1
From the 9 dots -> About Chat:
Mattermost Version: 6.3.3
DB Schema version 6.3.3

3:
Windows 10

4: 
Mattermost (desktop app) does not respond to the link on that page for me to connect to the community server.
(Could be an IT policy, could be a bug).
So unfortunately I'm not able to check

@esethna The build date is Feb 2022

I'm not too hot on using a different version from the rest of the company, but since this is a relatively easy issue to reproduce, i.e.:

- ctrl+f for a word for about 10-20 pages of chat in the past (i.e. isn't cached, part of the current document)
Is it found?
- ctrl+f for a word that's the name of a channel you're subbed to
Is that also erroneously found?
Does that also take precedence over actual chat contents?

Are you or @amyblais able to take a few secs to confirm/refute this behaviour on a recent version?
Or perhaps confirm that since Feb, search has been fixed to work as expected?

Many Thanks.

**Comment by amyblais** [comment]
@jgilliam17 Do you have Windows to verify whether the original report https://github.com/mattermost/desktop/issues/2255#issue-1370408993 still reproduces on the latest desktop app version?

**Comment by devinbinnie** [comment]
Sorry, I should have jumped in here. Version v4.6 is no longer supported and will conflict with any version of `mattermost-server` newer than v6. If you use Desktop v5 or greater, Ctrl+F will automatically highlight the top search bar of the Mattermost webapp and will allow you to search channel history.

**Comment by esethna** [comment]
@JonathanDotCel +1 to Devin, this has been addressed in future versions, as such I would recommend upgrading to latest

**Comment by JonathanDotCel** [comment]
@amyblais, @esethna, @devinbinnie 
That's great, thanks all :)
