### ISSUE TITLE
Left click on the tray icon doesn't open app window but opens tray menu for right click 

### ISSUE THREAD

**Issue by p01arbear** [mattermost/desktop#2257]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
It would be nice if the left mouse click opened the App Window and the right click opened the tray menu.
Or may be current behavior is intentional?

**Environment**
- Operating System: Debian 11
- Mattermost Desktop App version: 5.1.1

**Comment by edlerd** [comment]
Can confirm the same behavior in Ubuntu 22.04.

I found a related issue in electron, which is open: https://github.com/electron/electron/issues/14941

Electron docs state "The click event is ignored" on Linux under some circumstances: https://www.electronjs.org/docs/latest/api/tray

**Comment by devinbinnie** [comment]
So given what the Electron docs say, I think this needs to be marked as a known issue. We already make sure to capture the `click` event for other OSes, but it seems that this is a limitation set by Electron/AppIndicator which means it isn't something we can fix.

There's a bug open with Electron already which is good, but it doesn't seem like they'll get to it any time soon given the length of time it's been open. I think we'll mark this down as a known issue in our changelogs going forward but I don't think we can fix this.

Closing as can't fix.

**Comment by devinbinnie** [comment]
@amyblais Can we add this to our list of Known Issues? Not sure where to do that myself.

**Comment by amyblais** [comment]
> Can we add this to our list of Known Issues? Not sure where to do that myself.

👍 I'll add it to the changelog known issues via this PR that I already have open https://github.com/mattermost/docs/pull/5903.
