### ISSUE TITLE
Dismiss connection not available dialog when reconnected

### ISSUE THREAD

**Issue by Razzeee** [mattermost/desktop#226]
We should dismiss the "There appears to be a problem with your internet connection." -bar which shows up when your offline, if you have reconnected again.

**Comment by jasonblais** [comment]
Any thoughts from the community on how we might be able to accomplish it?

It seems to reappear quite often when I first launch the app as well.

**Comment by jasonblais** [comment]
The blue bar at the top with "There appears to be a problem with your internet connection." is appearing quite often these days, even though I've reconnected. 

It sometimes doesn't disappear even after a couple of minutes unless I manually remove it.

Have been reported by a few other people, impacting user experience.

![image](https://cloud.githubusercontent.com/assets/13119842/18683115/e7c566fc-7f3c-11e6-9a8b-620f403c387b.png)

**Comment by jasonblais** [comment]
@Razzeee Wondering if this still reproduces for you?

The blue bar disappears for me with desktop app 3.4.1 after the app has reconnected.

**Comment by Razzeee** [comment]
Haven't really seen this in the last month's I think. We can close it for now.
