### ISSUE TITLE
On Mac and Windows, even if you set Desktop Notification Sounds to "Off" in Mattermost, still get desktop sounds for every notification.

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#227]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [X] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [X] This is a product defect issue that can be reproduced using the steps listed below.
- [X] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

On Mac and Windows, even if you set **Account Settings > Notifications > Desktop Notification Sounds** to "Off" in Mattermost, you still get desktop sounds for every notification.

#### Steps to reproduce

On 
 - Windows 10 and OS X,  
 - Mattermost Desktop v1.3, 
 - Mattermost Server v3.2

1. Go to **Account Settings > Notifications > Desktop Notification Sounds** and set the field to `Off`.
2. Go to **Account Settings > Notifications > Send desktop notifications** and set the field to `Always`.
3. Receive a message from someone.

#### Expected behavior

Desktop notification appears, but no sound is played.

#### Observed behavior

Desktop notification appears and sound is played.

#### Possible fixes

-

**Comment by Razzeee** [comment]
I also noticed this when using the android app. Might this be platform related after all?

**Comment by yuya-oc** [comment]
Probably the sound is played by operation system because [`silent` is not set by the server](https://github.com/mattermost/platform/blob/v3.3.0/webapp/utils/utils.jsx#L100). I can easily fix this by appending `silent` in the app.

But this means that the app doesn't follow OS settings (Windows 10: Settings->System->Notification and Actions, OS X: Preferences.app->Notifications). Any thoughts?

**Comment by Razzeee** [comment]
Well if there is a setting in platform to set Desktop Notification Sounds off they should probably silence the notifications too?

**Comment by jasonblais** [comment]
I think the two settings have different purpose (Mattermost Desktop Notification Sounds vs. OS Notification Sounds).

1) Suppose I have team_1 and team_2, but don't want notification sounds from team_2. I'd then go into Mattermost and set Desktop Notification Sounds off for that team only.

I will then receive sounds for team_1, but not for team_2.

2) On the other hand, I might never want notification sounds from Mattermost. In that case I would go to the OS notification settings and turn the sound off. 

I will never receive sounds for any Mattermost teams on the desktop app as long as the OS notification setting is set to off.

Thoughts @yuya-oc, @Razzeee ?

**Comment by yuya-oc** [comment]
Totally it looks correct. But the problem is **Mattermost Desktop Notification Sounds** is not controlled by `new Notification()` API. So now there are 4 cases.

|No.|Settings|Sound|Note|
|---|---|---|---|
|1|Mattermost:On, OS:On|Mattermost and OS|should be one sound|
|2|Mattermost:On, OS:Off|Mattermost|should be Off|
|3|Mattermost:Off, OS:On|OS|should be Off|
|4|Mattermost:Off, OS:Off|(Off)|-|

In my thought, the best possible way is that Mattermost server doesn't play the sound in the app, and the server sets `silent:true` to `new Notification` when **Mattermost Desktop Notification Sounds** is "Off".

**Comment by Razzeee** [comment]
> In my thought, the best possible way is that Mattermost server never play the sound in the app, and the server sets silent:true to new Notification when Mattermost Desktop Notification Sounds is "Off".

:+1:

**Comment by jasonblais** [comment]
> In my thought, the best possible way is that Mattermost server never play the sound in the app, and the server sets silent:true to new Notification when Mattermost Desktop Notification Sounds is "Off".

@yuya-oc  - so as long as the Mattermost app plays the sound, we can't achieve case 2 in your table, correct?

I'd be happy to forward it to the platform team, I'm not sure how hard that would be for them to change (as the notification sounds need to continue to fire in the browser).

In the meantime, we could still implement the cases where the server sets `silent:true` to `new Notification` when either
 a) **Mattermost Desktop Notification Sounds** is "Off".
 b) OS sound setting is "Off".

at least achieving cases 3 and 4 above.

**Comment by Razzeee** [comment]
I'm confused now, I'll have to look at the code, but I thought that notifications using silent true should be handled by default correctly. Thought we just don't get that case from core yet. 

Is there another place platform generates notifications other than here https://github.com/mattermost/platform/blob/v3.3.0/webapp/utils/utils.jsx#L100

**Comment by yuya-oc** [comment]
> so as long as the Mattermost app plays the sound, we can't achieve case 2 in your table, correct?

@jasonblais Yes. To solve this issue, the server should stop the sound in the desktop app.

For `a) Mattermost Desktop Notification Sounds is "Off".`,
There are two choices for this.
- a-1) The server sets `silent: true` in [`new Notification()`](https://github.com/mattermost/platform/blob/v3.3.0/webapp/utils/utils.jsx#L100) when the browser is the desktop app and the setting is "Off".
- a-2) The app injects `silent: true` in [`Notification override`](https://github.com/mattermost/desktop/blob/v1.3.0/src/browser/js/notification.js#L4). To take this, the way to know `Mattermost Desktop Notification Sounds is "Off".` at client side is needed (Is there API?)

For `b) OS sound setting is "Off".`,
It should be handled by OS. So both of app and server don't have to implement anything.


If `sound` and `silent` parameters of in `Notification()` were supported in many browsers, the problem would be simpler...

**Comment by jasonblais** [comment]
Got it, thanks @yuya-oc, @Razzeee! 

I'll check with the platform team next week (I'll be out for a few days) and give an update here.

This would be another great improvement as some of our users have been annoyed when they can't turn notifications off. Love the progress here.

**Comment by Razzeee** [comment]
@jasonblais Please also mention that the android app always plays sound on notifications even if your phone is on vibrate

**Comment by jasonblais** [comment]
Thanks @Razzeee! Will be sure to mention both.

Removing v1.4 label since it's something for the platform team to consider first.

**Comment by jasonblais** [comment]
Have talked to the platform team and created a Jira ticket: https://mattermost.atlassian.net/browse/PLT-4261

Would someone on the desktop community like to submit a pull request so that 

IF
 - someone sets desktop sound notifications off from Mattermost Account Settings, AND
 - browser corresponds to the desktop app

THEN
 - the Mattermost server sets `silent: true` in new `Notification()`

The pull request would be on the server side (in https://github.com/mattermost/platform)

**Comment by jasonblais** [comment]
Thanks @yuya-oc for the pull request, [it was merged today in platform repo](https://github.com/mattermost/platform/pull/4192) and should fix the issue.

Closing per https://github.com/mattermost/platform/pull/4192

**Comment by krobi64** [comment]
I still see this behavior on the Mac app.

**Comment by jasonblais** [comment]
Which Desktop App version are you using? @krobi64 

You can find out the version from "Help" menu > Version
