### ISSUE TITLE
Linux has annoying extra notification "Mattermost Desktop App is ready."

### ISSUE THREAD

**Issue by nearapogee** [mattermost/desktop#2271]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

App gets an extra `"Mattermost Desktop App" is ready.` notification along side other notifications.

**Environment**
- Operating System: Linux / PopOS 22.04
- Mattermost Desktop App version: 5.1.1 
- Mattermost Server version: 7.1.0 

**Steps to reproduce**
- Open app
- Get a notification
- Get a second notification "Mattermost Desktop App is ready."

**Expected behavior**
- Open app
- Get a notification

**Observed behavior**
- Open app
- Get a notification
- Get a second notification "Mattermost Desktop App is ready." See image:

![image](https://user-images.githubusercontent.com/175446/194129240-48f57f10-5bcc-457c-bff7-de3307df45de.png)

**Possible fixes**

Searched source code for "is ready" and didn't see anything. That string is in some notifications for new versions, but not this exact message.

I would like to be able to shut them off, so I get the exact number of beeps and/or notifications for the number of messages received. I usually run with notifications in "Do not disturb" in my OS so that these aren't annoying, but then it is easy to miss things.

I will report back if after upgrading the server this issue persists, but it has been here for some time.

**Comment by njnatale-lm** [comment]
That alert looks like a GNOME alert to let you know that an application has started but is not visible. Looks like some have created ways around this alert: https://extensions.gnome.org/extension/1007/window-is-ready-notification-remover/

**Comment by nearapogee** [comment]
Much thanks!
