### ISSUE TITLE
Windows: If "Start app on login." is set to True, start the app automatically, but keep the window minimized in the taskbar until the user has set focus to the app

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#228]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [X] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [X] This is a product defect issue that can be reproduced using the steps listed below.
- [X] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

If "Start app on login." is set to True, start the app automatically, but keep the window minimized until the user has set focus to the app

#### Steps to reproduce

On
- Windows 10,
- Mattermost Desktop v1.3,
- Mattermost Server v3.2

1. In **Desktop Settings**, set `Start app on login.` to `True`.
2. Restart your machine.

#### Expected behavior

App launches automatically, but remains minimized in the taskba until the user has set focus on the app.

#### Observed behavior

App launches automatically, and is focused on launch.

This means that if the user has opened another program while Mattermost desktop is launching, the desktop app will open on top. This can be annoying and interrupt user's work.

#### Possible fixes

**Comment by yuya-oc** [comment]
Auto-starting was implemented with `node-auto-launch`. @Razzeee Would you check this?
