### ISSUE TITLE
No desktop notification is sent for last open channel on macOS desktop

### ISSUE THREAD

**Issue by MaPaw** [mattermost/desktop#2288]
Per Mattermost guidelines, GitHub issues are for bug reports: <https://handbook.mattermost.com/contributors/contributors/ways-to-contribute/>.

For troubleshooting see: https://forum.mattermost.com/.
For feature proposals see: https://www.mattermost.com/feature-ideas/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://mattermost.com/security-vulnerability-report/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
No desktop notification appears when a new message arrives in the last open channel even though the desktop app is not in focus or no window is currently open.

#### Steps to reproduce
How can we reproduce the issue (what version are you using?) I am using version 5.1.1 of the dekstop app.
To reproduce:
1. open the mattermost desktop app
2. open a channel
3. switch to another application or close the mattermost window but leave the mattermost app running
4. send a message to the channel opened above

#### Expected behavior
Describe your issue in detail
A desktop notification should appear, the mattermost icon in the menubar should show a dot and the mattermost icon in the doc should show a red dot with the number of new messages

#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.
Nothing happens when a new message arrives in the selected channel.  When I manually open the mattermost window again, the new messages show but no notifications are shown, nor any dots in the menubar and dock icons.

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by amyblais** [comment]
@MaPaw What Mattermost server version are you on?

**Comment by MaPaw** [comment]
I am sorry but I cannot find the server version.  Could you please let me know where I can find it?

**Comment by MaPaw** [comment]
Thank you, but I think this is just the desktop version.  It says Version 5.1.1 (5.1.1.20701).

**Comment by amyblais** [comment]
1. I've attached a screenshot of where to find the server version (see attached image).
2. Please also help check if you see any console log errors - instructions are here https://docs.mattermost.com/install/desktop-app-install.html#report-desktop-app-issues.
3. Also, what MacOS version are you on?

<img width="252" alt="Screenshot at Oct 17 08-51-48" src="https://user-images.githubusercontent.com/29708087/196182173-65806d14-891b-4926-b743-193c44e81707.png">

**Comment by MaPaw** [comment]
1. Thank you, the server version is 7.2.0
2. The console log shows this:
```
VM5:258 Preload initialized
index.jss:151 Loading plugin com.github.manland.mattermost-plugin-gitlab, version 1.3.0
index.jss:151 Loading plugin playbooks, version 1.29.1
index.jss:151 Loading plugin focalboard, version 7.1.0
index.jss:151 Loading plugin com.mattermost.wrangler, version 0.6.0
index.jss:137 Loaded plugin com.github.manland.mattermost-plugin-gitlab, version 1.3.0
index.jss:137 Loaded plugin playbooks, version 1.29.1
focalboard_5908048cb7c76bc1_bundle.js:2 [1665988888.26] OctoClient baseURL: https://mattermost.geomar.de/plugins/focalboard
index.jss:137 Loaded plugin focalboard, version 7.1.0
index.jss:137 Loaded plugin com.mattermost.wrangler, version 0.6.0
/api/v4/trial-license/prev:1          Failed to load resource: the server responded with a status of 403 ()
websocket.tss:95 websocket connecting to wss://mattermost.geomar.de/api/v4/websocket
VM5:348 registering Mattermost v5.1.1 with the server
/api/v4/analytics/old?name=standard&team_id=:1          Failed to load resource: the server responded with a status of 403 ()
Metropolis-SemiBold.woff2:1          Failed to load resource: the server responded with a status of 404 ()
websocket.tss:180 got connection id  p8bgoz4jtp8yfgor1ntej896ma
Metropolis-SemiBoldItalic.woff2:1          Failed to load resource: the server responded with a status of 404 ()
needs_team.tsxx:106 computer woke up - fetching latest
```
3. The MacOS version is 12.6

**Comment by devinbinnie** [comment]
@MaPaw I'm unable to reproduce this on community with the latest nightly build. Can you give that build a shot? You can find it here: https://community.mattermost.com/core/channels/desktop-builds

If it still reproduces, it could be an issue with the Mattermost server not sending notifications. If that's the case, you can turn on Debug logging in the Settings window and test for notifications. You should see them in the logs if they're being sent by the server.

**Comment by MaPaw** [comment]
Thank you, the nightly build notifies correctly.
