### ISSUE TITLE
Blurry tray icon on Linux/XFCE

### ISSUE THREAD

**Issue by prudloff-insite** [mattermost/desktop#2289]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: Linux Mint 20
- Mattermost Desktop App version: 5.1.1 
- Mattermost Server version: 7.1.2 

**Steps to reproduce**

I am using XFCE with xfce4-panel 4.14.3. My toolbar contains the notification area item and the Mattermost tray icon is displayed in this area.
In the area settings, I have the max icon size set to 22.

**Expected behavior**
The icon should be crisp.

**Observed behavior**
The icon is blurry. (Other app icons are displayed correctly.)

![image](https://user-images.githubusercontent.com/50333926/196415542-1a243dcc-7b24-4cf5-ba82-7bca519a2b7a.png)

**Comment by devinbinnie** [comment]
I can reproduce this as well. Unfortunately we don't really support Linux Mint or XFCE, and this is a small cosmetic bug, it won't be worked on for a while.

I'm going to open this as Help Wanted in case anyone is interested in fixing this.

**Comment by Daylien** [comment]
Hey @prudloff-insite,

I had the same issue (note that I'm running KDE not XFCE4, but the blurry icon in your screenshots looked the same), the blurry icon can be fixed (at least for me) if you install `libappindicator-gtk2` and/or `libappindicator-gtk3`. I'm running an Arch based distro I think in Mint the package is called `libappindicator1` and/or `libappindicator3-1`.

I hope this helps

**Comment by prudloff-insite** [comment]
I checked and libappindicator1 and libappindicator3-1 are already installed.

**Comment by Daylien** [comment]
That's unfortunate, I will try it with an XFCE4 installation in Mint within the next week.

**Comment by Daylien** [comment]
Hey @prudloff-insite,

I'm sorry for my late response. I am currently writing my thesis so please excuse this late reply.
I installed a fresh Debian 11 instance with the basic XFCE4 environment. My tray icon is definitely not blurry. You can see it in the screenshot below. I have `libayatana-appindicator3` installed and it renders just fine.

![image](https://user-images.githubusercontent.com/22529605/216724116-8791645b-924d-429c-811f-c524b8f6d488.png)

**Comment by prudloff-insite** [comment]
This seems to be fixed in 5.2.2.
