### ISSUE TITLE
After clicking on Desktop app and putting it in focus keyboard shortcuts don't work

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#231]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [X] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [X] This is a product defect issue that can be reproduced using the steps listed below.
- [X] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

After clicking on Desktop app and putting it in focus keyboard shortcuts don't work

#### Steps to reproduce

1) Have Desktop app open on desktop without focus, then click on Desktop app and hit "CTRL+K".
OR
2) Have Desktop app open, switch tabs, then hit "CTRL+K"

EXPECTED:
Channel picker UI appears

OBSERVED:
Nothing happens. It requires a SECOND click on the app before keyboard shortcuts work.

NOTES:
This occurs on 
a) Windows 10, Mattermost Server v3.2/v3.3 and Desktop App v1.3.
b) Ubuntu 16.04, Mattermost Server v3.3 and Desktop App v1.3.

This doesn't repro if a user clicks on the system tray icon or the taskbar icon.

**Comment by yuya-oc** [comment]
Reproduced on Windows 10, but not reproduced on OS X 10.11.5.

@jasonblais Probably it happens when clicking the region of webview. Would you check?

**Comment by yuya-oc** [comment]
It seems the behavior is caused by side effects of f2209aa9 for #10. So after reverting the change, we have to handle the focus of input.

**Comment by jasonblais** [comment]
That's correct @yuya-oc, it reproduces when clicking on the webview region.

Would there be an alternative way to fixing #10?

**Comment by jasonblais** [comment]
There is another note that this reproduces on Linux: https://github.com/mattermost/desktop/pull/258#issuecomment-241277494

(Keyboard shortcuts don't work when clicking on the `WebView` after switching tabs or clicking somewhere into the Tab header.)

**Comment by yuya-oc** [comment]
Created the PR as #262.
