### ISSUE TITLE
Enable standard shortcuts for zooming in/out 

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#232]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [X] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [X] This is a product defect issue that can be reproduced using the steps listed below.
- [X] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

These are standard shorcuts that should work in any app.

Zoom in:
 - CTRL+PLUS
 - CTRL+=
 - CTRL+SHIFT+= [already implemented]

Zoom out:
 - CTRL+MINUS [already implemented]
 - CTRL+SHIFT+MINUS

^Mac-equivalent shortcuts replaces CTRL with CMD.

Right now we have one which requires `SHIFT` to work, and another which doesn't. We've got reports from people confused about it and having to work with either too small or too large text before figuring it out.

**Comment by jasonblais** [comment]
I see, thanks for the note!

Do we have an idea on potential turn-around from issue filing to fixing the issue? 

Probably depends whether someone in the community submits a pull request for the issue.

**Comment by jasonblais** [comment]
Actually, we can continue discussion in the pull request @akashnimare submitted here: https://github.com/mattermost/desktop/pull/234

**Comment by yuya-oc** [comment]
Should be closed by #234
