### ISSUE TITLE
macos-notification-state module imported but unavailable on non-macOS

### ISSUE THREAD

**Issue by selfisekai** [mattermost/desktop#2334]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
App imports macOS-specific native node module, which does not get built on Linux by module author's design

**Environment**
- Operating System: Alpine Linux edge
- Mattermost Desktop App version: 5.2.0 
- Mattermost Server version: N/A 

**Steps to reproduce**
try opening a mattermost-desktop build in electron

**Expected behavior**
app opens successfully

**Observed behavior**
app fails to open, the electron process keeps running anyway. in terminal:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Could not locate the bindings file. Tried:
 → /usr/lib/mattermost/app.asar/node_modules/macos-notification-state/build/notificationstate.node
 → /usr/lib/mattermost/app.asar/node_modules/macos-notification-state/build/Debug/notificationstate.node
 → /usr/lib/mattermost/app.asar/node_modules/macos-notification-state/build/Release/notificationstate.node
 → /usr/lib/mattermost/app.asar/node_modules/macos-notification-state/out/Debug/notificationstate.node
 → /usr/lib/mattermost/app.asar/node_modules/macos-notification-state/Debug/notificationstate.node
 → /usr/lib/mattermost/app.asar/node_modules/macos-notification-state/out/Release/notificationstate.node
 → /usr/lib/mattermost/app.asar/node_modules/macos-notification-state/Release/notificationstate.node
 → /usr/lib/mattermost/app.asar/node_modules/macos-notification-state/build/default/notificationstate.node
 → /usr/lib/mattermost/app.asar/node_modules/macos-notification-state/compiled/16.16.0/linux/x64/notificationstate.node
 → /usr/lib/mattermost/app.asar/node_modules/macos-notification-state/addon-build/release/install-root/notificationstate.node
 → /usr/lib/mattermost/app.asar/node_modules/macos-notification-state/addon-build/debug/install-root/notificationstate.node
 → /usr/lib/mattermost/app.asar/node_modules/macos-notification-state/addon-build/default/install-root/notificationstate.node
 → /usr/lib/mattermost/app.asar/node_modules/macos-notification-state/lib/binding/node-v109-linux-x64/notificationstate.node
    at bindings (/usr/lib/mattermost/app.asar/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/usr/lib/mattermost/app.asar/node_modules/macos-notification-state/lib/index.js:1:34)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13339)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.defineProperty.value (/usr/lib/mattermost/app.asar/index.js:53778:18)
```

**Possible fixes**

do not import macos-notification-state if not on macOS

**Comment by devinbinnie** [comment]
@selfisekai We don't generally support Alpine Linux just in general, so there could be an issue building. Did you make sure to install all the required dependencies as per this document: https://developers.mattermost.com/contribute/more-info/desktop/developer-setup/

It looks to me like the version that was built is missing those packages, and those files are required for the app to run, despite not being necessary for the specific OS you're using.

**Comment by selfisekai** [comment]
ok, I found the root cause. `macos-notification-state` does not define an `install` script, or even depend on `node-gyp`. I actually have no clue how does this package work anywhere. anyway, this means `npm rebuild macos-notification-state` does nothing. so, my current solution is this:
```
	(
		cd node_modules/macos-notification-state
		../.bin/node-gyp rebuild --build-from-source --nodedir=/usr/include/electron/node_headers
	)
```

I'm gonna make a PR to the module

**Comment by devinbinnie** [comment]
> ok, I found the root cause. `macos-notification-state` does not define an `install` script, or even depend on `node-gyp`. I actually have no clue how does this package work anywhere. anyway, this means `npm rebuild macos-notification-state` does nothing. so, my current solution is this:
> 
> ```
> 	(
> 		cd node_modules/macos-notification-state
> 		../.bin/node-gyp rebuild --build-from-source --nodedir=/usr/include/electron/node_headers
> 	)
> ```
> 
> I'm gonna make a PR to the module

Huh, that's weird because we've added our own patch to that module to make sure it builds correctly:
`"postinstall": "node scripts/patch_macos_notification_state.js && electron-builder install-app-deps"`

Is your build for some reason not running `npm run postinstall`?

**Comment by selfisekai** [comment]
yes, I routinely add `--ignore-scripts` to npm/yarn commands for electron app build scripts and then run `npm rebuild` for the needed dependencies, as the scripts often download binaries built for GNU libc which won't work on Alpine (`electron`, `playwright`, ...), and I use electron_tasje as a replacement for electron-builder to avoid, among others, the binary downloads, building dependencies with downloaded headers for a different electron version than in the repositories, to get the `.desktop` files generated (not available in electron-builder on target=dir), and so on.

**Comment by devinbinnie** [comment]
Ahh that makes sense. I was planning on sending an update to the module at some point, but since we wanted to release sooner rather than later we opted to fix it ourselves.

**Comment by selfisekai** [comment]
PR sent: https://github.com/felixrieseberg/macos-notification-state/pull/34
