### ISSUE TITLE
Onboarding screen blocked at the step of adding a new server despite the DefaultServerList GPO

### ISSUE THREAD

**Issue by cyberm8** [mattermost/desktop#2335]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

Despite the configuration of Mattermost servers by GPO, the onboarding screen in version 5.2.0 requires the manual configuration of a server to access the application.

**Environment**
- Operating System: Windows 10 + Windows server 2019 with Mattermost 5.2.0 admx pack
- Mattermost Desktop App version: 5.2.0 (via msi installer)
- Mattermost Server version: 7.2.0

**Steps to reproduce**

- Configure group policy "DefaultServerList" ;
- Install Mattermost Desktop 5.2.0 ;
- Open Mattermost Desktop.

![image](https://user-images.githubusercontent.com/117109145/199072636-8754b662-8233-417e-957d-84d5cac757f5.png)

**Expected behavior**

- The user should not need to configure any servers as these are managed by a GPO ;
- The user should land directly on the discussion channels.

**Observed behavior**

- The user remains stuck on the "Let's connect to a server" onboarding page ;
- It seems to be mandatory to fill in the server information ;
- The server pushed by GPO does appear at the top left, but the button is greyed out.

![image](https://user-images.githubusercontent.com/117109145/199071869-8cb30fcb-a9f8-48b8-8982-5ad022f04db6.png)

**Possible fixes**

N/A.

**Comment by markatk** [comment]
Same issue on our installation. We get quite a lot of complains from our users, I hope this is fixed quite fast.

**Comment by slate17** [comment]
Same Issue here. Hope this gets fixed fast, very annoying for the users.

**Comment by devinbinnie** [comment]
Fixed by https://github.com/mattermost/desktop/pull/2346

**Comment by kairauer** [comment]
I've updated to 5.2.1. Doesn't seem to be fixed yet.

**Comment by markatk** [comment]
For our installation it seems to be fixed with version 5.2.1.

**Comment by Cl4whammer** [comment]
Nope, not fixed, at least not at my system. I was still on the working 5.1.1 and updated today to 5.2.1 and iam now getting this screen every time i restart the app.

**Comment by bokkabonga** [comment]
Same here. Not fixed with 5.2.1

**Comment by slate17** [comment]
Same here. Just rolled out the update to 5.2.1 and got the Onboarding Screen again.
