### ISSUE TITLE
[v5.2.0] The phenomenon that the server URL scheme is forced to be overwritten to http and port to 8065

### ISSUE THREAD

**Issue by tatsuyasenbom** [mattermost/desktop#2337]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
- If you change the server URL to https://hogefuga.jp and then restart the application, it will be overwritten by http://hogefuga:8065.
    - ![image](https://user-images.githubusercontent.com/87968771/199132768-cb3ace9b-8963-4498-837a-e7a4d778bcb6.png)
- This could not be confirmed for the v5.1.1 version.

**Environment**
- Operating System: Windows 11 22H2
    - ![image](https://user-images.githubusercontent.com/87968771/199132450-b5774ad1-76ed-4331-86f1-d9960ea2ca6b.png)
- Mattermost Desktop App version: v5.2.0
    - ![image](https://user-images.githubusercontent.com/87968771/199132499-e3769c3b-fad1-43e6-97a8-7f51fd9c1c24.png)
- Mattermost Server version: v7.4.0

**Comment by jaehyun-ko** [comment]
I have same error, and it overwritten as https://example.mattermost.com.

**Comment by devinbinnie** [comment]
@tatsuyasenbom @jaehyun-ko We added a feature that forces the configured URL to be changed to the SiteURL configured by your system adminstrator. This is expected behaviour.

**Comment by jaehyun-ko** [comment]
@devinbinnie How can I config it?

**Comment by tatsuyasenbom** [comment]
> @tatsuyasenbom @jaehyun-ko We added a feature that forces the configured URL to be changed to the SiteURL configured by your system adminstrator. This is expected behaviour.

Thank you!

The following steps have improved the situation.

```sh
# vim /opt/mattermost/config/config.json
{
    "ServiceSettings": {
        "SiteURL": "https://hogefuga.jp",
        :
    },
    :
}
# systemctl restart mattermost
```

**Comment by devinbinnie** [comment]
Closing as per above.
