### ISSUE TITLE
5.2.0 file: cannot download for linux ia32

### ISSUE THREAD

**Issue by ceamac** [mattermost/desktop#2347]
Hi,

Not sure if this is a bug or troubleshooting, I'll ask here.

Cannot download https://releases.mattermost.com/desktop/5.2.0/mattermost-desktop-5.2.0-linux-ia32.tar.gz, it says Acces Denied.

Thank you!

**Comment by anx-ag** [comment]
Hi ceamac,

Linux IA32 support has been dropped with this release as mentioned in the release notes:
https://docs.mattermost.com/install/desktop-app-changelog.html#linux

**Comment by ceamac** [comment]
Thank you!
