### ISSUE TITLE
Extra gray bar with "<- Back" entry appears on Windows Desktop 5.2.0

### ISSUE THREAD

**Issue by acataluddi** [mattermost/desktop#2351]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---
Hi, 

After the upgrade to version 5.2.0, an extra gray bar containing only a "<- Back" entry appears and I cannot get rid of it.

![immagine](https://user-images.githubusercontent.com/8874358/199738837-05241452-a07a-4ada-bfe9-d9ffcc7a2b58.png)

**Summary**

**Environment**
- Operating System: Windows 11 Enterprise (21H2)
- Mattermost Desktop App version: 5.2.0
- Mattermost Server version: 6.0.0

**Steps to reproduce**
Just launch the desktop application.

**Expected behavior**
The bar was expected to be missing.

**Observed behavior**
There is an extra bar.

Thanks,
Adriano C.

**Comment by devinbinnie** [comment]
@acataluddi Do you have your SiteURL configured correctly on your server? With v5.2 we've made sure that the SiteURL matches the URL configured by the server.

Is there a proxy or a redirect happening here somewhere?

**Comment by acataluddi** [comment]
Hi @devinbinnie,

Thank you very much for your help. The `SiteURL` configuration helped me solving the problem. Basically, while the client was using an URL like `https://chat.example.com`, on the server was only configured the `http://` counterpart. By synchronising the settings and putting everything on HTTPS, the gray bar disappeared.

Thank you for your help.
Adriano C.

**Comment by nickolasdeluca** [comment]
> @acataluddi Do you have your SiteURL configured correctly on your server? With v5.2 we've made sure that the SiteURL matches the URL configured by the server.
> 
> Is there a proxy or a redirect happening here somewhere?

What if there was? We currently have a proxy setup and it's been showing the white bar with the back button... What should I do to make it disappear?

**Comment by devinbinnie** [comment]
@nickolasdeluca Is the server always connected to via the proxy? If so it might make sense to change the Site URL to the proxy URL. There are a couple other benefits to this because we use the Site URL in the web app itself to map certain URLs (mostly in plugins)

**Comment by nickolasdeluca** [comment]
> @nickolasdeluca Is the server always connected to via the proxy? If so it might make sense to change the Site URL to the proxy URL. There are a couple other benefits to this because we use the Site URL in the web app itself to map certain URLs (mostly in plugins)

Yes, it is. I just talked to our head of IT and the proxy I mentioned previously is a reverse proxy. Also the `SiteURL` is already set to the URL set in this reverse proxy. Another thing worth mentioning, our url is set to https protocol but the certificate is not set in the config.json... Can this cause the issue?
