### ISSUE TITLE
Mattermost desktop no longer asks where files are to be downloaded *at time of download*

### ISSUE THREAD

**Issue by tritium21** [mattermost/desktop#2352]
What it says on the tin.  This is a major show stopper bug.

**Comment by tritium21** [comment]
yes, this is the bug i am reporting.  it does this behavior rather than open a file dialog, as is the obvious, and desirable behavior.

**Comment by devinbinnie** [comment]
@tritium21 You can work around this by removing the default downloads folder in your configuration settings. This has always been the behaviour that the app has used at least since v5.1 as well. It's possible that now that you have a default directory set that you're seeing a different behaviour.

We can look into a way to reset it more easily, but for now if you want to see the dialog persist, you can go to the config.json file in your config directory (depending on OS) and remove it. I can provide you with a location if you tell me which OS you're using.

**Comment by tritium21** [comment]
>This has always been the behaviour that the app has used at least since v5.1 as well. It's possible that now that you have a default directory set that you're seeing a different behaviour.

incorrect.  In v5.1 a default location simply picked the location a file dialog opened in, it did not skip the dialog.

**Comment by jordanafung** [comment]
Hi @tritium21 
Thank you for your feedback. We understand that you don't agree with many other folks about the usefulness of a feature that was asked for and implemented. You were given an alternate option to disable this feature and get the dialog back.
I've just tested the workaround that @devinbinnie offered and can confirm it works.

We appreciate that we won't always agree on things, but as a reminder, our [Code of Conduct](https://handbook.mattermost.com/contributors/contributors/guidelines/contribution-guidelines#our-standards) notes that our standards include "Being respectful of differing opinions, viewpoints, and experiences".
We want to ensure that we best serve our community, and as such, we all (Mattermost employees as well as community members) abide by our [Community Expectations](https://developers.mattermost.com/contribute/good-decisions/).
In this case, we are happy to accept a [feature request](https://handbook.mattermost.com/operations/research-and-development/product/product-planning/feature-requests) to add an option to always ask where a file is saved, and as mentioned, we can look for a way to implement a way to more easily reset the default download option, but in the meantime removing the download location from your config.json works.

I feel both @devinbinnie and @tboulis have been gracious and understanding of your concerns and explained our reasoning for implementing this feature.
We are not perfect, nor do we expect anyone to be, as we are all human. As such, we have noted your feedback and will create a feature request on your behalf.

In the meantime, please try the solution provided and let us know if you have any questions or concerns.

**Comment by tritium21** [comment]
The solution you gave is "roll back to the previous version" or "Manually edit a file in a hidden folder"

Why am i still paying for this?

**Comment by HedererAndreas** [comment]
In the Windows-App you can change standard download folder at file->settings->download folder:

![Image](https://github.com/user-attachments/assets/0c672159-08d8-4f5f-8494-0023e391bcd2)
