### ISSUE TITLE
Existing instance in system tray is not reused when starting the application

### ISSUE THREAD

**Issue by nmatt** [mattermost/desktop#236]
I confirm (by marking "x" in the [ ] below): 

- [ x] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [ x] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [ x] This is a product defect issue that can be reproduced using the steps listed below.
- [ x] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

When closing the application window, minimizing it to the system tray, then restarting the applications opens a new instance instead of reactivating the one in the system tray. Closing the new instance window adds another instance to the system tray. This is very unexpected and inconvenient for a system tray application.

#### Steps to reproduce

- Operating System: Windows 7 Pro
- Mattermost Desktop App version: 1.3.0
- Mattermost Server version (See Main Menu > About Mattermost) — There is no "About Mattermost" in the main menu.
Steps to reproduce the issue:
1) Start the Mattermost desktop application.
2) Close the application window to minimize the application to the system tray.
3) Start the Mattermost desktop application again from the Start menu or a pinned task bar icon.
4) Close the new application window

#### Expected behavior

In step 3, the existing system tray instance would be reused.
Step 4 would not create an additional instance in the system tray.

#### Observed behavior

Step 3 creates a new Mattermost application instance in addition to the system tray instance.
Step 4 adds another Mattermost instance to the system tray.
Repeating step 3 and 4 creates an unlimited number of Mattermost instances running in the system tray.

**Comment by jasonblais** [comment]
Thanks for the feature request @nmatt,

@jgis, thank you for working on this, please let us know if you have questions. Would love to see a pull request for it and test it out
