### ISSUE TITLE
No convenient way to reactivate system tray instance via keyboard

### ISSUE THREAD

**Issue by nmatt** [mattermost/desktop#237]
I confirm (by marking "x" in the [ ] below): 

- [ x] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [ x] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [ x] This is a product defect issue that can be reproduced using the steps listed below.
- [ x] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

There is no convenient way, like a global keyboard shortcut, to reactivate a Mattermost instance from the system tray via keyboard.

#### Steps to reproduce

- Operating System: Windows 7 Pro
- Mattermost Desktop App version: 1.3.0
- Mattermost Server version (See Main Menu > About Mattermost) — There is no "About Mattermost" in the main menu.
Steps to reproduce the issue: n/a

#### Expected behavior

It should be possible to configure a global keyboard shortcut. Alternatively (or even preferably), starting the application again should reactivate the existing instance in the system tray (cf. issue #236). That way it would be possible to pin the Mattermost application to the task bar and use Win+<digit> to both start or reactivate it.

In previous versions, it was possible to use Alt+Tab to switch to an existing Mattermost instance. Now that Mattermost minimizes to the system tray, that is not possible any more.

P.S.: I wrote "no convenient way" instead of just "no way" because it is actually possible to use the key sequence Win, Esc, Tab, Tab, Space, Arrow keys and Return to access the system tray via keyboard and reopen the Mattermost application from there; but that's very far from a practical solution.

#### Observed behavior

n/a

**Comment by jasonblais** [comment]
Apologies @nmatt for the delay here. Thank you for the feedback!

First, you can still minimize the Mattermost application to the taskbar either
a) using the shortcut `CTRL+M`,
b) going to **Window > Minimize** in the menu bar
c) minimizing the app by clicking "-" on the top right corner

Second, it's not immediately obvious to me what an appropriate shortcut would be to reactivate the system tray instance via keyboard. If you'd like to see this feature, can we have your help adding it as a feature request in [Feature Idea Forums](https://mattermost.uservoice.com/forums/306457-general/category/159795-mattermost-app-windows-mac-and-linux) so that we can have the community's help discussing and upoting the feature?

**Comment by nmatt** [comment]
Thanks for the response @jasonblais. I'm aware of the minimization possiblity, however it means that Mattermost remains in the Alt+Tab task list. With the close-to-system-tray feature, I was hoping to be able to show/hide the application (by keyboard) and not have it in the Alt+Tab task list while it is hidden.

If issue #236 is implemented AND is fast enough, that would be a solution, because on Windows you can bind a Ctrl+Alt+somekey shortcut to start menu entries or use Win+digit for entries pinned to the taskbar. (I'm stressing "fast enough" because normal application startup of the desktop application is too slow for the purpose of quickly switching to Mattermost.)

Otherwise, applications with global hotkeys usually let the keyboard shortcut be defined by the user, so that conflicts with other applications can be avoided. On Windows, Ctrl+Alt+somekey and Ctrl/Shift/Alt+Win+somekey are commonly used for global hotkeys.

Regarding a feature request, I'll first wait to see how issue #236 goes.

**Comment by Razzeee** [comment]
@nmatt 
you can test the speed of #236 with this https://576-43964563-gh.circle-artifacts.com/0//tmp/circle-artifacts.Aa7PAlq/mattermost-setup-x64.exe

**Comment by nmatt** [comment]
@Razzeee: Thanks, I tried out that build. Reactivating the application that way takes just short of a second on my system (with an SSD). While that's not quite as instantaneous as when reopening the application window from the system tray, it's probably good enough I guess. Looking forward to have this in the next official relase.

**Comment by yuya-oc** [comment]
Closed by merging #247.
