### ISSUE TITLE
5.2.0 - Windows 8 - no notification popup

### ISSUE THREAD

**Issue by licaon-kter** [mattermost/desktop#2373]
Works fine on 5.1.1

**Comment by amyblais** [comment]
Are you on Windows 8.1?

**Comment by licaon-kter** [comment]
Ah indeed, there a difference. Yes, latest 8.1.

**Comment by jgilliam17** [comment]
@amyblais I checked our QA device list and don't see anyone listed in possession of Win8. I can try to create a VM and see if notifications can be tested that way.

**Comment by jgilliam17** [comment]
I created a vm with Win8 and I am not getting any notifications. Tested using Desktop v5.2.1. I'll chat with Tasos about this and post an update.
