### ISSUE TITLE
python3 in mattermost app

### ISSUE THREAD

**Issue by matthiasschroder** [mattermost/desktop#2374]
I noticed that Mattermost 5.20 universal app contains 

Mattermost.app/Contents/Resources/app.asar.unpacked/node_modules/macos-notification-state/build/node_gyp_bins/python3
Mattermost.app/Contents/Resources/app.asar.unpacked/node_modules/windows-focus-assist/build/node_gyp_bins/python3

Both are "Mach-O 64-bit executable x86_64" only.

Is it correct to assume these are build-artifacts that should have been removed?

**Comment by matthiasschroder** [comment]
Hi @tboulis , thanks a lot for the feedback. If these executables are needed it would be good to provide them as 'universal' instead of x86_64 only, otherwise the universal app is not really universal.

**Comment by devinbinnie** [comment]
@matthiasschroder Thanks for the question. I think we might have to remove these altogether anyways since they bloat the build, and I don't think we want to package them with the Mac App Store build either.
