### ISSUE TITLE
Tray icon shows non-applicable keyboard shortcuts

### ISSUE THREAD

**Issue by nmatt** [mattermost/desktop#239]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [x] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [x] This is a product defect issue that can be reproduced using the steps listed below.
- [x] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

The team menu items in the menu tray icon’s context menu show the Ctrl+<digit> keyboard shortcuts, however these are only applicable within the application window.

#### Steps to reproduce

Please include: 
- Operating System: Windows 7 Pro
- Mattermost Desktop App version: 1.3.0
- Mattermost Server version (See Main Menu > About Mattermost) : <There is no such menu entry>
- Clear steps to reproduce the issue: Right-click on the Mattermost tray icon

#### Expected behavior

No keyboard shortcut should be shown on the team menu items in the tray icon’s context menu (unless a feature for global hotkeys is added).

#### Observed behavior

The team menu items in the tray icon’s context menu show the Ctrl+<digit> keyboard shortcuts, which are only applicable within the application window.

#### Possible fixes

Don't reuse the exact same team menu items from the "Window" menu for the tray icon's context menu.

**Comment by Razzeee** [comment]
Not sure if this is valid on the other operatingsystems, but on windows it's indeed not useable. Only other app that also has these set, that I have installed is slack. They probably also did it on error? Not sure.

**Comment by jasonblais** [comment]
Thanks @nmatt, good point indeed.

I think it's re-using the shortcuts from **Menu Bar > Window**, so it would be a matter of removing the keyboard shortcuts from the list that appears after right-clicking the system tray icon.

![image](https://cloud.githubusercontent.com/assets/13119842/17624446/a9ccc90a-6072-11e6-80ce-016202cd5d51.png)


@Razzeee Would you be interested in looking into a fix?

**Comment by jasonblais** [comment]
@mmahkamov @jnugh @timroes @akashnimare: Would you be able to verify if this reproduces on OS X and Linux?

**Comment by akashnimare** [comment]
I am not sure what he's trying to say. It's working fine on OS X.

**Comment by Razzeee** [comment]
@akashnimare 
even if you have the app in the background?

**Comment by yuya-oc** [comment]
In my understanding,

- Windows: Should not work (Tray should get focus to use, but maybe cannot).
- OS X: Should not work (Probably application's menu is working).
- Linux: I'm not sure.

**Comment by Razzeee** [comment]
Then I'll just remove the accelerators from there.

**Comment by mmahkamov** [comment]
The issue is replicable on OS X 10.11.5, Mattermost Desktop 1.3.0 (actually it's an RC release but the about window doesn't show which one).

Pre-requisites:
1. Mattermost Desktop window is inactive
2. Some other window is active (e.g. Xcode)

Now if you click on the tray icon of Mattermost Desktop you'll see shortcuts listed for the team (Command + 1 in my case). Pressing Command + 1 in the active window (Xcode) won't switch me to Mattermost Desktop because that's not a global hotkey.

**Comment by yuya-oc** [comment]
Yeah, so #242 removes the shortcuts from the tray icon.
