### ISSUE TITLE
Port 8065 does not work with new Mattermost desktop App for windows

### ISSUE THREAD

**Issue by rainerZugang** [mattermost/desktop#2394]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System:
- Mattermost Desktop App version: X.X.X 
- Mattermost Server version: X.X.X 

**Steps to reproduce**
insert server address with port. For example:
http://myMattermostServer.com:8065/myMattermost/
and save it in desktop app. 
The it will all the time end in
http://myMattermostServer.com/myMattermost/
(Port 80)
**Expected behavior**
-> It should end in http://myMattermostServer.com:8065/myMattermost/ and show mattermost

**Observed behavior**
http://myMattermostServer.com/myMattermost/

**Possible fixes**

**Comment by devinbinnie** [comment]
@rainerZugang Do you have the port number included in the Site URL of your mattermost server? The new Desktop App makes sure that we use the exact Site URL provided by the web app to avoid any issues with other features.

**Comment by rainerZugang** [comment]
yes, sure I check that.
The problem is, when I enter the right port it works, but after restarting Mattermost desktop App the port information is lost

**Comment by rainerZugang** [comment]
The issue is new and exists since desktop version 5.2.0

**Comment by devinbinnie** [comment]
@rainerZugang I can't reproduce this myself. Can you double check to confirm that the Site URL you have configured on your server matches exactly the URL that shows up in the Desktop App?

If so, then can you turn on Debug logging (in the Settings Window) and post a log file when the app starts up? Thanks!

**Comment by anx-ag** [comment]
The new desktop apps inherit the connection settings from the servers's `SiteUrl` configuration option. I'm guessing that the `SiteUrl` setting in your Mattermost server's `config.json` file is set to `https://x.x.x.x" which will cause exactly this behaviour.

This is a new feature to help the server admins force the URLs used by the clients so if `https://x.x.x.x` is not a valid endpoint for your system, please change the `SiteUrl` to `http://x.x.x.x:8065`  and restart the Mattermost application service, afterwards the newer desktop clients should not change the URLs anymore.

**Comment by p-dub42** [comment]
Nailed it, @anx-ag ! There were some example settings in the docker .env file that I hadn't bothered to change. 

I had already defined the APP_PORT variable to be 8065 but also (for 5.2.x+) need to change a line from:
MM_SERVICESETTINGS_SITEURL=https://${DOMAIN}
To:
MM_SERVICESETTINGS_SITEURL=http://${DOMAIN}:${APP_PORT}

Thanks for your help.

**Comment by devinbinnie** [comment]
@rainerZugang Does the above comment fix your issue?

**Comment by anx-ag** [comment]
@p-dub42  glad to hear that this works for you now. The `APP_PORT` is not automatically added in the `env.example` file because it would not work for deployments using the nginx reverse proxy (the port of the application server is irrelevant then).

**Comment by p-dub42** [comment]
Yeah, we're using the docker image configuration without nginx. 

The only remaining quirk seems to be that the links for boards are incorrect in the DMs and channels.  They are prefixed with the old "https://${DOMAIN}" not the "http://${DOMAIN}:${APP_PORT}" for some reason, but it looks like a server issue, not a desktop client issue (if I manually fix the URL, the board is still there, just the provided links are wrong). There seems to be a history of boards not respecting the siteURL configuration, but that's a problem for another repo. :-)

**Comment by anx-ag** [comment]
Interesting finding - yes, please create the issue in the boards repo, maybe they're already aware of this issue.

**Comment by rainerZugang** [comment]
> The new desktop apps inherit the connection settings from the servers's `SiteUrl` configuration option. I'm guessing that the `SiteUrl` setting in your Mattermost server's `config.json` file is set to `https://x.x.x.x" which will cause exactly this behaviour.
> 
> This is a new feature to help the server admins force the URLs used by the clients so if `https://x.x.x.x` is not a valid endpoint for your system, please change the `SiteUrl` to `http://x.x.x.x:8065` and restart the Mattermost application service, afterwards the newer desktop clients should not change the URLs anymore.

Hi, I tried this now. Hopefully it works. Indeed in my config :8065 was missing..I will test it a few days

**Comment by anx-ag** [comment]
@eladyarom I cannot answer the questions as to why and what, because I'm just here for the fun, but to be honest, every Mattermost tutorial tells you to configure the SiteURL properly and make sure that it matches what users use to connect and I think (but this is just my assumption as a user) that the amount of people not having followed this configuration advise was underestimated.

**Comment by rainerZugang** [comment]
yes it worked. in the config the port was missing

**Comment by rainerZugang** [comment]
yes it worked. in the config the port was missing
