### ISSUE TITLE
5.2.1 on MacOS 13.0.1 (M1 chip)

### ISSUE THREAD

**Issue by srzkptrsk** [mattermost/desktop#2411]
Desktop app not visible after launch.

**Environment**
- Operating System:
- Mattermost Desktop App version: 5.2.1
- Mattermost Server version: 7.5.1

**Comment by nab-77** [comment]
@srzkptrsk Can you share more about not visible?

**Comment by devinbinnie** [comment]
@srzkptrsk Can you grab the logs from this location: https://docs.mattermost.com/install/troubleshooting.html#mattermost-desktop-app-logs and post them here? Thanks!

**Comment by srzkptrsk** [comment]
> @srzkptrsk Can you grab the logs from this location: https://docs.mattermost.com/install/troubleshooting.html#mattermost-desktop-app-logs and post them here? Thanks!

cat main.log
[2022-11-22 15:46:32.036] [debug] DownloadsManager.init {
  'this.json': {
    'vnds.png': {
      addedAt: 1668769859703,
      filename: 'vnds.png',
      mimeType: 'image/png',
      location: '/var/folders/cp/wg5w638s63s9v68kg080xcx80000gn/T/Mattermost.Desktop/vnds.png',
      progress: 100,
      receivedBytes: 94265,
      state: 'interrupted',
      totalBytes: 94265,
      type: 'file',
      bookmark: 'Ym9va8ACAAAAAAQQMAAAAEpMdN5Iwfl1pi6d+rhiISGzYN+X5MFFwkSCUArGadhdvAEAAAQAAAADAwAAAAgAKAUAAAABAQAAVXNlcnMAAAARAAAAAQEAAHNpYXJ6dWtwaWF0cm91c2tpAAAABwAAAAEBAABEZXNrdG9wAAgAAAABAQAAdm5kcy5wbmcQAAAAAQYAABAAAAAgAAAAPAAAAEwAAAAIAAAABAMAALlcAAAAAAAACAAAAAQDAACdvAMAAAAAAAgAAAAEAwAAt48EAAAAAAAIAAAABAMAANfnyQMAAAAAEAAAAAEGAAB0AAAAhAAAAJQAAACkAAAACAAAAAAEAABBxJPP4bpJZBgAAAABAgAAAQAAAAAAAAAPAAAAAAAAAAAAAAAAAAAACAAAAAQDAAACAAAAAAAAAAQAAAADAwAA9QEAAAgAAAABCQAAZmlsZTovLy8MAAAAAQEAAE1hY2ludG9zaCBIRAgAAAAEAwAAAJCClucAAAAIAAAAAAQAAEHEhebagAAAJAAAAAEBAABGRTQxNjEzMS05N0Y2LTQ3MjUtODEyNS1DODg4MjZDQjFDMTgYAAAAAQIAAIEAAAABAAAA7xMAAAEAAAAAAAAAAAAAAAEAAAABAQAALwAAAAAAAAABBQAAzAAAAP7///8BAAAAAAAAABAAAAAEEAAAXAAAAAAAAAAFEAAAtAAAAAAAAAAQEAAA3AAAAAAAAABAEAAAzAAAAAAAAAACIAAAqAEAAAAAAAAFIAAAGAEAAAAAAAAQIAAAKAEAAAAAAAARIAAAXAEAAAAAAAASIAAAPAEAAAAAAAATIAAATAEAAAAAAAAgIAAAiAEAAAAAAAAwIAAAtAEAAAAAAAABwAAA/AAAAAAAAAARwAAAIAAAAAAAAAASwAAADAEAAAAAAAAQ0AAABAAAAAAAAAA='
    }
  },
  validatedJSON: {
    'vnds.png': {
      addedAt: 1668769859703,
      filename: 'vnds.png',
      mimeType: 'image/png',
      location: '/var/folders/cp/wg5w638s63s9v68kg080xcx80000gn/T/Mattermost.Desktop/vnds.png',
      progress: 100,
      receivedBytes: 94265,
      state: 'interrupted',
      totalBytes: 94265,
      type: 'file',
      bookmark: 'Ym9va8ACAAAAAAQQMAAAAEpMdN5Iwfl1pi6d+rhiISGzYN+X5MFFwkSCUArGadhdvAEAAAQAAAADAwAAAAgAKAUAAAABAQAAVXNlcnMAAAARAAAAAQEAAHNpYXJ6dWtwaWF0cm91c2tpAAAABwAAAAEBAABEZXNrdG9wAAgAAAABAQAAdm5kcy5wbmcQAAAAAQYAABAAAAAgAAAAPAAAAEwAAAAIAAAABAMAALlcAAAAAAAACAAAAAQDAACdvAMAAAAAAAgAAAAEAwAAt48EAAAAAAAIAAAABAMAANfnyQMAAAAAEAAAAAEGAAB0AAAAhAAAAJQAAACkAAAACAAAAAAEAABBxJPP4bpJZBgAAAABAgAAAQAAAAAAAAAPAAAAAAAAAAAAAAAAAAAACAAAAAQDAAACAAAAAAAAAAQAAAADAwAA9QEAAAgAAAABCQAAZmlsZTovLy8MAAAAAQEAAE1hY2ludG9zaCBIRAgAAAAEAwAAAJCClucAAAAIAAAAAAQAAEHEhebagAAAJAAAAAEBAABGRTQxNjEzMS05N0Y2LTQ3MjUtODEyNS1DODg4MjZDQjFDMTgYAAAAAQIAAIEAAAABAAAA7xMAAAEAAAAAAAAAAAAAAAEAAAABAQAALwAAAAAAAAABBQAAzAAAAP7///8BAAAAAAAAABAAAAAEEAAAXAAAAAAAAAAFEAAAtAAAAAAAAAAQEAAA3AAAAAAAAABAEAAAzAAAAAAAAAACIAAAqAEAAAAAAAAFIAAAGAEAAAAAAAAQIAAAKAEAAAAAAAARIAAAXAEAAAAAAAASIAAAPAEAAAAAAAATIAAATAEAAAAAAAAgIAAAiAEAAAAAAAAwIAAAtAEAAAAAAAABwAAA/AAAAAAAAAARwAAAIAAAAAAAAAASwAAADAEAAAAAAAAQ0AAABAAAAAAAAAA='
    }
  }
}
[2022-11-22 15:46:32.038] [debug] DownloadsManager.saveAll
[2022-11-22 15:46:32.039] [debug] DownloadsManager.checkForDeletedFiles

**Comment by devinbinnie** [comment]
Can you try one of the nightly builds from here: https://community.mattermost.com/core/channels/desktop-builds

It's possible your issue might already be fixed.

**Comment by srzkptrsk** [comment]
> 

Yes, it's working correct!

**Comment by srzkptrsk** [comment]
> Can you try one of the nightly builds from here: https://community.mattermost.com/core/channels/desktop-builds
> 
> It's possible your issue might already be fixed.

Yes, it's working correct!

**Comment by devinbinnie** [comment]
Great! This should be fixed in v5.2.2 so I'm going to close this issue.
