### ISSUE TITLE
Cannot set Server URL / Server URL stuck on localhost.

### ISSUE THREAD

**Issue by NekoApocalypse** [mattermost/desktop#2417]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

Server URL is stuck on `http://localhost`. Each time I change it to something else it would revert back to localhost.

Running the client as Administrator does not solve the problem.

**Environment**
- Operating System: Windows
- Mattermost Desktop App version: 5.2.1
- Mattermost Server version: ?

**Steps to reproduce**
- Click on the servers drop menu.
- Click the pencil icon to changer server config.
- Change Server URL from `http://localhost` to `https://mattermost.company.com/`

**Expected behavior**
Should connect to `https://mattermost.company.com`

**Observed behavior**
The clients starts loading, and a few moments later, give this error message:

```
Cannot connect to Mattermost

We're having trouble connecting to Mattermost. We'll continue to try and establish a connection.
If refreshing this page (Ctrl+R or Command+R) does not work please verify that:

Your computer is connected to the internet.
The Mattermost URL [http://localhost/](https://github.com/mattermost/desktop/issues/new?assignees=&labels=&template=bug_report.md#) is correct
You can reach [http://localhost/](https://github.com/mattermost/desktop/issues/new?assignees=&labels=&template=bug_report.md#) from a browser window.

Error: ERR_CONNECTION_REFUSED (-102) loading 'http://localhost/'
```

Apparantly it still tries to connect to localhost depite I entered another Server URL.

**Possible fixes**

No idea.

**Comment by JtheBAB** [comment]
Check your SiteURL within the Mattermost server config. There it seams to be http://localhost

**Comment by NekoApocalypse** [comment]
Problem solved. Many thanks!

**Comment by NekoApocalypse** [comment]
Though I do wish there is a clearer explanation on what's happeneing on the client.

Our server maintenance guy had no idea that such a config existed.

Something like "Your server redirected you from `https://mattermost.company.com` to `http://localhost`. If that is incorrect, please contact your system administrator."
