### ISSUE TITLE
Win10 App fires unclear desktop notifications and fails to start it if launches while PC is disconnected from Internet

### ISSUE THREAD

**Issue by it33** [mattermost/desktop#243]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [x] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [x] This is a product defect issue that can be reproduced using the steps listed below.
- [x] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

When Win10 App configured to multiple servers starts without an internet connection it repeatedly throws an unclear error and the app UI won't appear. 

#### Steps to reproduce

Start Win10 app, with multiple servers configured, on a machine without Internet access

#### Expected behavior

The app doesn't fire desktop notifications if internet isn't available. The app works after internet connection is re-established. 

#### Observed behavior

The app fires repeated desktop notifications with an unclear error message. 

![image](https://cloud.githubusercontent.com/assets/177788/17650357/7e7033d4-6200-11e6-8c47-5a31297029e1.png)

#### Possible fixes

Not sure

**Comment by yuya-oc** [comment]
Now the notification is not necessary because there are the error message and auto-reloading(by timer) in the main window when the connection is not established. Thanks for feedback.
