### ISSUE TITLE
Browser back/forward keyboard shortcuts don’t work on the desktop app

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#245]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [X] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [X] This is a product defect issue that can be reproduced using the steps listed below.
- [X] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

Browser back/forward keyboard shortcuts don’t work on the desktop app
- Operating System: Windows 10
- Mattermost Desktop App version: v1.3
- Mattermost Server version: v3.3

**Comment by yuya-oc** [comment]
Would you clarify the shortcuts? And I'm not sure the situation back/forward is necessary in Mattermost server.

**Comment by jasonblais** [comment]
On the browser, `ALT+LEFT` and `ALT+RIGHT` shortcuts can be used to go back/forward in history and allows you to quickly navigate through channels you've recently viewed.

It would be nice to have this feature in the desktop app too (you might have to go back to the channel you were previously viewing, but can't remember which one it was).

I was about to add this as a feature request [in UserVoice](https://mattermost.uservoice.com/forums/306457-general), but it's been reported as a bug couple of times.

**Comment by akashnimare** [comment]
@jasonblais @yuya-oc I have implemented `cmd/ctrl+'[' => back `and `cmd/ctrl+']' => Forward` for Zulip. See here - 
https://github.com/zulip/zulip-electron/blob/master/app/main/index.js#L172-L182

**Comment by jasonblais** [comment]
That's awesome, thanks for letting us know @akashnimare! 

Would you be interested in submitting a pull request for it? Not sure how busy you still are,

**Comment by akashnimare** [comment]
@jasonblais sorry for delay. I'm bit held up in finishing Zulip's desktop [client](github.com/zulip/zulip-electron) 🚀 .

**Comment by jasonblais** [comment]
No worries! Thanks @akashnimare, looking forward to seeing you back here :) 

Would anyone from the community be open to taking a look?

**Comment by yuya-oc** [comment]
Created the PR #268.
