### ISSUE TITLE
release candidate deb package version sorts higher than release version

### ISSUE THREAD

**Issue by kenyon** [mattermost/desktop#2458]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Release candidate debian package version sorts higher than release version.

**Environment**
- Operating System: Debian, Ubuntu

**Steps to reproduce**

`dpkg --compare-versions 5.2.2-26058 gt 5.2.2-rc.3-25928` returns false.

**Expected behavior**

The version number for release candidates should be lower than for actual releases, so that upgrades work. Currently, apt/dpkg considers an upgrade from an rc to the release to be a downgrade.

**Possible fixes**

Use a tilde `~` before the rc in the version string to make release candidates sort earlier. Example: `5.2.2~rc.3-25928`

`dpkg --compare-versions 5.2.2-26058 gt 5.2.2~rc.3-25928` returns true.

References:
* https://www.debian.org/doc/debian-policy/ch-controlfields.html#version
* https://manpages.debian.org/stable/dpkg/dpkg.1.en.html#compare

**Comment by devinbinnie** [comment]
Created a ticket for Release team to investigate: https://mattermost.atlassian.net/browse/CLD-4665

**Comment by mvitale1989** [comment]
Hello @kenyon , thank you for raising this!
The [upstream fix to electron-builder](https://github.com/electron-userland/electron-builder/pull/7978) is now merged and released. Desktop releases starting from `5.7.0` will be ordered correctly by the Debian package managers.
