### ISSUE TITLE
mattermost-desktop rpm package conflicting with other electron packages

### ISSUE THREAD

**Issue by rcaspart** [mattermost/desktop#2461]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
The most recent mattermost-desktop rpm conflicts with (at least some) other electron based rpms packages (e.g. slack).

**Environment**
- Operating System: Fedora 37
- Mattermost Desktop App version: 5.2.0

**Steps to reproduce**
- Install `slack` version 4.29
- Install or Upgrade `mattermost-desktop` version 5.2.0

This issue is likely to also be present for other electron based packages (see linked discussions below).

**Expected behavior**
Both mattermost-desktop and slack can be installed and upgraded at the same time.

**Observed behavior**
mattermost-desktop fails to upgrade/install version 5.2.0. The error message is:
```
Error: Transaction test error:
  file /usr/lib/.build-id/0d/9fad3f21b1e381cc66b5efcae8f3910ae0edc1 from install of mattermost-desktop-5.2.0-24470.x86_64 conflicts with file from package slack-4.29.149-0.1.el8.x86_64
  file /usr/lib/.build-id/76/9d0269491ca2313fcd15d63059bac67bd8b1b3 from install of mattermost-desktop-5.2.0-24470.x86_64 conflicts with file from package slack-4.29.149-0.1.el8.x86_64
  file /usr/lib/.build-id/c2/dcac7cb6a727685d10d4161a0d14988f12a0fa from install of mattermost-desktop-5.2.0-24470.x86_64 conflicts with file from package slack-4.29.149-0.1.el8.x86_64
  file /usr/lib/.build-id/cb/dc9db5fec0e6129bddcb0c282be98be4c6966e from install of mattermost-desktop-5.2.0-24470.x86_64 conflicts with file from package slack-4.29.149-0.1.el8.x86_64
```

**Possible fixes**
It seems to be an issue related to electron building options for rpm.
Similar/the same issues and possible solutions by parsing additional options to `fpm` are also discussed for other packages, e.g. https://github.com/gravitational/teleport/issues/18859 or https://github.com/ferdium/ferdium-app/issues/416

Note other version combinations do not conflict, i.e.
`mattermost-desktop` v5.0.1 and `slack` v4.29 does **not** conflict
`mattermost-desktop` v5.2.0 and `slack` v4.28 does **not** conflict
`mattermost-desktop` v5.0.1 and `slack` v4.28 does **not** conflict
`mattermost-desktop` v5.2.0 and `slack` v4.29 does conflict

**Comment by dfateyev** [comment]
This issue has been affecting several RPM-based distributions for several months already. Please consider to fix the tooling.

**Comment by devinbinnie** [comment]
Looks like this was fixed in the PR above. Closing.
