### ISSUE TITLE
Blank screen in desktop client

### ISSUE THREAD

**Issue by Zhoglik** [mattermost/desktop#2463]
I confirm (by marking "x" in the [ ] below: [x]):

- [ x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [ x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Blank screen on startup**

**Environment**
- Operating System: Windows 10,  
- Mattermost Desktop App version: 5.2.2
- Mattermost Server version: 7.5.0

**Steps to reproduce**
This is intermittent issue and I'm sure that it can be reproduced any time.

**Expected behavior**
Blank screen

**Comment by devinbinnie** [comment]
@Zhoglik Are you able to access the top menu with the 3-dots? If not, can you press Ctrl+Shift+I and see if you get any output?

**Comment by Zhoglik** [comment]
I can do both.

С уважением,
Глеб Селезнев
моб: +7 (918) 523-4549
Telegram <https://t.me/FurorHold> | Skype 
<https://join.skype.com/invite/bfUgJhB3YaBj>

------ Исходное сообщение ------
От: "Devin Binnie" ***@***.***>
Кому: "mattermost/desktop" ***@***.***>
Копия: "Zhoglik" ***@***.***>; "Mention" 
***@***.***>
Отправлено: 08.12.2022 18:25:18
Тема: Re: [mattermost/desktop] Blank screen in desktop client (Issue 
#2463)

**Comment by devinbinnie** [comment]
@Zhoglik Sounds like there's an issue with your own server, if you can access the 3-dots menu you can go to View > Developer Tools for Current Server and you should see some errors in there that may point to what is wrong.

**Comment by Zhoglik** [comment]
Perhaps I would agree, because yes, there were mistakes, but these 
mistakes affected everyone. And I have a problem like no one faces me

С уважением,
Глеб Селезнев
моб: +7 (918) 523-4549
Telegram <https://t.me/FurorHold> | Skype 
<https://join.skype.com/invite/bfUgJhB3YaBj>

------ Исходное сообщение ------
От: "Devin Binnie" ***@***.***>
Кому: "mattermost/desktop" ***@***.***>
Копия: "Zhoglik" ***@***.***>; "Mention" 
***@***.***>
Отправлено: 08.12.2022 19:00:06
Тема: Re: [mattermost/desktop] Blank screen in desktop client (Issue 
#2463)

**Comment by devinbinnie** [comment]
@Zhoglik If you go to the View > Developer Tools for Current Server though you can find the error messages that might help us solve your issue.

**Comment by Zhoglik** [comment]
Sorry, it's really here. I'll provide info tomorrow.

С уважением,
Глеб Селезнев
моб: +7 (918) 523-4549
Telegram <https://t.me/FurorHold> | Skype 
<https://join.skype.com/invite/bfUgJhB3YaBj>

------ Исходное сообщение ------
От: "Devin Binnie" ***@***.***>
Кому: "mattermost/desktop" ***@***.***>
Копия: "Zhoglik" ***@***.***>; "Mention" 
***@***.***>
Отправлено: 08.12.2022 21:42:22
Тема: Re: [mattermost/desktop] Blank screen in desktop client (Issue 
#2463)

**Comment by devinbinnie** [comment]
@Zhoglik It would be the same process (View > Developer Tools for Current Server). Are you able to capture a screenshot of the entire Developer Tools window?

**Comment by Zhoglik** [comment]
I can see issues only for current day. BTW, which window do you need? 
Just errors or whole inputs?

С уважением,
Глеб Селезнев
моб: +7 (918) 523-4549
Telegram <https://t.me/FurorHold> | Skype 
<https://join.skype.com/invite/bfUgJhB3YaBj>

------ Исходное сообщение ------
От: "Devin Binnie" ***@***.***>
Кому: "mattermost/desktop" ***@***.***>
Копия: "Zhoglik" ***@***.***>; "Mention" 
***@***.***>
Отправлено: 09.12.2022 16:58:19
Тема: Re: [mattermost/desktop] Blank screen in desktop client (Issue 
#2463)

**Comment by Zhoglik** [comment]
I've provided whole errors that I can see

С уважением,
Глеб Селезнев
моб: +7 (918) 523-4549
Telegram <https://t.me/FurorHold> | Skype 
<https://join.skype.com/invite/bfUgJhB3YaBj>

------ Исходное сообщение ------
От: "Tasos Boulis" ***@***.***>
Кому: "mattermost/desktop" ***@***.***>
Копия: "Zhoglik" ***@***.***>; "Mention" 
***@***.***>
Отправлено: 13.12.2022 12:34:50
Тема: Re: [mattermost/desktop] Blank screen in desktop client (Issue 
#2463)

**Comment by Zhoglik** [comment]
Here you're

С уважением,
Глеб Селезнев
моб: +7 (918) 523-4549
Telegram <https://t.me/FurorHold> | Skype 
<https://join.skype.com/invite/bfUgJhB3YaBj>

------ Исходное сообщение ------
От: "Tasos Boulis" ***@***.***>
Кому: "mattermost/desktop" ***@***.***>
Копия: "Zhoglik" ***@***.***>; "Mention" 
***@***.***>
Отправлено: 13.12.2022 14:04:22
Тема: Re: [mattermost/desktop] Blank screen in desktop client (Issue 
#2463)

**Comment by Zhoglik** [comment]
[main_12132022.log](https://github.com/mattermost/desktop/files/10218111/main_12132022.log)

**Comment by Zhoglik** [comment]
Sorry, my fault, uploaded

С уважением,
Глеб Селезнев
моб: +7 (918) 523-4549
Telegram <https://t.me/FurorHold> | Skype 
<https://join.skype.com/invite/bfUgJhB3YaBj>

------ Исходное сообщение ------
От: "Tasos Boulis" ***@***.***>
Кому: "mattermost/desktop" ***@***.***>
Копия: "Zhoglik" ***@***.***>; "Mention" 
***@***.***>
Отправлено: 13.12.2022 15:54:19
Тема: Re: [mattermost/desktop] Blank screen in desktop client (Issue 
#2463)

**Comment by Zhoglik** [comment]
Hi.

I saw the same behavior 1-2 min ago. I was waiting for 1 min. Interface 
loaded with my Channels list only after desktop app was focused (I moved 
mouse cursor through the blank screen to 3 dots to check log) . I've 
checked server log and it's showing the same 5 error messages.

С уважением,
Глеб Селезнев
моб: +7 (918) 523-4549
Telegram <https://t.me/FurorHold> | Skype 
<https://join.skype.com/invite/bfUgJhB3YaBj>

------ Исходное сообщение ------
От: "Tasos Boulis" ***@***.***>
Кому: "mattermost/desktop" ***@***.***>
Копия: "Zhoglik" ***@***.***>; "Mention" 
***@***.***>
Отправлено: 13.12.2022 15:54:19
Тема: Re: [mattermost/desktop] Blank screen in desktop client (Issue 
#2463)

**Comment by Zhoglik** [comment]
Haven't seen it till now

вт, 17 янв. 2023 г., 14:30 Tasos Boulis ***@***.***>:

**Comment by devinbinnie** [comment]
Closing as it's likely that this has been resolved.
