### ISSUE TITLE
Application requests focus on every notification

### ISSUE THREAD

**Issue by nmatt** [mattermost/desktop#248]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [x] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [x] This is a product defect issue that can be reproduced using the steps listed below.
- [x] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

On every notification, the desktop application window requests focus (icon flashes in the task bar), requiring to activate the window manually to stop the flashing. This appears to be a regression from a previous version (not sure if that was 1.1 or 1.2).

#### Steps to reproduce

- Operating System: Windows 7 Pro
- Mattermost Desktop App version: 1.3.0
- Mattermost Server version: 3.2.0
- Clear steps to reproduce the issue:
1) Open the Mattermost desktop application and put its window into the background or minimize it.
2) Wait for a notification to appear.

#### Expected behavior

It is expected that a notification balloon appears above the system tray area, but not for the task bar icon to start flashing. I'm pretty sure that is how it was in earlier versions. Notification balloons go away automatically, but a flashing task bar icon requires manual intervention to make it stop.

Normally you don't want to have to react to every new message appearing in any subscribed Mattermost channel. It's okay to be notified via the balloons, because you can ignore it and it goes away quickly. But the task bar icon flashing (and the task bar appearing when it was auto-hidden) does not go away by itself, you have to activate the application window before you can go back to what you were doing before.

This is probably (I haven't tested it) not a problem when the desktop application window has been closed and the application only resides in the system tray. But I keep the window open (usually minimized) so I can quickly switch to it by keyboard, which is not possible when it is closed (cf. issue #237).

#### Observed behavior

A notification balloon appears above the system tray area, and the task bar icon starts flashing (and appears if previously auto-hidden). The notification balloon disappears after a short time (which I believe can be configured in the registry), but the task bar icon keeps flashing until the desktop application window is activated.

#### Possible fixes

Don't have the application window request focus upon notification.

**Comment by Razzeee** [comment]
Hey @nmatt 

This is the new default behaviour, if you don't like it, you can change it in the settings.
![unbenannt](https://cloud.githubusercontent.com/assets/5943908/17709240/a2fe4fda-63e8-11e6-8c45-a63048cebfca.png)

The feature was asked for in #39 then implemented in #159 and #200 if you need some more information.

**Comment by nmatt** [comment]
@Razzeee: Ah, I missed/forgot that setting, sorry about that!
