### ISSUE TITLE
Can't join any team (login before been invitined)

### ISSUE THREAD

**Issue by baznikin** [mattermost/desktop#2488]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
I connect to own MM server by test user, see error "no available teams". Then I add user to team error still persists.

**Environment**
- Operating System: Linux Mint 21
- Mattermost Desktop App version: 5.2.2
- Mattermost Server version: 7.5.1

**Steps to reproduce**
1. Connect to server with user who doesn't invited to any team
2. See error message
3. As administrator I add user to some team
4. Error persist. Neither "Reload" nor "Clear cache and reload' helps
5. At same time same user can successfully connect with web version. See screenshot, same user with web and with desktop app:
![image](https://user-images.githubusercontent.com/5183334/209542118-6e9f20e4-7978-4f3a-98da-10318b37258d.png)

**Expected behavior**
Desktop and web version have same behavior.

**Observed behavior**
User can't proceed.

**Possible fixes**

**Additional notes**

I check network requests from web version and from desktop app. They are mostly the same, except two queries returned with 403 for random reason for desktop app. For web app they are always successful. They can be both 403 or only one of them:
`GET https://XXXXXXX/api/v4/users/me/teams/7t86uhmhti8opkdgj86ubrnmgw/channels?include_deleted=true`
`GET https://XXXXXXX/api/v4/users/me/teams/7t86uhmhti8opkdgj86ubrnmgw/channels/members`

Desktop:
![image](https://user-images.githubusercontent.com/5183334/209543032-bb8ddf9f-ad9e-4aa2-9c2f-de99c7c31f3d.png)
![image](https://user-images.githubusercontent.com/5183334/209543089-c1e94d71-ca05-416e-8b68-48a038f01002.png)
![image](https://user-images.githubusercontent.com/5183334/209543211-557a87ad-3657-43a1-8bb7-d84ab667605c.png)

Failed query example:
![image](https://user-images.githubusercontent.com/5183334/209542962-7759d730-faf5-4343-9342-f45f9330f57b.png)

**PS**

I began this process because all my desktop app users began to blame it for undelivered messages, missed notifications, very long message delivery times. Issues started week ago.

Events which can possibly correlate with this issues
1. Removed enterprise trial license
2. Kubernetes cluster upgrade 
3. Some sort of mess-up with Mattermost server configuration via "Server console"

**PPS**

I hope there is no server information in cookies. Let me know if I am wrong

**Comment by baznikin** [comment]
This particular problem resolved after updating server to 7.5.2

**Comment by baznikin** [comment]
Is it all parts of same underlying problem? I send messages from web app (on the right) to test user, connected with desktop app and web app at same time. He doesn't receive all of my messages!
![image](https://user-images.githubusercontent.com/5183334/209554295-95c85a77-564d-4d83-b088-8af6aa5c8954.png)

**Comment by baznikin** [comment]
After some (long) time messages become synced
![image](https://user-images.githubusercontent.com/5183334/209560003-a339f8b5-f8e4-4330-93ab-0b3760504373.png)

**Comment by devinbinnie** [comment]
@baznikin It might also be worth checking if this reproduces using the browser as well.

**Comment by baznikin** [comment]
@tboulis after server update to most recent patch level (and followinf restart) issue resolved. Undelivered messages are addressed in other issue (it was licensing issues and HA setup), see https://github.com/mattermost/mattermost-server/issues/21955

@devinbinnie there were no issues with browser, only app was affected

I suppose issue can be closed.
