### ISSUE TITLE
mattermost desktop 4.5.4.7024 stores caches in the wrong directory on macOS

### ISSUE THREAD

**Issue by sneak** [mattermost/desktop#2491]
caches are in `~/Library/Application Support/Mattermost/Cache`

caches should be in `~/Library/Caches/Mattermost`

**Comment by sneak** [comment]
may be related to  #487

**Comment by devinbinnie** [comment]
Mattermost Desktop v4.5 is no longer supported. Please upgrade to v5.2.2: https://github.com/mattermost/desktop/releases/tag/v5.2.2

**Comment by sneak** [comment]
I'm not asking for support. You might check to see if the issue exists in your current version; I reported with the version I am using.

**Comment by devinbinnie** [comment]
Sorry, thanks for letting us know. Looks like it does store it correctly now though.

**Comment by volo-droid** [comment]
> Looks like it does store it correctly now though.

@devinbinnie Does it? On my machine there's `~/Library/Application Support/Mattermost/Cache` folder with data, but there's no `~/Library/Caches/Mattermost` directory at all. Mattermost client v5.11.0
