### ISSUE TITLE
Bug: server url changes are not saving

### ISSUE THREAD

**Issue by yantato** [mattermost/desktop#2495]
## Steps to reproduce the behavior

We changed our mattermost server's url, and whenever I try to change it on the desktop app, after attempting to log in, it reverts to the old url

## Expected behavior

Server url should not be reverting to the previous url when saving server config

## Edition and Platform

 - Edition: Personal Desktop
 - Version: 5.2.2
 - Browser and OS: Chrome on Windows 10

## Additional context (optional)

- I've tried reinstalling, same issue
- Another machine's desktop app works fine, same machine's browser app works fine; other colleagues are not experiencing the same issue on their machines
- I'm using tailscale vpn (not sure if this matters)

**Comment by devinbinnie** [comment]
@yantato Is there a reason your server's SIte URL isn't configured the same as the one that it's being changed to? Looks like there's some kind of redirect going on.

**Comment by yantato** [comment]
> @yantato Is there a reason your server's SIte URL isn't configured the same as the one that it's being changed to? Looks like there's some kind of redirect going on.

Not sure why they didn't config the old url for this, but as i mentioned this only affects one of my machines, all my others are using the desktop app just fine.

I just found this in mattermost forums, it sounds like a similar problem to mine https://forum.mattermost.com/t/cannot-uninstall-fully-on-windows-10/8373/2 - where the guy is having problems connecting with servers, I'm not looking to uninstall the app

**Comment by devinbinnie** [comment]
@yantato Is this still an issue for you?

**Comment by canunen** [comment]
Hi @devinbinnie not sure if related to this or not, but a server URL I put in automatically changes from https to http, and doesn't connect after restart. Even if I manually update into https, it's not saved and still see http on server URL setting. 

I

**Comment by canunen** [comment]
Thank you for your quick response. We have fixed the URL at the server side and it's working well now. Good to hear this won't be an issue with the upcoming release. Cheers.

**Comment by devinbinnie** [comment]
Since this is fixed for upcoming releases, I'm closing this issue as fixed.

**Comment by yantato** [comment]
Just checked, server url changes are saved, works now
