### ISSUE TITLE
No able to run npm install (node-gyp errors)

### ISSUE THREAD

**Issue by artutava** [mattermost/desktop#2510]
I can't run npm install on windows 10. Even after installing Visual Studio(latest), Node.JS (latest LTS) and chocolatey.
Here are the errors:

> 9018 timing command:install Completed in 95312ms
9019 verbose stack Error: command failed
9019 verbose stack     at ChildProcess.<anonymous> (C:\Users\artut\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:63:27)
9019 verbose stack     at ChildProcess.emit (node:events:513:28)
9019 verbose stack     at maybeClose (node:internal/child_process:1091:16)
9019 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
9020 verbose pkgid robotjs@0.6.0
9021 verbose cwd G:\sircrux chat\desktop
9022 verbose Windows_NT 10.0.19044
9023 verbose node v18.13.0
9024 verbose npm  v8.11.0
9025 error code 1
9026 error path G:\sircrux chat\desktop\node_modules\robotjs
9027 error command failed
9028 error command C:\Windows\system32\cmd.exe /d /s /c prebuild-install || node-gyp rebuild
9029 error Compilando os projetos desta solu��o um por vez. Para habilitar o build paralelo, adicione a op��o "-m".
9029 error   robotjs.cc
9029 error C:\Users\artut\AppData\Local\node-gyp\Cache\18.13.0\include\node\v8-array-buffer.h(12,10): fatal  error C1083: N�o � poss�vel abrir arquivo incluir: 'v8-local-handle.h': No such file or directory [G:\sircrux chat\desktop\node_modules\robotjs\build\robotjs.vcxproj]
9030 error gyp info it worked if it ends with ok
9030 error gyp info using node-gyp@9.3.0
9030 error gyp info using node@18.13.0 | win32 | x64
9030 error gyp info find Python using Python version 3.10.9 found at "C:\Users\artut\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe"
9030 error gyp info find VS using VS2022 (17.4.33213.308) found at:
9030 error gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Community"
9030 error gyp info find VS run with --verbose for detailed information
9030 error gyp info spawn C:\Users\artut\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe
9030 error gyp info spawn args [
9030 error gyp info spawn args   'G:\\sircrux chat\\desktop\\node_modules\\node-gyp\\gyp\\gyp_main.py',
9030 error gyp info spawn args   'binding.gyp',
9030 error gyp info spawn args   '-f',
9030 error gyp info spawn args   'msvs',
9030 error gyp info spawn args   '-I',
9030 error gyp info spawn args   'G:\\sircrux chat\\desktop\\node_modules\\robotjs\\build\\config.gypi',
9030 error gyp info spawn args   '-I',
9030 error gyp info spawn args   'G:\\sircrux chat\\desktop\\node_modules\\node-gyp\\addon.gypi',
9030 error gyp info spawn args   '-I',
9030 error gyp info spawn args   'C:\\Users\\artut\\AppData\\Local\\node-gyp\\Cache\\18.13.0\\include\\node\\common.gypi',
9030 error gyp info spawn args   '-Dlibrary=shared_library',
9030 error gyp info spawn args   '-Dvisibility=default',
9030 error gyp info spawn args   '-Dnode_root_dir=C:\\Users\\artut\\AppData\\Local\\node-gyp\\Cache\\18.13.0',
9030 error gyp info spawn args   '-Dnode_gyp_dir=G:\\sircrux chat\\desktop\\node_modules\\node-gyp',
9030 error gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\artut\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\18.13.0\\\\<(target_arch)\\\\node.lib',
9030 error gyp info spawn args   '-Dmodule_root_dir=G:\\sircrux chat\\desktop\\node_modules\\robotjs',
9030 error gyp info spawn args   '-Dnode_engine=v8',
9030 error gyp info spawn args   '--depth=.',
9030 error gyp info spawn args   '--no-parallel',
9030 error gyp info spawn args   '--generator-output',
9030 error gyp info spawn args   'G:\\sircrux chat\\desktop\\node_modules\\robotjs\\build',
9030 error gyp info spawn args   '-Goutput_dir=.'
9030 error gyp info spawn args ]
9030 error gyp info spawn C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe
9030 error gyp info spawn args [
9030 error gyp info spawn args   'build/binding.sln',
9030 error gyp info spawn args   '/clp:Verbosity=minimal',
9030 error gyp info spawn args   '/nologo',
9030 error gyp info spawn args   '/p:Configuration=Release;Platform=x64'
9030 error gyp info spawn args ]
9030 error gyp ERR! build error 
9030 error gyp ERR! stack Error: `C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
9030 error gyp ERR! stack     at ChildProcess.onExit (G:\sircrux chat\desktop\node_modules\node-gyp\lib\build.js:203:23)
9030 error gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
9030 error gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
9030 error gyp ERR! System Windows_NT 10.0.19044
9030 error gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "G:\\sircrux chat\\desktop\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
9030 error gyp ERR! cwd G:\sircrux chat\desktop\node_modules\robotjs
9030 error gyp ERR! node -v v18.13.0
9030 error gyp ERR! node-gyp -v v9.3.0
9030 error gyp ERR! not ok
9031 verbose exit 1
9032 timing npm Completed in 95447ms
9033 verbose unfinished npm timer reify 1674325350754
9034 verbose unfinished npm timer reify:audit 1674325354012
9035 verbose unfinished npm timer auditReport:init 1674325355275
9036 verbose unfinished npm timer reify:build 1674325421882
9037 verbose unfinished npm timer build 1674325421886
9038 verbose unfinished npm timer build:deps 1674325421886
9039 verbose unfinished npm timer build:run:install 1674325422194
9040 verbose unfinished npm timer build:run:install:node_modules/robotjs 1674325422202
9041 verbose unfinished npm timer build:run:install:node_modules/windows-focus-assist 1674325422208
9042 verbose unfinished npm timer metavuln:calculate:security-advisory:bin-build:I6qX53Np+mW5NRRCFGTTrZl2CiYrwRuBqtNJ00+JCCDXUhrfhsMtCEM1jDA4kDfUyE3Lj3nY0Wqcj/B9QdR3pA== 1674325445346
9043 verbose unfinished npm timer metavuln:packument:bin-build 1674325445347
9044 verbose unfinished npm timer metavuln:calculate:security-advisory:node-jq:I6qX53Np+mW5NRRCFGTTrZl2CiYrwRuBqtNJ00+JCCDXUhrfhsMtCEM1jDA4kDfUyE3Lj3nY0Wqcj/B9QdR3pA== 1674325445350
9045 verbose unfinished npm timer metavuln:packument:node-jq 1674325445350
9046 verbose code 1

``
[2023-01-21T18_22_30_644Z-debug-0.log](https://github.com/mattermost/desktop/files/10472757/2023-01-21T18_22_30_644Z-debug-0.log)

**Comment by devinbinnie** [comment]
Hey @artutava, `node-gyp` can sometimes have some weird errors popup when you try to install for the first time on Windows. A solution I've found that works for me is to run:

```
npm i -g node-gyp
node-gyp install
```

What this does is installed `node-gyp` globally and predownloads the headers for you. This fixes a weird race condition that sometimes crops up when trying to build the native node modules.

If that doesn't work, you can try disabling the `postinstall` script by running `npm install --ignore-scripts`, but that can sometimes cause more problems that it solves.

**Comment by devinbinnie** [comment]
Feedback given, closing as inactive

**Comment by rnestler** [comment]
I also had build errors related to `node-gyp`:

```
npm ERR! code 1
npm ERR! path /build/mattermost-desktop/src/desktop-5.4.0/node_modules/robotjs
npm ERR! command failed
npm ERR! command sh -c prebuild-install || node-gyp rebuild
npm ERR! make: Entering directory '/build/mattermost-desktop/src/desktop-5.4.0/node_modules/robotjs/build'
npm ERR!   CXX(target) Release/obj.target/robotjs/src/robotjs.o
npm ERR! make: Leaving directory '/build/mattermost-desktop/src/desktop-5.4.0/node_modules/robotjs/build'
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@10.0.1
npm ERR! gyp info using node@21.6.1 | linux | x64
npm ERR! gyp info find Python using Python version 3.11.6 found at "/usr/bin/python3"
npm ERR! gyp http GET https://nodejs.org/download/release/v21.6.1/node-v21.6.1-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v21.6.1/node-v21.6.1-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v21.6.1/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v21.6.1/SHASUMS256.txt
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args '/usr/lib/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args 'binding.gyp',
npm ERR! gyp info spawn args '-f',
npm ERR! gyp info spawn args 'make',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args '/build/mattermost-desktop/src/desktop-5.4.0/node_modules/robotjs/build/config.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args '/usr/lib/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args '-I',
npm ERR! gyp info spawn args '/build/.cache/node-gyp/21.6.1/include/node/common.gypi',
npm ERR! gyp info spawn args '-Dlibrary=shared_library',
npm ERR! gyp info spawn args '-Dvisibility=default',
npm ERR! gyp info spawn args '-Dnode_root_dir=/build/.cache/node-gyp/21.6.1',
npm ERR! gyp info spawn args '-Dnode_gyp_dir=/usr/lib/node_modules/node-gyp',
npm ERR! gyp info spawn args '-Dnode_lib_file=/build/.cache/node-gyp/21.6.1/<(target_arch)/node.lib',
npm ERR! gyp info spawn args '-Dmodule_root_dir=/build/mattermost-desktop/src/desktop-5.4.0/node_modules/robotjs',
npm ERR! gyp info spawn args '-Dnode_engine=v8',
npm ERR! gyp info spawn args '--depth=.',
npm ERR! gyp info spawn args '--no-parallel',
npm ERR! gyp info spawn args '--generator-output',
npm ERR! gyp info spawn args 'build',
npm ERR! gyp info spawn args '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! cc1plus: warning: command-line option ‘-Wbad-function-cast’ is valid for C/ObjC but not for C++
npm ERR! In file included from ../src/robotjs.cc:1:
npm ERR! /build/.cache/node-gyp/21.6.1/include/node/node.h:1202:7: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
npm ERR!  1202 |       (node::addon_register_func) (regfunc),                          \
npm ERR!       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! /build/.cache/node-gyp/21.6.1/include/node/node.h:1236:3: note: in expansion of macro ‘NODE_MODULE_X’
npm ERR!  1236 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
npm ERR!       |   ^~~~~~~~~~~~~
npm ERR! ../src/robotjs.cc:907:1: note: in expansion of macro ‘NODE_MODULE’
npm ERR!   907 | NODE_MODULE(robotjs, InitAll)
npm ERR!       | ^~~~~~~~~~~
npm ERR! In file included from /build/.cache/node-gyp/21.6.1/include/node/v8-array-buffer.h:12,
npm ERR!                  from /build/.cache/node-gyp/21.6.1/include/node/v8.h:24,
npm ERR!                  from /build/.cache/node-gyp/21.6.1/include/node/node.h:73:
npm ERR! /build/.cache/node-gyp/21.6.1/include/node/v8-local-handle.h: In instantiation of ‘v8::Local<T>::Local(v8::Local<S>) [with S = v8::Data; T = v8::Value]’:
npm ERR! ../../nan/nan_callbacks_12_inl.h:175:53:   required from here
npm ERR! /build/.cache/node-gyp/21.6.1/include/node/v8-local-handle.h:253:42: error: static assertion failed: type check
npm ERR!   253 |     static_assert(std::is_base_of<T, S>::value, "type check");
npm ERR!       |                                          ^~~~~
npm ERR! /build/.cache/node-gyp/21.6.1/include/node/v8-local-handle.h:253:42: note: ‘std::integral_constant<bool, false>::value’ evaluates to false
npm ERR! make: *** [robotjs.target.mk:123: Release/obj.target/robotjs/src/robotjs.o] Error 1
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack at ChildProcess.<anonymous> (/usr/lib/node_modules/node-gyp/lib/build.js:209:23)
npm ERR! gyp ERR! System Linux 6.7.4-arch1-1
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /build/mattermost-desktop/src/desktop-5.4.0/node_modules/robotjs
npm ERR! gyp ERR! node -v v21.6.1
npm ERR! gyp ERR! node-gyp -v v10.0.1
npm ERR! gyp ERR! not ok
```

For me the solution was to use an older nodejs version (20.11.0).
