### ISSUE TITLE
Screen share button not working properly Windows App

### ISSUE THREAD

**Issue by artutava** [mattermost/desktop#2512]
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

Screen sharing button on expanded call window does not work. It tries to record the call instead of sharing the screen.

**Environment**
- Operating System: Win 10
- Mattermost Desktop App version: 5.3.0-develop.1 commit: 5f1a3a4
- Mattermost Server version:  7.7.1

**Steps to reproduce**

1. Click on screen share on small call menu (Screen share works from here)
2. Stop sharing screen from this menu
3. Expand the call to the expanded windowed mode
4. Try to share the screen from this button
3. A message will pop up saying you dont have permissions to record the screen

**Expected behavior**
Screen sharing should happen from this menu

Video recording with the issue:
https://drive.google.com/file/d/1aXkvTYReGVtjz5WfMsW5LGR9vHhEXPyX/view?usp=sharing

**Comment by devinbinnie** [comment]
@artutava It looks like you're using a development build of the application, is there a reason for that? If not, can you try with the latest stable release (found here: https://github.com/mattermost/desktop/releases/tag/v5.2.2) or the latest nightly release (found here: https://community.mattermost.com/core/channels/desktop-builds)

**Comment by artutava** [comment]
@devinbinnie I have tested on the latest nightly release and it's happening as well.

**Comment by devinbinnie** [comment]
@streamer45 Any thoughts on this? Is there anything on the server or in the plugin that could be causing issues?

**Comment by streamer45** [comment]
I am not aware of this issue and not able to reproduce on my end although I haven't personally tested on Windows yet. I created an internal ticket to keep track of this ([MM-49924](https://mattermost.atlassian.net/browse/MM-49924)) and will have a look soon.

@artutava In the mean-time could you share the console logs for when this happens? They should likely show some error. You can find logs under [Dots menu -> View -> Developer Tools for Current Server](https://user-images.githubusercontent.com/1832946/211383060-aa4a79b8-c039-47ab-b3d4-43fe7af629ac.png)

**Comment by artutava** [comment]
[chat.sircrux.com-1674575817504.log](https://github.com/mattermost/desktop/files/10491760/chat.sircrux.com-1674575817504.log)

**Comment by streamer45** [comment]
Okay, I was able to reproduce on the nightly build. It looks like the returned Desktop app version on the expanded window (`5.3.0-nightly.20230124`) is not compared as we expect so it's failing to execute the logic necessary for Desktop >= 5.3.0 . Interestingly the version returned by the main Mattermost window is just `5.3.0` otherwise it wouldn't even possible to get the new floating widget.

Running the app directly from repository should work as expected. I'll make some changes on the plugin side to fix this but overall it shouldn't affect official builds.
