### ISSUE TITLE
Plugin support for popup/dialog windows with external URL or content. Window focus issue.

### ISSUE THREAD

**Issue by catz** [mattermost/desktop#2534]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

Show (focus on) already opened popup on url change. It's hard to understand what's going on when main app is in fullscreen and popup is in background.

**Environment**
- Operating System: macOS
- Mattermost Desktop App version: 5.2.2
- Mattermost Server version: 7.5.1

**Steps to reproduce**

1. Plugin (right panel in our case) opens some url. Popup gets focus.
2. Go back to main app. Popup is in background
3. Plugin opens another url. Some intentional user action like user clicked another button. 

**Expected behavior**

Popup gets focus.

**Observed behavior**

Popup is in background.

**Possible fixes**

Change line 
https://github.com/mattermost/desktop/blob/master/src/main/views/webContentEvents.ts#L195

From 

`this.popupWindow.once('ready-to-show', () => {`

to

`this.popupWindow.on('ready-to-show', () => {`

**Comment by devinbinnie** [comment]
@catz Can you give an example where plugins should be doing this? The current behaviour of the Desktop App is to not open another popup (or a plugin URL in the same popup window) so I can't see where this would be happening.

**Comment by catz** [comment]
Hello Devin,

I will try to explain. 
1. User opens the right panel and clicks info on some event
![img1](https://user-images.githubusercontent.com/472690/222225679-6b643d4f-c202-4d83-9de0-2b712ad0fa6e.jpg)
2. MM opens new BrowserWindow
![img2](https://user-images.githubusercontent.com/472690/222225839-39391c43-49f7-4420-a149-b1edabd272ec.jpg)
3. User returns to main MM window. MM main window becomes on top of child window.
4. User clicks on another event. 
5. Child's window content gets updated but the child window itself stays behind the main MM window. It doesn't receive focus because 'ready-to-show' event happens only once.

Can't say it's a big issue but imho fix seems very trivial.

**Comment by devinbinnie** [comment]
@catz Which plugin are you using here?

**Comment by catz** [comment]
@devinbinnie this is our own (work in progress) plugin.

**Comment by devinbinnie** [comment]
@catz I've made a change that should address your issue: https://github.com/mattermost/desktop/pull/2581
There will be a build generated shortly, can you test and make sure it works for you?
