### ISSUE TITLE
The msi installer doesn't offer an ability to install the app for all users

### ISSUE THREAD

**Issue by wget** [mattermost/desktop#2537]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: https://docs.mattermost.com/install/troubleshooting.html](https://docs.mattermost.com/install/troubleshooting.html).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

This ticket is just t keep track of this before releasing the new installer based on Wix Toolset 4.x. Have received reports saying that installation for `All Users` (Windows term) may not work and the shortcuts for each user not generated.

We need a proper Windows Server + Windows clients to check this from E2E.

**Environment**
- Operating System: Windows 10/11
- Mattermost Desktop App version: latest (5.2.2)
- Mattermost Server version: 7.7.1

**Steps to reproduce**

Need to provide this with proper screenshots.

**Expected behavior**

The ability for the shortcuts to be created for all users (existing).

We need to also check whether new users created *after* the package is installed are supposed to have this default Shortcuts enabled or not.

**Observed behavior**

N/A

**Possible fixes**

Implement the feature and carefully check with previous deployment to ensure we are not introducing a regression

**Comment by itkfm** [comment]
> Need to provide this with proper screenshots.

There is nothing to screenshot. The installer just runs through and automatically launches the user-local installation afterwards.

![image](https://github.com/user-attachments/assets/81c2460a-c7b0-49a6-896d-c0386dd0f083)

**Comment by itkfm** [comment]
The uninstall dialog is as interactive as this installer gets:
![image](https://github.com/user-attachments/assets/8fcc347f-4f61-4194-8da7-91389a951b6e)

**Comment by devinbinnie** [comment]
This issue should be closed for now, we do support installing via the MSI for all users, see: https://docs.mattermost.com/install/desktop-msi-installer-and-group-policy-install.html#install-for-all-users

**Comment by itkfm** [comment]
Having to manually append `ALLUSERS=1` to the install command really screams for problems.
