### ISSUE TITLE
Notifications Preferences Setting for Channels and Group Messages. 

### ISSUE THREAD

**Issue by jboboyle** [mattermost/desktop#2540]
It would be useful to enable notifications for certain channels and group messages. Currently, I only receive notifications from direct messages or mentions within channels. However, there are certain channels I need to attend to frequently and others I only look into infrequently. It would be great to be able to set notification preferences for individual channels.

I apologize in advance if this feature is already implemented but I haven't been able to find it.

**Comment by amyblais** [comment]
Hi @jboboyle, please find docs here for channel notification settings https://docs.mattermost.com/channels/set-channel-preferences.html#channel-notification-preferences.
