### ISSUE TITLE
Mattermost app doesn't have login by Google Account but the webpage does

### ISSUE THREAD

**Issue by cuonghtran** [mattermost/desktop#2542]
#### Summary
Cannot use the account (login by Google account) in the app.

#### Steps to reproduce
- Create a new account by Google Account.
- Download the app.
- There is no way/function to use that account in the app.
- Create a new account normally using the same email => cannot because the email is already associated.

#### Expected behavior
There should be a social login feature in the app like on the web.

**Comment by devinbinnie** [comment]
@cuonghtran Our application does support sign-in via Google, but it needs to be setup by the administrator of the server that you are trying to log in to. I'm not seeing it setup on the server in question.

Does this work for you in the web browser? Or is it somehow being blocked in the Desktop App?

**Comment by cuonghtran** [comment]
It worked now. Somehow everything was fine if I created an account from the invitation link and it didn't trigger the "this email is already associated...". I can also use this account on the native desktop app. Thanks for the quick response and support though (:.
