### ISSUE TITLE
Desktop app is hanging, not receiving Okta token

### ISSUE THREAD

**Issue by secarch-aa** [mattermost/desktop#2547]
Per Mattermost guidelines, GitHub issues are for bug reports: <https://handbook.mattermost.com/contributors/contributors/ways-to-contribute/>.

For troubleshooting see: https://forum.mattermost.com/.
For feature proposals see: https://mattermost.com/suggestions/

If you've found a bug--something appears unintentional--please follow these steps:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) to ensure that the ticket does not already exist.
2. Confirm your issue does not involve security. Otherwise, please see our [Responsible Disclosure Policy](https://mattermost.com/security-vulnerability-report/).
3. [File a new issue](https://github.com/mattermost/mattermost-server/issues/new) using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed. 

#### Summary
Bug report in one concise sentence
My desktop Mattermost app is hanging.
#### Steps to reproduce
How can we reproduce the issue (what version are you using?)
Version 5.2.2 on Windows
#### Expected behavior
Describe your issue in detail
When attempting to login to a server using the desktop app, I have tried using both push notificaitons and manually entering a code from my Okta app, and both methods lead to the app hanging, with no way to interrupt it. 
#### Observed behavior (that appears unintentional) 
What did you see happen? Please include relevant error messages and/or screenshots.
![image](https://user-images.githubusercontent.com/124731697/217353709-716c6ebf-257a-4f12-910a-9ca88d6127ea.png)

#### Possible fixes
If you can, link to the line of code that might be responsible for the problem

**Comment by devinbinnie** [comment]
Hey @secarch-aa, can you attach your log file from the Desktop App? You can find it here: https://docs.mattermost.com/install/troubleshooting.html#mattermost-desktop-app-logs

**Comment by secarch-aa** [comment]
See attached.

Aaron Agostini CISSP, MS (he/him)
Information Security Architect
IT Security
University of Maryland Medical System
Email: ***@***.******@***.***> | Desk: (443) 462-5201 | Mobile: (240)278-6260

A better state of care.
compassion | discovery | excellence | diversity | integrity

umms.org

**Comment by devinbinnie** [comment]
@secarch-aa I didn't get the attached, you might need to actually post it on GitHub instead of using the email, link to the issue is here: https://github.com/mattermost/desktop/issues/2547

You can also feel free to DM me on community.mattermost.com, username is @devin.binnie

**Comment by secarch-aa** [comment]
[main.log](https://github.com/mattermost/desktop/files/10687772/main.log)

**Comment by devinbinnie** [comment]
@secarch-aa Is your Mattermost server URL configured correctly in the Desktop App? I'm seeing it pointing to `https://h-isac.okta.com/`, which looks like the single-sign on page.

**Comment by secarch-aa** [comment]
Thanks, that was the problem. The initial screen led back to that page, so I figured I needed to load that one in the config. I'm all set now.

**Comment by devinbinnie** [comment]
Awesome! Closing this ticket.
