### ISSUE TITLE
Feature request - Scale Desktop

### ISSUE THREAD

**Issue by VladimirCores** [mattermost/desktop#2562]
Requesting missing option to scale desktop:

![image](https://user-images.githubusercontent.com/442111/219804055-4b297876-6ce1-4ec0-b52e-4dd878f5bfe6.png)

**Comment by devinbinnie** [comment]
You can zoom the desktop app in and out using the 3-dot menu (View > Zoom In, View > Zoom Out) or using the associated keyboard shortcuts.

**Comment by VladimirCores** [comment]
Alright, figured out, just not very intuitive, thanks : )
