### ISSUE TITLE
Allow to work through a proxy and self-signed https

### ISSUE THREAD

**Issue by finsterwalder** [mattermost/desktop#26]
I have to use a proxy to connect to my mattermost server. Is there a way to configure a proxy? If not, could you please add that feature?

**Comment by yuya-oc** [comment]
For now, please try command line switches such as `--proxy-server`.

* http://peter.sh/experiments/chromium-command-line-switches/#proxy-server
* http://electron.atom.io/docs/v0.36.5/api/chrome-command-line-switches/#proxy-server-address-port

**Comment by finsterwalder** [comment]
Hi there,

that doesn't quite do the trick.
I see that data is sent through the proxy when I do a reload now (my proxy
shows bytes received and sent).
But I still get an empty page.
Is there any way to troubleshoot?

Greetings,
   Malte

**Comment by yuya-oc** [comment]
I tried with `electron-mattermost.exe --proxy-server=<IP>:<PORT>` on Windows, it works. (I chose an open proxy by serching with google.)
The app won't work in your environment even if I add proxy options.

**Comment by finsterwalder** [comment]
Do you have any idea, how I can find out, what's not working, then?
Like I said, my screen stays blank. I only see the teams I added in tabs,
but the tabs remain blank.

Greetings,
   Malte

**Comment by yuya-oc** [comment]
I have to check [webview tag events](http://electron.atom.io/docs/v0.36.7/api/web-view-tag/#dom-events) like `did-fail-load` to know what happened. However, I don't know whether I can fix it.

I tried with a proxy in intranet (it requires authentication for internet). Then, I couldn't see mattermost content. `electron-mattermost.exe --proxy-server=<USER>:<PASSWORD>@<SERVER>:<PORT>`
It seems that Electron doesn't support all proxies.

Just an idea, how about using local proxy?

```
app -> local proxy -> the proxy -> Mattermost
```

**Comment by finsterwalder** [comment]
Hello Yuya,

I am using a local proxy. It's at localhost. It does not need
authentication and I never had any problems with it so far. It's part of
our VPN infrastructure. I use it to access Mattermost via browser without
any problems.

Greetings,
   Malte

**Comment by yuya-oc** [comment]
Assuming that, I can't guess why the app doesn't see Mattermost. It's difficult.

byw, could you test [this build](https://circleci.com/gh/yuya-oc/electron-mattermost/151#artifacts) with `--proxy-server` switch? It shows detailed logs in devTools console. Although, I think we will see mere connection error...

**Comment by finsterwalder** [comment]
Hi Yuya,

I get a bunch of messages on the console, that don't look too good to me.
;-)
Maybe it helps...

Greetings,
   Malte

On 14 February 2016 at 14:45, Yuya Ochiai <notifications@github.com> wrote:

> Assuming that, I can't guess why the app doesn't see Mattermost. It's
> difficult.
>
> byw, could you test this build
> <https://circleci.com/gh/yuya-oc/electron-mattermost/151#artifacts> with
> --proxy-server switch? It shows detailed logs in devTools console.
> Although, I think we will see mere connection error...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yuya-oc/electron-mattermost/issues/26#issuecomment-183890962>
> .
>

Download the React DevTools for a better development experience: https://fb.me/react-devtools
index.js:2441 Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `MainPage`. See https://fb.me/react-warning-keys for more information.warning @ index.js:2441validateExplicitKey @ index.js:19510validateChildKeys @ index.js:19572ReactElementValidator.createElement @ index.js:19677React.createClass.render @ index.js:203ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext @ index.js:7905ReactCompositeComponentMixin._renderValidatedComponent @ index.js:7925wrapper @ index.js:1678ReactCompositeComponentMixin.mountComponent @ index.js:7538wrapper @ index.js:1678ReactReconciler.mountComponent @ index.js:5856ReactCompositeComponentMixin.mountComponent @ index.js:7543wrapper @ index.js:1678ReactReconciler.mountComponent @ index.js:5856mountComponentIntoNode @ index.js:2869Mixin.perform @ index.js:6958batchedMountComponentIntoNode @ index.js:2885Mixin.perform @ index.js:6958ReactDefaultBatchingStrategy.batchedUpdates @ index.js:10978batchedUpdates @ index.js:6466ReactMount._renderNewRootComponent @ index.js:3079wrapper @ index.js:1678ReactMount._renderSubtreeIntoContainer @ index.js:3153ReactMount.render @ index.js:3173wrapper @ index.js:1678(anonymous function) @ index.js:435__webpack_require__ @ index.js:20(anonymous function) @ index.js:47__webpack_require__ @ index.js:20(anonymous function) @ index.js:40(anonymous function) @ index.js:43
index.js:2441 Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `TabBar`. See https://fb.me/react-warning-keys for more information.warning @ index.js:2441validateExplicitKey @ index.js:19510validateChildKeys @ index.js:19572ReactElementValidator.createElement @ index.js:19677React.createClass.render @ index.js:261ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext @ index.js:7905ReactCompositeComponentMixin._renderValidatedComponent @ index.js:7925wrapper @ index.js:1678ReactCompositeComponentMixin.mountComponent @ index.js:7538wrapper @ index.js:1678ReactReconciler.mountComponent @ index.js:5856ReactMultiChild.Mixin.mountChildren @ index.js:14396ReactDOMComponent.Mixin._createContentMarkup @ index.js:11579ReactDOMComponent.Mixin.mountComponent @ index.js:11467ReactReconciler.mountComponent @ index.js:5856ReactCompositeComponentMixin.mountComponent @ index.js:7543wrapper @ index.js:1678ReactReconciler.mountComponent @ index.js:5856ReactMultiChild.Mixin.mountChildren @ index.js:14396ReactDOMComponent.Mixin._createContentMarkup @ index.js:11579ReactDOMComponent.Mixin.mountComponent @ index.js:11467ReactReconciler.mountComponent @ index.js:5856ReactCompositeComponentMixin.mountComponent @ index.js:7543wrapper @ index.js:1678ReactReconciler.mountComponent @ index.js:5856ReactCompositeComponentMixin.mountComponent @ index.js:7543wrapper @ index.js:1678ReactReconciler.mountComponent @ index.js:5856ReactCompositeComponentMixin.mountComponent @ index.js:7543wrapper @ index.js:1678ReactReconciler.mountComponent @ index.js:5856mountComponentIntoNode @ index.js:2869Mixin.perform @ index.js:6958batchedMountComponentIntoNode @ index.js:2885Mixin.perform @ index.js:6958ReactDefaultBatchingStrategy.batchedUpdates @ index.js:10978batchedUpdates @ index.js:6466ReactMount._renderNewRootComponent @ index.js:3079wrapper @ index.js:1678ReactMount._renderSubtreeIntoContainer @ index.js:3153ReactMount.render @ index.js:3173wrapper @ index.js:1678(anonymous function) @ index.js:435__webpack_require__ @ index.js:20(anonymous function) @ index.js:47__webpack_require__ @ index.js:20(anonymous function) @ index.js:40(anonymous function) @ index.js:43
index.js:342 webview [Humboldt] did-start-loading Event {isTrusted: false}
index.js:342 webview [HanseMerkur] did-start-loading Event {isTrusted: false}
index.js:342 webview [CI 2.0] did-start-loading Event {isTrusted: false}
index.js:342 webview [Humboldt] did-fail-load Event {isTrusted: false, errorCode: -501, errorDescription: "", validatedURL: "https://mattermost.hanse-merkur.de/humboldt"}
index.js:342 webview [Humboldt] load-commit Event {isTrusted: false, url: "https://mattermost.hanse-merkur.de/humboldt", isMainFrame: true}
index.js:342 webview [Humboldt] did-navigate Event {isTrusted: false, url: "https://mattermost.hanse-merkur.de/humboldt"}
index.js:342 webview [Humboldt] did-stop-loading Event {isTrusted: false}
index.js:342 webview [Humboldt] did-frame-finish-load Event {isTrusted: false, isMainFrame: true}
index.js:342 webview [Humboldt] did-finish-load Event {isTrusted: false}
index.js:342 webview [HanseMerkur] did-fail-load Event {isTrusted: false, errorCode: -501, errorDescription: "", validatedURL: "https://mattermost.hanse-merkur.de/hansemerkur"}
index.js:342 webview [CI 2.0] load-commit Event {isTrusted: false, url: "https://mattermost.hanse-merkur.de/ci-20", isMainFrame: true}
index.js:342 webview [CI 2.0] did-navigate Event {isTrusted: false, url: "https://mattermost.hanse-merkur.de/ci-20"}
index.js:342 webview [CI 2.0] did-stop-loading Event {isTrusted: false}
index.js:342 webview [CI 2.0] did-frame-finish-load Event {isTrusted: false, isMainFrame: true}
index.js:342 webview [CI 2.0] did-finish-load Event {isTrusted: false}
index.js:342 webview [HanseMerkur] load-commit Event {isTrusted: false, url: "https://mattermost.hanse-merkur.de/hansemerkur", isMainFrame: true}
index.js:342 webview [HanseMerkur] did-navigate Event {isTrusted: false, url: "https://mattermost.hanse-merkur.de/hansemerkur"}
index.js:342 webview [HanseMerkur] did-stop-loading Event {isTrusted: false}
index.js:342 webview [HanseMerkur] did-frame-finish-load Event {isTrusted: false, isMainFrame: true}
index.js:342 webview [HanseMerkur] did-finish-load Event {isTrusted: false}
index.js:342 webview [CI 2.0] did-fail-load Event {isTrusted: false, errorCode: -501, errorDescription: "", validatedURL: "https://mattermost.hanse-merkur.de/ci-20"}

**Comment by yuya-oc** [comment]
Thank you! `errorCode: -501` means [INSECURE_RESPONSE (e.g. there was a cert error)](https://code.google.com/p/chromium/codesearch#chromium/src/net/base/net_error_list.h&l=712).

So I want to know following points.
* Are there any SSL/TLS cert issues on the sever or the proxy?
  * e.g. older version, expired cert, self-signed cert, or intermediate cert
* Can the app browse https://google.com? (HTTPS content)
* Can the app browse http://example.com? (HTTP content)

You can add a URL as a team to browse website.

**Comment by finsterwalder** [comment]
Hi,

yes, the Certificate is self signed.
https://google.com and http://example.com work both fine.

Thanks,
   Malte

**Comment by yuya-oc** [comment]
Sorry for late. Does `--ignore-certificate-errors` has effect? If so, this is adhoc solution.

**Comment by finsterwalder** [comment]
Hey,

That does the trick!
Thanks,
   Malte

**Comment by yuya-oc** [comment]
Excuse me, what does "trick" mean? Did you able to see your Mattermost?

**Comment by finsterwalder** [comment]
Yes. It works now.

"That does the trick" is a general saying.

So I'm sure now, that the certificate is somehow invalid.

Thanks,
   Malte

**Comment by yuya-oc** [comment]
I haven't know, thank you.

conclusion:
* `--proxy-server=<SERVER>:<PORT>` set the proxy
  * Authentication not working.
  * Electron might follow system's proxy settings. need to research.
* `--ignore-certificate-errors` ignores some https certificate erros.
  * When certificate is invalid (self-signed, expired, etc. The case Chrome shows warning.)
