### ISSUE TITLE
Taskbar Icon is Inconsistent with Tray Icon and Confusing

### ISSUE THREAD

**Issue by TheDarocker** [mattermost/desktop#260]
I confirm (by marking "x" in the [ ] below): 
- [x] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [x] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [x] This is a product defect issue that can be reproduced using the steps listed below.
- [x] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---
#### Summary

When a message that does not contain a mention of one of your highlight words is sent, the tray icon displays a [blue circle](https://github.com/mattermost/desktop/blob/master/resources/windows/tray_unread.svg) but the taskbar icon shows a red circle with no number inside- something you would expect of a mention. 
#### Steps to reproduce

I think it's pretty easy to reproduce this without instructions p:
- Get message without mention
- Get message with mention

:+1: 
#### Expected behavior

If you are not being mentioned but there are unread messages, the taskbar icon should have a blue circle similar to the tray icon. It's expected that mentions are red, and non-mentions should be blue.
#### Observed behavior

![Image](http://darocker.xyz/sc/SX-2016-08-22-1471922844.png)
Icon without any unread messages.

![AnotherImage](http://darocker.xyz/sc/SX-2016-08-22-1471923239.png)
Icon with an unread message, a non-mention.

![GuessWhatThisIs](http://darocker.xyz/sc/SX-2016-08-22-1471923327.png)
Icon with a mention, red as it should be.
#### Possible fixes

Not sure. Whatever code handles the creation of the badge.

**Comment by Razzeee** [comment]
I changed the behaviour to the one expected from you some time ago, as I had the same expectations. 
But the rest of the people here didn't really like that unfortunately.

**Comment by Razzeee** [comment]
Please see https://github.com/mattermost/desktop/issues/194 for example

**Comment by jasonblais** [comment]
Hello @TheDarocker, thanks for your feedback!

And very sorry for the late reply -- I was away last week and have been catching up on things.

The red dot will be more consistent with mobile apps; at the moment mobile apps display a red badge with a number counter on unread channels, but the long term plan is to have 
 - red dot for unread messages
 - red dot with number counter for unread mentions

The current behaviour in the desktop app is also more consistent with other apps we researched. I'm not sure a blue dot would be more obvious for unread messages (we use it for the system tray icon given numbers cannot be used to display mentions).

That being said, @Razzeee helped [submit a pull request](https://github.com/mattermost/desktop/pull/201), which allows you to configure whether  a red dot is displayed for unread messages on Windows and Mac OS X. This will be included in the v1.4 release

**Comment by jasonblais** [comment]
Thanks again @TheDarocker for the suggestion,

If you're interested continuing the discussion, please consider joining the [Mattermost Desktop App channel](https://pre-release.mattermost.com/core/channels/desktop-app). 

There is also an open [Help Wanted issue for how unread messages and mentions are shown on mobile](https://github.com/mattermost/platform/issues/4590), added from an older Jira ticket on the server side.
