### ISSUE TITLE
[Bug]: Installation gives warning: update-desktop-database: command not found

### ISSUE THREAD

**Issue by dionysius** [mattermost/desktop#2611]
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.3.0-rc.4-28893

### Operating System

Devuan Chimaera with KDE Desktop Environment

### Steps to reproduce

- Get a (virtual) system with [devuan chimaera](https://www.devuan.org/os/install)
- Install latest mattermost deb package on this system (`sudo dpkg -i mattermost....deb`)
- Apply installation of dependencies and finalize the installation of mattermost (`sudo apt-get install -f`)
- Observe the output for the error:
```
/var/lib/dpkg/info/mattermost-desktop.postinst: line 10: update-desktop-database: command not found
```

### Expected behavior

postinst succeeds without warning/error

### Observed behavior

postinst succeeds correctly without throwing warning/error

### Log Output

```shell
$ sudo dpkg -i Downloads/mattermost-desktop_5.3.0-rc.4-1_amd64.deb 
Selecting previously unselected package mattermost-desktop.
(Reading database ... 323301 files and directories currently installed.)
Preparing to unpack .../mattermost-desktop_5.3.0-rc.4-1_amd64.deb ...
Unpacking mattermost-desktop (5.3.0-rc.4-28893) ...
dpkg: dependency problems prevent configuration of mattermost-desktop:
 mattermost-desktop depends on gconf2; however:
  Package gconf2 is not installed.
 mattermost-desktop depends on gconf-service; however:
  Package gconf-service is not installed.

dpkg: error processing package mattermost-desktop (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for mailcap (3.69) ...
Errors were encountered while processing:
 mattermost-desktop

$ sudo apt-get install -f
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  gconf-service gconf2 gconf2-common libgconf-2-4
Suggested packages:
  gconf-defaults-service
The following NEW packages will be installed:
  gconf-service gconf2 gconf2-common libgconf-2-4
0 upgraded, 4 newly installed, 0 to remove and 9 not upgraded.
1 not fully installed or removed.
Need to get 2’310 kB of archives.
After this operation, 8’327 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://deb.devuan.org/merged chimaera/main amd64 gconf2-common all 3.2.6-7 [1’039 kB]
Get:2 http://deb.devuan.org/merged chimaera/main amd64 libgconf-2-4 amd64 3.2.6-7 [428 kB]
Get:3 http://deb.devuan.org/merged chimaera/main amd64 gconf-service amd64 3.2.6-7 [415 kB]
Get:4 http://deb.devuan.org/merged chimaera/main amd64 gconf2 amd64 3.2.6-7 [427 kB]
Fetched 2’310 kB in 9s (265 kB/s)                                              
Selecting previously unselected package gconf2-common.
(Reading database ... 323403 files and directories currently installed.)
Preparing to unpack .../gconf2-common_3.2.6-7_all.deb ...
Unpacking gconf2-common (3.2.6-7) ...
Selecting previously unselected package libgconf-2-4:amd64.
Preparing to unpack .../libgconf-2-4_3.2.6-7_amd64.deb ...
Unpacking libgconf-2-4:amd64 (3.2.6-7) ...
Selecting previously unselected package gconf-service.
Preparing to unpack .../gconf-service_3.2.6-7_amd64.deb ...
Unpacking gconf-service (3.2.6-7) ...
Selecting previously unselected package gconf2.
Preparing to unpack .../gconf2_3.2.6-7_amd64.deb ...
Unpacking gconf2 (3.2.6-7) ...
Setting up gconf2-common (3.2.6-7) ...
Processing triggers for libc-bin (2.31-13+deb11u5) ...
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for sgml-base (1.30) ...
Setting up libgconf-2-4:amd64 (3.2.6-7) ...
Setting up gconf-service (3.2.6-7) ...
Setting up gconf2 (3.2.6-7) ...
Setting up mattermost-desktop (5.3.0-rc.4-28893) ...
/var/lib/dpkg/info/mattermost-desktop.postinst: line 10: update-desktop-database: command not found
Processing triggers for libc-bin (2.31-13+deb11u5) ...
needrestart is being skipped since dpkg has failed
```

### Additional Information

Even through the error, the installation succeeds and is available as application icon and so far works fine

**Fix suggestion**
- Either make calling `update-desktop-database` optional in postinst if not available
- Or make a dependency to [`desktop-file-utils`](https://salsa.debian.org/freedesktop-team/desktop-file-utils/-/blob/master/debian/control) if really required

**Comment by devinbinnie** [comment]
I don't think we have any control over this, our `.deb` packages are created by `electron-builder` and they attach this call themselves: (see here: https://github.com/electron-userland/electron-builder/blob/54c85374790f7a8e0dc520a20c716b4afe69be20/packages/app-builder-lib/templates/linux/after-install.tpl#L17)

Since as per that script there's no consequence to that script not being able to be run (given the `|| true`) I think we safely leave it as is.

Closing.
