### ISSUE TITLE
[Bug]: White bar with "Back" button only

### ISSUE THREAD

**Issue by samueltootle** [mattermost/desktop#2622]
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

Version 5.2.2 commit: 2030c66

### Operating System

Linux pop-os 6.2.0-76060200-generic

### Mattermost Server Version

7.8.1

### Steps to reproduce

Always present after opening Mattermost Application.  Behaviour is not present when using the web app in Firefox or Chrome.

### Expected behavior

I would not expect this white bar to be present

### Observed behavior

When opening the app, the bar is immediately present underneath the server tabs.  It is always white and the only thing on this bar is a "Back" link
![image](https://user-images.githubusercontent.com/41571724/225585614-d538066d-8100-427c-9339-ef729f74894e.png)

### Log Output

```shell
None found [Help]>[Show logs] does not exist.
```

**Comment by irrationalnumbers** [comment]
> @irrationalnumbers Can you confirm that your configured server URL matched the Site URL on the server?

Yes, the server URL matches. The only issue is this bar. The app itself works fine. I can see chats, talk to people etc. The image only shows the bar to avoid sharing private information.

**Comment by devinbinnie** [comment]
Sorry, must have lost track of this one. This bar is only supposed to show itself when the view for the server is on a page that is not internal to the application, and we verify this by checking if the URL is on a subpath of the configured internal URL.

Sorry to reiterate, but can you definitely confirm that there is no difference between the URL in your server configuration and the `SiteURL` field on your server? This includes the protocol and the subpath.

**Comment by devinbinnie** [comment]
Closing as inactive.
