### ISSUE TITLE
[Bug]: Wrong datetime for Asia/Tehran Timezone

### ISSUE THREAD

**Issue by soheilrahsaz** [mattermost/desktop#2636]
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.0.4

### Operating System

Windows 10 x64

### Mattermost Server Version

7.8.1

### Steps to reproduce

From [22-September 2022 onwards, Iran will abolish DST and observe standard time year-round](https://en.wikipedia.org/wiki/Daylight_saving_time_in_Iran)
It is now showing the wrong datetime value in the desktop version and it is calculating DST which it should not.
The values are stored correctly in the database and are shown correctly on web browser and mobile application.

### Expected behavior

When a message is sent at 03:00 it is expected to see the sent time as 03:00 not 04:00

### Observed behavior

It adds 1 hour to the time the messages are shown

### Log Output

```shell
There is no [Help] > [Show logs].
```

**Comment by devinbinnie** [comment]
@soheilrahsaz Can you reproduce this issue on Desktop version 5.2.2? If so, can you confirm it also doesn't reproduce on the browser?

**Comment by soheilrahsaz** [comment]
It works ok on version 5.2.2.
And also ok on browser.
