### ISSUE TITLE
[Bug]: Cannot access the Board plugin on Windows

### ISSUE THREAD

**Issue by q-wertz** [mattermost/desktop#2639]
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.2.2

### Operating System

Windows 11 x64

### Mattermost Server Version

7.9.x

### Steps to reproduce

Navigate to the Boards tab

### Expected behavior

The Boards show up

### Observed behavior

White screen with message 

> Redirecting to error page…

In the Browser everything works fine and both URLs mentioned in the log output are accessible and show the focalboard.

On at least two Linux clients it is working (did not yet have the opportunity to check on other windows machines)

### Log Output

```shell
[2023-03-28 13:12:42.293] [debug] webContentEvents.did-start-navigation {
  webContentsId: 28,
  url: 'https://chat.asdf.com/boards/plugins/focalboard/error?id=unknown'
}
[2023-03-28 13:12:42.294] [debug] webContentEvents.will-navigate {
  webContentsId: 28,
  url: 'https://chat.asdf.com/boards/plugins/focalboard/error?id=unknown'
}
[2023-03-28 13:12:42.295] [info]  Prevented desktop from navigating to: https://chat.asdf.com/boards/plugins/focalboard/error?id=unknown
[2023-03-28 13:12:42.674] [debug] WindowManager.handleReactAppInitialized Mattermost-INS___TAB_FOCALBOARD
[2023-03-28 13:12:42.675] [debug] WindowManager.handleBrowserHistoryButton Mattermost-INS___TAB_FOCALBOARD
[2023-03-28 13:12:43.736] [debug] WindowManager.handleLoadingScreenAnimationFinished
[2023-03-28 13:13:04.023] [debug] Utils.flushCookiesStore
[2023-03-28 13:13:06.155] [debug] Config.handleGetConfiguration undefined
[2023-03-28 13:13:06.192] [debug] DownloadsManager.hasDownloads
[2023-03-28 13:13:33.482] [debug] Initialize.UserActivityMonitor.on(status) { userIsActive: true, idleTime: 0, isSystemEvent: false }
[2023-03-28 13:14:34.101] [debug] Initialize.UserActivityMonitor.on(status) { userIsActive: true, idleTime: 1, isSystemEvent: false }
[2023-03-28 13:15:34.709] [debug] Initialize.UserActivityMonitor.on(status) { userIsActive: true, idleTime: 0, isSystemEvent: false }
[2023-03-28 13:16:35.266] [debug] Initialize.UserActivityMonitor.on(status) { userIsActive: true, idleTime: 0, isSystemEvent: false }
[2023-03-28 13:17:04.131] [debug] WindowManager.focusBrowserView
```
```


### Additional Information

The following things did not help:
1. Logout and login again
2. Delete the server and do a fresh connect

**Comment by q-wertz** [comment]
Thanks for your reply. What exactly do you mean?

What I tried yesterday: I copied the URL `https://chat.asdf.com/boards/plugins/focalboard` from the error message and entered it in the Browser and could access the board…

What I am curious about in the error log is the `error?id=unknown` part. Shouldn't there be an `28`?

**Comment by q-wertz** [comment]
Ah sorry, there is something strange. In my browser `https://chat.asdf.com/boards/plugins/focalboard` also is empty. `https://chat.asdf.com/boards/` works fine...

But this link is generated by the desktop application… When connecting to the server I entered (on all devices) `https://chat.asdf.com`

**Comment by devinbinnie** [comment]
@q-wertz Okay so seems like the URL is correct, but I'm not sure why you're being redirected to `https://chat.asdf.com/boards/plugins/focalboard`. I'm wondering if the link is wrong or something is misconfigured on your server.

**Comment by q-wertz** [comment]
But as it is working in the Browser and the other clients it shouldn't be an issue on the server side, or?

I checked it on my Linux machine (where no issues appear). There it looks like
```
17:40:28.558 › webContentEvents.did-start-navigation {
  webContentsId: 8,
  url: 'https://chat.asdf.com/boards/team/ugxy7475s3rz9mq5d9dpnm747c/babco1x4hmpdn3rzjutapcpc3uc/v4kd4cgrj3ty63eaqtkmpdhhq9w'
}
17:40:28.564 › WindowManager.handleAppLoggedIn INS___TAB_MESSAGING
17:40:28.565 › webContentEvents.did-start-navigation {
  webContentsId: 8,
  url: 'https://chat.asdf.com/boards/team/ugxy7475s3rz9mq5d9dpnm747c/babco1x4hmpdn3rzjutapcpc3uc/v4kd4cgrj3ty63eaqtkmpdhhq9w'
}
17:40:28.621 › MattermostView.handleTitleUpdate { tabName: 'INS___TAB_FOCALBOARD', title: 'Boards - Mattermost' }
```
So the link and redirect is fine (no `plugins/focalboard` part).

Will check tomorrow again on the Windows machine and report back. Thanks for your help so far

**Comment by devinbinnie** [comment]
> But for some reason `couldn't show INS___TAB_FOCALBOARD, not ready`

That's normal to come up while the view is loading. `viewManager.showByName INS___TAB_FOCALBOARD` is where it should actually be displayed.

**Comment by q-wertz** [comment]
Ok.
I tested on another Windows instance (Windows 10) and there also no problems.
So only on one Client so far.

I already tried `Clear Cache and Reload` functionality, logging out, deleting the server. Any other suggestions? :sweat_smile:

**Comment by devinbinnie** [comment]
Maybe a full re-install of the app? Also, just double check that there are no pre-configured servers on that machine (via Group Policy, build config, etc.)
Could also be some kind of redirect on that exact machine.

**Comment by q-wertz** [comment]
closing the issue as it seems to be a specific problem of that one PC.
