### ISSUE TITLE
Use eslint to enforce/help with common errors

### ISSUE THREAD

**Issue by Razzeee** [mattermost/desktop#266]
See discussion in: https://github.com/mattermost/desktop/pull/265

About eslint: http://eslint.org/

**Comment by yuya-oc** [comment]
Current candidate of eslint rule in my thought:

- Based on [mattermost/platform/webapp/.eslintrc.json](https://github.com/mattermost/platform/blob/master/webapp/.eslintrc.json): It's very explicit, so it seems hard to maintain for us.
- Based on [eslint-config-airbnb](https://github.com/airbnb/javascript): This includes the style guide for React. And one of the choices in `eslint init`.

**Comment by Razzeee** [comment]
I've just drafted this bases on the platform/webapp and some customization for our usecase.
https://github.com/Razzeee/desktop/tree/eslint

There are quite a few errors showing up, but we should take our time and remove them or align the rules.

**Comment by Razzeee** [comment]
Should this replace prettify?

**Comment by Razzeee** [comment]
Please check out https://github.com/Razzeee/desktop/tree/eslint if you can, it should be a good first start. We might do some more automation.

**Comment by yuya-oc** [comment]
Thanks! The purpose of prettify was to format coding style, so I feel eslint can replace it.

**Comment by yuya-oc** [comment]
@Razzeee Any updates for eslint? I feel that just adding the config is sufficient to start for now.

**Comment by Razzeee** [comment]
You can just grab my branch then, I'm off for a week on vacation
