### ISSUE TITLE
[Bug]: Clicking on tray icon making unfocused window to hide instead moving it in front

### ISSUE THREAD

**Issue by Profesor08** [mattermost/desktop#2661]
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.3.0

### Operating System

Windows 10 x64

### Mattermost Server Version

7.7.1

### Steps to reproduce

1. Open mattermost
2. Open some other application
3. Click on mattermost tray icon

### Expected behavior

mattermost to move in front

### Observed behavior

mattermost is hiding to tray

### Log Output

```shell
No errors
```

### Additional Information

It was broken in this pull request https://github.com/mattermost/desktop/pull/2508
There must be some check if window is in front or not.

**Comment by devinbinnie** [comment]
Created a JIRA ticket: https://mattermost.atlassian.net/browse/MM-51886

**Comment by devinbinnie** [comment]
Closed the original bug and have created a new ticket based on was discussed internally: https://mattermost.atlassian.net/browse/MM-52625
