### ISSUE TITLE
CircleCi Settings

### ISSUE THREAD

**Issue by Razzeee** [mattermost/desktop#267]
Hey @yuya-oc 

are there any hidden CircleCi Settings I need to do when I want to build the solution via circleci?
My branch is failing so far: 
https://circleci.com/gh/Razzeee/desktop/3

**Comment by yuya-oc** [comment]
For now, you have to use ubuntu 12.04 build image. I could not find out the way to specify the image in `circle.yml`.

**Comment by Razzeee** [comment]
Doesn't seem to work :/
https://circleci.com/gh/Razzeee/desktop/5

**Comment by yuya-oc** [comment]
Still using ubuntu-14.04 (see "Start container" section). Please check "Build Environment" section in the settings page?

![build_environment](https://cloud.githubusercontent.com/assets/1412057/18222195/0e515d10-71ca-11e6-9f5f-b78a6fce9c8c.png)

Probably I can upgrade the image to ubuntu-14.04, but for now it should be done after v1.4.0.

**Comment by Razzeee** [comment]
Weird, I did change that. Will have to look again

**Comment by Razzeee** [comment]
I was able to fix this by pushing something again, only then the new server version get's picked up.
