### ISSUE TITLE
[Bug]: 5.3.x should refuse to install on Windows 8.x

### ISSUE THREAD

**Issue by licaon-kter** [mattermost/desktop#2671]
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.2.2

### Operating System

Windows 8.1

### Steps to reproduce

Use Windows 8
Get an [erroneous update notification](https://github.com/mattermost/desktop/issues/2670)

### Expected behavior

Updater would error out and inform the user that it is not compatible with Windows 8.x

### Observed behavior

App installing just fine and then crash

### Log Output

```shell
-
```

**Comment by devinbinnie** [comment]
Looks like we should probably see if we can find a way to block future updates from installing on Windows 8 and later.

Unfortunately I don't believe there's anything we can do from having older versions try and download and update, our auto updater is built on `electron-updater` and I don't believe there's a way to do this. Will have a look though anyways.

**Comment by licaon-kter** [comment]
When checking for updates, the useragent does not leak OS version?

**Comment by devinbinnie** [comment]
Yes, but we would have to make a fix to the app itself, but since we don't support Windows 8 anymore it would never go out to it. So the solution would be to try and stop future installers from installing the app on Windows 8 and earlier.

**Comment by devinbinnie** [comment]
Created a JIRA ticket: https://mattermost.atlassian.net/browse/MM-51987

**Comment by licaon-kter** [comment]
If you see useragent, then you can have the server say: _"no updates, go away"_

**Comment by devinbinnie** [comment]
We would have to do some strange configuration on our server in order to do this, and that's not something we're looking to support.

What we COULD do is for future versions of the application, we might be able to add a custom script that would check for the Windows version and refuse to install if it's an older version. However, this would likely be a fair amount of work, and this currently isn't a priority for us, since Microsoft is already encouraging users to move off of Windows 7 and 8.

I'm going to close this bug for now. The above ticket will serve to track this issue going forward.

**Comment by licaon-kter** [comment]
So you know you are going to continue breaking users installs yet you close this anyway? ಠ_ಠ
