### ISSUE TITLE
[Bug]: server url will be changed

### ISSUE THREAD

**Issue by yiruchen1993** [mattermost/desktop#2679]
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.3.1

### Operating System

win 10 x64, macOS Ventura 13.3 (Intel Core i5)

### Mattermost Server Version

7.9.1

### Steps to reproduce

When I set a new Server URL to http://{my_host}:{my_port} and I found that I cannot login, and check the url again in Edit Server dialog, it has been changed to http://{my_host}.

### Expected behavior

Successful login

### Observed behavior

Cannot login

### Log Output

```shell
[2023-04-14 09:14:14.217] [info]  preloading with /Applications/Mattermost.app/Contents/Resources/app.asar/desktopAPI.js
[2023-04-14 09:14:22.059] [info]  Saving config data to file...
[2023-04-14 09:14:22.243] [info]  Saving config data to file...
[2023-04-14 09:14:22.314] [info]  [test___TAB_MESSAG...] failed loading http://{my_host}:{my_port}/: Error: ERR_FAILED (-2) loading 'http://{my_host}:{my_port}/', retrying in 5 seconds

p.s. I replace the host and port with symbol {my_host}:{my_port}
```

**Comment by anx-ag** [comment]
Hi @yiruchen1993 ,

Please check your `SiteUrl` setting (System Console -> Environment -> Web Server). The clients redirect to the value specified in the `SiteURL` so make sure what is configured there is also the URL your installation is reachable at. Depending on your installation type, you might not be able to change the value in your system console if it is being overridden by environment variables f.ex., in docker deployments, you would have to check the value of the variable `MM_SERVICESETTINGS_SITEURL` in your `.env` file.

**Comment by yiruchen1993** [comment]
After I modify the variable MM_SERVICESETTINGS_SITEURL in .env file, it works, thanks.
