### ISSUE TITLE
[Bug]: No more tray icon on Linux

### ISSUE THREAD

**Issue by dtrunk90** [mattermost/desktop#2681]
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

Version 5.3.1 commit: 2c3d80f

### Operating System

Ubuntu Budgie Linux 20.04.6 LTS x64

### Steps to reproduce

Enable tray icon in settings and restart mattermost

### Expected behavior

Tray icon should be visible

### Observed behavior

There's no more tray icon

### Log Output

```shell
[2023-04-17 09:09:57.321] [debug] DownloadsManager.init { 'this.json': {}, validatedJSON: {} }
[2023-04-17 09:09:57.327] [debug] DownloadsManager.saveAll
[2023-04-17 09:09:57.328] [debug] DownloadsManager.checkForDeletedFiles
[2023-04-17 09:09:57.370] [error] Log level set to: error
```

### Additional Information

Workaround:
```
$ apt-cache policy mattermost-desktop
mattermost-desktop:
  Installed: 5.3.1-496
  Candidate: 5.3.1-496
  Version table:
 *** 5.3.1-496 500
        500 https://deb.packages.mattermost.com stable/main amd64 Packages
        100 /var/lib/dpkg/status
     5.2.2-382 500
        500 https://deb.packages.mattermost.com stable/main amd64 Packages
     ...
$ sudo apt install mattermost-desktop=5.2.2-382
```

Now the tray icon is back again.
So the issue got introduced in either 5.3.0 (which i didn't tested because there doesn't seem to be a final release) or 5.3.1. I guess it was this commit: https://github.com/mattermost/desktop/commit/8efa3480e4f125f1da9843c7aee2f010fcab73b1
and the issue is somewhere in electron 23.1.0, 23.1.1 or 23.1.2.

Maybe related to https://github.com/electron/electron/issues/36602

**Comment by razzeee** [comment]
Is it really gone? I seem to have a black icon on a black background now, with gnome 44

**Comment by dtrunk90** [comment]
Yes, it's gone on Budgie.

**Comment by IceWreck** [comment]
I have it on flatpak fedora but the latest update did mess something up.

The tray menu for mattermost now has a weird theme, and the icon looks pixelated unlike the high res tray icon before.

Other than the tray, the electron menu (File, Edit, View, Help, etc) also looks different (doesn't respect theme) compared to before.

**Comment by IceWreck** [comment]
The packaging method did not change but something happened with the tray icon due to the latest update. Seems related.

Mine is pixelated, somebody else claims they have a black icon and you dont have one at all. Something happened.

**Comment by dtrunk90** [comment]
Btw: I've noticed the same for Element (matrix Chat) which is also an Electron app.

**Comment by IceWreck** [comment]
Does element use the same electron version ? Could be that something changed on electron's end.

**Comment by razzeee** [comment]
My problem was also with the flatpak. But it seems like I can get it to work again, by allowing the flatpak to access the session bus - but that's probably not the correct solution.

**Comment by razzeee** [comment]
https://github.com/flathub/com.mattermost.Desktop/pull/87#issuecomment-1510465967

**Comment by dtrunk90** [comment]
Since it's not a mattermost issue I'm closing this. It's definitely related to electron. They moved to StatusNotifier spec instead of libappindicator. Budgie's system tray is based on XEmbed and they're already about to fix this is Budgie 10.8.

So, the workaround for now is to either downgrade the software (happens on discord, electron, mattermost because they all are electron apps) or just disable the "minimize to tray" features and keep the software always open.

**Comment by dtrunk90** [comment]
Reopening due to https://github.com/electron/electron/issues/40493#issuecomment-1804753975

**Comment by devinbinnie** [comment]
@dtrunk90 I've commented on the Electron issue. We can continue the discussion there. Closing.
