### ISSUE TITLE
[Bug]: 100% Black Screen after minimizing and restoring mattermost from tray

### ISSUE THREAD

**Issue by pampersrocker** [mattermost/desktop#2689]
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

Version 5.3.1 commit: 2c3d80f

### Operating System

Windows 11 x64

### Mattermost Server Version

7.7.1

### Steps to reproduce

1. Minimize Mattermost using the Minimize Button on the top right
2. Click on the tray icon to restore it -> window disappears
3. Click again on the tray icon to restore it -> black window appears where nothing is interactible
4. Click again on the tray icon -> window is restored.

### Expected behavior

Window is restored on the first click to the tray icon, if the main window is minimized.

### Observed behavior

Window has 2 different states before it gets restored properly

### Log Output

```shell
[2023-04-24 10:58:01.125] [info]  restoreMain
[2023-04-24 10:58:02.848] [info]  restoreMain
```

### Additional Information

This happens on multiple machines.
When GPU acceleration is disabled, the second click spawns an invisible instead of black window.

**Comment by devinbinnie** [comment]
Thanks for the report, we have a ticket open for this: https://mattermost.atlassian.net/browse/MM-51991

**Comment by googman** [comment]
+1

Windows 11. 
Black screen instead of window (not always, occasionally).
It happened at my pc and some of my colleagues experience the same problem.
This bug is on two latest versions at least so we're forced to use the very old version of mattermost client (5.1.1)

![image](https://user-images.githubusercontent.com/37333953/235673520-c26cbaff-eb97-4ddc-94a2-84acc6479c56.png)

**Comment by devinbinnie** [comment]
This should be fixed on the master branch, you can verify using one of the nightly builds here: https://community.mattermost.com/core/channels/desktop-builds

**Comment by devinbinnie** [comment]
Closing as this issue should be resolved as per this comment: https://community.mattermost.com/core/pl/zzzmjyr1pbgijnmdgwf86q13co
