### ISSUE TITLE
Clicking "Help" below text box opens a blank white screen on Mac

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#269]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [X] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [X] This is a product defect issue that can be reproduced using the steps listed below.
- [X] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

Clicking "Help" below text box opens a blank white screen on Mac.

#### Steps to reproduce

On Mac Desktop app v1.3, Mattermost server 3.4

1) Open a Mattermost instance
2) Click on "Help" which appears below the textbox

Given this reproduces on Mattermost 3.4, which has not yet been released, you can reproduce this issue on the daily pre-built instance of Mattermost in https://pre-release.mattermost.com/core

#### Expected behavior

A popup screen appears with title "Messaging Basics" (the text comes from https://docs.mattermost.com/help/getting-started/messaging-basics.html)

#### Observed behavior

A blank white popup screen appears.

#### Possible fixes

?

**Comment by yuya-oc** [comment]
Not reproduced in pre-release on my Mac. Possibly we have to check with RC server.

**Comment by jasonblais** [comment]
Thanks @yuya-oc, I'll confirm with the original reported whether this reproduces consistently.

**Comment by jasonblais** [comment]
Verified with original reporter that the page loads after a couple of seconds.

Closing as it's not a bug.
