### ISSUE TITLE
[Bug]: Hyperlinks with the same hostname as mattermost server are assumed to be channel links

### ISSUE THREAD

**Issue by motlaghreyhan** [mattermost/desktop#2692]
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.3.1

### Operating System

MacOS Ventura & PopOS

### Mattermost Server Version

7.9.1

### Steps to reproduce

Clicking on link with same domain as server produces the error below. We host a gitlab instance on the same domain.

### Expected behavior

Link should open in web browser as if it were any other link, since it isn't /mm

### Observed behavior

No Matching Server
There is no configured server in the app that matches the requested url: https://domain/-/snippets/75

### Log Output

```shell
No Matching Server
There is no configured server in the app that matches the requested url: https://domain/-/snippets/75
```

### Additional Information

Links to the same hostname are assumed to be a mattermost channel and can't be clicked on (likely due to our configuration being hostname/mm and not mm.hostname)

**Comment by devinbinnie** [comment]
Thanks, created a ticket here: https://mattermost.atlassian.net/browse/MM-52587
