### ISSUE TITLE
[Bug]: The calls panel is not fully displayed

### ISSUE THREAD

**Issue by googman** [mattermost/desktop#2701]
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

Version 5.3.1 commit: 2c3d80f

### Operating System

Windows 11 x64

### Mattermost Server Version

7.7.3

### Steps to reproduce

Please see an attached videoclip:
https://user-images.githubusercontent.com/37333953/235679149-33f5bf37-6aa6-49e0-bee2-007e7c6f1ef8.mp4

### Expected behavior

Phone call panel should be visible during the call.

### Observed behavior

The panel (popout) with phone call controls is not fully displayed (partially hidden) when making a call. It doesn't allow me to press some buttons (f.e. break the call). Furthermore, after focusing cursor to chat area the panel disappears completely.

### Log Output

```shell
Sorry. I can't include logs. I've checked it and see that logs contain chat messages in clear text. It's a security-sensitive info.
```

### Additional Information

- The bug is reproduced on several recent versions of the client (including 5.3.1, 5.3.0, 5.2.2).
- The bug is not happening on old version of the client 5.1.1 (I haven't checked any other versions between 5.1.1 and 5.2.2 for this bug).

**Comment by googman** [comment]
I forgot to mention that all my colleagues, not just me, experience this problem on the above versions.

**Comment by streamer45** [comment]
That would be expected if the issue is the plugin although I'd be very surprised if this issue reproduces on desktop app 5.2.x since the way the calls widget renders was only changed in 5.3

**Comment by streamer45** [comment]
Yeah, there was a breaking change we introduced in Desktop 5.3 that requires the plugin to be at least at version 0.13
Thanks for checking, let us know when you upgrade.

**Comment by googman** [comment]
Unfortunately, updating the Calls plugin to version 0.15.1 did not help.
![image](https://user-images.githubusercontent.com/37333953/235685051-25cfca8d-dd54-4dbf-b61e-7370761b0aae.png)

We've restarted Mattermost Server after the plugin update but the problem is still reproducing. :(
![image](https://user-images.githubusercontent.com/37333953/235684779-d128b031-9143-48db-8bbe-2f0de680f3e1.png)

**Comment by streamer45** [comment]
@googman Could you make sure to hard refresh the app (Ctrl-Shift+R) ? Maybe it's still loading some cached version.

**Comment by googman** [comment]
@streamer45 Yeah, it helped (Ctrl+Shift+R)! Thank you!
