### ISSUE TITLE
[Bug]: Custom SAML2.0 doesn't show MFA popup

### ISSUE THREAD

**Issue by itsmichaelk** [mattermost/desktop#2715]
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.3.1

### Operating System

macOS Ventura 13.2.1 Apple Silicon M2

### Mattermost Server Version

7.9.1

### Steps to reproduce

Add the Mattermost server to AWS Identity Center as a custom SAML2.0 application.
Open the Mattermost client on macOS and click on the SAML login button.
Enter the username and click on next.
Enter the password and click on next.
Wait for the popup that prompts you to choose your MFA device.
Select the MFA device and get logged in.

### Expected behavior

As soon as I type in my username and password, I'll get prompted for my already added MFA devices. I can choose one and proceed.

### Observed behavior

As soon as I type in my username and password, the page is loading but I get no MFA device prompt (pop up).

### Log Output

```shell
[2023-05-08 11:33:44.763] [info]  {TEAMNAME}___TAB_MESSAGING timeout expired will show the browserview
```

### Additional Information

In the browser version it works just perfectly, but in the client I think the popup gets surpressed.
I don't know if the log output helps.

**Comment by devinbinnie** [comment]
@itsmichaelk When you say MFA device are you referring to a physical security key (eg. YubiKey)?
If so, there is a fix for the App Store app here: https://github.com/mattermost/desktop/pull/2710
As for the DMG app, Electron does not show a popup for a security key on macOS for some reason, and they don't give us a hook into the process to allow us to pop one, however, the key will still work. You just won't get a popup.
Hope that helps :)

**Comment by itsmichaelk** [comment]
@devinbinnie thanks for your answer!
Yup, I was talking about a physical security key (YubiKey).
I just downloaded the DMG app and tried it - I get no popup (as you already said) but the MFA token is accepted and I get redirected to Mattermost.
Sadly every Mac in our company is using the AppStore version.. so we just have to wait for an update?
Thanks in advance!
