### ISSUE TITLE
[Bug]: Red dot on Desktop version remains after reading all new messages

### ISSUE THREAD

**Issue by dyve** [mattermost/desktop#2723]
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.3.1 (46002745061)

### Operating System

macOS Ventura 13.3.1 (a) (22E772610a)

### Mattermost Server Version

7.1.4

### Steps to reproduce

- Install Mattermost for Mac
- Connect to server
- Wait for new content
- See red dot on Dock Icon
- Read all new content
- Red dot on Dock Icon remains
- Close Mattermost
- Reopen Mattermost
- Red dot icon is gone
- Wait for new content and repeat.

### Expected behavior

- Red dot disappears from Dock icon when there is no more new content

### Observed behavior

See Steps to reproduce.

### Log Output

Some content replaced with `xxxxx/XXXXX`

```shell
[2023-05-17 06:30:15.162] [debug] DownloadsManager.init { 'this.json': {}, validatedJSON: {} }
[2023-05-17 06:30:15.170] [debug] DownloadsManager.saveAll
[2023-05-17 06:30:15.170] [debug] DownloadsManager.checkForDeletedFiles
[2023-05-17 06:30:15.204] [warn]  Current working directory is /Users/xxxxx/Library/Containers/Mattermost.Desktop/Data, changing into /Applications/Mattermost.app/Contents/MacOS
[2023-05-17 06:30:15.289] [info]  Autoupgrade disabled: false
[2023-05-17 06:30:15.328] [warn]  couldn't show XXXXX___TAB_MESSAGING, not ready
[2023-05-17 06:30:15.328] [info]  Set new language nl
[2023-05-17 06:30:15.812] [info]  Can't send load_success, will retry
[2023-05-17 06:30:15.813] [info]  Can't send update_mentions, will retry
[2023-05-17 06:30:15.815] [info]  Can't send load_success, will retry
[2023-05-17 06:30:15.815] [info]  Can't send update_mentions, will retry
[2023-05-17 06:30:15.816] [info]  Can't send load_success, will retry
[2023-05-17 06:30:15.829] [info]  Can't send update_mentions, will retry
[2023-05-17 07:39:21.533] [warn]  main window closed
[2023-05-17 07:39:23.137] [debug] DownloadsManager.init { 'this.json': {}, validatedJSON: {} }
[2023-05-17 07:39:23.142] [debug] DownloadsManager.saveAll
[2023-05-17 07:39:23.142] [debug] DownloadsManager.checkForDeletedFiles
[2023-05-17 07:39:23.188] [warn]  Current working directory is /Users/xxxxx/Library/Containers/Mattermost.Desktop/Data, changing into /Applications/Mattermost.app/Contents/MacOS
[2023-05-17 07:39:23.269] [info]  Autoupgrade disabled: false
[2023-05-17 07:39:23.300] [warn]  couldn't show XXXXX___TAB_MESSAGING, not ready
[2023-05-17 07:39:23.301] [info]  Set new language nl
```

### Additional Information

Might be a regression of or connected to #2108.

**Comment by devinbinnie** [comment]
I can't reproduce this one myself, have you tried removing your server and seeing if the issue still reproduces? If you want to test against a different server, feel free to make an account on `community.mattermost.com` and work from that.

You can use the `Mark as Unread` feature to force unreads to come in (or you can make 2 accounts)

**Comment by dyve** [comment]
I did remove the server, I also tried removing the app and all support files and reinstalling. I will try the community server to see if I can reproduce.

**Comment by dyve** [comment]
Well, both Mark as unread and the Unread icon seem broken.

First of all, it's a pain to mark an individual item as unread, because using the right click focuses on the item and immediately afterwards marks it as read. I used the browser and some fast mouse movements, maybe a UI race issue there.

Using Mark as Unread, it's easy to create an unread item and no red marker. This is on the Community Server.

Also, there seem to be 3 red dots:

- red dot without a number
- red dot with a number (appears when you have unread DM's?)
- red dot with a black circle in it (not sure when that one appears)

Screenshot of unread message in channel _Reception_ but no red dot (OS is set to Dutch so those are the strange words and texts):

![Scherm­afbeelding 2023-05-19 om 08 52 44](https://github.com/mattermost/desktop/assets/82315/d0fc0bfd-6e35-4405-bcfa-da81840bc533)

**Comment by dyve** [comment]
Possible workaround/solution: after clicking Mark as Unread several times in several channels on the main server we use, on both message and channel level, the red dot now disappears after viewing new information.

**Comment by devinbinnie** [comment]
Thanks for the additional info @dyve, unfortunately I'm still unable to reproduce this myself. I'm wondering if you have access to another machine to see if you see similar behaviour?

Otherwise I'm happy to open this up to the community to try and reproduce and see if there's a bug anywhere.

**Comment by dyve** [comment]
Thanks @devinbinnie for the excellent follow-up.

Since the workaround/solution I mentioned, he behavior has been solid. So deleting the server and adding it again did not help. Reinstalling the app did not help. But applying _Mark as unread_ / _Mask as read_ did help.

I think we can safely assume this was a local issue somewhere between my computer and the Mattermost server in question and close this.

**Comment by Hacker1337** [comment]
I encountered the same issue. And I think the whole problem with this "bug", and similar issues like #2108 is a bit unintuitive behaviour of this unread messages dot. 
After you read all direct messages, the  counter goes to zero, but the dot keeps being red. Because there are unread messages in the channels. And in the app interface chats with unread messages are barely distinguishable compared to chats without. So it took me a bit of time to link these channels, and this red annoying dot without counter. 
 
On the screenshot from [dyve](https://github.com/dyve) you can see that he also has unread message from channel. 
> ![Scherm­afbeelding 2023-05-19 om 08 52 44](https://github.com/mattermost/desktop/assets/82315/d0fc0bfd-6e35-4405-bcfa-da81840bc533)

Hope it will help someone.
