### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by chiefplato** [mattermost/desktop#2742]
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.3.1

### Operating System

Windows 10 x64  OpenSuse Leap 15.4 

### Mattermost Server Version

7.10.2

### Steps to reproduce

Just try to add a server on an alternative port 

Example: https://mattermost.mydomain.com:448

It does not retain the port number and sends you to port 443.

### Expected behavior

I expect to be able to add a server on a port other than 443

### Observed behavior

Just try to add a server on an alternative port

Example: https://mattermost.mydomain.com:448/

It does not retain the port number and sends you to port 443.

### Log Output

```shell
No logs
```

**Comment by devinbinnie** [comment]
@chiefplato Can you try the latest RC? This one should fix that issue for you: https://github.com/mattermost/desktop/releases/tag/v5.4.0-rc.1

**Comment by chiefplato** [comment]
Windows 10 client is working just fine now.

Issue persists with the Linux AppImage

**Comment by devinbinnie** [comment]
> Windows 10 client is working just fine now.
> 
> Issue persists with the Linux AppImage

Can you send a screenshot of the Add Server screen while trying to add the server in question?
There should be a little message that pops up before you click 'Save' or 'Connect'.

**Comment by chiefplato** [comment]
Sure, will do first thing when I get home from work.
________________________________

**Comment by devinbinnie** [comment]
This is likely resolved in v5.4. Closing for now.

**Comment by chiefplato** [comment]
Ty Sir, I will report my findings back from the AppImage and windows installer.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
