### ISSUE TITLE
[Bug]: Typo in Server URL can't be corrected (Cache issue?)

### ISSUE THREAD

**Issue by stephanmg** [mattermost/desktop#2744]
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.3.1

### Operating System

macOS Ventura 13.2 Apple Silicon

### Mattermost Server Version

v7.10.2

### Steps to reproduce

Type in wrong URL in Add Server.

Try to correct the wrong URL since server can't be reached with typo in URL.

Can't be corrected, config.json also gets regenerated with wrong URL (with typo) from some cache I presume.

### Expected behavior

URL should be able to be changed and change should persist.

### Observed behavior

URL will get changed back to URL with a typo from some cache.

### Log Output

```shell
-
```

**Comment by stephanmg** [comment]
Additionally I cleared out  `~/Library/Application Support/Mattermost/Cache` but without success.

**Comment by devinbinnie** [comment]
@stephanmg We've changed the way this behaves in v5.4.0-rc1, can you try that version: https://github.com/mattermost/desktop/releases/tag/v5.4.0-rc.1

**Comment by stephanmg** [comment]
Okay, this version works @devinbinnie - however I have white bars now in the user interface.

**Comment by stephanmg** [comment]
<img width="1715" alt="Screenshot 2023-06-01 at 09 11 52" src="https://github.com/mattermost/desktop/assets/1750463/290b8aa2-f4f9-41fa-9cd4-847050c5db59">

**Comment by devinbinnie** [comment]
@stephanmg Do you have a redirect on your server somewhere? It's likely that whatever URL you're configuring isn't the one that the app is ending up on, hence the white bar.

You can see what the current URL is if you go to View > Developer Tools for Current Server

**Comment by stephanmg** [comment]
No redirect, deleting the server and adding fixed it.

**Comment by devinbinnie** [comment]
> No redirect. However deleting the server (in the Mattermost Desktop app) and re-adding the server fixed it. Bar is now grey-ish as supposed to. Not sure if I can help here out with more details.

It's likely the server was slightly misconfigured. Sounds like it's working now though :)
Closing as completed.
