### ISSUE TITLE
[Bug]: not able to download file on MacOs - add folder access request

### ISSUE THREAD

**Issue by jmoeyersons** [mattermost/desktop#2747]
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.3.1

### Operating System

macOS Ventura 13.3.1 Apple Silicon

### Steps to reproduce

When downloading a file, it says "cancelled"

### Expected behavior

File must be downloaded to the Downloads folder

### Observed behavior

File cannot be download (I have to copy the public link and download it through my browser).
It says cancelled and when I click on it, I receive the following Mac notification: The application “Mattermost” does not have permission to open “Downloads”.

### Log Output

```shell
No usable log output in the logs
```

**Comment by devinbinnie** [comment]
This has been fixed here: https://github.com/mattermost/desktop/pull/2699

It will be released in v5.4. You can preview the release here: https://github.com/mattermost/desktop/releases/tag/v5.4.0-rc.1
