### ISSUE TITLE
Show URL when hovering over links

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#276]
#### Summary

Show URL when hovering over links, similar to the web app.
#### Details

At the moment you have to copy the link and paste it somewhere in order to see what the link is.

Until #123 has been addressed, in some platforms copying doesn't work (PR submitted in #272). Hence, you must click on the URL to find out what it's linking to, which is a bad user experience.

Given it has been brought up from a few sources, creating an issue here to track.

**Comment by jasonblais** [comment]
Anyone from the community interested to work on this?

**Comment by jasonblais** [comment]
@Razzeee referred to [`update-target-url` event](http://electron.atom.io/docs/all/#event-update-target-url) that might be useful to show URLs when hovering over links.

**Comment by rico042002** [comment]
I'm willing to try this one, still have not got my first PR in.

**Comment by jasonblais** [comment]
That would be awesome! All yours @rico042002!

**Comment by rico042002** [comment]
@jasonblais don't mean to be a bother. But what branch is the issue on? I'm having a hard time locating it, I already forked it and I have been searching through the src/browser branch. I'm still new to this.

**Comment by jasonblais** [comment]
@yuya-oc would you be able to help?

Thank you for working on the improvement, highly appreciate it @rico042002!

**Comment by yuya-oc** [comment]
@rico042002  `src/browser/index.jsx` is the entry point of UI, so you will add the new element/component into `MainPage` component in order to show a URL. As it's large and has complicated callbacks, it might be hard. First, how about you subscribe the [`update-target-url` event](http://electron.atom.io/docs/api/web-contents/#event-update-target-url) or add the placeholder to show a URL?

**Comment by jasonblais** [comment]
Hey @rico042002, were you able to locate the issue? Any help or guidance we can provide?

**Comment by rico042002** [comment]
Setting up my environment to modify the app. Never dealt with C++ before, plus I have to install python. It's a little much for a newbie like me but I have a friend helping me so I will still be taking care of the issue @jasonblais

**Comment by jasonblais** [comment]
Thanks @rico042002, much appreciated! Please let us know if there's anything we can help with.

You're also welcome to join the [Mattermost Deskop community channel](https://pre-release.mattermost.com/core/channels/desktop-app), if you're not already a member. A good place to ask questions and discuss the future of the desktop project.

**Comment by yuya-oc** [comment]
@rico042002 Are there any updates? I would like to take this because the next release is upcoming.

**Comment by jasonblais** [comment]
Closed by #372

**Comment by jasonblais** [comment]
Thanks @rico042002 for your interest earlier. If you'd be interested in helping with another pull request, we'd be more than happy to help you out

**Comment by Scotchester** [comment]
Hey, thanks all for adding this feature. I was sorely missing it when seeing Markdown links in chat.

I do have one minor frustration with it that I wonder if can be fixed. When the URL indicator is visible, it covers up the typing status indicator under the input field.

For the case of hovering over a URL in the message area, I don't think this is a huge deal. What makes it frustrating is when hovering over the sidebar, where nearly every pixel is a link. If I change channels and leave my mouse in place while reading what I've missed in that channel, the URL indicator just stays there, preventing me from seeing if anyone is typing.

Would it be possible (and if possible, desirable) to _not_ show the URL indicator for things in the sidebar? It seems of low value to me to reveal the internal channel/user URLs, which are safe and predictable, compared to whatever URL someone might put in a Markdown link.

**Comment by jasonblais** [comment]
Thanks @Scotchester for the feedback! We've got a related issue here: https://github.com/mattermost/desktop/issues/427

At the moment, the app can identify the URL string only, so the only way is pattern matching to not show internal URLs. The issue is with embedded links where you'd want to show the URL on hover, ex.

```
[here's the team invite link](link to team)
```

**Comment by Scotchester** [comment]
D'oh! Sorry I didn't catch that.

**Comment by jasonblais** [comment]
Not to worry! :)
