### ISSUE TITLE
[Bug]: Access denied attempting to download Mattermost 5.4.0 Windows setup exe

### ISSUE THREAD

**Issue by kelderek** [mattermost/desktop#2760]
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.4.0

### Operating System

Windows 10 x64

### Mattermost Server Version

N/A

### Steps to reproduce

Click the link on the release page for 5.4.0 to download the windows setup exe:
https://releases.mattermost.com/desktop/5.4.0/mattermost-desktop-setup-5.4.0-win.exe

### Expected behavior

Download starts

### Observed behavior

Access Denied error

### Log Output

```shell
N/A
```

**Comment by devinbinnie** [comment]
Thanks for letting us know @kelderek, we had an issue on CI that caused the Windows builds not to build correctly, they should be up within an hour :)
