### ISSUE TITLE
[Bug]: Version 5.4.0 missing in Debian Repository

### ISSUE THREAD

**Issue by AlexanderS** [mattermost/desktop#2767]
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.3.1

### Operating System

Debian GNU/Linux 11 (amd64)

### Steps to reproduce

The client told me, that 5.4.0 is available, but the version is apparently missing in the repo available under https://deb.packages.mattermost.com/.

### Expected behavior

Version 5.4.0 should be available in the repo.

### Observed behavior

Only the following versions are available: 5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.0.4, 5.1.0, 5.1.1, 5.2.0, 5.2.1, 5.2.2 and 5.3.1.

### Log Output

```shell
# apt-get install mattermost-desktop
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
mattermost-desktop is already the newest version (5.3.1-496).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by devinbinnie** [comment]
Looks like our build didn't finish properly for the DEB repo. I've rerun the pipeline and it should be here now:
```
devinbinnie@devinbinnie-Standard-PC-Q35-ICH9-2009:~$ sudo apt install mattermost-desktop/stable
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Selected version '5.4.0-570' (Mattermost Releases:stable [amd64]) for 'mattermost-desktop'
```

Thanks for letting us know :)
