### ISSUE TITLE
Context menu can't paste a URL which is copied from a link

### ISSUE THREAD

**Issue by yuya-oc** [mattermost/desktop#279]
#### Summary

Reported in #272. Context menu can't paste a URL which is copied from a link on Windows.

#### Steps to reproduce

- Operating System: Windows 10
- Mattermost Desktop App version: v1.4 (#272 artifact)
- Mattermost Server version: N/A
- Steps to reproduce the issue:

1. Post a message `[Link to Docs](docs.mattermost.com)` (any url)
2. Highlight the message and right-click
3. Select `Copy Link`
4. Attempt to paste in a message box, but can't select `Paste`.

#### Expected behavior

Select `paste` can be selected and the URL is pasted.

#### Observed behavior

See [@jasonblais's comment in #272](https://github.com/mattermost/desktop/pull/272#issuecomment-244635083) and further comments.

On OS X and Linux, this doesn't happen.

#### Possible fixes

sindresorhus/electron-context-menu#18 or fixes on Electron.

**Comment by jasonblais** [comment]
Fixed by #306 :tada:

Big thanks to @Razzeee, and again to @jnugh who originally added the [`electron-context-menu`](https://github.com/mattermost/desktop/pull/272) for v3.4
