### ISSUE TITLE
Application doesn't show up properly in the volume mixer in Windows

### ISSUE THREAD

**Issue by Jarvil** [mattermost/desktop#28]
Hello,

There seem to be a bug in Electron-mattermost 64bit v1.0.2 it doesn't show up properly in the Windows volume mixer in Windows 10.

![volumemixer](https://cloud.githubusercontent.com/assets/15193418/12776061/89fb25c0-ca5b-11e5-8ed6-0cd1eb4c5e24.png)

**Comment by alerque** [comment]
Duplicate of  #29.

**Comment by yuya-oc** [comment]
Reproduced on notification sound.

I also tested [simplest app](https://gist.github.com/yuya-oc/fc43ebebf6292128fe2f). However it's shown in the volume mixer.

![simplest app](https://cloud.githubusercontent.com/assets/1412057/12787067/2c64636e-cad7-11e5-9a4a-7f3b1916392a.png)
.

**Comment by Jarvil** [comment]
Hello,

This isn't a duplicate since windows 7 and windows 10 are different OS's.

**Comment by amyblais** [comment]
Ticket for tracking: https://mattermost.atlassian.net/browse/MM-14129

**Comment by esethna** [comment]
In Windows 10 the app uses the system sound for notifications so it's controlled by the system sounds in the volume mixer.

If other sounds are played through the app (ie a youtube video) then it appears in the mixer as expected. Closing this.
