### ISSUE TITLE
Bug Hunt Competition (Desktop App v3.4)

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#280]
It's time for a new **Bug Hunt Competition** for 3.4! 

Top 5 point scorers will win a special prize and named as the Mattermost Desktop Quality Champion of v.1.4/3.4. Anyone who scores at least one point will be recognized on the Mattermost page.

Here are steps to participate in the competition:
 1. Download release candidate (link to be added).
 2. Find an issue with the product which is not a feature idea, and not already reported by someone else in this thread or in [GitHub issues](https://github.com/mattermost/desktop/issues).
 3. Reply to this thread with an issue you have found, containing
  - the operating system 
  - Mattermost server version and database (from three-dot Main Menu > About Mattermost)
  -  clear repro steps

The point system that will be used: 
   - 1 point: Issue filed satisfies all three steps above
   - 2 bonus points: Issue reproduces on Windows
   - 3 bonus points: Issue is deemed critical and fixed for v3.4
   - 4 bonus points: The issuer submits a pull request, which is merged to the [desktop](https://github.com/mattermost/desktop/) repo

**The competition will run from Wednesday September 14th until Monday September 19th 17:00 GMT**

_____________________________________________________________________________

Big thanks to everyone who helped [resolve issue and submit pull requests for Desktop App v3.4](https://github.com/mattermost/desktop/milestone/3?closed=1)! We're really excited to ship our best release to date!

You are welcome to join our [Desktop App](https://pre-release.mattermost.com/core/channels/desktop-app) discussion channel to meet the Desktop App community and use the Mattermost server for testing.

**Comment by jasonblais** [comment]
The competiton has now begun! You can [download the release candidate for Desktop App v3.4 here](https://github.com/mattermost/desktop/issues/285).

Top 5 point scorers will receive a personalized Mattermost Quality Champion award tile with your name and everyone who scores at least one point will be recognized on the Mattermost page.

Good luck everyone!

**Comment by LordMike** [comment]
**Details**
OS: Windows 10 TH2, x64
Desktop app: 1.4.0
MM Server: 3.3.0 (not 3.4.0, so I assume it's fixed in 3.4.0)

**Reproduction**
As the API doesn't exist in 3.3.0 and isn't documented, so any setup should observe this.

**Issue**
A text appears with `We received an unexpected status code from the server. (404)`

This seems to be due to using an undocumented api, at `/api/v3/users/status`, as seen in Fiddler. The request is made every 30 seconds.

UI:
![image](https://cloud.githubusercontent.com/assets/1027111/18580404/a90df490-7bfb-11e6-9e86-125facb943e2.png)

Fiddler:
![image](https://cloud.githubusercontent.com/assets/1027111/18580439/e13c32b4-7bfb-11e6-842b-02243a817a30.png)

**Comment by jasonblais** [comment]
Thanks @LordMike! 

This should indeed be fixed with Mattermost 3.4. A workaround is [reported here](https://forum.mattermost.org/t/404-error-messages-for-api-v3-users-status/2089) which should resolve the problem after clearing cache (from **View > Clear Cache and Reload**)

**Comment by LordMike** [comment]
It does. The issue is gone.

Another issue seems to have appeared though. Pressing [ENTER] on messages will not send them. [CTRL+ENTER] does not work either (regardless of the relevant setting). The issue sticks on both restarts of the application and clearcache/reload procedures.

**Comment by jasonblais** [comment]
Hmm, I assume it doesn't reproduce on the web app?

**Comment by raphaelcastaneda** [comment]
I'm still seeing this: https://github.com/mattermost/desktop/issues/209 in v1.4.0  on OSX 10.11. 1 despite the workaround being merged.

**Comment by jasonblais** [comment]
Thanks @raphaelcastaneda for the report! It turned out to be [an issue on the server side](https://mattermost.atlassian.net/browse/PLT-3805), should be fixed Mattermost v3.4 released today

**Comment by jasonblais** [comment]
@raphaelcastaneda Neglected to mention -- if you experience the issue with Mattermost server v3.4, please do let us know and we'll investigate it further

**Comment by LordMike** [comment]
@jasonblais no. It does not. On the Web app I can send messages using the selected option anytime. It only affects the desktop app.

**Comment by Razzeee** [comment]
I had that at one point and blamed the pre-release server for it. Was gone the next day.

**Comment by LordMike** [comment]
@jasonblais it does not reproduce in the Pre-release MM. I'll wait for our admin to update our installation.

**Comment by LordMike** [comment]
@jasonblais following advice from my sysadmin, I cleared the Appdata-roaming for Mattermost (renamed it), and then reconfigured the app from scratch. This seems to have done it. I can now send messages by pressing ENTER.

**Comment by LordMike** [comment]
@jasonblais issue persists on a `1.3.0` client a colleague is running.

**Comment by jasonblais** [comment]
Thanks @LordMike. I'm not sure what might have happened there, any thoughts @yuya-oc or @Razzeee?

**Comment by jasonblais** [comment]
On another note, the bug hunt competition has ended. Thanks to those who participated! 

We'll keep the discussion open for a bit to see if the [ENTER] behaviour experienced above is an issue with the desktop app.

**Comment by jasonblais** [comment]
@LordMike Let us know if you see the issue appearing again. To ensure cahce is cleared you can use the shortcut `CTRL + SHIFT + R`, or from **Window > Clear Cache and Reload**.

Closing the issue for now as the competition has closed, but if you see it reappearing, you're welcome to open a separate issue for it, or reply in this thread.

**Comment by mrburrito** [comment]
I'm seeing this issue with v3.4.0 on both the server and OS X client. Updated both of them yesterday (Oct 25, 2016) and the issue keeps coming back. If I can find a pattern in the time after refresh, I'll post it.
