### ISSUE TITLE
[Bug]: Error when user type server address

### ISSUE THREAD

**Issue by wispoz** [mattermost/desktop#2809]
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.4.0

### Operating System

Windows 10 x64

### Mattermost Server Version

7.8

### Steps to reproduce

On Login page when users type server address , adrdes will be broken

### Expected behavior

server addres url must be correct

### Observed behavior

video here : 
https://veed.io/view/c1fab445-de6e-41fd-8775-58cc93bbfdba

### Log Output

```shell
none
```

**Comment by devinbinnie** [comment]
Created a JIRA ticket: https://mattermost.atlassian.net/browse/MM-54276
