### ISSUE TITLE
[Feature Request]: Follow Skype for Business status while presenting or being in a call

### ISSUE THREAD

**Issue by iva-5-middleware** [mattermost/desktop#2815]
### Before you file a crash report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.4.0

### Operating System

Windows 10 x64

### Mattermost Server Version

8.1.0 ESR

### What type of crash did you experience?

White screen (I can see the top bar, but I cannot see my Mattermost server)

### Crash report details

```shell
This ain't a crash report, sorry for misusing this category.

I'd like to propose the following features:
- when I'm in a call on Skype for Business, it would be nice, if there was a status change in Mattermost to something like "in a call"
- this status may also apply to Mattermost calls, so that other users can see if I'm already in a call or am free to call
- when I'm presenting in Skype for Business, it would be nice, if there was a status change in Mattermost to "Do not disturb" or at least the notification messages should be silenced and turned off for the duration of the presentation
```

**Comment by devinbinnie** [comment]
As stated in the Bug issue template:
You can request features and make product suggestions here: https://mattermost.com/suggestions/

Closing.
