### ISSUE TITLE
[Bug]: gconf-2 and gconf-service aren´t anymore availables on debian trixie or ubuntu mantic 23.10

### ISSUE THREAD

**Issue by damienlibouton** [mattermost/desktop#2853]
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.5.0-646

### Operating System

Debian Trixie x64 or Ubuntu 23.10 Mantic x64

### Steps to reproduce

Use Debian Trixie or Ubuntu 23.10

Add the gpg key and list file in the /etc/apt/sources.list.d folder following the instruction here : https://docs.mattermost.com/collaborate/install-desktop-app.html [section Ubuntu/Debian]

Then execute `apt update && apt install mattermost-desktop`

### Expected behavior

Mattermost desktop should be installable on the next release of Ubuntu 23.10 and Debian testing

### Observed behavior

We have this output : 
```bash
Hit:6 https://deb.packages.mattermost.com stable InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mattermost-desktop : Depends: gconf2 but it is not installable
                      Depends: gconf-service but it is not installable
E: Unable to correct problems, you have held broken packages.
```

### Log Output

```shell
No logs
```

**Comment by devinbinnie** [comment]
@damienlibouton Looks like these packages are no longer required by Electron, so I think we're safe to remove them. I will do so. Thanks for the heads up :)
