### ISSUE TITLE
Windows 10: Confusing text appears at the bottom of desktop notifications

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#287]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [X] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [X] This is a product defect issue that can be reproduced using the steps listed below.
- [X] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

Windows 10: Confusing text appears at the bottom of desktop notifications

#### Steps to reproduce

- Operating System: Windows
- Mattermost Desktop App version: v3.4 (RC1)
- Mattermost Server version: v3.4
- Steps to reproduce: Have another user send a direct message to you and observe the desktop notification.

#### Expected behavior

No text at bottom of notifications.

#### Observed behavior

![image](https://cloud.githubusercontent.com/assets/13119842/18552519/bb25d6d8-7b2a-11e6-93fd-be95e5ae0adb.png)

#### Possible fixes

N/A

**Comment by jasonblais** [comment]
Might reproduce on other platforms too.

We should consider fixing this for 1.4

**Comment by yuya-oc** [comment]
This reproduces on Windows only. The reason is that the application is not using ApplicationUserModelID which is used in the start menu shortcut. It's `com.squirrel.mattermost.Mattermost`.

**Comment by yuya-oc** [comment]
In the setup process of `mattermost-setup-*.exe`, it should create the shortcut which has ApplicationUserModelID. But it seems the ID is not attached to the shortcut. So the application name is not applied there.

**Comment by jasonblais** [comment]
I see, thanks @yuya-oc. Would that be feasible to fix for 3.4?

**Comment by jasonblais** [comment]
Fixed by #290
