### ISSUE TITLE
[Bug]: README for linux is outdated OR Desktop launcher isn't created

### ISSUE THREAD

**Issue by BaumiCoder** [mattermost/desktop#2874]
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

Version 5.5.1 commit: db8645b

### Operating System

Linux Mint 21.2 Victoria 64-bit (MATE Version)

### Mattermost Server Version

8.0.1

#### README for linux is outdated
1. Install as deb package (Instruction [here](https://docs.mattermost.com/collaborate/install-desktop-app.html) in the tab "Ubuntu/Debian")
2. Take a look in the installation directory `/opt/Mattermost`
3. "finding" a README file :wink: 
4. Read the README file
#### OR Desktop launcher isn't created
1. Install as deb package (Instruction [here](https://docs.mattermost.com/collaborate/install-desktop-app.html) in the tab "Ubuntu/Debian")
2. You can not find Mattermost the "all applications" section of your main menu.

#### README for linux is outdated
I find correct and useful informations. 
Because "normal" users maybe didn't find there way to the  install directory, the informations maybe useful, but not elementarily important to use the application.
####  OR Desktop launcher isn't created
I can start Mattermost without manuell configuration and without the shell.

### Observed behavior

First sentence of the README:
> If you installed the application via a package manager, it’s ready to use in your system. Please follow the User Guide for further information. 

I am not sure if manually adding the repo server for mattermost is a Installation "via package manager". Maybe that only relates to package shipped in a main repository of a distribution?

#### README for linux is outdated

If the **Install** section is applicable for my kind of situation, this are the bugs in the README:

1. The install directory is always mention as `/opt/mattermost-desktop-<VERSION>/`, but there only exists a `/opt/Mattermost` directory.
2. In the section **Terminal command** there are two ways to include mattermost-desktop in to the PATH environment variable. One way is to make a link from `/usr/local/bin` to the installation, but such a link already exists after installation.
```bash
$ type mattermost-desktop 
mattermost-desktop ist gehasht (/usr/bin/mattermost-desktop)
$ ls -l /usr/bin/mattermost-desktop 
lrwxrwxrwx 1 root root 34 Okt  6 19:30 /usr/bin/mattermost-desktop -> /opt/Mattermost/mattermost-desktop
```
#### OR Desktop launcher isn't created
There is no `mattermost.desktop` on my system. The main menu does not contain any mattermost programm in the all applications section.

### Log Output

No Start of Mattermost necessary for this issue. So there is no log.

### Additional Information

I am not completely sure in which situation I am with my kind of installation. The wrong part can be crossed out, after that is cleared.

**Comment by devinbinnie** [comment]
@BaumiCoder Thanks for the feedback, would you be open to making the requested changes in the `README` file?

As for the `.desktop` file, are you installing via APT? I'm able to see it when I install via APT. Also tried `snap` and it worked correctly for me.

**Comment by BaumiCoder** [comment]
## README

I am no sure what would be correct in the README. In the situation of an installation with APT the Section Install is not applicable. In which situation this steps must be executed? If a download the tar archive, I can put it everywhere. So no directory mention in the README would be really "correct".

## `.desktop` file
Yes, I installing with apt:
```bash
curl -o- https://deb.packages.mattermost.com/setup-repo.sh | sudo bash
sudo apt install mattermost-desktop
sudo apt upgrade mattermost-desktop
```
### Way of research
I make a further research of the problem with testings.

It works on other distribution. I tried it with virtual machines on:
- Kubuntu 22.04.3 LTS
- Linux Mit 21.2 (Cinnamon Version)

In the directory `/usr/share/applications` is the `.desktop` file on the kubuntu machine. I looked there on my Linux Mint (MATE) machine and it is also there, but the applications is not listed in den main menu.

I also tried it with Linux Mint 21.1 Vera 64-bit (MATE Version) on a virtual machine. There it is listed correctly. I seems to be a problem on my machine. I hope I can find the reason, why this new `.desktop` file in  `/usr/share/applications` is not listed in the main menu on my machine ... :thinking:

### Solution

But then I checked the settings of my main menu. :bulb: I have hidden the section for uncategorized applications. 🤦‍♂️
Think I have hidden that long time ago. There are some "rubish" application in there, like opening the tray of the optical drive.

### Improvement

Would it be possible to put it in a suitable categorie? My suggestion would be "internet", where beside webbrowsers also Mailclients and other Chatclients can be found.

**Comment by devinbinnie** [comment]
Yes we could probably put it in another category, currently we have it listed under these:
`"category": "Network;InstantMessaging",`
I guess there's no hard and fast rule as to which category exist per distribution, so I guess adding for each wouldn't be the worst idea.

As for the README, if you can think of any improvements specifically please let us know, I'm happy to consider any changes :)

**Comment by BaumiCoder** [comment]
- In the `.desktop` file on my machine: 
```desktop
Categories=contrib/net
```
- In the [create_desktop_file.sh](https://github.com/mattermost/desktop/blob/master/src/assets/linux/create_desktop_file.sh) (also in this script in my Installation):
```desktop
Categories=Network;InstantMessaging;
```
Where is the place in code to change the Categories for the APT installation?

**Comment by devinbinnie** [comment]
> * In the `.desktop` file on my machine:
> 
> ```desktop
> Categories=contrib/net
> ```
> 
> * In the [create_desktop_file.sh](https://github.com/mattermost/desktop/blob/master/src/assets/linux/create_desktop_file.sh) (also in this script in my Installation):
> 
> ```desktop
> Categories=Network;InstantMessaging;
> ```
> 
> Where is the place in code to change the Categories for the APT installation?
> 
> (When I add the Network and InstantMessaging Categories, Mattermost is listed under "Internet" after logout and login.)

It's here in `electron-builder.json`: https://github.com/mattermost/desktop/blob/4fb7676d41da42b249a4a210ea0374cbcbf3ecfa/electron-builder.json#L58C1-L58C1

**Comment by BaumiCoder** [comment]
@devinbinnie I hope that I created the Pull Request correctly.

**Comment by devinbinnie** [comment]
@BaumiCoder Just need to sign the CLA and I can have a look :)
