### ISSUE TITLE
[Bug]: Permission for audio not allowed

### ISSUE THREAD

**Issue by BKapelari** [mattermost/desktop#2881]
### Before you file a bug report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.5.1

### Operating System

Multible macOS Versions (v13.5.1 and v14.0)

### Mattermost Server Version

9.0.1

### Steps to reproduce

We have on mutlible Macs the same problem with the new version of Mattermost Desctop on Mac. The Version 5.5.1 has an error with microphone and screen sharing. The permissions are given in the Mac system settings. It is, i have tested it a lot, only a problem with Mattermost Desktop 5.5.1 (universal, X64 and silicon). Version 5.5.0 works perfektly - So we use this now.

<img width="303" alt="Bildschirmfoto 2023-10-11 um 11 50 32" src="https://github.com/mattermost/desktop/assets/4718590/2b048a10-0d99-420e-848b-d768f60fc913">

### Expected behavior

sound should work

### Observed behavior

the permissions are given, but the programm reacts like it would not be

### Log Output

```shell
[2023-10-11 12:24:12.501] [error] Logger Log level set to: info
[2023-10-11 12:24:12.624] [warn]  [App.Initialize] Current working directory is /, changing into /Applications/Mattermost.app/Contents/MacOS
[2023-10-11 12:24:12.732] [info]  [App.Initialize] Autoupgrade disabled: false
[2023-10-11 12:24:12.820] [info]  [ServerDropdownView] init
[2023-10-11 12:24:12.842] [info]  [i18nManager] Set new language de
```

**Comment by devinbinnie** [comment]
@BKapelari We added a new permission dialog that should be popping up per server to allow access to the microphone. Does this not appear for you when you start a call?

**Comment by devinbinnie** [comment]
![Screenshot 2023-10-11 at 2 23 37 PM](https://github.com/mattermost/desktop/assets/52460000/77cff1e8-3cf8-4c88-a872-4856a4c207d5)

This is what the dialog should look like.

**Comment by BKapelari** [comment]
Yes I know this dialog. After allowing MM appears in System Settings - Privacy. But MM has still the same error.

**Comment by devinbinnie** [comment]
@BKapelari Just to clarify, there are 2 separate dialogs, the other one is provided by macOS and looks like this:
![Screenshot 2023-10-12 at 11 06 25 AM](https://github.com/mattermost/desktop/assets/52460000/9d12f42a-8370-433e-a2c8-6fe47ec1bab4)

Do you end up seeing both?

**Comment by BKapelari** [comment]
Yes, both are coming up and the permission is  added in the system setting. But MM behaves like there would be no permission.

**Comment by devinbinnie** [comment]
@BKapelari Thank you for clarifying. So it's likely that a permission isn't being granted somewhere. Can you turn on Debug logging and reproduce the problem and send the logs along? We might be able to see what's going on with more granular logs.

**Comment by BKapelari** [comment]
@devinbinnie here you can find the debug log and two screenshots. 
To create the problem, I updated to 5.5.1. because the problem only exists in this version. In productive operation, I am currently working on version 5.5.0. because I can still make calls normally there.

![Bildschirmfoto 2023-10-16 um 09 11 31](https://github.com/mattermost/desktop/assets/4718590/462ab3f4-ee0f-483a-87e8-555d6919919c)
![Bildschirmfoto 2023-10-16 um 09 11 45](https://github.com/mattermost/desktop/assets/4718590/d9beed35-42d8-4766-b78f-31274917f234)
[main.log](https://github.com/mattermost/desktop/files/12913238/main.log)

**Comment by devinbinnie** [comment]
@BKapelari Thanks for the logs. So I can see the permissions check we added in v5.5.1 here:
`[2023-10-16 09:10:41.625] [debug] [PermissionsManager] doPermissionRequest https://kapelari.com/ media`

There's a new config file that should be in `/Users/<yourusername>/Library/Containers/Mattermost/Data/Library/Application Support/Mattermost` called `permissions.json`. Can you send me the contents for that? Thanks!

**Comment by BKapelari** [comment]
@devinbinnie I can't find any folder in /Users/<yourusername>/Library/Containers named "Mattermost". There is a lot of stuff but no Mattermost. Should I create it manually?

**Comment by devinbinnie** [comment]
@BKapelari Did you download the app from the Mac App Store? If you did it might be `.../Library/Containers/Mattermost.Desktop`

If you got it from GitHub or our website, it will be `/Users/<yourusername>/Library/Application Support/Mattermost`

**Comment by BKapelari** [comment]
@devinbinnie initially I downloaded it from the Mac App Store. After I had this problem I downloaded multiple releases from GitHub for testing. Now I use an older release from GitHub. But we all had the App Store Version and the same problem after the 5.5.1 update.

Here are my contents /Users/<yourusername>/Library/Application Support/Mattermost/permissions.json

**Comment by devinbinnie** [comment]
@BKapelari Gotcha, thanks for the attachment, and that does seem to reveal the crux of the problem: it looks like you're either not being asked about the dialog [here](https://github.com/mattermost/desktop/issues/2881#issuecomment-1758257058) or it's not storing properly. This is what it should look like when the permission has been accepted:
```
{
  "https://community.mattermost.com": {
    "media": {    // this should exist when the microphone permission is granted
      "allowed": true
    },
    "notifications": {
      "allowed": true
    }
  },
  "http://localhost:8065": {
    "notifications": {
      "allowed": true
    }
  }
}

As a workaround, if you want to add the `media` bit to your file manually, that might fix the issue? But i'll have to investigate further as to what is happening.

As a sanity check first, can I get you to remove that file entirely, fully restart your computer and reproduce with a video for me? I just want to make sure we are missing the dialog, or if we're not then it's a data storage issue. Thanks for your cooperation :)

**Comment by BKapelari** [comment]
> As a workaround, if you want to add the `media` bit to your file manually, that might fix the issue? But i'll have to investigate further as to what is happening.

I did. Nothing changed.

> As a sanity check first, can I get you to remove that file entirely, fully restart your computer and reproduce with a video for me?

I did. Nothing changed.

What I also did: Uninstall MM completly (with all Appliclation Support files) via AppCleaner. Restart mac. Reinstall througt the AppStore. Nothing changed. Same issue. Now MM is not allowed in the System Settings, cause it only asked for notifications but not for the other stuff. Maybe it ist related to the self hosted server?

Thanks for your help @devinbinnie

**Comment by devinbinnie** [comment]
@BKapelari Can you still take a video for me so I can see that you see both dialogs? Just as a sanity check.

**Comment by BKapelari** [comment]
I don't see the dialogs. only the one for desktop notifications

**Comment by devinbinnie** [comment]
> I don't see the dialogs. only the one for desktop notifications
> 

@BKapelari Can you please post a video of what you're seeing? That would be very helpful to me. Thanks!

**Comment by BKapelari** [comment]
@devinbinnie yes of course! So here you can see a fresh installed Mattermost from Mac AppStore. After inputing the link of our instance and login. Our instance is on a supfolder of our domain.
https://github.com/mattermost/desktop/assets/4718590/d7b4f614-357f-4f9f-8bb8-ff3e6d4036c4

**Comment by devinbinnie** [comment]
@BKapelari Okay so definitely no dialogs at all, the only thing left is a potential conflict with the configured server. Can you post the contents of `/Users//Library/Application Support/Mattermost/config.json`?

**Comment by BKapelari** [comment]
Yes of course! 
```
{
  "version": 3,
  "teams": [
    {
      "name": "kapelari.studio Chat",
      "url": "https://kapelari.com/mattermost",
      "order": 0,
      "lastActiveTab": 0,
      "tabs": [
        {
          "name": "TAB_MESSAGING",
          "order": 0,
          "isOpen": true
        },
        {
          "name": "TAB_FOCALBOARD",
          "order": 1,
          "isOpen": true
        },
        {
          "name": "TAB_PLAYBOOKS",
          "order": 2,
          "isOpen": true
        }
      ]
    }
  ],
  "showTrayIcon": true,
  "trayIconTheme": "use_system",
  "minimizeToTray": true,
  "notifications": {
    "flashWindow": 2,
    "bounceIcon": true,
    "bounceIconType": "informational"
  },
  "showUnreadBadge": true,
  "useSpellChecker": true,
  "enableHardwareAcceleration": true,
  "autostart": true,
  "hideOnStart": false,
  "spellCheckerLocales": [],
  "darkMode": false,
  "lastActiveTeam": 0,
  "downloadLocation": "/Users/USERNAME/Downloads",
  "startInFullscreen": false,
  "logLevel": "info",
  "autoCheckForUpdates": true
}
```

**Comment by devinbinnie** [comment]
Ah-ha! The subpath is what's doing it...we are checking for the URL's origin but not the subpath so it's immediately assuming it's an outside URL.

This is a bug we can fix!
Created a ticket: https://mattermost.atlassian.net/browse/MM-55054

**Comment by kamlim1k** [comment]
I have the same issue - version 5.5.1 and any RC older from GitHub, microphone not working. Was trying to install from app store, homebrew, releases from GitHub, release 5.5.0 and below works, 5.5.1 and after not. Using Mac Studio M2 Max.

**Comment by kamlim1k** [comment]
ufff after some code review / debug - was able to figure out the issue. Our instance was installed using omnibus installer. Because it installed behind load balancer with ssl termination, we setup parameters for omnibus https = false to prevent generate ssl certificated and after things. That cause server url in configuration to be http:// instead of httpS://. Looks like latest version has some code in permissionManager: 
`
if (!((0, _url.isTrustedURL)(parsedURL, serverURL) || permission === 'media' && parsedURL.origin === serverURL.origin || isExternalFullscreen)) {
        return false;
      }
      `
which compares server url from application and parsed url when trying to connect on call and it false to continue to show popup asking for permissions and so on. After I correct manually server url in mmomni.mattermost.env file which omnibus generates I was able to connect without issue and use latest version on mac (and windows, the same issue was there).
Hope it will help someone.

**Comment by Bruce-N6BMW** [comment]
Also having this same issue with Ubuntu 22.04 v5.6.0 (and Windows 10 v5.3.1, too). Do not have Chrome or Chromium browsers installed. Also, when trying to make it full screen it goes to "about:blank".

**Ubuntu 22.04**
team-id=T0JSBPG85,
call-id=R06EHRA4GCR,
audio-input=PermissionDenied,
audio-output=Succeeded,
video-input=PermissionDenied,
audio-connectivity=AudioInputPermissionDenied,
video-connectivity=VideoInputPermissionDenied,
content-share-connectivity=PermissionDenied,
network-UDP-connectivity=Succeeded,
network-TCP-connectivity=Succeeded,
microphone=LifeCam Cinema Mono,
camera=Microsoft® LifeCam Cinema(TM) (045e:075d),
speaker=Renoir Radeon High Definition Audio Controller Digital Stereo (HDMI),

**Comment by idowork2x** [comment]
@devinbinnie we are having the same audio not allowed issue but on the Mattermost MacOS desktop app version 5.6.0. Any ideas?

**Comment by Bruce-N6BMW** [comment]
I really don't want to have to install the Slack client as it just datamines.
