### ISSUE TITLE
Desktop client (1.3.0, 1.4.0) does not receive other messages on server 3.3.0.

### ISSUE THREAD

**Issue by LordMike** [mattermost/desktop#289]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [X] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [X] This is a product defect issue that can be reproduced using the steps listed below.
- [X] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary
A "message sending" icon appears on new messages, but never dissappears like if the server never accepts them.

Possibly part of #280 

#### Steps to reproduce

Please include: 
- OS: Windows 10 x64 TH2
- Mattermost Desktop App: 1.3.0 (colleague) and 1.4.0 (mine)
- Mattermost Server version: 3.3.0
- Clear steps to reproduce the issue

1. Send a message
2. Observe the "sending" animation

![image](https://cloud.githubusercontent.com/assets/1027111/18581526/530aec00-7c01-11e6-8b64-b0f13ae80951.png)

#### Expected behavior
Messages should be sent immediately (visually), and arrive as others send theirs.

#### Observed behavior

In the desktop client. No new messages are received from the channel, and all outgoing messages are marked like below.
![image](https://cloud.githubusercontent.com/assets/1027111/18581624/b956b174-7c01-11e6-87df-d78d1fa78acf.png)

On the web, however, new messages are seen from the desktop client as they're sent, but messages from here are not arriving in the client. As noted before, restarting the client will show any messages up until that point (in correct order too).
![image](https://cloud.githubusercontent.com/assets/1027111/18581670/eab67844-7c01-11e6-9edb-d7f4170df33c.png)

#### Possible fixes
None.

**Comment by jasonblais** [comment]
Do the problems disappear if you try reloading and clearing cache (from **View > Clear Cache and Reload**)

**Comment by LordMike** [comment]
They disappear. Figures.
Isn't there a version in the links to resources (like a hash or a timestamp of last change)?

**Comment by yuya-oc** [comment]
If my understanding is correct, hash is used in js file name since the server v3.4.
