### ISSUE TITLE
[Bug]: "Add Server" dialogue cannot be used to add server

### ISSUE THREAD

**Issue by bsl** [mattermost/desktop#2891]
### Checks before filing an issue

- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

Version 5.5.1 (63830002741)

### Operating System

macOS Ventura 13.4 (22F66)

### Mattermost Server Version

9.1.0

### Steps to reproduce

Click the server selection dropdown. Click "Add a server". Type or paste a Mattermost URL that the app does not already know about.

### Expected behavior

I expect that the app will go verify that the URL is actually for a Mattermost server, leave the entered URL in the text field, allow setting the display name of the server, and allow me to click Add.

### Observed behavior

When the URL is entered, the app goes and checks that the URL is for a Mattermost server. Having verified that it is, it clears the URL text field. It's still possible to click Add, but no server is actually added.

### Log Output

```shell
[2023-10-21 13:41:03.422] [error] Logger Log level set to: info
[2023-10-21 13:41:03.537] [warn]  [App.Initialize] Current working directory is /Users/b/Library/Containers/Mattermost.Desktop/Data, changing into /Applications/Mattermost.app/Contents/MacOS
[2023-10-21 13:41:03.654] [info]  [App.Utils] MAS: No files to migrate, skipping
[2023-10-21 13:41:03.666] [info]  [App.Initialize] Autoupgrade disabled: false
[2023-10-21 13:41:03.712] [info]  [ServerDropdownView] init
[2023-10-21 13:41:03.725] [warn]  [i18nManager] Failed to set new language en-US
[2023-10-21 13:41:03.726] [warn]  [i18nManager] Failed to set new language TH
[2023-10-21 13:41:10.605] [info]  [ModalView] [newServer] preloading with /Applications/Mattermost.app/Contents/Resources/app.asar/desktopAPI.js
[2023-10-21 13:41:23.396] [error] [App] [ServerViewState] there was an error in the new server modal: Error: Invalid url for creating a server
```

**Comment by devinbinnie** [comment]
@bsl I can't reproduce this myself, can you take a video of what you're seeing? That would be very helpful, thanks :)

**Comment by bsl** [comment]
@devinbinnie https://www.youtube.com/watch?v=jdARq0LofQk

**Comment by devinbinnie** [comment]
@bsl Thank you for the video. Looks like your server doesn't have the SiteURL set to anything.
There is a bug though in the Desktop App, because we shouldn't be blanking out the URL if this is the case, so we'll fix that.

For now, the fix (and definitely recommended practice) is to set the SiteURL.

**Comment by devinbinnie** [comment]
Created ticket: https://mattermost.atlassian.net/browse/MM-55134

**Comment by bsl** [comment]
@devinbinnie That was it. Thank you.

**Comment by aagha** [comment]
I am still having this issue.
![image](https://github.com/mattermost/desktop/assets/5522103/6c911a45-77e4-4807-bc1a-6409c50bc0ea)
![image](https://github.com/mattermost/desktop/assets/5522103/40739825-40aa-4f6a-9e5e-519639129de1)
![image](https://github.com/mattermost/desktop/assets/5522103/125b3584-78b4-4afc-b34d-ebb23c8e5a0c)
![image](https://github.com/mattermost/desktop/assets/5522103/4dcd7297-d9ad-4f1b-8d22-05a30638d8ef)
![image](https://github.com/mattermost/desktop/assets/5522103/e85cf8f5-ea93-475d-8aee-ae72622518f5)

I'm on MM server version 9.4.1 and client 5.6.0
