### ISSUE TITLE
If auto-starting the desktop app is turned on, an old app will continue to auto-start unless the auto-start option is reset from the Settings page.

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#291]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [X] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [X] This is a product defect issue that can be reproduced using the steps listed below.
- [X] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

Registry key not updated if using auto-start and downloading a new version

#### Steps to reproduce

Operating System: Windows 10
MM Desktop App version: 3.4 RC1
MM Server version: 3.4

1. Download Desktop v1.3 from the [downloads page](https://about.mattermost.com/downloads/)
2. Go to the Settings page via **File > Settings**
3. Turn on **Start app on login.** and hit **Save**
4. Download the RC for v1.4/3.4: https://github.com/mattermost/desktop/issues/285
 - [64-bit installer here](https://releases.mattermost.com/desktop/3.4.0-rc1/mattermost-setup-3.4.0-rc1-win64.exe)
5. Verify download was successful by checking the version number from **Help > Version**
6. Exit the application from **File > Exit**
7. Restart your machine

#### Expected behavior

The latest downloaded version of Mattermost starts.

#### Observed behavior

Mattermost v1.3 auto-starts.

#### Possible fixes

Registry key doesn't update when you download the desktop app. Thus, the old version will start unless the **Start app on login.** setting is reset (which only happens if you first turn the option off, save, then turn the setting back on)

@Razzeee has started progress with an [initial artifact here](https://circleci.com/gh/Razzeee/desktop/18#artifacts).

**Comment by jasonblais** [comment]
The setting was new for v1.3, so releasing v1.4/3.4 will be the first time users will hit this issue, and they most likely will hit it.

This is a really important bug to fix before the release - could we get the community's help here to chime in?

**Comment by jasonblais** [comment]
@Razzeee @yuya-oc, any potential thoughts here?

**Comment by yuya-oc** [comment]
I feel [Razzeee's branch](https://github.com/Razzeee/desktop/commit/66757ca406e9b3796f7d4c0c95fb43fdaec4dea9) would potentially help this.

**Comment by Razzeee** [comment]
Well it should, but it doesn't. Might be a bug in winreg :/

**Comment by jasonblais** [comment]
@Razzeee Can you help take a look at some of the comments from @yuya-oc, looks like he added some notes? 

I'd be happy to test it out afterward

**Comment by Razzeee** [comment]
@jasonblais 
Already looked at them, this is the latest code iteration. https://github.com/Razzeee/desktop/commit/1092aa3f547efc85f882e7e1c79033b2dcc71662 and it doesn't work for me.

**Comment by yuya-oc** [comment]
@Razzeee I added a comment for the commit. It should work.

**Comment by jasonblais** [comment]
@Razzeee Did you have a chance to take a look at @yuya-oc's new comment?

**Comment by jasonblais** [comment]
@Razzeee @yuya-oc any updates? I see there are some notes in the [commit](https://github.com/Razzeee/desktop/commit/1092aa3f547efc85f882e7e1c79033b2dcc71662), not sure if those are covered.

Sorry to bump you guys here, but I think this is the last PR to consider for Desktop 3.4 release

**Comment by Razzeee** [comment]
PR incoming. Just took a second to test it.

**Comment by yuya-oc** [comment]
Closed by #296.
