### ISSUE TITLE
[Bug]: Alternative HTTPS Port does not stick on desktop app. Reverts to HTTPS 443

### ISSUE THREAD

**Issue by chiefplato** [mattermost/desktop#2916]
### Checks before filing an issue

- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.5.1

### Operating System

Windows 11

### Mattermost Server Version

9.2.2

### Steps to reproduce

Port forward a port to 443 of the Mattermost Server. Add the server in the desktop app, it will initially work but any refresh or closing and reopening of the program results in it reverting back to https://sub.domain.com instead of https://sub.domain.com:44X

### Expected behavior

It is expected to behave the same way as the mobile apps and web browserr which have always worked without issue.
As far as I know this has never worked on the dekstop app and app images.

### Observed behavior

Add the server in the desktop app, it will initially work but any refresh or closing and reopening of the program results in it reverting back to https://sub.domain.com instead of https://sub.domain.com:44X

### Log Output

```shell
No logging
```

**Comment by devinbinnie** [comment]
It's likely that `https://sub.domain.com` is your configured SiteURL correct? I believe if the system is able to hit your server via the SiteURL once it's gotten that, it will always use that URL to connect.

That's actually a feature, not a bug ;)
The Desktop App prefers to use the configured SiteURL because there are a lot of small things that depend on it, such as detecting whether a URL is outside the app or not.

Hope this helps.

**Comment by chiefplato** [comment]
My site is https://sub.domain.com:449

Kind of makes the dekstop app useless, but thanks for confirming, I'll just use the browser

**Comment by devinbinnie** [comment]
@chiefplato If you change your configured SiteURL to `https://sub.domain.com:449` the problem should go away.
