### ISSUE TITLE
[Bug]: Deeplinks do not work on linux or mac

### ISSUE THREAD

**Issue by DanielHeath** [mattermost/desktop#2929]
### Checks before filing an issue

- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.5.1

### Operating System

Ubuntu Linux 22.04 LTS x64

### Mattermost Server Version

9.1.2

### Steps to reproduce

Open a chat between two users, eg 

https://radiopaedia.org/chat/dev/messages/@frank

When prompted, ask to "open in the app" (this links to mattermost://radiopaedia.org/chat/dev/messages/@frank )

### Expected behavior

App gains focus and navigates to that chat

### Observed behavior

App gains focus and refreshes the display, but keeps focus on the channel you were already in.

### Log Output

```shell
Help -> Show logs does not open a dialog in the current snap store release.
```

### Additional Information

This issue is also reported by our users on OSX. I also can't get this to work by killing the desktop app and then launching it via `mattermost://` url (it launches, but not to the right room).

I've tried setting breakpoints in [triageArgs](https://github.com/mattermost/desktop/blob/master/src/main/ParseArgs.ts#L16C10-L16C20), but they aren't hit if you load the app while it's already running

**Comment by devinbinnie** [comment]
@DanielHeath This is working for me on macOS. For Linux users, depending on how the app was installed you might have to run `./scripts/create_desktop_file.sh`, which is available in the root of this repo.

If it still doesn't work, I'd recommend trying the latest nightly (available [here](https://community.mattermost.com/core/channels/desktop-builds)) and seeing if that helps.

**Comment by DanielHeath** [comment]
I assume you meant to refer to src/assets/linux/create_desktop_file.sh.

I've installed it [via Snap](https://snapcraft.io/mattermost-desktop), as recommended [by your website](https://docs.mattermost.com/collaborate/install-desktop-app.html). 

I've run `/snap/mattermost-desktop/742/opt/Mattermost/create_desktop_file.sh` - still no improvement.

Will try the debugger again, since attempting to follow the link _does_ cause it to reload the app, which indicates it's doing _something_.

**Comment by DanielHeath** [comment]
Ooh, one more interesting tidbit: If I open the desktop app to another team, opening the link _will_ change teams, but not open the linked direct message.

**Comment by DanielHeath** [comment]
Aha!

If the server URL lacks a trailing slash (eg "https://radiopaedia.org/chat" - note no trailing slash).

src/main/views/viewManager.ts:204 adds a _second_ slash, resulting in a path like `//chat/main/messages/@frank`.

If I remove the extra slash via the debugger, the deeplinking works.

Solution: `pathName` should only have the slash added if `urlWithSchema.replace(formattedServerURL, '')` does not start with a slash.

**Comment by DanielHeath** [comment]
This can be reproduced reliably at our test environment - try opening

`mattermost://env-develop.radiopaedia-dev.org/chat/asdf/messages/@rp-user-019689` (username `a`, password `a`) in the latest version.

**Comment by devinbinnie** [comment]
@DanielHeath I think I might have already fixed that actually. Have you tried the latest nightly build? There was some issues with subpath based servers.

**Comment by DanielHeath** [comment]
Where are nightly builds found? Do you mean the release candidate on the releases page of this repo?

**Comment by devinbinnie** [comment]
> Where are nightly builds found? Do you mean the release candidate on the releases page of this repo?

That would also work, but I also provided a link to the nightly builds in my first reply :)

**Comment by DanielHeath** [comment]
Ahh thanks. I've run the latest nightly, but I can still reproduce the bug using the link I posted earlier.

**Comment by devinbinnie** [comment]
@DanielHeath Is it still reproducing on both macOS and Linux for the nightly version?

**Comment by devinbinnie** [comment]
> This can be reproduced reliably at our test environment - try opening
> mattermost://env-develop.radiopaedia-dev.org/chat/asdf/messages/@rp-user-019689 (username a, password a) in the latest version.

@DanielHeath Just tested using the above site and credentials on macOS and I am able to successfully open the deep link, the app navigates to the correct channel as well.

Seems as though the server and the deep links are working correctly. I'm using the December 15th nightly build, if that makes a difference.

**Comment by DanielHeath** [comment]
Interesting. I'm still getting it on linux, but I'll ask the user who first reported it (on macos) to try the nightly build (unless you have a release planned soon).

**Comment by devinbinnie** [comment]
We did a release on the 15th of December, next one will be sometime in March most likely.
Linux is sometimes finicky depending on the distribution and how it is installed.

**Comment by DanielHeath** [comment]
Thanks. I've confirmed it's working on macos.

**Comment by DanielHeath** [comment]
I've installed via `snap install mattermost-desktop` on ubuntu.

**Comment by devinbinnie** [comment]
Closing this as stale.
FWIW, under the recommended APT repo installation described [here](https://docs.mattermost.com/collaborate/install-desktop-app.html#install-and-update-the-mattermost-desktop-app), I was able to get the app running and signed in under both Chrome and Firefox on Ubuntu 24.04.

I'm thinking that there's some work to be done on the side of the `snap` package (we don't directly maintain that). Happy to assist with that though if there's something I can do.
