### ISSUE TITLE
[Bug]:  ToS not a URL

### ISSUE THREAD

**Issue by DatadudeDev** [mattermost/desktop#2944]
### Checks before filing an issue

- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

Version 5.6.0 commit: aebafea

### Operating System

Windows 11 x64

### Steps to reproduce

Switch push notification provider to HPNS (requires accepting a ToS.). 

### Expected behavior

Read the ToS (lol), accept if you agree and hit "save"

### Observed behavior

No access to the ToS, not formatted as a URL

### Log Output

```shell
I understand and accept the Mattermost Hosted Push Notification Service <linkTerms>Terms of Service</linkTerms> and <linkPrivacy>Privacy Policy</linkPrivacy>.
```

**Comment by devinbinnie** [comment]
@DatadudeDev This looks like it might be a web app issue, can you provide a video of what you're seeing?
