### ISSUE TITLE
[Feature]: Add LanguageTool, spelling and grammar checker, support

### ISSUE THREAD

**Issue by emericv** [mattermost/desktop#2963]
### Checks before filing an issue

- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.6.0

### Operating System

Ubuntu Linux 22.04 LTS x64

### Steps to reproduce

Write a message into the text input with mistakes

### Expected behavior

A powerful spelling and grammar checker is performed on the text with language autodetection

### Observed behavior

Only spelling check is performed with poor results

### Log Output

```shell
Not applicable here…
```

### Additional Information

A Chrome extension is available (https://languagetool.org/fr/chrome) and can be integrated here.

**Comment by devinbinnie** [comment]
Thanks for the suggestion @emericv. As per the note when filing an issue:
`This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.`

Please feel free to send your feature request to the above link.
Closing this ticket.
