### ISSUE TITLE
Since I upgraded to 5.7.0 on my desktop, I only get a black screen

### ISSUE THREAD

**Issue by Taralian** [mattermost/desktop#2986]
### Before you file a crash report

- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.7.0

### Operating System

macOS Big Sur 11.7.10

### Mattermost Server Version

Mattermost Version: 9.0.0 Database Schema Version: 111 Database: mysql

### What type of crash did you experience?

White screen (I can see the top bar, but I cannot see my Mattermost server)

### Crash report details

```shell
How to reproduce, step-by-step:  Open the app on my desktop
Expected behavior (or what is wrong):  The screen is completely black
Desktop App version:  5.7.0.
Operating System:  Mac OS Big Sur 11.7.10
Mattermost Server version: Mattermost Version: 9.0.0 Database Schema Version: 111 Database: mysql

I went to [View] > [Developer Tools for Current Server] and the window that came up was also black, so I have no way to click on a Console tab or save any log.  See photos below for screenshots.
```

### Additional Information

<img width="1280" alt="Screen Shot 2024-03-19 at 2 13 51 PM" src="https://github.com/mattermost/desktop/assets/163999616/e690da98-48ef-4623-aced-c0da16ee48fa">
<img width="1280" alt="Screen Shot 2024-03-19 at 2 14 08 PM" src="https://github.com/mattermost/desktop/assets/163999616/b4a8cf8b-c43c-4dc6-ac79-fe2637e0bb8d">

**Comment by devinbinnie** [comment]
@Taralian Is there a reason you're still on Big Sur? It is no longer supported by Apple. I haven't seen any other reports of this, so it's possible the latest Electron broke this. Would upgrading your macOS be something you could try?

**Comment by Taralian** [comment]
Thanks, @devinbinnie.  I'm using an old MacBook from 2016 and I'm a bit concerned that upgrading to the next system would push it too hard.  I didn't know that Apple was no longer supporting Big Sur.  I'll check into this.

**Comment by koderis-volkovs** [comment]
Same here for MacOS Monterey Version 12.7.4. I'm using iMac (Retina 5K, 27-inch, Late 2015).
Desktop app version: Version 5.7.0 (81418775581)

**Comment by Taralian** [comment]
So @devinbinnie, if @koderis-volkovs is having the same issue, it seems it won't help for me to upgrade to Monterey.  Do you have any other advice for us?  Thanks!

**Comment by koderis-volkovs** [comment]
@devinbinnie Probably is right that Electron broke this. In crash logs saw many lines about Electron.
@Taralian I just removed Mattermost  that I downloaded from AppStore and downloaded Mattermost 5.6.0  from https://github.com/mattermost/desktop/releases/tag/v5.6.0 and at least - Mattermost works now.

**Comment by Taralian** [comment]
@koderis-volkovs Thank you so much, it worked! @devinbinnie, does this mean that we can't go beyond 5.6.0 Mattermost with the systems we're using?

**Comment by devinbinnie** [comment]
@Taralian I guess it would appear so. Though it's possible that this was unintentional and was fixed in a newer version of Electron. One thing I can do is upgrade the Electron version on the nightly build, if you would be willing to try that?

**Comment by yewkay** [comment]
My office is experiencing the same issue, we're on Windows 11.

**Comment by Taralian** [comment]
@devinbinnie At the moment on 5.6.0 I am having no issue, but if you think upgrading the Electron version on the nightly build might avoid future issues and help others, I'm willing to try.  Just let me know what you need :-)

**Comment by devinbinnie** [comment]
@Taralian The current nightly is running v29.0.0. Do you want to give that a try?
https://community.mattermost.com/core/pl/fg6xhhehqtd15grjtd64kt931r

**Comment by Taralian** [comment]
@devinbinnie I have no idea what you're talking about...and when I click that link, I just get sent to the login of my regular Ängsbacka Mattermost account.  What is a nightly and why is the version so much higher than 5.7?

**Comment by devinbinnie** [comment]
@Taralian The nightly build is our latest build from the current code branch, containing new but untested features. That link is for our community server which you would need an account one, but I can give you a direct link for Mac here: https://s3.amazonaws.com/releases.mattermost.com/desktop/5.8.0-nightly.20240322/mattermost-desktop-5.8.0-nightly.20240322-mac-universal.dmg

The version number I referred to above is the Electron version number, not our internal one.

**Comment by Taralian** [comment]
@devinbinnie In order to try this, will I have to delete the current version of Mattermost?

**Comment by devinbinnie** [comment]
@Taralian Nope, you can just drag the app from the DMG into your Downloads folder and run it from there

**Comment by yewkay** [comment]
I'll start another issue since mine is windows related and the solution here seems to be Mac focused. My office systems runs Windows and doesn't have electron installed. So I believe it should be a different issue altogether.

**Comment by devinbinnie** [comment]
Closing as this is likely resolved.
