### ISSUE TITLE
[Bug]: The title and taskbar doesn't match browser anymore

### ISSUE THREAD

**Issue by devnopt** [mattermost/desktop#2987]
### Checks before filing an issue

- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.7.0

### Operating System

Amazon Linux 2

### Mattermost Server Version

7.8.9

### Steps to reproduce

The application is running.

### Expected behavior

In the browser the title and taskbar will contain the channel/direct message and the number of unread messages. It should match that.

### Observed behavior

The application always displays "Mattermost Desktop App" in the title and taskbar.

### Log Output

```shell
N/A
```

### Additional Information

Before upgrading to 5.7.0, had 4.3.2 and it matched what the browser does in the title and taskbar.

**Comment by devinbinnie** [comment]
This has an open PR for it which it appears has since been abandoned: https://github.com/mattermost/desktop/pull/2719
We've thought a bit about how to best approach this but haven't had the time to look.

**Comment by devnopt** [comment]
Sorry, I was looking through issues with word taskbar.

Assuming this wasn't an intentional change, I would recommend updating the other ticket as Type/Bug since the Desktop app used to render the title properly (worked in 4.3.2).

**Comment by devinbinnie** [comment]
There's another issue that covers changes to the titlebar. This is something that probably needs to be discussed internally as to how we want to approach it, but we'll track with this ticket: https://github.com/mattermost/desktop/issues/1563
