### ISSUE TITLE
[Bug]: handleGetDesktopSources Blocked on wrong webContentsId

### ISSUE THREAD

**Issue by onlymaj** [mattermost/desktop#2996]
### Checks before filing an issue

- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.7.0

### Operating System

macOS Sonoma 14.2.1

### Steps to reproduce

Click on Share screen button on a call or press shortcut keys to start sharing the screen but it does not work 

### Expected behavior

Share screen window get opened  and be able to select the right place that you want to share

### Observed behavior

Nothing will happen when you click on the button and a log will appear

### Log Output

```shell
[CallsWidgetWindow] handleGetDesktopSources Blocked on wrong webContentsId
```

**Comment by devinbinnie** [comment]
@onlymaj I can't reproduce this myself. Do you have an older version of the Calls plugin installed? Or are you trying to start the Call from a popout window by chance?

cc @streamer45 @cpoile In case you have any insight

**Comment by onlymaj** [comment]
@devinbinnie I am using Mattermost server v7.4.0 and also call plugin 0.10.0. I have sound from both sides perfectly and also can share my screen when I open it using browser. 
My colleague can share screen to me and I have no problem with that, but on my end the screen share window does not appear.
I am using Mattermost Desktop version 5.7.0 (81418775581) .  I believe there is a problem with Desktop version which happens on new version of Macos and also on some windows 11 recent updates. The logs doesn't show anything special but I believe something can not get permission and it doesn't appear.

**Comment by streamer45** [comment]
@onlymaj You should really update Mattermost (and plugin), it's more than a year old and well out of support. Oldest supported Mattermost version is 8.1 (ESR).

**Comment by onlymaj** [comment]
@streamer45 I have updated the server version to the latest and call plugin to 0.24 , it seems working fine now.
