### ISSUE TITLE
Improve settings UI

### ISSUE THREAD

**Issue by yuya-oc** [mattermost/desktop#3]
- [ ] Sort teams
- [x] Edit team name and URL
- [x] Validate URL

**Comment by smackjack3** [comment]
Not sure if this is the right place to put this, but I didn't want to submit and issue because I don't think it's an actual issue - just an enhancement request. What would be nice is if we only have one team, don't show the team tabs along the top of the main app.  I'd much rather save the space at the top of the window since we only have one tab, but definitely see the benefits of them if there are actually multiple teams.

**Comment by smackjack3** [comment]
Wondering if it could be as simple as checking if this.props.teams[index]<1 and if true setting top:0 instead of 42px in src/browser/index.jsx?

**Comment by yuya-oc** [comment]
Thanks a lot. Feel free to submit request issues. I will assign right labels.

I had thought the tabs feature, but it was low priority in that time. I think the way you said is the most simple.

**Comment by yuya-oc** [comment]
1cc68197d2e1a922149a46211cbd1079bfe3556c implemented the idea to hide tabs.

**Comment by smackjack3** [comment]
Just installed 1.0.2 and the new tabs functionality is working great.  Thank you!!

**Comment by Razzeee** [comment]
> Edit team name and URL

should be resolved

**Comment by jasonblais** [comment]
Here is a proposed mock up for an updated settings page.

### P1:
 - Add `Settings` as a title for the Settings page

TEAMS:
 - Change `Teams` to `Team Management`
 - Move `Add new team` to top right of the Teams section
 - Change the pencil/cross icons to `Edit` and `Delete` for less ambiguity of their behaviour

OPTIONS:
 - Change `Options` to `App Options`
 - Condense app options into a single section. That is `Flash the taskbar icon when a new message is received.` would not be in a separate Notifications section

![image](https://cloud.githubusercontent.com/assets/13119842/18232990/8e68460a-72a9-11e6-867b-67ecbff534f7.png)

### P2:
 - Adding and editing a team opens a pop up, similar to when creating and renaming channels in Mattermost

![image](https://cloud.githubusercontent.com/assets/13119842/18233044/4de66722-72ab-11e6-9876-899ee07be9d6.png)

![image](https://cloud.githubusercontent.com/assets/13119842/18233050/6b566bea-72ab-11e6-97f1-f13725868f7e.png)

 - Removing a team opens a pop up to confirm the user wants to remove the team, similar to when deleting a channel in Mattermost

![image](https://cloud.githubusercontent.com/assets/13119842/18233067/ad2b3866-72ab-11e6-8f31-75617f4d9b64.png)

**Comment by jasonblais** [comment]
Propose we try to aim cover P1 items above or v1.4?

If we can also cover P2 items, that would be great. But I'm not sure how much additional work that would involve, so leaving that to a future version is okay too.

If there's a volunteer who would like to work on it, that would be awesome!

Also, as a note, if you get stuck with any CSS, let us know. We can get our UX designer help with CSS updates.

**Comment by jasonblais** [comment]
Closing as complete. 

We'll be opening a second issue, which will involve some further updates to the Settings page (e.g. the behaviour of adding and editing teams). A few details still need to be reviewed.

Big thank you to everyone who helped improve the page!
