### ISSUE TITLE
After right-clicking an image thumbnail, "Copy Link" option moves around when clicking different places afterwards

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#300]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [X] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [X] This is a product defect issue that can be reproduced using the steps listed below.
- [X] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

After right-clicking an image, "Copy Link" option moves around when clicking different places afterwards
#### Steps to reproduce

Please include: 
- Operating System: Mac and Windows
- Mattermost Desktop App version: v3.4-RC1
- Mattermost Server version: v3.4

1. Right-click on an image thumbnail
2. Right-click elsewhere on the page

#### Expected behavior

"Copy Link" menu comes up

#### Observed behavior

"Copy Link" menu comes up, and moves around when I click different places. 

Link to video: https://www.dropbox.com/s/w7uh3mr6fyrvcak/copylink.mov?dl=0

#### Possible fixes

?

**Comment by jasonblais** [comment]
Looking to see if others in the community are able to reproduce the behaviour, reported by at least two people

**Comment by Razzeee** [comment]
I'm pretty sure my dependency bump won't affect this error.

**Comment by jasonblais** [comment]
To add, this reproduces when right-clicking links on the center channel, and channel names on the left sidebar

**Comment by yuya-oc** [comment]
Not reproduced on my v3.4 app. In the step 2, right-clicking doesn't show anything or show correct context menu.

- Windows 10
- macOS 10.12

**Comment by jasonblais** [comment]
It was reproducing for me yesterday, but after quitting the app and re-opening it, the issue disappeared.

I didn't see any console errors while the issue was happening.

Would there be additional information that would be helpful?

**Comment by jasonblais** [comment]
Transferred details to #340, closing as duplicate
