### ISSUE TITLE
Add `CTRL+SHIFT+MINUS` as a shortcut for zooming out

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#301]
I confirm (by marking "x" in the [ ] below): 
- [X] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [X] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [X] This is a product defect issue that can be reproduced using the steps listed below.
- [X] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 
---
#### Summary

These are standard shorcuts that should work in any app. [Original issue posted here](https://github.com/mattermost/desktop/issues/232).

Zoom in:
- `CTRL+=` [implemented]
- `CTRL+SHIFT+=` [implemented]

Zoom out:
- `CTRL+MINUS` [implemented]
- `CTRL+SHIFT+MINUS`

^Mac-equivalent shortcuts replaces `CTRL` with `CMD`.

If someone is familiar uses `CTRL+SHIFT` on the browser, then the experience appears broken on the desktop app since `CTRL+SHIFT+MINUS` doesn't work.

**Comment by kytwb** [comment]
I'm taking this one. I will submit a PR within 24 hours.

**Comment by jasonblais** [comment]
Thanks @kytwb  for your interest! Highly appreciated!

**Comment by kytwb** [comment]
@jasonblais From what I read from other issues and guess from the implemented "Zoom In", the shortcut with SHIFT can't work with every keyboard layout, can it?

**Comment by magicmonty** [comment]
I'm not sure but I see no change here. CMD+PLUS and CMD+MINUS work, and CMD+SHIFT+MINUS too, but CMD+SHIFT+PLUS is currently not working on OSX

Also this worked as decribed above already the same way before.

So what exactly should be the expected behaviour here on OSX?

**Comment by yuya-oc** [comment]
Closed by #344
