### ISSUE TITLE
[Bug]: Missing notifications on Ubuntu 23

### ISSUE THREAD

**Issue by TenCoKaciStromy** [mattermost/desktop#3016]
### Checks before filing an issue

- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.7.0

### Operating System

Ubuntu Linux 23

### Mattermost Server Version

9.7.0

### Steps to reproduce

After install Mattermost from AppCenter, the Mattermost is not listed in system notification settings. Therefore (probably) is not Mattermost able to show notifications. No notifications are showing.

### Expected behavior

Mattermost would be able show notifications.

### Observed behavior

No notification are showing and I can't find any way, how to enable that.

### Log Output

```shell
[2024-04-24 09:30:26.953] [error] Logger Log level set to: info
[2024-04-24 09:30:27.060] [warn]  [App.Initialize] Current working directory is /home/tcks, changing into /snap/mattermost-desktop/752/opt/Mattermost
[2024-04-24 09:30:27.158] [info]  [App.Config] config.autostart has been configured: true
[2024-04-24 09:30:27.167] [info]  [App.Initialize] Autoupgrade disabled: false
[2024-04-24 09:30:27.192] [info]  [ServerDropdownView] init
[2024-04-24 09:30:27.197] [warn]  [i18nManager] Failed to set new language en-US
[2024-04-24 09:30:27.198] [warn]  [i18nManager] Failed to set new language US
[2024-04-24 09:30:27.231] [info]  [App.Config] config.autostart has been configured: true
[2024-04-24 09:30:27.627] [info]  [App.Config] config.autostart has been configured: true
```

**Comment by devinbinnie** [comment]
@TenCoKaciStromy Do you get the same result when installing with the DEB/AppImage, or from the APT repository? What about installing manually and using the `create_desktop_file.sh`? Do other apps behave similarly?

**Comment by TenCoKaciStromy** [comment]
I installed  [DEB package](https://releases.mattermost.com/desktop/5.7.0/mattermost-desktop_5.7.0-1_amd64.deb) and behaviour is same. Notifications are not shown.

My personal tip is - something changed in Ubuntu between 20 and 23 (I used 20 before), not in Mattermost. Other colleagues of mine are not affected by this behaviour.

**Comment by devinbinnie** [comment]
Tested for myself on Ubuntu 23.10.1 with the DEB build and was able to get notifications on v5.7. It's possible that you denied permission to them, you should have seen a screen that asks permission to send notifications. Otherwise it's possible something else is misconfigured.

**Comment by TenCoKaciStromy** [comment]
I made two fresh installs of Ubuntu 23 recently, but I was never asked to allow/forbid the notification permission.
I checked the notifications permission in system settings, it's allowed. Tried disable and enable it. But it doesn't help.

Is it possible, that the root cause is in server? We have on-prem server.

**Comment by devinbinnie** [comment]
It is possible that the server might have an effect on that, could be something to do with notification settings being turned off, or the websocket not connecting.

**Comment by reuschling** [comment]
I doesn't see mattermost inside the application list at all, and I assume that I mistakenly forbid notifications at the moment it was asked for. How can I change this setting? Notifications inside mattermost-desktop are allowed, I just can not see any.
