### ISSUE TITLE
[Bug]: Random Certificate Error

### ISSUE THREAD

**Issue by pmkap** [mattermost/desktop#3020]
### Checks before filing an issue

- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.7.0

### Operating System

Windows, Linux, MacOS

### Mattermost Server Version

9.7.2

### Steps to reproduce

Not really reproducible, happens randomly on Linux, Mac and Windows. Mattermost itself works perfectly, but the message showing up is irritating to users.

### Expected behavior

Nothing

### Observed behavior

Certificate error showing up randomly

### Log Output

```shell
mattermost-desktop[41788]: [41788:0429/091348.416219:ERROR:ssl_client_socket_impl.cc(975)] handshake failed; returned -1, SSL error code 1, net_error -200
```

### Additional Information

![image](https://github.com/mattermost/desktop/assets/48184470/9ec672b3-e967-4c2e-9c1e-767033daec3c)

**Comment by devinbinnie** [comment]
@pmkap Did someone post an image from an unsecure site onto the server? Usually this error will popup when the app is trying to load something from a server that is deems untrusted. If it's coming up when you load the server initially, then it's possible that the server itself has an expired certificate?

**Comment by pmkap** [comment]
@devinbinnie Thanks for the reply!
I am not aware of any images posted from an unsecure site. 

The error is showing up randomly, not when connecting to the server initially. Also we use let's encrypt certificates. The error however says "Sectigo RSA Organization Validation Secure Server CA"
Additional note: This happened with two different Mattermost servers.

**Comment by devinbinnie** [comment]
If you're able to turn on Debug logging in the Settings windows/modal there should be a line in there that shows the certificate check, so we should be able to see what URL it's coming from.

**Comment by devinbinnie** [comment]
@pmkap Is this still an issue?

**Comment by pmkap** [comment]
> @pmkap Is this still an issue?

@devinbinnie  Yes, but we're pretty sure it's a misconfiguration somewhere on our server. Therefore closing this issue.
