### ISSUE TITLE
[Bug]: Linux desktop client keeps creating autostart file for Electron

### ISSUE THREAD

**Issue by nicolamori** [mattermost/desktop#3029]
### Checks before filing an issue

- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.7.0

### Operating System

ArchLinux

### Mattermost Server Version

9.7.2

### Steps to reproduce

Install the `mattermost-desktop` package from ArchLinux official repositories, start the app, configure a server, close and restart.

### Expected behavior

No ` ~/.config/autostart/electron.desktop` file should be present.

### Observed behavior

A ` ~/.config/autostart/electron.desktop` has been created, autostarting an Electron instance at every login to the desktop environment (Plasma Wayland in my case).

### Log Output

```shell
[2024-05-08 09:59:16.566] [error] Logger Log level set to: info
[2024-05-08 09:59:16.681] [warn]  [App.Initialize] Current working directory is /home/mori, changing into /usr/lib/electron28
[2024-05-08 09:59:16.744] [info]  [App.Initialize] Autoupgrade disabled: false
[2024-05-08 09:59:16.784] [info]  [ServerDropdownView] init
[2024-05-08 09:59:16.792] [warn]  [i18nManager] Failed to set new language en-US
[2024-05-08 09:59:16.792] [warn]  [i18nManager] Failed to set new language IT
[2024-05-08 09:59:16.852] [info]  [App.Config] config.autostart has been configured: true
[2024-05-08 09:59:16.853] [info]  [App.Config] config.autostart has been configured: true
[2024-05-08 09:59:17.268] [info]  [App.Config] config.autostart has been configured: true
```

### Additional Information

The ` ~/.config/autostart/electron.desktop` file is created at every start of the Mattermost desktop client, so deleting it is not effective. Deleting it, touching it, and then making it non-writable with e.g. `sudo chattr +i ~/.config/autostart/electron.desktop` then the client crashes at startup with this message:
```
Application: Mattermost 5.7.0 [commit: 5.7.0
]
Platform: Linux 6.8.9-arch1-1 x64
Error: EPERM: operation not permitted, open '/home/mori/.config/autostart/electron.desktop'
```

**Comment by devinbinnie** [comment]
@nicolamori Can you post a screenshot of the "vanilla" Electron window you're seeing?

**Comment by nicolamori** [comment]
@devinbinnie Here it is:

![Screenshot_240508_174028](https://github.com/mattermost/desktop/assets/59166070/6263f753-d293-441c-9d10-13704bc03959)

And this is the `.desktop` file created at Mattermost start:
```
[Desktop Entry]
Type=Application
Version=1.0
Name=electron
Comment=electronstartup script
Exec=/usr/lib/electron28/electron
StartupNotify=false
Terminal=false
```

**Comment by devinbinnie** [comment]
@nicolamori Huh, that seems really odd. Have you ever spun up Electron for development purposes in the past? How did you install Mattermost? (AppImage, Snap, from our APT repo, using the `.tar.gz`)

**Comment by devinbinnie** [comment]
> @devinbinnie I've no development record with Electron. The only thing that comes to my mind related to development is that if I remember correctly in Archlinux [this bug](https://github.com/mattermost/desktop/issues/2942) was hit and now the `mattermost-desktop` executable is this shell script:
> 
> ```
> #!/bin/sh
> exec electron28 /usr/lib/mattermost-desktop/app.asar --disable-dev-mode "$@"
> ```

That's probably what's doing it. If I recall correctly the desktop file is created using the executable name, so if it's supposed to be just run vanilla Electron with the ASAR it's probably creating a file using that executable. I think if you modify the desktop file to use the extra arguments it should work fine.

**Comment by nicolamori** [comment]
That makes sense, if I correctly understood what's happening under the hood. Anyway it's a buggy behavior and requiring the user intervention for such a basic functionality doesn't feel right. I'll check with the ArchLinux packager if it's possible to fix this at distribution level.

**Comment by devinbinnie** [comment]
Thank you, unfortunately this is something that package is doing, which we don't currently maintain ourselves.

Closing this issue as-is for now.
