### ISSUE TITLE
Under Wayland, Mattermost should not draw extra window decorations if the compositor encourages client-side decorations

### ISSUE THREAD

**Issue by tmke8** [mattermost/desktop#3035]
### Checks before filing an issue

- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.7.0

### Operating System

Ubuntu Linux 23.10 x64

### Mattermost Server Version

9.7.3

### Steps to reproduce

Observe the title bar on Wayland:

![image](https://github.com/mattermost/desktop/assets/7741417/5c9c3f7e-0d86-4feb-98ad-993dc0d25270)

### Expected behavior

I think on Wayland, the ideal behavior is this (which I think is what Obsidian is doing, for example):

- if the compositor supports server-side decorations (i.e., supports the [xdg-decoration](https://wayland.app/protocols/xdg-decoration-unstable-v1) protocol), then the application should not draw decorations and leave this to the compositor
- if the compositor doesn't support the above protocol, the application should draw its own decorations in a way that integrates the decorations into the app itself; Mattermost desktop used to have this, but it was removed in version 4.6.0

### Observed behavior

Mattermost desktop draws extra borders on GNOME Wayland.

### Log Output

```shell
n/a
```

**Comment by devinbinnie** [comment]
Apologies for missing this issue. @tmke8 Have you tried v5.9? We have opted to use a native Electron button overlay that combines the top bars. Is that what you were hoping to see? If not, can you elaborate on what you meant by "extra borders"?

**Comment by tmke8** [comment]
>We have opted to use a native Electron button overlay that combines the top bars. Is that what you were hoping to see?

Yes! Thanks!
