### ISSUE TITLE
[Bug]: linux x64 (non-arm) AppImage is missing (mattermost-desktop-5.8.0-linux-x86_64.AppImage)

### ISSUE THREAD

**Issue by srconne** [mattermost/desktop#3036]
### Checks before filing an issue

- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.8.0

### Operating System

Linux x64 non-arm

### Steps to reproduce

Attempt to download mattermost-desktop-5.8.0-linux-x86_64.AppImage from the release page download link or attempt to use the download update from the 5.7.0 running mattermost appimage desktop client.

### Expected behavior

The image is available and can be downloaded

### Observed behavior

Access denied returned. Asset is also not listed in the assets from the github page even though the link to download it is.

### Log Output

```shell
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>RVSPTPXKMYQVWFD3</RequestId>
<HostId>GKk8BvPQOIM0qRZH0TuHbkHrv1TYLkTpJEAreD67Mvbc8fgQa+c5qxZWydq3b1XVh8ELFA3zazQEhtFZ4o0UuIVlk5r3He9Ueh8smqRrI4w=</HostId>
</Error>
```

**Comment by devinbinnie** [comment]
Yep, looks like the way our artifacts were built was changed somehow...
Ticket created: https://mattermost.atlassian.net/browse/MM-58286

**Comment by francislavoie** [comment]
Looks like the `.deb` is missing too

**Comment by jmairboeck** [comment]
RPM packages are missing too.

**Comment by devinbinnie** [comment]
v5.8 has been republished with the missing artifacts. Sorry for the inconvenience!
