### ISSUE TITLE
Desktop notification duration settings in Mattermost not honoured on the desktop app

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#304]
I confirm (by marking "x" in the [ ] below): 
- [X] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [X] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [X] This is a product defect issue that can be reproduced using the steps listed below.
- [X] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---
#### Summary

Desktop notification duration settings in Mattermost not honoured on the desktop app
#### Steps to reproduce

Please include: 
- Operating System: Windows and Mac
- Mattermost Desktop App version: v3.4-RC1
- Mattermost Server version: v3.4
1. Go to **Account Settings > Notifications > Desktop Notifications**
2. Set "Notification Duration" to 10 seconds, Save
3. Send a message that fires a desktop notification
#### Expected behavior

Desktop notification remains on screen for 10 seconds.
#### Observed behavior

Desktop notification remains on screen for 5 seconds regardless of the "Notification Duration" setting
#### Possible fixes

?

**Comment by Razzeee** [comment]
That's probably something you should post at https://github.com/sindresorhus/electron-context-menu ?

**Comment by jasonblais** [comment]
Were you referring to this issue? https://github.com/mattermost/desktop/issues/300

**Comment by Razzeee** [comment]
Yeah, sorry that was my intention. Not sure how I mixed them up.

**Comment by jasonblais** [comment]
Sounds good, I'll check the new PR you just submitted with updated `electron-context-menu` to see if it reproduces https://github.com/mattermost/desktop/pull/306

**Comment by yuya-oc** [comment]
Ah, I missed this point for Windows.

When `new Notification()` is called, Electron creates a Toast. Toast has a parameter to control duration, [`short` or `long`](https://msdn.microsoft.com/library/windows/apps/br230846.aspx). In my memory, Electron doesn't set this parameter, so `short` should be chosen (see [electron/brightray](https://github.com/electron/brightray/blob/master/browser/win/windows_toast_notification.cc)). As the result, there are two choices to fix the issue.

- Create a PR for electron/brightray. (It affects all electron apps)
- Create a native module to access to all Toast APIs. (Need Windows CI machine, e.g. AppVeyor)

FYI, if `long` was set, the maximum duration would be about 20 sec.

**Comment by yuya-oc** [comment]
I'm not familiar at notifications in macOS. But as far as I read [the document](https://developer.apple.com/reference/foundation/nsusernotification), I think there is no way to control the duration from application code. So users have to change the settings of "Notifications Center" from Preferences.app.

**Comment by jasonblais** [comment]
@yuya-oc: The notification duration is at most 5 seconds in Safari and Edge as well, and there is help text mentioning that.

Propose we do the same for the desktop apps, given I haven't heard any customer bringing this up and it would be a lot of work to fix for small benefit.

Here is the proposed PR for changing the help text server-side: https://github.com/mattermost/mattermost-webapp/pull/362
