### ISSUE TITLE
[Bug]: Some download links are down for v5.8.1

### ISSUE THREAD

**Issue by prasanthcakewalk** [mattermost/desktop#3069]
### Checks before filing an issue

- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.8.1

### Operating System

Windows 10 x64

### Steps to reproduce

N/A

### Expected behavior

N/A

### Observed behavior

N/A

### Log Output

```shell
N/A
```

### Additional Information

Hello!

This is not a bug per se, but the following links for the v5.8.1 windows zip files are down:
* https://releases.mattermost.com/desktop/5.8.1/mattermost-desktop-5.8.1-win32.zip
* https://releases.mattermost.com/desktop/5.8.1/mattermost-desktop-5.8.1-win64.zip
* https://releases.mattermost.com/desktop/5.8.1/mattermost-desktop-5.8.1-arm64.zip

This hinders installations and updates via, e.g., [scoop installer](https://github.com/ScoopInstaller/Scoop), which [currently uses these links as sources for Mattermost desktop](https://github.com/ScoopInstaller/Extras/blob/master/bucket/mattermost.json).

Thank you for your time!

----
Source for the download links: https://github.com/mattermost/desktop/releases/tag/v5.8.1

**Comment by aliesbelik** [comment]
Looks like correct links are
https://releases.mattermost.com/desktop/5.8.1/mattermost-desktop-5.8.1-win-x64.zip
https://releases.mattermost.com/desktop/5.8.1/mattermost-desktop-5.8.1-win-ia32.zip
https://releases.mattermost.com/desktop/5.8.1/mattermost-desktop-5.8.1-win-arm64.zip
as files from release assets named.

**Comment by devinbinnie** [comment]
Yes, these are the new links. I will update the GitHub release and make a fix for the script that generates that.
Thanks for pointing that out for us :)
