### ISSUE TITLE
Evaluate if greeenkeeper.io makes sense for this project

### ISSUE THREAD

**Issue by Razzeee** [mattermost/desktop#309]
It might be worth to check out https://greenkeeper.io/ and see if it could improve our workflow.

**Comment by jasonblais** [comment]
What do you think about using the new "GitHub Project" tool for managing our workflow?

I've been looking into it these past couple days and it might be something we could use.

![image](https://cloud.githubusercontent.com/assets/13119842/18729457/d543d98a-801f-11e6-9d0a-d858bc85d270.png)


![image](https://cloud.githubusercontent.com/assets/13119842/18729424/b3249f7e-801f-11e6-9f3a-d75fe4cf9bc4.png)


I do agree that we should upgrade our workflow a bit to make it more transparent and easier to follow

**Comment by jasonblais** [comment]
Another thing I've found potentially useful is employing clear STAGES for each pull request (and potentially issue).

I.e. the stages could be
 - stage0-triage
 - stage1-design-review
 - stage2-code-review
 - stage3-testing
 - stage4-doc-review
 - stage5-ready-to-merge

or something along those lines.

I first considered labels, but maybe the GitHub project can accomplish that more nicely

**Comment by Razzeee** [comment]
Yes, but probably unrelated. Greenkeeper.io is keeping track of dependencies and tries to automatically manage them. Only needing interaction via PR when something breaks due to a bump. Haven't really given it a spin yet, but it sounds nice on paper.

**Comment by jasonblais** [comment]
> [Greenkeeper] tracks your dependencies and applies an update to a branch for every new version coming in. Your test suite runs behind the scenes, and only if a dependency update breaks your software, we let you know in a Pull Request, including all the information you need to make an informed decision.

Okay, that makes a lot more sense. I immediately thought about project management when you said 'workflow'.

But yeah, I think that's worth taking a closer look.

**Comment by yuya-oc** [comment]
I feel it's nice because it makes automation. I had used https://gemnasium.com to track dependencies, but I have to test the app manually every update. So it was a little hard.

**Comment by jasonblais** [comment]
Since [the release processç(https://github.com/mattermost/desktop/blob/master/docs/release-process.md) has a step to upgrade dependencies, greenkeeper.io is no longer necessary.
