### ISSUE TITLE
[Bug]: No window controls

### ISSUE THREAD

**Issue by vitoyucepi** [mattermost/desktop#3102]
### Checks before filing an issue

- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.9.0-rc.1

### Operating System

Debian 12 x64

### Mattermost Server Version

N/A

### Steps to reproduce

1. Install fresh Debian 12.
   Other distributions should work out of the box, except ubuntu 24.04.
1. Use a wayland or xorg session.
1. Download the [release artifact](https://releases.mattermost.com/desktop/5.9.0-rc.1/mattermost-desktop-5.9.0-rc.1-linux-x64.tar.gz).
1. Extract the archive.
1. Run the `mattermost-desktop` file.

### Expected behavior

The window control buttons should be visible.

### Observed behavior

No window control buttons like minimize, maximize, close.
![Screenshot of the GNOME desktop with the Mattermost application](https://github.com/user-attachments/assets/ecdeb416-469a-48a6-81c9-8173e6697f91)

### Log Output

```shell
[2024-07-21 09:12:56.980] [error] Logger Log level set to: info
[2024-07-21 09:12:57.192] [info]  [App.Config] config.autostart has been configured: true
[2024-07-21 09:12:57.247] [info]  [App.Initialize] Autoupgrade disabled: false
[2024-07-21 09:12:57.280] [info]  [ServerDropdownView] init
[2024-07-21 09:12:57.301] [warn]  [i18nManager] Failed to set new language en-US
[2024-07-21 09:12:57.302] [warn]  [i18nManager] Failed to set new language US
[2024-07-21 09:12:57.706] [info]  [ModalView] [welcomeScreen] preloading with /home/test/Downloads/mattermost-desktop-5.9.0-rc.1-linux-x64/resources/app.asar/internalAPI.js
```

### Additional Information

The problem seems to be related to electron 30+. I've done a custom build with electron 29 and it works fine.

**Comment by devinbinnie** [comment]
It appears that Electron has given us a new feature, not told us about us and broken the old one :P
This will mean that Linux will not need a window frame going forward, thanks for catching this :)

**Comment by vitoyucepi** [comment]
I tried to create an application with electron:31 and it has window borders.

**Comment by devinbinnie** [comment]
> I tried to create an application with electron:31 and it has window borders.

It's likely there's something about our configuration that's causing it then.
