### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by it33** [mattermost/desktop#311]
Propose updating README

1. Remove "(beta)" tag
2. Replace screenshot with electron-mattermost title with updated banner, e.g. `![20160922_mattermost_desktop](https://cloud.githubusercontent.com/assets/177788/18802327/f1b8d56a-819c-11e6-9b4b-e87b094b7929.png)
`
3. Add links to new documentation for Desktop App on docs.mattermost.com: https://docs.mattermost.com/help/apps/desktop-guide.html
4. Add link to download page: https://about.mattermost.com/downloads

![20160922_mattermost_desktop](https://cloud.githubusercontent.com/assets/177788/18802327/f1b8d56a-819c-11e6-9b4b-e87b094b7929.png)

**Comment by jasonblais** [comment]
Closed by #328
