### ISSUE TITLE
Cannot start Client on RedHat 6

### ISSUE THREAD

**Issue by abij** [mattermost/desktop#312]
I confirm (by marking "x" in the [ ] below): 
- [x] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [x] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [x] This is a product defect issue that can be reproduced using the steps listed below.
- [x] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---
#### Summary

Mattermost Desktop 3.4.0 on RH6 does not start GLIBCXX_3.4.15 missing
#### Steps to reproduce
- On standard RedHat 6.8 we extracted the Mattermost distribution for linux.
- Start the app by ./Mattermost
- Errors that specific versions of GLIBCXX_3.4.15 are missing.
#### Expected behavior

The app should start normally. No interface appears, stops directly.
#### Observed behavior

```
/usr/lib64/libstdc++.so.6: version 'GLIBCXX_3.4.14' not found (required by ./Mattermost)
/usr/lib64/libstdc++.so.6: version 'CXXABI_1.3.5' not found (required by ./Mattermost)
/usr/lib64/libstdc++.so.6: version 'GLIBCXX_3.4.14' not found (required by ./Mattermost)
/usr/lib64/libstdc++.so.6: version 'GLIBCXX_3.4.14' not found (required by ~abij/mattermost-desktop-linux/libnode.so)
```

On RedHat 7, these version are available, because its using a newer GCC version. This is bundled with a newer libstdc++ file which includes these versions. You cannot replace these on RH6.
#### Possible fixes

We have tried to install [devtoolset-4](https://www.softwarecollections.org/en/scls/rhscl/devtoolset-4/) and enable it before starting Mattermost. This did not work. 
Maybe it can be build for RedHat 6 by default with electron-packager.

**Comment by yuya-oc** [comment]
It seems that your report means RedHat 6 can't use any Electron-based applications. electron-packager uses prebuilt Electron to make applications, so it depends on [electron's spec](https://github.com/electron/electron/blob/master/docs/tutorial/supported-platforms.md#linux).
I feel the app should work if there is correct libstdc++ in your system. But I'm not sure how `devtoolset-4` works. Or, probably manually need to build Electron from source code.

**Comment by abij** [comment]
Looks the same as: https://github.com/electron/electron/issues/1172
And relates to: https://github.com/atom/atom/issues/2177

I might try this 'solution':
https://chrome.richardlloyd.org.uk/build_library.html

**Comment by jasonblais** [comment]
Did the solutions work for you @abij?

**Comment by blackSea4477** [comment]
Just Copy 
- libstdc++.so.6  
- ld-linux-x86-64.so.0
- libc.so.6
- libgtk-x11-2.0.so.0 
under the path .....src/node_modules/electron/dist . You can get this from Centos 7 . 
Then Download https://jlison.github.io/bin/centos6/soichih/mirror/gcc-4.7.2.tar.gz and extarct it to some folder and update LD_LIBRARY_PATH 

glibpath=/opt/glib/  (path where you have extracted glib )

export LD_LIBRARY_PATH=$glibpath/glib-2.49.4-kgesagxmtbemim2denf65on4iixy3miy/lib:$LD_LIBRARY_PATH

export LD_LIBRARY_PATH=$glibpath/libffi-3.2.1-wk2luzhfdpbievnqqtu24pi774esyqye/lib64:$LD_LIBRARY_PATH

export LD_LIBRARY_PATH=$glibpath/pcre-8.39-itdbuzevbtzqeqrvna47wstwczud67wx/lib:$LD_LIBRARY_PATH

export LD_LIBRARY_PATH=$glibpath/gettext-0.19.8.1-aoweyaoufujdlobl7dphb2gdrhuhikil/lib:$LD_LIBRARY_PATH


I am able t o run electron on my centos 6.5 and nothing breaks !

**Comment by jasonblais** [comment]
Thanks @blackSea4477, glad to hear!

Closing for now -- if anyone finds further issues on RedHat 6, let us know!

**Comment by Zubairlatif** [comment]
` relocation error: libc.so.6: symbol _dl_starting_up, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference`
I'm facing above issue. Any solutions?
