### ISSUE TITLE
[Bug]: Mattermost 5.9.0 MSI Silent Install not working anymore

### ISSUE THREAD

**Issue by WebBuddha** [mattermost/desktop#3133]
### Checks before filing an issue

- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.9.0

### Operating System

Windows 11 x64

### Mattermost Server Version

9.5.1

### Steps to reproduce

open an administative cmd an run the installation by "mattermost-desktop-5.9.0-x64.msi /qn"

### Expected behavior

I've expect that the msiexec.exe starts in the background and run the installer itself.

### Observed behavior

Try to deploy mattermost-desktop-5.9.0-x64.msi with the parameter /qn but nothing happens, no msiexec.exe process starts at all to begin an silent installation of Mattermost desktop. 

### Log Output

```shell
No log file available because the installation failed.
```

**Comment by devinbinnie** [comment]
@WebBuddha The correct command to run should be `msiexec /i mattermost-desktop-v5.9.0-x64.msi /qn`, can you try running that?

**Comment by WebBuddha** [comment]
> @WebBuddha The correct command to run should be `msiexec /i mattermost-desktop-v5.9.0-x64.msi /qn`, can you try running that?

The windows installer (msiexec) is still running, but mattermost wont be installed also.
We use the PSADT for your SCCM deployments at all and an the cmdlet is using the msiexec /i command in the background.

**Comment by devinbinnie** [comment]
There should be something available in the logs for the MSI installer. I'm not sure how PSADT works internally, but perhaps it's passing different arguments that aren't supported by our MSI? As designed the MSI is supported to be used as per our documentation here: https://docs.mattermost.com/install/desktop-msi-installer-and-group-policy-install.html

If you can get some logs from `msiexec` (the switches to do so are [here](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/msiexec#parameters-3)) I might be able to help further.

**Comment by WB-RH** [comment]
I can can confirm the problem as stated by @WebBuddha 
There's nothing usefull in the logifle either.
I'va also tried to install by command line in an elevated CMD with /qb he seup starts, shows some progress bars and then simply quits, no errors, no messages are shown. When I start the MSI with a doubel cklick ther's no GUI comming up, just the same progress bars and then nothing.

**Comment by cyberm8** [comment]
I have the same problem.

I managed to install Mattermost by running msiexec with the current user (not as an admin).
The program is then installed in the user's Appdata.

As a result, I've switched from a computer GPO to a user GPO.
I am convinced that you had to be an administrator to install Mattermost.
I tried to install version 5.8.1 without admin rights and it failed.

**Comment by obsidian1200** [comment]
> Note that the program location changes : 5.8.1 in `C:\Program Files\Mattermost` (admin rights required), 5.9.0 in `C:\Users\username\AppData\Roaming\Mattermost` (without admin rights). I end up with two installed versions.
> 
> ![image](https://private-user-images.githubusercontent.com/117109145/361228443-071ead10-8027-42bf-bf94-ac1b21a41656.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2OTI2NTIsIm5iZiI6MTcyNDY5MjM1MiwicGF0aCI6Ii8xMTcxMDkxNDUvMzYxMjI4NDQzLTA3MWVhZDEwLTgwMjctNDJiZi1iZjk0LWFjMWIyMWE0MTY1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQxNzEyMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OTFmZTEwNWJjZTliZTk5Njk3YzFlODRiNjliNmM1MGNmOTdmOWQwNTgzZjQxNTg4MGVlOWEyMzUxNjFjMTdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.o_oWwrz1Iw0xbg14jwzDOdp-fh5CpYvVYoq8TUiFHlU)

I've seen the same. Additionally, I have found running `msiexec /a mattermost-desktop-v5.9.0-x64.msi /qn` as an admin will install the application to `C:\mattermost-desktop` without generating an entry under Installed Apps. This has been the only way I've found to install v5.9.0 and have it accessible for all users on a system.

**Comment by devinbinnie** [comment]
@cyberm8 To install for administrators, you'll need the `ALLUSERS=1` parameter, see: https://docs.mattermost.com/install/desktop-msi-installer-and-group-policy-install.html#install-for-all-users
If you're trying to install under the admin account without this line, that could be why it's failing but the logs should reveal that.

The duplicate installer is expected, as we switched installer IDs between v5.8 and v5.9 so the newer one cannot overwrite the old one. For this upgrade, you'll have to install manually.

I've been able to run the installer on multiple machines:
- Windows 10 VM x64
- Windows 11 VM ARM64
- Windows 11 bare-metal (also had never installed the MSI before)

All of those have performed the silent install correctly, so given that the installer works as expected and supported, and without logs I'm afraid there's not much else I can do, so I'm going to close this ticket.

Feel free to continue to comment if anyone has any ideas about how to resolve this.

**Comment by freemandv** [comment]
silent_install.bat

```
@echo off
cls

echo Uninstall mattermost 5.8.1
call msiexec /x {E300F0C8-EA36-4C19-893C-AD1B79914B10} /qn
echo Returncode: %ERRORLEVEL%

echo Uninstall mattermost 5.9.0
call msiexec /x mattermost-desktop-5.9.0-win-x64.msi /qn
echo Returncode: %ERRORLEVEL%

echo Install mattermost 5.9.0
call msiexec /i mattermost-desktop-5.9.0-win-x64.msi ALLUSERS=1 /qn
echo Returncode: %ERRORLEVEL%

echo Create link for mattermost
echo Set objShell = CreateObject("WScript.Shell") > %TEMP%\CreateShortcut.vbs
echo Set objLink = objShell.CreateShortcut("C:\Users\Public\Desktop\Mattermost.lnk") >> %TEMP%\CreateShortcut.vbs
echo objLink.Description = "Mattermost" >> %TEMP%\CreateShortcut.vbs
echo objLink.TargetPath = "%ProgramFiles%\mattermost-desktop\mattermost.exe" >> %TEMP%\CreateShortcut.vbs
echo objLink.Save >> %TEMP%\CreateShortcut.vbs
cscript %TEMP%\CreateShortcut.vbs
del %TEMP%\CreateShortcut.vbs

echo Delete old pin in TaskBar
for /f "delims=" %%a in ('dir/b/ad-h "%SystemDrive%\Users\*"^|findstr/ixvc:"Public"') do (
	IF EXIST "%SystemDrive%\Users\%%a\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\Mattermost.lnk" (
		del "%SystemDrive%\Users\%%a\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\Mattermost.lnk"
	)
)

echo End

EXIT /B 0
```

**Comment by WB-RH** [comment]
I tried with ALLUSERS=1 and ALLUSERS=2, neither of it works,
Attached you'll find a log file from an deplyoment with ALLUSERS=1

The Deplyoment is run with the localsystem user.
[MMinstall.log](https://github.com/user-attachments/files/16777732/MMinstall.log)

**Comment by devinbinnie** [comment]
@WB-RH saw this in your logs:
```
MSI (s) (34:58) [09:03:21:985]: Determined that existing product (either this product or the product being upgraded with a patch) is installed per-user.

MSI (s) (34:58) [09:03:21:985]: PROPERTY CHANGE: Adding MSIINTERNALINSTALLEDPERUSER property. Its value is '1'.

MSI (s) (34:58) [09:03:21:985]: Determined that existing product (either this product or the product being upgraded with a patch) is a dual mode package installed in per-user mode.

MSI (s) (34:58) [09:03:21:985]: PROPERTY CHANGE: Modifying ALLUSERS property. Its current value is '2'. Its new value: '1'.

MSI (s) (34:58) [09:03:21:985]: PROPERTY CHANGE: Deleting ALLUSERS property. Its current value is '1'.

```
Is there an existing install either for a different user or the current one?

**Comment by WB-RH** [comment]
Hi

Indeed, there’s an older version 5.6.0 installed on our clients, before 5.9.0 we never had any trouble upgrading trough MSI, for us, this new behavior is not really a good change.
I never really understood, why anyone would want any software to be installed in a user’s context (unless absolutely necessary for it to work properly), al this ever does is create endless troubles for managed systems.


Best Regards

Roger Hungerbuehler

Workbooster GmbH
Obermülistrasse 85
8320 Fehraltorf
Switzerland

Phone:

+41 44 515 48 80

Direct:

+41 44 515 48 86





Helpline:

+41 44 515 48 83

Support:

***@***.******@***.***>


Von: Devin Binnie ***@***.***>
Gesendet: Mittwoch, 28. August 2024 16:29
An: mattermost/desktop ***@***.***>
Cc: Roger Hungerbühler ***@***.***>; Mention ***@***.***>
Betreff: Re: [mattermost/desktop] [Bug]: Mattermost 5.9.0 MSI Silent Install not working anymore (Issue #3133)


@WB-RH<https://github.com/WB-RH> saw this in your logs:

�M�S�I� �(�s�)� �(�3�4�:�5�8�)� �[�0�9�:�0�3�:�2�1�:�9�8�5�]�:� �D�e�t�e�r�m�i�n�e�d� �t�h�a�t� �e�x�i�s�t�i�n�g� �p�r�o�d�u�c�t� �(�e�i�t�h�e�r� �t�h�i�s� �p�r�o�d�u�c�t� �o�r� �t�h�e� �p�r�o�d�u�c�t� �b�e�i�n�g� �u�p�g�r�a�d�e�d� �w�i�t�h� �a� �p�a�t�c�h�)� �i�s� �i�n�s�t�a�l�l�e�d� �p�e�r�-�u�s�e�r�.�

�

�M�S�I� �(�s�)� �(�3�4�:�5�8�)� �[�0�9�:�0�3�:�2�1�:�9�8�5�]�:� �P�R�O�P�E�R�T�Y� �C�H�A�N�G�E�:� �A�d�d�i�n�g� �M�S�I�I�N�T�E�R�N�A�L�I�N�S�T�A�L�L�E�D�P�E�R�U�S�E�R� �p�r�o�p�e�r�t�y�.� �I�t�s� �v�a�l�u�e� �i�s� �'�1�'�.�

�

�M�S�I� �(�s�)� �(�3�4�:�5�8�)� �[�0�9�:�0�3�:�2�1�:�9�8�5�]�:� �D�e�t�e�r�m�i�n�e�d� �t�h�a�t� �e�x�i�s�t�i�n�g� �p�r�o�d�u�c�t� �(�e�i�t�h�e�r� �t�h�i�s� �p�r�o�d�u�c�t� �o�r� �t�h�e� �p�r�o�d�u�c�t� �b�e�i�n�g� �u�p�g�r�a�d�e�d� �w�i�t�h� �a� �p�a�t�c�h�)� �i�s� �a� �d�u�a�l� �m�o�d�e� �p�a�c�k�a�g�e� �i�n�s�t�a�l�l�e�d� �i�n� �p�e�r�-�u�s�e�r� �m�o�d�e�.�

�

�M�S�I� �(�s�)� �(�3�4�:�5�8�)� �[�0�9�:�0�3�:�2�1�:�9�8�5�]�:� �P�R�O�P�E�R�T�Y� �C�H�A�N�G�E�:� �M�o�d�i�f�y�i�n�g� �A�L�L�U�S�E�R�S� �p�r�o�p�e�r�t�y�.� �I�t�s� �c�u�r�r�e�n�t� �v�a�l�u�e� �i�s� �'�2�'�.� �I�t�s� �n�e�w� �v�a�l�u�e�:� �'�1�'�.�

�

�M�S�I� �(�s�)� �(�3�4�:�5�8�)� �[�0�9�:�0�3�:�2�1�:�9�8�5�]�:� �P�R�O�P�E�R�T�Y� �C�H�A�N�G�E�:� �D�e�l�e�t�i�n�g� �A�L�L�U�S�E�R�S� �p�r�o�p�e�r�t�y�.� �I�t�s� �c�u�r�r�e�n�t� �v�a�l�u�e� �i�s� �'�1�'�.�

�

Is there an existing install either for a different user or the current one?
