### ISSUE TITLE
Desktop app window pops up second to foreground when a new message is received

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#314]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [X] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [X] This is a product defect issue that can be reproduced using the steps listed below.
- [X] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

Desktop app window pops up second to foreground when a new message is received

#### Steps to reproduce

- Mac OS X
- Mattermost Desktop v3.4
- Mattermos server v3.4

1. Open Mattermost Desktop and sign into a team
2. Open two browser windows side-by-side in front of Mattermost
3. Receive a message from someone

#### Expected behavior

Mattermost desktop window remains behind the two browser windows

#### Observed behavior

Mattermost desktop window pops up second to foreground, in front of one of the browser tabs when a new message is received

#### Possible fixes

?

**Comment by yuya-oc** [comment]
Reproduced on macOS 10.12

**Steps to reproduce**:

1. Open Mattermost Desktop and sign into a team
2. Open two browser windows side-by-side in front of Mattermost (Don't click "close(x)" button)
3. Receive a mention or direct message from someone

**Comment by yuya-oc** [comment]
Probably #262 is related. When new messages have arrived, <webview>'s webContents get focus by `componentDidUpdate` handler. At this time, window order is somehow changed on macOS.

**Comment by jasonblais** [comment]
Could we change it so that `<webview>'s webContents` doesn't get focus when a new message is received?

Or will that require reverting #262?

**Comment by yuya-oc** [comment]
I feel reverting is too much. Probably need to stop using `componentDidUpdate` and should call the focus function at applicable part.

**Comment by jasonblais** [comment]
I see - we could get someone's help testing a commit/pull request on Mac OS X if you have a work-in-progress commit or pull request.

It's a pretty bad issue given many users might have two screens side-by-side when working on things. Mattermost popping in front is annoying in that case

**Comment by jasonblais** [comment]
Resolved by #326
