### ISSUE TITLE
Mac: Opening the v3.4 app on OS X 10.11.6 causes -330 errors

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#315]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [X] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [X] This is a product defect issue that can be reproduced using the steps listed below.
- [X] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

Mac: Opening the v3.4 app on OS X 10.11.6 causes -330 errors

#### Steps to reproduce

- Operating System: OS X 10.11.6 
- Mattermost Desktop v3.4
- Mattermost Server v3.4

[Download v3.4 app for Mac OS](https://about.mattermost.com/downloads), and attempt to open the app

#### Observed behavior

Can't connect to the MM server properly, throwing `"ERR_CONTENT_DECODING_FAILED (-330)"` errors

#### Possible fixes
?

**Comment by magicmonty** [comment]
Tried it on 10.12.1 Beta 1 (Sierra). Here I have no problem.

**Comment by jasonblais** [comment]
Highly appreciated @magicmonty!

Have sent a message to the original reporter for more information.

**Comment by jasonblais** [comment]
No new information received -- closing the issue as fixed or no longer valid.

If anyone experiences problems, please reopen the issue with relevant information.

**Comment by jasonblais** [comment]
Also, created a new `cannot reproduce` label to properly mark the reason for closing the issue.
