### ISSUE TITLE
Mac: App v3.4 crashes with OS X 10.10.5

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#316]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [X] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [X] This is a product defect issue that can be reproduced using the steps listed below.
- [X] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

Unable to open the app, which crashes each time. Problem resolved by upgrading to OS X 10.11.6.

Reproduced with MM Desktop v3.4 and MM Server v3.4

**Comment by jasonblais** [comment]
Has anyone else using Mac 10.10.5 experienced problems?

**Comment by yuya-oc** [comment]
I'm using OS X 10.10.5 in my work, but I have not experienced.

**Comment by magicmonty** [comment]
Works for me on 10.12.1

**Comment by jasonblais** [comment]
Thanks @yuya-oc and @magicmonty, much appreciated!

The original reporter hasn't been able to reproduce it after upgrading to OS X 10.11.6.

Closing for now, if anyone is able to reproduce, please reopen the issue with relevant information.
