### ISSUE TITLE
Mac: Right-clicking a link doesn't provide "Copy Link" option

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#318]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [X] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [X] This is a product defect issue that can be reproduced using the steps listed below.
- [X] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

Issue in one concise sentence.

#### Steps to reproduce

- Mattermost Desktop App v3.4
- Mattermost Server v3.4

1. Post a link in a channel
2. Right-click the link

#### Expected behavior

After right-clicking a link, a "Copy Link" option appears, which let's the user to copy the link.

#### Observed behavior

See below

![image](https://cloud.githubusercontent.com/assets/13119842/18900562/990c508c-8510-11e6-90ad-9930773516aa.png)

#### Possible fixes

I think it was supposed to be https://github.com/mattermost/desktop/pull/272

**Comment by jnugh** [comment]
Electron Context Menu does not include a "Select All" option at all, did you pick the correct binary? Maybe this was an old version, the old Menu Code has been completely removed (https://github.com/mattermost/desktop/pull/272/files#diff-501bad972b0e1d172ec174384d20bf40L1).

**Comment by jasonblais** [comment]
I see -- I'll check with the original issuer, but they reported it was on v3.4

**Comment by magicmonty** [comment]
Can't reproduce this behaviour on OSX 10.12.1 (neither at Tag v3.4.0 nor v3.4.1 nor current master)

**Comment by jasonblais** [comment]
Thanks @jnugh and @magicmonty for helping with the testing, much appreciated :) 

I asked the original reported and they mentioned it shows `Copy Link` now as expected. 

Closing the issue,
