### ISSUE TITLE
[Bug]: Linux client crashes when click to download or view an attachement [random with high occurence]

### ISSUE THREAD

**Issue by goutnet** [mattermost/desktop#3188]
### Checks before filing an issue

- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.9.0

### Operating System

Ubuntu 24.04.1 LTS x64

### Mattermost Server Version

10.1.1

### Steps to reproduce

 1. User 1: Send a file on a channel (ex: DXF, PDF etc…)
2. User 2: open the file

(more rarely): download the file directly would have same effects

### Expected behavior

open the file, or at least do not crash

### Observed behavior

crash

### Log Output

```shell
20:51:35.229 › [App.Initialize] Current working directory is /home/fdelizy, changing into /opt/Mattermost
20:51:35.305 › [App.Config] config.autostart has been configured: true
20:51:35.328 › [App.Initialize] Autoupgrade disabled: false
20:51:35.368 › [ServerDropdownView] init
20:51:35.396 › [i18nManager] Failed to set new language en-US
20:51:35.396 › [i18nManager] Failed to set new language 
20:51:35.482 › [App.Config] config.autostart has been configured: true
20:51:36.066 › [App.Config] config.autostart has been configured: true
[285218:1028/205150.131063:ERROR:browser_main_loop.cc(278)] GLib-GObject: ../../../gobject/gsignal.c:2685: instance '0x3d2c022e90d0' has no handler with id '4713'
Segmentation fault (core dumped)
```

**Comment by devinbinnie** [comment]
@goutnet Do you get any visual indication when the crash happens? Like a dialog box or something?
Have you seen this thread: https://github.com/mattermost/desktop/issues/3140? Seems like your issue is similar.

**Comment by goutnet** [comment]
no dialog, or maybe something flashing very quickly not a real chance to see what.

#3140 is indeed looking very similar, downloads do work, but it crashes randomly  after the download works.

**Comment by goutnet** [comment]
Seeing this in the crash message:

```
Application: Mattermost 5.9.0 [commit: 97c7331
Platform: Linux 6.8.0-47-generic x64
TypeError: s.nativeImage.createThumbnailFromPath is not a function
    at C.formatDownloadItem (/opt/Mattermost/resources/app.asar/index.js:2:258352)
    at C.upsertFileToDownloads (/opt/Mattermost/resources/app.asar/index.js:2:255760)
    at C.doneEventController (/opt/Mattermost/resources/app.asar/index.js:2:257116)
    at DownloadItem.<anonymous> (/opt/Mattermost/resources/app.asar/index.js:2:254922)
    at Object.onceWrapper (node:events:634:26)
    at DownloadItem.emit (node:events:519:28)

```
Yep, it now looks like a clear duplicate of #3140.

Closing here as this is a duplicate.
