### ISSUE TITLE
Desktop App 5.9.0 Freezing Ubuntu 24.04.1 LTS

### ISSUE THREAD

**Issue by jonespaulr** [mattermost/desktop#3195]
Before filing a bug report, please check the following:

1. Confirm you’re filing a new issue. [Search existing tickets in Jira](https://mattermost.atlassian.net/jira/software/c/projects/MM/issues/) and [existing issues in GitHub](https://github.com/mattermost/mattermost/issues) to ensure that the ticket does not already exist. [X]
2. Confirm your issue does not involve security. Please submit security issues via our [Responsible Disclosure Policy](https://mattermost.com/security-vulnerability-report/). [X]
3. Confirm your issue is not a feature request. Please submit feature requests on [UserVoice](https://mattermost.uservoice.com/forums/306457-general). [X]
4. Confirm your issue is not a troubleshooting question. Please submit troubleshooting questions on the [forum](https://forum.mattermost.com/).[X]
5. File a bug report using the format below. Mattermost will confirm steps to reproduce and file in Jira, or ask for more details if there is trouble reproducing it. If there's already an existing bug in Jira, it will be linked back to the GitHub issue so you can track when it gets fixed.

#### Summary
Desktop app freezes after a few minutes - no new messages arrive, message window shows 'Loading...' if team or channel changed. Reload or Reload and Clear Cache go to spinning wheel icon and never progress. App is installed from Mattermost Ubuntu repo - same behaviour for installing via snap.

#### Steps to reproduce
Open the app, leave it for a few minutes.

#### Operating System
Ubuntu Linux 24.04.1 LTS x64

#### Mattermost Server Version
9.6.1

#### Expected behavior
App should continue to work normally, with new messages arriving and being able to switch between teams and channels with no issue

#### Observed behavior
Behaviour is normal immediately after opening, but before long (between 5-10 minutes) app becomes unresponsive. Doesn't seem to be triggered by _doing_ anything, just a matter of time. Closing and reopening the app immediately solves the issue, for a few minutes. Web client version of the same works without issue.

#### Additional Information
The only thing in the logs that registers as an error is "[2024-11-05 16:18:03.380] [error] [WebContentsEventM...] [TEST] [TAB_MESSAGING] [renderer] Uncaught (in promise) Error:      Not authorized", although I believe this to be a false positive from other searches.

#### Possible fixes
This is an issue that has come about since upgrading from the previous Ubuntu LTS 22.04.05 where the app worked without issue. So presumably tied to something which has changed with an Ubuntu package. But no idea what.

**Comment by devinbinnie** [comment]
@jonespaulr Does the same thing happen if you try to use `community.mattermost.com`? I'm wondering if it's due to a large load on the web client that the Desktop App is struggling with somehow.

**Comment by jonespaulr** [comment]
@devinbinnie. Adding that to the client and leaving it for a few minutes and it's still working as expected, whereas if I change server back to 'my' one, that's frozen already.

Interestingly as I type this I've had a private message through on my server. The red notification dot has appeared and the user's name in Unread, but no message:

![Screenshot from 2024-11-06 09-00-41](https://github.com/user-attachments/assets/ca5c183b-3173-47b2-a54c-10b99346f08c)

For the server here - that's larger/has more teams/channels than the community server but AFAIK I'm the only person having problems. And it does seem linked to my OS upgrade, as no problems here previously. So a bit strange if it's a server-side issue? But maybe...

**Comment by devinbinnie** [comment]
@jonespaulr So if you're able to switch between servers freely, then it's likely not the Desktop App having issues specifically, it's likely something in the client. Do you see any errors in Developer Tools? (you can see in View > Developer Tools for Current Server).

To be sure, can you send some logs from the Desktop App? First can you turn on Debug logging in the Settings modal and then use the app for a bit while the server is slow? That way we can capture if there's anything the app is doing to slow things down.

**Comment by jonespaulr** [comment]
This is the log output after I started the app the most recent time. Things here look in line with the rest of the log going back a good few months.

[main.log](https://github.com/user-attachments/files/17649013/main.log)

On the developer console though, yes - these ERR_CONNECTION_REFUSED messages start as soon as the app goes unresponsive.

![Screenshot from 2024-11-06 15-07-28](https://github.com/user-attachments/assets/1cfa69a9-dd78-447a-9466-dc63f15bb7b7)

**Comment by devinbinnie** [comment]
@jonespaulr Looks like your connection to the server is being lost, or perhaps blocked somehow. Are you running in a managed environment, or do you have a VPN or some kind of endpoint security? It looks like something external is stopping the app from connecting. Assuming Developer Tools doesn't also go unresponsive, it's not likely the Desktop App stopping you from connecting.

**Comment by jonespaulr** [comment]
Connection is on the same VLAN to an internally hosted server, so no VPN here. There's a local firewall on the server, but that's just listening on 443 and is open to internal traffic. I can't think of anything else that would be blocking traffic, especially not anything that would allow it for a few minutes before closing it off.

There's AV on my machine and on the server, but logs here are clean. SELinux is the other thing that could block internally, but again, that's a hard block not something that comes and goes and isn't logging any issues here either.

Developer Tools (and the community server) do keep working once the one server has gone into this loop though, so I'd agree that that doesn't seem like an app problem. To that extent, I guess this can be closed as not an App issue, although still quite puzzling!

Thanks for the help.

**Comment by devinbinnie** [comment]
No problem, if you end up with more information let me know. Otherwise I'll close this issue.
