### ISSUE TITLE
[Bug]: On windows there is no 2nd screen to share

### ISSUE THREAD

**Issue by majkinetor** [mattermost/desktop#3196]
### Checks before filing an issue

- [X] This issue doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/mattermost-server/issues).
- [X] I have checked the [issue tracker](https://github.com/mattermost/desktop/issues) and have not found an issue that matches the one I'm filing.
- [X] This issue is not a troubleshooting question. Troubleshooting questions go here: https://forum.mattermost.com/c/trouble-shoot/16.
- [X] This issue is not a feature request. You can request features and make product suggestions here: https://mattermost.com/suggestions/.
- [X] This issue reproduces on the most recent [stable version](https://github.com/mattermost/desktop/releases/latest), or the most recent [prerelease version](https://github.com/mattermost/desktop/releases) of the Mattermost Desktop App.
- [X] I have read the [contribution guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

### Mattermost Desktop Version

5.8.1

### Operating System

Windows 11 x64

### Steps to reproduce

Have 2 monitors connected to Windows. Share the screen. One is missing.

### Expected behavior

Have both screens present like on web.

### Observed behavior

Screenshot from desktop, missing **Screen 1**, showing only 2 windows from it.

![image](https://github.com/user-attachments/assets/5a0b8ad0-1847-47cb-aadc-092aed8fd2cb)

The same thing on web shows **Screen 2**

![image](https://github.com/user-attachments/assets/6af4e9ed-5fc1-433a-97ad-29c353cf902d)

### Log Output

```shell
-
```

**Comment by devinbinnie** [comment]
Can you try this on [v5.9)](https://github.com/mattermost/desktop/releases/tag/v5.9.0), or [v5.10.0-rc.3](https://github.com/mattermost/desktop/releases/tag/v5.10.0-rc.3)?

Also what version of the calls plugin is your server using? This might be an issue on that end cc @streamer45

**Comment by streamer45** [comment]
The plugin side relies on what `desktopCapturer` returns so I find it most likely for a problem to exist there, especially if the browser implementation works as expected.

**Comment by majkinetor** [comment]
@devinbinnie 

It works on 5.10-rc3


![image](https://github.com/user-attachments/assets/6bf21922-f5a8-47c3-add7-157a6bfe24d8)

**Comment by devinbinnie** [comment]
Great, so this was likely a bug in an older Electron version that is fixed in v5.10. Closing as fixed.
