### ISSUE TITLE
Auto-read notification on Arch/i3

### ISSUE THREAD

**Issue by Razakhel** [mattermost/desktop#327]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [x] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [x] This is a product defect issue that can be reproduced using the steps listed below.
- [x] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

Notifications are not appearing for the currently opened channel, while in another workspace.

#### Steps to reproduce

- OS: Arch Linux - using i3-wm
- Client: Mattermost Desktop 3.4.0 
- Server: Mattermost Enterprise Edition 3.4.0
- Steps to reproduce : Open Mattermost on any channel and any workspace you want, then go to another one and wait for a message to be written on the selected channel.

#### Expected behavior

While Mattermost is on another workspace than the current one, it does not display notifications for a new message written in the current selected channel (at least on the taskbar icon, I disabled phone app notifications/mail and do not have any popup on my computer).
I figured it may have been i3 relevant, but since it does not happen with any of my other apps (Skype, Slack...), I don't think it really is. There may be some intermediate focus, on which the app is switching to when changing workspace, that I don't know.

#### Observed behavior

The usual black circle, indicating a notification, isn't appearing in that particular case.
![notif_ko](https://cloud.githubusercontent.com/assets/5424728/18992499/edae9bd0-871e-11e6-89df-6a656cfc8cf9.png)
![notif_ok](https://cloud.githubusercontent.com/assets/5424728/18992503/f1abb95c-871e-11e6-99e6-ab8b83c4e7dc.png)

#### Possible fixes

I will try to get into the MM source code in a *(probably)* near future, if I have the time to.

**Comment by Razakhel** [comment]
The issue seems to be resolved, thanks!

**Comment by DPSLynix** [comment]
Which is weird, since nothing did change?

**Comment by Razakhel** [comment]
Maybe it just wasn't related to MM directly then. That didn't occur to me for a while now though (and I confirm that it worked just now), so I guess it's not an issue anymore.
