### ISSUE TITLE
Search keybinding on OS X not consistent with OS

### ISSUE THREAD

**Issue by hamishgraham** [mattermost/desktop#335]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [x] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [x] This is a product defect issue that can be reproduced using the steps listed below.
- [x] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

The key binding to search in OS X version is command-s but should be command-f.

#### Environment

 - OS used: OS X 10.12
 - Mattermost desktop version: 3.4.1

#### Expected behavior

To be consistent with other applications it would make more sense for the search key binding to be command-f and not command-s. Command-s is typically used for saving and not searching.

**Comment by yuya-oc** [comment]
The behavior is by design. Please see #270. In future Command+F would have the feature, for example "find-in-page".
