### ISSUE TITLE
There is unexpected "Show Tab Bar" menu item on macOS 10.12

### ISSUE THREAD

**Issue by hamishgraham** [mattermost/desktop#337]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [x] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [x] This is a product defect issue that can be reproduced using the steps listed below.
- [x] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

The Show Tab Bar menu item is inconsistent with team tabs.

#### Steps to reproduce

Environment
- OS X 10.12
- Mattermost Desktop App version: 3.4.1
- Mattermost Server version: v3.3.0 

On OS X there is a menu item called Show Tab Bar. This menu item show/hides what appears to be an Electron provided tab bar that is different to the team tabs. See screenshot: http://imgur.com/a/DBMXC

#### Expected behavior

The Show Tab Bar menu item should show/hide the Team tabs.

#### Observed behavior

The Show Tab Bar menu item shows a different additional tab bar.

#### Possible fixes

Option1: Hide the Show Tab Bar menu item.

Option2: Make the Show Tab Bar menu item show/hide the team tabs.

Option3: Adopt the provided tab functionality instead of the existing team tabs. This allows the tabs to be consistent with other applications and allows for behaviour like dragging tabs to a new window, combining tabs from windows etc.

**Comment by yuya-oc** [comment]
I can't see the menu on my macOS 10.12.

![no-show-tab-bar](https://cloud.githubusercontent.com/assets/1412057/19153945/71a2b158-8c13-11e6-93a6-daeff7ead68d.png)

But probably it's a issue which was fixed at electron v1.4.2. electron/electron#7415

**Comment by yuya-oc** [comment]
@hamishgraham This should be solved by using electron v1.4.2 (#307). Would you try the latest build?
https://circleci.com/gh/mattermost/desktop/734#artifacts

**Comment by hamishgraham** [comment]
Sure no problem - I can confirm that the above build does not show the extra "Show Tab Bar" menu item.

**Comment by yuya-oc** [comment]
Thanks for your confirmation!

**Comment by sloantash** [comment]
I'm having this issue suddenly in MacOS 10.14.3 with electron 3.1.6. Any ideas? I've got a view menu with the only option being role: "togglefullscreen", and that works, but those two items appear above it.
