### ISSUE TITLE
Regression: Receiving a direct message from someone doesn't automatically add the user to direct message contact list

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#338]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [X] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [X] This is a product defect issue that can be reproduced using the steps listed below.
- [X] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

Receiving a direct message from someone doesn't automatically add the user to direct message contact list

#### Steps to reproduce

- Operating System: Mac
- Mattermost Desktop App v3.4
- Mattermost Server v3.4

Repro steps:
1) Sign into desktop application as User1
2) On a browser, create a new account (call it User2)
3) With User2 account, send a direct message to User1
4) Switch back to desktop app as User1

Note: Step 2 is not necessary, but guarantees repro steps as the user doesn't appear in the direct message contact list.

#### Expected behavior

User1 sees a red badge with "1" on the team tabbar, AND User2 automatically appears on the direct message contact list.

#### Observed behavior

User1 sees a red badge with "1" on the team tabbar, but do not see User2 in the direct message list. Thus, there is no indication who the message was from.

**Comment by jasonblais** [comment]
Noted as a regression as I'm pretty certain this used to work.

Tested and the expected behaviour works on Mac.

**Comment by yuya-oc** [comment]
Please let me confirm. Does it happen on chrome? As far as reading the issue, it seem to happen also on chrome.

**Comment by jasonblais** [comment]
At least one user reported that it doesn't reproduce on their browser, just on the desktop app.

**Comment by jasonblais** [comment]
It's reproduced on latest `master` now on the server side. Jira ticket created here: https://mattermost.atlassian.net/browse/PLT-4496

Closing this issue given it's not desktop app specific
