### ISSUE TITLE
Automatically remove caches when desktop app version is updated

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#342]
Auto-reloading might not run when updating the app to a new version given the Mattermost server likely doesn't recognize the app version.

This is causing issues such as #313 

Suggestion is to remove caches when updating the app. This would mean that the app needs to save the version that was used last time.

**Comment by jnugh** [comment]
We already save some sort of config version, we can use this to detect any version prior to the one which purges cache on startup!
I will prepare a PR for this!
