### ISSUE TITLE
On Linux, middle-click to paste primary selection results in two copies of pasted text

### ISSUE THREAD

**Issue by jasom** [mattermost/desktop#343]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [x] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [x] This is a product defect issue that can be reproduced using the steps listed below.
- [x] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

On Linux, middle-click to paste primary selection results in two copies of pasted text.

#### Steps to reproduce

Please include: 
- Linux
- Version 1.3.0
- Mattermost Server 3.4.0

#### Observed behavior

Fairly simple to reproduce; select text in another application (Firefox, rxvt-unicode, and claws-mail have all been confirmed by me), and middle-click to the "Write a message..." box in mattermost desktop.  Two copies of the primary selection appear.  I tested this on the web client in chrome and do not observe this behavior.

#### Possible fixes

Not investigated.

**Comment by yuya-oc** [comment]
Please try the latest release, v3.4.1. If the issue still happens, please write about your distribution and window manager.

**Comment by jasom** [comment]
Fixed in 3.4.1
