### ISSUE TITLE
Failed to build on Arch Linux

### ISSUE THREAD

**Issue by stevenroose** [mattermost/desktop#346]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [X] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [X] This is a product defect issue that can be reproduced using the steps listed below.
- [X] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

Does not build on Arch Linux.

#### Steps to reproduce

Simple:
`pacaur -S mattermost-desktop`

Better, this is the build script:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mattermost-desktop

#### Observed behavior

Error log:
https://gist.github.com/stevenroose/1fb03b768c5aee5ff99926357bf7487d

**Comment by yuya-oc** [comment]
I could not find which part fails in the log file. AUR is not supported officially, would you ask to the maintainer?

**Comment by stevenroose** [comment]
I did also notify the maintainer, however I took a look at the build script and it seemed fine, so there might be a problem from this side.

**Comment by stevenroose** [comment]
It seems to work now with an update to Node.js and npm.
