### ISSUE TITLE
Latest MatterMost desktop client freezes in Windows 10

### ISSUE THREAD

**Issue by indrekpihor** [mattermost/desktop#347]
I confirm (by marking "x" in the [ ] below): 

- [-] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [-] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [x] This is a product defect issue that can be reproduced using the steps listed below.
- [-] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

I installed 32Bit latest MM desktop app 3.4.1 and it freezes after some time of use, same thing happens when I install 64BIT.

#### Steps to reproduce

Install latest app with latest server also installed, you can use the app, but freezes in about 3-4 minutes of usage. Notifications continue to work, but UI freezes, nothing can be pushed on the screen. After reopening the app, all works again. On same time web-app works pefectly.

I am using Windows 10 Enterprise 64bit, version 1607, Mattermost 3.4.1 desktop, Mattermost Version: 3.4.0 server.

To reproduce, open the app, log into MM and start using it, after some while it freezes. Before the installable app, the desktop application worked, but now even that freezes.

Freezing means, nothing can be clicked on MM window, even the horizontal app menu : file, edit view .. etc.

**Comment by indrekpihor** [comment]
Here is a bit more info from windows event logs: 

The program Mattermost.exe version 1.2.8.0 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.
 Process ID: 1240
 Start Time: 01d22dc779ea3de7
 Termination Time: 4294967295
 Application Path: C:\Users\XXX\AppData\Local\mattermost\app-3.4.1\Mattermost.exe
 Report Id: 21b0bd48-99bc-11e6-82b2-00aa004d0001
 Faulting package full name: 
 Faulting package-relative application ID:

**Comment by yuya-oc** [comment]
Hmm...it seems the process is somehow stopping. But I'm using Windows 10 Pro 64bit and I have never seen the issue.
In the second comment, I was not sure what is the reason of problem. Is there any more info on the control panel?

**Comment by indrekpihor** [comment]
I have checked the Security and maintenance .. seems like there is no futher info. Not sure what to do, maybe I need to wait until some-one else experiences same issue.

**Comment by indrekpihor** [comment]
Issue solved. When person has Lenovo X1, with lenovo own power management software installed, then high performance powersettings (with train icon) then desktop apps like Mattermost desktop will hang, tested on Slack also, same thing, turned into balanced mode and all cool. 

strange but.. still  may help someone in future.

**Comment by mjekovec2** [comment]
I'm having the same issue. Dell XPS 13, no special power management. Freezes, for a few minutes, then throws out all the messages at once.

**Comment by jasonblais** [comment]
@yuya-oc Is there debugging available for the desktop app?

@mjekovec2 anything in the server logs? (From System Console > Logs)

**Comment by jasonblais** [comment]
@mjekovec2 have you noticed any patterns when the freezing occurs? Such as after receiving a notification or after someone posts a link/image preview?

**Comment by mjekovec2** [comment]
1) No, I don't see a pattern. It might be notification as currently very few people are online and I'm not receiving any notification. And everything works great

2) I will try to track logs tomorrow. Currently, the history is cleared and I'm only seeing logs from a few minutes ago.

Thanks for a quick reply

**Comment by mdementev** [comment]
Problem still reproducible. 
I see pattern. Problem occurs when application is minimized and i receive a message. After expanding application window - it freeze for 2-3 minutes. Console is clear and doesn't have any errors.

**Comment by mdementev** [comment]
Seems that problem has been solved by DIsabling windows notifications for Mattermost.
