### ISSUE TITLE
Mac: Red badge on dock icon doesn't honor channel notification preferences

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#349]
I confirm (by marking "x" in the [ ] below): 
- [X] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [X] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [X] This is a product defect issue that can be reproduced using the steps listed below.
- [X] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 
---
#### Summary

Mac: Red badge on dock icon doesn't honor channel notification preferences

#### Steps to reproduce

Mattermost Server v3.4
Mattermost Desktop App v3.4.1

Repro:
1) Ensure you have no unread messages and the OS X dock icon doesn't show a red notification dot
2) Change channel notifications to "Mark Channel Unread" = "Only For Mentions"
3) Change focus away from Mattermost.
4) Receive a message in that channel that doesn't contain a mention.

Observed: Channel on the left-hand sidebar (inside the app) does not show unread (correct), but OS X dock icon shows the red notification dot (incorrect)

**Comment by yuya-oc** [comment]
Probably this happens in other platforms.

Usually `src/browser/webview/mattermost.js` counts unread channels in the left-hand sidebar. But it also counts unread messages in the main pane of the current channel in order to keep badges even if the app is working in background.

**Comment by jasonblais** [comment]
Ah interesting,

it wasn't reproducing on Windows 10 when I tried, but could reproduce on Linux though.

**Comment by yuya-oc** [comment]
I confirmed this today, but it's not reproduced on either of Windows 10 or macOS.

**Comment by yangchen1** [comment]
Not reproduced on macOS.

**Comment by jasonblais** [comment]
Thanks to both of you, glad to hear.

@yuya-oc was this reproducing on Linux though? If you didn't test, no worries as the original bug report was on Mac.

**Comment by yuya-oc** [comment]
@jasonblais I didn't test on Linux. And now the issue doesn't reproduce on Ubuntu 16.04 with Unity. However, possibly the badge might not work on Ubuntu 16.04 in the first place, but I'm not sure tough.

**Comment by yuya-oc** [comment]
@jasonblais I misunderstood the spec. On ubuntu unity, only mentions are counted and shown as the badge, so this problem never happens.

**Comment by jasonblais** [comment]
Got it -- closing as cannot reproduce.

Thanks all!
