### ISSUE TITLE
Images don't appear for http URL

### ISSUE THREAD

**Issue by jbrazeau** [mattermost/desktop#35]
An image that appears in a browser based mattermost client doesn't appear in the client (reproductible on Mac, Linux & Window)

**Comment by yuya-oc** [comment]
How did you show the image in browser? Screenshot is better.

**Comment by jbrazeau** [comment]
You're perfectly right. It seems that the problem is not systematic. Here is an example :
![screen shot 2016-02-16 at 15 01 49](https://cloud.githubusercontent.com/assets/1405453/13078334/96a5dc76-d4be-11e5-9fbd-214bb0cd75a8.png)

**Comment by jbrazeau** [comment]
But it is true that the feature works perfectly for many images. I have not understood the difference between images that are correctly shown and images that doesn't appear.

**Comment by jbrazeau** [comment]
(I forgot to tell you that in the previous example, the image is correctly displayed in the browser)
![screen shot 2016-02-16 at 15 38 24](https://cloud.githubusercontent.com/assets/1405453/13079218/70ba02ee-d4c3-11e5-8f81-6bc97b0943bd.png)

**Comment by yuya-oc** [comment]
I could get the image v1.0.5 with Mattermost 1.4.

![2016-02-16 23 21 00](https://cloud.githubusercontent.com/assets/1412057/13078846/9eef6d84-d504-11e5-8449-b2ba391c96a5.png)

Could you show the correct case in the app? In my guess, it depends on its url.

**Comment by jbrazeau** [comment]
This URL works fine : https://images.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png

<img width="398" alt="screen shot 2016-02-16 at 15 46 44" src="https://cloud.githubusercontent.com/assets/1405453/13079445/8fce0986-d4c4-11e5-93af-610c1a7fecc2.png">

**Comment by yuya-oc** [comment]
Is your Mattermost served by https? If so, only https url image will be shown.

Electron has following options to control its security:

> webSecurity Boolean - When setting false, it will disable the same-origin policy (Usually using testing websites by people), and set allowDisplayingInsecureContent and allowRunningInsecureContent to true if these two options are not set by user. Default is true.
> allowDisplayingInsecureContent Boolean - Allow an https page to display content like images from http URLs. Default is false.
> allowRunningInsecureContent Boolean - Allow a https page to run JavaScript, CSS or plugins from http URLs. Default is false.

However, `webview` has just only `disablewebsecurity` option. I did not add it because `allowRunningInsecureContent` should be false.

**Comment by jbrazeau** [comment]
Yes it is served by HTTPS. Is there a way to change these parameters ? If I understand, these parameters come from electron that you use. Once the app is built, can these parameters still be changed ?

**Comment by yuya-oc** [comment]
I think the package contains `browser/index.js`. Please try adding "disablewebsecurity" attribute to webview. However I think it's a little difficult because index.js is compiled from index.jsx and many modules.

**Comment by rompic** [comment]
i see the same when posting xkcd images (works in the browser)

**Comment by david-at** [comment]
Yeah this is an issue with HTTP/HTTPS. Confirmed here.

**Comment by yuya-oc** [comment]
Because of security, I won't add `disablewebsecurity` attr. If you want, please add it and rebuild the app.

**Comment by disassembler** [comment]
So what's the solution? It seems telling people to not use https because images won't display is a security issue as well. How does the browser handle the origin policy to make it work?

**Comment by jbrazeau** [comment]
Isn't it possible to add a configuration parameter so that the end user can choose whether he prefers security or usability ?

**Comment by yuya-oc** [comment]
Reopen this issue for reference.

**Comment by SockenSalat** [comment]
Well, this is still unsolved ... any plans for addressing this?
