### ISSUE TITLE
Change user agent from "Safari/vX.X.X" to "Desktop App/vX.X.X"

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#352]
I confirm (by marking "x" in the [ ] below): 
- [X] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [X] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [X] This is a product defect issue that can be reproduced using the steps listed below.
- [X] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 
---
#### Summary

Change user agent from "Safari/vX.X.X" to "Desktop App/vX.X.X"
#### Steps to reproduce
- Operating System: Windows 10
- Mattermost Desktop App v3.4.1
- Mattermost Server v3.4
#### Expected behavior

**Account Settings > Security > View and Logout of Active Sessions** shows `Desktop App/3.4.0` as the user agent for desktop apps
#### Observed behavior

**Account Settings > Security > View and Logout of Active Sessions** shows `Safari/3.4.0` as the user agent for desktop apps

![image](https://cloud.githubusercontent.com/assets/13119842/19823003/5b1fbcfa-9d34-11e6-976d-3a6f940f6210.png)

**Comment by yuya-oc** [comment]
We should not change the user agent. The whole of it is like `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Mattermost/1.2.1 Chrome/49.0.2623.75 Electron/0.37.8 Safari/537.36` and it's important for webapp.
So [`webapp/components/activity_log_modal.jsx`](https://github.com/mattermost/platform/blob/master/webapp/components/activity_log_modal.jsx) of /platform repository should be updated like `iPhone Native App` instead.

**Comment by jasonblais** [comment]
I see, got it. Will report to the platform team @yuya-oc

**Comment by jasonblais** [comment]
Closing, will be tracked in Jira by the Mattermost core team: https://mattermost.atlassian.net/browse/PLT-4317

**Comment by Artwalk** [comment]
Hi, If I want add more string in the user agent, which files should I inspect?
I tried `node_modules/ua-parser-js` `getUA` and`setUA`, then rebuilt it, but this did not work

**Comment by jasonblais** [comment]
@yuya-oc any thoughts? I'm not sure if this would be handled on the server side

**Comment by yuya-oc** [comment]
You can use `session.defaultSession.getUserAgent()` and `session.defaultSession.setUserAgent()` in `src/main.js`. http://electron.atom.io/docs/api/session/
Existing elements of user agent should be kept to get some features from webapp. See server's [`webapp/utils/user_agent.jsx`](https://github.com/mattermost/platform/blob/master/webapp/utils/user_agent.jsx)

**Comment by Artwalk** [comment]
Yeah, It works.

Thank you 👍😄
