### ISSUE TITLE
Change target screen resolution from 800x600 to 1280x800

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#353]
I confirm (by marking "x" in the [ ] below): 
- [X] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [X] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [X] This is a product defect issue that can be reproduced using the steps listed below.
- [X] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---
#### Summary

[An estimated 94% of browsers are 1280x800 or larger](http://www.w3schools.com/browsers/browsers_display.asp), and using the current 800x600 resolution can cause issues such as hiding the channel header on initial launch.

Thus, propose changing our target screen resolution to be 1280x800.

(Note that the default desktop app window size should be a little smaller vertically than the target 1280x800 resolution, so that it's not hidden by the bottom taskbar)

**Comment by jasonblais** [comment]
(Note that the default desktop app window size should be a little smaller vertically than the target 1280x800 resolution, so that it's not hidden by the bottom taskbar)

**Comment by yuya-oc** [comment]
The default window dimensions should be smaller than target screen to avoid conflicting with other UI, e.g. task bar. So the dimensions are set to 1000x700.

**Comment by jasonblais** [comment]
We're also targeting 1024x768 screen resolution instead, update title and description.

This is because 1366x768 resolution is common, in which case targeting 1200x800 isn't recommended
