### ISSUE TITLE
Notifications still sounding and popping even when disabled

### ISSUE THREAD

**Issue by madchap** [mattermost/desktop#356]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a feature idea. Feature ideas go here: http://www.mattermost.org/feature-ideas/
- [x] This is not a troubleshooting question. Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/
- [x] This is a product defect issue that can be reproduced using the steps listed below.
- [x] I have read [CONTRIBUTING.md](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

#### Summary

When setting "Send desktop notifications" to "Only for mentions" or "Never", I still receive notifications with sound and pop-up.

#### Steps to reproduce

Please include: 
- Operating System: Mac OSX or Linux Ubuntu 16.04
- Mattermost Desktop App version (See **Help > Version Number**): 3.4.1 
- Mattermost Server version (See **Mattermost Menu > About Mattermost: **, where **Mattermost Menu** can be accessed by clicking on three dots next to your profile picture) : 3.4.0 Team Edition.
- Clear steps to reproduce the issue: Just be part of a channel with monitoring alerts popping at an alarming rate, set your notifications to never, and enjoy the storm :)

#### Expected behavior

If set to "never", I should never be notified.
If set to "Only for notifications", my alias should be on the line.

#### Observed behavior

The setting doesn't take effect.

#### Possible fixes

If you can, link to the line of code that might be responsible for the problem.

**Comment by yuya-oc** [comment]
Would you check whether that happens also on web browsers? Notifications are invoked by the webapp of the mattermost server. So the issue should also happens on browsers.

If it happened on browsers, please consider make an issue at mattermost/platform repository.

**Comment by madchap** [comment]
I just tried in the webapp

- The notifications settings were different than the ones I have on the desktop
- After changing to mention only, I still got the notifications via google chrome as well.

I will move this issue to platform.

Thank you.
Best,
fred

**Comment by madchap** [comment]
Opened issue 4403 on mattermost-desktop https://github.com/mattermost/platform/issues/4403.
