### ISSUE TITLE
Tray icon image is missing on Linux

### ISSUE THREAD

**Issue by yuya-oc** [mattermost/desktop#360]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Tray icon image is missing on Linux.

**Steps to reproduce**
- Operating System: Linux Mint 18 Cinnamon
- Mattermost Desktop App version: master branch (b27c2dda36223acd1fdffbf5f4099b6c24352118)
- Mattermost Server version: N/A 
- Clear steps to reproduce the issue
  1. Build and launch the packaged app.
  2. Enable tray icon.
  3. Restart the application.
  4. The blank space appears instead of the tray icon.

**Expected behavior**
The png image appears.
<img alt="tray_png" src="https://cloud.githubusercontent.com/assets/1412057/20059137/01d13e6a-a538-11e6-8554-5b65e01839bb.png">

**Observed behavior**
The png image is missing.
<img alt="tray_missing_png" src="https://cloud.githubusercontent.com/assets/1412057/20058974/2cb26e52-a537-11e6-96e5-85446e2ee22c.png">

**Possible fixes**
Possibly the file path to the png image is wrong in the packaged app.

**Comment by yuya-oc** [comment]
Somehow `dist/resources` is not included in linux package. Probably it's bug of `electron-builder` or my mis-configuration. As an easy fix, it's applicable to rename `src/resources` to `src/assets`.

And now there are two "resources" directories, `resources` and `src/resources`. So renaming would also make sense to describe the purpose of directories.

**Comment by jasonblais** [comment]
Thanks @yuya-oc!
