### ISSUE TITLE
Write direct messages to several users

### ISSUE THREAD

**Issue by viveris-villeurbanne** [mattermost/desktop#361]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [ ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**

It would be great to write direct messages to several users. This feature is really missing.

**Comment by jasonblais** [comment]
Thanks @viveris-villeurbanne, agree it would be nice to have feature!

Mattermost has an [existing feature idea for group messaging here](https://mattermost.uservoice.com/forums/306457-general/suggestions/9920163-add-support-for-sending-message-to-multiple-users), I encourage you to upvote the feature so it can be discussed and prioritized along with the community.

Everyone gets 10 votes on the feature idea forum, influencing the future of Mattermost.

**Comment by jasonblais** [comment]
Closing the issue, we'll track it through the feature idea on the server side.

Thanks again for the feedback!
