### ISSUE TITLE
Download file in the download folder by default

### ISSUE THREAD

**Issue by MartinDelille** [mattermost/desktop#362]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**

When trying to download a file using OSX client, it ask me to save it in my harddrive root folder which is quite inappropriate (*~/Download* would be more appropriate)

**Steps to reproduce**

Configuration:
- OSX 10.11.6
- Mattermost Desktop 3.4.1
- Mattermost Server 3.4.0

Steps:
- Upload a file in a room
- Click on file to download

**Expected behavior**

The save dialog box should propose the user download folder by default (~/Download in my case)

**Observed behavior**

The save dialog box propose the harddrive root folder.

**Comment by jasonblais** [comment]
Thanks for the report @MartinDelille! 

This should be fixed with the next desktop release: https://github.com/mattermost/desktop/pull/330

**Comment by MartinDelille** [comment]
Ok thanks!

**Comment by MartinDelille** [comment]
Do you know when the next version will be released?

**Comment by jasonblais** [comment]
@MartinDelille Currently we're planning to cut a release candidate on November 30th, with an official release of v3.5 desktop app on December 14th.
