### ISSUE TITLE
Mattermost desktop client goes black when messaging someone through slash commands (Mac + Windows)

### ISSUE THREAD

**Issue by KasperJanssens** [mattermost/desktop#363]
Summary
When sending a message through the command line api (/msg) I get a black screen.

Steps to reproducte
To reproduce, just open a new private chat by typing '/msg user test'. The screen will go black and will not redraw. The message does get sent it seems, but the screen is black and the application is not usable anymore until a restart or sometimes also until opening one of the menus.

Expected behavior
Send a normal message and shows it

Observed behavior
Messages gets sent but application doesn't redraw the screen, screen goes black.

Possible fixes
NA

Mattermost server version 3.4.0
Mattermost Mac desktop client version: 3.4.1
Mattermost Windows desktop client version: 3.4.1

**Comment by jasonblais** [comment]
Thanks @KasperJanssens for the report!

I tried it on my end and it seems to be working okay. Just confirming this issue doesn't reproduce on the browser?

Also, we have a [Mattermost preview instance open to public](https://pre-release.mattermost.com/core/channels/public-test-channel), wondering if you'd like to try and see if the issue reproduces on that server too?

**Comment by KasperJanssens** [comment]
Can't reproduce in the browser no, but we can reproduce it on four different machines, two macs and two windows. Don't know what that means if you can't reproduce it on your instances, something wrongly configured on the server side? That seems a bit weird doesn't it?

I sent you a direct message on the mattermost instance for review and I don't have the issue, but like I said I don't have it on the http client.

**Comment by jasonblais** [comment]
@yuya-oc Any thoughts what might be going on?

**Comment by yuya-oc** [comment]
I tested /msg on pre-release.mattermost.com and my 3.4.0 server, but the issue didn't reproduce. As far as reading the issue, it should happen also on webapp.

@KasperJanssens To make sure, would you try `Ctrl(Cmd)+Shift+R` to refresh caches? If you had recently upgraded the server, possibly it is the reason.

**Comment by KasperJanssens** [comment]
Cleaning the caches refreshes the image, but I can't click anymore in it
then, the application is no longer responsive. The only thing we did was
follow the setup on the website to install Postgres, Mattermost and Nginx,
so it's not a docker setup or anything. We don't have the issues on the web
app but we have the issue consistently on all desktop clients. I didn't do
any update on the server, server was installed five days ago and has been
running all that time. Just downloaded a linux tarfile release from your
webiste, 3.4.0, installed on a fresh 64 bit server.

2016-11-15 14:28 GMT+01:00 Yuya Ochiai <notifications@github.com>:

**Comment by yuya-oc** [comment]
Hmm...it's weird. Is the instruction https://docs.mattermost.com/install/prod-ubuntu.html ? Please tell your exact steps if you know. I would like to setup later on virtual machines in order to reproduce.

**Comment by KasperJanssens** [comment]
Indeed these but on an ubuntu 16.04. It's a vm I think, might be that we can even share it somewhere with you guys. I followed those instructions step by step (except the ip - address of course). We do have a different config for nginx though, some options that weren't supported on the nginx in the ubuntu repos for ubuntu 16. 
```

upstream backend {
  server 10.108.56.58:8065;
}

proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=mattermost_cache:10m max_size=3g inactive=120m ;

server {
  listen 80; server_name releasemanagement.int.amplidata.com;

    location /api/v3/users/websocket {
    proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection "upgrade"; client_max_body_size 50M; proxy_set_header Host $http_host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto $scheme; proxy_set_header X-Frame-Options SAMEORIGIN; proxy_buffers 256 16k; proxy_buffer_size 16k; proxy_read_timeout 600s; proxy_pass http://backend;

  }

  location / {
    client_max_body_size 50M; proxy_set_header Connection ""; proxy_set_header Host $http_host; proxy_set_header X-Real-IP $remote_addr; proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; proxy_set_header X-Forwarded-Proto $scheme; proxy_set_header X-Frame-Options SAMEORIGIN; proxy_buffers 256 16k; proxy_buffer_size 16k; proxy_read_timeout 600s; proxy_cache mattermost_cache; proxy_cache_min_uses 2; proxy_cache_use_stale timeout; proxy_cache_lock on; proxy_pass http://backend;

  }

}
```

**Comment by jasonblais** [comment]
Hey @KasperJanssens, we just released Desktop App v3.5

Wondering if [you'd like to download the app](https://about.mattermost.com/downloads/) and see if the issue persists?

**Comment by KasperJanssens** [comment]
Seems to fix it on the Mac client, asking my colleagues to test on the Windows and Linux client as well but I expect it will be fixed. I'll close the ticket as soon as they have confirmed.

**Comment by jasonblais** [comment]
Awesome, glad to hear!

**Comment by KasperJanssens** [comment]
Works on Windows and Linux as well. Closing.
