### ISSUE TITLE
"Search in team" breaks OS keyboard shortcut conventions

### ISSUE THREAD

**Issue by filipp** [mattermost/desktop#364]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**

The "Search in team" command is using the Command-S shortcut. This is typically reserved for the "Save" command in most apps and OSs. It should be changed to Command-F, which is not used at all at the moment.

**Steps to reproduce**

Using client version 3.4.1 on OS X. Mattermost Server 3.4.0.

**Expected behavior**

Cmd-F should be Search, Cmd-S should be save (if applicable)

**Observed behavior**

Cmd-S is search, Cmd-F doesn't do anything.

**Comment by jasonblais** [comment]
Thanks @filipp for the feedback!

We originally implemented search as `CTRL/CMD + F`, but opted for `CTRL/CMD +S` given were planning to [implement a real browser-like search in the desktop app](https://mattermost.uservoice.com/forums/306457-general/suggestions/16821433-ctrl-f-performs-a-browser-like-search-in-the-deskt).

Once implemented, we'd have
 - `CTRL + F`: Browser-like "Find"
 - `CTRL + S`: Search, which autofocuses the search bar
 - `CTRL + SHIFT + S`: [Search in current channel](https://github.com/mattermost/desktop/issues/305), which autofocuses the search bar and autocompletes `in:[CURRENT_CHANNEL]`

**Comment by jasonblais** [comment]
If you'd like to see a browser-like search (`CTRL+F`) implemented, I encourage you to upvote the existing feature request: https://mattermost.uservoice.com/forums/306457-general/suggestions/16821433-ctrl-f-performs-a-browser-like-search-in-the-deskt

**Comment by jasonblais** [comment]
If you have any further thoughts, please let us know! Feedback always welcome.
