### ISSUE TITLE
Copy link button does not copy link in Windows desktop client version 3.4.1

### ISSUE THREAD

**Issue by hannu78** [mattermost/desktop#367]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**

**Steps to reproduce**
Post a link to a channel or find a posted link from a channel using desktop app, right-click on the link and select "Copy Link". Go to message writing box on the same or on different channel and right-click to Paste or use CTRL+V.  

Occurs in Windows 10 with desktop app version 3.4.1 and Mattermost Enterprise server versions 3.4.X and 3.5.0 (can't find out the older version we had).

**Expected behavior**
Link should be copied to clipboard and then be possible to be pasted to message writing box.
**Observed behavior**
Paste is disabled when trying to paste to message writing box via right-click and nothing is pasted with CTRL+V either.

**Possible fixes**
N/A

**Comment by jasonblais** [comment]
Thanks for the report @hannu78! 

This sounds similar to https://github.com/mattermost/desktop/issues/279 and https://github.com/mattermost/desktop/pull/272#issuecomment-244635083. If this issue is the same, then it should be fixed with https://github.com/mattermost/desktop/pull/306 which will be included in the 3.5 release.

**Comment by jasonblais** [comment]
Thanks again for the report, much appreciated.

Closing the issue for now as it should be fixed with Mattermost Desktop App 3.5
