### ISSUE TITLE
[Help Wanted] Add README file for Linux Desktop App

### ISSUE THREAD

**Issue by it33** [mattermost/desktop#376]
Add a simple README file for Linux Desktop App with basic instructions on how to install and use it. 

References: 
- [Desktop Install Guide](https://docs.mattermost.com/install/desktop.html)
- [Desktop User's Guide](https://docs.mattermost.com/help/apps/desktop-guide.html)

**Comment by jasonblais** [comment]
Closed via #383, thanks @yuya-oc!
