### ISSUE TITLE
Yellow border appears around clickable UI buttons in Account Settings modal

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#377]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Yellow border appears around clickable UI buttons

**Steps to reproduce**

Windows 10; Mattermost Desktop App v3.4.1, 3.5.0; Mattermost Server v3.5.0

 1. Open Account Settings by pressing CTRL+SHIFT+A
 2. Click and hold down the "x" button in top right corner of account settings modal

**Expected behavior**

No yellow border appears
![image](https://cloud.githubusercontent.com/assets/13119842/20863883/40ad65ac-b9a9-11e6-9a2b-1e18a77dc1c9.png)

**Observed behavior**

![image](https://cloud.githubusercontent.com/assets/13119842/20863858/36e5cd3a-b9a8-11e6-999b-886fa0aefaaf.png)

Other example:

![image](https://cloud.githubusercontent.com/assets/13119842/20863867/ceb5ddd0-b9a8-11e6-9ad4-3b999f771156.png)

**Possible fixes**

Maybe something similar to the fix here: https://github.com/mattermost/desktop/pull/371#issuecomment-263556036

**Comment by yuya-oc** [comment]
The point of https://github.com/mattermost/desktop/pull/371#issuecomment-263556036 is that the first tab unexpectedly gets focus.

Chrome shows blue border which is hard to see in your theme on the focused element, so the yellow color seems Electron's default style. If the blue border was the spec of webapp, it's an issue for our side.

<img width="605" alt="blue_border_in_chrome" src="https://cloud.githubusercontent.com/assets/1412057/20883982/32db98c0-bb2c-11e6-98f4-3adef3b25dee.png">

**Comment by jasonblais** [comment]
Ah interesting.

Propose we still change to the same colour, to make it consistent with the web app? Unless this can lead to other side effects,

**Comment by jasonblais** [comment]
This is not really priority since it's Electron's default style and reproduces in other Electron's apps. 

Closing the task - we can reopen it later if someone else brings it up.
