### ISSUE TITLE
Mac: Mattermost app opens in an "invisible" screen

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#378]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Mac: Mattermost app opens in an "invisible" screen

**Steps to reproduce**

Mac OS X; Mattermost Server v3.4.0; Mattermost Desktop v3.4.1

1) Connect Mac to two screens
2) Have Mattermost open on Screen 2
3) Disconnect display from Screen 2
4) Click on Mattermost icon on the dock menu

**Expected behavior**

Mattermost opens in Screen 1 (which is still open)

**Observed behavior**

Mattermost opens in Screen 2 (which is invisible)

**Comment by jasonblais** [comment]
An issue with the above description was reported -- wondering if others in the community have noticed this or are able to reproduce?

If you're able to reproduce, can you also help:
1) Launch "System Preferences" from "Launchpad"(application list).
2) Select "Displays".
3) Select "Show mirroring options in the menu bar when available"

and see if it also reproduces when the mirroring option is selected in Mac display settings.

![image](https://cloud.githubusercontent.com/assets/13119842/20868145/3443cdfa-ba22-11e6-9ff3-3bf73331a8ed.png)

**Comment by jnugh** [comment]
I was able to reproduce this on Linux (Unity) and wrote a PR that fixes it for me :) https://github.com/mattermost/desktop/pull/386

**Comment by yuya-oc** [comment]
I confirmed the test case of #386 with v3.5.0 on macOS again, but the original issue didn't reproduced (I unplugged the cable instead of disabling because "disable" doesn't exist).

As far as I observed the behavior, the original behavior is a little complicated on macOS.

- Launched from Dock or Launchpad: The window opens in the monitor where Dock exists.
- Launched from Finder: The window opens at the previous position (expected behavior of source code).
  - If the monitor doesn't exist, the window position is fitted to the current monitor.

**Comment by jasonblais** [comment]
It sounds like the behaviour (from user's perspective) is correct when launched from Dock or Launchpad, but not when launched from the Finder? 

Is that correct?

**Comment by yuya-oc** [comment]
Good question. Just in my thought, both of them are correct. So I feel we can define what is correct for us.
However in my guess, the app would be launched from Dock or Launchpad in almost cases.

**Comment by jasonblais** [comment]
One more question: 

> Launched from Finder: The window opens at the previous position.

By previous position, do you mean in the screen it was previously at? But if the monitor no longer exist / is disabled, the app opens in the currently active monitor?

**Comment by yuya-oc** [comment]
In my MacBook, yes for both.
