### ISSUE TITLE
Mattermost Desktop App 3.4.1 on Windows 10 64-bit VERIFIED

### ISSUE THREAD

**Issue by tonyD-2016** [mattermost/desktop#380]
| Version | OS | Issues | Tester | Date |
| :-- | :-- | :-- | :-- | :-- |
| 3.4.1 | Windows 10 64-bit | None Observed | @tonyD-2016 | 2016-12-05 |

I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**

**Steps to reproduce**

**Expected behavior**

**Observed behavior**

**Possible fixes**

**Comment by jasonblais** [comment]
Thanks @tonyD-2016! 

Added you as a verified tester

![image](https://cloud.githubusercontent.com/assets/13119842/20906043/499935a8-bb14-11e6-9dfb-d925e1023370.png)
