### ISSUE TITLE
Mac: "Leave app running in notification center when application window is closed" setting is disabled

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#382]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**

Mac: "Leave app running in notification center when application window is closed" setting is disabled

**Steps to reproduce**

Mac OSX 10.9.5; Mattermost Server v3.5.1; Mattermost Desktop App v3.5.0-RC1

1) Go to the Settings page via **File > Settings**
2) Try to select or unselect the option "Leave app running in notification center when application window is closed"

**Expected behavior**

User can select or unselect the setting

**Observed behavior**

Setting is disabled and the checbox box can't be selected

**Possible fixes**

**Comment by jasonblais** [comment]
Candidate for 3.5.0-RC2 hotfix.

Wondering if Linux is having a similar problem with the setting.

**Comment by yuya-oc** [comment]
Closed by #385
