### ISSUE TITLE
Allow disabling chrome smooth scrolling

### ISSUE THREAD

**Issue by BotoX** [mattermost/desktop#388]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
The desktop client forces smooth scrolling and does not provide a way to disable it.
For some reason I become very dizzy when an application uses smooth scrolling and have to quit using it, so this is indeed an issue for me and not a feature request.

**Steps to reproduce**
My setup consists of:
- Archlinux
- Mattermost desktop client version 3.4.1
- Mattermost server version 3.5.1-1

Scroll in the desktop client.

**Expected behavior**
A possibility to disable smooth scrolling.

**Observed behavior**
No obvious possibility to disable smooth scrolling.

**Possible fixes**
Offer a way to visit chrome://flags inside the desktop app or provide an option in settings to disable smooth scrolling.

I'd also be very happy if I could disable it through the developer tools, config file, eg. something that is not patching and recompiling.

**Comment by yuya-oc** [comment]
Possibly Chromium's command line switches are applicable. http://peter.sh/experiments/chromium-command-line-switches/
Does `--disable-smooth-scrolling` have any effects?

**Comment by BotoX** [comment]
Yes indeed, thank you very much.
This issue can be closed if you are okay with this solution (I am).

**Comment by jasonblais** [comment]
Thanks @BotoX :)

@yuya-oc The [command line switches](http://peter.sh/experiments/chromium-command-line-switches/) seem pretty comprehensive, wondering if we should add a reference somewhere in our docs?

**Comment by yuya-oc** [comment]
@jasonblais Yeah, it would make sense.

**Comment by jasonblais** [comment]
I was reading through the list and I ended up being a bit worried about referencing it in our docs before we've had a chance to test if they work fine with the app. I worry there might be a command that causes issues that we cannot troubleshoot.

So I think for now it's okay to reference them but I won't add them to our docs yet,

**Comment by jasonblais** [comment]
Closing the issue as resolved
