### ISSUE TITLE
Unnecessary whitespace on right side of the window when shrinked to small size

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#389]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Unnecessary whitespace on right side of the window when shrinked to small size
**Steps to reproduce**

Windows 10; Mattermost Server v3.5.1; Mattermost Desktop v3.5.0 RC1

1) Shrink app window horizontally until you see a horizontal scrollbar at the bottom
2) Scroll all the way to the right

**Expected behavior**

- no horizontal scrollbar and no whitespace on the right side of the window

**Observed behavior**

![image](https://cloud.githubusercontent.com/assets/13119842/20956390/9bf4b2c4-bc17-11e6-9bba-7a7d5c42bec6.png)

**Possible fixes**

Maybe related to #371?

**Comment by jasonblais** [comment]
Propose fixing in 3.5 as it's a regression from an earlier release.

**Comment by yuya-oc** [comment]
Reproduced also on v3.4.1 on Windows 10. So #371 seems not to be related.

**Comment by jasonblais** [comment]
Ah okay - I thought it wasn't happening on an earlier version.

Since it doesn't sound like a regression, no need for a hot fix. We can fix it in a later version instead.

**Comment by yuya-oc** [comment]
Reproduced also on macOS. The point seems that the window is too narrow to show contents. In this case, Chrome limits the width to 400px, so I will add similar minimum size to the main window.
