### ISSUE TITLE
Windows - Feature Idea: "Blink" Windows Taskbar icon on new messages

### ISSUE THREAD

**Issue by i23098** [mattermost/desktop#39]
In skype, when a message is received and it doesn't have the focus, the icon on the taskbar will "blink" until the user goes to the app. I think the same behavior should be implemented (and configurable, so some people could enable it while others disable it)

**Comment by Johnich** [comment]
The better way is to show a tray icon on the bar, and show the number of unread new messages on the tray icon when new messages arrived. That will help a lot when we set the OS X Dock to auto-hide. Hope to see this new feature in the next version.

**Comment by yuya-oc** [comment]
I have understood this is issue for Windows.

@Johnich, could you make a new issue to split topic? (yours is for osx)

btw, please indicate platform to understand the point of topic. It's very helpful because I have to think about all platforms(win, osx, linux). :(

**Comment by i23098** [comment]
I had raised it with Windows in mind as I don't know if other platforms support that behavior on the icons in the taskbar. If they do, and it's easy, can't see why not implement it in all platforms. If it's only possible to implement it in Windows, then it's a Windows only request :)

**Comment by Johnich** [comment]
Got it. I will new an issue.

**Comment by lunawesley9** [comment]
Yes, we recently switched to mattermost, 10% of users complain that without blinking they can't notice new messages.

**Comment by lunawesley9** [comment]
![image](https://cloud.githubusercontent.com/assets/14857117/15045810/2f76aeb0-130f-11e6-89f8-966f56412125.png)

**Comment by MetalCar** [comment]
Currently on Windows 7 this blinking notification stuff isn't working, as I understand this right: https://github.com/electron/electron/blob/master/docs/tutorial/desktop-environment-integration.md

So, that I only has win7 on my computer, I can't really help out here :disappointed: 
Otherwise we should wait til electron add a full support for blink notifications.

**Comment by MetalCar** [comment]
Seems that this type of notification doesn't work on windows. Maybe electron isn't so far yet?

**Comment by yuya-oc** [comment]
I had thought [browserWindow.flashFrame()](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winflashframeflag) might realize this, however I have never tested this function yet.

**Comment by MetalCar** [comment]
Tried it in a quick test. You're right, it works. I will make a Pull Request to implement this.

**Comment by Razzeee** [comment]
Jep, works but maybe something we would want a setting for?

**Comment by MetalCar** [comment]
I think it's the common way to blink the icon in the taskbar when a notification show up. Every chat messenger do that.

**Comment by Razzeee** [comment]
Well slack isn't doing it.

**Comment by Razzeee** [comment]
@MetalCar 
for reference, the slack settings. afaik this is the default there:
![unbenannt](https://cloud.githubusercontent.com/assets/5943908/15780287/4b09054e-29a1-11e6-9210-54aea1552433.png)

**Comment by MetalCar** [comment]
Have some problems with the "Idle"-Setting. Is there a possibility to get how long the user is idle? Or should I build this for myself? I tried to build it for myself, using the `blur`-Event on the `BrowserWindow`. But it is fired twice :confused:

**Comment by Razzeee** [comment]
Let's just start with Never and Always, we can always expend the settings in the future.

**Comment by yuya-oc** [comment]
Sure, it seems a good way

**Comment by Razzeee** [comment]
Is merged in master, should probably be closed.

**Comment by johnnyPescarul** [comment]
On Windows 10, there is an option in settings to "Flash window when receiving a notification". The taskbar icon flashes but only 4 times (4 seconds), then it goes back to normal, and there is no way to know that you have a missed message. Can we please add an option to "Flash continuously until at least one message is read"? I love Slack, but I hate that I keep missing messages due to focusing on other work, or being away from the computer.
