### ISSUE TITLE
Ubuntu tray icon is gone after 3.5.0-rc2

### ISSUE THREAD

**Issue by thanosk** [mattermost/desktop#394]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
The tray icon for mattermost desktop app is not appearing in ubuntu's system tray (top right horizontal menu bar). Ubuntu version used: 16.04 LTS, mattermost desktop app: 3.5.0 final.

**Steps to reproduce**
Installing mattermost desktop 3.5.0 final or 3.5.0 rc3.

**Expected behavior**
Tray Icon should appear on Ubuntu's top horizontal bar

**Observed behavior**
Tray icon is not appearing in versions 3.5.0-rc3 and 3.5.0 final. Tray icon is appearing in version 3.5.0-rc2.

**Comment by yuya-oc** [comment]
v3.5.0-rc1 and rc2 had a bug where the setting for tray icon was incorrectly saved on Linux. Does reconfiguring fix the issue?

**Comment by thanosk** [comment]
Yes, reconfiguring did the trick. Actually, I think I had to reconfigure the icon theme setting (set to dark and then back to light), because previously it had an empty value string in config.json. The showTrayIcon was already set to true.
