### ISSUE TITLE
Desktop UX Improvements: App Options

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#398]
This ticket is one of three improvement tickets planned for Desktop user experience.

----

### PART 1 - All platforms

Add help text below each option in gray text, similar to the example below

![image](https://cloud.githubusercontent.com/assets/13119842/21290382/4fd989d8-c486-11e6-97dd-1404fb18b211.png)

Below is a list of app options with their corresponding help texts:

- Start app on login (Windows, Linux)
  - Help Text: Enabling automatically starts the app when you log in to your machine. The app will initially start minimized and appear on the taskbar.
  - This setting should be ON by default.

- ~~Hide menu bar (Windows, Linux)~~
  - ~~Help Text: Press Alt to show menu bar.~~
  - ~~This setting should be OFF by default.~~

- Display secure content only (Windows, Mac, Linux)
  - Help Text: Enabling allows the app to display non-secure (HTTP) content such as images. Disabling allows only secure (HTTPS/SSL) content.
  - This setting should be OFF by default.
  - NOTE: This setting is reversed from its current implementation (where selecting the option allows mixed content). If this is a lot of work to do, then we can re-word the setting and help text accordingly.

- Show red badge on taskbar icon to indicate unread messages (Windows, Mac)
  - Help Text: Regardless of this setting, mentions are always indicated with a red badge and item count on the taskbar icon.
  - This setting should be ON by default.

- Flash taskbar icon when a new message is received (Windows, Linux)
  - Help Text: Taskbar icon flashes for a few seconds when a new message is received.
  - This setting should be OFF by default.

- ~~Toggle window visibility when clicking on the tray icon (Windows)~~
  - ~~Help Text: Enabling clicking on the system tray icon allows you to toggle the window open and minimized.~~
  - ~~This setting should be OFF by default.~~

- Show Mattermost icon in the menu bar (Mac)
  - Help Text: Setting takes effect after restarting the app.
  - This setting should be OFF by default.

- Show icon in the notification area (Linux)
  - Help Text: Setting takes effect after restarting the app.
  - This setting should be OFF by default.

- Leave app running in notification area when application window is closed (Linux)
  - Enabling will leave the app running in the notification center when app window is closed.
  - This setting should be OFF by default.

### PART 2 - Mac only

- Remove “Leave app running in menu bar when application window is closed” setting, as this is not applicable to a Mac
  - This setting is causing weird behaviour on Mac and is not standard. If the option is enabled, the Mattermost dock icon gets removed when closing the app, and it hasn't been obvious to the end user how to get back to Mattermost.

### PART 3 - Windows only

- Remove “Toggle window visibility when clicking on the tray icon” setting, as it's a setting most people don't care about (we should add settings that are meaningful for at least 80% of the users)

### PART 4 - Windows AND Linux only

- Remove “Hide menu bar” setting. Enabling causes issues for users who then later forget how to display the menu bar (via Alt) or access the Settings page. There are alternate designs we can consider in the future that don't require the menu bar.

**Comment by yuya-oc** [comment]
Solved by #428
