### ISSUE TITLE
Implement CTRL+F to work as a browser-like search in the desktop app

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#399]
One key missing piece in the desktop app user experience is CTRL+F browser-like search.

There is existing electron APIs for finding something on the page: http://electron.atom.io/docs/api/web-contents/#contentsfindinpagetext-options

Wondering if someone in the community was interested looking at implementing this feature?

**Comment by Artwalk** [comment]
It's weird no one complains about 'cmd + f' can't focus on search bar on Mac.

**Comment by jasonblais** [comment]
Hey @Artwalk, 

We want it to reserve CTRL/CMD+F on the desktop app for browser-like search so the experience would be consistent with the webapp.

I understand that you feel we removed functionality in this release, which is why we're considering to add a shortcut for the webapp (which would also work on the desktop app) that sets focus on the search bar. Curious to hear if you'd have any suggestions on a good shortcut for this? Perhaps CTRL+SHIFT+S?

**Comment by Artwalk** [comment]
Oh, I see, consistent experience. the shortcut should be CTRL/CMD+SHIFT+F, then CTRL/CMD+F to work as a browser-like search.

But would you think that CTRL/CMD+F has a universal meaning which is 'find in apps'. You see,  Xcode, iTerm, Sublime.

If *search* was bound to other keys, users would get frustrated when they are going to search by pressing CTRL/CMD+F subconsciously. After all when they chose to use desktop app rather than webapp, they expect this already. Say, Safari/Chrome, CTRL+F of course search in browser(app), Mattermost, CTRL+F search in Mattermost(app).

As for Slack, they provide this in webapp:
>Cmd + F starts a Slack search
Overrides normal browser search behavior

I'm not sure which experience is better.

**Comment by jasonblais** [comment]
You raise very good points here.

It's true Slack overrides the normal browser behaviour, but that might be because [findInPage](http://electron.atom.io/docs/api/web-contents/#contentsfindinpagetext-options) was only available on Electron a year ago. So at the time when the feature was added there might not have been an easy way to add browser-like search for CTRL+F.

Good suggestion about CTRL+SHIFT+F a well. One other option for that is to view flagged posts as well :)

**Comment by fermulator** [comment]
Whatever we decide as the default, we should make it per-user configurable in their account settings. (probably needs a new "Keyboard Shortcuts" section in the "Account Settings"? - I realize now keyboard shortcuts are not configurable, and statically listed under TRIPLE_BAR -> "Keyboard Shortcuts" (or shown by CTRL+/). - maybe be out of scope ...

My initial opinion (which seemed so obvious at the time), was that the default should be CTRL+F. However I understand the concern for a seamless (consistent) experience between the user experience in a web browser, vs. the desktop application.

CTRL+SHIFT+F is a reasonable compromise (however as already stated it may conflict with displaying flagged posts as a future key-map...).
 - "F" = legacy means "find", but Mattermost labels as "Search"
 - "F" may also mean "flag"
 - "S" may map to search (but this is not intuitive to legacy computer users -- many systems use "F")

To argue against the concern (devil's advocate), who cares about consistency? IMO, for users running Mattermost within a web browser, it is acceptable that they MAY have a degraded experience when it comes to desktop interactions and other conveniences. Running the raw desktop application has numerous benefits, and is worthwhile. Accessing MM within a browser is convenient, but shouldn't be considered a permanent or fully capable use case.

**Comment by jasonblais** [comment]
@fermulator Thanks for the input! Much appreciated.

And yes, there are two kinds of "searches" discussed here, one for "finding on page", and the second for "setting focus on the Search box".

We actually had the second implemented as CTRL+S shortcut, but people were confused about it and we eventually deprecated it.

As for using CTRL+F as a shortcut for one of the two options: we have lots of users who switch between desktop app and browser, so having a consistent experience is important - particularly for CTRL+F which tends to be used quite often.

All that being said, further feedback is welcome :) I also like the user-configurable option, as people are used to different shortcuts and it would be nice to be able to set them exactly how you want.

**Comment by jasonblais** [comment]
Platform team helping with this feature.

**Comment by mcallaghan-sandvine** [comment]
In #836, it looks like (someone?) decided to go with **CTRL|CMD+F**

**Comment by yuya-oc** [comment]
Closed via #836
