### ISSUE TITLE
Images (build badges) not rendering from Gitlab authenticated team

### ISSUE THREAD

**Issue by a1fred0** [mattermost/desktop#402]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
status badge images from same server as authenticated login are not rendering 

**Steps to reproduce**
- Operating System: Windows 7 64-bit
- Mattermost Desktop App version: 3.5.0
- Mattermost Server version:  Version: 3.5.0  (3.5.1) Database: postgres

All images are served from within same network.  All URLs (including mattermost team URL) are served via http.   The build status and coverage badges from local Gitlab instance that was used to authenticate the mattermost team fail to render in desktop client.  They are perfect in full chrome browser.

Markdown for the two affected badges:  
``` md
[![build status](http://gitlab.local/group/project/badges/develop/build.svg)](http://gitlab.local/group/project/commits/develop) 
| 
[![coverage report](http://gitlab.local/group/project/badges/develop/coverage.svg)](http://gitlab.local/group/project/commits/develop)
```

### Expected behavior
Images from authenticated Gitlab server should render like they do in a Web browser:  
![image](https://cloud.githubusercontent.com/assets/15949488/21306410/c2b1dcce-c5c8-11e6-8b21-0a9cad58b337.png)

### Actual behavior
Images not rendered:  
![image](https://cloud.githubusercontent.com/assets/15949488/21306431/dd93000e-c5c8-11e6-9fb8-9fa3729c64ed.png)

**Possible fixes**
No expert - only a user. Sorry.

**Comment by yuya-oc** [comment]
Does the developer console (Ctrl+Shift+I) show any error messages?

**Comment by a1fred0** [comment]
There are no error messages in the developer console, however I have since discovered that the issue only occurs when you close the Mattermost client and re-open it.  If you log out of the active session and log back in again, everything is okay until you close the client and re-open it without re-authenticating.

**Comment by yuya-oc** [comment]
Does "close" mean just pressing "x" button at top right of window? Or "quit"(Ctrl+Q)? They are different. If it's "quit", the app might lose the session to access to gitlab in next launching. Perhaps your gitlab project is not public, so I guess that the badges doesn't render.

In this case, the app can't control the expiration of gitlab session. So please check your gitlab settings.

**Comment by a1fred0** [comment]
Close meant "Quit" (via Crtl-Q or Tray Icon: Right-click->Exit).  

I can confirm that the same behaviour is observed by closing a Chrome browser down and opening up again.  The session for mattermost is alive and no authentication is needed but the session to gitlab is lost and the (non-public) build badges are not rendered.  Therefore the issue is certainly with the mattermost backend to gitlab authentication.
