### ISSUE TITLE
Error icon instead of Mattermost icon in task bar

### ISSUE THREAD

**Issue by prakashprabhakar** [mattermost/desktop#403]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Error icon instead of Mattermost icon in task bar

**Steps to reproduce**

- Operating System: Ubuntu 16.10 (x86_64)
- Mattermost Desktop App version: v3.5.0
- Mattermost Server version: v3.5.1
Steps:

1) Launch the desktop app.
2) Minimise it tray.
3) Leave it unattended to tray.

**Expected behavior**
The mattermost icon should be intact

**Observed behavior**
Actual: The mattermost icon is turning into "Error" icon. Check the attached snapshot.

![image](https://cloud.githubusercontent.com/assets/13349934/21341538/112e084c-c6b3-11e6-8398-86e044fd344c.png)

**Possible fixes**

**Comment by yuya-oc** [comment]
It seems something wrong. As far as reading the steps to reproduce, does the icon appear correctly until you minimize the app? The icon should exist always if the feature is enabled.

**Comment by prakashprabhakar** [comment]
Yes it does. Infact I get the icon back if I click on this error icon and chose the company.

**Comment by yuya-oc** [comment]
Hmm...It's weird. The app changes the icon for notification only when new messages or mentions have been detected.

**Comment by prakashprabhakar** [comment]
Can you let me know if this app generates any logs??? I can pass it on to you...

**Comment by yuya-oc** [comment]
Unfortunately I can't. If it's generated, it appears in the command line terminal (not developer console in the main window).

**Comment by jnugh** [comment]
This is a known issue on Ubuntu 16.10 Upstream launchpad bug is this one: https://bugs.launchpad.net/ubuntu/+source/unity/+bug/1635577 and https://bugs.launchpad.net/ubuntu/+source/unity/+bug/1635625
seems like a fix has already been commited and should be available in Ubuntu propsed in a few days (which means a stable update should be available in the next weeks).

**Comment by yuya-oc** [comment]
Thanks @jnugh to let us know!

@prakashprabhakar If you still have the issue in a stable update of Ubuntu, please reopen this.
