### ISSUE TITLE
Tray icon is not shown by default

### ISSUE THREAD

**Issue by prakashprabhakar** [mattermost/desktop#404]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**

Tray icon is not shown by default

**Steps to reproduce**

- Operating System: Ubuntu 16.10
- Mattermost Desktop App version: v3.5.0 
- Mattermost Server version: v3.5.1
Clear steps to reproduce the issue:

1) Install the application for the first time
2) Ensure the folder ~/.config/Mattermost to be empty before installation (In case any previous versions were installed).
3) After installation check ~/.config/Mattermost/config.json

{
  "teams": [
    {
      "name": "xxxxxxxx",
      "url": "http://xxx.29.106.xxx",
      "index": false
    }
  ],
  "hideMenuBar": false,
  "showTrayIcon": true,
  "trayIconTheme": "",
  "disablewebsecurity": true,
  "minimizeToTray": true,
  "toggleWindowOnTrayIconClick": false,
  "version": 1,
  "notifications": {
    "flashWindow": 2
  },
  "showUnreadBadge": true,
  "lastMattermostVersion": "3.5.0"
}

**Expected behavior**

 "trayIconTheme": "" should be set to "light" by default.

**Observed behavior**

 "trayIconTheme": "" is not being set.

**Possible fixes**

**Comment by yuya-oc** [comment]
As a workaround, please configure the tray icon setting. https://github.com/mattermost/desktop/issues/394#issuecomment-267017181
