### ISSUE TITLE
App reload causes copy and save link malfunction

### ISSUE THREAD

**Issue by hannu78** [mattermost/desktop#408]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**

When reloading app, copy and save file start to malfunction
**Steps to reproduce**
Open app, then reload the app. The many times you have reloaded app, the many times you need to Copy and save file using the 2nd mouse button. Save file also opens the save file dialog as many times as you have reloaded and clicked "Save file".

OS: MAC and Windows (10 at least)
Mattermost Desktop app version 3.5.0
Mattermost server version 3.5.1 Enterprise

**Expected behavior**
Copy copies the string on first time and Save file opens save dialog at first time
**Observed behavior**
Depending on how many times you have reloaded app, you need to click Copy or Save image / file as many times. After clicking enough, Save link also opens save dialog as many times in row despite the file gets saved in 1st dialog. The Save dialog reclickings also seem to follow mouse clicks also outside MM app area. 

**Possible fixes**

**Comment by jasonblais** [comment]
@hannu78 you're an angel

This explains the issue described in #300 and #340..awesome.

Thanks! @jnugh @yuya-oc FYI

**Comment by yuya-oc** [comment]
@hannu78 Thank you for reporting! Does the issue for notification reproduce on other browsers or OS? It's different from this issue, so please open another issue and describe in detail if it's necessary.
