### ISSUE TITLE
Unread messages not properly accounted for across teams in Mattermost Server v3.6

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#409]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Unread messages not properly accounted for across teams in Mattermost Server v3.6.

This is likely a side effect of the team sidebar feature, see https://github.com/mattermost/platform/pull/4569

**Steps to reproduce**

Windows 10, Mattermost server v3.6.0-RC1, Mattermost desktop v3.5.0

1) Join at least two teams
2) Have unread messages in Team A, but no mentions
3) Switch to Team B and clear all unread messages in that team

**Expected behavior**
1) Server navigation bar bolded to indicate unread messages. 
2) Dock icon should have a red badge if "Show red badge on taskbar icon to indicate unread messages" is set to true

**Observed behavior**
Neither of the expected behaviours reproduces

![image](https://cloud.githubusercontent.com/assets/13119842/21682080/91e740d8-d320-11e6-9584-c3321b1bf95e.png)
*Contributors team has an unread message*

![image](https://cloud.githubusercontent.com/assets/13119842/21682088/9b2ed066-d320-11e6-8504-b391da2dba83.png)

**Comment by yuya-oc** [comment]
@jasonblais This feature was not assumed in past releases because the team sidebar haven't exist until v3.6. So I feel this should have "Feature" label.

**Comment by jasonblais** [comment]
Ah true, it's not really a "bug" by definition. Changed the label

**Comment by jasonblais** [comment]
Closed via #413 - thanks @yuya-oc!
