### ISSUE TITLE
Typing a double quote (") in a message after a "~" causes JavaScript errors

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#410]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Typing a double quote (") in a message after a "~" causes JavaScript errors

**Steps to reproduce**

Windows 10, Mattermost Server v3.6-RC1, Mattermost Desktop App v3.5.0

1) Type a message `~ some text followed by " text`

**Expected behavior**: No JavaScript error

**Observed behavior**

"We encountered an error searching channels" message -->"~" can be used for channel shortlinking 

![image](https://cloud.githubusercontent.com/assets/13119842/21700138/c4940632-d36c-11e6-8f51-3c3955459648.png)

![image](https://cloud.githubusercontent.com/assets/13119842/21700141/c94b6030-d36c-11e6-8c78-88580c1509ec.png)

**Comment by yuya-oc** [comment]
The error happens at inside of webview and I could reproduce this also on Windows 10, Chrome 55. Would you check again?

**Comment by jasonblais** [comment]
I just tried with RC5 and I couldn't reproduce on Chrome v55, but it did reproduce on the Desktop App again. Not sure, would there be something else I could check?

![image](https://cloud.githubusercontent.com/assets/13119842/21850899/d2aede1e-d7da-11e6-8171-b8754602e222.png)

**Comment by yuya-oc** [comment]
Here is the error of pre-release server on Chrome 55 when I typed `~ "`.

<img width="553" alt="chrome_error" src="https://cloud.githubusercontent.com/assets/1412057/21851539/d0322c36-d852-11e6-9628-27daa6ca3971.png">

In this case, ` "`(space and double-quote) is sent to the autocomplete API and http 500 is returned as the response status. Assuming that, the logic to determine the query parameter should be checked.

<img width="659" alt="autocomplete_error" src="https://cloud.githubusercontent.com/assets/1412057/21851786/f457084c-d853-11e6-8a9f-d6b53f50fc1b.png">

**Comment by jasonblais** [comment]
Hmm, okay -- I created a ticket for the platform team since it's seems to be server related then.

Ticket here: https://mattermost.atlassian.net/browse/PLT-5257
