### ISSUE TITLE
Private group visibility mismatch

### ISSUE THREAD

**Issue by igmar** [mattermost/desktop#412]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**

Private group creation / deletion is out of sync

**Steps to reproduce**

Create private group
Add user to that group
User can't see the group until the app is restarted

Please include: 
- Operating System

Windows >= 7
- Mattermost Desktop App version 

3.5.0

- Mattermost Server version 

3.5.1

- Clear steps to reproduce the issue
-->

**Expected behavior**

Be synced whenever a user is added / removed from groups, or when groups are deleted.

**Observed behavior**

Requires app restart

**Comment by jasonblais** [comment]
Thanks @igmar! Are you able to reproduce this behaviour on the browser (e.g. Chrome)? 

And does it reproduce on OS X or only on Windows?

**Comment by igmar** [comment]
Hi,

I'll check on Monday.

Igmar

**Comment by jasonblais** [comment]
Hey @igmar, curious if you were able to test it out on a browser?

**Comment by jasonblais** [comment]
We haven't received an update so we will assume that the problem is fixed or is no longer valid. 

If you still experience the problem, you're welcome to reopen this issue with the relevant information and we're happy to look into it further.
