### ISSUE TITLE
 Unread channels not properly counted on the Windows system tray icon

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#417]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

Jira ticket: https://mattermost.atlassian.net/browse/MM-14102

**Summary**
Unread teams are counted as unread channels on Windows system tray icon

A consequence of #413 

**Steps to reproduce**

1) Join two teams on the same server, TEAM A and TEAM B
2) On TEAM A, join at least two channels.
3) Switch to TEAM B
4) With another account, go to TEAM A and post a message (without a mention) in the channels from step 2

**Expected behavior**

System tray icon reads "2 unread channels"

**Observed behavior**

System tray icon reads "1 unread channel"

----

Marked as an improvement since this requires code changes not originally designed for the desktop app.

**Comment by amyblais** [comment]
Jira ticket: https://mattermost.atlassian.net/browse/MM-14102

**Comment by esethna** [comment]
Please reopen if this is still an issue
