### ISSUE TITLE
Mattermost is not starting maximized on autostart

### ISSUE THREAD

**Issue by Lehmax** [mattermost/desktop#419]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question.
- [x] This doesn't reproduce on web browsers (such as in Chrome).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Mattermost is starting as a non-maximized window, even if I maximize it before quitting. It should remember the state of the window over multiple sessions.

**Information**
- OS: Windows 10
- Mattermost version: 3.5.0 
- Mattermost Server version: 3.6.1

**Steps to reproduce**
- Use a screen at 1440p or higher
- start Mattermost
- maximize the window
- exit Mattermost
- start again

**Expected behavior**
The Mattermost window is maximized.
![how it should be](https://cloud.githubusercontent.com/assets/8298953/22113252/edd01e4c-de65-11e6-9233-eb549da0f308.PNG)

**Observed behavior**
It's not. It's nearly as big as my screen, but doesn't fill it completely.
![how it is](https://cloud.githubusercontent.com/assets/8298953/22113251/edad5b64-de65-11e6-9404-0001e1b2fdc9.PNG)

**Comment by jasonblais** [comment]
Thanks @Lehmax, confirmed on Windows 10 as well.

**Comment by yuya-oc** [comment]
Thanks, but it didn't reproduce for me on Windows 10. I tried with 2160p screen.

**Comment by jasonblais** [comment]
Hmm, it's not reproducing for me now either.. It definitely was earlier, so I'll keep an eye out for this.

@Lehmax does this reproduce for you every time when you quit, then re-open the app?

**Comment by Lehmax** [comment]
Yes, it does. I can fix it temporarily by switching to 1080p, maximizing and then reverting the resolution. After I do that, it stays maximized even if I exit. If I log off from my Windows account or restart the PC, it's minimized again.

@jasonblais what resolution are you on?

**Comment by jasonblais** [comment]
> it's minimized again

Do you mean a) minimized when the app starts (i.e. minimized to taskbar), or b) opens in window size that isn't maximized?

**Comment by Lehmax** [comment]
The latter.

**Comment by yuya-oc** [comment]
@Lehmax After exiting from the app, what about `%HOME%\AppData\Roaming\Mattermost\bounds-info.json`? Maximized state should be saved in it.

**Comment by Lehmax** [comment]
Any reference to "signing out" means signing out of my windows account to trigger autostart.

I just observed the bounds-info.json while doing different stuff.
First it was set to false. Then I maximized the window and it changed to true. After exiting and restarting it stayed true.
I signed out and opened Notepad++ immediately after logging in, but before Mattermost autostarted. It was still set to "true". After Mattermost autostarted it was "false" again until I maximized the window.
It's strange that it now stays maximized after exiting, but still fails when signing out.

`{"x":-8,"y":-8,"width":2560,"height":1400,"maximized":false,"fullscreen":false}`
This is my file, in case it helps. This is how it looks like after maximizing and triggering the autostart. It's also worth noting that resizing and exiting/signing out works. It will remember the size of the windows. Only after I maximize and sign out it will forget that it should be maximized by default.

**Comment by yuya-oc** [comment]
Thanks you for detailed information.

When using autostart, the application launches with `--hidden` flag. In this case, the maximized state was not restored. Would you confirm this build fixes the problem?

https://circleci.com/gh/yuya-oc/desktop/135#artifacts

**Comment by Lehmax** [comment]
It does. 👍

**Comment by yuya-oc** [comment]
Thanks!

**Comment by ayZagen** [comment]
@yuya-oc This issue seems still valid. Using version `5.13.0` with Windows11 24h2

`bounds-info.json`

```json
{"x":-8,"y":-8,"width":1936,"height":1056,"maximized":true,"fullscreen":false}
```
