### ISSUE TITLE
Download file should default to last used directory

### ISSUE THREAD

**Issue by fmp777** [mattermost/desktop#422]
I confirm (by marking "x" in the [ ] below): 

- [ x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [:P] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---
Every time you download a file from a chat, it defaults to the root directory (as in highest level dir). All operating systems actually have a default Download folder that could be used when no other is known, but then after a download to a user specified directory, the next download should default there as well.

Either way, shouldn't default to the root directory, since NOBODY ever wants to save files there.

**Comment by yuya-oc** [comment]
The behavior depends on platform. Just for reference, please write about your platform.

**Comment by fmp777** [comment]
Sorry about that
Version 3.4.0 (3.4.0)  OSX Sierra 10.12.2

**Comment by yuya-oc** [comment]
v3.5.0 should fix the problem. If you still have the problem, feel free to reopen this.
