### ISSUE TITLE
[Help Wanted] After using ctrl+k, an added row appears in msg box

### ISSUE THREAD

**Issue by rholmboe** [mattermost/desktop#426]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**

Linux: After using ctrl+k, an added row appears in msg box

**Steps to reproduce**

Please include: 
- Operating System: 
Linux/Ubuntu 16.10
- Mattermost Desktop App version: 
3.5.0
- Mattermost Server version 
3.6.0
- Clear steps to reproduce the issue
In a channel, use ctrl+k to search for another channel and press enter, "write a message..." msg box adds another row in it.

**Expected behavior**
One-row msg box with focus() for direct writing.

**Observed behavior**
Dual-row msg box with focus() appears, and either first or second row is in focus.

**Possible fixes**

**Comment by jasonblais** [comment]
Thanks @rholmboe for the report!

Does this reproduce on the Chrome browser? Would you have a sample screenshot to share?

**Comment by rholmboe** [comment]
@jasonblais This doesn't reproduce on a Chrome browser. Sadly I cant share a sample without displaying sensitive information. But the fault is very easy to reproduce. Activate search by using ctrl+k, type in your wanted channel and press enter twice, one for select channel in search box and one to press "switch" button.

I just found out that it doesn't reproduce when using mouse to click on "switch" in the search box tho. So it should be limited for when using enter to switch channel within the search box.

**Comment by jasonblais** [comment]
Ah yes, I'm able to reproduce it on Windows 10 as well. Thanks for the report!

**Comment by rholmboe** [comment]
No worries, glad I could help. Awesome product, keep the good work up :)

**Comment by yuya-oc** [comment]
@jasonblais I feel this issue was fixed by upgrading Electron in #459. Would you confirm with the latest build? https://circleci.com/gh/mattermost/desktop/909#artifacts

**Comment by jasonblais** [comment]
You're correct @yuya-oc, I'm not longer able to reproduce it on the latest build

**Comment by yuya-oc** [comment]
Thanks for testing. I will update the changelog.
