### ISSUE TITLE
Cannot Back Out of "Choose a Team" Screen

### ISSUE THREAD

**Issue by seanodell** [mattermost/desktop#432]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Cannot back out of team selection to enter another server/team path.

**Steps to reproduce**

1. Pick a server on which you are not part of any team
2. Pick a team and fail to log into it
3. Try to change to another server to log into a team you are part of

**Expected behavior**

I expect to be able to change server at any point.

**Observed behavior**

I'm stuck at the Choose a Team/Create a Team screen. I'm unable to back up to enter in a different server.

I'm not 100% sure how I started down the path to get to the Choose a Team screen because I can't go back (I can't reproduce because I'm stuck at this one screen and can't go anywhere).

Note: I can edit the server settings to get this straightened out. Reporting an issue with the UI, not that I'm blocked.

**Possible fixes**

Add a link to go back up a step.

**Comment by jasonblais** [comment]
Hey @seanodell, thanks for the note.

If you go to File > Settings, you'll be able to update your server information (either edit existing or add a new one).

With #415 you'll also be able to add a new server from the server tab bar, to make that experience better.

**Comment by jasonblais** [comment]
> Note: I can edit the server settings to get this straightened out. Reporting an issue with the UI, not that I'm blocked.

Sorry, I missed this note on my first read.

Any suggestions on how we would make it easier to edit server information on the UI?

**Comment by jasonblais** [comment]
@seanodell We've made an update on the Mattermost server side where you should be able to go back from the "Choose a Team" screen to the previous page in the webview.

Hopefully this will help in the future,
