### ISSUE TITLE
Extend clickable area of individual app options on the Settings page

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#434]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**

**Steps to reproduce**

Windows 10; Mattermost Desktop v3.5; Mattermost Server v3.6.2
1) Go to File > Settings and click on any of the existing Settings

**Expected behavior**
The clickable area should 
 1) have equal width across the app options [consistency]
 2) be slightly wider than the longest app option text, so the user is less likely to accidentally mis-click outside of the clickable area [forgiving]

![image](https://cloud.githubusercontent.com/assets/13119842/22866860/c1c0f842-f14a-11e6-8a12-27cc3a338e23.png)

NOTE: The clickable area should never extend beyond the section divider line between Server Management and App Options.

![image](https://cloud.githubusercontent.com/assets/13119842/22866905/6bec439e-f14b-11e6-95c0-37ba3120ad54.png)

**Observed behavior**

Clickable area is independent for each app option and can be easily mis-clicked if clicking next to the option text.
![image](https://cloud.githubusercontent.com/assets/13119842/22866830/48f187ba-f14a-11e6-926d-7c2bc53bf964.png)

**Comment by yuya-oc** [comment]
Solved by #428
