### ISSUE TITLE
Desktop notification doesn't disappear if you lock the screen while notification is visible

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#437]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Desktop notification doesn't disappear if you lock the screen while notification is visible

**Steps to reproduce**

Windows 7 & 10 / Mattermost Desktop v3.5.0 / Mattermost Server 3.6.2

1) Receive a desktop notification from someone
2) While the desktop notification is shown, lock the screen (e.g. WIN+L shortcut)

**Expected behavior**

Desktop notification disappears and isn't shown on lock screen

**Observed behavior**

Desktop notification persists and doesn't disappear from the lock screen until after some time.

**Comment by yuya-oc** [comment]
I think it's not applicable for Windows 7 and it seems that's Window's normal behavior.

I created a toast notification with [Notifications Visualizer](https://docs.microsoft.com/en-us/windows/uwp/controls-and-patterns/tiles-and-notifications-notifications-visualizer), then locked the screen. As the result, the notification didn't disappear from the lock screen for few seconds.

**Comment by jasonblais** [comment]
If the desktop notification is visible, we cannot "remove" it when the screen is locked similar to Chrome notifications?

**Comment by yuya-oc** [comment]
I could remove notifications by clicking it or its "x" button on the lock screen.

I think Chrome's notifications never appear on the lock screen because Chrome uses its own notification system rather than Windows' notifications.

**Comment by jasonblais** [comment]
Thanks @yuya-oc! Sounds good

Given this is default Windows system behaviour and there isn't much we can do on our end, I'll close it. I was able to reproduce it with other apps that use a Windows notification system as well.
