### ISSUE TITLE
"X" in top right corner of Settings page doesn't have an on hover effect

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#439]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
"X" in top right corner of Settings page doesn't have an on hover effect

**Steps to reproduce**

Windows 10; Mattermost Server 3.6; Mattermost Desktop 3.5
1) Go to File > Settings
2) Hover over the "X" in top right corner

**Expected behavior**
On hover effect following [Mattermost UX guidelines](https://docs.mattermost.com/developer/fx-guidelines.html#display-button-states).

This can be similar to the on hover effect of the "+" icon in desktop server tab bar.

**Observed behavior**

No on hover effect

**Comment by wvds** [comment]
@jasonblais I've made a small PR where the color of the icon changes to the same color as the "add server" icon. In my opinion that is the nicest solution :)
