### ISSUE TITLE
Clicking a server name from system tray icon while on the Settings page does nothing

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#443]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Clicking a server name from system tray icon while on the Settings page does nothing

**Steps to reproduce**

Windows 10; Mattermost Desktop v3.6-RC1; Mattermost server v3.6.2

1) Go to File > Settings
2) Right-click the system tray icon and click one of the servers

**Expected behavior**

Page for the selected server opens.

**Observed behavior**

No action

Note: Reproduced on desktop app v3.5 as well

**Comment by yuya-oc** [comment]
Closed via #444
