### ISSUE TITLE
Windows 7: Scrolling the Mattermost Access History dialog breaks

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#445]
I confirm (by marking "x" in the [ ] below): 

- [ ] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [ ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**

**Steps to reproduce**

Windows 7; Mattermost Desktop v3.6.0-RC1; Mattermost Server v3.6.2

1. Go to Account Settings -> Security -> View Access History
2. Scroll the modal

**Expected behavior**
Modal scrolls successfully

**Observed behavior**
Dialog breaks, see attached
![image](https://cloud.githubusercontent.com/assets/13119842/23176359/9bc50e0c-f830-11e6-8145-35397378de59.png)

**Comment by jasonblais** [comment]
^this seems to happen with Account Settings -> Security -> View and Logout of Active Sessions modal as well

**Comment by yuya-oc** [comment]
Reproduced on Chrome 56.

Steps:

1. Go to `Account Settings -> Security`
2. Reduce window width to use mobile layout of webapp
3. Click `View Access History` or `View and Logout of Active Sessions`
2. Scroll the modal

**Comment by jasonblais** [comment]
Ah okay, I created a ticket for the platform team: https://mattermost.atlassian.net/browse/PLT-5622

Thanks @yuya-oc
