### ISSUE TITLE
Windows/Linux: Title bar flashes for each new message if "Flash taskbar icon when new message is received" is enabled

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#447]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

*Summary*:

Windows/Linux: Title bar flashes for each new message if "Flash taskbar icon when new message is received" is enabled

**Steps to reproduce:**

Windows 10; Mattermost Desktop 3.6-RC1; Mattermost Server 3.6.2

1) Go to File > Settings
2) Enable "Flash taskbar icon when new message is received"
3) Go back to a server page
4) Receive a message

**Expected behavior**
Taskbar icon flashes on new messages.

**Observed behavior**

Taskbar icon flashes on new messages. TITLE BAR flashes as well.

**Comment by yuya-oc** [comment]
It's correct behavior at least on Windows. We are merely using [`win.flashFrame()`](http://electron.atom.io/docs/api/browser-window/#winflashframeflag). But due to function name, possibly we might have to modify the option's description.

**Comment by jasonblais** [comment]
Closed by #452
