### ISSUE TITLE
[Help Wanted] JavaScript error after refreshing the app

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#448]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
JavaScript error after refreshing the app

**Steps to reproduce**

1) Open the Developer console from View > Toggle Developer Tools, then choose "Console"
2) Refresh the app

**Expected behavior**
No JavaScript error

**Observed behavior**

![image](https://cloud.githubusercontent.com/assets/13119842/23215451/6d84c158-f8e0-11e6-927b-20c918e3a5f4.png)

**Possible fixes**

This would be gone by removing initial `nodeIntegration` attribute from webview. It's unknown, so reported as warning by React. Existing tests would check whether node integration is correctly disabled.

**Comment by yuya-oc** [comment]
Closed via b1d586e9da3b8eba958d2ca855d4b679adf8d5f7
