### ISSUE TITLE
 JavaScript error after going to the Settings page

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#449]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

Jira ticket: https://mattermost.atlassian.net/browse/MM-14101

**Summary**
JavaScript error after going to the Settings page

**Steps to reproduce**

1. Open the Developer console from View > Toggle Developer Tools, then choose "Console"
2. Go to File > Settings

**Expected behavior**
No JavaScript error

**Observed behavior**
![image](https://cloud.githubusercontent.com/assets/13119842/23215519/af7600e0-f8e0-11e6-836b-c1d25ed6b9d1.png)

**Possible fixes**

It's shown because our components are not completely stateless.

Might be tricky to fix.

**Comment by amyblais** [comment]
Jira ticket: https://mattermost.atlassian.net/browse/MM-14101

**Comment by aswathkk** [comment]
I'm not able to reproduce this issue in MacOS.

**Comment by esethna** [comment]
No Longer Valid
