### ISSUE TITLE
Feature request: show tray icon and unread new message badge on OS X menu bar.

### ISSUE THREAD

**Issue by Johnich** [mattermost/desktop#45]
Should show a tray icon on the bar, and show the number of unread new messages on the tray icon when new messages arrived. That will help a lot when we set the OS X Dock to auto-hide. Hope to see this new feature in the next version.

**Comment by sinky** [comment]
:+1: same for Windows tray
and a option to hide the taskbar icon (see https://github.com/yuya-oc/electron-mattermost/pull/43)

**Comment by jmreynolds** [comment]
:+1: 

Let me know if you want me to resubmit any of my pull request (#46)

**Comment by Johnich** [comment]
Yes it's just a request, hope @yuya-oc or you guys or someone else can code it ;)

**Comment by yuya-oc** [comment]
I think OS X menu bar is too small to show the number. So I'm thinking about the way to indicate it.
In Windows, I could use colored dot, but OS X requires a template image (black only). Do you have any ideas?

**Comment by Johnich** [comment]
Numbered badge on the menu bar icon is acceptable. As I know there are some other apps have supported this feature by using small size font for the badge, that looks nice, almost a native style.

**Comment by yuya-oc** [comment]
Are there any example screenshots? I want to know how size is nice.

**Comment by Johnich** [comment]
Will do it when I am back to my computer later :)





On Fri, Feb 26, 2016 at 6:02 AM -0800, "Yuya Ochiai" <notifications@github.com> wrote:












Are there any example screenshots? I want to know how size is nice.

**Comment by nItroFreeZer** [comment]
Menu bar icon would be very nice! +1
@yuya-oc Here is a screenshot of Telegram on OS X (original size, non-retina, full-hd)

![bildschirmfoto 2016-03-03 um 09 25 09](https://cloud.githubusercontent.com/assets/1172623/13488659/e8672a68-e122-11e5-95d3-6c74df749f5f.png)

**Comment by yuya-oc** [comment]
Thank you, @nItroFreeZer . Do you know about two-digit number?

**Comment by nItroFreeZer** [comment]
@yuya-oc Here is a new screenshot with the number 20.

![bildschirmfoto 2016-03-03 um 14 09 40](https://cloud.githubusercontent.com/assets/1172623/13495295/2baec796-e14a-11e5-9e1f-576c972ab92a.png)

**Comment by acidicX** [comment]
:+1: for the same on Linux. I'd be fine with the red/green dot indication that Slack uses :)

**Comment by nItroFreeZer** [comment]
@yuya-oc This might help: https://github.com/cadecairos/electron-mattermost/commit/c1ea367723f80974de21051cf89bb6262a78ff6f

**Comment by yuya-oc** [comment]
Practically it has no effect yet. `src/main.js should receive message via `ipc` like `win32-overlay` in order to change icon.

**Comment by nItroFreeZer** [comment]
I moved the feature request to [mattermost's feature idea forum](https://mattermost.uservoice.com/forums/306457-general/suggestions/12892620-mac-desktop-add-menu-bar-icon-and-show-unread-new).

@Johnich @sinky @jmreynolds @acidicX: If this is still a priority for you, please upvote the request in mattermost's feature idea forum and add / move your comments.

**Comment by teetrinkers** [comment]
I implemented the tray functionality for matterfront (https://github.com/lloeki/matterfront/pull/81) and can port it to mattermost desktop, if that's ok with you.

**Comment by yuya-oc** [comment]
If it's ok the icon is the same as Windows, I can add it very easily in fact.

Unread: ![tray_unread](https://cloud.githubusercontent.com/assets/1412057/13847118/cfdb9908-ec8e-11e5-971d-2f54b708da51.png)
Mention: ![tray_mention](https://cloud.githubusercontent.com/assets/1412057/13847121/d1881506-ec8e-11e5-9cb5-d3b622c5e224.png)

Then, this is my experiment. How do you think?

Normal: ![tray_osx](https://cloud.githubusercontent.com/assets/1412057/13847193/4033e9b2-ec8f-11e5-835e-3d40ccb93dbd.png)
Dark: ![tray_osx_dark](https://cloud.githubusercontent.com/assets/1412057/13847194/40363e06-ec8f-11e5-9248-0f7aa7d63894.png)

**Comment by nItroFreeZer** [comment]
@yuya-oc Great! :+1:

**Comment by teetrinkers** [comment]
Nice.

**Comment by yuya-oc** [comment]
At least, I think there should be the way to know whether the message is "mention" or "unread".

**Comment by yuya-oc** [comment]
So as @teetrinkers said, the count might not be necessary.

**Comment by nItroFreeZer** [comment]
@yuya-oc In my opinion the count is nice to have, not must have.

I added a second team and found out that the unread marker (on Dock icon) only appears if a new message arrives in the current active team. (OS X)

**Comment by lloeki** [comment]
Please make sure this is an option, as I like my menubar to be uncluttered and free of distractions.

**Comment by yuya-oc** [comment]
Now, I will able to add the icon. But it seems that it's hard to support the counting in Retina environment. Dynamically-generated images are not correctly assigned as 2x images.

<img width="94" alt="screenshot 2016-04-04 at 11 22 37" src="https://cloud.githubusercontent.com/assets/1412057/14251196/cf19254e-fabc-11e5-8b6c-30e1ece9388b.png">

**Comment by nItroFreeZer** [comment]
@yuya-oc Counting is not so important.

**Comment by xeno-by** [comment]
Hi everyone! What's the current status of this feature? I can't seem to be able to find it in 2.5.2.

**Comment by jasonblais** [comment]
@xeno-by Which desktop app version are you running? We haven't released v2.5.2

**Comment by xeno-by** [comment]
v2.5.2: https://www.dropbox.com/s/7zssczcsq2mju98/Screenshot%202017-03-28%2018.20.03.png?dl=0

**Comment by jasonblais** [comment]
Looks like it might be the Slack desktop app @xeno-by 

If you're using the app to run a Mattermost instance, we recommend downloading the [Mattermost desktop app](https://about.mattermost.com/downloads/) to get the best user experience.

**Comment by xeno-by** [comment]
Oops, I came here via google and figured that you guys are somehow related. Sorry for the trouble!

**Comment by jasonblais** [comment]
no worries! 👍

**Comment by harryi3t** [comment]
Is this released? Can't find it.
Using the native app on mac.

**Comment by nItroFreeZer** [comment]
@harryi3t Yes. Press <kbd>cmd</kbd>+<kbd>,</kbd> and enable the option.

**Comment by FERMarkSA** [comment]
@harryi3t is it only in the paid version? If not, can you post a shot of where to enable once in prefs?

**Comment by besil** [comment]
Can't find the option in the Notifications menu on Telegram mac os native app (downloaded via app store, not the Desktop version).
Am I missing something?

![image](https://user-images.githubusercontent.com/7081486/35776619-18410982-09a0-11e8-8bc0-36afd4976f22.png)

**Comment by jasonblais** [comment]
@besil If you go to the Mac Desktop App, choose "Mattermost" > "Preferences", there is an option to `Show Mattermost icon in the menu bar`

![image](https://user-images.githubusercontent.com/13119842/35783131-8f369e8c-09d0-11e8-89b2-6761484901b5.png)

Let me know if you can't find it.

**Comment by nItroFreeZer** [comment]
@besil This is neither Telegram Desktop nor Telegram Mobile, this is about Mattermost Desktop.

**Comment by besil** [comment]
Sorry, my fault.
I came here googling Telegram notification bar, I didn't notice this was about mattermost.

Thanks! Sorry for the misleading question :(
