### ISSUE TITLE
"Help" below message box does nothing

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#450]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
"Help" below message box does nothing

**Steps to reproduce**

Windows 10; Mattermost Desktop v3.6.0-RC1; Mattermost Server v3.6.2

1. Click on "Help" below the text box

**Expected behavior**
A local copy of help text opens in a new window, with title "Messaging Basics"

**Observed behavior**
No action

**Comment by jasonblais** [comment]
@yuya-oc not sure if something easy to fix for 3.6

**Comment by yuya-oc** [comment]
It's easy to fix. It was introduced by f8fadcb8446001bf9b303bf086b4ac01d7fd7e8d because Electron's `window.open()` inherits `show: false` option from the main window.

**Comment by jasonblais** [comment]
Thanks @yuya-oc, sounds good, let's aim to fix it for 3.6 then

**Comment by jasonblais** [comment]
Fixed by #453, thanks @yuya-oc!
