### ISSUE TITLE
Give a more graceful error page when the app renderer process crashes

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#455]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**

Give a more graceful error page when the app rendered process crashes

**Steps to reproduce**

Mac v10.9.5; Desktop App v3.6.0-RC1; Mattermost Server 3.6.2

There are no specific reproduction steps, this occurred once when the app page renderer crashed on both the app and on the webapp

**Expected behavior**

Electron(Chrome)'s renderer-process crashes with the app providing an appropriate error page.

See below for an example from Chrome

![image](https://cloud.githubusercontent.com/assets/13119842/23335694/99533292-fb88-11e6-8f11-6de88b0ff1d0.png)

**Observed behavior**

Electron(Chrome)'s renderer-process crashes and you end up with a blank screen.

![image](https://cloud.githubusercontent.com/assets/13119842/23335695/a171deb0-fb88-11e6-97c2-5826e76713d4.png)

**Comment by jasonblais** [comment]
Adding `More Information Needed` label as we don't have a design for the error page yet for someone to implement.

**Comment by amyblais** [comment]
Ticket: https://mattermost.atlassian.net/browse/MM-14072
