### ISSUE TITLE
Settings not saved when changing tray icon theme

### ISSUE THREAD

**Issue by CromFr** [mattermost/desktop#456]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Settings not saved when changing tray icon theme

**Steps to reproduce**

- Operating System: __Archlinux__
- Mattermost Desktop App version __3.6.0__
- Mattermost Server version: __3.6.0  (3.6.2)__
- Clear steps to reproduce the issue
  - Go to file/settings
  - Try to change the tray icon theme

**Expected behavior**

"Settings saved" toast, and settings effective & saved (after restarting mattermost-desktop)

**Observed behavior**

Tray icon theme is still on the last value set.
Also, if you change another setting after changing the tray icon, everything works as expected

**Possible fixes**

maybe the save settings callback is not called with radio buttons?

---

_nice issue template btw :)_

**Comment by jasonblais** [comment]
@yuya-oc can you help take a look? Potentially a critical bug

**Comment by yuya-oc** [comment]
@CromFr Thanks for feedback. Yeah, auto-saving is missing in callback of radio buttons as you mentioned. So we need to fix.

**Comment by jasonblais** [comment]
To confirm, does this mean we should do 3.6.1 for Linux?

Is it **only** for the theme setting change?

**Comment by yuya-oc** [comment]
@jasonblais Ah, I didn't think about that.

As far as I read the codes again, only theme doesn't start auto-saving. As reported in original observed behavior, fortunately the theme is saved by changing another app option. So I feel we **can** cut v3.6.1.

**Comment by jasonblais** [comment]
I'm not really familiar with the Linux UI - how common is it to change the theme option?

It sounds like it might be a one-time change, for which there's a workaround for now (changing another app option). So I'm not sure it warrants a v3.6.1, although we should fix it for v3.7 of course.

**Comment by jasonblais** [comment]
Closed by #465, thanks @CromFr and @yuya-oc!
