### ISSUE TITLE
Use power-monitor API to re-load the app after computer wakes from sleep

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#461]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Use [power-monitor](https://github.com/electron/electron/blob/master/docs/api/power-monitor.md) API to re-load the app after computer wakes from sleep.

This should help with missing messages reported by people when the wake their computer from sleep.

**Comment by yuya-oc** [comment]
@jasonblais To make sure, would you check webapp's behavior in this case? I'm afraid there are missing messages in web browsers.

**Comment by jasonblais** [comment]
This isn't an easy-to-solve solution on the webapp because we are limited by what the browser tells us and have no access to operating system events that would normally make this trivial. 

However, if the app reloads after the computer wakes from sleep, we can be more certain that messages shouldn't be missing on the desktop app.

As a note, the people who reproduced the issue could do it on v3.6 but not v3.4.1 (of the desktop app), and we're running on the same Mattermost server (v3.6.2 at the time).

**Comment by yuya-oc** [comment]
Ah, thanks. Probably I confused with online/offline-events. But the computer might be offline when it wakes from sleep, so I will take care about this case.

> on v3.6 but not v3.4.1

Separately, it's a little weird :(

**Comment by jasonblais** [comment]
Since Mattermost Server v3.8, there haven't been issues with missing messages after this PR on server side: https://github.com/mattermost/platform/pull/5907

Closing the issue
