### ISSUE TITLE
OS X client doesn't integrate with native system text services

### ISSUE THREAD

**Issue by ostrain** [mattermost/desktop#463]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
OS X client doesn't integrate with native system text services.

**Steps to reproduce**

- Operating System: Mac OS X 10.11.6
- Mattermost Desktop App version: 3.6.0
- Mattermost Server version: Not sure, but this is purely a client issue

**Steps to reproduce**

Select some text either in the chat history or in the chat input box and right click.

**Expected behavior**

In all other OS X apps, including Chrome, a variety of standard system services will be available to use with the selected text. For example, looking up the selected word in the dictionary or searching for it on the web. Users can also install custom text services systemwide.

**Observed behavior**

Instead of these standard options being available, only cut/copy/paste operations appear in the context menu.

**Notes**

The missing functionality goes beyond the context menu -- these standard operations can also be triggered via keyboard shortcuts or multitouch gestures in some cases.

This seems related to https://github.com/mattermost/desktop/issues/225

**Comment by jasonblais** [comment]
Thanks @ostrain - we currently use an [electron-context-library](https://github.com/sindresorhus/electron-context-menu) to display the context menu.

Apart from having a dictionary (which will be added with #225, hopefully soon) and Google search, are there additional options you're missing?

PS: @yuya-oc @jnugh I'm not sure if there are alternate libraries available we could explore?

**Comment by yuya-oc** [comment]
I feel there no alternatives. UI is not consist from native code (at least in our side), so basically os-level integration is not easy.

Search:
I'm not sure how I can use it in Objective-C, but we can use a hard-coded query, `https://google.com#q=<TEXT>` as a workaround.

Dictionary:
Probably we can use Electron's [`webview.showDefinitionForSelection()`](https://electron.atom.io/docs/api/webview-tag/#webviewshowdefinitionforselection-macos). But it doesn't work for me (https://github.com/electron/electron/issues/8905). On the other hand, I could use three-finger tap to show this on the latest build.

Custom services:
I'm not sure what services can be installed on Mac. @ostrain would you provide an example?

**Comment by yuya-oc** [comment]
There is an implementation, `services` role of MenuItem. But it's not correctly working with webview.

https://electron.atom.io/docs/api/menu-item/#new-menuitemoptions
https://github.com/electron/electron/issues/7260

**Comment by ostrain** [comment]
@ jasonblais: Sorry for the long delay in replying. I use several custom text services that I've defined myself (for example, I use one that lets me select some text that contains one or more JIRA bug IDs, press a keyboard shortcut I've defined, and open those bugs in my browser -- it's a small python script that I wrote). It works in essentially every other app on my Mac including other webview-based apps like Slack and HipChat, so it would be great to have it working in Mattermost too.

**Comment by jasonblais** [comment]
Thanks for the feedback! We actually heard about a similar use case with Jira tickets.

I think the `services` role that Yuya linked above for menu items would work here, but we'll need to have it fixed upstream by Electron first: https://github.com/electron/electron/issues/7260

**Comment by sanfords** [comment]
I just upgraded to 3.7.0 of the Mac desktop app.  Spell check and command-shift-d-hover work now.  I don't see any text services, but it could be me.

**Comment by ostrain** [comment]
Just for reference, here's the actual service I was talking about: https://github.com/ostrain/the-talon

**Comment by yuya-oc** [comment]
After quick investigation, it seems that electron v3 or v4 will solve this issue (tested on the current master branch: electron/electron@ccd63b5ed0e583596c97dbe24c7f42572f9a6bbe).

**Comment by amyblais** [comment]
Closing via feature request ticket here: https://mattermost.uservoice.com/forums/306457-general/suggestions/36827626-have-os-x-client-integrate-with-native-system-text.
