### ISSUE TITLE
 JavaScript error after adding server via the "+" icon

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#468]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

Jira ticket: https://mattermost.atlassian.net/browse/MM-14100

**Summary**
JavaScript error after adding server via the "+" icon

**Steps to reproduce**

1. Click the "+" icon in server tab bar
2. Add name and URL, then click "Add"

**Expected behavior**
No JavaScript error

**Observed behavior**
![image](https://cloud.githubusercontent.com/assets/13119842/24002488/44f74b1c-0a37-11e7-98c7-eb717242deb8.png)

**Comment by amyblais** [comment]
Jira ticket: https://mattermost.atlassian.net/browse/MM-14100

**Comment by devinbinnie** [comment]
Closed in JIRA as Invalid.
