### ISSUE TITLE
Don't show notification if app is in focus

### ISSUE THREAD

**Issue by mkozakov** [mattermost/desktop#47]
If app is open and in focus, a notification should not be displayed.

**Comment by yuya-oc** [comment]
Why do you think so? I think current behavior follows that of web browsers.

**Comment by i23098** [comment]
I think the behavior should follow that of desktop applications ;) Skype won't show notifications if you're on the app (it does show the username in bold, with unread messages).

**Comment by espro** [comment]
Can this be reconsidered? I am not a fan of this behaviour either. Notifications are intrusive/distracting and are meant to draw your attention to them. If you have the window focused, what's the point? This is how the HipChat app behaves for example, no notification when the window has focus.

**Comment by yuya-oc** [comment]
First, I want notifications always even if the window is focused. At least this behavior should be optional.
By the way, in this case, I can understand the reason for the active tab. But how should unfocused tabs work?

**Comment by i23098** [comment]
Optional is always good.

In skype, you get the new message sound (configurable), the person name changes font (bold a different color), but the notification popup does not show up. I think it's good like that.

**Comment by mcfedr** [comment]
Maybe show notifications for other channels?

**Comment by timroes** [comment]
Also, maybe part of this issue, you get thousand of notifications on your mobile device, if you having a private chat with someone on desktop. Also the mobile notifications won't be cleared when the messages are read on any other device, causing your notification area on mobile to be filled with *already read* notifications.

**Comment by Razzeee** [comment]
Likely mobile app specific.

**Comment by jasonblais** [comment]
Thanks @timroes! Mattermost provides an option to configure which types of messages should send a push notification on mobile. You can find this setting in **Main Menu > Account Settings > Notifications > Mobile push notifications**.

As for your second piece of feedback, Mattermost currently doesn't support clearing push notifications on mobile notification area after they've been read on web or the desktop app.

If you'd like to suggest it as a feature idea, I encourage you to submit your idea to the [Feature Idea forums](https://mattermost.uservoice.com/forums/306457-general) so it can be discussed, upvoted and prioritized by the Mattermost team.

**Comment by jasonblais** [comment]
A pull request has been submitted on the server side, which will disable notifications when actively viewing a channel https://github.com/mattermost/platform/pull/4216 - I believe this will partially cover the suggested improvement.

If there are further suggestions, I encourage you to submit the idea to the [Feature Idea forums](https://mattermost.uservoice.com/forums/306457-general) so it can be discussed, upvoted and prioritized by the community.
