### ISSUE TITLE
Review README.md and CONTRIBUTING.md files

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#472]
Review README.md and CONTRIBUTING.md files

Creating an issue for @jasonblais to review the two files and update where needed

1) README should really be for developers looking to contribute, and install guides, feature lists, etc. 
2) contribution guidelines way out of date and missing a note about testers. Could base it off of platform contribution guidelines: https://github.com/mattermost/platform/pull/5455

**Comment by jasonblais** [comment]
Sorry @yuya-oc, I unfortunately won't have time to finish this up for end of this week..

I've started doing some research though, and added a few references below. 

https://github.com/mattermost/platform/pull/5455
https://github.com/mattermost/desktop/pull/350/files
https://github.com/nodejs/node
https://github.com/nodejs/node/blob/master/COLLABORATOR_GUIDE.md#landing-pull-requests
https://github.com/EionRobb/purple-mattermost

**Comment by yuya-oc** [comment]
As mentioned at https://github.com/mattermost/desktop/pull/637#discussion_r147594929, we should also consider to define how changelog should be written. Currently "issues" are listed trailing to the sentence, but "pull requests" are not.

**Comment by philip-peterson** [comment]
Just for cross-referencers' sake, I was also suggesting back there that some distinction be made between PR number indicators and Issue number indicators (perhaps `PR #4` and `Issue #4` as a convention). Right now when you see `#34` in the changelog it could mean either PR #34 or Issue #34.

**Comment by amyblais** [comment]
Jira ticket: https://mattermost.atlassian.net/browse/MM-14062.
