### ISSUE TITLE
 Main window unresponsive when brought back from command line.

### ISSUE THREAD

**Issue by michaelcadilhac** [mattermost/desktop#473]
**Summary**
When the main window is closed but the app is not (normal tray icon behavior), bringing back the window with `xdotool`, `wmctrl`, etc. results in an unresponsive or blank window.

**Steps to reproduce**
Start the app, with systray and "leave app running" checked.  Close the window.  Execute:
` xdotool search --class mattermost windowmap `

On: Arch Linux using Awesome as the WM, and the git mattermost-desktop.

**Expected behavior**
Show the window, be able to interact with it.

**Observed behavior**
This brings the window alright, but it is blank or unresponsive.  One needs to minimize and unminimize it to gain back control.

**Possible fixes**
`xdotool` can be used to minimize and unminimize the window, but this is more of a temporary fix.

**Comment by amyblais** [comment]
Ticket for tracking: https://mattermost.atlassian.net/browse/MM-14130

**Comment by amyblais** [comment]
Ticket for tracking: https://mattermost.atlassian.net/browse/MM-14132

**Comment by devinbinnie** [comment]
JIRA ticket was closed
