### ISSUE TITLE
More informative “About this app” dialog

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#474]
Implement a more informative “About this app” dialog for the desktop app (currently we only show the version number in Help menu).

One option is to use this library: https://github.com/rhysd/electron-about-window

Something we'll want to consider is whether it's weird to have two "About" dialogs (one for the app, one for the server from the Mattermost Main Menu) and whether we'd want to hide the Mattermost server dialog when on the desktop app.

**Comment by amyblais** [comment]
Moved to Jira: https://mattermost.atlassian.net/browse/MM-14059
