### ISSUE TITLE
Full support for CTRL+MINUS and CTRL+PLUS

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#477]
Jira ticket: https://mattermost.atlassian.net/browse/MM-14099

Full support for CTRL+MINUS and CTRL+PLUS, matching the webapp experience.

For instance, for zoom-in, only `CTRL+=` and `CTRL+SHIFT+=` work, but `CTRL+PLUS` doesn't work in standard Windows keyboard layouts like attached where the right side of the keyboard has a numeric keypad.

![image](https://cloud.githubusercontent.com/assets/13119842/24210717/53e66270-0f00-11e7-9ff0-b9914ce3c607.png)

**Comment by yuya-oc** [comment]
@jasonblais Please let me confirm, does `PLUS` mean the `+` key on a numeric pad?

**Comment by jasonblais** [comment]
That's correct @yuya-oc, it's the `+` key on the numeric pad on the right side

**Comment by amyblais** [comment]
Jira ticket for tracking: https://mattermost.atlassian.net/browse/MM-14099

**Comment by devinbinnie** [comment]
JIRA ticket was closed.
