### ISSUE TITLE
Allow reordering servers in desktop application

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#478]
Jira ticket: https://mattermost.atlassian.net/browse/MM-14098

Allow users to reorder servers directly on the Server Management page and on the navigation bar.

There seems to be no way to reorder the servers in the desktop application (the order within the tab strip at the top of the application window), other than deleting and re-adding the servers  in the desired order. It would be useful to be able to reorder the servers in the settings by dragging, or directly in the tab strip.

From: https://mattermost.uservoice.com/forums/306457-general/suggestions/15771343-allow-reordering-teams-in-desktop-application

**Comment by jnugh** [comment]
Any opinions against one of these options?
Else we should integrate both ways to reorder the tabs I think.

**Comment by jasonblais** [comment]
> Any opinions against one of these options?

Do you mean reordering via the Server Management page or the navigation bar? If so, agree that it would be good to allow both ways to reorder the tabs.

**Comment by amyblais** [comment]
Jira ticket: https://mattermost.atlassian.net/browse/MM-14098

**Comment by esethna** [comment]
Done in v4.4
