### ISSUE TITLE
Allow admins to pre-configure desktop apps

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#483]
Allow admins to pre-configure desktop apps so end users don't have to input server URLs and app settings.

For auto-start option, there are 2 ways to sync this kind of setting:
 - Query the OS on app start and set config.json to whatever is set in the OS -> Changing config.json would have no effect
 - Set whatever is found in config.json and write it to OS (create or remove autostart file). -> Removing the autostart file using the settings provided by windows would have no effect

Neither is ideal so we'll want to carefully evaluate the option. See here for more details: https://pre-release.mattermost.com/core/pl/136f8r3w8f835m3f4mpho7bhua

**Comment by yuya-oc** [comment]
In current implementation, [we use registry or hidden files](https://github.com/Teamwork/node-auto-launch#how-does-it-work). Probably users don't modify them, so I feel the second option looks good.

**Comment by dmeza** [comment]
@yuya-oc @jasonblais the actual fix for this is `BASH-14 Set default server/team in settings`: https://github.com/mattermost/desktop/pull/594 that is built on top of `BASH-20`

**Comment by jasonblais** [comment]
@yuya-oc With https://github.com/mattermost/desktop/pull/594, https://github.com/mattermost/desktop/pull/586 and https://github.com/mattermost/desktop/issues/618, is there additional work required for this issue?

**Comment by yuya-oc** [comment]
@jasonblais One addition, the core concept of this issue (admins can set pre-config without building app from source) would be needed.

**Comment by yuya-oc** [comment]
The possible location to put the pre-configuration file:

- Windows: `C:\ProgramData\Mattermost\`
- Mac: `/Library/Application Support/Mattermost/`
- Linux: `/etc/mattermost/`

Are there any better choices?

**Comment by yuya-oc** [comment]
Probably we haven't decided how to prioritize pre-configuration against to user preferences.

I think there are two choices for that:
  1. defaultPreferences are overridden. So users can change overridden parameters later.
  2. config.json is overridden. So users can't change overridden parameters.

@jasonblais I feel 2 is suitable for admins to control their clients. Any thoughts?

**Comment by jasonblais** [comment]
@yuya-oc 1. is more consistent with the server.

For instance, if the [admin sets a default theme](https://docs.mattermost.com/administration/config-settings.html#default-theme), the user can change it unless they modify some of the other settings such as [theme selection](https://docs.mattermost.com/administration/config-settings.html#theme-settings-experimental).

Also, if they set a default server URL, but keep `EnableServerManagement` as `true`, then they would expect that their users can edit the URL (or add more servers) if they want.

What do you think

**Comment by yuya-oc** [comment]
@jasonblais In development side, 1. is easier. And I agree to choose 1. if it's consistent for us.

And I forgot to mention about buildConfig such as `EnableServerManagement`. Should pre-configuration override buildConfig? (However if it's yes, users can ignore buildConfig by creating their own pre-configuration file)

**Comment by jasonblais** [comment]
I think pre-configuration includes both `defaultPreferences` and `buildConfig`. For instance, to pre-configure the server URL for your users, you would set `defaultTeams` in `buildConfig`.

What do you think?

**Comment by yuya-oc** [comment]
When editing buildConfig.js, the admin need to build the app from source code. In that case, pre-configuration is not needed because they can directly edit defaultPreferences.js.

To pre-configure server URL, they can also override default value of `teams` in defaultPreferences via pre-config file. In that case, users can edit/remove pre-configured URL.

**Comment by jasonblais** [comment]
@yuya-oc I think that makes sense. The only thing the admin would not be able to pre-configure is
 - help link
 - disable server management

However, only Shift has asked for this (and submitted pull requests for them), and they build the app themselves. So I think it's okay to **not override** buildConfig with pre-configuration. If we hear requests for it, we can re-consider it then.

**Comment by yuya-oc** [comment]
@jasonblais Okay, I will prepare.

**Comment by amyblais** [comment]
Closing via https://mattermost.atlassian.net/browse/MM-14086.
