### ISSUE TITLE
Use Redux to manage application state

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#484]
Both the webapp and mobile app are planning to move over to [a Redux architecture](https://github.com/mattermost/mattermost-redux).

We'll eventually want the desktop app moved to it too, perhaps later in Q3 or Q4 of 2017

----

EDIT: The action to move to pure React Native apps will be a different project. This issue is only to use Redux to manage application state.

Here are some references for React Native projects:
 - Windows: https://github.com/Microsoft/react-native-windows
 - Mac: https://github.com/ptmt/react-native-macos

If we moved over to the React Native apps, we could use this plugin to support the Universal Windows Platform (UWP): https://github.com/mattermost/mattermost-mobile/issues/286

We could also consider incorporating a more native Quick Look more easily for Mac: https://github.com/mattermost/desktop/issues/506

Related ticket for mobile repo: https://github.com/mattermost/mattermost-mobile/issues/286
Related uservoice request: https://mattermost.uservoice.com/forums/306457-general/suggestions/15012594-add-a-windows-universal-app-so-that-windows-10-mob

**Comment by yuya-oc** [comment]
Ah, probably there is misunderstanding a little. I had meant "Using Redux to manage application state". To use the plugin, I think we need to move to a pure React app without webview first.

**Comment by jasonblais** [comment]
Hmm yeah, that makes sense.

I updated the title + description to reflect it.

**Comment by jasonblais** [comment]
Perhaps we can use Redux states to later migrate over to BrowserView: https://slack.engineering/growing-pains-migrating-slacks-desktop-app-to-browserview-2759690d9c7b

**Comment by jasonblais** [comment]
@yuya-oc As a follow-up, would this ticket be required before we can consider migrating over to BrowserView? https://slack.engineering/growing-pains-migrating-slacks-desktop-app-to-browserview-2759690d9c7b

**Comment by yuya-oc** [comment]
@jasonblais Not required. However this would be a good option to sort out the app state management before migrating to BrowserView.

**Comment by amyblais** [comment]
Moved to Jira: https://mattermost.atlassian.net/browse/MM-14060
