### ISSUE TITLE
Evaluate yarnpkg as a dependency management tool

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#485]
Evaluate yarnpkg as a dependency management tool: https://github.com/yarnpkg/yarn/releases

Should first wait until v1.0.0 is released

**Comment by yuya-oc** [comment]
https://github.com/mattermost/platform/pull/6226 would be good case to watch.

**Comment by jasonblais** [comment]
Some comments/discussion on pre-release too: https://pre-release.mattermost.com/core/pl/wp8wauuq83gufjhcyahkh67sey

**Comment by jasonblais** [comment]
Closed via #585

**Comment by yuya-oc** [comment]
@jasonblais Thanks to let me know. Right now, we should not back to npm to keep current dependencies until we release v4.1.0. However it's not bad because we can reduce an amount of tools.

**Comment by jasonblais** [comment]
@yuya-oc Makes sense. Would you recommend we still move away from yarn to npm?

**Comment by yuya-oc** [comment]
@jasonblais It's hard to say. Actually we don't have any problem in yarn, so either is fine.

In the first time of this issue, yarn was blazing-faster than npm, and could lock all dependencies. That was very important for us. But right now, npm can lock dependencies as well.
