### ISSUE TITLE
Windows 7: Dialog to confirm uninstallation

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#486]
Dialog to confirm uninstallation, so that a user doesn't accidentally perform the action

**Comment by yuya-oc** [comment]
This can be applied only for Windows. On Mac, we will never use uninstaller. On Linux, package managers would confirm to perform uninstallation.

**Comment by jasonblais** [comment]
I just tried and I do get a confirmation dialog on Windows 10 before uninstallation is completed.

Some of the information is incomplete or inaccurate, but that's related to https://github.com/mattermost/desktop/issues/542

@yuya-oc Okay if I closed this issue?

**Comment by yuya-oc** [comment]
Windows 10 always shows the dialog, but Windows 7 doesn't. As far as looking #551, I think we need to fix it first.

**Comment by amyblais** [comment]
Jira ticket: https://mattermost.atlassian.net/browse/MM-14068
