### ISSUE TITLE
Use AppData/Local for cached data on Windows

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#487]
From: https://mattermost.uservoice.com/forums/306457-general/suggestions/17887945-use-appdata-local-for-cached-data-on-windows

For Windows all local Mattermost data is stored inside of %APPDATA% (AppData/Roaming). 
This directory syncs between computers on every login / logout in certain corporate environments.

Cache data should be placed inside AppData/Local.

**Comment by yuya-oc** [comment]
As far as reading https://github.com/electron/electron/issues/1404, it's Electron's limitation.

**Comment by jasonblais** [comment]
Closing. Will track in feature proposal forum: https://mattermost.uservoice.com/forums/306457-general/suggestions/17887945-use-appdata-local-for-cached-data-on-windows
