### ISSUE TITLE
Send Softpedia an updated product description and screenshots

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#493]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Send Softpedia an updated product description and screenshots

**Observed behavior**

The page is using Slack screenshots and has an out-dated product description: http://mac.softpedia.com/get/Internet-Utilities/Mattermost-Desktop.shtml

**Comment by jasonblais** [comment]
Lots of great improvements coming in the next couple of months, so might be better to wait until v3.9/3.10 is released

**Comment by amyblais** [comment]
Ticket: https://mattermost.atlassian.net/browse/MM-14065
