### ISSUE TITLE
Unable to upload SAML certificate file from file upload dialog

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#497]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Unable to upload SAML certificate file from file upload dialog

**Steps to reproduce**

Mattermost Server v3.7.3; Mattermost Desktop App v3.6.0
Mac and Windows 10

1) Go to an Enterprise Edition server and upload a license file
2) Go to System Console > SAML > Identity Provider Public Certificate
3) Click "Choose File" and attempt to upload a .pem file

**Expected behavior**

The file upload dialog might have a custom endpoint it expects, but there is an option to display "All Files"
![image](https://cloud.githubusercontent.com/assets/13119842/24421687/014446f8-13c5-11e7-96be-758fe2734c27.png)

**Observed behavior**

File upload dialog only displays .cert files and there's no way to display 'all' files

![image](https://cloud.githubusercontent.com/assets/13119842/24421819/724c93be-13c5-11e7-892e-3ca82d4133d0.png)

**Comment by yuya-oc** [comment]
https://github.com/electron/electron/pull/9745 was merged. We can fix the issue by upgrading Electron in the future.

**Comment by jasonblais** [comment]
I moved this to the 3.9 milestone -- your fix was added to Electron 1.7.5 which is still Beta. So we probably won't update to that version prior to releasing 3.8

**Comment by jasonblais** [comment]
We should consider updating to Electron 1.7.5, which would also include a fix for this issue.

**Comment by yuya-oc** [comment]
Fixed by upgrading Electron at #602

**Comment by dengyaolong** [comment]
This commit cause a bug in 1.7.9 mac:  <input type="file" accept=".png"> , filter not work! 
But I revert this commit and build electron , filter works!

can I ignore add "all files" filter in mac?

**Comment by jasonblais** [comment]
^@yuya-oc thoughts?

**Comment by yuya-oc** [comment]
@dengyaolong I have read the issue. Sorry for not enough testing on Mac. Probably your PR (https://github.com/electron/electron/pull/11573) looks the only way to fix filters on Mac.

By the way, it seems that Chrome has an option to choose `All Files` filter by using "Options" button. But the button doesn't exist on Electron. For now, we want to solve our original issue, so I would like to find a similar way.

**Comment by jasonblais** [comment]
@yuya-oc Just to clarify, should we do anything on our end or will https://github.com/electron/electron/pull/11573 be sufficient?

**Comment by yuya-oc** [comment]
@jasonblais By the PR, this our issue will happen again on Mac. Workarounds are below.

- Rename the .pem file with appropriate extension (.cert) before uploading.
- Accept both of .cert and .pem files at `<input>` tag of webapp.

Then, we can try to add the “Options” button like Chrome by researching Electron code.

**Comment by jasonblais** [comment]
@yuya-oc Does https://github.com/electron/electron/pull/11573 help cover it?

**Comment by yuya-oc** [comment]
@jasonblais No. The PR would make our original problem again on Mac by reverting my PR. However it's correct in the meaning of bugfix for Electron.

In other words, we need to research another way only for Mac. i.e.
> Then, we can try to add the “Options” button like Chrome by researching Electron code.

**Comment by jasonblais** [comment]
@yuya-oc Sorry. I just realized I already asked that question.

> Accept both of .cert and .pem files at <input> tag of webapp.

So just a one-line change here would work? https://github.com/mattermost/mattermost-webapp/blob/16288b2633be813e1019f548c66bf6f75e218662/components/admin_console/saml_settings.jsx#L212

If so, I can submit a PR and that should be sufficient for now.

**Comment by yuya-oc** [comment]
@jasonblais Yeah, so `fileType` would be `'.crt,.cer,.cert,.pem'`

**Comment by jasonblais** [comment]
PR here @yuya-oc https://github.com/mattermost/mattermost-webapp/pull/570
