### ISSUE TITLE
Custom Emojis not visible in Mac OS

### ISSUE THREAD

**Issue by MetalCar** [mattermost/desktop#499]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
On MacOS the custom emojis won't display. After a manual reload of the mattermost desktop application (command + r) the emojis will be displayed.

**Steps to reproduce**
- Operating System: MacOS Sierra 10.12.3
- Mattermost Desktop Version: 3.6.0
- Mattermost Server Version: 3.2.0

You must only start the mattermost desktop app and someone else send you a custom emoji.

**Expected behavior**
The custom emoji will be displayed.

**Observed behavior**
The custom emoji will be displayed like `:custom_emoji:`

**Comment by jasonblais** [comment]
Thanks @MetalCar for the report! We've got a ticket to track this on the server side: https://mattermost.atlassian.net/browse/PLT-3711

**Comment by jasonblais** [comment]
I'll close this issue in favor of https://mattermost.atlassian.net/browse/PLT-3711, since it's not desktop app specific issue

Much appreciate the bug report, good to still see you around @MetalCar :)
