### ISSUE TITLE
Feature request: Add functionality to grow/shrink font size

### ISSUE THREAD

**Issue by Endemoniada** [mattermost/desktop#50]
When running Mattermost in Safari, it's easy to change font size with Cmd+ and Cmd-, but when running it in Electron those shortcuts don't work. Seeing as Mattermost itself doesn't support setting font sizes, only font families, this would be a welcome addition.

**Comment by yuya-oc** [comment]
Cmd+ and Cmd- is grow/shrink the rendering, not only fonts.

Please check #27 .

**Comment by it33** [comment]
Should this thread be closed as a dupe?
