### ISSUE TITLE
Change position of "Saved" indicator on Settings page

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#500]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Change position of "Saved" indicator on Settings page

**Steps to reproduce**

Windows 10; Mattermost Server v3.7.3; Mattermost Desktop App v3.6.0

Go to File > Settings and update one of the Settings option. "Saved" indicator appears at the top left corner of the page

![image](https://cloud.githubusercontent.com/assets/13119842/24467528/e07b416a-1482-11e7-86eb-88e1f07572b0.png)

**Proposed change:**

The general feedback is that the current position of the "Saved" indicator is awkward.

The proposed change is to show the "Saved" indicator next to the section header. Specifically
 - if you update server information, the "Saved" indicator appears next to `Server Management`
 - if you update an app option, the "Saved" indicator appears next to `App Options`

See screenshot for an example.

![image](https://cloud.githubusercontent.com/assets/13119842/24472118/8697b33a-1492-11e7-8c52-d056515ff24d.png)

**Comment by wvds** [comment]
@jasonblais I've created a PR for this, where it shows the 'Saved' indicator at the specific section title.
