### ISSUE TITLE
Emoji picker UI shifts to the side when scrolling diagonally up-left on touch pad

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#501]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Emoji picker UI shifts to the side when scrolling diagonally down-right on touch pad

**Steps to reproduce**

Mac; Mattermost server v3.8.0; Mattermost Desktop App v3.6.0

1) Go to Account Settings > Advanced > Preview pre-release features and select `Enable emoji picker in message input box`
2) Open emoji picker in the center panel message input box
3) Scroll down using touch pad, but move diagonally up-left rather than straight up.

**Expected behavior**
Emoji picker scrolls up

**Observed behavior**
Emoji picker scrolls up but shifts to the left

![image](https://cloud.githubusercontent.com/assets/13119842/24482597/9326a52e-14c0-11e7-967c-1d550513c930.png)

**Notes**

This is a feature which will be available on Mattermost server v3.8. You can try testing it at https://pre-release.mattermost.com/core/

**Comment by yuya-oc** [comment]
Not reproduced for me on Mac. Need to check later again.

**Comment by jasonblais** [comment]
Reproduces on the browser so created a ticket for the webapp https://mattermost.atlassian.net/browse/PLT-6216
