### ISSUE TITLE
Add installer hashes

### ISSUE THREAD

**Issue by GeoffreyVDB** [mattermost/desktop#504]
Hi there,

It would be nice to have hashes of the mattermost installers provided here and on the website. This way it is possible to quickly verify if the installers have not been tampered with :).
Example: http://keepass.info/integrity.html

**Comment by jasonblais** [comment]
That's a good idea, I think that shouldn't be too hard to do

@GeoffreyVDB would SHA-256 Checksum be sufficient? We provide it with the Mattermost server releases https://docs.mattermost.com/administration/upgrade.html#version-archive

**Comment by GeoffreyVDB** [comment]
Yes SHA256 should be fine, thanks!



On 5 Apr 2017, at 06:23, Jason Blais <notifications@github.com<mailto:notifications@github.com>> wrote:


That's a good idea, I think that shouldn't be too hard to do

@GeoffreyVDB<https://github.com/GeoffreyVDB> would SHA-256 Checksum be sufficient? We provide it with the Mattermost server releases https://docs.mattermost.com/administration/upgrade.html#version-archive

**Comment by jasonblais** [comment]
Thanks! Created a pull request to add it to our release process. We'll include it in our next desktop app release https://github.com/mattermost/desktop/pull/505
