### ISSUE TITLE
[OS X] Unable to display main window once it's closed

### ISSUE THREAD

**Issue by frdmn** [mattermost/desktop#51]
Steps to reproduce:

1. Open `electron-mattermost` on OS X
2. Click on the red close button of said main window.
3. Now the application is hidden but still running (Dock icon remains)

Would be nice if <kbd>CMD + N</kbd> would redraw the window on the screen :)

**Comment by yuya-oc** [comment]
Step 3 is correct behavior. The main window appears again when clicking the Dock icon.

OS X: 10.11.3
electonr-mattermost: 1.0.7

**Comment by frdmn** [comment]
@yuya-oc I agree, works for me as well. However it took me quite a long time to figure that out. Usually I just try to "recreate" the window again using "standard shortcuts" (<kbd>CMD + N</kbd> or by doing <kbd>CMD + ⇥</kbd> twice)

**Comment by yuya-oc** [comment]
Could you tell me about "standard shortcuts"? I checked Slack and Skype, but there are no such shortcuts.
Then, to handle the shortcut, the app have to get focus. How do you get focus for it from other window?

**Comment by frdmn** [comment]
@yuya-oc You are totally right. For some reason I was certain that other applications, automatically redraw the window as soon as they regain focus.

However, in this case I would suggest we just implement a <kbd>CMD + N</kbd>, to provide a way to redisplay the main window in case it got closed somehow (clicking through red close button). Right now, the only way to fix this, is restarting `electron-mattermost`.

**Comment by yuya-oc** [comment]
For example, when the app get focus by <kbd>CMD + TAB</kbd>, window does not appear. In that case, the shortcut is useful. OK.

**Comment by teetrinkers** [comment]
There is a standard way to restore windows on OS X, but it is a bit awkward. I usually use `CMD + H` instead of closing the window with `CMD + W`.

http://apple.stackexchange.com/questions/55432/keyboard-shortcut-for-restoring-applications-from-the-mac-os-x-dock

**Comment by frdmn** [comment]
@teetrinkers I'm not sure if I understand the reported issue on SO. Let's take mail app for example:

1. Focus Mail.app
2. Hit  <kbd>CMD + H</kbd> to hide the window
3. Use  <kbd>CMD + ⇥</kbd> once, to show the window again

But right now, this doesn't work for `electron-mattermost`. So once the window is closed/hidden, I HAVE to switch to the trackpad/mouse and click on the Dock icon to make it visible again or alternatively I restart the app completely.

**Comment by teetrinkers** [comment]
There is a difference between hiding and closing a window. You hide a window using `CMD + H`. You close a window using `COM + W` or the red close button.

This works for me:

1. Focus electron-mattermost (1.0.7)
2. Hit `CMD + H` to hide the window
3. Use `CMD + ⇥` once, to show the window again.

If, on the other hand, you close the window using the red close button, then `CMD + ⇥` won't bring it back. This is the same for Mail.app. The stackexchange post shows a standard way to restore closed windows without using the mouse.

With some apps (e.g. Mail.app), you can restore closed windows using `CMD + 1`, but this is not a standard.

**Comment by frdmn** [comment]
> This works for me: [...]

I was pretty certain that this didn't work for me earlier, but I just tried to record a screencast for you to show you the behaviour on my screen, but now I can't reproduce the way I mentioned in my previous comment anymore. _Crud!_

> If, on the other hand, you close the window using the red close button, then CMD + ⇥ won't bring it back. 

I assume that was exactly what I did earlier but instead I thought I've hit <kbd>CMD + H</kbd>. 

> The stackexchange post shows a standard way to restore closed windows without using the mouse.

Got it. Thanks for the explanation!

> [...] so I propose we use CMD + 1 as well. Or just use CMD + H instead of closing the window

Makes sense and I'm totally fine with that! :+1:

**Comment by it33** [comment]
Hi @frdmn, per [CMD +W](https://github.com/mattermost/desktop/issues/52#issuecomment-194911024) thread, if this is important, can we have your help (or the help of someone from your team who wants the same feature) to open a [feature idea?](http://www.mattermost.org/feature-requests/) so this can be upvoted? 

We have a new category for [Mattermost Mac desktop app specifically](https://mattermost.uservoice.com/forums/306457-general/category/159792-mattermost-app-mac), if this is a priority area for you, would love your help getting the conversations started.

**Comment by mikaoelitiana** [comment]
Hello, I fixed a similar issue in Kitematic (electron based as well) https://github.com/docker/kitematic/issues/702 and I can work on this if the feature is upvoted.
