### ISSUE TITLE
Can't launch application on macOS Sierra

### ISSUE THREAD

**Issue by makedonmax** [mattermost/desktop#510]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Can't launch application.

**Steps to reproduce**
Launch an application.
An app has worked fine before, but today the error is shown.

Mattermost app: v.3.6.0
Operating System: macOS v.10.12.4

**Observed behavior**
![2017-04-11 14 13 33](https://cloud.githubusercontent.com/assets/12586970/24906809/00c5e22e-1ec2-11e7-92ba-d735d1313a68.png)

**Comment by jasonblais** [comment]
@yuya-oc does the error provide any useful information?

**Comment by yuya-oc** [comment]
Not reproduced on my macOS 10.12.**3**. To make sure, I will check 10.12.4 on my office's Mac.

As far as looking the screenshot, I feel the application is actually running if it's not freezing. But it seems that webapp's login page is not correctly loaded due to some reason.

@makedonmax would you check following points?

- Try the application again.
- Check that your server is correctly working by using Chrome.

**Comment by makedonmax** [comment]
@yuya-oc 
> Try the application again.
Tried few times. Result is the same.

> Check that your server is correctly working by using Chrome.
Server is working well. I'm using it instead of desktop app today.

**Comment by jasonblais** [comment]
@makedonmax Can you try un-installing the app, then re-downloading from about.mattermost.com/downloads?

**Comment by makedonmax** [comment]
@jasonblais 
Tried that too. I've removed it from "Applications", then downloaded it and extracted from zip.

**Comment by yuya-oc** [comment]
I tried 10.12.4, but the problem was not reproduced. Does developer tools console (Cmd+Option+I) show any messages?

**Comment by makedonmax** [comment]
@yuya-oc 
> I tried 10.12.4, but the problem was not reproduced. 

It's really strange.

Here is a screenshot with console:
![2017-04-12 17 49 37](https://cloud.githubusercontent.com/assets/12586970/24963908/90788408-1fa8-11e7-9172-752937e62110.png)

Hope, it will helps.

**Comment by yuya-oc** [comment]
Hmm...as I thought, the main window of desktop app is actually working. Red messages are merely warning for other known issues.

This means the loaded content is wrong due to some reason(caches?). So "Clear Cache and Reload"(Cmd+Shift+R) might make sense.

**Comment by makedonmax** [comment]
@yuya-oc 
"Clear cache" helped! Thank you very much.
