### ISSUE TITLE
Pressing "Return" in the "Switch Channels" dialog adds a newline to the text input box

### ISSUE THREAD

**Issue by benreic** [mattermost/desktop#511]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Pressing "Return" in the "Switch Channels" dialog adds a newline to the text input box after you've switched channels.

**Steps to reproduce*
1. Open Mattermost Desktop
2. Press Cmd+K to open the "Switch Channels" dialog.
3. Start typing the name of a channel.
4. When the desired channel is selected in the auto complete drop down, press "Return" to choose the channel.
5. Now that the desired channel is selected, press "Return" again to commit the change and close the dialog.
6. Notice that you are now in the desired channel and that the input area has a newline inserted with the cursor focused on the text input box.

- Operating System: macOS Sierra 10.12.4
- Mattermost Desktop App version: 3.6.0
- Mattermost Server version: 3.7.3

**Expected behavior**
I should be in the desired channel with the cursor focused on an empty text box.

**Observed behavior**
I am in the desired channel with the cursor focused on a textbox that has a newline inserted.

**Possible fixes**
My guess is that the code that responds to the "Return" keypress that closes the "Switch Channels" dialog box is bubbling the event up and allowing the main window to respond to the keypress as well. The keypress event should be cancelled in the dialog.

**Comment by jasonblais** [comment]
Thanks @benreic! This issue will be resolved in the next Mattermost desktop app version. We're estimating it to be available by end of April.

https://github.com/mattermost/desktop/issues/426
