### ISSUE TITLE
Ctrl+Tab should switch between servers when logged into multiple servers

### ISSUE THREAD

**Issue by benreic** [mattermost/desktop#512]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Pressing Ctrl+Tab should switch tabs when logged into multiple teams.

**Steps to reproduce**
1. Open Mattermost Desktop
2. Sign in to at least two servers, creating multiple tabs across the top of the app
3. Press Ctrl+Tab
4. Observe that nothing happens.

- Operating System: macOS 10.12.4
- Mattermost Desktop App version: 3.6.0
- Mattermost Server version: 3.7.3

**Expected behavior**
I should switch between tabs, similar to how other common tabbed interfaces work (Chrome, FF, Visual Studio, etc.)

**Observed behavior**
Nothing happens when you press Ctrl+Tab

**Comment by jasonblais** [comment]
Hm, that should work, so it might be a bug.

Can you try if clicking "Select Next Team" from Menu Bar > Window switches you to the next tab?

![image](https://cloud.githubusercontent.com/assets/13119842/25012169/acacccc0-203d-11e7-9a04-9fff0f610ae1.png)

**Comment by benreic** [comment]
"Select Next Team" does work correctly, the advertised shortcut for that functionality is Option+Command+(Left|Right) arrow, which also works.

CMD+TAB does not work, as that opens up the macOS application switcher.

**Comment by jasonblais** [comment]
Got it, thanks @benreic.

Sorry that I got confused with the Windows platform initially. Adding `CTRL+TAB` for Mac makes sense.

**Comment by wvds** [comment]
@jasonblais 
I would like to pick this up; does it need to change (from `Option+Cmd+(Left|Right)` to `Ctrl+(Shift)+Tab`) or add it?

IMO it's nicer to replace it, to keep it consistent with the other platforms.

**Comment by jasonblais** [comment]
@wvds excellent, thank you!

Does `Option+Cmd+(Left|Right)` currently work for you? (I don't have a Mac to test it on)

**Comment by MusikPolice** [comment]
On the MacOS desktop client, `Option+Cmd+(Up|Down)` changes between channels. In a browser, `Option+Cmd+(Left|Right)` changes between tabs.

**Comment by jasonblais** [comment]
Thanks @MusikPolice, 

1) Does `Option+Cmd+(Left|Right)` do anything for you, if you're connected to more than one server and have the server tab bar visible on the app?

![image](https://user-images.githubusercontent.com/13119842/31080777-bfe783c4-a757-11e7-924c-7d78dd758f9c.png)

2) Does `CTRL+TAB` work for you on Mac browsers? (My understanding is that it does)

**Comment by benreic** [comment]
I can confirm that `Option+Cmd+(Left|Right)` does toggle between servers on the desktop app.

**Comment by benreic** [comment]
And just to throw in my two cents on the expected behavior:

I believe `Ctrl+Tab` and `Ctrl+Shift+Tab` should be the canonical way to change server tabs on the desktop app. This is consistent with other tabbed macOS apps like Safari and Finder.

**Comment by jasonblais** [comment]
Thanks all! This is very helpful.

@wvds Propose we ADD support for `Ctrl+Tab` and `Ctrl+Shift+Tab` rather than replace the existing because:
 - `Option+Cmd+(Left|Right)` switches tabs in the browser
 - Some users may already be familiar with the shortcut
 - There is little value for removing the `Option+Cmd+(Left|Right)` shortcut

**Comment by wvds** [comment]
@jasonblais Okay! Will probably pick this up tomorrow :)
