### ISSUE TITLE
MacOS: Add a new option to bounce dock icon

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#514]
Add a new option below `Show red badge on taskbar icon to indicate unread messages`.

By default the setting is disabled. The user can enable the setting, and choose between two options:
 - `once` // only bounces once when a new message is received
 - `until I open the app` // bounces until the app gets focus

![image](https://user-images.githubusercontent.com/13119842/31949076-6f091c78-b8a6-11e7-8a6b-96e6b7716ec7.png)

The icon will always bounce for a new message regardless of the `Show red badge on taskbar icon to indicate unread messages` setting.

**Comment by yuya-oc** [comment]
"Flash" feature doesn't exist on macOS. There is a bouncing icon instead.

https://electron.atom.io/docs/api/app/#appdockbouncetype-macos

**Comment by jasonblais** [comment]
Ah okay, updated the title.

**Comment by wvds** [comment]
I'll pick this one up as well, it's a nice feature to have!
@jasonblais Should it bounce once (= informational) or should it keep bouncing until the window is active (= critical)?

**Comment by jasonblais** [comment]
@wvds Do you know how other typical desktop apps behave on Mac? It might be good to test on
 - Slack
 - Skype
 - HipChat

to compare. Unfortunately I don't have a Mac environment to try it out..

//cc @yuya-oc @MusikPolice 

---

PS: Huge thanks for all your help!

**Comment by MusikPolice** [comment]
I can't be certain, but I don't think bounce exists anymore. 

I distinctly remember it on previous versions of the OS, but none of my app icons bounce for notifications in macOS Sierra, and I can't find anything in the preferences panel that enables that behaviour. It seems to have been superseded by icon badges, similar to iOS.

They do bounce when an app is first launching, but Mattermost already does that.

**Comment by yuya-oc** [comment]
Yeah, recently I also didn't see bouncing icons on Mac. 

Whether the icon bounces is controlled by application code. So we can choose bouncing in our choice. However [the guideline](https://developer.apple.com/library/content/documentation//UserExperience/Conceptual/OSXHIGuidelines/Dock.html) saids **Use bouncing to notify users of serious information that requires their attention**. In our app, I think that it would be possibly applicable for mention.

Unfortunately, the event can't tell whether the notification is "new comment" or "mention" for now.

**Comment by wvds** [comment]
@jasonblais 

I also don't see it often in applications anymore as before. But last week I saw it happen at someones Mac, where iTunes was bouncing. Next to that Slack also has it implemented, and you can choose to only bounce once (= default) or until you open the application: <img width="577" alt="screen shot 2017-10-10 at 20 04 52" src="https://user-images.githubusercontent.com/4283723/31402457-505817a8-adf6-11e7-88ad-1678c026931b.png">

**Comment by jasonblais** [comment]
Thanks all! That's very helpful.

Would it be correct to assume that on older Mac versions the Dock icon bounces but not on MacOS Sierra? If so, we can add this setting given ~40-50% of Mac users haven't upgraded to Sierra yet and several customers have requested for this feature.

I started [working on a mock up for how to display the setting](https://docs.google.com/presentation/d/1ss5MAHiSV7V2OmFxjA12rOjJDVNZr2MDx8HUj694TQQ/edit#slide=id.g28a5d197ac_0_0) and had two questions:

1) If we add the setting, do we need to do anything special for it not to bounce on MacOS Sierra so that it's consistent with other apps. Or will the operating system take care of that, do we know?
2) If Slack's `Show badge on icon to indicate unread activity` is disabled, does the icon bounce for all messages or only for mentions?
   - Given you guys seem to have MacOS Sierra, I asked one of our team members to check this out. But posting here in case you'd know.

PS: HipChat also offers this setting (see below). The user can choose between bouncing the dock icon once or until the user opens the app via a dropdown. The approach seems simpler than Slack's and might be worth to consider.

![image](https://user-images.githubusercontent.com/13119842/31439936-0f430e4c-ae5c-11e7-9bb3-1fa316ef6f44.png)

**Comment by yuya-oc** [comment]
@jasonblais IMHO, the reason we haven't seen bouncing icons might be that merely there are few apps which uses bouncing frequently.

**Comment by wvds** [comment]
From the [human interface guidelines](https://developer.apple.com/macos/human-interface-guidelines/system-capabilities/dock/):
> To avoid annoying the user and minimize the disruption of other activities, bouncing should only be used for infrequent serious issues the user might care to address.

So maybe not really a good idea to implement it, although.. of course it's a user setting which is default off.

**Comment by jasonblais** [comment]
Hey @yuya-oc and @wvds, sorry for the silence on my part.

We have quite a few customers and community members who have shown interest towards this feature. So I think it's worth to add. I do agree it should be disabled by default though.

I have a proposed design here, queued for UX sign-off. Let me know if you have any feedback on it: https://docs.google.com/presentation/d/1ss5MAHiSV7V2OmFxjA12rOjJDVNZr2MDx8HUj694TQQ/edit#slide=id.p

@wvds You mentioned you're busy, which I completely understand. However, if you're interested contributing this feature during Hacktoberfest, that would be great! Something that will benefit a lot of Mattermost Mac users.

**Comment by jasonblais** [comment]
@wvds I've updated the issue description with final design, let me know if you have time and interest to work on it :)

**Comment by wvds** [comment]
@jasonblais I'll probably work on it in the upcoming days :)

**Comment by wvds** [comment]
@jasonblais @yuya-oc I've created a pull request with the bouncing icon. By default it is disabled and when enabling the 'sub-setting' is by default `once`.

**Comment by jasonblais** [comment]
Awesome!

**Comment by pmalbu** [comment]
I cannot seem to figure out how to enable this bouncing. I looked through the Slack docs and could not find it there either. Would someone please enlighten me?

**Comment by jasonblais** [comment]
Hi @pmalbu - you can modify app settings from **Mattermost > Preferences** in the menu bar
![image](https://user-images.githubusercontent.com/13119842/68224345-6bdb9d00-ffbc-11e9-805a-82a7321636b4.png)

then enabling in the App Options
![image](https://user-images.githubusercontent.com/13119842/68224364-772ec880-ffbc-11e9-84ae-fb03cde1a4db.png)

You mentioned Slack docs -- so I should mention that this will apply for Mattermost, not Slack :)
