### ISSUE TITLE
CMD or Ctrl + W to close window

### ISSUE THREAD

**Issue by frdmn** [mattermost/desktop#52]
Would be also nice to use  <kbd>CMD + W</kbd> to close the current window of `electron-mattermost`.

**Comment by yuya-oc** [comment]
Now there is <kbd>CMD + H</kbd> to hide the window.

**Comment by frdmn** [comment]
@yuya-oc Nice, thanks for the quick reply!

I think adding CMD + W as fallback would be best practise in this case. Never saw an application before that simply does nothing on <kbd>CMD + W</kbd>.

**Comment by nItroFreeZer** [comment]
Hide and close are two different things.
`CMD + W` is used to close a window, and `CMD + H` to hide a window in OS X.

`CMD + W` may be **not** a fallback to hide Windows.

**Comment by frdmn** [comment]
@nItroFreeZer Well, just replace `hide` with `close and able to redraw` then? If you checkout Mail.app or Contacts.app, etc: You can use  <kbd>CMD + W</kbd> in any of them and they just "close" (or hide?) the current window.

Giving no response for  <kbd>CMD + W</kbd> just feels weird and not usual.

**Comment by nItroFreeZer** [comment]
> If you checkout Mail.app or Contacts.app, etc: You can use <kbd>CMD + W</kbd> in any of them and they just "close" (or hide?) the current window.

They **close** the current window.
A hidden window is not closed, it's only hidden and accessible through Mission Control.

> Giving no response for <kbd>CMD + W</kbd> just feels weird and not usual.

I agree with you.

**Comment by frdmn** [comment]
@nItroFreeZer Sorry for mixing up terms then. I indeed mean close not hide actually. 

Gonna adjust the title and description of this issue :)

**Comment by it33** [comment]
Hi @frdmn, hi @nItroFreeZer appreciate your feedback on the CMD + W enhancement. 

Now that the app is official, we're hoping to move enhancements from GitHub issues into Mattermost's existing [feature idea forum](http://www.mattermost.org/feature-requests/). The feature idea forum allows the broader user community to discuss and upvote features, and also encourages people to volunteer for implementation. 

We've created a [feature idea for CMD + W to start.](https://mattermost.uservoice.com/forums/306457-general/suggestions/12882867-cmd-w-to-close-window) If this is still a priority, can we have your help upvoting it and we can close this ticket?

**Comment by frdmn** [comment]
Unfortunately, I don't have any upvotes left anymore on Uservoice. What do you guys do once you spent all of your three precious votes? Waiting for the upvoted requests to be implemented and closed?

**Comment by it33** [comment]
Mattermost is a team communication service, so the expectation is you'd message people on your team using Mattermost with something like "Hey, I added a feature idea for Mattermost, I think it's important, anyone want to help upvote this?" 

When people agree, the vote count rises, and it's easier to find contributors who want to work on the most popular requests.
