### ISSUE TITLE
After changing spelling language, incorrect words not highlighted until you click outside of the message box

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#524]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
After changing spelling language, incorrect words not highlighted until you click outside of the message box

**Steps to reproduce**

Mac OSX: Mattermost Server v3.8.2; Mattermost Desktop App v3.7.0-RC1

1. Go to File > Settings
2. Select "Check spelling"
3. Click one of the servers, or click "x" to close the Settings page
4. Paste the following into an empty message box

```
Shouldn't it be easy? 1 2 3 Aimee Lindsay Russian isn't football stick Jason Eric English November screenshot helllo.
```

5. Right-click inside the message input box
6. Go to "Spelling Languages"
7. Select French

**Expected behavior**

Incorrect words highlighted right away.

**Observed behavior**

Incorrect words not highlighted until you click outside of the message box.

**Comment by yuya-oc** [comment]
Closed via #526
