### ISSUE TITLE
Change default setting for spellchecker to true

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#527]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

Change default setting for spellchecker to true

We've been doing testing on the spellchecker and there haven't been issues thus far. So propose enabling it by default to encourage people to use it.

Moreover, most of our use base will be covered by the available languages (English, French, German, Spanish and Dutch).

**Comment by jasonblais** [comment]
Closed via #529

**Comment by viki53** [comment]
I have an issue with this setting: my language is set to French, though the spellchecker seems to use an different language so pretty much everything is shown as wrong.

Any idea how to fix this?

**Comment by jasonblais** [comment]
@viki53 If you right-click the message box, you can navigate to `Spelling Languages` and choose French.

Let me know if that helps? 

![image](https://user-images.githubusercontent.com/13119842/31820214-52db9d7c-b56e-11e7-8ada-ead22c4ed8c5.png)

**Comment by viki53** [comment]
Ah, gotcha! Didn't see this option before…

Maybe automatically adjust this setting with the interface language?

**Comment by jasonblais** [comment]
@yuya-oc Is it possible to initially set the spelling language based on the user's Mattermost language setting? Not sure it's possible given the setting is written in the user's config file

**Comment by yuya-oc** [comment]
@jasonblais The initial language should be automatically chosen based on user's system language. However, "en-US" would be chosen when upgrading from v3.6.0 or earlier. It's a bug.

**Comment by jasonblais** [comment]
Ah got it, so this is resolved with v3.7 and later.

**Comment by viki53** [comment]
Initial language isn't spellchecker language, is it?

I am using a fresh install (3.7.1) since the end of last week and had this issue.

**Comment by yuya-oc** [comment]
It was insufficient explanation. For upgrading, it's actually a bug of v3.7. For initial installation, we need more investigation.

I thought [`app.getLocale()`](https://electron.atom.io/docs/api/app/#appgetlocale) returned wrong locale. But probably my code is wrong because it's called before `app.on('init')` callback.

**Comment by yuya-oc** [comment]
Added #632 to track the bug.
