### ISSUE TITLE
Constant refreshing of server in Desktop App v3.7 after changing settings

### ISSUE THREAD

**Issue by lindy65** [mattermost/desktop#528]
I confirm (by marking "x" in the [ ] below): 

- [x ] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Constant refreshing of server in Desktop App v3.7 after changing settings

**Steps to reproduce**
1. Click on "File" > "Settings"
2. Scroll down and change any setting (which is auto-saved)
3. Click the "X" at the top right of the screen to close the settings menu

**Expected behavior**
- Be taken back to the server tab I was on and continue working.

**Observed behavior**
- Server constantly refreshes (I will DM the screen capture to you - .mp4 not supported on GitHub) with errors in the dev tools (see attached screenshot)

**Possible fixes**
Sorry, no idea...

#

![image pasted at 2017-5-2 18-48](https://cloud.githubusercontent.com/assets/13020833/25651181/e58c08cc-2fe1-11e7-9e8b-c64fd9d13003.png)

**Comment by yuya-oc** [comment]
The message is transferred from webview. So it seems that the problem happens in webapp itself.

Would you try clearing caches(Ctrl+Shift+R)? Somehow webapp failed to communicate with the server. But it looks strange because `getPostsPage` returns status 404. I worry that there is mismatch between the webapp and the server.

**Comment by lindy65** [comment]
Sorry @yuya-oc,

Forgot to include in the original report that I did clear cache and refresh and the issue still persisted. Tried a few times with the repro steps and it was the same each time. 

It does not repro on the browser...

**Comment by jasonblais** [comment]
Yuya added a workaround for it in the troubleshooting section: https://github.com/mattermost/docs/pull/1163

We can increase priority of this issue if we hear more reports about it, but assigning to `Unscheduled` for now.

**Comment by lindy65** [comment]
Thanks Jason, I'll close off this issue for now as we have a workaround in the docs.  If we hear more reports, we can reopen.
