### ISSUE TITLE
Pressing "help" from the help window show the main chat area.

### ISSUE THREAD

**Issue by ruivieira** [mattermost/desktop#531]
I confirm (by marking "x" in the [ ] below): 

- [x ] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [ ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**

Pressing the help link from the help window shows the main chat interface.

**Steps to reproduce**

- Operating System: macOS Sierra 0.12.2 (16C67)
- Mattermost Desktop App version: 3.6.0
- Mattermost Server version: 3.8.2

From the main chat area in the desktop app, press the "help" link in the bottom right corner.
A new window ("Messaging Basics") should appear. In that window press again "help" in very bottom. This window will now show the main chat area resulting in two open windows with the same content.

**Expected behavior**

Pressing help should lead to the help index.

**Comment by yuya-oc** [comment]
Not reproduced for me on Windows and Mac.

- macOS 10.12.4
- Mattermost Desktop 3.6.0
- Mattermost Server 3.8.2

I clicked "Help" of the screenshot though, is it correct? The link shows the "Mattermost User’s Guide".

![messaging_basics](https://cloud.githubusercontent.com/assets/1412057/25745641/e82e9798-31da-11e7-985a-2a591a31a87d.png)

You didn't mark "x" on "This doesn't reproduce on web browsers (such as in Chrome)" though, I feel this should reproduce also on Chrome. If the problem reproduces also on Chrome, this issue should be reported to [mattermost/platform](https://github.com/mattermost/platform).

**Comment by jasonblais** [comment]
Hey @ruivieira, let us know if this reproduces on the browser? We'd be happy to file a ticket on the server side, or schedule a fix for the desktop app.

**Comment by jasonblais** [comment]
We haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the latest version. 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
