### ISSUE TITLE
Add SHA-256 checksum for 3.7 release builds

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#533]
Add SHA-256 checksum for 3.7 release builds: https://github.com/mattermost/desktop/releases/tag/v3.7.0

This is following the post here https://github.com/mattermost/desktop/issues/504 and follows what the platform team does for server release builds

**Comment by jasonblais** [comment]
@yuya-oc Not urgent -- once you're back, wondering if this is something you'd be able to help with?

**Comment by yuya-oc** [comment]
@jasonblais When I had cut the release build, I created checksums. So what we need to do is writing or uploading them.

- Write checksums in [release text](https://github.com/mattermost/desktop/releases/tag/v3.7.0) like [version archive of Mattermost server](https://docs.mattermost.com/administration/upgrade.html#version-archive)
- Upload [SHASUMS256.txt](https://github.com/mattermost/desktop/files/1105739/SHASUMS256.txt) to somewhere and write the link.

**Comment by jasonblais** [comment]
I think we can include them in the release text. I can add them from the release text if you think that's okay?

**Comment by yuya-oc** [comment]
Okay, thanks.

**Comment by jasonblais** [comment]
Added to https://github.com/mattermost/desktop/releases/tag/v3.7.0, let me know if that looks good?

If it's okay, you can close this issue,
