### ISSUE TITLE
Make it easier to open a file you've downloaded from Mattermost

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#535]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Make it easier to open a file you've downloaded from Mattermost.

**Steps to reproduce**

Windows 10 Home; Mattermost Desktop App v3.7.0; Mattermost Server v3.8.2

1) upload a file
2) download the file

**Expected behavior**

File downloads and you have an easy way of opening it in your machine.

**Observed behavior**

File downloads. You must then open up the folder explorer, navigate to the location, and then open it.

**Possible fixes**

There's a few options we could consider:
 1) Provide an option to open & save the file, in addition to just saving it
 2) Provide a list of downloaded files somewhere in the Mattermost desktop app UI (Slack style)
 3) Download the file via browser (HipChat style)
 4) A second button with "Show in Finder/Windows Explorer" would be nice as well.
 5) Downloaded files are listed at the bottom of the app (Chrome style). See screenshot attached.

![image](https://user-images.githubusercontent.com/13119842/34826971-a20b2d3a-f6a6-11e7-8137-a13be76742a7.png)

 6) Provide an option to download, then open the file from within the UI (Skype style). See screenshot attached.

![image](https://user-images.githubusercontent.com/13119842/34827021-c91037e0-f6a6-11e7-811a-d4d6479068d6.png)

Some use cases described in this ticket https://mattermost.atlassian.net/browse/PLT-7157

**Comment by pangxieke** [comment]
This issue is necessary. Now this issue  has achieved in v3.10?

**Comment by jasonblais** [comment]
Hey @pangxieke, thanks for the feedback! We'll take this into consideration for prioritizing issues.

The version number in the "milestone" column indicates the desktop app version.

**Comment by jasonblais** [comment]
Given a few people have asked for this, I've moved this up to 3.9 in place of https://github.com/mattermost/desktop/issues/518

**Comment by MusikPolice** [comment]
We should consider attempting to match the behaviour of the web app when running in Chrome. There are sample videos attached to [this ticket](https://mattermost.atlassian.net/browse/PLT-7157)

**Comment by jasonblais** [comment]
@yuya-oc Of the six potential options listed in the ticket description
 1. which ones are technically possible in our Electron framework
 2. those that are possible, how long will each take to implement?

**Comment by yuya-oc** [comment]
@jasonblais 

1. Probably 1, 2 and 5 are possible. 3 might be possible, but the user needs to login also on the browser. 4 and 5 are not possible because they would need to edit webapp.
2. That depends on how rich UI will we want though, they would take from few days to 1 week. Especially, 2 and 5 would be built-in to the main page, so I might have to refactor existing codes before.

**Comment by jasonblais** [comment]
Thank you @yuya-oc! This is very helpful, have shared with our UX designer.

**Comment by jasonblais** [comment]
Some mock ups of 6. UX designers are leaning towards that option, which would mean changes in the webapp rather than the desktop app

https://projects.invisionapp.com/share/PVDKAJ67Z#/screens

![image](https://user-images.githubusercontent.com/13119842/35596476-0d56b8b6-05e8-11e8-8f9a-447ba87c7a4c.png)

![image](https://user-images.githubusercontent.com/13119842/35596484-11869258-05e8-11e8-81da-165de624a6a7.png)

**Comment by yuya-oc** [comment]
Sorry, I have noticed that I forgot to comment about No.6 in https://github.com/mattermost/desktop/issues/535#issuecomment-356949202 .

I think No.6 approach is very difficult. Generally, the desktop app's webview can't do what webapp can't (webapp can't know the folder where downloaded files are saved). Even if the desktop app modified webapp's DOM tree, webapp's React would restore the ideal tree after a moment.

However if it's outside of webview, Electron can know the folder and create UI. So I had written "1, 2 and 5 are possible".

**Comment by jasonblais** [comment]
@yuya-oc Thanks for the feedback, that's good to know. I didn't realize the webapp can't know the folder where downloaded files are saved, but it makes sense now that you say it.

**Comment by jasonblais** [comment]
@yuya-oc Here are new designs based on option 5. 

Let me know if there are concerns with implementation? And if not, what estimate would you give for development effort (that way we can plan accordingly)?

https://projects.invisionapp.com/share/FBE083826#/screens/289031413_Download_Bar_Circular

**Comment by jasonblais** [comment]
@yuya-oc Thank you for the feedback. If we didn't have the download manager
 1. What functionality would be lost?
 2. How much work would this option be then?

**Comment by yuya-oc** [comment]
@jasonblais 

1. Almost (information, open the downloaded file). To get information to render the UI, we need to manually manage downloading items in background. ("download manager" might be an exaggeration, but items must be kept in the main process at least)
2. Probably few days. But it works with UI, so they would be done together.

**Comment by jasonblais** [comment]
@yuya-oc Thank you! Very useful to know. By the way, we might get someone from the Mattermost dev team to help work on this feature as well, I'll know later this month.

**Comment by jasonblais** [comment]
Platform team helping with this feature.

**Comment by amyblais** [comment]
Moved to Jira: https://mattermost.atlassian.net/browse/MM-14061
