### ISSUE TITLE
Mention count not shown in taskbar

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#537]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Mention count not shown in taskbar

**Steps to reproduce**

Mattermost Destkop App v3.7; Current `master` branch in `/platform`; Windows 10; Mac

**Expected behavior**
Mention count shown in taskbar

**Observed behavior**
1) Mention count not shown in taskbar
2) Mattermost logo missing (Windows 10 home only; doesn't reproduce on Mac)
3) Blue "unreads" dot shown in system tray

![image](https://cloud.githubusercontent.com/assets/13119842/26222786/49315e82-3be9-11e7-9174-570cbe00774e.png)
![image](https://cloud.githubusercontent.com/assets/13119842/26222787/4b55cb6c-3be9-11e7-8998-f12f625760de.png)
![image](https://cloud.githubusercontent.com/assets/13119842/26222790/4f5745b0-3be9-11e7-8b88-7eea253691b6.png)

**Comment by jasonblais** [comment]
@yuya-oc This started after we switched platform to `master`. 

If this is an issue on the desktop app (that somehow got introduced with latest changes on `master`), we might need to deploy a dot release that is timed with Mattermost Server v3.10 release

**Comment by yuya-oc** [comment]
Yeah, this is an issue for desktop app. On master branch,  https://github.com/mattermost/platform/commit/fc58174747cd25eded07c30f5f122d4f8122e7e5 changed `badge` to `mention-badge`. So currently desktop app can't count mentions.

**Comment by jasonblais** [comment]
Thanks Yuya, I'll ask @asaadmahmood whether that change was necessary as it will break the mention count for anyone using an older desktop app version.

**Comment by yuya-oc** [comment]
Thanks! To make sure, I will prepare the version compatible with both of `badge` and `mention-badge`

**Comment by jasonblais** [comment]
@yuya-oc Asaad will help submit a PR that reverts back to using the `badge` classname.

It would be nice to have an auto-upgrade feature that's tied with server upgrades. That way it won't be a big issue to change classes since people could upgrade to the latest desktop release.

**Comment by yuya-oc** [comment]
@jasonblais I see. So also for our internal comfortable, we would have to add auto-upgrade.

**Comment by jasonblais** [comment]
Yeah probably. 

I have been talking to people after posting the spec in the desktop app channel: https://docs.google.com/presentation/d/1BmH5gGtdhijHRfv46_uhgl_0kwT5qOI8_5y2HNfNpqA/edit#slide=id.p

Hoping to have some time to update and post again in the channel for more feedback.

**Comment by jasonblais** [comment]
@yuya-oc I'll close this issue for now, since the change was reverted in platform repo and the mention count appears again.

Also, my desktop task bar icon reappeared today - it might have disappeared temporarily due to a Windows update.
