### ISSUE TITLE
Don't restart the app in full screen mode

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#538]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

Jira ticket: https://mattermost.atlassian.net/browse/MM-14097

**Summary**
Don't restart the app in full screen mode.

**Steps to reproduce**

Windows 10; Mattermost Desktop App v3.7; Mattermost Server v3.9; 

1) Open the app
2) Go to **View > Toggle Full Screen**
3) Quit the app, then restart it

**Expected behavior**
The app is not in full screen mode after restarting.

**Observed behavior**
The app is in full screen mode after restarting

**Comment by amyblais** [comment]
Ticket for tracking: https://mattermost.atlassian.net/browse/MM-14097
