### ISSUE TITLE
FreeBSD Desktop Support

### ISSUE THREAD

**Issue by discostur** [mattermost/desktop#546]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question.

---

**Summary**
I want to use Mattermost Desktop Client on FreeBSD. Can anybody provide me a makefile or a short documentation how i can build Mattermost desktop for FreeBSD?

I've only found some discussions about the server version, but not for the desktop client ...

Thanks
Greets
Kilian

**Comment by yuya-oc** [comment]
Unfortunately the framework Electron which we are using doesn't support FreeBSD.

https://github.com/electron/electron/issues/3797
