### ISSUE TITLE
Load more messages throws focus to newest message on channel

### ISSUE THREAD

**Issue by hannu78** [mattermost/desktop#547]
I confirm (by marking "x" in the [ ] below): 

- [x ] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**

Load more messages throws focus to newest message

- Operating System: Windows 10 at least
- Mattermost Desktop App version: 3.7.0
- Mattermost Server version: 3.9.0 ES

- Clear steps to reproduce the issue:
Browse up to old messages on a channel. Click "Load more messages" and focus is thrown to newest message on channel while more messages are loaded. 

**Expected behavior**
Focus stays in the oldest messages where it was before loading more messages. This is how it works on web browser, too.

**Observed behavior**
Focus changes to newest message on channel.

**Possible fixes**

**Comment by jasonblais** [comment]
Thanks @hannu78 for the report! 

This is an issue on the [Mattermost server](github.com/mattermost/platform). It will be fixed with a [major refactoring](https://github.com/mattermost/platform/pull/6501) that is scheduled for Mattermost Server 4.0, released on July 16th

**Comment by jasonblais** [comment]
@hannu78 The PR has been merged and the fix will be available on the July 16th release of Mattermost Server 4.0: https://github.com/mattermost/platform/pull/6501
