### ISSUE TITLE
Voice mail / recording feature to desktop app

### ISSUE THREAD

**Issue by kaksikanaa** [mattermost/desktop#548]
Feature request: 
It would be very nice to have the voice mail recording feature straight in the app in all platforms like Windows, Mac, Linux and iOS. It is possible now only in the Adroid app. All format should be also supported on all platforms eg. sound should be mp3 and videos should be mp4 etc. Or the play support for the different file types should be incluced in all platforms.

**Comment by jasonblais** [comment]
Thanks @kaksikanaa, 

Just read your note again, and realized I had misunderstood. mp3 audio and mp4 video files can be uploaded to the desktop app, and played directly within the app. But you're looking for a voice record directly in the app.

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by jasonblais** [comment]
I'll close the issue here, but you're welcome to contributing the idea to the feature idea forum as noted above. https://mattermost.uservoice.com/forums/306457-general/

Thanks @kaksikanaa again for the feedback!
