### ISSUE TITLE
Switch the status color indicator to the background of the icon

### ISSUE THREAD

**Issue by kaksikanaa** [mattermost/desktop#549]
Feature request:
User icons are okay now on the left side list but would it be even more clear to switch the icon color to white and change to background color for the status? Please check the attached file for a quick and dirty demo.
![userstatusicons_example](https://user-images.githubusercontent.com/15322015/27384398-5f22a494-5697-11e7-88d2-1c0ca63ccb51.png)

**Comment by jasonblais** [comment]
Thanks, appreciate your feedback.  

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](http://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by kaksikanaa** [comment]
Ok, thank you for advice and sorry for inappropriate approach to this at first, I've added it here:
https://mattermost.uservoice.com/forums/306457-general/suggestions/19686445-switch-the-status-color-indicator-to-the-backgroun

**Comment by jasonblais** [comment]
No worries, thanks for the feedback @kaksikanaa! 

I'll close this issue and we can track it in the feature idea forum.

Thanks again :)
