### ISSUE TITLE
New-message indicator duplicated and stuck on all tabs

### ISSUE THREAD

**Issue by LimiLime** [mattermost/desktop#550]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
When I get a new direct message in my MM Mac client, A red circle mark appears on all tabs. I wouldn't mind that, but the issue is that after reading the message, the red mark disappears only from the tab I'm on while all other tabs still show it until I click on the tab and clicked on that DM. I have to do that with each and every tab in order to remove that new message mark.

**Steps to reproduce**
- Operating System: OS X El Capitan v. 10.11.6
- Mattermost Desktop App version 3.7.0 
- Mattermost Server version 3.3.0

Steps:
- receive a DM message from another user on your MM network
- the new-message indicator (red dot with a number inside) will appear on all tabs simultaneously.
- select one tab then in the left nav, select the user that have sent you the message. At that point the red indicator will disappear from the current tabs, but remains on all other tabs. 
- Annoying step: in order to remove that indicator you will need to go into each tab and select that DM message user within each tab. 

It's a problem because that new message indicator will falsely appear in the MM icon on the Apple dock unless you go and do that Annoying step described above. 

**Expected behavior**
When receiving a new DM, Red dot indicator appears on all tabs (or only on tabs in which the sending user is a team member. doesn't matter), and when I click on the user name in the left nav within any tab, the new-message indicator **disappears from ALL tabs**. 
  
**Observed behavior**
See above

**Possible fixes**
No idea. not a programmer.

**Comment by jasonblais** [comment]
Hey @LimiLime, 

Can you help describe your use case -- do you have a different team open in each tab? If so, is it because it's easier to follow conversations across teams, rather than switching between them using the team sidebar on the left-hand side?

**Comment by LimiLime** [comment]
Hi Jason, 

Here’s a screenshot to make it easier. 
I definitely would like to work with Tabs and not have the teams buried in the dots menu on the left. This way I can easily see if there’s a post to each team and quickly toggle between them. 

Cheers,
Limor





Mit freundlichen Grüssen / With Best regards, 

Limor Hader
Sr. Projekt Manager

nuveon GmbH
Büro 2.30
Sonnenstraße 23
80331 München

mobil : +49 (0) 170 / 555 0353
büro:   +49 (0) 9146 / 95990 02

email: limor.hader@nuveon.de
web: www.nuveon.de

**Comment by jasonblais** [comment]
^Also, it looks like the screenshot didn't get attached, but I think I understand where you're coming from,

**Comment by yuya-oc** [comment]
Related: #160 

As Jason described, Mattermost server v3.6 or later would solve the problem.

**Comment by LimiLime** [comment]
The new interface looks awesome! we will make sure to update our server version of MM.

Thank you!


Mit freundlichen Grüssen / With Best regards, 

Limor Hader
Sr. Projekt Manager

nuveon GmbH
Büro 2.30
Sonnenstraße 23
80331 München

mobil : +49 (0) 170 / 555 0353
büro:   +49 (0) 9146 / 95990 02

email: limor.hader@nuveon.de
web: www.nuveon.de

**Comment by jasonblais** [comment]
Glad to hear! In the meantime I'll close the issue @LimiLime, thanks for the feedback!
