### ISSUE TITLE
Windows 10: Uninstalling the app doesn't work

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#551]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Windows 10: Uninstalling the app doesn't work

**Steps to reproduce**

Windows 10; Mattermost Server v3.10; Mattermost Desktop App v3.7

1) Go to Settings > Apps and features
2) Locate Mattermost, and click it to expand options
3) Click "Uninstall"

**Expected behavior**

Mattermost uninstalled.

**Observed behavior**

Some files still exist in `C:\Users\%USERNAME%\AppData\Local\mattermost` and the Start menu shortcut still exists.

**Comment by yuya-oc** [comment]
@jasonblais Would you provide more detailed info about your observed behavior?

I found some files still existed after uninstalling, so I think the uninstaller incompletely worked.

- If the application is running, it finishes. (ok)
- "Mattermost" is removed from the "Apps and features" list. (ok)
- Some files still exist in `C:\Users\%USERNAME%\AppData\Local\mattermost`. (wrong)
- Start menu shortcut still exists. (wrong)

**Comment by jasonblais** [comment]
I just tried and what you described is correct.

Neither 1 or 2 worked for me yesterday (the app continued to run and Mattermost was still listed under "Apps and features") but maybe I didn't perform the uninstallation properly.

Updated the observed behaviour accordingly
