### ISSUE TITLE
Get stuck in Settings page after re-installing the app

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#552]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Mac: Get stuck in Settings page after re-installing the app

**Steps to reproduce**

Mac OSX 10.9; Mattermost Desktop App v3.7; Mattermost Server v3.10

1) Uninstall the app
2) Download the latest version from [the downloads page](https://about.mattermost.com/download/#mattermostApps) and install/open the app.

**Expected behavior**
User can enter their Mattermost instance by clicking one of the servers or the "X" in top right corner.

**Observed behavior**
User is stuck as neither option works. Going to Mattermost > Preferences to reload the page 

**Issue report**

https://pre-release.mattermost.com/core/pl/ofnk4g9tei8dbr81heqx5tu9dy

**Comment by yuya-oc** [comment]
Reproduced.

Steps to reproduce:

1. Quit the app.
2. Remove `~/Library/Application Support/Mattermost` folder.
3. Start the app.
4. Enter the server name and URL.
5. "X" is not available in the Settings page.

As a workaround, you can click the server list item or restart the app.

**Comment by yuya-oc** [comment]
Closed via #555
