### ISSUE TITLE
Mattermost windows client chat window does not take up available space

### ISSUE THREAD

**Issue by Kritner** [mattermost/desktop#553]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
When maximized, the "chat area" does not take up the entirety of the window.

**Steps to reproduce**
Is constant, have tried restarting the app and the system, but persists.

Windows 10
MMD app 3.7.0
MMS Version: 3.7.0  (3.7.3) (I guess?)

**Expected behavior**
Chat area should take up full window.

**Observed behavior**

![image](https://user-images.githubusercontent.com/8814983/27635199-162e6d1c-5bd4-11e7-8d5e-9c321abc61a9.png)

**Comment by jasonblais** [comment]
Thanks @Kritner, it's related to https://github.com/mattermost/desktop/issues/334

Can you click somewhere inside the center channel, then hit `CTRL+0`? This should resize the view to take up the full window.

You can then use the zoom in/out to change the font size.

**Comment by Kritner** [comment]
Hey @jasonblais I just tried that, it reset the zoom level, but is still not maximized to the usable window - even after a restart.

**Comment by Kritner** [comment]
Actually i just tried it again, and it got worse (was probably scaled down a similar amount, on top of what was posted in my initial screenshot).

After a third time, I have gotten back to a maximized chat window.

**Comment by jasonblais** [comment]
Hm okay -- there's an upstream issues in Electron that's causing it: https://github.com/electron/electron/issues/7375

> After a third time, I have gotten back to a maximized chat window.

Does this mean it's now properly in full window?

**Comment by Kritner** [comment]
yeah, i don't know what causes it to initially happen as it has happened several times, but it is corrected at the moment.

**Comment by siebertm** [comment]
I experience this problem since a while now. I cannot reproduce the issue reliably and I cannot reproduce any "fix" to it. Restarting the app worked once, now it doesn't. Same for switching to File->Settings and back.

When I go to "File->Settings", the view takes the whole screen though! When I go back, it switches back to the "broken" size:

![image](https://user-images.githubusercontent.com/2021/29260966-52a229dc-80cd-11e7-92cd-4b5cef9518ce.png)
 (the whole white part should be covered by the chat view, I have the app on full screen!)

**Comment by siebertm** [comment]
I was just able to "fix" the issue by removing `~/.config/Mattermost/Preferences` file. And then, I could reproduce it!

OS: Ubuntu 16.04 LTS
MMD: 3.7.0
MMS: 4.0.0 (4.0.2)

Steps to reproduce: 

* delete `~/.config/Mattermost/Preferences`
* Start Mattermost Desktop
* zoom one step (Ctrl++)
* quit the app (Ctrl+Q)
* Start again

=> Problem, as described above.

Workaround: removal of `Preferences` file.

**Comment by jasonblais** [comment]
Thanks! That's really helpful.

@yuya-oc Could a fix to the above repro steps also fix the issue in https://github.com/mattermost/desktop/issues/334

**Comment by siebertm** [comment]
@jasonblais this is actually the same issue, but I didn't find #334. maybe you close that one and I add my additional finding to #334.

**Comment by jasonblais** [comment]
That works for me @siebertm 👍
