### ISSUE TITLE
Random crash... white windows 

### ISSUE THREAD

**Issue by andrelec1** [mattermost/desktop#554]
I confirm (by marking "x" in the [ ] below): 

- [ X ] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [ X ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ X ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Ramdom crash ... all windows still blank ...
( can't show the debug menu whit alt key ... ) 
**Steps to reproduce**
This is random ... most time i juste retake focus on windows after a long moment of inactivity ...

 This is randome issue

**Expected behavior**
normal mattermost ...
**Observed behavior**
White windows

 ( i edit my post when i reproduce this error )

**Comment by jasonblais** [comment]
@andrelec1 How often does this issue reproduce for you?

**Comment by andrelec1** [comment]
Its not regular, some time, no crash for 2 or 3 days ... and some time, like 10 time in days ...

![image](https://user-images.githubusercontent.com/3273204/27821371-4f738472-60a2-11e7-8824-98d71f1d3be1.png)

**Comment by andrelec1** [comment]
O_o i can see the channel when i move my mouse ...
![image](https://user-images.githubusercontent.com/3273204/27821510-cdabffe0-60a2-11e7-8c71-f946830d7f43.png)

**Comment by jasonblais** [comment]
@andrelec1 Can you try disabling desktop notifications and see if the issue reproduces?

We've had reports where desktop notifications causes temporary freezing of the client, so wondering if it's the same cause.

**Comment by yuya-oc** [comment]
@andrelec1 Possibly the renderer of webview might not work properly. Would you try also `--disable-gpu` command line option?

And for reference, please write about your ubuntu version and desktop environment.

**Comment by andrelec1** [comment]
i use ubuntu mate 17.04,

**Comment by andrelec1** [comment]
i try with the --disable-gpu argument and it work perfectly ... i have a coworker with same error , so i tell her to try with the argument, and this fix the issue like me ....
