### ISSUE TITLE
Show unread chats first on Ctrl+K

### ISSUE THREAD

**Issue by augustnmonteiro** [mattermost/desktop#557]
Today when someone talk to you and you do ctrl+k you have to write the chat name, would be easily just do ctrl+k and down arrow or tab

PS: tab also doesn't move to next chat

**Comment by jasonblais** [comment]
Thanks @augustnmonteiro for the feedback!

Would you like to upvote [a related feature request](https://mattermost.uservoice.com/forums/306457-general/suggestions/17828368-sort-channel-when-switching-with-ctrl-cmd-k-by-unr) so it can be discussed, upvoted and considered for a [help wanted ticket](http://docs.mattermost.com/process/help-wanted.html)?

If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by jasonblais** [comment]
Thanks again @augustnmonteiro!

I'll close this one for now and track the feature request [in our uservoice forum](https://mattermost.uservoice.com/forums/306457-general/suggestions/17828368-sort-channel-when-switching-with-ctrl-cmd-k-by-unr).

PS: You can also switch to the next/previous unread channel on your left sidebar by using the shortcuts ALT+SHIFT+UP/DOWN
