### ISSUE TITLE
Incorrect task name in Windows 10 startup list

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#559]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---
Ticket: https://mattermost.atlassian.net/browse/MM-14095

See original report: https://github.com/mattermost/desktop/issues/542

When Mattermost App is set to be launched at startup, the task manager displays an incorrect name or publisher name. 

#### Steps to reproduce

1. Set Mattermost Windows App to start with Windows.
2. Launch Windows Task Manager (CTRL+ALT+SUPRR)
3. Select Startup Tab
4. Mattermost App is under a group named Update(X) and the Publisher is GitHub

![capture2](https://cloud.githubusercontent.com/assets/18822/26450271/de5ee4bc-4156-11e7-9b11-f2e2ff5fe3d9.PNG)

#### Expected behavior
Instead of Update the name of the process should be Mattermost (same for Publisher)

#### Possible fixes

Run `rcedit` when packaging Windows app and find the code in `electron-builder` to modify the process name.

**Comment by yuya-oc** [comment]
I made [a PR for electron-builder](https://github.com/electron-userland/electron-builder/pull/1860), however it's rejected. It seems that we should not change the meta data.

**Comment by jasonblais** [comment]
Hm, is there a workaround we can do on our end?

**Comment by yuya-oc** [comment]
There is possiblity, but I think it's difficult.

1. Extract a packaged installer.
2. Modify metadata of Update.exe.
3. Re-package into a new installer.

As suggested in the PR, it might be good for us to use nsis installer (#491). And we can also get electron-builder's support for auto-updater I'm investigating

**Comment by jasonblais** [comment]
Oh that's nice. Sounds good.

I think we can leave this ticket for now and work on it at the same time when we get to https://github.com/mattermost/desktop/issues/491.

If it doesn't work, we can consider the alternate option, but I agree it sounds difficult.

**Comment by amyblais** [comment]
Jira ticket for tracking: https://mattermost.atlassian.net/browse/MM-14095

**Comment by esethna** [comment]
No longer valid with v4.4
