### ISSUE TITLE
Add support for basic HTTP authentication

### ISSUE THREAD

**Issue by PiotrZierhoffer** [mattermost/desktop#56]
Electron supports it, as in https://github.com/atom/electron/pull/3250

I added this configuration to app/main.js and it worked, but I'd love having a default with a popup window. Keeping my password unencrypted on hdd is no fun.

Is that even possible with electron?

**Comment by yuya-oc** [comment]
Maybe possible, the API has been just tested at dca9b62cda34025124195de6c31f0f961f19267a.
But Electron doesn't support input dialog such as `window.prompt`, so the app has to implement on its own.

**Comment by mgielda** [comment]
Let me jump in here, I had solved the problem in a not-so-graceful but effective way once for a different app, perhaps this experience can come in handy (did spend some hours testing various libraries which refused to work before coming up with this):

```
var app = require('app');
var BrowserWindow = require('browser-window');

var prompt = require('sync-prompt').prompt;

var name = prompt('Username: ');
var password = prompt.hidden('Password: ');

app.on('login', function (event, webContents, request, authInfo, callback) {
  event.preventDefault();
  console.log("Replacing default auth behaviour.");
  callback(name, password);
});
```

**Comment by yuya-oc** [comment]
Thank you for feedback. I think It will work, however users have to use command-line and keep it opened.

Note: `callback()` can be called asynchronously, so `sync-prompt` might not be necessary. Then, `sync-prompt` is a native module, so it's a little hard to compile release version. (In my environment, Windows 10 + Node 4.2.2 + VS2015 Update1, I could not compile `sync-prompt`.)

**Comment by yuya-oc** [comment]
`readline-sync` might be nice for @mgielda's example. It looks JavaScript.

**Comment by mgielda** [comment]
@yuya-oc indeed it works (sorry it took some time to answer) - so I agree, the updated snippet is:

```js
var readlineSync = require('readline-sync'); //tested on readline-sync 1.4.1

var username = readlineSync.question('Username: ');
var password = readlineSync.question('Password: ', {
  hideEchoBack: true // The typed text on screen is hidden by `*` (default). 
});

app.on('login', function (event, webContents, request, authInfo, callback) {
  event.preventDefault();
  console.log("Replacing default auth behaviour.");
  callback(username, password);
});
```

How should we proceed with that? There needs to be some config option for this I suppose. I agree that doing a graphical version later is a good idea but for now this would be good enough. Should we perhaps propose a pull request?

**Comment by yuya-oc** [comment]
Closed by the commit message. This should not be closed yet.

**Comment by mgielda** [comment]
Sorry! You are right of course. Habit from my own projects.
