### ISSUE TITLE
Inline spell check doesn't preserve case

### ISSUE THREAD

**Issue by alallier** [mattermost/desktop#562]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Spell check doesn't preserve case. If a word is spelled wrong, the spelling suggestions for it are always lowercase.

**Steps to reproduce**

- Operating System: Windows 10
- Mattermost Desktop App version: 3.7.0
- Mattermost Server version: 3.10.0
- Clear steps to reproduce the issue

See GIF below. But spell word wrong, right click on the word notice spelling suggestions are always lower case. Causing you have to go back and correct the case.

![mattermostcasescreenshotpng](https://user-images.githubusercontent.com/13004518/28083686-2abbd9a2-6644-11e7-97c6-fe42e8c378ad.png)

![mattermostcasevideo](https://user-images.githubusercontent.com/13004518/28083555-ba5b40bc-6643-11e7-8817-f38429ae5d0e.gif)

**Expected behavior**

Expect case to be reflected in the spelling suggestions

**Observed behavior**

Case is not preserved in spelling suggestions

**Comment by jasonblais** [comment]
I just noticed this too :)

@yuya-oc do you think this would be an easy fix?

**Comment by yuya-oc** [comment]
If it's okay it depends on the case of first letter, I feel it's not so hard.

Proposal: When the first letter of wrong word is upper case, suggestions' first letters become upper case.

**Comment by jasonblais** [comment]
@yuya-oc That sounds good

If the first letter of the incorrectly spelled word is lower case, will there still be suggestions in upper case as in the attached screenshot?
![image](https://user-images.githubusercontent.com/13119842/28211381-5a78ea40-686a-11e7-8317-25d20b518c90.png)

**Comment by yuya-oc** [comment]
It's `simple-spellchecker`'s behavior. They're originally included in the dictionary file.

**Comment by jasonblais** [comment]
Perfect. Your proposal sounds good then 👍
