### ISSUE TITLE
Font/render size not persisted

### ISSUE THREAD

**Issue by dmke** [mattermost/desktop#564]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**

Changing the font size does not persist accross app restarts.

**Steps to reproduce**

1. open Mattermost Desktop (v3.7.0)
2. hit `Ctrl++` or `Ctrl+-` to change font size
3. close and restart Mattermost Destop

I'm using Debian Jessie v8.9 under GNOME 3.14.4 and Mattermost Server v4.0.2; but neither of this should matter.

**Expected behavior**

The selected font/render size after the app restart (step 3) should be the same as in step 2.

**Observed behavior**

It is not. The font/render size falls back to the default.

**Possible fixes**

Store the last selected font/render size locally upon change.

**Comment by yuya-oc** [comment]
Thanks for feedback. I confirmed that on Windows 10. And the next v3.8.0 would fix the problem. Unfortunately its date is not decided yet.

**Comment by jasonblais** [comment]
@yuya-oc Do you think this was fixed by an Electron update?

**Comment by yuya-oc** [comment]
@jasonblais Ah, yes. I forgot writing that. Electron 1.6.4 fixed zoom resetting. https://github.com/electron/electron/releases/tag/v1.6.4

**Comment by jasonblais** [comment]
Thanks! Sounds good.

@dmke I'll close this ticket -- the fix will be available in Mattermost Desktop App v3.8.

**Comment by dmke** [comment]
Wow, that was fast. Thank you very much!
