### ISSUE TITLE
Client disappears on second screen, even though that screen is not available

### ISSUE THREAD

**Issue by HrFlorianHoffmann** [mattermost/desktop#565]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
The desktop app disappears on the second, unavailable screen, after undocking the notebook.

**Steps to reproduce**

- Windows 10, desktop app release v3.7.0
- Use a notebook in a docking station that connects to two monitors
- Open the app and move it to the secondary screen
- Close the app
- Undock the notebook
- Open the app

**Expected behavior**

The app is displayed on the primary display.

**Observed behavior**

The app is not visible. It's listed in the task bar as running. Windows-Tab previews its window. Selecting the app in the Windows-Tab list shows that the app is actually displayed, but on the unavailable secondary screen, outside of the available screen's range. Unfortunately, it's not possible to get the window back to the primary screen, even using shortcuts like Windows-Left etc.

**Possible fixes**

No idea about the code. But looks like the app stores its last coordinates somewhere and uses them on next startup, even if those coordinates are not good anymore.

**Comment by jasonblais** [comment]
@yuya-oc @jnugh Looks like this is still an issue

This is the original PR that fixed it (at least partially) https://github.com/mattermost/desktop/pull/509

**Comment by yuya-oc** [comment]
Not reproduced for me on Windows 10. But possibly there might be a special case we didn't cover.

@HrFlorianHoffmann To make sure, would you tell us about your environment?

- Resolution and scaling for each monitor - I tested with 3840x2160@150% and 1920x1080@100%.
- Does "close" mean "x" button at top right of the window?

**Comment by jasonblais** [comment]
Hey @HrFlorianHoffmann, 

We haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, reopen this issue with the above informatio and we'd be glad to help you where we can. If we can help clarify the questions, let us know.
