### ISSUE TITLE
On macOS, Notifications dismiss themselves even when they are configured to the Alert type

### ISSUE THREAD

**Issue by jake-griffin** [mattermost/desktop#566]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
On macOS, Notifications dismiss themselves even when they are configured to the Alert type

**Steps to reproduce**

I am using macOS Sierra (10.12.5) and Mattermost Version 3.1.0 (according to About Mattermost in the Mattermost menu) or 3.7.0 (in the Mattermost -> About Mattermost Application Menu).. not sure which of these is correct or if one is server version and the other is client version.

1. Configure Mattermost notifications in OS X Notifications preferences to be of the Alert type
2. Minimize or close the Mattermost window
3. Have someone send you a message, triggering a notification

**Expected behavior**
The notification appears and remains until interacted with. (per this link - http://osxdaily.com/2014/01/29/change-notifications-banner-time-mac-os-x/ - "a banner will slide in and slide out of the Mac screen without interaction (or you can swipe on it to dismiss), while alerts require some sort of user involvement with manually closing or rescheduling the alert")

**Observed behavior**
The notification appears as expected, but then dismisses itself after a few seconds.

**Possible fixes**
Not sure

**Comment by jake-griffin** [comment]
Note: this was originally filed in mattermost/platform, but I was asked to refile it here: https://github.com/mattermost/platform/issues/7026#issuecomment-317977322

**Comment by jasonblais** [comment]
Thanks @jake-griffin! 

Thoughts @yuya-oc? 

Not sure if it's related to https://github.com/mattermost/desktop/issues/304 or #539

**Comment by yuya-oc** [comment]
Related to #539. Surely this have been confusing point because there are two kind of preferences for desktop notifications.
Now the application seriously follows notification duration of webapp, so notifications close.

**Comment by jasonblais** [comment]
Thanks @yuya-oc -- how does the notification system differ from the webapp? Does the webapp just always follow the Mattermost notification settings

----

On a side note:

> I am using macOS Sierra (10.12.5) and Mattermost Version 3.1.0 (according to About Mattermost in the Mattermost menu) or 3.7.0 (in the Mattermost -> About Mattermost Application Menu).. not sure which of these is correct or if one is server version and the other is client version.

That's good feedback @jake-griffin and we should make this better -- ticket here https://github.com/mattermost/desktop/issues/474

@yuya-oc Wondering if we could add the desktop app version to the server "About Mattermost" dialog? That way there wouldn't need to be two different ones, and it might be a simpler solution than creating a custom one for the desktop app.

**Comment by yuya-oc** [comment]
@jasonblais The difference is how to close notifications. webapp explicitly calls `Notification.close()` function to follow duration settings. This is the reason why native notifications close on macOS. (It's contrasting with Windows. Windows' notifications have about 7 seconds limitation.)
So possibly webapp should ignore duration settings when the client is desktop app.

About version info, it's possible in webapp. The User-Agent has app version, `Mattermost/<VERSION>`. Please see https://github.com/mattermost/platform/blob/master/webapp/utils/user_agent.jsx#L20-L24 .

**Comment by jasonblais** [comment]
Thanks for the additional info on both! Very helpful.

I'll consider bringing these points up to the platform team

**Comment by johnnyutahh** [comment]
Quoting https://github.com/mattermost/desktop/issues/566#issuecomment-318642334 ...

Is there a way to change Chrome's "duration settings" somehow, to effectively generate a workaround while MatterMost (potentially) works to develop a longer-term fix?  Or is this not a worthwhile, feasible path?

**Comment by amyblais** [comment]
Ticket for tracking: https://mattermost.atlassian.net/browse/MM-14134
