### ISSUE TITLE
Support GSSAPI/Kerberos

### ISSUE THREAD

**Issue by trothwell** [mattermost/desktop#567]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**

Kerberos authentication to server is unsupported with app.

**Steps to reproduce**

Reproduceable for local server.

**Expected behavior**

Utilitize `kinit` certificate to authenticate to server.

**Observed behavior**

Does not perform any kerberos authentication.

**Possible fixes**

Use v8's auth mechanism to support Kerberos.
https://github.com/electron/electron/blob/master/docs/api/net.md

**Comment by jasonblais** [comment]
Thanks, appreciate your feedback @trothwell! 

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by yuya-oc** [comment]
@trothwell Would you also write about an environment we should assume? I'm not sure what environment is necessary for this. And, basically the desktop app can use only same authentication systems as well as Chrome browser.
