### ISSUE TITLE
Insecure connection produces hundreds of messages

### ISSUE THREAD

**Issue by LarsKumbier** [mattermost/desktop#569]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---
Jira ticket: https://mattermost.atlassian.net/browse/MM-14094

**Summary**
When a certificate becomes invalid during mattermost being active, a new message for the insecure connection will pop up every few seconds - leaving the desktop with hundreds of those messages.

**Steps to reproduce**

- Tested on ubuntu gnome 17.04, Mattermost-Desktop 3.7.0
- Run your own mattermost server
- create a server certificate with a lifetime of +5min or so
- install the certificate on the server, restart
- connect Mattermost-desktop to the server
- wait

In my setup, I used letsencrypt and the cert-update-routine did not work. Left for the weekend, came back after, got hundreds of new messages on the client.

**Expected behavior**

To get only *one* message informing me of the problem.

**Observed behavior**

Having hundreds of messages informing me of the problem.

**Possible fixes**

**Comment by jasonblais** [comment]
Thanks for the report! 

@yuya-oc any thoughts on this one?

**Comment by yuya-oc** [comment]
The confirmation dialog only consider the situation when the application try to connect to the server. But the situation that the certificate expires while the application is running haven't not been considered.
Once invalid certificate is registered to the application data by using the dialog, it would be gone after restarting the application.

**Comment by amyblais** [comment]
Jira ticket for tracking: https://mattermost.atlassian.net/browse/MM-14094

**Comment by JorisPLA7** [comment]
Details : It's also **impossible to close the software** without killing from an external tool, or trusting the unsecure certificate.  

(at least from Gnome desktop env)

**Comment by Willyfrog** [comment]
> Details : It's also **impossible to close the software** without killing from an external tool, or trusting the unsecure certificate.
> 
> (at least from Gnome desktop env)

it also happens on osx, the original issue should be fixed either in 4.4 or future 4.5, but I'll open a [new ticket](https://mattermost.atlassian.net/browse/MM-23818) for this

**Comment by KlavsKlavsen** [comment]
this is still a HUGE problem - and I have to remove the mattermost server (of several I am connected to with my mattermost-desktop app) - to even be able to actually use mattermost again :(

**Comment by KlavsKlavsen** [comment]
I see the backend issue has been closed ? I am running snap: mattermost-desktop       4.5.3 - which is the latest afaik ?

**Comment by KlavsKlavsen** [comment]
I can choose "trust insecure connection" - but I can't say "stop connecting" or disregard the message (if I f.ex. wanted to wait until issue was fixed to use that server again.. And how do I remove this "trust" that I now have to manually remove so the SSL security layer actually works again?

**Comment by Willyfrog** [comment]
Hello @KlavsKlavsen 
Thanks for reporting.

To remove trust, you'll have to go to the folder where configuration is stored. There should be a file called trustedcertificates.json (or trusted connections I can't check my machine right now) and remove the entry. It is a bit cumbersome, but for the time being is the only way. 

Regarding your issue,are you getting a ton of messages when the server is trusted/not trusted? Or just one per server? If you could give us a description of the symptoms and some info of your setup we can try and figure out what are the next steps.

**Comment by KlavsKlavsen** [comment]
Its when its set to NOT ignore certificate warnings - that it keeps popping up the same error - so I can't use mattermost-desktop app AT ALL - on any of the servers connected.
If I choose "more details"-> trust, then it goes away - but thats a very very bad solution - I'd rather just wait until cert is fixed :)

**Comment by Willyfrog** [comment]
So, what you are asking for is a way to ignore an invalid certificate without connecting to it, is that right? So you would have the server configured on your settings, but no connection is made to it and it doesn't ask to trust it.

**Comment by KlavsKlavsen** [comment]
Well.. f.ex. an option "delay connection for 30 min" - or "disable automatic reconnect" - which would make mattermost-desktop stop trying to connect (in an inifinity loop) - and not adding "trust insecure cert" in settings :)
If one choose "disable automatic reconnect" - if I choose reload - it could then connect and complain as usual - if issue isn't fixed.

**Comment by devinbinnie** [comment]
Fixed as per JIRA ticket.
