### ISSUE TITLE
Make notifications for multi-person direct messages work the same as for single-person direct messages.

### ISSUE THREAD

**Issue by stihl716** [mattermost/desktop#572]
I confirm (by marking "x" in the [ ] below): 

- [ x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [ x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Make notifications for multi-person direct messages work the same as for single-person direct messages.

**Steps to reproduce**
- Operating System: Windows 7 Enterprise SP1 
- Mattermost Desktop App version: 3.7.0
- Mattermost Server version: 4.0.0  (4.0.2)

- Scroll down to the bottom of the Direct Message section in the channel bar and click More...
- Choose 2 names to send a message to and click Go
- Type a message in the chat window

**Expected behavior**
On the recipients' clients, the taskbar icon should show a red dot with a number (eg: 1) 
![image](https://user-images.githubusercontent.com/5540347/29177335-74600fbc-7dbc-11e7-8232-ee95ae349e51.png)

On the system tray icon, a red dot should appear.
![image](https://user-images.githubusercontent.com/5540347/29177352-81e31af8-7dbc-11e7-9e05-da50761289f5.png)

**Observed behavior**
On the recipients' clients, the taskbar icon shows a red dot with a white dot in the middle
![image](https://user-images.githubusercontent.com/5540347/29177208-17e36dba-7dbc-11e7-947d-770f75386d1d.png)

On the system tray icon, a blue dot appears.
![image](https://user-images.githubusercontent.com/5540347/29177293-5819bd58-7dbc-11e7-8a22-4fe6b6aabd06.png)

**Additional Information**
I find that users respond to direct messages more readily than group channels.  The way the notifications are currently working, the notifications for multi-person DMs look more like channel notifications and people aren't getting back to them as quickly.  Sometimes, not at all.

**Comment by jasonblais** [comment]
Thanks @stihl716 , appreciate your feedback! Sounds like this change would also apply to the browser.

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by stihl716** [comment]
Done.

https://mattermost.uservoice.com/forums/306457-general/suggestions/20503204-make-notifications-for-multi-person-direct-message

**Comment by jasonblais** [comment]
Thanks! I'll close for now and we can track in the feature idea forum.
