### ISSUE TITLE
Reloading page makes it blank after some secs

### ISSUE THREAD

**Issue by yuya-oc** [mattermost/desktop#573]
From @S6066 at mattermost/platform#7242

**Summary**
Sometimes I have a DNS error, or a Network Changed one, and I have to reload (Ctrl + R) the page.
When doing that, after some seconds the page becomes blank one second and reload again

https://youtu.be/pyeaz3hp5b4

**Steps to reproduce**
- Operating System: Windows 10 x64
- Mattermost Desktop App version: 3.7.0
- Mattermost Server version: 4.1.0
- Clear steps to reproduce the issue
  1. Make a DNS error or a Network Changed one. (More concrete step is needed to reproduce the situation.)
  2. Reload the page with `Ctrl+R`.
  3. The page reloads again after some seconds.

**Expected behavior**
The reloading should happen only once.

**Observed behavior**
The page reloads twice.

**Possible fixes**
?

**Comment by yuya-oc** [comment]
@S6066 Please let me confirm. The application should automatically reload the page when the app has become online from offline. Do you need to press Ctrl+R when you meet DNS or Network Changed error?

**Comment by S6066** [comment]
@yuya-oc Yep, I need to press Ctrl+R to reload when meeting the error
Operating System: Windows 10 x64 (16xx, probably 1607)
To reproduce the issue, Exit mattermost if opened, disable wifi, start Mattermost, enable wifi, press Ctrl+R

**Comment by yuya-oc** [comment]
The problem reproduced for me on Windows 10. The error is ERR_NAME_NOT_RESOLVED (-105). When the error is ERR_INTERNET_DISCONNECTED (-106), the app properly reloads the page automatically.

The app automatically reloads the page every 30 seconds as another mechanism to repair the error. So I feel  it's wrongly working when the page is manually reloaded.

**Comment by jasonblais** [comment]
> The app automatically reloads the page every 30 seconds as another mechanism to repair the error.

**Comment by yuya-oc** [comment]
@jasonblais Yes, if the error is gone in that time, the user will see correct reloaded webapp. However I think the automatic reloading is not canceled when the page is manually reloaded. So the page reloads again after Ctrl+R is done.

**Comment by jasonblais** [comment]
Okay cool. Do you have an idea on how much work it is to fix? Wondering if we should fix it in 3.8

**Comment by yuya-oc** [comment]
It looks easy. I will test my fix tomorrow.
