### ISSUE TITLE
Mac: Help > About Mattermost displays a confusing version number

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#581]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Mac: Help > About Mattermost displays a confusing version number

**Steps to reproduce**

Mac; Mattermost Desktop App v3.7.0; Mattermost Server v4.1.0

Go to Help > About Mattermost.

**Expected behavior**

Version number is displayed as `3.7.0`

**Observed behavior**

Version number is displayed as `3.7.0 (3.7.0.3.7.0)`

![image](https://user-images.githubusercontent.com/13119842/29947513-07e99714-8e78-11e7-8d78-12d41436dc3a.png)

**Comment by yuya-oc** [comment]
The X part of 3.7.0.X is added by electron-builder. For example, it becomes 3.7.0.100 when the app was built in CircleCI's build 100.

The parameter is derived from `BUILD_NUMBER` environment variable of Jenkins. We need to fix the job.

**Comment by yuya-oc** [comment]
Note: The job had been already fixed. We can check this when cutting next RC.

**Comment by jasonblais** [comment]
Would it be fixed in one of the PR test CI artifacts? If so, we could check it from there

**Comment by yuya-oc** [comment]
There are no changes in source code to solve this. Need to execute jenkins job.

**Comment by jasonblais** [comment]
@yuya-oc This is fixed for me on 4.0.0-RC1
