### ISSUE TITLE
Mac: When the app auto-starts, app page opens on screen instead of being minimized to Dock

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#583]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Mac: When the app auto-starts, app page opens on screen instead of being minimized to Dock

**Steps to reproduce**

Mac; Desktop App v3.7.0; Mattermost Server v4.1.0

1) Enable the auto-start option on the desktop app.
2) Close the app and restart your machine.

**Expected behavior**
App launches automatically, but remains minimized on the Dock until the user actually clicks on the app.

**Observed behavior**

App launches automatically, and loads the page on screen. Two issues:
 - interferes if the user is viewing/interacting on another window
 - app is not in focus, so keyboard shortcuts and other actions don't work until the user actually clicks on the app.

**Comment by yuya-oc** [comment]
Just for note: auto-start option is not supported in the desktop app. However users can launch the app on login by using Dock icon's right-click option.

**Comment by yuya-oc** [comment]
I think it's solved via #853.
