### ISSUE TITLE
Embedded markdown images with `http://` doesn't render in mattermost/desktop

### ISSUE THREAD

**Issue by it33** [mattermost/desktop#59]
Chrome 48/Win7: 

The markdown `![d](http://img.lum.dolimg.com/v1/images/tfa_poster_wide_header_adb92fa0.jpeg?region=61%2C271%2C1937%2C1089&width=600)` in a message renders on the web, but not on mattermost/desktop.

![image](https://cloud.githubusercontent.com/assets/177788/13660924/314175c0-e643-11e5-891f-fb14addb44c9.png)

**Comment by yuya-oc** [comment]
It looks same as #35 and #55 . For now, one of `webview.setAttribute('disablewebsecurity', true)` or `--allow-running-insecure-content` resolve this.

**Comment by it33** [comment]
Perfect, thanks @yuya-oc!

**Comment by frdmn** [comment]
Did anyone of you guys got this (refering to Yuya's solution possibilities) working?

I already spent hours trying to implement something like that but still without any luck. However, I suck at reactive DOM stuff, so there's that.

Thank you! :)
