### ISSUE TITLE
Suppress the hovering URL status bar

### ISSUE THREAD

**Issue by jsg2021** [mattermost/desktop#610]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Feature request: Many electron apps suppress the browser's status bar in the bottom left corner, it would be awesome if mattermost's app did so as well. (many links obscure input area (esp the typing indicator)

**Steps to reproduce**
Hover over any link/nav element

**Expected behavior**
No status bar shown

**Observed behavior**
Chromium's status bar is visible

**Comment by yuya-oc** [comment]
Electron doesn't have any status bar. The bar we call "Hovering URL" was manually implemented in #276(#372) because a markdown link can hide its actual URL.

@jasonblais Recently I have not watched the server side of #427 though, should we reopen this?

**Comment by jasonblais** [comment]
There is an open PR here, so it should be resolved in Mattermost v4.4: https://github.com/mattermost/mattermost-webapp/pull/53

**Comment by jsg2021** [comment]
Ah, thanks for the update.  It looks nearly identical to chrome's bar. :)  If the scope of that bar could be restricted to links in message bodies that would be awesome...and if that bar could be more of a tool tip than a bottom left corner bar... even better.
