### ISSUE TITLE
App window doesn't save "floating" app position on Windows

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#617]
I confirm (by marking "x" in the [ ] below): 

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
Windows: App window doesn't save "floating" app position

**Steps to reproduce**

Windows 7; Mattermost Desktop App v3.7.1; Mattermost Server v4.2

1) Hit `Windows`+`Left Arrow` to cycle through
 - Left half of screen
 - Right half of screen
 - "Floating" on screen (suppose this is in the right edge of the screen)
2) Once at the "Floating" state, move the window to the middle of the screen
3) Exit the app
4) Relaunch the app

**Expected behavior**

App relaunches in the "Floating" state, in the middle of the screen.

**Observed behavior**

App relaunches in the "Floating" state, but in the right edge of the screen.

**Possible fixes**

There is a possibility that Windows AeroSnap (`Windows`+`Left Arrow` key) might internally cause a strange window state. 

Another option is to use the Electron's `move` event: https://electron.atom.io/docs/api/browser-window/#event-move

**Comment by amyblais** [comment]
Ticket for tracking: https://mattermost.atlassian.net/browse/MM-14135

**Comment by boxed** [comment]
On macOS it just always starts in the middle of the screen with the same size. It never remembers the position at all.

**Comment by devinbinnie** [comment]
This issue is resolved.
