### ISSUE TITLE
Sorting channels & direct messages by last sent/received date

### ISSUE THREAD

**Issue by DerkBusser** [mattermost/desktop#620]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**
When you have a large number of channels or conversations, navigating between different conversations is cumbersome due to the fact that conversations are sorted by alphabetic order. Preferably this list is sortable by last message date and might have a preview of the last send/received message. 

This is common practice in chat applications such as whatsapp, messenger, etc. 

**Steps to reproduce**
MAC OSX Desktop v3.7.1

**Comment by MusikPolice** [comment]
Hey @DerkBusser, thanks for the report. This seems like a feature request, rather than a bug report, so the correct place to post it is [on our Uservoice forum|https://mattermost.uservoice.com/forums/306457-general/]. If other users agree with you, the request will be upvoted, and we'll implement it.

**Comment by robertograzzi** [comment]
I would also need the chronological ordering of data chat to be implemented
