### ISSUE TITLE
Cannot find a permalink

### ISSUE THREAD

**Issue by fishbike** [mattermost/desktop#622]
I confirm (by marking "x" in the [ ] below): 

- [x ] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**

**Steps to reproduce**

Using desktop 3.7.1, there is no way to navigate to a permalink (the way I can in a browser address bar). This makes collaborating with inbound traffic (e.g. a reference in an email) very hard, I end up switching to a browser. (I realize this might be borderline feature request, but the lack of handling is specific to this client, or my ignorance of how to use it.)

1. Get permalink from existing post
2. Switch to different channel, same team
3. Paste full link (or just token ID) into search 
4. Nothing found

**Observed behavior**

![mmdesktop permalink search](https://user-images.githubusercontent.com/26098136/31555268-aaa705f6-b040-11e7-913f-89074eca0c56.png)

**Comment by yuya-oc** [comment]
@jasonblais I have two questions for this.

- Is deeplinking also available for permalink (by using `mattermost://` instead of `https://`)?
- Can webapp search the message via permalink by implementing something?

**Comment by jasonblais** [comment]
@yuya-oc 

1) Once https://github.com/mattermost/desktop/pull/616 is merged, deeplinking on permalinks should work, although that case should be tested.
2) No, there isn't a way to search for a message via permalink. I think that would be difficult, as it's a text-based search

@fishbike What is your use case for navigating to the permalink? You mentioned `This makes collaborating with inbound traffic (e.g. a reference in an email) very hard` -- is it because
 - you receive an email notification
 - copy the permalink included in the email
 - want to easily access the permalink in the app?

**Comment by fishbike** [comment]
@jasonblais Yes, your description of the use case is correct: if one user wants to send another user a permalink, there is no way in the app for the recipient to navigate to the post. (As I said in original comments, search might not be the best way, but was the only approach I found.)

**Comment by jasonblais** [comment]
Thanks @fishbike, 

If the user sends another user a permalink, wouldn't that be included in the message itself? Then clicking the permalink should redirect the user to the relevant post.

**Comment by jasonblais** [comment]
PS: @yuya-oc - deeplinking is available for permalinks with #616, I tested it.

**Comment by fishbike** [comment]
No, sorry @jasonblais that is not what happens. Not sure how I'm failing to get my point across, but if a user takes a permalink from mattermost and shares it _anywhere outside mattermost_ (e.g. in an email), there is no way to "click back into" the desktop app. As I said before, yes, you can simply load the permalink into a browser address bar (assuming you're connected to mattermost) and jump right to it. Again, the discrepancy is in the desktop application.

**Comment by jasonblais** [comment]
Sorry @fishbike, I see it now.

@yuya-oc Wondering if you'd have any thoughts on this? #616 adds the ability to deep link into an app, but I don't see an easy way to extend that feature to support this use case.

**Comment by yuya-oc** [comment]
@jasonblais I can think two choices.

- Add a dialog (and shortcut) to enter the permalink. The app can treat it as deeplinking.
- Once #628 is resolved, a user would be able to open the permalink via Browser landing page.

**Comment by jasonblais** [comment]
@yuya-oc Would resolving #628 work, since it'll only work for `mattermost://...` protocols, whereas the permalink is in the form `https://...`?

The shortcut idea is interesting though.

**Comment by gnbAT** [comment]
I'm also interested in this feature because I prefer the desktop app over using the browser, but it isn't currently possible to navigate to permalinks posted in other places like e-mail or our bug/project tracking app. At a minimum I would expect searching for the permalink's hashcode in the desktop app would return the link target.

**Comment by jasonblais** [comment]
@gnbAT Thanks for the feedback!

Search would be an option, but I could see users hitting this issue if they get a link to a channel, e.g. `https://mattermost.com/myteam/channels/mychannel`. So search might not cover that use case.

If there are additional ideas, would love to hear!

**Comment by yuya-oc** [comment]
@jasonblais Ah, probably I had misunderstanding. I had thought that the browser shows a landing page when opening `https://` permalink. In that case, the landing page can convert the permalink into `mattermost://` link.

**Comment by jasonblais** [comment]
Okay cool. We can think about it more with #628, since a pull request for that should be coming soon.

In the meantime, adding `Needs Design` label.

**Comment by amyblais** [comment]
Closing via feature request ticket: https://mattermost.uservoice.com/forums/306457-general/suggestions/36828142-desktop-app-ability-to-find-a-permalink.
