### ISSUE TITLE
Rename variables from "team" to "server" in source code

### ISSUE THREAD

**Issue by yuya-oc** [mattermost/desktop#623]
I confirm (by marking "x" in the [ ] below): 

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

Jira: https://mattermost.atlassian.net/browse/MM-14093

**Summary**
Rename variables from "team" to "server" in source code.
The name has been originally since there is no team side bar in webapp. In that time, the app need to handle "team" URL (https://SERVER/TEAM) to show multiple teams in the single window. 
Now it's confusing so we need to rename for readability.

NOTE: There is a distinction between `server` and `team`, some of the code is actually talking about `server` when using `team`, however, the MM webapp actually has the concept of a `team`, so some uses of `team` in the code should stay as `team`.  Please reach out if this is difficult to determine!

**Possible fixes**
- Rename variables by searching.
- Consider upgrading `config.json` schema version.

**Comment by thepill** [comment]
would like to do this as my first contribution and getting to know the project :)

**Comment by amyblais** [comment]
Jira ticket for tracking: https://mattermost.atlassian.net/browse/MM-14093.

**Comment by deanwhillier** [comment]
Updated the summary with an important note about `server` vs. `team`.

**Comment by alphaninja27** [comment]
Copy the entire code on a text editor and then search for keywords, and change accordingly, or send me the code I shall do it for you.

**Comment by harika551** [comment]
I would like to solve the issue

**Comment by devinbinnie** [comment]
@harika551 Are you still planning on working on this?
