### ISSUE TITLE
Switch channels  wrong placement 

### ISSUE THREAD

**Issue by andrelec1** [mattermost/desktop#624]
I confirm (by marking "x" in the [ ] below): 

- [x ] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md). 

---

**Summary**

when you resize the windows, the block "switch channels" doens't stick to the bottom of the list 

Os : ubuntu
Version client : 3.5.0

**Comment by andrelec1** [comment]
![image](https://user-images.githubusercontent.com/3273204/31620703-3a740892-b298-11e7-9100-26b92abe7b93.png)

**Comment by jasonblais** [comment]
@andrelec1 Can you try to see if this reproduces on the browser?

**Comment by andrelec1** [comment]
yes, i can't reproduces this bug on browser ...

**Comment by jasonblais** [comment]
I see. Can you help with one more step by downloading the latest version of the desktop app? v3.5.0 was released a while ago, so the issue might have been resolved since.

You can download v3.7.1 here: https://about.mattermost.com/download/#mattermostApps

**Comment by andrelec1** [comment]
HO , the v3.7.1  fix the bug !
