### ISSUE TITLE
Add a server landing page when deep linking to an app when it's not yet installed

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#628]
Add a server landing page when deep linking to an app when it's not yet installed

Follow-up to https://github.com/mattermost/desktop/pull/616. @dmeza has a prototype version ready.

**Comment by dmeza** [comment]
@jasonblais a first version is here: https://github.com/mattermost/mattermost-webapp/pull/208
I'm sure you'll want to change the design of the page and will have questions.
