### ISSUE TITLE
Message too long makes MM freeze

### ISSUE THREAD

**Issue by bmtheo** [mattermost/desktop#631]
#### Summary

Mattermost freezes when the message is too long

#### Steps to reproduce

Type a message too long (over 4000 characters) then press enter
Mattermost freezes

#### Expected behavior

Nothing or any animation to show the message "Your message is too long. Character count: 10466/4000" even more (flashing, red, anything...)
But not freezing

#### Observed behavior (that appears unintentional)

Mattermost freezes
You can't click anywhere (change channels etc...)

You have to quit mattermost
Kill Mattermost process in the task manager
Restart mattermost

#### Environment

Windows
Mattermost desktop
Version 3.4.0

![image](https://user-images.githubusercontent.com/31310846/31811650-99a4ac82-b580-11e7-9698-dffaa947249f.png)

**Comment by jasonblais** [comment]
Thanks @bmtheo! Can you try downloading the latest version (v3.7.1) to see if the issue gets resolved? https://about.mattermost.com/download/#mattermostApps

If it still reproduces on the latest release, can you try to see if it reproduces on the browser (say Chrome or IE11)

**Comment by bmtheo** [comment]
It's ok for Chrome (the message is highlighted in yellow with a slow fade away)

![image](https://user-images.githubusercontent.com/31310846/31824282-da114342-b5ae-11e7-9235-d4cf89c52b94.png)

I'll try it out on the desktop app once it's updated and I will get back to you

Thanks for the answer

**Comment by bmtheo** [comment]
Ok also corrected in the 3.7.1 desktop version

Thanks

**Comment by jasonblais** [comment]
Ah, glad to hear it's resolved! Thanks for following up

**Comment by pLesur** [comment]
Experiencing this on Ubuntu 16.04, version 4.0.0...
