### ISSUE TITLE
Set correct spellchecker language for non en-US locales

### ISSUE THREAD

**Issue by yuya-oc** [mattermost/desktop#632]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
en-US is chosen regardless of user's system locale.

See https://github.com/mattermost/desktop/issues/527#issuecomment-338571447 and later comments.

**Steps to reproduce**
Use non en-US and supported locale: one of fr-FR, de-DE, es-ES nl-NL

**Expected behavior**
Set correct language for spellchecker on installation of v3.7 or later.

**Observed behavior**
en-US is chosen.

**Possible fixes**
Call `app.getLocale()` after `app.on('init')` event.

**Comment by jasonblais** [comment]
@yuya-oc Will you check if this issue is fixed with https://github.com/mattermost/desktop/pull/651?

**Comment by yuya-oc** [comment]
@jason Unfortunately no. Surely that helps to solve the problem, but it’s not enough.

**Comment by jasonblais** [comment]
@yuya-oc Cool - moved back to v4.1. Thanks for checking

**Comment by yuya-oc** [comment]
Closed by #731
