### ISSUE TITLE
Mattermost and Thunderbird

### ISSUE THREAD

**Issue by LAfricain** [mattermost/desktop#634]
This not really a bug, I would like to know if it is possible to use mattermost on Thunderbird as client?
I don't find information about this feature, but I saw thunderbird in the [list of clients](https://docs.mattermost.com/install/requirements.html#client-software).

**Comment by MusikPolice** [comment]
Thunderbird is listed as an email client, as in you can use it to receive email sent by the system. As far as I know, there is no way to use Thunderbird as a UI for Mattermost.

**Comment by LAfricain** [comment]
Ok thanks!

**Comment by hlesesne** [comment]
I’m fairly certain you can open additional tabs (chrome or chromium) and I bet you could pin that with mattermost web client.

**Comment by hlesesne** [comment]
I was able to do it using the Open In New Tab plugin, but I haven't figured out how to pin it.
