### ISSUE TITLE
OSX: tri-tone sound playing instead of Mattermost "ding" sound

### ISSUE THREAD

**Issue by philip-peterson** [mattermost/desktop#636]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Mac OSX "installation finished" (aka tri-tone) sound plays every time there is a Mattermost notification.

**Steps to reproduce**

Using Mattermost app on any OSX system, have a friend send you a message when the app is not focused while the volume is on.

**Expected behavior**
Mattermost ding sound will play.

**Observed behavior**
OSX Tri-tone sound will play.

**Possible fixes**
I have a PR that fixes this issue. Just wanted to create a ticket first in case someone has an objection.

**Comment by amyblais** [comment]
Closing via feature request: https://mattermost.uservoice.com/forums/306457-general/suggestions/8686084-change-notification-sound.
