### ISSUE TITLE
Update scr/package.json dependancies

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#639]
Update scr/package.json dependancies.

Also update the following to take security updates:
 - mocha: v3.5 https://github.com/mochajs/mocha/releases/tag/v3.5.0 (since released v3.5.3 and others)
 - url-loader: 0.6.0 https://github.com/webpack-contrib/url-loader/releases/tag/v0.6.0 (since released v0.6.2)
 - webpack-dev-server: 2.5.0 https://github.com/webpack/webpack-dev-server/releases/tag/v2.5.0 (since released 2.5.1 and others)

**Comment by jasonblais** [comment]
^@yuya-oc There were two others that I forgot to mention on pre-release, url-loader and weboack-dev-server

**Comment by yuya-oc** [comment]
Closed via #642
