### ISSUE TITLE
macOS desktop client sometimes blanks out swathes of the display

### ISSUE THREAD

**Issue by kraigu** [mattermost/desktop#641]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Steps to reproduce**
OS: macOS 10.13
Desktop App version: 3.7.1
Server version: 4.3.0 (4.3.1)

Unfortunately I can't give any clear steps to reproduce. All I can really say is that, after the client has been connected for some time (perhaps a day or two) the client display will wipe text, images, etc, apparently randomly. Waving the mouse around will sometimes cause text or images to disappear or reappear, although do it enough and eventually almost everything disappears. Please see included (redacted) screenshot for an example.
![screen shot 2017-11-03 at 8 15 03 am](https://user-images.githubusercontent.com/1298068/32373606-6c4d947e-c070-11e7-8e74-31eaaf5d052f.png)

I do not typically use the browser interface, so I can't say if it happens there or not.

Since it may be relevant - I've seen odd display behaviour with such systems - I'm running an iMac with a couple of external displays connected.

**Comment by kraigu** [comment]
Somebody has just told me about "clear cache and reload" - I'll try that next time. Previously simply restarting the client has worked.

**Comment by kraigu** [comment]
Clear cache + reload works. I presume that means some problem with Electron?

**Comment by yuya-oc** [comment]
I'm not sure about this. If the server was recently upgraded, our cache-purging might not work well now. Otherwise, I think Electron accidentally saved wrong caches due to some reason.

**Comment by jasonblais** [comment]
@yuya-oc Is there anything we can investigate or debug?

**Comment by yuya-oc** [comment]
@jasonblais Looks difficult. We already have cache-purging in both of webapp and desktop. So either of them should work in almost cases.

If more measures are needed, how about clearing caches when `X-Version-Id` has been changed? (if the parameter never changes while using same server version)

**Comment by jasonblais** [comment]
> If more measures are needed, how about clearing caches when X-Version-Id has been changed? (if the parameter never changes while using same server build)

@yuya-oc Does this mean we'd purge cache on server upgrade?

**Comment by yuya-oc** [comment]
@jasonblais Yes. And I think it would be done by webapp, so I have doubt whether more fixes are needed.

**Comment by jasonblais** [comment]
@kraigu Does it reproduce for anyone else on your team? Also, you mentioned `I've seen odd display behaviour with such systems` - does this mean you've sometimes encountered with other apps on your Mac?

**Comment by kraigu** [comment]
Nobody else has said it's happened to them. We have a relatively small team and I'm not sure how many are using the desktop client vs web.

re odd display behaviour - Not so much with other apps, but with the OS itself. Although it turns out my most recent display issues - after unlocking from locked screensaver, one of them won't show anything - turns out to have been hardware-related. The display died completely after I filed this request. I've had OS-related issues in the past, flickering/odd lockups with multiple displays attached - but those were 10.12 and older, I haven't seen those specifically yet in 10.13.

Sorry, I know this isn't a lot of help.

**Comment by jasonblais** [comment]
@kraigu All that is really helpful. Is this issue new and only started happening recently, do you remember?

**Comment by kraigu** [comment]
@jasonblais Sorry, I missed your followup question. I can't really say, since I only started using the client about two months ago. So it's new, but from my point of view, it's also always existed. :)

**Comment by jasonblais** [comment]
Thanks @kraigu - wondering if you'd have another Mac or PC you'd be able to try? I suspect it might be related to your Mac display somehow, but I'm not sure.

**Comment by kraigu** [comment]
Sure. I mostly leave the client open on my primary desktop, which I actually just changed out last week (I noticed it on the new desktop as well). For what it's worth, I was playing with Rambox and noticed a similar issue (connected to the same local Mattermost server). I don't know what that means, if anything.

I'll leave it open on a secondary machine and keep an eye on it, hopefully if it's a client bug it's one that is triggered by idling rather than requiring usage. :)

**Comment by jasonblais** [comment]
Thanks! Appreciate it :)

**Comment by jasonblais** [comment]
Hey @kraigu, have you noticed the issue on your secondary machine yet?

**Comment by kraigu** [comment]
No, but I've not been able to pay very much attention. Interestingly, perhaps, I've noticed a similar issue with a different client (Rambox) connecting to our Mattermost server.

**Comment by jasonblais** [comment]
Thanks @kraigu. Unfortunately there isn't much we can do at this point. If there is any more information you have later, let us know and we can take a second look.
