### ISSUE TITLE
Permission request dialog doesn't appear when the app shows only one server

### ISSUE THREAD

**Issue by yuya-oc** [mattermost/desktop#644]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
#609 added the dialog to confirm requested permissions. However it's implemented in the tab bar.
So the dialog doesn't appear when there is one server in the app.

**Steps to reproduce**
1. Remove `permission.js` of config directory.
2. Register only one server.
3. Back to the main page.
4. The tab bar should not appear.
5. Receive messages.
6. The dialog to confirm `notifications` permission should appear, but the dialog doesn't appear.

**Expected behavior**
The dialog appear even when the app doesn't show the tab bar.

**Observed behavior**
The dialog doesn't appear, so I can't allow requested permissions.

**Possible fixes**
Show the dialog in MainPage component when the app doesn't show tab bar.

**Comment by jasonblais** [comment]
@yuya-oc Does this prevent the user from opening the app?

**Comment by jasonblais** [comment]
@yuya-oc Does this prevent the user from receiving notifications?

**Comment by yuya-oc** [comment]
@jasonblais Yes, so the user can't see desktop notifications (badges are okay) and can't start webrtc concall.

**Comment by jasonblais** [comment]
Closed via #645
