### ISSUE TITLE
"Get Public Link" option opens image file in window where URL link is not available.

### ISSUE THREAD

**Issue by it33** [mattermost/desktop#65]
Repro: Upload an image, open it in preview mode, and click "Get Public Link" 
Expected: Public link available to copy from URL bar of image viewer
Observed: Image viewer does not have a URL bar from which to copy the URL

![image](https://cloud.githubusercontent.com/assets/177788/13675528/e41dc466-e696-11e5-9ce4-5a3ad8747e72.png)

**Comment by yuya-oc** [comment]
In my memory, it was designed only for pop-up(not image viewer) at earlier Mattermost. Sure, it has no UI components. b50527b01d5001a3871d7156da41577a767cfa8d

BTW, is it possible to implement "Copy to clipboard" in Mattermost like GitHub? Or simply show a text field to copy?

![default](https://cloud.githubusercontent.com/assets/1412057/13703251/f40ddc34-e7d7-11e5-8c46-87ce2ab3948e.PNG)

**Comment by alerque** [comment]
Check into [clipboard.js](https://github.com/zenorocha/clipboard.js) for that. I've had pretty good success with it.

**Comment by it33** [comment]
There's a ticket for non-images that could be used: https://mattermost.atlassian.net/browse/PLT-252

Actually, maybe that ticket is the better solution for this...

Curious about other people's thoughts on how to solve this? 

If the Jira ticket is the right answer--maybe apply it to all files--we can close this ticket.

**Comment by lfbrock** [comment]
I think the easiest way to solve this for now might be to open "Get Public Link" in a browser instead of in a window inside the app, like how it works in the mobile apps.

**Comment by Razzeee** [comment]
Seems to be solved in combination with mattermost 3.0?

**Comment by yuya-oc** [comment]
I have not checked. Thanks.
