### ISSUE TITLE
Mattermost Desktop App v4.0 - Beta is out!

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#650]
We've built an early beta version of Desktop App v4.0, scheduled for a release in December.

We welcome everyone in the community to download the app, and report issues you find. Valid bug reports will be acknowledged in the v4.0 changelog.

[See changelog for details on what's new](https://github.com/mattermost/desktop/blob/beta-4.0/CHANGELOG.md).

**Windows Installers**

[.../mattermost-setup-4.0.0-beta1-win64.exe](https://1112-43964563-gh.circle-artifacts.com/0/tmp/circle-artifacts.nKKqnDu/mattermost-setup-4.0.0-beta1-win64.exe)
[.../mattermost-setup-4.0.0-beta1-win32.exe](https://1112-43964563-gh.circle-artifacts.com/0/tmp/circle-artifacts.nKKqnDu/mattermost-setup-4.0.0-beta1-win32.exe)

**Windows - Zip**

[.../mattermost-desktop-4.0.0-beta1-win64.zip](https://1112-43964563-gh.circle-artifacts.com/0/tmp/circle-artifacts.nKKqnDu/mattermost-desktop-4.0.0-beta1-win64.zip)
[.../mattermost-desktop-4.0.0-beta1-win32.zip](https://1112-43964563-gh.circle-artifacts.com/0/tmp/circle-artifacts.nKKqnDu/mattermost-desktop-4.0.0-beta1-win32.zip)

**Mac**

[.../mattermost-desktop-4.0.0-beta1-mac.tar.gz](https://1112-43964563-gh.circle-artifacts.com/0/tmp/circle-artifacts.nKKqnDu/mattermost-desktop-4.0.0-beta1-mac.tar.gz)

**Linux (Beta)**

[.../mattermost-desktop-4.0.0-beta1-linux-x64.tar.gz](https://1112-43964563-gh.circle-artifacts.com/0/tmp/circle-artifacts.nKKqnDu/mattermost-desktop-4.0.0-beta1-linux-x64.tar.gz)
[.../mattermost-desktop-4.0.0-beta1-linux-ia32.tar.gz](https://1112-43964563-gh.circle-artifacts.com/0/tmp/circle-artifacts.nKKqnDu/mattermost-desktop-4.0.0-beta1-linux-ia32.tar.gz)

**Linux - Debian (Unofficial)**

[.../mattermost-desktop-4.0.0-beta1-linux-x64.deb](https://1112-43964563-gh.circle-artifacts.com/0/tmp/circle-artifacts.nKKqnDu/mattermost-desktop-4.0.0-beta1-linux-x64.deb)
[.../mattermost-desktop-4.0.0-beta1-linux-i386.deb](https://1112-43964563-gh.circle-artifacts.com/0/tmp/circle-artifacts.nKKqnDu/mattermost-desktop-4.0.0-beta1-linux-i386.deb)

**Comment by hualiansheng** [comment]
Is v4.0 going to be released later this month?

Thanks

**Comment by jasonblais** [comment]
@hualiansheng Excellent question.

We are aiming to release v4.0 soon. All PRs have been submitted and are undergoing reviews and testing https://github.com/mattermost/desktop/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+milestone%3A%22v4.0.0%22

**Comment by amyblais** [comment]
### Update

RC for v.4.0 will be cut on Jan. 19th, with release scheduled for Jan 23rd.

**Comment by amyblais** [comment]
### Changelog

Updated changelog for 4.0 is [here](https://github.com/mattermost/desktop/blob/master/CHANGELOG.md).

**Comment by amyblais** [comment]
RC1 for v4.0 has been cut! Download links available to test below. Please link to issues you believe may warrant a patch.

Mattermost Desktop App 4.0 is scheduled for a release on January 23rd.

[See changelog for details on what's new.](https://github.com/mattermost/desktop/blob/master/CHANGELOG.md)

**Linux**

https://releases.mattermost.com/desktop/4.0.0-rc1/mattermost-desktop-4.0.0-rc1-linux-ia32.tar.gz
https://releases.mattermost.com/desktop/4.0.0-rc1/mattermost-desktop-4.0.0-rc1-linux-x64.tar.gz
https://releases.mattermost.com/desktop/4.0.0-rc1/mattermost-desktop-4.0.0-rc1-linux-amd64.deb
https://releases.mattermost.com/desktop/4.0.0-rc1/mattermost-desktop-4.0.0-rc1-linux-i386.deb

**Mac**

https://releases.mattermost.com/desktop/4.0.0-rc1/mattermost-desktop-4.0.0-rc1-osx.tar.gz

**Windows**

https://releases.mattermost.com/desktop/4.0.0-rc1/mattermost-desktop-4.0.0-rc1-win32.zip
https://releases.mattermost.com/desktop/4.0.0-rc1/mattermost-desktop-4.0.0-rc1-win64.zip
https://releases.mattermost.com/desktop/4.0.0-rc1/mattermost-setup-4.0.0-rc1-win32.exe
https://releases.mattermost.com/desktop/4.0.0-rc1/mattermost-setup-4.0.0-rc1-win64.exe

**Comment by amyblais** [comment]
### Approved fixes for RC2

1. [Cache-purging not working](https://github.com/mattermost/desktop/issues/691)
2. [CTRL/CMD+Q shortcut does not work](https://github.com/mattermost/desktop/issues/692)
3. [Mac: Dock icon stops bouncing if you hover over the Dock icon](https://github.com/mattermost/desktop/issues/693)

**Comment by amyblais** [comment]
RC2 for v4.0 has been cut! Download links available to test below. Please link to issues you believe may warrant a patch.

[See changelog for details on what's new.](https://github.com/mattermost/desktop/blob/master/CHANGELOG.md)

**Linux**

https://releases.mattermost.com/desktop/4.0.0-rc2/mattermost-desktop-4.0.0-rc2-linux-ia32.tar.gz
https://releases.mattermost.com/desktop/4.0.0-rc2/mattermost-desktop-4.0.0-rc2-linux-x64.tar.gz
https://releases.mattermost.com/desktop/4.0.0-rc2/mattermost-desktop-4.0.0-rc2-linux-amd64.deb
https://releases.mattermost.com/desktop/4.0.0-rc2/mattermost-desktop-4.0.0-rc2-linux-i386.deb

**Mac**

https://releases.mattermost.com/desktop/4.0.0-rc2/mattermost-desktop-4.0.0-rc2-osx.tar.gz

**Windows**

https://releases.mattermost.com/desktop/4.0.0-rc2/mattermost-desktop-4.0.0-rc2-win32.zip
https://releases.mattermost.com/desktop/4.0.0-rc2/mattermost-desktop-4.0.0-rc2-win64.zip
https://releases.mattermost.com/desktop/4.0.0-rc2/mattermost-setup-4.0.0-rc2-win32.exe
https://releases.mattermost.com/desktop/4.0.0-rc2/mattermost-setup-4.0.0-rc2-win64.exe

**Comment by jasonblais** [comment]
v4.0 is now cut and will be available on our download page on January 29th: https://about.mattermost.com/download
