### ISSUE TITLE
Win 7: "More unreads" bubble in channel sidebar doesn't move to the bottom after resizing window

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#652]
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Win 7: "More unreads" bubble in channel sidebar doesn't move to the bottom after resizing window

**Steps to reproduce**

Windows 7 Enterprise; Mattermost Server v4.3.1; Mattermost Desktop App v3.7.1
Windows 7; Mattermost Server v4.4.0-RC1; Mattermost Desktop App v4.0.0-Beta1

 1) Reduce the window size so it only covers about half of your screen vertically
 2) Scroll up the channel sidebar so that the "More unreads" bubble appears at the bottom of left-hand channel sidebar
 3) Maximize the window

**Expected behavior**

"More unreads" bubble moves to the bottom left of the channel sidebar

**Observed behavior**

"More unreads" bubble is stuck in the middle of the sidebar, in the same place as in step 2.

**Comment by yuya-oc** [comment]
Not reproduced for me on Windows 7.

- Desktop app: 4.0.0
- Mattermost Server: 4.7.1 (4.8.0-rc1)

@jasonblais This sounds like an issue of webapp though, would you try again on your end?

**Comment by jasonblais** [comment]
The original reporter no longer has Windows 7. There was also a PR that fixed some resizing issues that may have helped with this one too 

https://github.com/mattermost/mattermost-webapp/pull/847

I'll close and we can reopen if someone else reports it. Thanks @yuya-oc!
