### ISSUE TITLE
Mac: Using CMD+1/CMD+2 to switch between servers flashes the "Window" help menu

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#653]
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
 Using CMD+1/CMD+2 to switch between servers flashes the "Window" help menu

**Steps to reproduce**
Mac OS Sierra; Desktop App v4.0.0-Beta1; Mattermost Server v4.4-RC4

1) Sign in to at least two servers on the desktop app
2) Use CMD+1 or CMD+2 to switch between the servers

**Expected behavior**
You switch between the server tabs.

**Observed behavior**
You switch between the server tabs. However, the "Window" help menu item flashes each time the shortcut is used

(Hard to take a screenshot, but I can capture a video for it if needed)

**Comment by yuya-oc** [comment]
I believe it's normal behavior of macOS. You would see that on Safari by pressing a shortcut such as `Cmd+C`.

**Comment by jasonblais** [comment]
@yuya-oc You're correct, also noted in https://pre-release.mattermost.com/core/pl/73ezcp4mefb8xncfk9ncqb88nh

Closing as a user misunderstanding the feature :)
