### ISSUE TITLE
Mattermost client does not inform user on session timeout.

### ISSUE THREAD

**Issue by soletan** [mattermost/desktop#654]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

Mattermost client does not inform user on session timeout.

**Steps to reproduce**
- Windows 10 Pro
- Client 3.7.1
- Notifications have been disabled recently due to freezing issue handled in another ticket.

* Recently peer users haven't been available on mattermost because client has expired session but user had to explicitly open client window to realize that. Clients of Skype etc. used to pop up login screen due to requiring re-authentication even though the app regularly starts minimized to systray by default. 

**Expected behavior**
- On session expiry mattermost should pop up main window requesting for re-login even though it is configured to start minimized into SysTray.

**Observed behavior**
- Users with expired sessions keep using their computers for days w/o recognizing mattermost being offline.

**Possible fixes**

**Additional Notes**

The same applies at least to mattermost iOS client.

**Comment by yuya-oc** [comment]
I feel it's a duplication of #608. Would you check?

**Comment by soletan** [comment]
Indeed, it is.
