### ISSUE TITLE
Add a prompt to download the desktop app after account creation

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#657]
I'm creating a ticket for this here so we can track it in the desktop app repo, given it's specific to the app.

Basically, there have been multiple proposals to add a prompt for new users to download the desktop app. This might appear as a blue bar at the top of the browser window, for instance, and after using Mattermost for a day or two.

One thing to consider with the implementation is not to display it if the user has already downloaded the app -- which I'm not sure is something we can detect easily. Perhaps by checking if the user has an active session on the app?

Edit: When the app is downloaded, would we be able to automatically populate the URL as well?

**Comment by amyblais** [comment]
Ticket: https://mattermost.atlassian.net/browse/MM-14075
