### ISSUE TITLE
Windows: tray icon is pixelated on HiDPI environment

### ISSUE THREAD

**Issue by it33** [mattermost/desktop#66]
See attached: 

![image](https://cloud.githubusercontent.com/assets/177788/13687984/912138e6-e6d3-11e5-93c8-ef6424d36e1e.png)

@asaadmahmoodspin, maybe have your help here replacing assets with new Mattermost logo, and maybe trying to tweak the sizing to get the right effect?

**Comment by asaadmahmoodspin** [comment]
Cool.

**Comment by yuya-oc** [comment]
JFYI, the icon looks correct on Windows 10.

![default](https://cloud.githubusercontent.com/assets/1412057/13702940/7434e3ba-e7d5-11e5-8822-35d66b32ef6f.PNG)

Does @it33's Windows use higher DPI? I think [High Resolution Image](http://electron.atom.io/docs/v0.36.8/api/native-image/#high-resolution-image) may help this.

**Comment by it33** [comment]
Thanks @yuya-oc, I might be on a higher DPI. I think it makes sense to add the High Resolution Image as you propose. Also, the [Mattermost logo has been recently updated](http://www.mattermost.org/brand-guidelines/), so we might ask @asaadmahmoodspin's help to update all the assets.

**Comment by yuya-oc** [comment]
I have found an issue on Electron. It seems that I can't fix this issue yet.
https://github.com/atom/electron/issues/2248

**Comment by asaadmahmoodspin** [comment]
The assets are already updated, but i think even the updated high resolution assets won't fix this.

**Comment by yuya-oc** [comment]
I tried 2x icons in my side. High-res icon fixes the pixelated icon in HiDPI environment, but it's pixelated in Normal DPI environment.
