### ISSUE TITLE
Removing File/Edit/View/History/Window/Help from top on Windows 

### ISSUE THREAD

**Issue by arjitc** [mattermost/desktop#661]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Would be good to remove this top bar and make the app fill in the whole screen like Slack, Hipchat apps do.

**Steps to reproduce**

- Operating System: Windows 10 Pro
- Mattermost Desktop App version:  3.7.1
- Mattermost Server version : 4.4.1

**Expected behavior**

A full screen app without these at the top.

**Observed behavior**

Has the items in the navbar which make it look a bit off (or maybe I'm too used to the HipChat app specifically)

**Possible fixes**

Removing the top bar to make the app fill up the whole screen.

**Comment by MusikPolice** [comment]
Can you be more specific? Both Mattermost and Slack have a navbar. 
![screen shot 2017-11-22 at 2 35 20 pm](https://user-images.githubusercontent.com/1799952/33146523-7b5a8676-cf92-11e7-9dc5-42967c80fb38.png)
<img width="858" alt="screen shot 2017-11-22 at 2 35 35 pm" src="https://user-images.githubusercontent.com/1799952/33146524-7b68c470-cf92-11e7-84d9-be8160e78713.png">

**Comment by arjitc** [comment]
Ah apologies, mixed up slack/hipchat. 

This is how hipchat has it,
![image](https://user-images.githubusercontent.com/363587/33147557-31b23062-cfee-11e7-88b5-299237ff82ab.png)

**Comment by jasonblais** [comment]
Hey @arjitc, we have a ticket to hide the menu bar on Windows, and integrate it within the UI. Would this cover your use case? 

https://github.com/mattermost/desktop/issues/457

https://cloud.githubusercontent.com/assets/13119842/24437399/d3cbca12-140e-11e7-8a38-6bc251fe347c.png

**Comment by arjitc** [comment]
Yes! This would be perfect!

**Comment by jasonblais** [comment]
Great! I'll close it as a duplicate.
