### ISSUE TITLE
mattermost XMPP support availability

### ISSUE THREAD

**Issue by mmanoharan83** [mattermost/desktop#666]
XMPP support available for mattermost?

**Comment by yuya-oc** [comment]
I'm not sure what is "XMPP support" though, there is a community-made integration, matterbridge.

https://github.com/42wim/matterbridge

**Comment by jasonblais** [comment]
Thanks @mmanoharan83! I'd recommend checking the Matterbridge integration linked above.

The integration is used by many and has active development of new features.
