### ISSUE TITLE
Page loads blank (plain black/white screen) in Desktop App

### ISSUE THREAD

**Issue by yth0625** [mattermost/desktop#667]
- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Page loads blank (plain black/white screen) in Desktop App

**Steps to reproduce**
When dragging the server name (top left corner of the screen) towards the center, as shown in the image, the server name and URL are displayed. And once the element is released onto the mattermost screen, it opens to a blank screen, forcing a user to reload the Desktop App so that they can view the page again.
This issue appears in Ubuntu 16.04, Windows 7 & 10. 
It probably appears in all mattermost versions. I have checked in  3.9, 4.2, 4.4.

**Expected behavior**
When dragging the server name, server name appears 'file:///C:/User ... index.html?/index=0#'
Perhaps the problem is that url appears as 'file:///C:/User ... index.html?/index=0#' instead  server url(pre-release.mattermost.com).

**Observed behavior**

Click mouse on the server UI:
![image pasted at 2017-11-27 13-51](https://user-images.githubusercontent.com/29148223/33252345-f7079f88-d380-11e7-86fa-516f9762f774.png)

argp: my server name
'file:///C:/User ... index.html?/index=0#': The server url assigned by the Meromost desktop app.

Drag and Drop serverUI to mattermost screen ( randomly appear ): 
![image pasted at 2017-11-27 10-48](https://user-images.githubusercontent.com/29148223/33252348-fd3d9984-d380-11e7-88fa-bda32e2b972f.png)
![image pasted at 2017-11-27 11-04](https://user-images.githubusercontent.com/29148223/33252349-fd7379b4-d380-11e7-99a0-cf7185c9e676.png)

**Comment by yuya-oc** [comment]
When the link is dropped into the contents region, an internal `<webview>` loads it. So the dropping should be denied on webviews.

For now, please avoid to drag&drop tabs.

**Comment by amyblais** [comment]
@yuya-oc A user reported an issue related to this ticket: https://pre-release.mattermost.com/core/pl/qyax9ej3tjycpg67eb5yo53hho

Screenshot shows the bleed through of Mattermost over a file explorer - to repro switch from Mattermost to file-explorer:

![image pasted at 2018-4-3 15-05](https://user-images.githubusercontent.com/29708087/38270741-56ca4e18-3752-11e8-8174-bf86a687417e.png)

They see this on a test VDI (in a zero client environment 100 % virtualized) with no graphics card.

**Comment by yuya-oc** [comment]
@amyblais That’s another problem. Possibly #750 would help it.

**Comment by jasonblais** [comment]
@yuya-oc Reporter came back about the most recent issue posted by @amyblais [above](https://github.com/mattermost/desktop/issues/667#issuecomment-378365994). #750 didn't resolve it.

https://pre-release.mattermost.com/core/pl/5zr4asf1m3r7bxq56nm7j47ozo

```
Yes that is exactly the issue. 

Please let me know if you need a testing device we can schedule time for you.  I am also willing to test any nightly builds you may have. 

For some strange reason alt-tab works just fine ( i believe that it is because the screen HAS to be redrawn due to the graphic it shows). I have read that this is an issue with the version of electron that is used to draw your iFrame and that a newer version of it fixes it.

Please let me know what i can do to help
```

The reported mentioned it might be related to an Electron issue fixed with this PR: https://github.com/electron/libchromiumcontent/pull/503

**Comment by yuya-oc** [comment]
@jasonblais Okay. I think https://github.com/electron/libchromiumcontent/pull/503 is related to the problem, too. I had misunderstood because DWM is disabled in the report and it's related to rendering. Would you create another issue to track that?

**Comment by jasonblais** [comment]
Sure thing. Have asked @amyblais to help create it. Closing this issue as the original report should be resolved with #752

**Comment by amyblais** [comment]
New issue here: https://github.com/mattermost/desktop/issues/753

**Comment by bdrmdrsylp** [comment]
![Githuberror](https://user-images.githubusercontent.com/58975147/71410655-23f7fe80-266c-11ea-8019-d51623af3df5.jpg)

**Comment by bdrmdrsylp** [comment]
i m getting page like this!!!!

**Comment by bdrmdrsylp** [comment]
what went wrong?

**Comment by jasonblais** [comment]
@bdrmdrsylp Hey, looks like GitHub was having issues, can you try reload the page (CTRL/CMD+R or via the "Reload this page" icon next to the URL bar?

![image](https://user-images.githubusercontent.com/13119842/71414356-934a0000-2624-11ea-929e-4b1661b714f0.png)

If you're still having issues, I recommend contacting GitHub support (https://github.com/contact) as it doesn't appear to be an issue with Mattermost :)
