### ISSUE TITLE
CPU 100% on Ubuntu KDE

### ISSUE THREAD

**Issue by XS-Firen** [mattermost/desktop#670]
**Summary**
mattermost-desktop constantly at 100% cpu

When I open the program the spawned thread goes to 100 and doesn't go below +- 90%

System:
Ubuntu 17.10 with KDE. Linux firen-werk 4.13.0-17-generic #20-Ubuntu SMP Mon Nov 6 10:04:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Mattermost-desktop version: I can't open the help menu, because it doesn't load but the three stripes in the interface -> Help says 4.4 . (dpkg says: mattermost-desktop (3.7.1-3.7.1))
- Mattermost Server version : Version: 4.0.0  (dev) Database: postgres
When I open the program the spawned thread goes to 100 and doesn't go below +- 90%
I have global menu's enabled in KDE without any other special tweaks on the interface

**Expected behavior**
2 / 3 % cpu usage on my i5-6300U CPU

**Observed behavior**
Using `$ strace mattermost-desktop` I see the following messages constantly:
futex(0x1ebedaa4ae70, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x1ebeda844180, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x1ebedaa30058, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x1ebeda7809c0, FUTEX_WAIT_PRIVATE, 2, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x1ebeda7809c0, FUTEX_WAKE_PRIVATE, 1) = 0
recvmsg(18, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(28, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=18, events=POLLIN}, {fd=19, events=POLLIN}, {fd=28, events=POLLIN}, {fd=36, events=POLLIN}], 4, 0) = 0 (Timeout)
recvmsg(28, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(18, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(28, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=18, events=POLLIN}, {fd=19, events=POLLIN}, {fd=28, events=POLLIN}, {fd=36, events=POLLIN}], 4, 9) = 1 ([{fd=19, revents=POLLIN}])
read(19, "\1\0\0\0\0\0\0\0", 16)        = 8
recvmsg(28, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
futex(0x1ebeda844180, FUTEX_WAKE_PRIVATE, 1) = 1
recvmsg(18, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(28, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=18, events=POLLIN}, {fd=19, events=POLLIN}, {fd=28, events=POLLIN}], 3, 0) = 0 (Timeout)
recvmsg(28, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
futex(0x7f0afefa31f8, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x1ebeda4a8b20, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7f0afc90ebb0, FUTEX_WAIT_PRIVATE, 2, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x7f0afc90ebb0, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7f0afefa3288, FUTEX_WAKE_PRIVATE, 1) = 1
write(77, "\1\0\0\0\0\0\0\0", 8)        = 8
<!--
Using `$ strace mattermost-desktop` I see the following messages constantly:
futex(0x1ebedaa4ae70, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x1ebeda844180, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x1ebedaa30058, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x1ebeda7809c0, FUTEX_WAIT_PRIVATE, 2, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x1ebeda7809c0, FUTEX_WAKE_PRIVATE, 1) = 0
recvmsg(18, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(28, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=18, events=POLLIN}, {fd=19, events=POLLIN}, {fd=28, events=POLLIN}, {fd=36, events=POLLIN}], 4, 0) = 0 (Timeout)
recvmsg(28, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(18, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(28, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=18, events=POLLIN}, {fd=19, events=POLLIN}, {fd=28, events=POLLIN}, {fd=36, events=POLLIN}], 4, 9) = 1 ([{fd=19, revents=POLLIN}])
read(19, "\1\0\0\0\0\0\0\0", 16)        = 8
recvmsg(28, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
futex(0x1ebeda844180, FUTEX_WAKE_PRIVATE, 1) = 1
recvmsg(18, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(28, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=18, events=POLLIN}, {fd=19, events=POLLIN}, {fd=28, events=POLLIN}], 3, 0) = 0 (Timeout)
recvmsg(28, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
futex(0x7f0afefa31f8, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x1ebeda4a8b20, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7f0afc90ebb0, FUTEX_WAIT_PRIVATE, 2, NULL) = -1 EAGAIN (Resource temporarily unavailable)
futex(0x7f0afc90ebb0, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7f0afefa3288, FUTEX_WAKE_PRIVATE, 1) = 1
write(77, "\1\0\0\0\0\0\0\0", 8)        = 8

**Comment by jasonblais** [comment]
@yuya-oc thoughts?

**Comment by yuya-oc** [comment]
For now, unfortunately I'm not familiar at reading `strace`. Although https://github.com/electron/electron/issues/8455 might be related. If it's true, upcoming v4.0.0 would fix the problem due to upgrading of Electron. Wondering if you could try [v4.0.0-beta](https://github.com/mattermost/desktop/issues/650).

**Comment by XS-Firen** [comment]
Perfect, v4.0.0-beta fixed the issue. The output of strace went back to a normal amount.
