### ISSUE TITLE
Dock icon doesn't bounce for new messages when setting is enabled, only for mentions

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#677]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Dock icon doesn't bounce for new messages when setting is enabled, only for mentions

**Steps to reproduce**

Mac; Mattermost Server v4.6.0-RC4; Mattermost Desktop App v4.0.0-beta2

1) Go to app settings via CTRL+COMMA
2) Enable "Bounce the Dock icon" setting
3) Go to your Mattermost team and receive a message

Observed: Dock icon doesn't bounce
Expected: Dock icon bounces

NOTE: The report indicates that this might be related to desktop notifications (i.e. when a desktop notification is triggered, the Dock icon bounces as well)

**Expected behavior**
Dock icon bounces

**Observed behavior**
Dock icon doesn't bounce

**Comment by yuya-oc** [comment]
> NOTE: The report indicates that this might be related to desktop notifications (i.e. when a desktop notification is triggered, the Dock icon bounces as well)

Yeah, the bouncing is triggered when there a desktop notification appears (#651).

**Comment by jasonblais** [comment]
@yuya-oc I tested against other apps, and this seems to be the standard behaviour.

So I tweaked the setting text to say it bounces for new notifications, instead of new messages. https://github.com/mattermost/desktop/pull/683
