### ISSUE TITLE
mattermost:// protocol doesn't launch the desktop app if it's not already open

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#678]
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
mattermost:// protocol doesn't launch the desktop app if it's not already open

**Steps to reproduce**

Mac; Mattermost server v4.6.0-RC1; Mattermost Desktop App v4.0.0-beta2

1. Sign in to https://pre-release.mattermost.com on your desktop app
2. Post http://pre-release.mattermost.com/core/channels/developers into a channel
3. Quit the desktop app
4. Sign in to https://pre-release.mattermost.com on your browser
5. Click on the link you posted in step 2.

**Expected behavior**
Desktop app launches, and opens the Developers channel.

**Observed behavior**

Opens in browser, doesn't launch desktop app.

NOTE: If the desktop app is already open, the app gets focus and redirects to the Developers channel.

**Comment by yuya-oc** [comment]
Reproduced also on my Mac. But not reproduced on Windows 10.
