### ISSUE TITLE
NOTICE.txt and LICENSE.txt Should be in Content/Resources directory of App Bundle

### ISSUE THREAD

**Issue by MusikPolice** [mattermost/desktop#681]
I confirm (by marking "x" in the [ ] below: [x]):
- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---
**Summary**
When code signing the application for distribution, `electron-osx-sign` spits out an error that looks like this:
```Bash
electron-osx-sign Error executing file: 
 > Stdout:  
 > Stderr: Mattermost.app/Contents/MacOS/Mattermost: code object is not signed at all
In subcomponent: /Users/jfritz/go/src/github.com/mattermost/desktop/release/mac/Mattermost.app/Contents/LICENSE.txt
 +241ms
  electron-osx-sign Sign failed: +1ms
  electron-osx-sign Command failed: codesign --sign **** --force Mattermost.app/Contents/MacOS/Mattermost
  electron-osx-sign Mattermost.app/Contents/MacOS/Mattermost: code object is not signed at all
  electron-osx-sign In subcomponent: /Users/jfritz/go/src/github.com/mattermost/desktop/release/mac/Mattermost.app/Contents/LICENSE.txt
  electron-osx-sign  +0ms
Sign failed:
Command failed: codesign --sign **** --force Mattermost.app/Contents/MacOS/Mattermost
Mattermost.app/Contents/MacOS/Mattermost: code object is not signed at all
In subcomponent: /Users/jfritz/go/src/github.com/mattermost/desktop/release/mac/Mattermost.app/Contents/LICENSE.txt
```
This seems to be caused by the fact that `LICENSE.txt` and `NOTICE.txt` are resource files, not code files, but are located in the top-level of the `Contents` directory. See [table 3-1 from this Apple developer doc](https://developer.apple.com/library/content/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html) for more info.

The issue can be solved by moving these two .txt files into the `Resources` directory:
```Bash
jfritz$ mv Mattermost.app/Contents/*.txt Mattermost.app/Contents/Resources/
```
After which, the signing will succeed as expected.

**Possible fixes**
Rather than making this a manual step, we should modify the electron build config to put these files in the `Contents/Resources` directory by default.

**Comment by yuya-oc** [comment]
`LICENSE.txt` and `NOTICE.txt` are located by electron-builder config (See also `extraFiles` at https://www.electron.build/configuration/contents).
https://github.com/mattermost/desktop/blob/52559111fa214137cb54f48bb993ca52e63910e4/electron-builder.json#L15-L22

By changing `extraFiles` to `extraResources`, the files would be located under `Contents/Resources/`.

@jasonblais By applying my approach, the files are located under `resources` folder also on Windows/Linux. So users might not be able to find files soon. But I think that doesn't matter in almost cases though, is it applicable?

**Comment by jasonblais** [comment]
@MusikPolice @yuya-oc If this only affects Mac, can we only have this change for Mac?

If that makes it too complicated, then there's probably not much we can do.

**Comment by yuya-oc** [comment]
@jasonblais We can locate the files under `Resources` only on Mac. However to do that, we need to set `extraFiles/extraResources` config for each OS instead of using common config.

**Comment by jasonblais** [comment]
@yuya-oc So you're saying we'd effectively need a separate electron-builder.json file for each OS?

**Comment by yuya-oc** [comment]
@jasonblais Ah, no. The file would be below.

```json
{
  "appId": "com.mattermost.desktop",
  "directories": {
    "buildResources": "resources",
    "app": "src",
    "output": "release"
  },
  "files": [
    "main_bundle.js",
    "browser/**/*{.html,.css,_bundle.js}",
    "assets/**/*",
    "node_modules/bootstrap/dist/**",
    "node_modules/simple-spellchecker/dict/*.dic"
  ],
  "protocols": [
    {
      "name": "Mattermost",
      "schemes": ["mattermost"]
    }
  ],
  "deb": {
    "synopsis": "Mattermost"
  },
  "linux": {
    "category": "InstantMessaging",
    "target": [
      "deb",
      "tar.gz"
    ],
    "extraFiles": [
      {
        "filter": [
          "LICENSE.txt",
          "NOTICE.txt"
        ]
      },
      {
        "from": "resources",
        "filter": "icon.png"
      },
      {
        "from": "resources/linux",
        "filter": [
          "create_desktop_file.sh",
          "README.md"
        ]
      }
    ]
  },
  "mac": {
    "category": "public.app-category.productivity",
    "target": [
      "tar.gz"
    ],
    "extraResources": [
      {
        "filter": [
          "LICENSE.txt",
          "NOTICE.txt"
        ]
      }
    ]
  },
  "squirrelWindows": {
    "iconUrl": "file://resources/icon.ico"
  },
  "win": {
    "target": [
      "squirrel",
      "zip"
    ],
    "extraFiles": [
      {
        "filter": [
          "LICENSE.txt",
          "NOTICE.txt"
        ]
      }
    ]
  }
}
```

The difference is below.

- Common `extraFiles` is removed.
- `mac` has `extraResources`. `win` and `linux` have `extraFiles` for theirselves. These three parts should list same files.

**Comment by MusikPolice** [comment]
I was just working on a PR to do this 👍 
Do you want to just submit your changes @yuya-oc, and we can try them out?

**Comment by yuya-oc** [comment]
Okay, I'll submit once.

**Comment by jasonblais** [comment]
@yuya-oc @MusikPolice I think this can be closed?

**Comment by MusikPolice** [comment]
Closed
