### ISSUE TITLE
Investigate timing of ready and open-url on macOS

### ISSUE THREAD

**Issue by yuya-oc** [mattermost/desktop#688]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

Jira ticket: https://mattermost.atlassian.net/browse/MM-14089

**Summary**
In #680, the oder of events was different due to some reason. We need to investigate the condition to reproduce the problem.

**Steps to reproduce**
1. Quit the app
2. Open `mattermost://` URL to open the app.
3. Confirm the order of events.

**Expected behavior**
N/A

**Observed behavior**
The order of ready and open-url events was different.

**Possible fixes**
N/A

**Comment by amyblais** [comment]
Jira ticket for tracking: https://mattermost.atlassian.net/browse/MM-14089

**Comment by esethna** [comment]
Please reopen if needed
