### ISSUE TITLE
Cache-purging not working

### ISSUE THREAD

**Issue by amyblais** [mattermost/desktop#691]
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Cache-purging not working. Link to earlier PR that was merged: https://github.com/mattermost/desktop/pull/682
This happened on Windows, Desktop app v4.0.0, server v.4.6.0.

**Steps to reproduce**

1. Quit the app.
2. Create AppData\Roaming\Mattermost\app-state.json with following content.
`{"lastAppVersion": "9.9.9"}`
3. Open AppData\Roaming\Mattermost\Cache in Explorer.
4. Cache files should be temporarily removed when launching the app next time.
5. If lastAppVersion equals to the app version (3.7.1 in this PR), cache files should NOT be removed.

**Expected behavior**
Cache files should be temporarily removed.

**Observed behavior**
Cache files are not removed.

**Comment by yuya-oc** [comment]
@amyblais Not reproduced for me on Windows 10. The behavior should be same as you saw at #682 though, would you test again?

**Comment by amyblais** [comment]
@yuya-oc I tried again and this is what I see now: the cache files disappear for a short moment when I open the desktop app and it starts to load. However, when the app has fully loaded, then the cache files come back and the content in app-state.json changes to `{"lastAppVersion": "4.0.0"} - is this expected?

**Comment by yuya-oc** [comment]
@amyblais Yes. The app saves caches again when the page has been loaded. And the json should be changed by launching the app. I forgot to write about this at #682.
