### ISSUE TITLE
Mac: Dock icon stops bouncing if you hover over the Dock icon

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#693]
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Mac: Dock icon stops bouncing if you hover over the Dock icon

**Steps to reproduce**

Mattermost server v4.6.0; Mattermost Desktop App v4.0.0

1. Select "Bounce the Dock icon", and select "until I open the app"
2. Press "Save"
3. Receive a mention from someone
4. Hover over the Dock icon

**Expected behavior**
Dock icon keeps bouncing until I open the app

**Observed behavior**
Dock icon stops bouncing. No further notification causes the Dock icon to bounce.

**Comment by yuya-oc** [comment]
I tested [the native API](https://developer.apple.com/documentation/appkit/nsapplication/1428358-requestuserattention) by creating a simple macOS app. Following code tries to bounce the Dock icon with `critical`(bounce until active) at 1 second interval.

```swift
// ViewController.swift
@IBAction func didClickButton(_ sender: Any) {
    print("Start")
    var counter = 0;
    func bounceAsyncLoop() -> Void {
        counter+=1
        print("Bounce", counter)
        NSApplication.shared.requestUserAttention(NSApplication.RequestUserAttentionType.criticalRequest)
        DispatchQueue.main.asyncAfter(deadline: .now() + 1, execute: bounceAsyncLoop)
    }
    bounceAsyncLoop()
}
```

As the result, the app behaves as well as this issue. So I think it's normal behavior on Mac.

**Comment by jasonblais** [comment]
@yuya-oc You're correct, I tested on another app.

I'll close this for now. If someone else finds it confusing, we can consider updating the settings text.
