### ISSUE TITLE
Vulnerability in Electron

### ISSUE THREAD

**Issue by Juburin** [mattermost/desktop#694]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---
Electron publicized a vulnerability in the protocol handler:
https://electronjs.org/blog/protocol-handler-fix

**Comment by yuya-oc** [comment]
Thanks to let us know. It will be shipped as a part of v4.0.0-rc2. #690

In normal usage, existing releases are not using the protocol handler.
