### ISSUE TITLE
Suggestion for private messages list

### ISSUE THREAD

**Issue by opxh** [mattermost/desktop#699]
Hi guys, very joyfull to use  your client, and I got one suggestion here:
Could you please do a thing like sorting persons in private messages by the date of last message in the chat? That would be a little more comfortable to not scroll around looking for person you've chatted bit time ago. Thanks.

**Comment by jasonblais** [comment]
Thanks @opxh for the feedback! We are actually tracking it through a [feature proposal here](https://mattermost.uservoice.com/forums/306457-general/suggestions/17606041-sort-contacts-by-last-message) and are considering ways to improve sidebar organization.

Would you like to consider upvoting the feature? You get **10** votes in the feature idea forum, and each one influences the future of the project.
