### ISSUE TITLE
Add to the list of words that are counted as "spelled correctly"

### ISSUE THREAD

**Issue by amyblais** [mattermost/desktop#700]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
There was a request to add the word "transgender" to the list of words that are counted as "spelled correctly". This issue was opened to track this project.

Another one is "Signage"

**Comment by jasonblais** [comment]
At the same time we should consider how we regularly update our dictionary files

**Comment by jasonsmith425** [comment]
"online" is another
