### ISSUE TITLE
Right-clicking an image, then choosing "Save Image" does nothing

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#707]
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Right-clicking an image, then choosing "Save Image" does nothing

**Steps to reproduce**

Mac and Windows; Mattermost server v4.6 and v4.7-RC1. Mattermost Desktop App v4.0.0

1) Upload an image and post it to a Mattermost channel
2) Right-click the image, then choose "Save Image"

**Expected behavior**
File explorer (on Windows) / Finder (on Mac) opens and lets you choose where to save the file.

**Observed behavior**
Nothing happens

**Comment by yuya-oc** [comment]
Probably related. https://github.com/sindresorhus/electron-context-menu/issues/13
However I'm not sure why this makes issue now because it was reported one and a half year ago.

**Comment by jasonblais** [comment]
@yuya-oc Yeah, I tested with Desktop App v3.7.1 and it was working as expected. So I'd be surprised if https://github.com/sindresorhus/electron-context-menu/issues/13 was the issue.

(The maintainer also makes a note that the proper text would be `Save Image As...`.

**Comment by jasonblais** [comment]
You don't think it's anything related to Redux changes in the webapp?

**Comment by yuya-oc** [comment]
Closed via #774.
