### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by divanikus** [mattermost/desktop#710]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Mattermost Desktop consumes constantly increasing amount of memory. I have something around 20 open channels and severl dialogues with other users. Memory consumption after cold restart was around 250 MB, after 5 hours it's around 750 MB. We also saw 1000 MB on one of our collegues desktop.

**Steps to reproduce**
Just use it for while and look at memory consumption in your Task Manager.

Version numbers
- MS Windows 10 Pro 1709, MacOS X 10.13
- Mattermost Desktop App Version 4.0.0
- Mattermost Server 4.5.0 (4.5.1, postgres) - Omnibus GitLab install v10.4.3

**Expected behavior**
Memory consumption remains low.

**Observed behavior**
Growing memory consumption.

**Comment by jasonblais** [comment]
@divanikus Do you know if the happens on a browser?

I suspect it might be from loading more data over time as you switch channels (and receive new messages).

**Comment by divanikus** [comment]
I can confirm that in-browser version also consumes memory, but at lesser amount. After 3 hours I see 360 MB for a Chrome tab and 1069 MB for desktop app.
![84320f00379ba237c0761a13ee52f7d2](https://user-images.githubusercontent.com/3438036/36252130-9f0ed270-1254-11e8-8356-252306307e38.png)
![d129602a33d82eb1e0ffc0179de62d17](https://user-images.githubusercontent.com/3438036/36252137-a34ecf48-1254-11e8-9280-b861c068cdbc.png)

**Comment by divanikus** [comment]
Ok, switching between channels boosts memory consumption at both in-browser and desktop app. I got 600 MB in Chrome in 2 minutes by simply switching between channels.

Anyway, it's totally not OK.

**Comment by divanikus** [comment]
Ok, I've reported an issue for server too [mattermost-server#8297](https://github.com/mattermost/mattermost-server/issues/8297)

**Comment by yuya-oc** [comment]
Thanks. As you saw on Chrome, switching channel increases memory consumption. The process is merely executing the webapp JavaScript as well as Chrome. So the desktop app can't control the consumption.

**Comment by jasonblais** [comment]
@divanikus I'll close this issue for now, and we can continue discussion at https://github.com/mattermost/mattermost-server/issues/8297
