### ISSUE TITLE
Auto-hide menubar on Linux

### ISSUE THREAD

**Issue by cassidyjames** [mattermost/desktop#715]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

Most Electron apps on Linux have an option to autohide the menubar, typically in the View or Window menus. Mattermost would fit in better if it did, too.

**Steps to reproduce**

- **OS:** Pop!_OS 17.10, elementary OS 0.4 Loki, any other Linux-based OS.
- **Desktop App:** 4.0.0
- **Sever:** 4.0.0 (4.0.1)

Install Mattermost on a Linux-based system, see the menubar. :wink: 

**Expected behavior**

There is a "Toggle Menu Bar" or "Always Show Menu Bar" option on Linux, like in Atom or Slack.

**Observed behavior**

The menubar is always visible and not hideable

**Other**

Opening as this is separate and distinct from #457; that deals with Windows specifically, whereas adding widgets to the titlebar is not something supported in Electron on Linux as far as I know.

**Comment by amyblais** [comment]
Thank you for this suggestion @cassidyjames!
@yuya-oc Can you help apply "Linux" and "Feature" labels on this ticket.

**Comment by freddyw** [comment]
Would love to see this as well. The menu bar is just taking up screen estate and looking ugly compared to the mattermost-desktop application.

**Comment by amyblais** [comment]
Closing via feature request here: https://mattermost.uservoice.com/forums/306457-general/suggestions/36842089-desktop-auto-hide-menubar-on-linux.
