### ISSUE TITLE
When hovering over tab outline of tab should not disappear

### ISSUE THREAD

**Issue by it33** [mattermost/desktop#717]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

When hovering over tab outline of tab should not disappear 

**Steps to reproduce**

Win10, w/ 4.0.0 Desktop, 4.7 Server 

1. Setup desktop with multiple servers
2. Hover over the tabs

**Expected behavior**

When hovering over tab outline of tab should not disappear. 

**Observed behavior**

When hovering over tab outline of tab disappears. It makes the highlighted tab look like it's part of the menu, which doesn't make sense. 

![image](https://user-images.githubusercontent.com/177788/36545226-4d29bd32-179d-11e8-8357-efe9ab5088c2.png)

**Possible fixes**

Fix styling of tabs for on-hover event.

**Comment by amyblais** [comment]
I'm able to reproduce, I reported this in the UX channel.

**Comment by jasonblais** [comment]
@yuya-oc Would that be an easy fix?

**Comment by amyblais** [comment]
@yuya-oc Can you help add "Bug" label for this ticket?

**Comment by jasonblais** [comment]
Added - also added `All Platforms` label although it's only visible on Windows given Mac doesn't have a menu bar.

**Comment by yuya-oc** [comment]
Closed via #778
