### ISSUE TITLE
Windows 7: Leaving "Name" blank creates unusable team site tab

### ISSUE THREAD

**Issue by it33** [mattermost/desktop#72]
Repro:  

- Create a team, then create an additional team using this procedure: 
- In **Settings Page** enter a valid **URL**, leave **Name** field blank then click **Add** and then **Save**

Observed:  

- Blank tab created for team, Blank tab cannot be clicked. 

Expected:   

- **Add** button responds with an error that **Name** is required when **Name** field is empty

**Comment by yuya-oc** [comment]
It will be fixed at next version by 97808373ede7aa333a4dd21de062da8024af5890.

**Comment by it33** [comment]
Perfect, thanks!
