### ISSUE TITLE
Help link is unecessary

### ISSUE THREAD

**Issue by client4** [mattermost/desktop#723]
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
The help link below the "write a message bar" is not visually appealing and should be able to be removed.

**Steps to reproduce**
Fedora 27, latest desktop edition

**Expected behavior**
Clean, beautiful UI
**Observed behavior**
Help link is unnecessary and should be removable.   

**Possible fixes**
Remove help link, or create option to allow for removal of help link.

**Comment by jasonblais** [comment]
Hey @client4, thanks for the feedback! It's placed there so that new users can easily find tips about sending messages, such as Markdown help.

**Comment by client4** [comment]
But can non-new users remove it?

EF

Treasure State Internet & Telegraph
406.204.4777
http://tsi.io

**Comment by jasonblais** [comment]
Hey @client4 - not right now. I see where you're coming from, but I'm wondering if a setting would be an overkill in this case.

As a side note, the space below the message box is primarily preserved for the `user is typing...`  notes, when someone else is typing in the channel.

**Comment by jasonblais** [comment]
@client4 Did you have any further thoughts on this one?

**Comment by client4** [comment]
Nope! I'm persuaded by your argument and didn't consider the typing status indicator.  Thank you for taking the time to discuss it with me and apologies for not closing the issue sooner.

**Comment by jasonblais** [comment]
Thanks @client4 - not to worry. Thanks for sharing, always open for feedback! 👍
