### ISSUE TITLE
Broken Avatars and Images

### ISSUE THREAD

**Issue by Domvel** [mattermost/desktop#726]
Since update from 3.7.1 to 4.0.0 the users avatar image is broken or resetted.

Please see the screenshot below. The user now displayed as default avatar "D" had a picture. Now only displayed the default avatar with his first latter.  The second user with the broken link hat the default avatar with his latter.

Summary changes since the update:
custom avatar -> resetted to default with first letter.
default avatar with letter -> broken link.

![mattermost-4 0 0-broken-avatars](https://user-images.githubusercontent.com/35452565/37292678-af45c786-2611-11e8-8e1c-9803d3fb8f4b.png)

Any idea, what could be the reason? Who has the same problem? 
I already tried to restart the app. I also cannot upoad a avatar anymore.
Message: "Couldn't upload profile image"

Setup: 
Windows 10 Pro 64bit
Mattermost Desktop 4.0.0
User account over AD/LDAP

**Comment by yuya-oc** [comment]
@Domvel As far as looking the problem, I feel the desktop app keeps wrong caches. Would you try following methods?

- Confirm whether the Mattermost server was recently upgraded (and its version).
- Clear cache and reload (Ctrl+Shift+R).
- See developer console (Ctrl+Shift+I). Possibly there might be some error messages.

**Comment by Domvel** [comment]
@yuya-oc Thanks for response. `Ctrl` + `Shift` + `R` does not fix the problem. The console prints: 
`websocket connecting to wss://mattermost.<domain>:443/api/v4/websocket``
So I guess the server version 4, beacuse api v4. For the exact version, I have to ask our admin who's currently not present. 

Maybe there are garbage files on my system for mattermost? temp. / cache files. I'll check the %appdata% folder.

**Comment by yuya-oc** [comment]
@Domvel You can find the server version on UI: **Mattermost Menu > About Mattermost**, where **Mattermost Menu** can be accessed by clicking on three dots next to your profile picture.

To make sure, did you see the problem on another web browser?

**Comment by Domvel** [comment]
Version: 4.7.1 (4.7.3)
Database: postgres
Same effect on browser (chrome)

**Comment by Domvel** [comment]
Seems to be a problem on server side.
