### ISSUE TITLE
Crash during installation but still installs correctly

### ISSUE THREAD

**Issue by bbodenmiller** [mattermost/desktop#728]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Desktop 4.0.0 is showing a crash during installation yet it appears to be installed correctly

**Steps to reproduce**

* Windows 10
* Install Desktop 4.0.0
* See crash during installation yet still see that Mattermost Desktop is installed

**Expected behavior**

Don't show crash during installation

**Observed behavior**

Crashes

**Possible fixes**

Unknown

**Comment by bbodenmiller** [comment]
![image](https://user-images.githubusercontent.com/1192780/37310211-72f0a618-2600-11e8-8715-a763a31f6b38.png)
![image](https://user-images.githubusercontent.com/1192780/37310231-81707722-2600-11e8-9604-cc001bf011c9.png)

**Comment by yuya-oc** [comment]
@bbodenmiller Possibly some logs might be found. Would you check following files?

- `%USERPROFILE%\AppData\Local\SquirrelTemp\SquirrelSetup.log`
- `%USERPROFILE%\AppData\Roaming\Mattermost\uncaughtException-*.txt`

**Comment by jasonblais** [comment]
@bbodenmiller Let us know if you need any help retrieving the logs? We haven't been able to reproduce this issue on our end yet.

**Comment by bbodenmiller** [comment]
Here they are:

[SquirrelSetup.log](https://github.com/mattermost/desktop/files/1836528/SquirrelSetup.log)
[uncaughtException-1520891271626.txt](https://github.com/mattermost/desktop/files/1836529/uncaughtException-1520891271626.txt)

**Comment by jasonblais** [comment]
Thanks! FYI @yuya-oc ^

**Comment by colchuck** [comment]
Have this same issue when installing the Desktop APP on 2012R2 and Windows 7 -
Comes up with the same SquirrelSetup.log but doesn't show an uncaughtException file. Don't know if that helps...

[Problem_Signature.txt](https://github.com/mattermost/desktop/files/1864102/Problem_Signature.txt)
