### ISSUE TITLE
formatting errors between matterircd and desktop app [Edit: Issue caused by incorrect rendering of MIRC color codes]

### ISSUE THREAD

**Issue by khronosschoty** [mattermost/desktop#729]
#### Summary
Formatting of text from matterircd is not always correctly shown on the web interface or the mobile app etc. 

#### Steps to reproduce
Use the IRC bot Malibu developed by Stinger for the browser game utopia-game.com

#### Expected behavior
Formatting should be the same in the IRC client (or near the same).  

#### Observed behavior (that appears unintentional) 
Some people report some of the formatting is off they see things like this

![encoding](https://user-images.githubusercontent.com/2358071/37365516-a9d2fafa-26f5-11e8-8838-830490efad23.PNG)

I can reproduce the issue above it happens only when using the desktop app, otherwise you get the issue from down below. 

![f95jrcd](https://user-images.githubusercontent.com/2358071/37367104-65e05dce-26fa-11e8-94c4-dd0639620ab2.png)

numbers displayed that should not be displayed like the '7' in front of "Quadratic" 
or the "Runes: 12 4k" should just read "Runes: 4k" and it displays properly on the irc gateway just not in the mattermost webui. 

#### Possible fixes
Ignore MIRC color codes.

**Comment by yuya-oc** [comment]
@khronosschoty The desktop app behaves like Chrome, i.e. the app is just rendering html. So unfortunately I believe there are nothing we can do in the desktop app side. I think Mattermost probably doesn't support MIRC color, so matterircd or Malibu should omit color codes when sending messages.
