### ISSUE TITLE
Zoomed window size disrupted on return from settings on desktop client

### ISSUE THREAD

**Issue by ShamimIslam** [mattermost/desktop#737]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

Jira ticket: https://mattermost.atlassian.net/browse/MM-14088

**Summary**

After you zoom the desktop client, opening and closing the settings window disrupts the screen sizes of the windows - zoomed windows are 1/4 of the screen and cannot be maximized even if the window frame is maximized.
**Steps to reproduce**

Fedora 26 x86_64 Gnu/Linux KDE
Mattermost 4.0.0 (1/29/18) client
Mattermost 4.4.0 server
1. Add server
2. Log in
3. Zoom in to make the text bigger (5x maybe 8x)
4. Click settings in the file menu
5. Click the X to close the settings menu
6. Page reloads with zoom but window size is not disrupted
7. Widnow now displays as a smaller portion of the overall window frame
8. Zoom remains constant.

**Expected behavior**
Return to the session should appear the same as before
**Observed behavior**
Return to the session appears with a smaller region of the window frame displaying the session. On my machine it is 1/4 the size and not usable.

No error messages seen.
**Possible fixes**
Unknown.

No idea.

**Comment by amyblais** [comment]
Hi @ShamimIslam,

Thank you for this report!

I tried to reproduce but couldn't, can you:

1. please let me know if you can share any logs from around the time the issue occurs?
2. consider upgrading the server to the latest (v4.8) in case there is a fix related to this in one of the recent server versions (not required, only a suggestion)?

**Comment by ankurloriya** [comment]
Facing the same issue. here are helpful steps.

System Details
Linux ankur-linux-pc 4.14.14-041414-generic #201801201219 SMP Sat Jan 20 12:20:41 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
MatterMost details
Desktop app version: 4.1.2
Server version: 4.8.0 (mysql)
Server type: Self-Hosted

```
1) Maximize desktop app
2) Click on notification (Any arrived notification) from the system tray notification area.
```

**Comment by ShamimIslam** [comment]
So just download the latest and run it or do I need to do anything special
to retain settings?

**Comment by amyblais** [comment]
@yuya-oc Is this something you would be able to help test on Linux?

**Comment by amyblais** [comment]
Jira ticket for tracking: https://mattermost.atlassian.net/browse/MM-14088.

**Comment by esethna** [comment]
Does not repro in v4.4
