### ISSUE TITLE
Desktop App issues certificate errors since v3.7.1

### ISSUE THREAD

**Issue by jasonblais** [mattermost/desktop#742]
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Desktop App issues certificate errors since v3.7.1

**Steps to reproduce**

There are no clear reproduction steps, but at least three separate users have reported certificate errors since v3.7.1:

https://pre-release.mattermost.com/core/pl/4jmwur5fr3no9j1nhg6ntgyfzr
https://pre-release.mattermost.com/core/pl/fyfek1upt7g83jxbh4hfwimf9y
https://pre-release.mattermost.com/private-core/pl/1tcwauk7ibdr9rf1gcz6pf8tur

**Comment by jasonblais** [comment]
@yuya-oc I know you're already looking into this, but created a ticket for us to track.

@amyblais Added a priority 1 label since it affects the "Trusted" principle.

**Comment by yuya-oc** [comment]
Probably related. https://github.com/electron/electron/issues/11997 And it might be fixed at Electron 1.8.4.

As an ad-hoc workaround, we might able to ignore the error by using [`setVertificateVerifyProc()`](https://github.com/electron/electron/blob/v1.7.13/docs/api/session.md#sessetcertificateverifyprocproc).

**Comment by jasonblais** [comment]
@amyblais Can you help ask Lindy to download a test build from https://github.com/mattermost/desktop/pull/741 which upgrades Electron to 1.8.4.

If it resolves it for her, then at least we'll know it's related.

**Comment by jasonblais** [comment]
Great! That means it should already be fixed for 4.1.0.

@amyblais Can you also help Lindy to download the test artifact here, which should fix it for 4.0.1: https://github.com/mattermost/desktop/pull/743

**Comment by amyblais** [comment]
Lindy tested with #743 and saw no issues. 
Linda also reported that she has seen no issues with the test build from #741 on Mac.

**Comment by jasonblais** [comment]
Perfect. @yuya-oc We can merge #743 and the changelog PR once you've reviewed (#744).

We can then close https://github.com/mattermost/desktop/issues/742 and cut 4.0.1-final.
