### ISSUE TITLE
windows version is too slow, using almost half of cpu

### ISSUE THREAD

**Issue by lovetingyuan** [mattermost/desktop#751]
what the matter with the desktop application?

**Comment by jasonblais** [comment]
Thanks @lovetingyuan for the note.

Is this after using the app for some time, or does it use that much CPU right after starting the app?

Do you have images/videos/GIFs in the channels you're viewing?

**Comment by jasonblais** [comment]
We haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the latest version. 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
