### ISSUE TITLE
Not working --proxy-server option in Windows

### ISSUE THREAD

**Issue by xswqaz** [mattermost/desktop#754]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

Not working --proxy-server option in Windows

**Steps to reproduce**

- Operating System
   Windows 7
- Mattermost Desktop App version (See **Help > Version Number**)
   4.0.1
- Mattermost Server version (See **Mattermost Menu > About Mattermost**, where **Mattermost Menu** can be accessed by clicking on three dots next to your profile picture)
   4.8.0
- Clear steps to reproduce the issue
   Mattermost.exe --proxy-server=ipaddress:port
-->

**Expected behavior**

Success to connect server with proxy

**Observed behavior**

Failed to connect server with proxy
Success to connect intranet server
I think proxy-server option is not working

**Possible fixes**

**Comment by yuya-oc** [comment]
@xswqaz Does `Mattermost.exe -- --proxy-server=ipaddress:port` work for you?

**Comment by xswqaz** [comment]
Thanks It works!
be helpful if It written to readme.md
