### ISSUE TITLE
Mattermost team invite link no longer works from Desktop app

### ISSUE THREAD

**Issue by bbodenmiller** [mattermost/desktop#758]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Team invite link no longer works in desktop app

**Steps to reproduce**
1. Get invite link to new team
1. Click link from app

Takes you to login screen, login, does not join you to new team

Windows 10
Desktop 4.0.0
Server: Version: 4.7.1 (4.7.3), Database: postgres

**Expected behavior**

Join me to team

**Comment by yuya-oc** [comment]
Reproduced with Mattermost server 4.7.2 (4.7.4) also on Chrome. And 4.8.1 doesn't have the problem.

Steps to reproduce
1. Post an invite link of another team on same server.
2. Click the link from an account which does not belong to the team.
3. Observed the email signup.

**Comment by jasonblais** [comment]
@bbodenmiller Can you help ask your System Administrator to upgrade your Mattermost server to 4.8.0 or later? That should resolve this issue.

Closing the issue, but let me know if upgrading doesn't resolve it and we can re-open.
