### ISSUE TITLE
Korean characters are broken while typing in message input box.

### ISSUE THREAD

**Issue by xiles** [mattermost/desktop#759]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

Korean characters are broken when typing.

**Steps to reproduce**

- macOS High Sierra
- 4.0.1
- Type Korean in message input box. (Input Sources - 2-Set Korean)

**Expected behavior**
input should look like this in message typing area.
"한글입력문제"

**Observed behavior**
input looks like this
"ㅎㅏㄴㄱㅡㄹㅇㅣㅂㄹㅕㄱㅁㅜㄴㅈㅔ"

![mattermost-korean-input](https://user-images.githubusercontent.com/906821/38718168-a6ad602e-3f26-11e8-8981-79180513898a.png)

**Possible fixes**

**Comment by yuya-oc** [comment]
Reproduced on pre-release 4.9.0-rc4 with Japanese text.

@jasonblais Probably it's similar to https://github.com/mattermost/desktop/issues/701. Would you check with webapp team?

**Comment by jasonblais** [comment]
Thanks! I've created a ticket for the webapp team to investigate https://mattermost.atlassian.net/browse/MM-10197

**Comment by yuya-oc** [comment]
Ref: https://github.com/mattermost/mattermost-server/issues/8206

**Comment by jasonblais** [comment]
This is now fixed server-side. You can upgrade the Mattermost server to v4.9.0 to have it resolved.

https://github.com/mattermost/mattermost-webapp/pull/1099
