### ISSUE TITLE
main screen stays empty

### ISSUE THREAD

**Issue by grexe** [mattermost/desktop#76]
We host a Mattermost 1.3.0 instance integrated with our GitLab 8.4.3 server.
Accessing Mattermost over the web works fine, but I couldn't get the app working (couldn't find a description on the exact URL to use, tried different variations to no avail) - I can see the login screen shortly, but afterwards the screen goes blank.
Using version 0.36.7 on Arch/Manjaro Linux 4.5.0-1 x64.

**Comment by yuya-oc** [comment]
Is it a https URL? If it is, can #26 help your trouble?

**Comment by yuya-oc** [comment]
Sorry, previous one is my misunderstanding because you can see the login screen. Did you try "Clear Cache and Reload(Ctrl+Shift+R)"? It might solve displaying issue.

Then, please write application version. 0.36.7 seems Electron's version.

**Comment by cadecairos** [comment]
@grexe I had this issue on my Antergos machine, and was able to resolve it by downgrading my freetype package to 2.6.2-1 from 2.6.3-1

**Comment by npcode** [comment]
I have this issue too. I can see this black screen after login.
![mattermost-empty](https://cloud.githubusercontent.com/assets/1129852/13765275/1816eaf6-ea9b-11e5-895c-3ec74cf87c9d.png)

server: mattermost 1.4.0
front: electron-mattermost 1.0.7 on Linux 4.4.3-1-ARCH / GNOME shell

"Clear cache and Reload" did not help.

**Comment by yuya-oc** [comment]
Hmm...I just tried with Ubuntu in VirtualBox, it can show the app properly.

![ubuntu14 04](https://cloud.githubusercontent.com/assets/1412057/13777197/fa5314d4-eaf1-11e5-800a-4ee4d6dd5b2d.PNG)

server: mattermost 2.0.0 and 2.1.0
front: electron-mattermost 1.0.7 on Ubuntu 14.04 64bit, freetype 2.5.2-1ubuntu2.5

It seems that it's hard to figure out why this happens.
Could you try updating Electron version? (It can be updated by changing [electron-prebuilt](https://github.com/mattermost/desktop/blob/v1.0.7/package.json#L31))

@npcode After login? Can you see the login screen correctly until login?

**Comment by cadecairos** [comment]
See: https://github.com/atom/electron/issues/4513

**Comment by yuya-oc** [comment]
@cadecairos Thank you! I have to update Electron at next release.

**Comment by grexe** [comment]
Thank you @cadecairos for linking, now I understand. Thanks @yuya-oc for the quick reaction. Now I guess I'll just wait patiently for the next update...,-)

**Comment by cadecairos** [comment]
If you really would like to use it, I found that the bug did not affect a previous version of freetype, and used the [Arch Linux Archive](https://wiki.archlinux.org/index.php/Arch_Linux_Archive) to grab an older version and downgraded to it with pacman.

I also forked the project a while back and updated electron to 0.36.10, and added a simple tray icon for linux :) (I thought the project was getting abandoned, but I'm glad that's no longer the case!) I have prebuilt binaries for it here if you care to use them: https://github.com/cadecairos/electron-mattermost/releases/

**Comment by npcode** [comment]
@yuya-oc Yes, I could see the login screen correctly.
