### ISSUE TITLE
Mattermost desktop client fails to open (black window) if GPU acceleration is busted on Linux

### ISSUE THREAD

**Issue by fermulator** [mattermost/desktop#763]
I confirm (by marking "x" in the [ ] below: [x]):

- [x ] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
If the user's desktop system has "GPU acceleration issues", Mattermost fails to open

**Steps to reproduce**

- Operating System - Linux (Fedora 26, Ubuntu 17.10, etc. - most major distros)
- Mattermost Desktop App version v4.0.1
- Mattermost Server version v4.7.1

Exact steps to reproduce are UNKNOWN - (unclear how/when/why the system has "GPU acceleration problems" - confirmation via glxgears also having "black window")

**Expected behavior**

In order to protect from this problem, Mattermost (as an enhancement), should self-detect that GPU acceleration is broken, and continue on without it (notifying the user).

**Observed behavior**

Occasionally (on multiple Linux systems; Fedora, Ubuntu, etc. - I have a few), I’ve observed Mattermost “hung” on the system and had to kill the PID. Upon attempting to re-open, the application refuses to re-open properly and usually looks like this:

https://discourse-cdn-sjc2.com/standard16/uploads/mattermost/optimized/2X/4/4d88e2c33bcbef75f8d3cab9982d4f0226e904c0_1_690x420.png

To see that GPU acceleration is busted, try running glxgears

https://discourse-cdn-sjc2.com/standard16/uploads/mattermost/optimized/2X/d/d5bffdd21b3aeee8362e62c5c7d8f9a2cb551c85_1_690x470.png

See https://forum.mattermost.org/t/solved-occasional-black-app-from-mattermost-desktop-app-on-linux/4763

**Workaround**

 1. Temporarily open the mattermost-desktop application with the "--disable-gpu" flag
 2. GUI? (unknown) - can't find a setting to disable it perminantly

**Possible fixes**

TBD
 (see expected behaviour for an idea)

**Comment by yuya-oc** [comment]
As I wrote on the forum, the GPU hardware acceleration will be disabled by default since v4.1.0. And it would be one of the app options in the settings page.

https://forum.mattermost.org/t/solved-occasional-black-app-from-mattermost-desktop-app-on-linux/4763/2?u=yuya-oc

Ref: #713
