### ISSUE TITLE
Blank screen on team switch

### ISSUE THREAD

**Issue by avasconcelos114** [mattermost/desktop#767]
I confirm (by marking "x" in the [ ] below: [x]):
- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Screen goes blank (white) when switching teams, only changes back to normal when clearing cache/refreshing with `Ctrl + Shift + R`

**Steps to reproduce**
1. Log into a server with multiple teams
2. Select a different team through the sidebar
3. Screen is now blank, hit `Ctrl + Shift + R` to have it go back to normal

- Operating System: **Windows 7**
- Mattermost Desktop App version: **v4.0.1**
- Mattermost Server version: **v4.9.0**

**Expected behavior**
App switches teams and renders everything normally

**Observed behavior**
Screen turns completely white and will only change back to normal upon refresh
![image pasted at 2018-4-18 17-08](https://user-images.githubusercontent.com/29700158/39165612-48bf3ecc-47c0-11e8-82fb-f8e0e08ef2b6.png)

**Possible fixes**
Could not find one. Issue doesn't seem to reproduce on every Windows 7 computer either

**Comment by yuya-oc** [comment]
Would you try enabling Windows Aero? Classic theme doesn't use DWM though, our underlying framework, Electron has an issue in such situation.

https://github.com/electron/electron/issues/1821

**Comment by SeungwooYu** [comment]
It does not relate to Windows Aero Theme, after enabling Aero the problem also exists.

**Comment by yuya-oc** [comment]
Thanks. Assuming that, there is another problem in rendering. I’m wondering if you could try [v4.1.0-rc1](https://github.com/mattermost/desktop/issues/768). It has better stability in rendering.
Although I have never heard the example which `Ctrl+Shift+R` can be workaround in such case. If v4.1 doesn’t solve the problem, we need more detailed research.

**Comment by SeungwooYu** [comment]
After install v4.1.0-rc1
It looks not fixed. Moreover, this issue now also happens on the Chrome, Opera, etc.... (when a user switches to other team channels, it happens).  Maybe Windows 7 users are getting to feel un-convenient this blank screen; everytime user should reload( 100 times more per day, on my god)


![image](https://user-images.githubusercontent.com/21060234/39480704-faea32bc-4da3-11e8-9ac8-8d8e3b219e59.png)

![image](https://user-images.githubusercontent.com/21060234/39480711-00d5b886-4da4-11e8-9139-8ebbdcfec75f.png)

**Comment by yuya-oc** [comment]
@jasonblais Would you take a look this? Possibly it's webapp issue.

**Comment by avasconcelos114** [comment]
I'm fairly certain now that this issue is related to [a comment](https://github.com/mattermost/mattermost-server/issues/8320#issuecomment-385879711) I wrote about a bug that happens when a team is deleted using the API. Since a [ticket](https://mattermost.atlassian.net/browse/MM-10432) has already been created on Jira, we could probably close this one.

**Comment by jasonblais** [comment]
Thanks @avasconcelos114 and @yuya-oc! Closing this and we'll track the issue via https://mattermost.atlassian.net/browse/MM-10432
