### ISSUE TITLE
Clear Cache and Reload in the Menu Bar - doesn't work

### ISSUE THREAD

**Issue by amyblais** [mattermost/desktop#769]
Windows, doesn't repro on browser.

Repro steps:
1. Go to View > Clear Cache and Reload in the Menu Bar

Expected:
Clears cache successfully and reloads the current page

Observed:
Cache not cleared properly. E.g. text in a message box (not posted yet) does not disappear.

**Comment by jasonblais** [comment]
Sorry @amyblais I mis-reported this issue to you. The message does stay in the message box (doesn't disappear) and this is in fact expected.

My mistake, sorry. Closing the issue.
