### ISSUE TITLE
Change window title to Mattermost Desktop (beta)

### ISSUE THREAD

**Issue by mikaoelitiana** [mattermost/desktop#77]
The application window still use 'electron-mattermost' as title yet the project was renamed 'Mattermost Desktop'

**Comment by nItroFreeZer** [comment]
It's already done in commit [e82d6be0b5e0bc63207f45641ec7bdca2ebc08b4](https://github.com/mattermost/desktop/commit/e82d6be0b5e0bc63207f45641ec7bdca2ebc08b4).
