### ISSUE TITLE
Issues with setting "Show red badge on taskbar icon to indicate unread messages"

### ISSUE THREAD

**Issue by amyblais** [mattermost/desktop#770]
Windows

**Case 1**

Repro steps:
1. Select "Show red badge on taskbar icon to indicate unread messages"
2. Press "Save"
3. Open at least one team with at least unread message, but no unread mentions
4. Open at least one team with at least one unread mention

Expected:
Step 3: Red dot displayed on the taskbar icon, indicating unread messages
Step 4: Red dot with a number displayed on the taskbar icon, counting unread mentions across all team tabs 

Observed:
Step 3: No red dot.
Step 4: No red dot and no unreads count.
_____________________________________________________

**Case 2**

Repro steps:

1. Unselect "Show red badge on taskbar icon to indicate unread messages"
2. Press "Save"
3. Open at least one team with at least unread message, but no unread mentions
4. Open at least one team with at least one unread mention

Expected:
Step 3: No red dot displayed on the taskbar icon
Step 4: Red dot with a number displayed on the taskbar icon, counting unread mentions across all team tabs 

Observed:
Step 4: No red dot and no unreads count

**Comment by yuya-oc** [comment]
Not reproduced for me on Windows 10.

Server 1: pre-release.mattermost.com: ci build 3802 (it has unread messages and no unread mention)
Server 2: 4.8.1 (it has unread mention)

@amyblais Would you check again and write server version?

**Comment by amyblais** [comment]
To clarify, is the task bar icon the one in the screenshot or the one in the second screenshot? This repros for me in the case of the first screenshot, but not for the second screenshot.

![screenshot_63](https://user-images.githubusercontent.com/29708087/39439112-80c7bba6-4c74-11e8-9152-98fea4c45745.png)

![screenshot_64](https://user-images.githubusercontent.com/29708087/39439125-8468e0c8-4c74-11e8-96be-5b4ca5fecbfd.png)

**Comment by yuya-oc** [comment]
Yeah, the first screenshot shows "Taskbar icon", which I meant.

**Comment by amyblais** [comment]
In that case I can still repro, but I haven't heard any other reports about this so maybe this is just my computer (not reproing on Mac) - so maybe I'll continue to monitor and we can fix later.

**Comment by yuya-oc** [comment]
Okay, let's wait another report or more observation.

**Comment by jasonblais** [comment]
@amyblais Let's ask if this reproduces for Lindy, who is also on Windows? That way we have at least two people on Windows who cannot reproduce.

**Comment by DHaussermann** [comment]
I was unable to reproduce this. Checked both cases. The functionality on 4.1.0 is behaving as expected for me.

**Comment by amyblais** [comment]
Thank you for testing! I'll close this for now.
