### ISSUE TITLE
Deep linking issues

### ISSUE THREAD

**Issue by amyblais** [mattermost/desktop#771]
**Case 1**

Repro Steps:
1. Sign in to https://pre-release.mattermost.com on your desktop app
2. Post mattermost://pre-release.mattermost.com/core/channels/developers into a channel
3. Quit the desktop app
4. Sign in to https://pre-release.mattermost.com on your browser
5. Click on the link you posted in step 2.

Expected:
Desktop app launches, and opens the Developers channel.

Observed:
Mac: Link causes https://github.com/mattermost/desktop/issues/705
Windows: Error message
![screenshot_60](https://user-images.githubusercontent.com/29708087/39219451-8e660b4e-47f8-11e8-9139-d6be2c31e155.png)

________________________________________________________________________________

**Case 2**

Repro steps:
1. Sign in to https://pre-release.mattermost.com on your desktop app
2. Post mattermost://pre-release.mattermost.com/core/channels/developers into a channel
3. Sign in to https://pre-release.mattermost.com on your browser
4. Click on the link you posted in step 2.

Expected:
Desktop app launches, and opens the Developers channel.

Observed:
Windows: Same error as above.

**Comment by yuya-oc** [comment]
Not reproduced for me on Windows 10.

@amyblais Would you check again? When you meet the error like the screenshot, please check "Show Details".

**Comment by amyblais** [comment]
@yuya-oc This is the error message when I click "Show more details":

Application: Mattermost 4.1.0
Platform: Windows_NT 10.0.16299 x64
TypeError [ERR_INVALID_URL]: Invalid URL: 
    at onParseError (internal/url.js:219:17)
    at parse (internal/url.js:228:3)
    at new URL (internal/url.js:311:5)
    at Function.<anonymous> (C:\Users\Amy\Downloads\mattermost-desktop-4.1.0-rc1-win64 (1)\resources\app.asar\main_bundle.js:15415:23)

However, when I repeat the steps in webapp, a blank screen opens in another tab, so maybe this is a server issue?

**Comment by yuya-oc** [comment]
As far as looking the error stack, somehow the problem is happening at permission request handler apart from deep linking. So it seems that there is the timing the handler can't correctly get URL when deep linking works. I'll add a fallback there.

About the second blank tab, it's webapp issue. I think the link has `target="_blank"` attribute, so web browsers try to open a new tab.
