### ISSUE TITLE
Clicking on a file:// protocol path does nothing

### ISSUE THREAD

**Issue by amyblais** [mattermost/desktop#772]
Repro steps:

1. Post a "file://..." path to a channel. (e.g. file://\\ComputerName\ShaedFolder)
2. Click on that link.

Expected:
Windows explorer opens.

Observed:
Nothing happens.

See PR here: https://github.com/mattermost/desktop/pull/712

**Comment by yuya-oc** [comment]
@amyblais Would you try again with `file://\\ComputerName\ShaedFolder`? I think `\\` is needed before `ComputerName`.

**Comment by amyblais** [comment]
Not able to repro this anymore, closing.
