### ISSUE TITLE
Not able to type in "Add Server" dialog when accessing via the "+" icon

### ISSUE THREAD

**Issue by amyblais** [mattermost/desktop#780]
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

Repro steps:
1. Press "+" to add a new server.
2. Start to type in / paste text in the textbox.

Observed:
Not able to type in the box. App freezes.

![image](https://user-images.githubusercontent.com/13119842/39389265-b932d812-4a54-11e8-9c92-eb28c8527104.png)

Expected:
Should be able to type in the box.

**Comment by yuya-oc** [comment]
Closed via #782
