### ISSUE TITLE
Desktop and Browser client keyboard shortcut for scroll up/down message list possible?

### ISSUE THREAD

**Issue by Murmur** [mattermost/desktop#783]
Tested on Windows10 Firefox and the latest Desktop client. I don't find a keyboard shortcut to scroll a message list up and down. Slack has PageUp/PageDown keycodes to scroll message list while focus is in a message prompt field. 

Is this possible in Mattermost(browser, desktop) or considered to have in a future?

**Comment by yuya-oc** [comment]
@jasonblais Would you confirm this?

**Comment by yuya-oc** [comment]
Confirmed on Slack webapp. So probably it's possible feature also on Mattermost webapp.

**Comment by jasonblais** [comment]
@amyblais Sounds like this applies to both browser and desktop. Can you help create an improvement ticket for the platform team and we can track this issue there? Let me know if I can help.

Thanks @Murmur for the feedback 👍

**Comment by jasonblais** [comment]
@amyblais Sounds like this applies to both browser and desktop. Can you help create an improvement ticket for the platform team and we can track this issue there? Let me know if I can help.

Thanks @Murmur for the feedback 👍

**Comment by amyblais** [comment]
This can now be tracked through this ticket: https://mattermost.atlassian.net/browse/MM-10435
