### ISSUE TITLE
Desktop Centos client

### ISSUE THREAD

**Issue by jamesacampbell** [mattermost/desktop#784]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
I would like a release for Centos. 

**Steps to reproduce**

Go to downloads. 
No Centos version.

**Possible fixes**

Build and compile a version for Centos.

**Comment by jasonblais** [comment]
Thanks, appreciate your feedback @jamesacampbell! 

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [ticket accepting pull requests](http://docs.mattermost.com/process/accepting-pull-request.html)?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

/cc @amyblais

**Comment by jamesacampbell** [comment]
@jasonblais @amyblais I am closing this issue as it turns out the linux download works out of the box on Centos. Sorry for the confusion.

**Comment by jasonblais** [comment]
No worries, thanks for following up!
