### ISSUE TITLE
 Clicking on a video attachment and then clicking on the icon (not the download link) of the attachment opens another Mattermost window

### ISSUE THREAD

**Issue by amyblais** [mattermost/desktop#792]
https://mattermost.atlassian.net/browse/MM-14163

Happens at least on Windows, 4.0.1 and 4.1.0-RC. Did not repro on webapp.

**Steps to reproduce**
1. Upload and post a video attachment to a channel.
2. Click the icon of the attachment (not the download button).

**Expected behavior**
Should not open a new window.

**Observed behavior**
A new Mattermost window is opened.

**Comment by ylluminate** [comment]
I realize that this is not entirely related, but I wanted make note that video playback is missing video in macOS 10.13.6 when clicking the play button / image in a video preview within the client for videos such as YouTube videos.  Audio plays, but no video.

Let me know if you'd like for me to generate a new issue or if this could be related to a 4.2 inbound update.

**Comment by yuya-oc** [comment]
Hi @ylluminate, thanks for reporting. The issue is different thing, so would you create a new one? I feel the problem didn't reproduce for me, so probably you need to include more detailed information (please see the template which appears when you create a new issue)

**Comment by ylluminate** [comment]
Thanks @yuya-oc. I tried it in a web client on Chrome and got the same result so I've pushed this over to the `-server` Issues: https://github.com/mattermost/mattermost-server/issues/9145

**Comment by weekscharlie** [comment]
I'd like to propose you target this issue for the 4.3.0 milestone.  We've been waiting a while for the many great fixes already incorporated into 4.2.0 and a Priority 2 issue such as this one shouldn't delay the 4.2.0 release (IMO).

**Comment by amyblais** [comment]
Jira ticket for tracking: https://mattermost.atlassian.net/browse/MM-14163

**Comment by esethna** [comment]
Hi @ylluminate, we haven't received an update so we'll assume that the problem is fixed or is no longer valid.

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/).

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
