### ISSUE TITLE
Possible client side memory leak

### ISSUE THREAD

**Issue by amyblais** [mattermost/desktop#793]
https://mattermost.atlassian.net/browse/MM-14164

From https://forum.mattermost.org/t/possible-client-side-memory-leak/4842

**Summary**
Noticed that the Mattermost client slows down the longer it is run for.

**Steps to reproduce**
Leave Mattermost application open for an extended period of time (days)

**Expected behavior**
Application continues to run quickly and smoothly. No noticeable delay while typing, submitting messages, switching channels, etc.

**Observed behavior**
Application slows down the longer it is open for. Sometimes it is very very slow to respond. A user can type an entire sentence and it won’t display and then suddenly it will all display at once. Other times it takes several seconds to switch between channels.

Users reporting issues are using v4.0.1 of the Mattermost Electron desktop app.

**Comment by amyblais** [comment]
Amy to follow up with original reporter after final is cut.

**Comment by jahller** [comment]
hi there. I can definitely report the same for the `electron app` running on `macOS Sierra 10.12.6`

**Comment by amyblais** [comment]
Hi @jahller! We released v4.1 just today and it is available to download here: https://about.mattermost.com/download/. Would you like to try upgrading to that version and see if it fixes the issue? v4.1 includes fixes related to this. Let me know what you find!

**Comment by weekscharlie** [comment]
I'd like to propose you target this issue for the 4.3.0 milestone. We've been waiting a while for the many great fixes already incorporated into 4.2.0 and a Priority 2 issue such as this one shouldn't delay the 4.2.0 release (IMO).

**Comment by amyblais** [comment]
Jira ticket for tracking: https://mattermost.atlassian.net/browse/MM-14164

**Comment by esethna** [comment]
@jahller does this still occur for you after v4.2?

If so please also indicate server version you're running

**Comment by wget** [comment]
Unable to reproduce on Windows. The latest 4.2.0 production release have been running for a few months on my Windows Dev server and I haven't noticed any memory leaks other than the 350 Mio resident memory the electron bundle is consuming.

I think we can close the Jira ticket as well.
