### ISSUE TITLE
Seeing white screen after leaving desktop app on standby for a while

### ISSUE THREAD

**Issue by amyblais** [mattermost/desktop#794]
https://mattermost.atlassian.net/browse/MM-14166

Reported by customers, this issue is for tracking. QA has a related ticket to investigate: https://mattermost.atlassian.net/browse/MM-10408. Might be network related.

**Comment by colchuck** [comment]
I get it several times a day - I don't seem get it on Linux - error logs come up with this a lot:

Application: Mattermost 4.1.1
Platform: Windows_NT 6.1.7601 x64
Error: webContents 'crashed' event has been emitted
    at WebContents.mainWindow.webContents.on (C:\Users\d2\AppData\Local\mattermost\app-4.1.1\resources\app.asar\main_bundle.js:6159:11)
    at emitTwo (events.js:130:20)
    at WebContents.emit (events.js:213:7)

Toggling GPU acceleration didn't seem to do anything. 

![screenshot_20180601_083445](https://user-images.githubusercontent.com/12130689/40849400-b6834f88-6576-11e8-9bed-bfd4c834e796.png)

**Comment by colchuck** [comment]
So I can't get to the Javascript console (CTRL SHIFT I) - it just turns the white screen to black. The logs (USER\AppData\Roaming\Mattermost\uncaughtException-*) just repeat the message from the last post over and over.

![screenshot_20180604_081704](https://user-images.githubusercontent.com/12130689/40926023-0d9713d0-67d0-11e8-842e-29e0c25a5ccf.png)

**Comment by amyblais** [comment]
@colchuck - Thank you for additional information - a few more questions: does this happen randomly or are there any specific repro steps to take? Is it temporary and do any steps help resolve the issue (e.g. refreshing the app)?

**Comment by colchuck** [comment]
It happens randomly - particularly when it hasn't been touched in a while - the only thing I can do is restart the App - going View->reload flashes the Mattermost splash logo and then goes back to blank. Closing the window but keeping it in the tray doesn't work - it just comes back blank - you have to completely exit out. I have 3 x64 Windows 7 machines - two with the exact same hardware and one with older hardware. All run as unprivileged users within a domain and all experience the same issue. For whatever reason, the older machine crashes maybe a couple time a week. The two newer ones that get much more use actually crash maybe 4 times a day. I have a fourth machine with older hardware and the same software that hasn't crashed at all.

**Comment by amyblais** [comment]
@yuya-oc FYI ^ - reporter has error logs here: https://github.com/mattermost/desktop/issues/794#issuecomment-393919550 and toggling GPU setting didn't help.

Is there any other additional information we could help gather to investigate this?

**Comment by yuya-oc** [comment]
The log `Error: webContents 'crashed' event has been emitted` was made by our event handler. So actually [a process had been dead by some reason](https://electronjs.org/docs/api/web-contents#event-crashed). To notice this via a dialog, we had added the event handler. But this prevents other behavior even if the internal chromium has countermeasure against to this kind of problem.

Now I worry about that we should not handle the `crashed` event. The test build which doesn't use the handler is below.

https://circleci.com/gh/yuya-oc/desktop/909#artifacts

If this doesn't make sense, we might need deep debugging of electron.

**Comment by Austin1** [comment]
Any updates on this issue? Been driving me crazy for last two versions and makes me reboot mattermost on a daily basis.

**Comment by colchuck** [comment]
Yeah, I never got anywhere with it - my (newer) suspicion was that it was something to do with it being run as an unprivileged user - I installed it as a user on 3 Windows 7 Pro/X64 (domain environment) machines and all 3 ended up crashing randomly. The one machine that was an administrator didn't seem to have any issues - but it's also running virtualized... so that doesn't exactly narrow down possibilities. I was never able to pull anything valuable from the logs... I assumed it was an electron problem and it was a "just me" thing.

**Comment by torlenor** [comment]
Just some random ideas: What GPU? Does your display go into power save/turn off after being idle for a while?

**Comment by holle** [comment]
I have seen a similar behaviour on my Linux Box (openSUSE 42.3) w/ KDE 3.5 as well. I am running my Linux with a Nvidia GT 610 and two attached displays configured using Nvidia's technique to have one screen with 3840x1080 pixels.

**Behaviour:**
Whenever Mattermost (official 4.1.2 release) had been idle for some time and I receive an incoming message the following happens:

1. I get a blank (black) screen and the app is not even responding to "Quit"
2. After approx. a minute or two the client recovers and shows the normal screen and can be used as if nothing had happened

The same version of mattermost-desktop on my mac book connected to the same private mattermost server does not expose this behaviour.

I have now turned off GPU acceleration to try figuring out any relations there.

**Comment by weekscharlie** [comment]
I'd like to propose you target this issue for the 4.3.0 milestone. We've been waiting a while for the many great fixes already incorporated into 4.2.0 and a Priority 2 issue such as this one shouldn't delay the 4.2.0 release (IMO).

**Comment by amyblais** [comment]
Jira ticket for tracking: https://mattermost.atlassian.net/browse/MM-14166

**Comment by esethna** [comment]
Is this still happening for folks in v4.2.0?

**Comment by amyblais** [comment]
Closing this as we cannot reproduce this anymore. Please report back if you still see this issue on v4.2.0.

**Comment by rakgenius** [comment]
Still seeing the issue in Version 4.2.1 (4.2.1.62)
Mac version 10.13.3 (High Sierra)

The issue happened at least 7 times within an hour and the issue happens to everyone in our team at the same time. Tried disabling the GPU acceleration and still didn't help.

The mac book was not in standby mode and it happened while replying to the message.

**Comment by amyblais** [comment]
Hi @rakgenius, do you see any log or Console errors?

**Comment by rakgenius** [comment]
I have attached the screenshot.
<img width="729" alt="mattermost" src="https://user-images.githubusercontent.com/10645273/59906842-f8b8fc00-9409-11e9-9750-de1b9690b597.png">

**Comment by rakgenius** [comment]
I have attached the screenshot.

![mattermost](https://user-images.githubusercontent.com/10645273/59907547-a1b42680-940b-11e9-8bc1-8f95c9716cae.png)

**Comment by amyblais** [comment]
@rakgenius What Mattermost server version are you on?

**Comment by rakgenius** [comment]
@amyblais Sorry for the late response.. Im using the version Version 4.2.1 (4.2.1.62)

**Comment by amyblais** [comment]
@rakgenius You can find out your server version from Mattermost > Main Menu > About Mattermost.

**Comment by lredor** [comment]
Hello,

For information, I have the same problem with Desktop App version 4.3.1 (server version is  "Mattermost Édition Team 5.16.3).

The log is:

> Application: Mattermost 4.3.1
Platform: Windows_NT 10.0.17763 x64
Error: webContents 'crashed' event has been emitted
    at WebContents.handleMainWindowWebContentsCrashed (C:\Users\userName\AppData\Local\Programs\mattermost-desktop\resources\app.asar\main_bundle.js:887:9)
    at WebContents.emit (events.js:194:13)

I noticed that simply maximize the window resolves the problem (the blank screen is replaced by the expected content).

Regards,

Laurent

**Comment by trch15** [comment]
Same issue here, white screen after upgrading Windows desktop clients from 4.2.x to 4.3.1.

- Only occurs when upgrading, not on clean installs of 4.3.1.
- Deleting appdata\local\mattermost solves the problem
- Deleting the 3 cache folders in appdata\local\mattermost doesn't solve the problem
- Resizing the window or exiting, then opening Mattermost again fixes the problem
- Closing the window, then opening the window from the tray icon doesn't fix the problem
- Disabling GPU acceleration makes no difference
- Only happens when users first login, happens every time
- Console doesn't list any errors

**Comment by T3rm1** [comment]
Same issue. Had 4.2.1 for a very long time and no problem at all. Upgraded to 4.3.1 and after a restart of the PC I now have a white screen.

**Comment by alexei-ciobanu** [comment]
> 
> 
> Same issue. Had 4.2.1 for a very long time and no problem at all. Upgraded to 4.3.1 and after a restart of the PC I now have a white screen.
> 
> Maximizing the window solves the problem.

I can't believe that actually worked for me. Many thanks.

**Comment by esethna** [comment]
Should be fixed in v4.3.2, are we okay to close this issue? cc// @amyblais

**Comment by devinbinnie** [comment]
Closing as per above.

**Comment by kipjunes** [comment]
@amyblais I was running v5.0.2 with no issues on my Windows 10 machine. Just upgraded to Windows 11. When I open MM, it initially shows the normal display with all of our teams and channels, but the entire screen goes white as soon as I move my mouse cursor. Have tried every troubleshooting step that I can think of and the same thing keeps happening. Not really sure what to do at this point - like so many others, I basically can't work without MM. Any help would be greatly appreciated.

**Comment by amyblais** [comment]
@kipjunes Would you be open to creating a new issue with details at https://github.com/mattermost/desktop/issues?

**Comment by kipjunes** [comment]
Sure thing @amyblais will do so now
