### ISSUE TITLE
Mattermost-desktop (via .deb package) utilizes an executable stack.

### ISSUE THREAD

**Issue by b1ack0wl** [mattermost/desktop#797]
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

The public beta Linux package (.deb) installs a version of mattermost-desktop that marks the stack and the heap as Read,Write,eXecute and allocates ~ 230 RWX pages. 

**Steps to reproduce**

1. Download Ubuntu 18.04 and install it into a VM
2. Download and install the latest mattermost-desktop AMD64 .deb package (https://releases.mattermost.com/desktop/4.0.1/mattermost-desktop-4.0.1-linux-amd64.deb)
3. Launch the `mattermost-desktop` application
4. Grep the process maps for mattermost-desktop and look at the permissions for the stack.
4a. Command: `for i in $(pidof mattermost-desktop); do cat /proc/$i/maps | grep stack; done` 

**Expected behavior**

The output from the command in `4a` should show that the stack is marked as RWX (Read,Write,eXecute)

**Observed behavior**

Mattermost-desktop running with an executable stack
```
test@test-virtual-machine:~$ for i in $(pidof mattermost-desktop); do cat /proc/$i/maps | grep stack; done
7ffecf983000-7ffecf9a4000 rwxp 00000000 00:00 0                          [stack]
```
Rough estimate of how many RWX allocations there are within the `mattermost-desktop` process.
```
test@test-virtual-machine:~$ for i in $(pidof mattermost-desktop); do cat /proc/$i/maps | grep rwxp | wc -l; done
242
```

**Comment by yuya-oc** [comment]
Confirmed. As written at https://github.com/electron/electron/issues/11628, it's fixed in Electron 1.8.3. Our upcoming v4.1 uses Electron 1.8.4, so it would fix this problem.

@b1ack0wl Please let me confirm. Actually v4.1.0-rc3's stack is listed as `rw-p`. Is it the expected behavior in this issue?

**Comment by b1ack0wl** [comment]
My apologies for the delay, but yes! The stack and heap should be marked as `rw-p`. Thank you so much for following up with a solid action plan! I'll be closing this ticket to reduce ticket volume. :)

Thanks again!!

**Comment by yuya-oc** [comment]
Now v4.1.0 is released, so I close this. Thanks!
