### ISSUE TITLE
Mattermost crashes when shutting down using the Start Menu

### ISSUE THREAD

**Issue by ssolidus** [mattermost/desktop#800]
I confirm (by marking "x" in the [ ] below: [x]):

- [ x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [ x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

https://mattermost.atlassian.net/browse/MM-14170

**Summary**
When initiating a shutdown of your PC, Mattermost does not exit gracefully - it crashes

**Steps to reproduce**
 - Operating System: Windows 7 x64
 - Mattermost Desktop App version: 4.0.1
 - Mattermost Server version: 4.9.0

1. Open Mattermost Desktop
2. Initiate a shutdown of your computer using the **Start menu**
![image](https://user-images.githubusercontent.com/14216632/40055053-02dd4590-588a-11e8-8f07-716de271ee9a.png)

**Expected behavior**

Mattermost should exit gracefully, closing itself

**Observed behavior**

Mattermost crashes

**Possible fixes**

Implement a procedure that handles a shutdown call from the operating system gracefully

**Comment by amyblais** [comment]
Jira ticket for tracking: https://mattermost.atlassian.net/browse/MM-14170.

**Comment by esethna** [comment]
We can't repro this on Windows 10. Is this still an issue for you @BadPackets @ssolidus? What is observed when the app crashes?

**Comment by ssolidus** [comment]
@esethna I will try reproducing shortly

**Comment by lindy65** [comment]
Hi @ssolidus :) Any update on whether the issue is still reproducing for you?

**Comment by ssolidus** [comment]
Hi @lindy65 @esethna, apologies I took some time to get back to you. Yes, Mattermost still crashes with an error when you shut down a Win7 PC with it open.

**Comment by lindy65** [comment]
Thanks for confirming @ssolidus,

Would it be an option to install the [latest version of the Desktop App](https://mattermost.com/download/#mattermostApps) to see whether the issue persists?  Perhaps upgrading to the [latest version of Mattermost server](https://mattermost.com/download/#server) is also an option?

**Comment by ssolidus** [comment]
> Thanks for confirming @ssolidus,
> 
> Would it be an option to install the [latest version of the Desktop App](https://mattermost.com/download/#mattermostApps) to see whether the issue persists? Perhaps upgrading to the [latest version of Mattermost server](https://mattermost.com/download/#server) is also an option?

I already use the latest version of the Desktop app.

**Comment by lindy65** [comment]
Thanks @ssolidus 

I was going by what you had reported above:

> Mattermost Desktop App version: 4.0.1
Mattermost Server version: 4.9.0

Has this information changed?  What Mattermost server version are you using now?

**Comment by devinbinnie** [comment]
Closing as inactive/cannot reproduce
