### ISSUE TITLE
Help menu is not accessible by keyboard under Windows

### ISSUE THREAD

**Issue by nmatt** [mattermost/desktop#804]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

On the Windows client, the "Help" menu is not accessible by keyboard. This is because both the "History" and the "Help"  menu have the same accelerator letter "H" assigned, so Alt+H opens the "History" menu (presumably because it comes first). Furthermore, the menu bar doesn't follow the normal Windows UI convention that you can toggle keyboard focus from/to the menu bar by presing just the Alt key, and that you can navigate between menus using the left/right arrow keys when keyboard focus is on the menu or menu bar, thereby preventing the other way the "Help" menu could be accessed using the keyboard.

**Steps to reproduce**

Press Alt+H, or press and release just Alt, and then press the left/right arrow keys.

Operating System: Windows 7
Mattermost Desktop App version: 4.1.1
Mattermost Server version: 4.10.0

**Expected behavior**

The "History" menu should have a different accelerator key than the "Help" menu. (For example, Firefox uses "S" for "History" instead of "H".) In addition or alternatively, one should be able to access the menu bar just by pressing Alt, and navigate between the menus using the left and right arrow keys (compare with the menu behavior in Notepad for example).

**Observed behavior**

Pressing Alt+H invokes the "History" menu. Pressing just Alt shows the accelerator keys, but doesn't move keyboard focus to the menu bar. Apparently the menu bar is not capable of having keyboard focus, contrary to Windows UI conventions. Furthermore, when keyboard focus is on a menu (e.g. after pressing Alt+H), then the left and right arrow keys don't move the keyboard focus from one menu to the next.

**Comment by amyblais** [comment]
Closing via Feature Request issue: https://mattermost.uservoice.com/forums/306457-general/suggestions/36845134-desktop-app-help-menu-should-be-accessible-by-key.
