### ISSUE TITLE
Random freezes after 4.1.0 upgrade

### ISSUE THREAD

**Issue by shochdoerfer** [mattermost/desktop#807]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [ ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

After upgrading to version 4.1.0 of the Mattermost desktop app, every now and then when writing messages the app freezes for a while (~15sec). I am not able to enter more text. This happens once or twice a day. I was not able to reproduce it in a web browser, given this doesn't happen regularly on desktop, this could just be a coincidence.

- Operating System: Linux (KDE Neon User Edition)
- Mattermost Desktop App version: 4.1.0
- Mattermost Server version: 4.10.0
- Clear steps to reproduce the issue

**Comment by amyblais** [comment]
Hi @shochdoerfer, thank you for reporting this issue!

Has this issue been happening daily? Would there be any logs that you would be able to gather from around the time the freezes occur?

**Comment by shochdoerfer** [comment]
The issue happened twice so far, in both cases I had the app open for hours. I don't have any logs regarding the freeze, will see if I provide those at a later point.

**Comment by yuya-oc** [comment]
We added a mechanism to clear memory cashes at v4.1.0. https://github.com/mattermost/desktop/pull/746

Possibly it might affect performance. However its interval is 6 hours, so I think you would not see that frequently.

**Comment by shochdoerfer** [comment]
Hmm, not sure if it really is the client. I switched to Rambox a few days ago and also got a freeze once when having a Mattermost tab open.

**Comment by shochdoerfer** [comment]
Just had another freeze and wasn't able to open another application, thus feels more like a KDE / Linux issue rather an an issue with the desktop app. Will close the issue for now. Might re-open it, if I can clearly say that this is Mattermost issue.
