### ISSUE TITLE
OS X: icon doesn't respect OS grid

### ISSUE THREAD

**Issue by lloeki** [mattermost/desktop#82]
OS X has design guidelines that use consistent sizes and appearance (subtle to-down gradient). See [Inspecting Yosemite's Icons](http://martiancraft.com/blog/2014/07/inspecting-yosemite-icons/)

`electron-mattermost` doesn't respect those and jarringly stands out as unpolished.

<img width="205" alt="screen shot 2016-03-17 at 10 13 02" src="https://cloud.githubusercontent.com/assets/75445/13841372/e06df0b0-ec28-11e5-8e5e-f3195888be4f.png">

Feel free to use, hack or take inspiration from Matterfront's icon (which respects both internal and external rings as well as the ambient lightning gradient). Alternatively, use the [icon grid](http://martiancraft.com/downloads/20140703_yosemite_Grid-PSD.zip).

**Comment by yuya-oc** [comment]
The icon is replaced by #85. It follows the grid.
