### ISSUE TITLE
Bad quality icon

### ISSUE THREAD

**Issue by aborderon** [mattermost/desktop#828]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: Ubuntu 18.04 - 64 Bit
- Mattermost Desktop App version: 4.1.2
- Mattermost Server version: 4.10

**Steps to reproduce**
I've installed the mattermost client with the .deb package. Configured my server and then try to configure the client itself.

**Expected behavior**
Display icon in good quality when launching the application.

**Observed behavior**
The icon in the favorites of the ubuntu dock is in good quality but at the launch of mattermost a new icon appears for the application and this one does not have a good quality icon.

![capture d ecran de 2018-06-15 09-45-08](https://user-images.githubusercontent.com/6728728/41456585-37b954a2-7081-11e8-9f53-46ff51e858b6.png)

**Possible fixes**

**Comment by ArchangeGabriel** [comment]
The next release has an SVG icon instead of PNG, maybe that will solve this issue. Or it might be the same issue as KDE, where all electron systray icons are lowres ones.

**Comment by yuya-oc** [comment]
SVG doesn't affect .deb packages. Actually too high resolution icon is applied on Linux. It's the reason.

https://github.com/mattermost/desktop/blob/v4.1.2/src/main/mainWindow.js#L34-L36

However I'm not sure what is correct handling about this because Linux has various window managers. I'm wondering if you could help testing.

**Comment by aborderon** [comment]
I managed to solve the problem by avoiding having a second icon open when launching Mattermost by modifying the launcher's (.desktop file).

I added the following line at the end of the file:
`StartupWMClass=Mattermost`

Here is the complete output of the .desktop
```
[Desktop Entry]
Name=Mattermost
Comment=Mattermost
Exec="/opt/Mattermost/mattermost-desktop" %U
Terminal=false
Type=Application
Icon=mattermost-desktop
Categories=InstantMessaging;
```

**Comment by erik-alatest** [comment]
> I managed to solve the problem by avoiding having a second icon open when launching Mattermost by modifying the launcher's (.desktop file).
> 
> I added the following line at the end of the file:
> `StartupWMClass=Mattermost`
> 
> Here is the complete output of the .desktop
> 
> ```
> [Desktop Entry]
> Name=Mattermost
> Comment=Mattermost
> Exec="/opt/Mattermost/mattermost-desktop" %U
> Terminal=false
> Type=Application
> Icon=mattermost-desktop
> Categories=InstantMessaging;
> ```

Adding `StartupWMClass=Mattermost` to the end of mattermost-desktop.desktop did the trick

![image](https://user-images.githubusercontent.com/32742367/51831317-15855380-22f2-11e9-9dc7-8132f98fc2fd.png)

Previously it was all jagged and horrible.

**Comment by skewty** [comment]
Can this please be re-opened until it is included in the .deb and .rpm and snap packages offered?

**Comment by skewty** [comment]
@yuya-oc while somebody is in the .desktop file adding a `StartupWMClass=Mattermost`line, perhaps the `Exec=` line should also be changed to `Exec=env GTK_THEME=Adwaita:light /opt/Mattermost/mattermost-desktop %U` until #899 is resolved.

PS: don't forget to re-open this issue until the issue is actually resolved.  I believe currently it is only solved.
