### ISSUE TITLE
When using a proxy that has its own certificates, such as BURP, and then turning it off, Mattermost does not load

### ISSUE THREAD

**Issue by ssolidus** [mattermost/desktop#829]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

https://mattermost.atlassian.net/browse/MM-14171

**Summary**

**Environment**
- Operating System: Windows 7 x64
- Mattermost Desktop App version: 4.1.0
- Mattermost Server version: 4.9.0

**Steps to reproduce**
- Download [https://portswigger.net/burp](BURP)
- Open BURP and Mattermost
- Go into Windows Internet Options > Connections > LAN settings
- Set the proxy server for the system to BURPs, which is `localhost:8080

**Expected behavior**

Mattermost continues to function as normal

**Observed behavior**

After showing innumerable amounts of prompts asking to accept the PortSwigger CA (somewhat expected behaviour), Mattermost shows a blank white screen. Doing **Clear Cache and Hard Reload** does not work, nor does restarting the application. 

The only solution is to close BURP, turn off the proxy, do a **Clear Cache and Hard Reload**, and then restart Mattermost.

![image](https://user-images.githubusercontent.com/14216632/41497329-bc04b9d4-7196-11e8-9788-a5802373161f.png)

**Possible fixes**

Implement proper support for replacing root CAs on-the-fly, and proxies in general.

**Comment by jasonblais** [comment]
@yuya-oc Are you familiar with this set up?

**Comment by yuya-oc** [comment]
Unfortunately no. Need to investigate and probably need to replace the dialog with Electron’s one.

For now, possibly installing the root CA into the system might make sense, although I’m not sure.

**Comment by amyblais** [comment]
Jira ticket: https://mattermost.atlassian.net/browse/MM-14171.

**Comment by amyblais** [comment]
@ssolidus Have you still experienced this issue recently?

**Comment by devinbinnie** [comment]
Closing as inactive
