### ISSUE TITLE
OS X: naming and menu consistency with platform

### ISSUE THREAD

**Issue by lloeki** [mattermost/desktop#83]
Platform conventions indicate the application name should be `Electron Mattermost.app`, together with the app menu being `Electron Mattermost`.

Also, the `Settings` entry is to be separated from `About <app-name>`, labeled `Preferences...`, and have a `CMD`+`,` shortcut.

electron-mattermost:
<img width="289" alt="screen shot 2016-03-17 at 10 25 19" src="https://cloud.githubusercontent.com/assets/75445/13841734/eb7cb066-ec2a-11e5-95c8-e13587b88056.png">
Chrome:
<img width="321" alt="screen shot 2016-03-17 at 10 25 35" src="https://cloud.githubusercontent.com/assets/75445/13841739/edbe12e8-ec2a-11e5-90d4-e9ba74676a97.png">

**Comment by lloeki** [comment]
Tied to #77, which solves the app name part.

**Comment by lloeki** [comment]
Found out that menus are lacking standard entries on OS X, so standard shortcuts like `CMD`+`W` are not working.

**Comment by it33** [comment]
Hi @lloeki, is there a straight forward way to add the shortcuts you mentioned?

**Comment by lloeki** [comment]
Yes, just create appropriately named entries, and OS X will do some magic.
There's an example in Matter front code. Link pending.

**Comment by lloeki** [comment]
Here it is, in [menu-template.js](https://github.com/lloeki/matterfront/blob/master/src/menu-template.js).  Just naming the things the right way makes OS X have the shortcuts, but they're included for Windows to behave. As for "Preferences...", it's lacking in the current code but naming it correctly shouldn't be a problem.

**Comment by yuya-oc** [comment]
Maybe I had overlooked the separator.

Then, the wording was difficult for me when I had implemented the menu. (Both of "Preferences" and "Settings" become "設定" in Japanese...). On Windows and Linux, which is better?

**Comment by lloeki** [comment]
Forgot to say that the `Edit` and `Window` entries are the one expected to be present on OS X.

**Comment by lloeki** [comment]
@yuya-oc haha localisation sure is hard in many subtle ways :-)

**Comment by leipert** [comment]
A few missing shortcuts on OS-X:
- `Command-M` Minimize Window
- (optional) `Alt-Command-Right` Next (unread?) Channel? (Like Next Tab in Chrome)
- (optional) `Alt-Command-Left` Prev (unread?) Channel? (Like Prev Tab in Chrome
- already mentioned `Command-,` for Preferences

Are there any of those that I could help with a simple PR?

**Comment by yuya-oc** [comment]
@leipert `Command+,` is added at v1.2.0. but the others are not yet. For PR, please see `CONTRIBUTING.md`.
