### ISSUE TITLE
Important | Trojan:Win32/Bluteal.B1rfn found in mattermost.exe

### ISSUE THREAD

**Issue by theriverman** [mattermost/desktop#830]
Hi,

System Center Endpoint Protection raised an alarm today reporting that there's a trojan in the installed `mattermost.exe` (see screenshot attached).

Is this a faulty alarm, that is, Mattermost/Electron is using some lib commonly used by trojans too or a serious threat?

![ms_trojan](https://user-images.githubusercontent.com/22156894/41531240-ff15d6b0-72f2-11e8-8182-830f26360410.png)

I'm not able to provide further information about the .exe itself, because it's in the quarantine and windows won't let accessing it.
The installer was `mattermost-setup-4.0.1-win64.exe`

Now trying with `mattermost-setup-4.1.2-win64.exe`

BR,
/riverman

**Comment by theriverman** [comment]
**Update**:
Multiple people have reported the same issue with version `*-4.0.1-win64.exe`
Looks like, version `mattermost-setup-4.1.2-win64.exe` solves the issue, but the true reason is still unknown.

**Comment by yuya-oc** [comment]
I got alerts for v4.0.1 from Windows Defender. We submitted correction to Microsoft, so the alerts should be no longer raised.

Definition version: 1.269.1577.0

If you're still seeing it, please let us know.

**Comment by Morgy93** [comment]
Hello,

I am on 4.1.2 and just got this warning

![image](https://user-images.githubusercontent.com/7961978/42451936-ef94ffee-8388-11e8-8473-fbeee1493d47.png)
(You may ask me for translation :b)
![image](https://user-images.githubusercontent.com/7961978/42452028-3d096c10-8389-11e8-9e13-095c745014ab.png)

I'll just reinstall mattermost and see if the warning continues.

**Comment by Morgy93** [comment]
Here I am again~

I actively checked `C:\Users\morgy\AppData\Local\mattermost\` after reinstall and no threat was found.
![image](https://user-images.githubusercontent.com/7961978/42452495-72de63b2-838a-11e8-95d9-2abf364620c6.png)
 ¯\\_(ツ)_/¯ 

Seems fixed then.
