### ISSUE TITLE
Communicator starts with a blank window from the Windows start up

### ISSUE THREAD

**Issue by DimitriLobov** [mattermost/desktop#835]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

https://mattermost.atlassian.net/browse/MM-14070

**Summary**
Communicator starts with a blank window from the Windows start up

**Environment**
- Operating System: Windows 7 Pro 64 bit
- Mattermost Desktop App version: 4.1.2
- Mattermost Server version: 4.10.0

**Steps to reproduce**
- Activate setting "start up on login",
- restart Windows,
- open communicator window from the tray icon.

**Expected behavior**
Application window opens from the system tray icon correctly with the side bar on the left and the chanel area on the right side.

**Observed behavior**
Empty window is opened. Only main menu bar is visible.

**Possible fixes**
Start up command line "%LOCALAPPDATA%\mattermost\update.exe" --processStart "Mattermost.exe" --process-start-args "--hidden", which is written to the Windows registry key "Run", seems not to work correctly. I have got the same result by starting this command line by the hand.

**Comment by amyblais** [comment]
Jira ticket to keep track: https://mattermost.atlassian.net/browse/MM-14070.

**Comment by esethna** [comment]
No longer repros
