### ISSUE TITLE
Dock Icon always shows the red notifications dot on Mac

### ISSUE THREAD

**Issue by ovidiub13** [mattermost/desktop#842]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
The Mattermost icon on the Mac desktop application alwas shows the Red Notification dot, as if there were unread messages, even if there arent any, even if the application is closed.

**Environment**
- Operating System: Mac OS 10.13.6
- Mattermost Desktop App version: 4.1.2
- Mattermost Server version: 5.1.0

**Steps to reproduce**
Install the Mattermost Mac application from https://releases.mattermost.com/desktop/4.1.2/mattermost-desktop-4.1.2-mac.zip
Log in and run the application

**Expected behavior**
The red dot to apear only if there are notifications.

**Observed behavior**
The red dot is always there.

<img width="60" alt="screen shot 2018-07-27 at 12 32 30" src="https://user-images.githubusercontent.com/3527534/43313822-d8863e5c-9199-11e8-9059-50aad79c6ad2.png">

**Comment by ovidiub13** [comment]
The red dot dissapeared as soon as I got a new notification and read it. So I'm guessing that reset it.

You may close this if you wish, but the fact that this has happened exposes that there is a bug somewhere.

**Comment by esethna** [comment]
Thanks for the report @ovidiub13. I am unable to repro this. It would be helpful if you are able to narrow down more specifc repro steps to get this to happen?

**Comment by ovidiub13** [comment]
More specific would be: I had some unread notifications and the channel with the messages open in the browser at the moment when I installed the Desktop app.

Might have been a freak communication even between my client and the server when I ran it.

**Comment by amyblais** [comment]
Hi @ovidiub13, have you seen this issue recently on the newest desktop version?

**Comment by ovidiub13** [comment]
Hello,

I don't use a Mac anymore so I can't confirm. The issue was hard to reproduce as it was, so I'm closing this issue.

Thank you for looking into it.

**Comment by aptash** [comment]
![image](https://user-images.githubusercontent.com/5793551/168551760-8363304b-9fc4-4894-aabf-0ab9fc71cf96.png)
I confirm this issue.
Mattermost  5.0.4 (5.0.4.17220)
