### ISSUE TITLE
Minimize to tray when clicking on the icon

### ISSUE THREAD

**Issue by ArchangeGabriel** [mattermost/desktop#845]
Currently, we have to close the windows in order to minimize to tray.

But a lot of similar apps, like Riot, allow minimizing to tray by clicking on the tray icon, which is much more convenient.

Please consider adding this.

**Comment by esethna** [comment]
Hi @ArchangeGabriel,

Would you mind adding some screenshots of what you are referring to, and reference in other apps like Riot. Not sure I completely understand your comment.

**Comment by ArchangeGabriel** [comment]
Well, I have icons like this in my tray:
![screenshot](https://user-images.githubusercontent.com/490531/43904600-974777cc-9bde-11e8-9a72-ce6bb2905167.png)
Clicking on the left one (riot.im) allows minimizing to tray and restoring from tray.
The Mattermost one only allows restoring from tray, not minimizing to it (clicking on the icon while the window is opened does nothing). To minimize Mattermost window to the tray, I have to close it using the window controls.

**Comment by amyblais** [comment]
Closing via feature request ticket: https://mattermost.uservoice.com/forums/306457-general/suggestions/36819994-desktop-app-minimize-to-tray-when-clicking-on-the.
