### ISSUE TITLE
macOS 10.14 Mojave dark titlebar

### ISSUE THREAD

**Issue by ylluminate** [mattermost/desktop#848]
Please implement a dark window title bar for Mojave as it really stands out currently:
![example](https://cl.ly/1A1r462S3g2J/Pasted_Image_8_17_18__8_19_PM.png)

**Comment by wvds** [comment]
@yuya-oc By adding the following line to `electron-builder.json`, it's automatically switching based on your Mac settings.

```json
"darkModeSupport": true,
```

**Comment by amyblais** [comment]
Closing via feature request: https://mattermost.uservoice.com/forums/306457-general/suggestions/36842986-desktop-mac-mojave-dark-titlebar.
