### ISSUE TITLE
Set default zoom in preferences

### ISSUE THREAD

**Issue by ylluminate** [mattermost/desktop#849]
I need to run Mattermost desktop client at about 4 control-+ levels of zoom.  Can you please implement a default level of zoom in preferences for text?  I doubt there's a way to isolate images vs text zoom, but at least being able to set a default overall zoom would help.  It might also be helpful to have an option to control "compactness" of content in that at this zoom level it would help to have text a bit more compact (ie, less vertical line height).

**Comment by amyblais** [comment]
Closing via a feature request ticket here: https://mattermost.uservoice.com/forums/306457-general/suggestions/36819139-set-default-zoom-in-preferences.
