### ISSUE TITLE
Switch Team via Shortcut

### ISSUE THREAD

**Issue by janhaertel** [mattermost/desktop#850]
I like to navigate applications mainly with my keyboard.
With mattermost I currently have the problem, that when I am **notified** about a **received message**, I open the mattermost chat window and hit **ctrl + k to switch** to the received message.
I am on **3 teams** and this works well when the message was sent in the currently viewing team. Unfortunately I **cannot read messages from others teams** without using my mouse to click on another team.

**Comment by yuya-oc** [comment]
Hi @janhaertel, did you try some shortcuts such as `Ctrl(Cmd) + Tab` or `Ctrl(Cmd) + {1~9}`? They can switch tabs.

**Comment by janhaertel** [comment]
Unfortunately I don't see anything happening, when pressing Ctrl + Tab (Windows) or Ctrl + (1-9)

**Comment by yuya-oc** [comment]
Please let me confirm. Do the 3 teams exist on the same server and do you have a single "tab" on the desktop app?
If it's true, the issue should be solved by webapp of mattermost-server.

@esethna I couldn't find this kind of shortcut on https://docs.mattermost.com/help/messaging/keyboard-shortcuts.html. Would you check?

**Comment by janhaertel** [comment]
They are all on the same server, I don't understand what you mean by "tab", my window looks like this: 
![screenshot577](https://user-images.githubusercontent.com/14938293/44340881-8b091000-a486-11e8-82b4-391ea2456b88.png)
![screenshot578](https://user-images.githubusercontent.com/14938293/44340884-8cd2d380-a486-11e8-9185-4b6ba9ef6770.png)

**Comment by lkraav** [comment]
Probably same as https://mattermost.uservoice.com/forums/306457-general?category_id=159795

**Comment by amyblais** [comment]
Closing via this feature request ticket: https://mattermost.uservoice.com/forums/306457-general/suggestions/34907044-cmd-ctrl-number-should-switch-teams.
