### ISSUE TITLE
Tray icon not working in Cinnamon (Linux Mint)

### ISSUE THREAD

**Issue by DissCent** [mattermost/desktop#851]
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
The tray icon option cannot be activated/selected when running Mattermost Desktop in the Cinnamon desktop environment.

**Environment**
- Operating System: Linux Mint 19.0 Cinnamon x64
- Mattermost Desktop App version: 4.1.2
- Mattermost Server version: 5.0.2

**Steps to reproduce**
 - Run the Cinnamon desktop environment
 - Open Mattermost Desktop
 - Go to File/Settings
 - The checkbox `Leave app running in notification area when application window is closed` isn't selectable (greyed out)
 - Closing the Mattermost client only minimizes it

**Expected behavior**
 - The checkbox isn't greyed out
 - A tray icon is shown
 - Closing the client window minimizes it to the tray icon

**Observed behavior**
There isn't much to say. I also tried editing the config.json file by hand and setting the option there. Afterwards, closing the client indeed doesn't minimize the window anymore - it just disappears, without showing a tray icon. The process is still running, but I can't restore the window (except for executing the binary again).

**Possible fixes**
I don't know for sure, but it seems like the setting is disabled if the tray icon isn't visible, so the problem probably won't be in the settings dialog but rather in the tray icon logic.

**Comment by yuya-oc** [comment]
To enable the option, "Show icon in the notification area" needs to be enabled then the app should be restarted.
In the step 4 of your steps to reproduce, the checkbox is grayed out. It's normal behavior due to the tray icon logic.

**Comment by DissCent** [comment]
What exactly do you mean by `It's normal behavior due to the tray icon logic`? I don't have a tray icon; it doesn't show and therefore, the checkbox is greyed out?

If that's true, then how can the tray icon be enabled/implemented on Cinnamon?

**Comment by yuya-oc** [comment]
Ah, I got it. Probably the real issue is that the tray icon is not shown even when `Show icon in the notification area` is enabled. Actually the app is assuming that the tray icon is shown, but it doesn't appear on the Cinnamon.

Would you try installing `libappindicator1`? It's needed to use the tray icon.

**Comment by DissCent** [comment]
Thank you for your answer. Unfortunately, this package is already installed:

```$apt search libappindicator | grep "^i"
i   libappindicator0.1-cil
i   libappindicator1
i   libappindicator3-1```

**Comment by yuya-oc** [comment]
It's curious. I could see the tray icon on clean installation of Linux Mint 19 Cinnamon. Would you check again?

![linux-mint-19-cinnamon-mattermost-4 1 2](https://user-images.githubusercontent.com/1412057/44402668-71062500-a58d-11e8-98e6-312c4166b722.PNG)

**Comment by DissCent** [comment]
Aah I figured it out - it seems like I didn't notice the "Show icon in the notification area" option. After setting it to true, everything works fine. So this is solved now - thank you and sorry!

**Comment by Darkless012** [comment]
Had exactly the same problem so for others seeking TLDR; solution:

1. Tick `Show icon in the notification area` checkbox
2. Restart APP (File -> Quit | Ctrl + Q) (Closing windows only minimizes app)
3. Tick `Leave app running in notification area when application window is closed` checkbox
4. Restart APP (File -> Quit | Ctrl + Q) (Closing windows only minimizes app)
5. Should work as expected
