### ISSUE TITLE
"Copy image" on images shown in channels

### ISSUE THREAD

**Issue by hniksic** [mattermost/desktop#858]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Provide a "copy image" option that copies an image shown in a channel.

**Steps to reproduce**
1. Start the mattermost desktop
2. Go to a channel with an image posted
3. Right-click on the image

Operating System: 64-bit Linux (Ubuntu 16.04)
Mattermost Desktop App version: 4.1.2
Mattermost Server version: 5.2.0

**Expected behavior**

It would be useful if "Copy image" were available in the right-click menu. In comparison, in the web app the "Copy image" is also available, as it is part of the standard Chrome menu for images.

**Observed behavior**

Only the "Save image" menu entry is present.

**Comment by amyblais** [comment]
Closing via a feature request ticket here: https://mattermost.uservoice.com/forums/306457-general/suggestions/36819001-desktop-app-copy-image-on-images-shown-in-chann.
