### ISSUE TITLE
Feature request: inline spell check as you type

### ISSUE THREAD

**Issue by kethinov** [mattermost/desktop#86]

**Comment by yuya-oc** [comment]
The text field is namaged by Mattermost server. Could you make a issue at the [forum](https://www.mattermost.org/feature-requests/)?

**Comment by yuya-oc** [comment]
Note: https://github.com/atom/electron/blob/master/docs/api/web-frame.md#webframesetspellcheckproviderlanguage-autocorrectword-provider

**Comment by kethinov** [comment]
The Mattermost server is relying on the fact that most browsers automatically do spell checking. Since electron's browser does not, the feature will have to be implemented on the electron app's side via JavaScript.

**Comment by kethinov** [comment]
Ah I should've read your second link before posting! haha

**Comment by jasonblais** [comment]
Thanks for the suggestion @kethinov ,

We're beginning to move feature requests from GitHub issues to our feature idea forum to keep all feature ideas in one place. Therefore, could we have your help contributing your suggestion in the [feature idea forum](https://mattermost.uservoice.com/forums/306457-general) so it can be discussed, upvoted and considered for a ticket?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review.

You get 10 votes in the feature idea forum, and each one influences the future of the project.

**Comment by jasonblais** [comment]
Thanks again @kethinov for the suggestion,

I have created a [Feature Idea forum post](https://mattermost.uservoice.com/forums/306457-general/suggestions/15272040-inline-spell-check-for-mattermost-client) where it can be discussed and upvoted.

Anyone interested in the community is encouraged to participate [in the discussion](https://mattermost.uservoice.com/forums/306457-general/suggestions/15272040-inline-spell-check-for-mattermost-client).
