### ISSUE TITLE
Custom title bar

### ISSUE THREAD

**Issue by muuvmuuv** [mattermost/desktop#862]
Slack enables this features when more then one workspace is logged in. It would be nice if Mattermost has this by default. This would make the app more unique between others. The default title bar does not fit into the design.

Here a screenshot:

![screenshot 2018-09-12 at 15 24 50](https://user-images.githubusercontent.com/11534760/45427987-8c51e500-b6a0-11e8-9378-47ba4b526e67.png)

**Comment by amyblais** [comment]
Closing via feature request ticket here: https://mattermost.uservoice.com/forums/306457-general/suggestions/36818959-desktop-custom-title-bar.
