### ISSUE TITLE
Mattermost opens both on fullscreen and on a smaller window when closing in fullscreen

### ISSUE THREAD

**Issue by carlosmcgregor** [mattermost/desktop#863]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

https://mattermost.atlassian.net/browse/MM-14176

**Summary**
When app is closed in fullscreen, opening it again leads to a fullscreen version _and_ a smaller window version. You cannot access the fullscreen version as it throws you again to the smaller window.

**Environment**
- Operating System: macOS High Sierra Version 10.13.6
- Mattermost Desktop App version: 4.1.2 (4.1.2.46)
- Mattermost Server version: 5.2.1

**Steps to reproduce**
1. Open Mattermost and make it fullscreen (green button on top left of window)
2. Press COMMAND + Q to quit Mattermost
3. Open Mattermost

**Expected behavior**

Mattermost opens either on fullscreen _or_ as a smaller window in a desktop.

**Observed behavior**

Mattermost opens both on fullscreen _and_ as a smaller window in a desktop, with the fullscreen being inaccessible.

<img width="365" alt="Desktop and Fullscreen Mattermost" src="https://user-images.githubusercontent.com/16442174/45503085-cfb95b80-b753-11e8-83c9-f246907b5e23.png">

**Possible fixes**

**Comment by yuya-oc** [comment]
Sadly it does not reproduce for me (macOS 10.13.6, desktop app v4.1.2).

- Does it always happen by following the steps to reproduce?
- Would you try removing `~/Library/Application Support/Mattermost/bounds-info.json`?

**Comment by carlosmcgregor** [comment]
* It always happens by following the steps to reproduce.
* I tried removing `~/Library/Application Support/Mattermost/bounds-info.json` and that forces Mattermost to open in windowed mode. However, the error persists when I attempt to recreate it. 

For reference, this is what I see in `bounds-info.json`:
```
{"x":0,"y":0,"width":1440,"height":900,"maximized":false,"fullscreen":true}
```

**Comment by carlosmcgregor** [comment]
Sorry~! Forgot to add one (apparently) crucial detail. This only happens when I am working with multiple screens and it happens on the main MacBook screen. I have tried to reproduce this error with other software, but I am hard pressed to find an app that will start fullscreen after being shutdown in fullscreen mode.

Not sure if this classifies as a Mattermost Client bug or a macOS bug. Please feel free to close this issue if you believe it is the latter.

**Comment by amyblais** [comment]
Ticket for tracking: https://mattermost.atlassian.net/browse/MM-14176.
