### ISSUE TITLE
Flatpak builds and Flathub distribution

### ISSUE THREAD

**Issue by SemaiCZE** [mattermost/desktop#870]
Flatpak is a way to provide applications to the users in standardized way accross distributions. From the three competitive systems (AppImage, Snap, Flatpak) the Flatpak now seems to be the most used solution in multiple desktop environments. From the user perspective it has an advantage in connection with distribution software tools (like GNOME Software).

In discussion below #864 @yuya-oc suggested this new issue to support my idea. As I said, Flatpak builds would bring easy updates to the users and in my oppinion they are more important than Ubuntu packages. Many known apps already have a flatpak version including Slack. Mattermost flatpak would help users to switch from Slack or Telegram easily.

Please, comment or like this issue to make the flatpak version happen. Thanks.

**Comment by SemaiCZE** [comment]
@yuya-oc I have a working version of Flatpak build from your prebuild sources in my repo https://github.com/SemaiCZE/mattermost-flatpak. Would you like to publish it on Flathub as one of the authors (see https://github.com/flathub/flathub/wiki/App-Submission)?

**Comment by SemaiCZE** [comment]
@yuya-oc ok, to speed things up I've already submitted the flatpak to the review process https://github.com/flathub/flathub/pull/702. But I still preffer you or @esethna to take controll over the new repo when the app is merged and published. Thanks.

**Comment by yuya-oc** [comment]
Thank you! Now I'm a collaborator of the repository, https://github.com/flathub/com.mattermost.Desktop.
