### ISSUE TITLE
Missing libgconf-2.so.4

### ISSUE THREAD

**Issue by 1605200517** [mattermost/desktop#872]
On Ubuntu 18.04 LTS, Mattermost desktop client wouldn't start with the message:

`error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory
`

However, this library is available for example under:

`/usr/lib/x86_64-linux-gnu/libgconf-2.so.4`

What to do? Where does the client expect this library file?

**Comment by yuya-oc** [comment]
After installing `libgconf-2-4`, I could successfully execute the app. And there is `/usr/lib/x86_64-linux-gnu/libgconf-2.so.4`. I think you are using 64-bit version of Ubuntu though, probably the system failed to load the library due to some reason. Would you check with `ldd mattermost-desktop`?

**Comment by 1605200517** [comment]
Hi, @yuya-oc !

```
 > ldd /usr/local/bin/mattermost-desktop  | grep "not found"
	libnode.so => not found
	libgconf-2.so.4 => not found
	libffmpeg.so => not found
	libasound.so.2 => not found
```

Then:

```
user@host:~$ ls -alh /usr/lib/x86_64-linux-gnu/libgconf-2.so.4
lrwxrwxrwx 1 root root 19 Jun  8  2017 /usr/lib/x86_64-linux-gnu/libgconf-2.so.4 -> libgconf-2.so.4.1.5
user@host:~$ sudo apt-get install libgconf-2-4
[sudo] Passwort für user: 
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
libgconf-2-4 ist schon die neueste Version (3.2.6-4ubuntu1).
libgconf-2-4 wurde als manuell installiert festgelegt.
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
```

**Comment by yuya-oc** [comment]
Hmm, it's obvious that some libraries are not found in your system, but I'm not sure the reason (ldconfig settings or LD_LIBRARY_PATH? but sadly I'm not familiar).

As a workaround, perhaps you can use .deb package instead because it's Ubuntu.

**Comment by amyblais** [comment]
Hi @1605200517, did the workaround proposed by Yuya help?

**Comment by amyblais** [comment]
Closing as there hasn't been activity on this for a while. Please re-open this Issue if the problem persists,

**Comment by CargoCoder** [comment]
This is exactly what happened to me when I tried to install 32 bit deb package on 64bit system
