### ISSUE TITLE
Group Policies Settings for Windows Mattermost Desktop

### ISSUE THREAD

**Issue by JtheBAB** [mattermost/desktop#873]
Hi

I was reading today the pull request #841 and it would make sense that the Mattermost Desktop Application can be configured by Sysadmins with the help of the Microsoft Group Policy (GPO).

I created a repository with a simple template that would set the Registry key to disable the AutoUpdate within [HKLM\Software\Policies\Mattermost]. It's not in sync with the value of #841 but that can be changed either within the admx or the Application.

Repository: https://github.com/JtheBAB/mattermost-gpo

Other possible settings that should be managed by GPO

- Add / modify server URL
- Prevent for adding another server URL
- Start app on login (not selectable when a policy exist)
- Show red badge on taskbar icon to indicate unread messages (not selectable when a policy exist)
- Flash app window and taskbar icon when a new message is recieved (not selectable when a policy exist)
- Use GPU hardware acceleration (not selectable when a policy exist)

I can help for the Policies, Registrykeys and testing. But i can't program.

Best regards

JtheBAB

**Comment by ThiefMaster** [comment]
out of curiosity, what's the benefit of having the last three things configurable via policy?

**Comment by JtheBAB** [comment]
The idea would be that every setting is configured by GPO. Perhaps on certian devices you want to prevent the optical indicators. 

The GPU Setting is perhaps interesting for RemoteDesktops with GPU. You may want to prevent that the App is using the GPU so that the GPU is free for other programs like Photoshop.

**Comment by ku-rt** [comment]
I would build the polices above into the admx for Mattermost even if they aren't implemented at this time. I think the most important part at this point is standardizing on what reg keys are going to be used for what and what are the expected values (0=not enabled, 1=enabled), etc.

Examples:
`HKLM\Software\Mattermost\Desktop\AutoUpdater`
`HKLM\Software\Mattermost\Desktop\ServerURL`
`HKLM\Software\Mattermost\Desktop\ServerName`
`HKLM\Software\Mattermost\Desktop\RestrictServers`
`HKLM\Software\Mattermost\Desktop\StartAppOnLogin`
`HKLM\Software\Mattermost\Desktop\GpuAcceleration`

**Comment by JtheBAB** [comment]
Sure. But i think it would be necessary to have @jasonblais as PM and @yuya-oc as Programmer on board. For specifing the keys and actually adding the logic into the desktop app. 

Slack dont provide GPO so i guess it would be a good argument for new E10/E20 customers to go with Mattermost. Especially if you could lock adding additional servers. 

I am also on prerelease with the same username.

**Comment by amyblais** [comment]
Opened an Improvement Jira ticket for tracking: https://mattermost.atlassian.net/browse/MM-14178.
