### ISSUE TITLE
make 24-hour clock the default (and provide a site-wide option)

### ISSUE THREAD

**Issue by sebalis** [mattermost/desktop#874]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
For new accounts, the default time format is the 12-hour clock. This creates ambiguity and is probably wrong for a majority of users.

**Environment**
- Mattermost Server version: 5.3.1

**Steps to reproduce**
Create a new account and log into it.

**Expected behavior**
The user’s time setting is the 24-hour clock, at least when the site language is not English.

**Observed behavior**
The 12-hour clock is set until the user changes it in their individual settings.

According to [Wikipedia](https://en.wikipedia.org/wiki/24-hour_clock), “a limited number of countries, particularly English-speaking, use the 12-hour clock, or a mixture of the 24- and 12-hour time systems.” And even “in countries where the 12-hour clock is still dominant, some professions prefer to use the 24-hour clock.” A 24-hour clock clearly reduces ambiguity and removes the need to add AM/PM indicators to times.

While trying out a test installation of Mattermost, I noticed I could set the server’s language to German, a language where a 24-hour clock is the only format in use and AM/PM indicators do not exist. There is no setting for either a region (to justify the 12-hour clock e.g. if the region were the US), the switch to German did not change the 12-hour default for new users, and no explicit change of the default time format was provided in the system console. Such a mechanism for changing the site default should be provided (either a regional setting together with knowledge which regions use the 12-hour format, or a site-wide setting for the time format). In any case, the 24-hour clock should be the default.

**Comment by yuya-oc** [comment]
@esethna I think this is an issue for a way to display time in webapp. Would you check?

**Comment by sebalis** [comment]
Yes, it is about the webapp. I am making my first steps with Mattermost now, as a desktop user (still my main platform) and also setting up my own test server, and in the process I forgot to remember that there are so many other interfaces. Sorry for not making that clear. :-)

**Comment by esethna** [comment]
Thanks @sebalis for your interest. What might make sense here is a setting in the System Console that sets the default for the server. I would be hesitant to update the end user default on it's own as that would be a major change for existing users. Would you be open to adding a system console setting for this with a default to 12h? I believe this change would be on the server and webapp repos.

**Comment by amyblais** [comment]
Hi @sebalis,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by sebalis** [comment]
I have very grudgingly added my input from here to https://mattermost.uservoice.com/forums/306457-general/suggestions/35193511-configurable-default-value-of-display-clock-12-h and voted for it. Grudgingly because I did not like the privacy statement very much. They create much more options for my personal information being sold than Github does.

**Comment by sebalis** [comment]
Nothing seems to be happening over on the forum. How can I move this forward?

**Comment by fleXible** [comment]
@amyblais Why was this closed?
I live in Germany, we use 24-hour clock display. So right now, every users has to manually change this in the web-UI.

**Comment by amyblais** [comment]
There is a feature request open for this here: https://mattermost.uservoice.com/forums/306457-general/suggestions/35193511-configurable-default-value-of-display-clock-12-h.

Would you be interested in implementing this feature?

**Comment by fleXible** [comment]
@amyblais I'm sorry, but I'm not that deep into software development. I'm much more into System Engineering and Operations.

**Comment by kpy3no** [comment]
> There is a feature request open for this here: https://mattermost.uservoice.com/forums/306457-general/suggestions/35193511-configurable-default-value-of-display-clock-12-h.
> 
> Would you be interested in implementing this feature?

cannot open the url

**Comment by fleXible** [comment]
@kpy3no I have no problems opening the URL.

**Comment by sebalis** [comment]
For the record, I had no problems opening that URL in February 2019 when I added a comment to it with details from this Github issue, and I have no problems opening it now :-)
