### ISSUE TITLE
Name is not rendered correctly in DM 

### ISSUE THREAD

**Issue by zetaab** [mattermost/desktop#878]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Name is not rendered correctly in DM when I have received new message

**Environment**
- Operating System: mac
- Mattermost Desktop App version: 4.1.2 (4.1.2.46)
- Mattermost Server version: 5.4.0

**Steps to reproduce**

1. ask someone send you private message using direct message
2.
 name before that
<img width="223" alt="screen shot 2018-10-24 at 12 37 50" src="https://user-images.githubusercontent.com/22482503/47421617-aa276500-d789-11e8-8a9e-b167c3eedb14.png">

3. name after there is new message
<img width="224" alt="screen shot 2018-10-24 at 12 38 29" src="https://user-images.githubusercontent.com/22482503/47421669-c4f9d980-d789-11e8-91d0-509670d1e856.png">
4. name after you click to open the users messages
<img width="242" alt="screen shot 2018-10-24 at 12 35 32" src="https://user-images.githubusercontent.com/22482503/47421579-92e87780-d789-11e8-819a-6264f784c5a7.png">

**Expected behavior**

Expected is that name should be rendered correctly. I have tested this in webbrowser as well, but the problem is only in mattermost-client. I have asked from other users as well and they can confirm that the problem exist only in client.

**Observed behavior**

<img width="242" alt="screen shot 2018-10-24 at 12 35 32" src="https://user-images.githubusercontent.com/22482503/47421579-92e87780-d789-11e8-819a-6264f784c5a7.png">

name looks like this

**Possible fixes**

**Comment by Taffer** [comment]
Comment from one of our team members:

> I think I just saw this happen. It seems to happen in direct messages. It's applying the "no unread messages" style on top of the "there are unread messages" style.

**Comment by rudovich** [comment]
We can confirm the same problem after server upgrade to v5.4  with the latest official macos app (4.1.2)

**Comment by amyblais** [comment]
Hi all, we have a ticket open here to address this bug: https://mattermost.atlassian.net/browse/MM-12493.

**Comment by rudovich** [comment]
Issue in client version 5.5 has been resolved for us. Thank you!

**Comment by wget** [comment]
*With the 5.5 server/webapp.

At this time, the desktop app is numbered 4.2.0 :)
