### ISSUE TITLE
If I'm receiving a file in Windows Client, not be able to enter text.(unstable)

### ISSUE THREAD

**Issue by Gloriashield** [mattermost/desktop#879]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
This problem can be easily reproduced by anyone. Occurs when downloading the uploaded file. Windows Client hangs or shows unstable behavior.

**Environment**
- Operating System: Windows 10 64bit redstone 4 (same Windows 10 32bit redstone 2)
- Mattermost Desktop App version: 4.1.2 (same 4.2.0-develop)
- Mattermost Server version: 5.4.0 team edition (no modified. standard version)

**Steps to reproduce**
1. Upload the PDF file to the server.
- The image file does not reproduce this problem.
- Same as S3 or HDD anywhere.
2. Launch the Windows Client.
3. Download the PDF file you uploaded in step 1. (It does not matter who gets it.)

**Expected behavior**
1. When the download is in progress, click mouse on the message input window.
2. The cursor does not flash.
3. Text input is unstable. (Slow or omitted)
4. 2-bytes characters can not be input. (Same in Korean and Japanese)
5. The download will be completed and the problem will be resolved after a certain period of time.

* This problem does not occur with WebApp. I think it's a problem with Electron.

**Observed behavior**

**Possible fixes**

**Comment by Gloriashield** [comment]
![check](https://user-images.githubusercontent.com/20394843/47423978-75370480-d7c1-11e8-9141-1a0078d30e64.gif)

This problem is difficult to implement with visuals, sorry.

**Comment by Gloriashield** [comment]
I found and fixed it.

**Comment by avasconcelos114** [comment]
This is reproducing for me as well, mind sharing how you fixed this issue?

**Comment by Gloriashield** [comment]
@avasconcelos114 
I solved and it was very simple. Separating the process can solve it. See Slack's download window. Open a new download window. However, user session data must be transmitted together. (If you simply open a new window, you will not be able to download it because you are not authorized)
