### ISSUE TITLE
Feature request: show tray icon and unread new message badge on Linux tray

### ISSUE THREAD

**Issue by smetj** [mattermost/desktop#88]
Should show a tray icon on the bar, and show the number of unread new messages on the tray icon when new messages arrived.

Similar request to #45 for for Linux/Gnome instead.

**Comment by yuya-oc** [comment]
Could you provide some example in Gnome?

**Comment by greenik** [comment]
@yuya-oc Any chance that this will be done?

**Comment by smetj** [comment]
@yuya-oc 
![blah](https://cloud.githubusercontent.com/assets/1007219/14811822/56fee4f6-0b9a-11e6-9935-4e2f1a172a13.png)

**Comment by edurenye** [comment]
It must also work in ubuntu unity, I guess should be a way to add it and make it work everywhere.

**Comment by rpglover64** [comment]
For the record, I'm using i3 with no desktop environment and with i3bar, and I don't see any tray icon.

**Comment by Great-Antique** [comment]
+1 for KDE
