### ISSUE TITLE
URL blocks input field

### ISSUE THREAD

**Issue by janhaertel** [mattermost/desktop#880]
Sometimes when I **focus** the **chat window**, a **URL** is displayed in the **bottom left** and it **won't disappear**. This is really annoying because I can't completely see the text I'm typing.

**Comment by amyblais** [comment]
Hi @janhaertel,

Can you help with more details on your Environment
- Operating System
- Mattermost Desktop App version: X.X.X - See Help > Version Number
- Mattermost Server version: X.X.X - See Mattermost Menu > About Mattermost, where Mattermost Menu can be accessed by clicking on three dots next to your profile picture

**Comment by janhaertel** [comment]
Windows 10
Mattermost Desktop Version 4.12
Mattermost-Version: 5.2.0

**Comment by janhaertel** [comment]
I'm still trying to find the exact cases when this happens and will append them here, fortunately this bug doesn't come up too often.

**Comment by janhaertel** [comment]
It seems to happen if the mouse hovers over a date next to the user name but not everytime :/

**Comment by STRML** [comment]
Dupe of #615, #610, #689

**Comment by amyblais** [comment]
Closing as a dup of https://github.com/mattermost/desktop/issues/909

A Jira ticket for this is here: https://mattermost.atlassian.net/browse/MM-13995,
