### ISSUE TITLE
Desktop app maximises to wrong monitor

### ISSUE THREAD

**Issue by th-joerger** [mattermost/desktop#885]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
If the Desktop app is minimised in Windows 7 from the secondary display and afterwards maximised again, it maximises to the wrong primary monitor.

**Steps to reproduce**
- Operating System: Windows 7 x64
- Mattermost Desktop App version: 4.2.1
- Mattermost Server version: 5.2.2
- Clear steps to reproduce the issue:
    * Maximise desktop app on your secondary monitor
    * Minimise desktop app with the windows buttons in the corner
    * Maximise/restore app from the Task bar

**Expected behavior**
App should maximise/restore on the display it was minimised on.

**Observed behavior**
App maximises/restores on the primary display

**Possible fixes**
- [Something seems to be wrong here](https://github.com/mattermost/desktop/blob/51f22c5c22f5dd5aab899920dd6b6f9175c09930/src/main.js#L265)

**Comment by wget** [comment]
@th-joerger Could you describe more in details what you mean by task bar? Are you speaking of the task bar or systray?

**Comment by wget** [comment]
@th-joerger Ok. Any way. [We will be migrating to electron 3](https://github.com/mattermost/desktop/pull/892), maybe this new version will solve your issue?

In the meantime, I have built a new build of mattermost desktop in order to test the msi installers. Maybe if you check with this new build, this could help us confirm the issue has been solved (the issue you are encountering is due to electron in all cases)?
https://github.com/wget/mattermost-desktop/releases/tag/27

**Comment by th-joerger** [comment]
@wget I installed your build ([msi, x64](https://github.com/wget/mattermost-desktop/releases/download/27/mattermost-desktop-x64.msi)) and it fixes the issue! Thank you very much :)

**Comment by wget** [comment]
@th-joerger Yes. Please note this msi is a simple test. Don't use it in production environment :) 4.3 will be released by the end of the month and we expect to have electron 3 and msi installers officially available at that time.

**Comment by th-joerger** [comment]
@wget Agreed, and thanks again!
