### ISSUE TITLE
Don't automatically (by default) post comments/replies to main chat

### ISSUE THREAD

**Issue by echosa** [mattermost/desktop#887]
People don't seem to use Mattermost's version of threading (compared to Slack) much, if at all, and it seems the main reason is because thread comments/replies are automatically posted to the main chat, which has two issues:

1) It clutters the main chat.
2) It causes people to respond in main chat rather than in the thread in the sidebar.

I'd like to see this changes to be more like Slack, where comments/replies aren't automatically posted to main chat, but are secluded into the thread and viewable in the sidebar. This would make them significantly more usable, useful, and used. Slack has an option to also post to main chat, and that's fine, just don't do it automatically by default, please.

**Comment by lkraav** [comment]
It's already targeted for work, albeit moving slowly https://mattermost.atlassian.net/browse/MM-8457

Fairly sure this is a duplicate issue.

**Comment by echosa** [comment]
Awesome! I didn't know about that ticket. Seems to be exactly what I'm looking for. Thanks! Closing this suggestion.
