### ISSUE TITLE
Different sound notifications for DMs/mentions and normal channel chatter

### ISSUE THREAD

**Issue by rosskusler** [mattermost/desktop#889]
Currently when someone sends you a direct message, mentions you, or sends a message to into non-muted channel that you are a member of, the desktop app plays the *same* sound.  I think it would be a really nice/useful feature to give users the option to play different sounds to distinguish between DM/mentions and normal channel chatter.

**Comment by amyblais** [comment]
Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by amyblais** [comment]
Opened one here: https://mattermost.uservoice.com/forums/306457-general/suggestions/36795829-different-sound-notifications-for-dms-mentions-and.
