### ISSUE TITLE
Support for custom user status

### ISSUE THREAD

**Issue by crevete** [mattermost/desktop#893]
It would be really nice to be able to set a custom user status (just like "Slack") with support of emoji. Now the we workaround by setting custom status (with emoji) in the "Nickname" filed, but it is not very user-friendly...

Beside, the emoji rendering on the Linux Desktop app is very cheap:
![status_with_emoji](https://user-images.githubusercontent.com/6795189/48694889-e5c51b80-ebdd-11e8-892d-09b49d4eb4c1.png)

Thanks.

**Comment by yuya-oc** [comment]
@esethna This would be a proposal for webapp. Would you check?

**Comment by crevete** [comment]
Thanks for checking this :+1: It would be very useful for everyone. And if you can add the support for emoji in status, it would be awesome!

**Comment by mismeniet** [comment]
I agree. This is one of the major reasons why we are still hesitating to move to mattermost. We completely rely on a users status for availability.

**Comment by amyblais** [comment]
Hi all,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by pomegranited** [comment]
Already requested as https://mattermost.uservoice.com/forums/306457-general/suggestions/17728987-status-labels :)

**Comment by amyblais** [comment]
Awesome, closing this via https://mattermost.uservoice.com/forums/306457-general/suggestions/17728987-status-labels.

**Comment by fdcds** [comment]
This feature is planned and can be tracked with this ticket: https://mattermost.atlassian.net/browse/MM-8463

**Comment by noonedeadpunk** [comment]
Yeah, task has been created 3 years ago, but no action on it...

**Comment by esethna** [comment]
@crevete @mismeniet @pomegranited @fdcds @noonedeadpunk Would you guys have feedback on this draft design? https://docs.google.com/presentation/d/1RpWQRcW2QYbQy8U8Q1lEWYzSWFMYNWp05egn77PKOsk/edit?usp=sharing

Approciate you sharing the feedback on your desire for this feature, currently we just need some design time to push it through. So any feedback you'd have on that would be helpful :)

**Comment by noonedeadpunk** [comment]
@esethna Actually that's exactly how I would be expecting it to work. But a bit extending `community feedback` proposal, by having option in system console, or even just via cli, to define default set of statuses, despite what's chosen for `Enable users to set custom statuses`.

**Comment by Kalaschnik** [comment]
It seems the issue was closed: https://mattermost.atlassian.net/browse/MM-8463
But was this ever rolled out?

**Comment by noonedeadpunk** [comment]
> It seems the issue was closed: https://mattermost.atlassian.net/browse/MM-8463
> But was this ever rolled out?

Epic has been created instead of this issue https://mattermost.atlassian.net/browse/MM-23120
So it seems not yet implemented

**Comment by esethna** [comment]
@Kalaschnik we had duplicate epics, please follow this one: https://mattermost.atlassian.net/browse/MM-23120

**Comment by dpanic** [comment]
+1
