### ISSUE TITLE
MacOs Desktop app repeatedly asks to accept a certificate.

### ISSUE THREAD

**Issue by albamath** [mattermost/desktop#894]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

MacOs Desktop app repeatedly asks to accept a certificate.

**Environment**
- Operating System: MacOs Mojave (up-to-date)
- Mattermost Desktop App version: 4.1.2 
- Mattermost Server version: 5.3.1 

**Steps to reproduce**

Besides using Mattermost at MacOs, I am not sure how to reproduce this bug. I have colleagues who use the Mattermost app on MacOs and never observed this behavior. The only difference I observed in the way we use our computers is that I am maybe the one who switches networks the most often.

From time to time, it just happens that when I re-open the Mattermost App, it is asking me to accept a certificate (more details below).

**Expected behavior**

I would like to remain connected on the app, without it asking for certificate acceptance almost every day. At least I would like the app to prevent me in some way that I have been disconnected due to this certificate issue, because I could be missing important messages without noticing. 

**Observed behavior**

On a regular basis (but not every time) when I re-open my MacOs app's window, I have the following message that appears on a pop-up window:

```
Do you trust certificate from "TERENA SSL CA 3"?
Certificate is different from previous one.
URL: https://api.segment.io/v1/t
Error: net::ERR_CERT_COMMON_NAME_INVALID
```

When I accept the certificate, the UI disappears and the only thing that appears on the Mattermost Desktop App window is:

```
{
  "success": true
}
```

After that, if I close and re-open the window, the message  `"success": true` is still there. If I quit and re-open the app, then I am again connected as usual.

**Comment by wget** [comment]
@albamath Are you sure your network doesn't have DPI (Deep Packet Inspection) measures on that particular network which could explain why the certificate changes? Or maybe do you have an antivirus on your computer/network (even on macOS) which analyzes the traffic for HTTPS based connections (therefore explaining why the certificate changes).

**Comment by amyblais** [comment]
We haven't received an update so we'll assume that the problem is fixed or is no longer valid. 

If you still experience the same problem, try upgrading to the [latest version](https://about.mattermost.com/download/). 

If the issue persists, reopen this issue with the relevant information and we'd be glad to help you where we can.
