### ISSUE TITLE
Inline Code highlighting

### ISSUE THREAD

**Issue by jethroguce** [mattermost/desktop#897]
Can there be a way to also change the inline code colors, for both background and text color. So we can configure the client to be more appealing and it can be seen easily.

currently it looks like this

<img width="404" alt="screen shot 2018-11-26 at 11 56 52 am" src="https://user-images.githubusercontent.com/4945428/48992406-7b2e5580-f172-11e8-90e0-8485ff37b164.png">

and this is how it looks like in slack

<img width="346" alt="screen shot 2018-11-26 at 11 57 21 am" src="https://user-images.githubusercontent.com/4945428/48992418-83869080-f172-11e8-9902-e43d65fcd6cb.png">

**Comment by yuya-oc** [comment]
@esethna This would be a proposal for webapp. Would you check?

**Comment by amyblais** [comment]
Hi @jethroguce,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by amyblais** [comment]
Opened one here: https://mattermost.uservoice.com/forums/306457-general/suggestions/36767524-inline-code-highlighting.
