### ISSUE TITLE
Upgrade dependencies for v4.3

### ISSUE THREAD

**Issue by yuya-oc** [mattermost/desktop#898]
#### Electron
- [x] Electron and Spectron (#892)
- [x] electron-builder (#906)

#### Build tools
- [x] Babel (#903)
- [x] Webpack (#903)

#### Test tools
- [x] ESLint (#906)
- [x] Other test tools (#906)

#### Others
- [x] Other devDependencies (#906)

#### React
- [x] React (#906)
- [x] React-Bootstrap (#906)

#### Others
- [x] Other dependencies (#906)

### build system
- [x] Remove yarn ([like discussed on the chat one month ago](https://community.mattermost.com/core/pl/ufs3971omjbg5n8sqgxjqzqqwo))

**Comment by wget** [comment]
I added a link to the conversation we had about removing the deprecated yarn build tool. ^

**Comment by yuya-oc** [comment]
All dependencies were upgraded.
