### ISSUE TITLE
Illegible menu in Ubuntu/Gnome Shell on focused window since v4.2

### ISSUE THREAD

**Issue by bentolor** [mattermost/desktop#899]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. 
- [x] This doesn't reproduce on web browsers (such as in Chrome). 

---

**Summary**
Since upgrading from Mattermost 4.1.x to 4.2.0 the applications menu has become illegible if the window is focused. It shows as light gray on dark gray if the window has no focus.

**Environment**
- Operating System: Ubuntu 18.10
- Mattermost Desktop App version: 4.2.0
- Mattermost Server version: 5.3.1

Shell: Gnome shell with default activated theme (called "Yaru")

**Steps to reproduce**
* Open the application in the described environment

**Expected behavior**
The menu should be legible all the time

**Observed behavior**

Invisible Menu when Mattermost Desktop app is focused:
![zwischenablage01](https://user-images.githubusercontent.com/588260/49144302-59150e80-f2fd-11e8-914e-eac1bcf0d63b.png)

Menu then window is NOT focused:
![grafik](https://user-images.githubusercontent.com/588260/49144193-09364780-f2fd-11e8-9a45-cd8ea181c108.png)

**Comment by yuya-oc** [comment]
Thanks for feedback. It's an upstream bug from Electron.

https://github.com/electron/electron/issues/15194

**Comment by amyblais** [comment]
Opened a ticket for this here: https://mattermost.atlassian.net/browse/MM-13994.

**Comment by devinbinnie** [comment]
Closing as inactive/cannot reproduce
