### ISSUE TITLE
4.2 build error - webpack-cli\bin\config-yargs.js

### ISSUE THREAD

**Issue by 6a7070** [mattermost/desktop#902]
I confirm (by marking "x" in the [ ] below: [x]):

- [X ] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
When compiling the MM desktop app from source, the build process errors out. The error appears related to config-yargs.js file for webpack-cli.

**Steps to reproduce**
- Operating System: Windows 10
- Mattermost Desktop App version: 4.2.0
- Mattermost Server version: N/A
- Clear steps to reproduce the issue:
```
cd C:\temp\desktop-4.2.0\src
yarn
cd ..
npm run build
<errors out - npm run build does not complete. error output below>
```

**Expected behavior**
npm run build will successfully build program.

**Observed behavior**
```
C:\temp\desktop-4.2.0>npm run build

> mattermost-desktop@4.2.0 build C:\temp\desktop-4.2.0
> npm-run-all build:*


> mattermost-desktop@4.2.0 build:main C:\temp\desktop-4.2.0
> webpack-cli --bail --config webpack.config.main.js

C:\temp\desktop-4.2.0\node_modules\webpack-cli\bin\config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (C:\temp\desktop-4.2.0\node_modules\webpack-cli\bin\config-yargs.js:89:48)
    at C:\temp\desktop-4.2.0\node_modules\webpack-cli\bin\webpack.js:60:27
    at Object.<anonymous> (C:\temp\desktop-4.2.0\node_modules\webpack-cli\bin\webpack.js:515:3)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mattermost-desktop@4.2.0 build:main: `webpack-cli --bail --config webpack.config.main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mattermost-desktop@4.2.0 build:main script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Possible fixes**
Appears to be the same issue referenced in the webpack-cli project: https://github.com/webpack/webpack-cli/issues/607
Unsure of how to fix, except perhaps to upgrade webpack-cli. Unsure if this is an issue with MM build package or not.

**Comment by yuya-oc** [comment]
v4.2 was already released, so we'll not fix unless we prepare a new patch release.

Now the master branch should solve some build errors. If you still have any issues to build the app, please let us know.

**Comment by wget** [comment]
@6a7070 If you really want build this particular tag, just upgrade the dependencies like I did for ArchLinux and respect the versions, the build process then should continue without issue.

I agree with @yuya-oc, the problem is already fixed on master. Either download the binaries for 4.2 or build from master. WON'T FIX.
