### ISSUE TITLE
Windows: Default app shortcut AltGr + M

### ISSUE THREAD

**Issue by marcelklehr** [mattermost/desktop#907]
Hey,
I've had a report of a windows user who said everytime she types a 'µ' on her German keyboard (AltGr+M) instead of a 'µ' appearing in the text, the mattermost app opens. Apparently, she was able to mitigate this by setting a shortcut for the Desktop link to Mattermost, but after a restart it's back as it was.
Any ideas?

**Comment by yuya-oc** [comment]
Well, I'd like to reproduce that for investigation, but I don't have any German keyboards. Can the right-hand Alt key of US keyboard be an equivalent for AltGr?

And would you tell us about her situation?
- Environment
  - Operating System:
  - Mattermost Desktop App version: X.X.X (See [Help] > [Version Number])
- Steps to reproduce
  - Did she type 'μ' on another app? Then did the mattermost desktop open?
  - In that time, was the mattermost desktop already running in background?

**Comment by marcelklehr** [comment]
* Environment
  * Windows 10
  * Mattermost 4.2.0
* Reproduction steps
  * Type 'μ' in any other app?, then the mattermost desktop app opens
  * This happens regardless of whether or not the app is already running in the background

**Comment by marcelklehr** [comment]
I'm not sure how to emulate Alt Gr on non German keyboards :S I have a German keyboard, but I'm not running Windows...

**Comment by JtheBAB** [comment]
Hi

The only way how i could trigger it was when i specified the shortcut field.

![shortcut](https://user-images.githubusercontent.com/42135332/49795910-84571f00-fd3b-11e8-826d-4c21dd858161.jpg)

Is that PC controlled by IT? Cloud it be that they push with Group Policy's or something else this Shortcut configured like that?

Best regards

**Comment by marcelklehr** [comment]
@JtheBAB Is that PC controlled by IT? It's a private computer, afaik, and the shortcut field in that dialog appears to be empty before she resets it to something else.

**Comment by wget** [comment]
Wasn't able to reproduce either.

**Comment by marcelklehr** [comment]
Alright, I was half-expecting this. Thanks for your help anyway, folks!
