### ISSUE TITLE
Cannot read property 'display_name' of undefined

### ISSUE THREAD

**Issue by PovilasKud** [mattermost/desktop#908]
Everything worked fine, but suddenly I get a blank white screen when I open Mattermost desktop app. 
I can see this error in devtools console:

`Loading zoom plugin index_bundle.js:28189`
`Loading bigbluebutton plugin index_bundle.js:28189`
`Loaded zoom plugin index_bundle.js:28189`
`websocket connecting to wss://mattermost.meridia.land/api/v4/websocket index_bundle.js:28195`  `TypeError: Cannot read property 'display_name' of undefined`
`webview.addEventListener.e @ index_bundle.js:28195 index_bundle.js:28195`
`Uncaught TypeError: Cannot read property 'display_name' of undefined`

Screenshot: https://prnt.sc/ltg2bb

For other users in our company, everything works fine.

I can't recall anything that changed on my system, except that I have cloned this repo https://github.com/electron-react-boilerplate/electron-react-boilerplate and installed dependencies + installed Yarn. 

**OS**: MacOS Mojave
**Mattermost v**: 4.2.0
**Npm v**: 6.5.0

Any ideas ?

**Comment by yuya-oc** [comment]
As far as looking the error, it seems that webapp failed to load data by some reason. So I feel it should happen also on web browsers though, would you check? And are other users also using the desktop app on macOS?

**Comment by PovilasKud** [comment]
> As far as looking the error, it seems that webapp failed to load data by some reason. So I feel it should happen also on web browsers though, would you check? And are other users also using the desktop app on macOS?

The browser version works fine. I have tested both on Firefox and Chrome.
Other users use desktop apps both Windows and MacOS and they have no such problem.

Any other logs I can provide?

**Comment by ReDucTor** [comment]
I'm having the same issue on Windows v4.2.0

**Comment by PovilasKud** [comment]
> I'm having the same issue on Windows v4.2.0

Is that a fresh install ?
Do you recall any changes you did that caused this issue?

**Comment by ReDucTor** [comment]
It's a fresh install, also a reoccurring issue and multiple people at my work have had similar issues.

I've worked out a workaround deleting `%appdata%\Mattermost\Local Storage`

**Comment by PovilasKud** [comment]
> It's a fresh install, also a reoccurring issue and multiple people at my work have had similar issues.
> 
> I've worked out a workaround deleting `%appdata%\Mattermost\Local Storage`
> 
> I haven't found any specific steps to reproduce

Thanks, that solved the problem on on mac too! 

MacOS:
`sudo rm -rf ~/Library/Application Support/Mattermost`

**CAUTION:** This will delete all saved servers. Pretty much same as having fresh install.

**Comment by amyblais** [comment]
Closing this as there is a workaround,

**Comment by PovilasKud** [comment]
Was able to reproduce this issue. 

The steps are - clicking on your own username in left sidebar.

Same happens both on Mac and Windows machines.

**Comment by bakasmarius** [comment]
It also happened to me when I clicked on my own username on the left sidebar under `DIRECT MESSAGES`. Then for a half a second I was able to see my whole workspace when I went through all the possible menu items, but the gray screen came straight back.

**Comment by bakasmarius** [comment]
I can now also confirm that this bug can be reproduced by trying to add yourself to `DIRECT MESSAGES` list.

**Comment by bakasmarius** [comment]
It also happened when I left one of the channels, but this time reloading a window helped, so I guess it's a different, but related issue.

**Comment by amyblais** [comment]
Hi all, what Mattermost server version are you on?

**Comment by levigo-systems** [comment]
We get the same error when we open email notifications.
No errors in the server logs. Only the browser DevConsole shows the 
> Cannot read property 'display_name' of undefined

Server version 5.17.0.

**Comment by devinbinnie** [comment]
Closing as inactive.
