### ISSUE TITLE
Make notification about new message persistent

### ISSUE THREAD

**Issue by Confucij** [mattermost/desktop#91]
Notification about new message stays active only for few seconds and then disappears. Thus it's hard to keep track of new messages. 
Is it possible to make them persistent (not dissappears until clicked or any other activity)?

**Comment by yuya-oc** [comment]
On OS X, I think that Notification Center on System Preferences can make it persistent. Unfortunately, I don't know about other OS in this point.

**Comment by Confucij** [comment]
@yuya-oc  AFAIK mattermost-desktop is using libnotify. So only examples i can provide is [https://wiki.archlinux.org/index.php/Desktop_notifications](url). When i use examples for python and JavaScript all notification was persistent,

**Comment by yuya-oc** [comment]
In mattermost-desktop, [`Notification()`](https://developer.mozilla.org/en-US/docs/Web/API/notification) is just called on the browser side. It strongly depends on the internal of Electron. Or, I have to prepare another module for this.

**Comment by Confucij** [comment]
@yuya-oc I see. As far as i can gues it should be "sticky" property in "notification.js" whitch is marked as unsupported. However, i found some js modules whitch  was able to show me sticky notes: https://sciactive.github.io/pnotify/ https://github.com/mikaelbr/node-notifier And the last one has mentioned Electron in readme so it should be possible, in general, to make them persistant.

Nevertheless thank you for your attention to this issue.

**Comment by slankes** [comment]
I've just tested this on mac os. The system preferences do have a way to change the Alert Style but even when changing it to "Alerts" (from the defaults of banners) it only stays for a few seconds.

**Comment by kostecky** [comment]
This would be fantastic to solve! I noticed the same thing as @slankes.

**Comment by jasonblais** [comment]
Thanks for the suggestion @Confucij,

We're beginning to move feature requests from GitHub issues to our feature idea forum to keep all feature ideas in one place. Therefore, could we have your help contributing your suggestion in the [feature idea forum](https://mattermost.uservoice.com/forums/306457-general) so it can be discussed, upvoted and considered for a ticket?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review.

You get 10 votes in the feature idea forum, and each one influences the future of the project.

**Comment by Confucij** [comment]
@jasonblais Done!

**Comment by jasonblais** [comment]
Perfect, thanks @Confucij!
