### ISSUE TITLE
Direct messaging yourself fails 

### ISSUE THREAD

**Issue by str255** [mattermost/desktop#912]
I confirm (by marking "x" in the [ ] below: [x]):

- [x ] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x ] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System:
- Mattermost  Desktop App version 4.2.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10)
--- Also reproduced on Version 4.1.2 on Windows 10
- Mattermost Server Version: 5.6.1
--- Database Schema Version: 5.6.0
--- Database: mysql

**Steps to reproduce**
Open up direct channel with myself

**Expected behavior**
Direct channel with myself

**Observed behavior**
White screen of death

**Possible fixes**

**Comment by jasonblais** [comment]
Thanks @str255 - our team has tried to reproduce it but haven't been successful so far.

We have the ticket queued for an upcoming triage next week - likely Wednesday after people come back from holidays. Our engineers will be able to offer some insight, or at minimum offer suggestions on further troubleshooting.

Would you be open to closing this in favor of the original issue you opened here? 
 https://github.com/mattermost/mattermost-server/issues/10008

**Comment by yuya-oc** [comment]
Closed in favor of https://github.com/mattermost/mattermost-server/issues/10008#issuecomment-455688059
