### ISSUE TITLE
Multi-Account Sign In

### ISSUE THREAD

**Issue by florianeichin** [mattermost/desktop#914]
Right now, the Desktop Client only allows to sign in to multiple servers, but not to sign in to one server with two accounts. This feature would be very helpful.

**Comment by lkraav** [comment]
What's the specific use case?

**Comment by florianeichin** [comment]
At the universities intranet, I have two identities. One as a student and one as a student assistant.

**Comment by wget** [comment]
@florianeichin Then you have to ask to have your account added to two roles. This requires the Pro version AFAIK.
@jasonblais  or @amyblais can confirm on this.

**Comment by jasonblais** [comment]
@wget Not sure which Pro version you're referring to?

@florianeichin that's an interesting use case. Appreciate your feedback.  

Would you be open to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](http://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub Issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by wget** [comment]
@jasonblais I was speaking of the Enterprise Edition be it E10 or E20. This is what I call the "pro" version of Mattermost :)

Aside from that, (although I'm not expert with the Enterprise Edition), I think the current use case can be already addressed with the Enterprise edition.

**Comment by jasonblais** [comment]
Got it, thanks @wget 👍 

> Aside from that, (although I'm not expert with the Enterprise Edition), I think the current use case can be already addressed with the Enterprise edition.

There currently isn't a way to sign in with different accounts (student vs student assistant) to the same Mattermost server on the desktop app. It assumes one login credential per server. Hence, you would need to sign out from one, to then sign in to the other.

That said, definitely worth a [feature proposal in our forum](https://mattermost.uservoice.com/forums/306457-general/), if you or @florianeichin are open to it. You get **10 votes** in the feature idea forum! :)

**Comment by wget** [comment]
@jasonblais I know there is no way to connect using different accounts at the same time, I was just saying to use only ONE account and ask to the sysadmin to put that account under different groups/roles. --> This solves the issue if I'm not wrong.

**Comment by jasonblais** [comment]
That's a good question. I believe this would be supported with custom, supplementary roles coming in a future release https://docs.mattermost.com/deployment/advanced-permissions.html#supplementary-roles-e20

**Comment by amyblais** [comment]
Closing this as this is a good candidate for a feature request,

**Comment by alexdevos** [comment]
Hello @amyblais, I'm very interested in this feature request suggestion of @florianeichin to be able to sign in to one server with two accounts in Desktop Client : do you know if a feature request on Uservoice has been opened (I didn't find any with the search) ?

**Comment by Wnme** [comment]
> Hello @amyblais, I'm very interested in this feature request suggestion of @florianeichin to be able to sign in to one server with two accounts in Desktop Client : do you know if a feature request on Uservoice has been opened (I didn't find any with the search) ?

See my feature request. Open for vote: https://mattermost.uservoice.com/forums/306457-general/suggestions/46077385-multi-account-sign-in
