### ISSUE TITLE
Users appear logged in when they're away or offline

### ISSUE THREAD

**Issue by Albyorix** [mattermost/desktop#916]
I confirm (by marking "x" in the [ ] below: [x]):

- [x ] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [ x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

https://mattermost.atlassian.net/browse/MM-14182

**Summary**

People appear to still be logger in even if they're computer is shut down of sleeping.

**Environment**
- Operating System: Windows 10 Pro
- Mattermost Desktop App version: 5.6.0 
- Mattermost Server version: 5.6.0 

Mattermost Enterprise Edition
Mattermost Version: 5.6.0
Database Schema Version: 5.6.0
Database: postgres
Build Hash: 0c1207215852a8726c3f09dea157d597fec368df
EE Build Hash: 2c2d33b22b4c2938938eade4b9914748c1be9d3b
Webapp Build Hash: 71d31890dcfaebbce350b5a93cccb44094d74a5d

**Steps to reproduce**
2 people log in to mattermost server & download mattermost app.
The 1st leaves the app open but locks his computer.
Both wait a few hours

**Expected behavior**
The 2nd person should see the 1st person as being offline or away.

**Observed behavior**
The 2nd person sees the 1st person as being online

**Possible fixes**

**Comment by Albyorix** [comment]
Additional note:
It doesn't matter if the 2nd person (the one logging in to see if the 1st one appears online) is on the web app or desktop app.
The issue seems to be on the 1st person's desktop app

**Comment by amyblais** [comment]
Hi @Albyorix, would you be open to taking a look at this section in our troubleshooting docs: https://docs.mattermost.com/install/troubleshooting.html#user-statues-get-stuck-on-away-or-offline-status?

**Comment by amyblais** [comment]
Jira ticket for tracking: https://mattermost.atlassian.net/browse/MM-14182

**Comment by amyblais** [comment]
Hi @Albyorix, what desktop app version are you on? Also, would you be open to upgrading your server version to see if you can still reproduce this on a more recent version?

**Comment by amyblais** [comment]
I'll close this for now as we haven't received feedback for a while. Please re-open this if the issue persists on the latest desktop version v4.4.0.
