### ISSUE TITLE
Short-key to close channel

### ISSUE THREAD

**Issue by swood** [mattermost/desktop#917]
Sometimes, if I want to close a channel, I'd like to make it by keyboard without mouse or trackpad.
Does it possible to provide this function?

**Comment by amyblais** [comment]
Hi @swood, are you referring to Direct Message and Group Message channels?

**Comment by swood** [comment]
Hey, @amyblais. Yes, I meant a Direct channels. Does it possible?

**Comment by amyblais** [comment]
It's not possible yet, but there is a feature request open here: https://mattermost.uservoice.com/forums/306457-general/suggestions/34656184-add-shortcut-to-close-current-channel-direct-chat.

Please feel free to open a pull request to implement this improvement if you are interested!
