### ISSUE TITLE
Presence isn't accurate

### ISSUE THREAD

**Issue by ntwrkguru** [mattermost/desktop#921]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

https://mattermost.atlassian.net/browse/MM-14183

**Summary**

**Environment**
- Operating System: macOS 10.14.2
- Mattermost Desktop App version: 4.2.0.61 
- Mattermost Server version: 5.4.0 

**Steps to reproduce**
Just use the desktop app in conjunction with the web app. 

**Expected behavior**
Presence status in the desktop client should match the web client.

**Observed behavior**
The presence indicator sometimes differs. Specifically, I can compare my DM list in the desktop app and the web app and see that people who show offline or away in the web app show as present in the desktop app. I realize that it's not a real-time sync, but this has been confirmed over spans of hours.

**Possible fixes**

**Comment by wget** [comment]
I can confirm.

**Comment by amyblais** [comment]
Hi @ntwrkguru, would you be open to taking a look at this section in our troubleshooting docs: https://docs.mattermost.com/install/troubleshooting.html#user-statues-get-stuck-on-away-or-offline-status?

**Comment by ntwrkguru** [comment]
I'm not opposed, but it's in an Open Telekom Cloud, not Amazon, so there is no ELB, but I'm not sure what they use for ingress.

**Comment by amyblais** [comment]
Jira ticket for tracking: https://mattermost.atlassian.net/browse/MM-14183

**Comment by amyblais** [comment]
Updated ticket for tracking: https://mattermost.atlassian.net/browse/MM-6404.

**Comment by amyblais** [comment]
Are you still experiencing this issue on desktop v4.4.0?

**Comment by ntwrkguru** [comment]
Can't say. I don't use MM any longer. Sorry.
