### ISSUE TITLE
AppData EXE

### ISSUE THREAD

**Issue by andyacep** [mattermost/desktop#923]
Please could we configure the windows client to be installed to the "program files" directory in windows.
The current location for the exe file is the %APPData% folder, this should be for Application Data not Application Executables.  

This has caused numerous problems including
When we create group policies for executable prevention for exe files in the %APPData% directory to reduce the possibility of malware running from there, this also prevents Mattermost, from running.
By manually moving the folder to "program files" it corrects this issue.

**Comment by JtheBAB** [comment]
4.3 will provide a MSI installer that install it within %programfiles%

**Comment by wget** [comment]
+1 @JtheBAB . Closing.
