### ISSUE TITLE
all files in tar-ball are world-writable

### ISSUE THREAD

**Issue by kjetilho** [mattermost/desktop#932]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
The distributed tar-ball has unsafe permissions.

**Environment**
- Operating System: Linux
- Mattermost Desktop App version: 4.2.0 
- Mattermost Server version: N/A 

**Steps to reproduce**

$ tar ztvf /tmp/mattermost-desktop-4.2.0-linux-x64.tar.gz | grep -c rwxrwxrwx

**Expected behavior**
I expect 0 files and directories to be world-writable.

**Observed behavior**
_all_ 78 files and directories are vulnerable for tampering by anyone.

**Possible fixes**

I could not find the code which does the packaging with a cursory search.  a strategic "umask 022" might be enough, but since even non-executable files get 777, it smells like a very bad chmod command in the build routine.

**Comment by amyblais** [comment]
Opened a Jira ticket for tracking: https://mattermost.atlassian.net/browse/MM-14347.

**Comment by devinbinnie** [comment]
Closing as inactive.

**Comment by kjetilho** [comment]
Uhm, this does not inspire confidence.  Checking if this bug is still present is easy to do.

```
tar ztvf mattermost-desktop-5.0.2-linux-x64.tar.gz 
drwxrwxrwx 0/0               0 2021-11-15 15:26 mattermost-desktop-5.0.2-linux-x64/
-rwxrwxrwx 0/0            1096 2021-11-15 15:26 mattermost-desktop-5.0.2-linux-x64/LICENSE.electron.txt
-rwxrwxrwx 0/0           11459 2021-11-15 15:25 mattermost-desktop-5.0.2-linux-x64/LICENSE.txt
-rwxrwxrwx 0/0         5438661 2021-11-15 15:26 mattermost-desktop-5.0.2-linux-x64/LICENSES.chromium.html
-rwxrwxrwx 0/0           36159 2021-11-15 15:25 mattermost-desktop-5.0.2-linux-x64/NOTICE.txt
[...]
```

**Comment by devinbinnie** [comment]
@kjetilho Would you be willing to look into a fix for this? Unfortunately for us this is not a huge priority right now, apologies.

**Comment by kjetilho** [comment]
I can take a look.  I managed to get a working npm setup and do a build, and the tarball made on my own workstation has the same problem, so that's a promising start - sort of :)
