### ISSUE TITLE
Show number of flagged message on the top right corner flag icon (which shows the flagged messages panel)

### ISSUE THREAD

**Issue by zsalab** [mattermost/desktop#933]
No indication of flagged messages unless click the top right corner flag icon and see the flagged messages on the appearing panel.
I would be a nice improvement to have a number on/inside of the flag to see how many (or least one) message is flagged.

Would be useful, because no possible to mark a message unread but sometime just no time to answer, so flag is a good feature for that... but if you busy maybe you even forget you flagged a message because you have to answer but was not time for it.

**Comment by amyblais** [comment]
Thanks, appreciate your feedback @zsalab,

Would you like to [contribute this in the feature idea forum](https://mattermost.uservoice.com/forums/306457-general/) so it can be discussed, upvoted and considered for a [help wanted ticket](https://docs.mattermost.com/process/help-wanted.html)?

Please include a link back to this GitHub issue. If you're interested in implementing, please say so and we'll prioritize the review. 

You get **10** votes in the feature idea forum, and each one influences the future of the project.

**Comment by zsalab** [comment]
https://mattermost.uservoice.com/forums/306457-general/suggestions/36982153-show-number-of-flagged-message-on-the-top-right-co

**Comment by amyblais** [comment]
Awesome, thank you!
