### ISSUE TITLE
Win7 x64: v1.1.0 release candidate shows 1.0.7 as version under File > About

### ISSUE THREAD

**Issue by it33** [mattermost/desktop#94]
Expected: Shows "Mattermost Desktop 1.1.0"

![image](https://cloud.githubusercontent.com/assets/177788/13987487/06e3d6d8-f0c5-11e5-8158-f6e9584b8470.png)

v1.1.0-rc1: https://github.com/mattermost/desktop/pull/92

**Comment by it33** [comment]
@yuya-oc, I'm wondering if it might make sense to include the build number in the version, or below? 

For example: Mattermost Desktop 1.1.0.1511 ? 

Alternatively could go below, like: 

---

Mattermost Desktop 1.1.0

Build: 1511

----

0/5, just a thought.

**Comment by yuya-oc** [comment]
It's my mistake and the issue was already fixed at e3130e4c77a8463040400885261e03b7c0670b59.

As you said, the build number is nice to know the actual package. For now, we have to use CircleCI's build number to realize that.

**Comment by it33** [comment]
Thanks @yuya-oc!
