### ISSUE TITLE
No system proxy detection on MacOS

### ISSUE THREAD

**Issue by guillaumesamson** [mattermost/desktop#942]
On MacOS 10.13.6 with Mattermost 4.2.0, system proxy settings are not taken into account when using "auto proxy discovery" option in MacOS network settings. Not sure if it's a bug or if I am doing something wrong.
I could use the `--proxy-pac-url=<URL> option`, but I would prefer to use directly system settings.
Thanks.

Guillaume

**Comment by amyblais** [comment]
Opened a ticket here for tracking: https://mattermost.atlassian.net/browse/MM-14462.

**Comment by esethna** [comment]
@yuya-oc any thoughts on this?

**Comment by amyblais** [comment]
Hi @guillaumesamson, do you know if this applies only to macOS? Does it work on Windows/Linux?

**Comment by lieut-data** [comment]
Hi @guillaumesamson. I setup Squid (via SquidMan) on OSX, and manually configured the `Web Proxy` and `Secure Web Proxy` accordingly. I confirmed that the desktop app connects through the proxy successfully, and when the proxy is stopped, it fails with `ERR_PROXY_CONNECTION_FAILED`.

It seems that the desktop app honours the system proxy settings. If the `Auto Proxy Discovery` is not working for you, I'm inclined to think it's a setup issue. If you can provide additional details on what's going wrong in your case and how the desktop app is at fault, we'd be happy to help investigate further!
