### ISSUE TITLE
Default build results in a windows install much larger than the install provided by Mattermost.

### ISSUE THREAD

**Issue by derekyle** [mattermost/desktop#947]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

**Environment**
- Operating System: Windows 10.
- Mattermost Desktop App version: 4.3.0 
- Mattermost Server version: X.X.X N/A

**Steps to reproduce**
Build the project using the included, default circleci build file.

**Expected behavior**
Get a build similar to to the Mattermost desktop app for windows. Are there large differences from a default build and the install binary that Mattermost provides? One would think that we would want the two to be somewhat similar.

**Observed behavior**
The mattermost install takes 66mb but the default build when built from source takes up more than 500mb.

**Possible fixes**
Perhaps there are some build defaults that can be changed or at least point out to avoid a bloated install?

**Comment by yuya-oc** [comment]
Hi @derekyle, thanks for reporting.

The master branch (v4.3) changed (and will change) the installer format from v4.2. So perhaps there are some problem in our new build process. Would you provide more detailed report for helping us?

**Comment by derekyle** [comment]
I don't have any additional log details at the moment. I'll try to get
those. But I see that the largest file is app.asar which is 121 MB. The
actual .exe binary is about 100mb.

**Comment by amyblais** [comment]
Hi @derekyle, have you seen this issue still and do you have any additional logs? If you've still seen this, I can create a ticket to get devs to look at this.

**Comment by devinbinnie** [comment]
Closing as inactive
