### ISSUE TITLE
Multiple teams only logs in with one team

### ISSUE THREAD

**Issue by xmakina** [mattermost/desktop#95]
Using mattermost-dev for a server
Set up a team (example.com/foo)
Set up a second team (eaxmple.com/bar)
Register for both with the same email (but different passwords)
Add both teams to the desktop app
Save
Log in under Foo

Expected: Be able to log into Bar and use independently
Issue: Bar tab also shows being logged into Foo team. The Bar tab shows the Foo login.

This can also be reproduced in Chrome by having multiple tabs open, one on example.com/foo and another on example.com/bar and logging in with one will cause the other to log in to the same team.

**Comment by yuya-oc** [comment]
Could you write the Mattermost server version?
In my memory, I met the problem on older Mattermost server and maybe it was changed in 1.1~1.3.

Tabs share same session as same as tabs of web browsers. As you wrote, it's also reproduced on Chrome. Could you check issues for `mattermost/platform`?

**Comment by alexmnguyen** [comment]
I'm also running into a similar issue. Steps:

1. New install of mattermost on Ubuntu 15.10 using the following link:

http://docs.mattermost.com/install/docker-local-machine.html#one-line-docker-install

2. Create two teams, team1 then team2 using the same email address, 

3. It seems the only team that exists after that is team2, as far as the label on the top left. If I try to manually access the team1 or any random url, the team name display is still team2. 

4. If I try to create a new team url with the default team1 url, it gives me this error:
```
This URL is unavailable. Please try another.
``` 

The information from the `About Mattermost` dialog is:
```
Mattermost Team Edition T0

Version:2.1.0
Build Number:6562
Build Date:Thu Mar 17 16:17:34 UTC 2016
Build Hash:2cd006474ec8a808b2ea2b0502a842f44cb0b127
```

**Comment by yuya-oc** [comment]
If it is reproduced on web browsers(Chrome), please consider to open an issue at `mattermost/platform`.
