### ISSUE TITLE
Muted channel stays in "selected" state after navigating away

### ISSUE THREAD

**Issue by matthewbryancurtis** [mattermost/desktop#951]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Selecting a muted channel and then selecting a different channel causes muted channel to show as selected in navigation.

**Environment**
- Operating System: macOS Mojave
- Mattermost Desktop App version: 3.7.1
- Mattermost Server version: 5.9.0

**Steps to reproduce**

1. Mute a channel (in this example it's Town Square)
![Screen Shot 2019-03-19 at 1 39 44 PM](https://user-images.githubusercontent.com/16308368/54632610-83294280-4a4c-11e9-919c-9913fd3757f1.png)
2. Select muted channel
![Screen Shot 2019-03-19 at 1 40 33 PM](https://user-images.githubusercontent.com/16308368/54632656-9805d600-4a4c-11e9-8189-4aed08e0a6ac.png)
3. Navigate to different channel
<img width="220" alt="Screen Shot 2019-03-19 at 1 41 18 PM" src="https://user-images.githubusercontent.com/16308368/54632702-b370e100-4a4c-11e9-8e40-81349276cfb2.png">

**Expected behavior**

When navigating away from a muted channel, the muted channel should go back to the "disabled" state rather than the "selected" state.

**Observed behavior**

When navigating away from a muted channel, the muted channel stays in the selected state.

**Possible fixes**

I'm not sure if this is an issue with Mattermost or with Electron. The reason I mention this is that this behavior doesn't happen in Chrome, but **also only happens in specific desktops.** By desktops, I mean that in macOS the user can create multiple virtual "desktops" to spread out applications. I can only reproduce when Mattermost is in Desktop 1 of these virtual desktops.

**Comment by amyblais** [comment]
Hi @matthewbryancurtis,

Would you be open to upgrading to the latest desktop app version (v4.2) to see if you still experience the issue?

**Comment by matthewbryancurtis** [comment]
Ah, yes. 😊That fixed the issue, thank you!
