### ISSUE TITLE
 Download page links to old gitlab-tag for Linux v4.1.2

### ISSUE THREAD

**Issue by NeroBurner** [mattermost/desktop#955]
- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [ ] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

Download page https://mattermost.com/download/#mattermostApps links to old gitlab-tag for Linux 

The `More Options` link on the download page links to https://github.com/mattermost/desktop/releases/tag/v4.1.2 instead of https://github.com/mattermost/desktop/releases/tag/v4.2.1

**Comment by wget** [comment]
@NeroBurner Indeed. I can reproduce.
![Screenshot_20190325_121436](https://user-images.githubusercontent.com/2997662/54915552-b01ba080-4ef7-11e9-83c9-47b05a88dba2.png)

**Comment by amyblais** [comment]
Thank you, I'll forward this to the marketing team for fixing.

**Comment by NeroBurner** [comment]
the link still leads to the wrong version. Is this issue planned to be fixed in the `v4.2.1` cycle or later when the next version `v4.3.0` comes out

**Comment by amyblais** [comment]
Nudged the marketing team again and this is now fixed.
