### ISSUE TITLE
Cannot change font family

### ISSUE THREAD

**Issue by dongtanhuy** [mattermost/desktop#958]
Hello Mattermost team,
I want to custom font family for the whole desktop app. So I add my font in `src/browsers/fonts` and updated  `src/browser/css/index.css` below
```
body {
  font-family: 'Lato'
}
...
@font-face {
  font-family: 'Lato';
  font-style: normal;
  font-weight: 400;
  src: url('../fonts/Lato-Semibold.ttf');
}
@font-face {
  font-family: 'Lato';
  font-style: normal;
  font-weight: 400;
  src: url('../fonts/Lato-SemiboldItalic.ttf');
}
```
**Note:** I choose Lato font to customize my Mattermost Desktop app.
I ran command to build and release into Mac app. It ran successfully but the Lato font was not applied in my app.
How can I change the font family of the app?
Thanks

**Comment by amyblais** [comment]
Hi @dongtanhuy,

Just to confirm, did you follow all the guides for customizing the desktop app?
 - https://docs.mattermost.com/deployment/customize-mattermost.html#mattermost-desktop-applications
 - https://github.com/mattermost/desktop/blob/master/docs/development.md

We removed support for changing fonts in server v4.0 release (https://forum.mattermost.org/t/removing-font-setting/3367) so I'm not sure if the fonts itself can be changed.

**Comment by amyblais** [comment]
Hi @dongtanhuy, I'll close this issue for now as there hasn't been updates on this for a while, please re-open this issue if you have any further questions.

**Comment by xnox** [comment]
@amyblais removing general font setting is fine, but we need to use our corporate font for our corporate deployment of mattermost.

Do custom themes allow providing / using webfonts, irrespective of what the default settings are? Cause ideally, together with corporate CSS we should be able to override the fonts to use too.

**Comment by palikacska** [comment]
Shame on you @amyblais for removing customization options. This is the very wrong direction you should not be heading.

**Comment by ghorbani-ali** [comment]
im using arch linux with cinnemon desktop
i just do little changes in desktop entery file
at first make ~/.fonts.conf file
then put this xml code inside file
`<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
    <match target="pattern">
        <test name="family" qual="any">
            <string>sans serif</string>
        </test>
        <edit mode="assign" binding="same" name="family">
            <string>Vazir</string>
        </edit>
    </match>
    <dir>~/.fonts</dir>
    <dir>.local/share/fonts</dir>
</fontconfig>` 
then edit desktop entry file inside /usr/share/applications and put this code
`Exec=env FONTCONFIG_FILE=~/.fonts.conf mattermost-desktop %U`
i just pass font config file as environment variable
dont forget copy font files inside ~/.fonts or .local/share/fonts directory
then finish 🤩

**Comment by nachtvlinder** [comment]
> Hi @dongtanhuy,
> 
> Just to confirm, did you follow all the guides for customizing the desktop app?
> 
>     * https://docs.mattermost.com/deployment/customize-mattermost.html#mattermost-desktop-applications
> 
>     * https://github.com/mattermost/desktop/blob/master/docs/development.md
> 
> 
> We removed support for changing fonts in server v4.0 release (https://forum.mattermost.org/t/removing-font-setting/3367) so I'm not sure if the fonts itself can be changed.

This not being able to change font situation is affecting accessibility. I wanted to change it to be better able to read it. :'(

**Comment by devinbinnie** [comment]
@nachtvlinder This is something currently supported by most browsers (Chrome does this in Settings > Appearance > Customize fonts) but not currently the Desktop App.

If this is affecting accessibility we could look into implementing something similar for Desktop App.

**Comment by boboTjones** [comment]
I found this issue when I was trying to figure out how to override the default font in the Mattermost desktop app (duh) with Dyslexie or OpenDyslexic. Slack (sorry; don't hate me) allows me to override the fonts in its desktop app using the /slackfont command. If I use Mattermost in the browser, I have a small snippet of code that allows me to override most fonts on most sites with Dyslexie, but what I'm reading here suggests that this accessibility support does not appear to be available for the desktop app? If you're looking for a reason to make this an option, now you have one. Thanks!

**Comment by da-mask** [comment]
This is pretty terrible. I'm not a slack fan, but at least they have this ability.  Really bad a11y for mine. I don't want to start a campaign at my company to switch over, but I will have to. No discussion from the mattermost team .. ?
