### ISSUE TITLE
App is non-functional on Ubuntu

### ISSUE THREAD

**Issue by orf** [mattermost/desktop#96]
Hey, I've downloaded the client and attempted to run it, but nothing displays. I've attached a screenshot including a JS error that might be the cause.

![screenshot from 2016-03-24 09-16-29](https://cloud.githubusercontent.com/assets/1027207/14012918/050cccd4-f1a1-11e5-84a4-3755a3d1c5ea.png)

**Comment by yuya-oc** [comment]
The error is not related to this issue. I think that the application failed connection with Mattermost server like #26. Perhaps, v1.0.0 will help that.

**Comment by orf** [comment]
Yep, the fix in #26 worked great thanks.
