### ISSUE TITLE
A tooltip titled 'Dropdown Icon' is shown upon hovering the caret down icon next to a channel name

### ISSUE THREAD

**Issue by m-mansoor-ali** [mattermost/desktop#963]
A tooltip titled 'Dropdown Icon' is shown upon hovering the caret down icon next to a channel name.

![image](https://user-images.githubusercontent.com/31011652/56484653-20631500-64ea-11e9-92a3-96c6d1402ef9.png)

**Comment by esethna** [comment]
Thanks, bug filed on this: https://mattermost.atlassian.net/browse/MM-15236

**Comment by amyblais** [comment]
This has been fixed in server v5.11 release,
