### ISSUE TITLE
HTTP basic authentication dialog not passing username and password

### ISSUE THREAD

**Issue by MikeNicholls** [mattermost/desktop#965]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Attempting to use an HTTP proxy which requires basic authentication fails. From investigating with developer tools, it appears that the username and password are being passed as `undefined` into the LoginModal onLogin function.

**Environment**
- Operating System: macOS
- Mattermost Desktop App version: 4.2.1
- Mattermost Server version: 5.9.0

**Steps to reproduce**
1. Configure an HTTP proxy which requires basic authentication
2. Open the desktop app and try to connect to a server through the proxy
3. Enter username and password when the proxy authentication dialog appears

**Expected behavior**
Authentication succeeds, Mattermost loads

**Observed behavior**
Authentication dialog disappears, "Cannot connect to Mattermost" screen is displayed with ERR_TUNNEL_CONNECTION_FAILED (-111)

**Possible fixes**
Possible regression from 5091f59

**Comment by pisymbol** [comment]
When can I test this on OSX?

**Comment by pisymbol** [comment]
Not to be impatient, but when we will see this fix? It's a show stopper for anyone on a network with a challenge based proxy server.
