### ISSUE TITLE
"Remember me" tickbox when logging in has no effect

### ISSUE THREAD

**Issue by mpetitjean** [mattermost/desktop#967]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

Even when the "Remember me" checkbox is ticked, I have to re-enter my credentials at each startup of the application.

**Environment**
- Operating System: Arch Linux 
- Mattermost Desktop App version: 4.2.1 
- Mattermost Server version: 5.9.0 

**Steps to reproduce**

- Launch the application
- Log in Mattermost using GitLab credentials
- Tick the "Remember me" box
- Close the running instance of Mattermost Desktop
- Launch the application again

**Expected behavior**

It is expected that your credentials are saved and that you are automatically logged in.

**Observed behavior**

I am prompted to log in again.

**Comment by svelle** [comment]
Hey @mpetitjean,
can you try the steps outlined in the desktop client troubleshooting here: https://docs.mattermost.com/install/desktop.html#desktop-app-constantly-asks-to-log-in-to-mattermost-server

Please report back if this fixed your issue or not.

Thanks!

**Comment by mpetitjean** [comment]
This indeed fixed the issue. Sorry about opening an issue about a known behavior and thanks for the help !

**Comment by svelle** [comment]
Absolutely no problem!
