### ISSUE TITLE
Win64 Desktop v1.1.0-rc2 on Win7: Entering invalid team URL puts desktop app in unrecoverable state

### ISSUE THREAD

**Issue by it33** [mattermost/desktop#97]
Repro: 

1. Create a valid team and login, 
2. Go to File > Settings and create a team with Name = Invalid, URL = https://badurl
3. Click Add
4, Click Save

Expected: 

- Settings saved and when Team UI reappears on the "Invalid" tab there is a message like "No team site could be found at https://badurl"

Observed: 

- Pressing "Save" has no response, pressing "Cancel" has no response. Only way to recover is to quit app.

**Comment by yuya-oc** [comment]
In my thoughts, the URL is not related because the Settings UI just handles URL as a string. It looks as same as #89, but I can't reproduce it on Windows 10 and OS X.
