### ISSUE TITLE
Electron 4.0 breaking change

### ISSUE THREAD

**Issue by fraviemor** [mattermost/desktop#970]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Electron 3.X alerts with this message:

> (electron) 'app.makeSingleInstance(cb)' is deprecated. Use 'app.requestSingleInstanceLock() and app.on('second-instance', cb)' instead

When I updated to Electron 4.X and tried to start Mattermost, an error ocurred. Its a breaking change.

**Environment**
- Operating System: ArchLinux
- Mattermost Desktop App version: 4.2.0 
- Mattermost Server version: 5.7.1 

**Steps to reproduce**

1. Start mattermost-desktop.

**Expected behavior**

Mattermost starts without errors.

**Observed behavior**

Mattermost doesn't load and terminal shows this error:

> App threw an error during load
> TypeError: app.makeSingleInstance is not a function
>     at Module.<anonymous> (/usr/lib/mattermost-desktop/app.asar/main_bundle.js:302:9)
>     at __webpack_require__ (/usr/lib/mattermost-desktop/app.asar/main_bundle.js:20:30)
>     at /usr/lib/mattermost-desktop/app.asar/main_bundle.js:84:18
>     at Object.<anonymous> (/usr/lib/mattermost-desktop/app.asar/main_bundle.js:87:10)
>     at Object.<anonymous> (/usr/lib/mattermost-desktop/app.asar/main_bundle.js:16670:3)
>     at Module._compile (internal/modules/cjs/loader.js:693:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
>     at Module.load (internal/modules/cjs/loader.js:602:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:533:3)
> /usr/lib/mattermost-desktop/app.asar/main_bundle.js:12225
>     throw err;

**Possible fixes**

Fix breaking changes: https://github.com/electron/electron/blob/master/docs/api/breaking-changes.md#appmakesingleinstance

Workaround: downgrade Electron to 3.X version.

**Comment by svelle** [comment]
Hi @fraviemor,
are you building the desktop app yourself or are you using a pre-built binary from our releases page?
There is a bug in the release-4.2 branch currently that's hindering from building, but I've already have a PR open to fix this.  
It's because of an outdated webpack version. It's already fixed in the master branch but that change hasn't been ported back to the release-4.2 branch yet.

**Comment by skewty** [comment]
Any idea when a release against a newer version of Electron will be released?
Bugs like #317 and #899 are serious usability issues and seem to require a less bugged version of Electron.

**Comment by yuya-oc** [comment]
I believe the master branch is adapted to this breaking change. If you wish to build the desktop app from v4.2 source code with Electron v4, probably you can use this patch: https://github.com/mattermost/desktop/commit/40257cf93e153a84a94f888aea3225788fbb9d3a

**Comment by alerque** [comment]
This issue is probably obsolete. Electron 6 is the current specified dependency!
