### ISSUE TITLE
Mattermost desktop hammers hard drive with write on each key stroke

### ISSUE THREAD

**Issue by aeris** [mattermost/desktop#977]
I confirm (by marking "x" in the [ ] below: [x]):

- [X] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [X] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [X] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**

This is due to write on `~/.config/Mattermost/IndexedDB/<url>_0.indexeddb.leveldb/<xxxx>.log`, written on each key stroke on the message input, even if you don't submit your message.
Inputing a X characters long message hammers the hard drive with X writes.

**Environment**
- Operating System: Arch Linux amd64
- Mattermost Desktop App version: 4.2.1
- Mattermost Server version: 5.10.0

**Steps to reproduce**

`strace -yy -f mattermost-desktop |& grep write | grep Index`

**Expected behavior**

No output when inputing a message without submitting it

**Observed behavior**

Write output on each key stroke

![2019-05-20_10-08](https://user-images.githubusercontent.com/51246/58006773-1c2a1780-7ae9-11e9-9447-6c7ac5201e91.png)
![2019-05-20_10-11](https://user-images.githubusercontent.com/51246/58006779-1df3db00-7ae9-11e9-89cb-b26afa2034c1.png)

**Comment by amyblais** [comment]
Opened a ticket for this here: https://mattermost.atlassian.net/browse/MM-15735.

**Comment by amyblais** [comment]
Do we know if this is causing side effects? The reason this happens is because the draft is being saved on every keystroke.

**Comment by lkraav** [comment]
The obvious thing to do is throttling the save / flush operation to every X keystrokes, minimum, no?

Daily driving crash risk looks low enough across the board, why do we need to save every keystroke?

**Comment by wget** [comment]
@aeris Do you know a way to display the items like you have in the second screenshot?
When I try to display the log, this is basically binary garbage.
Tested with the community server:
```
~/.config/Mattermost/IndexedDB/https_community.mattermost.com_0.indexeddb.leveldb/000010.log
```
I'm running on Arch Linux as well with the latest 4.3.1 I published just now.

**Comment by aeris** [comment]
Documented on the first post : `strace -yy -f mattermost-desktop |& grep write | grep Index`

**Comment by wget** [comment]
@aeris Yes, this is the command I used, but the latter is giving me garbage (non printage chars and without new lines). Could you check again from your side?

**Comment by aeris** [comment]
Got garbage now too :thinking:

**Comment by amyblais** [comment]
Are you still experiencing this issue on desktop v4.4.0?

**Comment by aeris** [comment]
Yep, still write hammering in `/home/aeris/.config/Mattermost/IndexedDB/https_mattermost.example.org_0.indexeddb.leveldb/000462.log`

Here strace output when inputing `test` on the input field (without sending it). 2 entries per characters.

```
[pid 150209] write(129</home/aeris/.config/Mattermost/IndexedDB/https_mattermost.example.org_0.indexeddb.leveldb/000462.log>, "\343\305\303Yq\1\1", 7 <unfinished ...>
[pid 150209] write(129</home/aeris/.config/Mattermost/IndexedDB/https_mattermost.example.org_0.indexeddb.leveldb/000462.log>, "\323\224-\0\0\0\0\0\3\0\0\0\1\7\0\1\0\0002\1\4\3\216.\17\1p\0\1\1\1\1"..., 369 <unfinished ...>
[pid 150209] write(129</home/aeris/.config/Mattermost/IndexedDB/https_mattermost.example.org_0.indexeddb.leveldb/000462.log>, "\2322\26\34r\1\1", 7) = 7
[pid 150209] write(129</home/aeris/.config/Mattermost/IndexedDB/https_mattermost.example.org_0.indexeddb.leveldb/000462.log>, "\326\224-\0\0\0\0\0\3\0\0\0\1\7\0\1\0\0002\1\4\3\217.\17\1p\0\1\1\1\1"..., 370) = 370
[pid 150209] write(129</home/aeris/.config/Mattermost/IndexedDB/https_mattermost.example.org_0.indexeddb.leveldb/000462.log>, "\302\260\3415s\1\1", 7 <unfinished ...>
[pid 150209] write(129</home/aeris/.config/Mattermost/IndexedDB/https_mattermost.example.org_0.indexeddb.leveldb/000462.log>, "\331\224-\0\0\0\0\0\3\0\0\0\1\7\0\1\0\0002\1\4\3\220.\17\1p\0\1\1\1\1"..., 371 <unfinished ...>
[pid 150209] write(129</home/aeris/.config/Mattermost/IndexedDB/https_mattermost.example.org_0.indexeddb.leveldb/000462.log>, "\244\245\2377t\1\1", 7 <unfinished ...>
[pid 150209] write(129</home/aeris/.config/Mattermost/IndexedDB/https_mattermost.example.org_0.indexeddb.leveldb/000462.log>, "\334\224-\0\0\0\0\0\3\0\0\0\1\7\0\1\0\0002\1\4\3\221.\17\1p\0\1\1\1\1"..., 372) = 372
```

**Comment by devinbinnie** [comment]
Closing as flushing drafts to the hard disk (or the browser store) is now throttled which reduces the disk thrashing.
If we're still seeing this, feel free to re-open.
