### ISSUE TITLE
Win64 Desktop v1.1.0-rc2 on Win7: Icon in top left of Windows Desktop app seems blurry. 

### ISSUE THREAD

**Issue by it33** [mattermost/desktop#98]
![image](https://cloud.githubusercontent.com/assets/177788/14034559/85c20c8c-f1e1-11e5-89c9-c757ef734a5e.png)

**Comment by yuya-oc** [comment]
It seems that it's a side effect of 7e7109413307336af211c4d19bbb4a280a470644. I think a too high resolution image is assigned, and v1.0.7 is same.

**Comment by yuya-oc** [comment]
Reopen to track this. It's a side effect by fixing #192.

**Comment by yuya-oc** [comment]
Closed by a0453b5. Thanks @asaadmahmood for preparing icons!
