### ISSUE TITLE
Cannot hide from task bar

### ISSUE THREAD

**Issue by Yournished** [mattermost/desktop#980]
I am using Mattermost Desktop v4.2.1 from https://aur.archlinux.org/packages/mattermost-desktop/ with Manjaro and Cinnamon as my DE.

Running the program produces a tray icon as well as the program showing up in my task bar, where it creates needless clutter. When I minimize or close the Mattermost window, it does not hide to tray but instead gets minimized so that the tray icon and the taskbar item both remain. I could not find any setting that changes this behavior.

Could you please make Mattermost minimize to tray (hide task bar item) when close is clicked, as is common with many similar apps?

**Comment by amyblais** [comment]
Hi @Yournished, would you like to upvote this feature request: https://mattermost.uservoice.com/forums/306457-general/suggestions/36819994-desktop-app-minimize-to-tray-when-clicking-on-the? If it doesn't quite describe what you're looking for, please feel free to open a new feature request or let me know if I can help open one.

**Comment by Yournished** [comment]
@amyblais That seems to be the same as what I'm asking, but I would not like to upvote it because it looks like making an account will be a gigantic pain.

**Comment by amyblais** [comment]
Hi @Yournished, no worries, I just added an upvote on it on your behalf. I'll close this issue here for now so that we can follow this request on the forum,

**Comment by globalqss** [comment]
Hi @amyblais - I think what @Yournished is reporting is different than the request you're pointing to.

I just upgraded my ubuntu to 20.04 and installed mattermost desktop 4.4.2 - and the behavior described by @Yournished appeared.

The thing is - even when I close the desktop application, the icon on my sidebar doesn't hide, and now I have two permanent mattermost icons in my screen - the icon at the sidebar, and the icon at the systray.

The key here is *closing* the window doesn't hide the sidebar - AFAIK it was working fine in ubuntu 18.04

In the meantime I'm considering to move to the browser version of mattermost.

Question, is it possible to reopen this?   Or must I open a new one?

Regards,

Carlos Ruiz

**Comment by Willyfrog** [comment]
@globalqss is this stock gnome? or using a different DE? I can't see this happening on either unity or gnome.

**Comment by globalqss** [comment]
Thanks @Willyfrog - this is stock ubuntu 20.04 freshly installed (not upgraded).

It seems by default gnome is installed using snap:

```
$ snap list
Nombre             Versión             Rev   Seguimiento      Editor      Notas
core               16-2.44.3           9066  latest/stable    canonical✓  core
core18             20200427            1754  latest/stable    canonical✓  base
gnome-3-34-1804    0+git.3009fc7       33    latest/stable/…  canonical✓  -
gtk-common-themes  0.1-36-gc75f853     1506  latest/stable/…  canonical✓  -
snap-store         3.36.0-80-g208fd61  454   latest/stable/…  canonical✓  -
snapd              2.44.3              7264  latest/stable    canonical✓  snapd

```

Regards,

Carlos Ruiz

**Comment by globalqss** [comment]
Hello, I gave a second try to the desktop app in my ubuntu 20.04 and found a solution for this:

*

**Comment by cryoff** [comment]
@globalqss thank you for the hint!
However on my Ubuntu 18.04 +XFCE after taking the same actions I have tray icon and taskbar icon. Still have no idea how to hide it from taskbar

**Comment by devinbinnie** [comment]
Closing as inactive. We have an open JIRA ticket to deal with Linux window behaviour that will address this.
