### ISSUE TITLE
Unread message notifier in launcher icon in Linux

### ISSUE THREAD

**Issue by yannikschaelte** [mattermost/desktop#982]
On Ubuntu 19.04, the mattermost desktop client does not indicate unread messages in the launcher (I mean adding a little pop-up symbol to the icon as shown in this post about Windows https://github.com/mattermost/desktop/issues/194).

I don't know if that is intended (no comparison on other systems). For thunderbird a similar thing exists, but I wouldn't know how to implement right away. I suggest a permanent "red dot" indicating new messages, not a counter.

**Comment by amyblais** [comment]
Hi @yannikschaelte, thank you for the feedback, would you be open to adding this suggestion to our feature request forum here: https://mattermost.uservoice.com/forums/306457-general?

**Comment by yannikschaelte** [comment]
Done

**Comment by amyblais** [comment]
Thank you!

Attaching it here for reference: https://mattermost.uservoice.com/forums/306457-general/suggestions/37766611-unread-message-notifier-in-launcher-icon-in-linux.
