### ISSUE TITLE
Cannot type a closing brace with Spanish keyboard layout

### ISSUE THREAD

**Issue by gigaherz** [mattermost/desktop#984]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Using Spanish keyboard layout, it is impossible to type a `}` symbol, because when pressing `AltGr+Ç`, it opens the "keyboard shortcuts" window instead of typing. This behaviour is not observed in Chrome or Firefox.

**Environment**
- Operating System: Windows 10 version 1809 (17763.503)
- Mattermost Desktop App version: ~~4.1.2~~ 4.2.1 (updated while writing the report, still happens)
- Mattermost Server version: 5.10.0

**Steps to reproduce**
Using Spanish keyboard layout, try to type a closing brace `}` by pressing `AltGr+Ç`.

**Expected behavior**
A closing brace is typed.

**Observed behavior**
The "Keyboard Shortcuts" popup opens instead.

**Possible fixes**
🤷‍♂

**Comment by svelle** [comment]
Hi @gigaherz,
can you please let us know what OS you are running the app on?
This way we can try to reproduce the bug on our end and try to find a fix for it.

**Comment by gigaherz** [comment]
Oh I completely forgot to mention that, didn't I... 🤦‍♂ 
Windows 10 version 1809 (17763.503)

The OS language is set to English (UK), but the keyboard layout is set to "Spanish".

**Comment by amyblais** [comment]
@svelle Have you been able to reproduce this?

**Comment by devinbinnie** [comment]
Closing as inactive.
