### ISSUE TITLE
Loading screen should respect theme preference

### ISSUE THREAD

**Issue by ryliejamesthomas** [mattermost/desktop#985]
Hi!

At the moment, no matter which theme you have selected (dark, light), the startup / loading screen is white with blue logo.

My eyes adapt slowly to such strong shifts in brightness, and I would love it if would respect my preferences and be dark if a dark theme was selected.

**Comment by amyblais** [comment]
Hi @ryliejamesthomas, this is a good idea, would you be open to sharing this idea on our feature request forum here: https://mattermost.uservoice.com/forums/306457-general?

**Comment by ryliejamesthomas** [comment]
Thanks @amyblais , I've done that now:

https://mattermost.uservoice.com/forums/306457-general/suggestions/37839610-make-the-loading-screen-match-the-user-s-theme-col
