### ISSUE TITLE
Add yum install repo

### ISSUE THREAD

**Issue by iced-duck** [mattermost/desktop#986]
I wander whether mattermost has some repo which we can used to be convinently installed in our centos linux?
Just like execute "yum install mattermost" can install all the requirments for the mattermost desktop version?

**Comment by valentinbajrami** [comment]
@duckzhouya I've packaged mattermost-desktop as rpm which does everything for you but it seems it's not yet available on the official website.

**Comment by 2019-05-10** [comment]
I second that, for 
Debian 
based distributions, though.
Having a repo 
a) is how sensible software management is done in Linux
b) ensures that dependencies are resolved upon installation
c) ensures that updates are installed whenever they are available, not just when I happen to remember to check  a web site

**Comment by valentinbajrami** [comment]
@2019-05-10  and @duckzhouya  you can now install mattermost-desktop client using: 
`dnf copr enable valentinb/mattermost ; dnf install mattermost-desktop`

**Comment by 2019-05-10** [comment]
a) what is `dnf`?
b) my comment was asking for a Debian repo, since deb packages are being built already

**Comment by valentinbajrami** [comment]
`dnf` is a package manager for RHEL based systems so ignore the above.

**Comment by duckzhouya** [comment]
Thanks for your kindly help. @valentinbajrami 
I have tried several times, but the package download speed is really slow, maybe I need to try another time while the network is stable.
I will let you know the result if I have installed the package successfully.

**Comment by duckzhouya** [comment]
I have installed the package successfully,
Thank you for your help. @valentinbajrami

**Comment by valentinbajrami** [comment]
Glad I could help and thank you for your feedback @duckzhouya

**Comment by holle** [comment]
The community at openSUSE created RPMs for:

* openSuSE
* Fedora 32
* CentOS/RHEL 8

available at: https://software.opensuse.org/package/mattermost-desktop (you may have to follow the "manual" instructions)

**Comment by devinbinnie** [comment]
Closing as these repos are maintain by their owners. Happy to help any of them get a build up and running for their specific package distribution method if need be.
