### ISSUE TITLE
Win64 Desktop v1.1.0-rc2 on Win7: Tray icon for Windows Desktop app seems blurry

### ISSUE THREAD

**Issue by it33** [mattermost/desktop#99]
See icon in bottom right: 

![image](https://cloud.githubusercontent.com/assets/177788/14034588/df7c7078-f1e1-11e5-942a-4c15a2d35605.png)

**Comment by kethinov** [comment]
How could you possibly refuse that free upgrade to Windows 10 in the bottom left corner? It's such awesomesauce! :wink:

**Comment by yuya-oc** [comment]
Duplicate of #66. @2x icons are not prepared yet.

**Comment by it33** [comment]
Cool, thanks!
