### ISSUE TITLE
mattermost-desktop lagging Gnome 3.32.1 when selecting show icon in notification area

### ISSUE THREAD

**Issue by mexin** [mattermost/desktop#991]
I confirm (by marking "x" in the [ ] below: [x]):

- [x] This is not a troubleshooting question. [Troubleshooting questions go here: http://www.mattermost.org/troubleshoot/](http://www.mattermost.org/troubleshoot/).
- [x] This doesn't reproduce on web browsers (such as in Chrome). If it does, [issue reports go to the Mattermost Server repository](https://github.com/mattermost/platform/issues).
- [x] I have read [contributing guidelines](https://github.com/mattermost/desktop/blob/master/CONTRIBUTING.md).

---

**Summary**
Mattermost slowing system down when opening, if "Show icon in the notification area" is turned on

**Environment**
- Operating System: Linux Pop_OS! 19.04, Gnome 3.32.1
- Mattermost Desktop App version: 4.2.1
- Mattermost Server version:  5.9.0

**Steps to reproduce**
Open Mattermost Desktop app with "Show icon in the notification area" turned on

**Expected behavior**
System running without any lag

**Observed behavior**
Every time when opening mattermost system gets laggy

**Possible fixes**
Disabling "Show icon in the notification area" seems to get rid of the lag

**Comment by amyblais** [comment]
Hi @mexin, do you see any Mattermost log errors or Console errors when this happens?

**Comment by mexin** [comment]
@amyblais I invoked it on the terminal and no log errors there also checked the chrome console within and no error logs as well.

**Comment by amyblais** [comment]
Ticket for reference: https://mattermost.atlassian.net/browse/MM-16547.

**Comment by amyblais** [comment]
Does this still happen on desktop v4.3.1?

**Comment by esethna** [comment]
@mexin would you be able to help us confim if this still happens on v4.3.2: https://mattermost.com/download/#mattermostApps

**Comment by amyblais** [comment]
I'll close this for now as we haven't received feedback on this for a while, please let us know if the issue persists,
