### ISSUE TITLE
Next release for this project?

### ISSUE THREAD

**Issue by humbled** [mattermost/desktop#992]
Apologies for raising the issue, but is there a published released timeline for this project? I've looked and haven't found one. We're reliant on a fix that's been merged and don't know when we can expect it.

Thanks

**Comment by StackKorora** [comment]
I'm just a user, but I've been watching their milestone release info:
https://github.com/mattermost/desktop/milestone/11

But I agree. I've got two very annoying bugs that are already fixed that I've been waiting months on. I'm very excited for the next release. :-)

**Comment by deanwhillier** [comment]
Apologies for the delayed response on this. We are currently working on developing a release timeline for this project moving forward similar to our primary mobile, webapp and server projects. The release schedule likely won't be as often to begin with, but should provide for more consistent, reliable and timelier releases!

That said, the v4.3.0 release version is imminent! Thanks for your patience!
